### PR TITLE
Update codegen related code to be merged into master

### PR DESCRIPTION
**Pull request by a7ehuo**
Update `codegen` related files to be merged into `master`. 

The mirrored change on the `master` branch is in PR #7358. 

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaas

**Comment by ymanton** [comment]
> Clearly these two methods are needed for JITServer and the check for `isOutOfProcessCompilation()` makes sense. However, I don't understand the check for `compileRelocatableCode()`. If we want to do this for AOT, why do we do it only when JITServer support is enabled? Maybe @ymanton would know

The same code exists in `OMR::CodeGenerator::addExternalRelocation()` without the `isOutOfProcessCompilation()` check. We extended the functions in OpenJ9 so we could add the JITServer check. The extensions are not needed for current master so we don't have to build it, but once we get rid of the `JITSERVER_SUPPORT` guard these functions will have to handle both AOT and JITServer.

We could let the extension get built on master by default and just guard the `isOutOfProcessCompilation()` check, but the result is more or less the same.

**Comment by mpirvu** [comment]
> We extended the functions in OpenJ9 so we could add the JITServer check

I understand now. Ideally we would have a definition for `comp()->isOutOfProcessCompilation()` at the OMR level and use it there without any extension, but that's another change for another day.

**Comment by mpirvu** [comment]
Java 11 failures


```
cmdLineTester_jvmtitests_debug_7
```
Testing: rc016
Test start time: 2019/10/17 14:19:56 Atlantic Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -Xcompressedrefs -XX:+UseCompressedOops -Xgcpolicy:balanced -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:count=0  -Xdump    -agentlib:jvmtitest=test:rc016 -cp /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/asm-all.jar com.ibm.jvmti.tests.util.TestRunner
Time spent starting: 22 milliseconds
Time spent executing: 6127 milliseconds
Test result: FAILED
Output from test:
 [ERR] JVMCDRT000E Unable to locate JIT stack map - aborting VM
 [ERR] JVMCDRT001E Method: java/lang/NullPointerException.<init>(Ljava/lang/String;)V (00000000011E4F18)
 [ERR] JVMCDRT002E Failing PC: 00007FF3EA23B223 (offset 0000000000000023), metaData = 00007FF3B11FF2B8
 [ERR] 17:19:56.683 0x11b3a00j9codertvm(j9ji.110    *   ** ASSERTION FAILED ** at jswalk.c:538: ((0 ))
```
J9vmTest_2
```
+++ j9vm.test.jni.CriticalRegionTest: +++
command: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/bin/java -XX:+UseJITServer -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump -Xms64m -Xmx64m    -classpath /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.jni.CriticalRegionTest 

Exception in thread "main" java.lang.BootstrapMethodError: java.lang.invoke.StringConcatException: Generator failed
	at j9vm.test.jni.CriticalRegionTest.testAcquireAndSleep(CriticalRegionTest.java:756)
	at j9vm.test.jni.CriticalRegionTest.runBlockingTests(CriticalRegionTest.java:733)
	at j9vm.test.jni.CriticalRegionTest.main(CriticalRegionTest.java:191)
Caused by: java.lang.invoke.StringConcatException: Generator failed
	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:764)
	at java.base/java.lang.invoke.StringConcatFactory.doStringConcat(StringConcatFactory.java:665)
	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:581)
	at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:963)
	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1093)
	... 3 more
Caused by: java.lang.ClassCastException: java.lang.StringBuilder incompatible with java.util.concurrent.ConcurrentHashMap$Node
	at java.base/java.util.concurrent.ConcurrentHashMap.tabAt(ConcurrentHashMap.java:760)
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:938)
	at java.base/java.lang.invoke.ThunkTable.get(MethodHandle.java:1704)
	at java.base/java.lang.invoke.FoldHandle.computeThunks(FoldHandle.java:69)
	at java.base/java.lang.invoke.MethodHandle.<init>(MethodHandle.java:235)
	at java.base/java.lang.invoke.FoldHandle.<init>(FoldHandle.java:33)
	at java.base/java.lang.invoke.FoldNonvoidHandle.<init>(FoldHandle.java:104)
	at java.base/java.lang.invoke.FoldHandle.get(FoldHandle.java:55)
	at java.base/java.lang.invoke.MethodHandles.foldArgumentsCommon(MethodHandles.java:2721)
	at java.base/java.lang.invoke.MethodHandles.foldArguments(MethodHandles.java:2637)
	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.generate(StringConcatFactory.java:1560)
	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:756)
	... 7 more
no-zero exit value: 1
*** Test FAILED *** (j9vm.test.jni.CriticalRegionTest)
```

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
This time tests have passes, hence merging.

**Pull request merged**
