### PR TITLE
Fix openj9 compile errors when ddr enabled

### PR DESCRIPTION
**Pull request by keithc-ca**
ddr/ddr_stubs.mk
  - simplify rules to use blob stubs

ddr/module.xml
  - don't define J9PORT_LIBRARY_DEFINE or OMRPORT_LIBRARY_DEFINE so stubs compile
  - fix line-ends

gc_ddr/gcddrblob.cpp.stub
  - use omrtty_printf macro

gc_ddr/module.xml
  - fix line-ends

### CODE REVIEW

**Comment by keithc-ca** [comment]
This is in support of https://github.com/eclipse/openj9/issues/378.

**Comment by pshipton** [comment]
Is the title of this Pull Request accurate? It seems misleading at this seems to be just a step along the way.

**Comment by keithc-ca** [comment]
I would say it is accurate: if the flag is not disabled in openj9-openjdk-jdk9/closed/OpenJ9.gmk then openj9 does build where it wouldn't without this change.
It is, however, only one step in the direction of full DDR support: we still need to make use of OMR's tool to generate real blobs instead of just stubs.

**Comment by pshipton** [comment]
Could you modify the title to indicate there will be multiple steps required and this isn't a complete solution?

**Comment by keithc-ca** [comment]
Commit rebased and headline updated.

**Comment by pshipton** [comment]
Causes the DDR build to fail in the IBM internal build. Reverting by request until the proper fixes can be contributed.

**Pull request merged**
