### PR TITLE
Statically link protobuf

### PR DESCRIPTION
**Pull request by dmitry-ten**
Dynamic linking causes issues when protobuf
on the build machine was compiled with a different
gcc version than on the testing machine.
Static linking adds only a few megabytes to JIT
library, so it should be the better way of building.

### CODE REVIEW

**Comment by dmitry-ten** [comment]
@mpirvu can you test jenkins in this PR?

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8 depends eclipse/openj9-omr#jitaas

**Comment by DanHeidinga** [comment]
Is the license compatible with being statically linked?  Some libraries (ie: libstdc++) have licenses that treat static linking differently

**Comment by mpirvu** [comment]
The license is 3 clause BSD:
```
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
    * Neither the name of Google Inc. nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.
```
It doesn't say anything about static linking. @DanHeidinga is that ok?

**Comment by DanHeidinga** [comment]
> `* Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.`

Prior to this PR, the JITaaS branch dynamically linked with the version of protobuf available on the system.  The protobuf library wasn't shipped with OpenJ9.

This PR changes that.  With this PR, OpenJ9 would ship ("redistribute") a version of protobuf.  I *think* we need an Eclipse CQ for that and need to update the https://github.com/eclipse/openj9/blob/master/LICENSE & https://github.com/eclipse/openj9/blob/master/longabout.html

We have a CQ for using protobuf (https://dev.eclipse.org/ipzilla/show_bug.cgi?id=17050) but it doesn't mention distribution of the library.  To be safe, please either open a new CQ or reach out to the Eclipse IP team for confirmation that shipping protobuf is fine.

**Comment by mpirvu** [comment]
I received a message from Eclipse regarding statically linking protobuf library: 
"This CQ covers the pre-req regardless of how its linked!"
Hence, we are covered from the legal point of view.

**Comment by dmitry-ten** [comment]
Rebased and added licenses.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Testing will be available when JITServer code is merged into master, so merging this PR now.

**Pull request merged**
