### PR TITLE
enable FindExtThread in DDR

### PR DESCRIPTION
**Pull request by OscarQQ**
[ci skip]

Signed-off-by: OscarQQ <Yixin.Qian@ibm.com>

### CODE REVIEW

**Comment by OscarQQ** [comment]
| Build       | Platform           | Java Version  | JDK Impl |
|:-------------:|:-------------:|:-----:|:-----------:|
| Grinder/9816     | ppc64le_linux | 8 | IBM|
| Grinder/9817    | s390x_linux      |   8 | IBM|
| Grinder/9818 | x86-64_linux      |    8 | IBM|
| Grinder/9813 | x86-64_windows      |    8 | IBM|
| Grinder/9819 | s390x_zos     |    8 | IBM|
| Grinder/9815 | ppc64_aix     |    8 | IBM|
| Grinder/9814 | x86-64_mac     |    8 | OpenJ9|

**Comment by OscarQQ** [comment]
@llxia

**Comment by llxia** [comment]
jenkins test extended all jdk8,jdk11

**Comment by llxia** [comment]
jenkins test extended xlinuxlargeheap jdk8

**Pull request merged**
