### PR TITLE
Revert "Revert "Mark VM as exitting earlier""

### PR DESCRIPTION
**Pull request by gacholio**
Reverts eclipse/openj9#9829

### CODE REVIEW

**Comment by pshipton** [comment]
@gacholio what's going on, this change introduces Windows hang on exit problems.

**Comment by gacholio** [comment]
It only affects a single test (on every platform, not just windows), and the fix is coming in a PR in a few minutes. There was no need to re-review the existing code.

**Comment by pshipton** [comment]
ok, but there is a timing hole here. If the new PR doesn't get merged today then the problem gets re-exposed in the builds tonight and on the weekend. The better approach is to include the revert commit in the new PR, separately from the new fix commit, so they are merged together.

**Comment by gacholio** [comment]
I was unable to figure out how to do that. This change was in the builds for a week before the problem was detected, so there's no issue with having it in for a short while unfixed.

**Comment by pshipton** [comment]
In Eclipse, make local branch, open the history, find the revert commit and select revert on it to create a new commit in your local branch. Then make the changes on top in a new commit as usual.

**Comment by gacholio** [comment]
Thanks, I'll keep it in mind for the next time.

**Comment by pshipton** [comment]
I believe the problem causes some timeouts in the builds running at AdoptOpenJDK (not sure why not at OpenJ9). They weren't noticed until triaging for the 0.21 release Milestone 1, the revert didn't make M1. My point is that now Adopt nightly builds may be failing again until the fix is reviewed and merged.

**Pull request merged**
