### PR TITLE
Rearrange yaml file properties for osx extra_configure_options

### PR DESCRIPTION
**Pull request by jdekonin**
* [skip ci]
* related ibmruntimes/openj9-openjdk-jdk11#31

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
jenkins compile osx jdk8

**Comment by jdekonin** [comment]
jenkins compile osx jdk11

**Comment by jdekonin** [comment]
fyi @pshipton

**Comment by pshipton** [comment]
@jdekonin I think you'd better fix jdk11 but remove the jdk8 change so we can deal with that separately. It might need a change to the jdk8 extensions.

@enasser fyi the jdk8 osx failure to build openssl https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK8-osx_x86-64_cmprssptrs-OpenJ9/7

**Comment by jdekonin** [comment]
jenkins compile osx jdk11

**Pull request merged**
