### PR TITLE
Set PLATFROM to XXX_mixed for all test builds

### PR DESCRIPTION
**Pull request by llxia**
- skip zos as it is not ready atm
- if the spec contians _mixed, skip it

[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/778/ failed with 
```
[2021-02-10T23:36:47.916Z] /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TKG/envSettings.mk:37: *** DETECTED_SPEC value is linux_x86-64_cmprssptrs, settled SPEC value is linux_x86-64_mxdptrs. SPEC value does not match. Please reset or unset SPEC.  Stop.
```

This is expected. The goal of this PR build is to verify PLATFORM is set to `x86-64_linux_mixed`

Used `Rerun in Grinder ` and a mixedred SDK in Grinder, to verify everything else is set up correctly
https://ci.eclipse.org/openj9/job/Grinder/1516/

**Comment by llxia** [comment]
Jenkins test sanity xlinux,zlinuxmxd jdk11

**Comment by AdamBrousseau** [comment]
To confirm my understanding, the goal here is to take all non-zos, non-mixed specs, continue calling the same test jobs but swap out the platform in the call to the test jobs. Basically a mirror of https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/22.
Once the test repo makes the default specs as mixed this can be removed as it can at Adopt.

**Comment by llxia** [comment]
That's correct. The code will be removed once we fully switch to mixed.

**Comment by llxia** [comment]
[Test_openjdk11_j9_sanity.functional_s390x_linux_mixed_Personal](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_s390x_linux_mixed_Personal/1/) passed as expected.

[Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/779/) failed as epxected.

**Comment by llxia** [comment]
This PR should only be merged once we switch to mixed SDK by default on all platforms (except zos).

**Comment by pshipton** [comment]
@llxia is there going to be any problem with win32, which doesn't support mixedrefs because it's 32-bit?

**Comment by llxia** [comment]
Good catch. I will update this PR to exclude 32bit platforms. I think AdoptOpenJDK/ci-jenkins-pipelines#22 also needs to be updated for this.

**Comment by llxia** [comment]
Jenkins test sanity xlinux,zlinuxmxd,win32 jdk8

**Comment by pshipton** [comment]
> Good catch.

@AdamBrousseau actually mentioned it to me.

**Comment by pshipton** [comment]
@llxia I wonder if this should be handled a different, more permanent way. Since mixedrefs will be the default everywhere but 32-bit and z/OS, should TKG reverse how testing is run? Rather than require `_mixed` in the name in order to run mixedrefs testing, it could run mixedrefs for 64-bit by default, and then have a special case to handle non-mixed testing. Perhaps by using `_nonmixed` in the platform name. If z/OS is handled, we don't even need to add support for `_nonmixed` right away, only if later we decide it's really needed.

**Comment by pshipton** [comment]
Note the TKG change would have to be merged at the same time as https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/382, and then this change and https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/22 won't be required.

**Comment by llxia** [comment]
Yes, it does make sense to make the change in TKG as the mixedrefs will be the default everywhere but 32-bit and z/OS. I think TKG could just override the `PLATFORM` value based on its auto-detected value, so this change and AdoptOpenJDK/ci-jenkins-pipelines#22 are not needed. We can clean up _mixed and _xl code in TKG at a later stage.
FYI @renfeiw

**Comment by pshipton** [comment]
Closing as the change is no longer required as it's been replaced by AdoptOpenJDK/TKG#155

**Pull request closed without merging**
