### PR TITLE
Exclude SetClasspathTest and libpathTest for windows

### PR DESCRIPTION
**Pull request by vsebe**
Exclude libpathTest and SetClasspathTest tests.
Fixed java home path for libpathTest and loadLibraryTest.

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
@pshipton  please review, thank you!

**Comment by pshipton** [comment]
@smlambert or @llxia pls review

**Comment by llxia** [comment]
Are we going to exclude libpathTest or update to use correct exclude file name for libpathTest?

**Comment by vsebe** [comment]
@llxia there are 2 libpathTest  suites. They both need to be excluded. There are also 2 exclude files. This patch fixes the name of one of the exclude files.

**Comment by llxia** [comment]
Thanks for clarify. In commit message, it should be  Exclude SetClasspathTest and `libpathTest` for windows. The rest looks good to me.

**Comment by vsebe** [comment]
@llxia - commit comment updated

**Pull request merged**
