### PR TITLE
get third party dependency in VM_Test

### PR DESCRIPTION
**Pull request by OscarQQ**
related: https://github.com/AdoptOpenJDK/TKG/issues/63
[ci skip]

Signed-off-by: OscarQQ <Yixin.Qian@ibm.com>

### CODE REVIEW

**Comment by OscarQQ** [comment]
Grinder_TKG/924
vmfarm job_output id=662498843

**Comment by OscarQQ** [comment]
in vmfarm, target `getDependentLibs ` is not called

**Comment by llxia** [comment]
Jenkins test sanity,extended plinux jdk8

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
