### PR TITLE
Update UNB curl redirection script to be more detailed

### LINKED ISSUE #10985: ub16p8j92 cannot unzip SDK
[ub16p8j92](https://ci.eclipse.org/openj9/computer/ub16p8j92/) failed to unzip SDK

```
16:39:03  get jdk binary...
16:39:03  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_ppc64le_linux_xl_Nightly/313/OpenJ9-JDK11-ppc64le_linux_xl-20201014-230529.tar.gz
16:39:03  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_ppc64le_linux_xl_Nightly/313/test-images.tar.gz
16:39:03  unzip file: OpenJ9-JDK11-ppc64le_linux_xl-20201014-230529.tar.gz ...
16:39:03  
16:39:03  gzip: OpenJ9-JDK11-ppc64le_linux_xl-20201014-230529.tar.gz: not in gzip format
16:39:03  tar: This does not look like a tar archive
16:39:03  tar: Exiting with failure status due to previous errors
```
https://ci.eclipse.org/openj9/job/Grinder/1117/
https://ci.eclipse.org/openj9/job/Grinder/1119/

The same SDK URL can be downloaded and unzipped at https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4308/ and hyc Jenkins Grinder/11550/

I am not sure if this is related to UNB network problem.

### PR DESCRIPTION
**Pull request by jdekonin**
* fixes #10985
* [skip ci]

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
@vsebe @AdamBrousseau @pshipton for review

**Comment by jdekonin** [comment]
Modified job output is detailed in #10985

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
If https://github.com/eclipse/openj9/issues/10985#issuecomment-759755185 is actual output instead of a mock up, the `Original parameter:` and `Modified to UNB mirror:` are the same.

**Comment by pshipton** [comment]
Is this change supposed to be just updating doc?

**Comment by AdamBrousseau** [comment]
This change is just to update the doc. The files will be rolled out by hand as root to all the unb machines.
Agree that the grinder Joe linked has the same before/after. I think he pasted a "non-standard" link.
I reran it with a link pulled from a nightly.
https://ci.eclipse.org/openj9/job/Grinder/1388/

**Comment by pshipton** [comment]
Waiting for approvals from Adam/Violeta before merging.

**Review by pshipton — APPROVED** [review]

**Review by AdamBrousseau — APPROVED** [review]

**Review by vsebe — APPROVED** [review]
lgtm

**Pull request merged**
