### PR TITLE
Re-Fetch patcharray after entering VM

### PR DESCRIPTION
**Pull request by fengxue-IS**
Fixes: #9931 

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Jenkins test sanity xlinux jdk11

**Comment by pshipton** [comment]
Failure is due to https://github.com/eclipse/openj9/issues/9869

Jenkins test sanity win jdk11

**Comment by gacholio** [comment]
+1 for scoping the local instead of reusing it.

**Comment by pshipton** [comment]
@fengxue-IS please cherry pick the commit and create a PR for the 0.21 branch.

**Pull request merged**
