### PR TITLE
Use default parameters for findOrCreateRuntimeHelper

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Replace references to findOrCreateRuntimeHelper on Z
* Replace references to findOrCreateRuntimeHelper on Power
* Replace references to findOrCreateRuntimeHelper on X86
* Replace references to findOrCreateRuntimeHelper on AArch64
* Replace references to findOrCreateRuntimeHelper on ARM
* Replace references to findOrCreateRuntimeHelper in common code

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Un-WIPing as local testing has completed successfully.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
@fjeremic : I'm wondering if you'd be willing to take this one since you merged the upstream eclipse/omr#5606 ?

**Review by fjeremic — APPROVED** [review]

**Pull request merged**
