### PR TITLE
Fix data race when locking JProfiling tables

### PR DESCRIPTION
**Pull request by aviansie-ben**
When adding new values to a JProfiling table, it is necessary for the
JIT helpers to lock the table in question to avoid conflicts. However,
the previous method of locking involved a data race on the _metaData
field. Specifically, the read of _metaData to determine the value to
CAS was not atomic. The result was that xlc compiled this into two
reads, one of _metaData.otherIndex and one of _metaData.rawData. If
another thread were to release the lock in between these two reads, this
could result in the value swapped into _metaData having otherIndex < 0,
which would trigger the "JIT access not disabled" assert.

This has been corrected by performing a single volatile read of
_metaData to determine what value to use. While it's not clear that this
eliminates all undefined behaviour here, it does fix the immediate
problem.

Signed-off-by: Ben Thomas <ben@benthomas.ca>

### CODE REVIEW

**Comment by r30shah** [comment]
Thanks a lot @aviansie-ben  for identifying the issue and creating a fix, changes looks ok to me. As @andrewcraik  is away, I want to request @vijaysun-omr  to review this change. 

Ben, I believe you would have to open up another PR to have this change in 0.18 release as we have JProfiling enabled from 0.18 release.

**Comment by aviansie-ben** [comment]
Understood. I'll open another PR to have this fix included in 0.18 once this PR is approved.

**Comment by vijaysun-omr** [comment]
Jenkins test sanity all jdk8

**Comment by vijaysun-omr** [comment]
@aviansie-ben I assume the asm code generated by xlc has been checked and the "non atomic" read is no longer seen with your fix.

**Comment by aviansie-ben** [comment]
@vijaysun-omr Yes, I checked manually and the assembly output from xlc after this patch no longer contains two loads of `_metaData`.

**Comment by gita-omr** [comment]
I would like to understand the semantics of the code a little better to see if this fix is sufficient in a general case. I will try to review soon.

**Comment by vijaysun-omr** [comment]
@gita-omr thanks for your review. Tests have also passed and so I am merging.

**Pull request merged**
