### PR TITLE
Consolidate implementations of RegisterIterators in OMR

### PR DESCRIPTION
**Pull request by samolisov**
OMR issue eclipse/omr#2645 (Consolidate implementation of RegisterIterators) is being solved under PR ~~eclipse/omr#2981~~ eclipse/omr#3287 There are a series of commits where such methods of the `Machine` classes as `getARCHRealRegister()` are renamed to `getRealRegister()`. The methods are actively used within OpenJ9 so that in order to exclude the possibility of getting an OpenJ9 broken build the methods must be renamed across the codebase.

**Warnings**: 
 * `build-all` is needed
 * the PR may be merged only after eclipse/omr#3287.

### CODE REVIEW

**Comment by charliegracie** [comment]
Jenkins test sanity plinux,zlinux,xlinux jdk8 depends eclipse/omr#2981

**Comment by samolisov** [comment]
Since eclipse/omr#3287 is merged, the renames can be applied on the OpenJ9 codebase. The 'WIP' marker has been removed.

@charliegracie @pshipton and other committers, please review the changes.

**Comment by pshipton** [comment]
@0xdaryl

**Comment by fjeremic** [comment]
Thanks again @samolisov, this cleanup is much appreciated.

Jenkins test sanity all JDK8

**Comment by samolisov** [comment]
Builds filed with the following error:

```
Using context: Sanity - JDK8 - win_x86-64_cmprssptrs
java.io.IOException: Tried to load head FlowNodes for execution Owner[PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9/389:PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9 #389] but FlowNode was not found in storage for head id:FlowNodeId 1:146
```
Unfortunately, I have no idea what is it.

**Comment by fjeremic** [comment]
> Unfortunately, I have no idea what it exactly is.

This is an infrastructure issue unfortunately. The Eclipse CI wen't down for ~30 mins a little while ago. We'll have to respin.

Jenkins test sanity all JDK8

**Comment by charliegracie** [comment]
Jenkins test sanity zlinux JDK8

**Comment by charliegracie** [comment]
Jenkins test sanity xlinux JDK8

**Comment by charliegracie** [comment]
Sorry my webpage did not refresh and quickly enough and for some reason it looked like there were failures...

**Comment by fjeremic** [comment]
> Sorry my webpage did not refresh and quickly enough and for some reason it looked like there were failures...

Looks like infrastructure failures.

**Comment by fjeremic** [comment]
Jenkins test sanity xlinux,zlinux JDK8

**Comment by fjeremic** [comment]
Jenkins test sanity zlinux,xlinux JDK8 depends eclipse/omr#2981

**Comment by samolisov** [comment]
@fjeremic 2981 was closed, do you mean 3287?

**Pull request merged**
