### PR TITLE
move third party lib to functional level

### PR DESCRIPTION
**Pull request by OscarQQ**
related: AdoptOpenJDK/TKG#63
[ci skip]

Signed-off-by: OscarQQ <Yixin.Qian@ibm.com>

### CODE REVIEW

**Comment by OscarQQ** [comment]
`Grinder_TKG/987`   mimic local testing environment, disable Jenkins GetDependency, also remove get all dependency at the beginning https://github.com/OscarQQ/TKG/commit/9d56119f89da392ac8315c8f477515a302ad73f7
`Grinder/12435`     mimic local testing environment, just disable Jenkins GetDependency
`Grinder/12436`    everything other than this commit stays unchanged, get the expected output: all libs with the correct hash

Former pr to move third party lib into functional level (just VM_Test): https://github.com/eclipse/openj9/pull/11226

**Comment by OscarQQ** [comment]
@llxia @renfeiw could you take a review? thanks :)

**Comment by llxia** [comment]
jenkins test sanity,extended xlinux,win,aix jdk8,jdk11

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
jenkins test sanity,extended xlinux,win,aix jdk8,jdk11

**Comment by llxia** [comment]
jenkins test extended win jdk11

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
