### PR TITLE
Fix -Xjit:perfTool option in JITServer mode

### PR DESCRIPTION
**Pull request by ymanton**
`-Xjit:perfTool` is broken in JITServer mode because `CompilationInfoPerThreadBase::setMetadata()` isn't being called for remote compiles (or AOT compiles), but only for local JIT compiles.

### CODE REVIEW

**Comment by ymanton** [comment]
@dchopra001 Try this and see if it lets you do what you wanted.

**Comment by mpirvu** [comment]
@dchopra001 Did this PR work for you?

**Comment by dchopra001** [comment]
Yes it did.

**Comment by mpirvu** [comment]
jenkins test sanity xlinuxjit,plinuxjit jdk8

**Comment by mpirvu** [comment]
All tests have passed, hence merging.

**Pull request merged**
