### PR TITLE
DTFJ: Add API to query the byte order of an address space

### PR DESCRIPTION
**Pull request by mikezhang1234567890**
Adds an API to query byte order so `findptr` can use the correct byte order instead of defaulting to little endian.

Fixes https://github.com/eclipse/openj9/issues/8749

### CODE REVIEW

**Comment by mikezhang1234567890** [comment]
@pshipton can you please review?

**Comment by pshipton** [comment]
jenkins test sanity,extended zlinux,plinux jdk8

**Comment by pshipton** [comment]
@keithc-ca can we squash your commits before this gets merged?

**Comment by keithc-ca** [comment]
> @keithc-ca can we squash your commits before this gets merged?

I have no problem with that.

**Comment by pshipton** [comment]
@mikezhang1234567890 can you pls squash Keith's commits into one, and keep yours separate.

**Comment by mikezhang1234567890** [comment]
@pshipton squashed the commits.

**Pull request merged**
