### PR TITLE
Correct escape analysis loop check

### PR DESCRIPTION
**Pull request by ncough**
Escape analysis may have to create initialization
code at the method start. If the first block is
part of a loop, it will create a new block to hold
these trees. However, the block test did not consider
whether the first block was in an improper region,
resulting in init code being placed inside a loop.

Signed-off-by: Nicholas Coughlin <cnic@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
This change looks good to me. It does affect non-x86 platforms so those need test coverage and then this can be merged.

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by AdamBrousseau** [comment]
Jenkins test sanity plinux

**Comment by andrewcraik** [comment]
@AdamBrousseau what happened to the Linux-ppc-64 build? it seems to have died?

**Comment by AdamBrousseau** [comment]
Not sure, I have seen this error before, continuing investigation, so far unsuccessfully.

**Comment by AdamBrousseau** [comment]
Jenkins test sanity plinux

**Comment by AdamBrousseau** [comment]
My apologies for the zlinux failure, unforeseen side-effect of investigation. The build did pass with no failures though
`ALL TESTS PASSED`

**Comment by andrewcraik** [comment]
Based on the clean ppc build and adam's comment that the 390 build also passed I am going to merge this.

**Pull request merged**
