### PR TITLE
Ignore dump file deletion failures on Windows

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Fixes https://github.com/eclipse/openj9/issues/2642

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pdbain-ibm** [comment]
@llxia would you kindly run an extended build on Linux and Windows?  My personal build failed due to lack of disk space.

**Comment by llxia** [comment]
Do we have this issue in openj9 build? Ideally, it is better to delete the core file once we are done.

**Comment by pdbain-ibm** [comment]
This has been observed in a build (I forget which one):
https://github.com/eclipse/openj9/issues/2642

**Comment by llxia** [comment]
Talked with Peter, some process maybe holding the file, so we cannot delete it right away. Since workspace will get cleaned up in OpenJ9 builds, this should be ok.

**Comment by llxia** [comment]
jenkins test extended win jdk10

**Comment by llxia** [comment]
jenkins test extended xlinux jdk10

**Comment by pdbain-ibm** [comment]
@llxia If issue #2642 is not occurring in the public builds, we can close this pull request as unnecessary.

**Comment by llxia** [comment]
nightly build seems fine: https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK10-win_x86-64_cmprssptrs/

Close this issue. We can reopen if it occurs again.

**Pull request closed without merging**
