### PR TITLE
Add external group in testKitGen

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by smlambert** [comment]
We will want the same for a 'perf' target, though its fine to have separate PRs

**Comment by AdamBrousseau** [comment]
Ignore me :)
Jenkins compile

**Comment by AdamBrousseau** [comment]
Jenkins test extended
(should be a few failures here)

**Pull request merged**
