### PR TITLE
Initial commit of OpenJ9 snapshot/restore mechanism

### PR DESCRIPTION
**Pull request by 0xdaryl**
Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
CQ created for the combined OpenJ9 & OpenJ9-OMR contribution: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22585

**Comment by 0xdaryl** [comment]
The CI failure is because the CI build is cloning the "openj9" branch of the "openj9-omr" repo, rather than the "snapshot" branch.

**Comment by DanHeidinga** [comment]
The CQ has been approved for initial check-in: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22585#c6

I'm going to merge this PR and the openj9-omr one as is and continue development from this point.

**Comment by DanHeidinga** [comment]
Corresponding openj9-omr PR: https://github.com/eclipse/openj9-omr/pull/75

**Review by DanHeidinga — COMMENTED** [review]
lgtm as initial snapshot PR

**Pull request merged**
