### PR TITLE
add ADD_JVM_LIB_DIR_TO_LIBPATH in TestAttachAPI and TestSunAttachClasses

### PR DESCRIPTION
**Pull request by llxia**
Fixes: #2704
[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Jenkins test extended xlinux jdk11

**Comment by llxia** [comment]
TestAttachAPI and TestSunAttachClasses are passed as expected. The rest failures are known issues #2871 and #2708

**Comment by pdbain-ibm** [comment]
Thank you @llxia ! Great work, as always.
      -p

**Comment by llxia** [comment]
@pshipton, could you help to merge this PR? Thanks.

**Pull request merged**
