### PR TITLE
Minor fix to testKitGen

### PR DESCRIPTION
**Pull request by renfeiw**
- add perf group
- move summary to bottom
- fix corner case with empty target

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by renfeiw** [comment]
Jenkins test sanity

**Comment by smlambert** [comment]
Addresses #85 and request to add additional top-level make target for better division of different types of tests, what was the empty target corner case?

**Comment by renfeiw** [comment]
In the case that there's no test in a group target, we need to set the target to empty. For example, if there's no test with external tag, the target should be empty. Otherwise "make test" will stuck at the dependent external target.

**Pull request merged**
