### PR TITLE
JITServer thunk and relo record fixes for Power

### PR DESCRIPTION
**Pull request by dchopra001**

### CODE REVIEW

**Comment by dchopra001** [comment]
@ymanton

**Comment by ymanton** [comment]
jenkins test sanity ppc64le_linux,ppc64le_linux_xl,ppc64_aix jdk8,jdk13

**Comment by ymanton** [comment]
jenkins test sanity ppc64le_linux,ppc64le_linux_xl,ppc64_aix jdk8,jdk13

**Comment by ymanton** [comment]
Jenkins test sanity ppc64le_linux,ppc64le_linux_xl,ppc64_aix jdk8,jdk13

**Comment by ymanton** [comment]
Jenkins test sanity plinux,plinuxxl,aix jdk8,jdk13

**Pull request merged**
