### PR TITLE
Add AOT upgrades based on SCC hints to the LPQ

### PR DESCRIPTION
**Pull request by dsouzai**
Forced AOT upgrades are recompilations that are based on hints stored in
the SCC. These hints are used to identify methods that were AOT compiled
(or loaded), but were recompiled because the sampling mechanism
determined that they were important methods. However, these upgrades are
added immediately to the queue when the method is loaded from the SCC,
which can potentially impact an application's rampup phase.

This PR defers these upgrades until free cycles are available by adding them to
the low priority queue.

### CODE REVIEW

**Comment by dsouzai** [comment]
@mpirvu could you please review?

**Comment by dsouzai** [comment]
fyi @vijaysun-omr

**Comment by vijaysun-omr** [comment]
By "steady state" in your description, I assume you just mean "when there are free CPU cycles" ? 
I don't see any checking of the "phase" that the JVM is in in your change (and that's fine) which is why I am asking the question.

**Comment by mpirvu** [comment]
LPQ requests are processed only under some conditions that are independent of the phase
```
bool TR::CompilationInfo::canProcessLowPriorityRequest()
   {
   // To avoid overhead cycling through all the threads, we should first
   // check if there is anything in that low priority queue
   //
   if (!getLowPriorityCompQueue().hasLowPriorityRequest()) // access _firstLPQentry without monitor in hand
      return false;

   // If the main compilation queue has requests, we should serve those first
   if (getMethodQueueSize() != 0)
      return false;

   // To process a request from the low priority queue we need to have
   // (1) no other compilation in progress (not required if TR_ConcurrentLPQ is enabled)
   // (2) some idle CPU
   // (3) current JVM not taking its entire share of CPU entitlement
   //
   if (TR::Options::getCmdLineOptions()->getOption(TR_ConcurrentLPQ) &&
       _jitConfig->javaVM->phase == J9VM_PHASE_NOT_STARTUP) // ConcurrentLPQ is too damaging to startup
      {
      if ((getCpuUtil() && getCpuUtil()->isFunctional() &&
         getCpuUtil()->getCpuIdle() > idleThreshold() && // enough idle time
         getJvmCpuEntitlement() - getCpuUtil()->getVmCpuUsage() >= 200)) // at least 2 cpus should be not utilized
         return true;
      // Fall through the next case where we allow LPQ if the JVM leaves 50% of a CPU
      // unutilized, but there should be nothing in the main queue
      }

   // Cycle through all the compilation threads
   for (uint8_t i = 0; i < getNumUsableCompilationThreads(); i++)
      {
      TR::CompilationInfoPerThread *curCompThreadInfoPT = _arrayOfCompilationInfoPerThread[i];
      TR_ASSERT(curCompThreadInfoPT, "a thread's compinfo is missing\n");

      if (curCompThreadInfoPT->getMethodBeingCompiled())
         return false;
      }
   return (getCpuUtil() && getCpuUtil()->isFunctional() &&
      getCpuUtil()->getCpuIdle() > idleThreshold() && // enough idle time
           getJvmCpuEntitlement() - getCpuUtil()->getVmCpuUsage() > 50); // at least half a processor should be empty
   }
```

**Comment by dsouzai** [comment]
> By "steady state" in your description, I assume you just mean "when there are free CPU cycles" ?
I don't see any checking of the "phase" that the JVM is in in your change (and that's fine) which is why I am asking the question.

Ah, yes, you're right; I was mixing it up with a change that I thought was also required (ie only process the LPQ during the STEADY_STATE jitstate); good catch. I'll update the PR/commit message.

> We may want to have an option to switch between the old and the new behavior.

yeah good point, I'll make the requested changes.

**Comment by dsouzai** [comment]
@mpirvu @vijaysun-omr I made the requested changes.

**Comment by mpirvu** [comment]
jenkins test sanity all jdk8

**Comment by vijaysun-omr** [comment]
LGTM to me too.

**Comment by dsouzai** [comment]
jenkins test sanity all jdk8

**Comment by dsouzai** [comment]
don't know why jenkins didn't trigger before :S

**Comment by dsouzai** [comment]
Builds are failing because of 

```
 > git fetch --tags --progress https://github.com/eclipse/openj9.git +refs/pull/*:refs/remotes/origin/pr/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/eclipse/openj9.git
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:894)
    at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1161)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
    at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
    at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:144)
    at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
    at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
    at hudson.model.ResourceController.execute(ResourceController.java:97)
    at hudson.model.Executor.run(Executor.java:429)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/eclipse/openj9.git +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
stdout: 
stderr: error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2042)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1761)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$400(CliGitAPIImpl.java:72)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:442)
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:892)
    ... 8 more
ERROR: Error fetching remote repo 'origin'
```

**Comment by dsouzai** [comment]
Builds seem ok in a different PR

**Comment by dsouzai** [comment]
jenkins test sanity all jdk8

**Comment by dsouzai** [comment]
@mpirvu all checks passed :)

**Pull request merged**
