### PR TITLE
Enable ProxyFieldAccess tests for JCL_VERSION=latest

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by llxia** [comment]
jenkins test sanity xlinux,win,aix jdk8,jdk11

**Comment by renfeiw** [comment]
The pr builds are failed because ProxyFiledAccess test cannot be compiled when `JDK_IMPL=openj9`. (e.g., https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_windows_Personal/405/) As the test only runs for ibm, we add a conditional check for JDK_IMPL in build.xml.

**Comment by llxia** [comment]
Please move the check into `proxyFieldAccess/build.xml`

**Comment by llxia** [comment]
jenkins test sanity xlinux,win,aix jdk8,jdk11

**Comment by llxia** [comment]
[AIX Build timeout ](https://ci.eclipse.org/openj9/job/Build_JDK11_ppc64_aix_Personal/496/) is not related to this PR

**Pull request merged**
