### PR TITLE
#7871 Remove getVMThreadStatus_DEPRECATED function

### PR DESCRIPTION
**Pull request by sbcd90**

### CODE REVIEW

**Comment by DanHeidinga** [comment]
@sbcd90 Thanks for creating this PR!  The change looks good overall and to be able to accept it, you'll need to sign the Eclipse Contributor Agreement (ECA).  

Currently, the eclipsefdn/eca automated checker is failing - see details https://accounts.eclipse.org/legal/eca/validation/20838

Can you update the commit with the correct sign-off by tags after signing the ECA?  Once that's passing, we can get the change built and take the next steps

**Comment by sbcd90** [comment]
Hi @DanHeidinga , Thanks for your comments. I have signed eca now. 
Kindly let me know the next steps.

**Comment by DanHeidinga** [comment]
Thanks @sbcd90!  The automated copyright checker is failing on these files:
```
01:34:42  runtime/tests/thread/thrstate/testcases1.c
01:34:42  runtime/tests/thread/thrstate/testcases2.c
01:34:42  runtime/tests/thread/thrstate/testcases3.c
01:34:42  runtime/tests/thread/thrstate/testcases4.c
01:34:42  runtime/tests/thread/thrstate/testcases5.c
01:34:42  runtime/tests/thread/thrstate/testcases6.c
01:34:42  runtime/tests/thread/thrstate/testsetup.c
01:34:42  runtime/tests/thread/thrstate/thrstatetest.h
```
and needs the second year in the comment at the top of the file to be updated to the current year.

So for example, `* Copyright (c) 1991, 2018` --> `* Copyright (c) 1991, 2019`

**Comment by sbcd90** [comment]
Hi @DanHeidinga , thanks for your inputs. I fixed all build failures now.

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux,osx,win jdk8

**Comment by DanHeidinga** [comment]
Thanks @sbcd90.  Once the PR testing completes, I'll merge this

**Comment by DanHeidinga** [comment]
thanks @sbcd90 - your PR has been merged now!  Congrats on your first contribution to OpenJ9!

**Pull request merged**
