### PR TITLE
Separate exclude files according to java_version and jcl_version

### PR DESCRIPTION
**Pull request by sophia-guo**
Support java8 with openj9 with separated exclude files. Temporarily duplicate the existing exclude files.

Reviewers: @renfeiw @smlambert  

[skip ci]

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by smlambert** [comment]
I believe there should be an update to the README file https://github.com/eclipse/openj9/blob/master/test/README.md with this change (search for "Add a line in the test/TestConfig/default_exclude.txt" in the file).  

Ideally, we only need to document the "latest_exclude_xxx" story, because in open builds we should only be testing the latest CLs, not caught on older versions described by "current".

**Comment by sophia-guo** [comment]
@smlambert Updated README.

**Comment by smlambert** [comment]
jenkins test sanity plinux

**Comment by smlambert** [comment]
@sophia-guo I guess I let this one sit too long, now has some merge conflict with openj9_exclude.txt file, can you update your PR to resolve?

**Comment by sophia-guo** [comment]
@smlambert resolved.

**Pull request merged**
