### PR TITLE
Update subset logic in TestKitGen

### PR DESCRIPTION
**Pull request by renfeiw**
- remove the hardcoded subset check
- support jdkVersion+
- modify Jsr292 playlist.xml to use new subset logic
- remove any reference to SE version
- this avoids any change in TKG when new subset is enabled

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by llxia** [comment]
jenkins test sanity all jdk11

**Comment by llxia** [comment]
jenkins test sanity all jdk11

**Comment by llxia** [comment]
jenkins test sanity all jdk8

**Comment by llxia** [comment]
jenkins test extended all jdk11

**Comment by llxia** [comment]
jenkins test extended xlinux,aix jdk11

**Comment by llxia** [comment]
Failures are not related to this change.
Passed builds have the same number of tests as the builds that without the change.

**Pull request merged**
