### PR TITLE
Add shared classes issue to milestone 1 release notes

### PR DESCRIPTION
**Pull request by pmhayward**
Issue added to 0.14 release notes re change to shared classes
cache and suggestion to remove existing caches.

Signed-off-by: Peter Hayward <pmhayward@uk.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
I don't expect this change will make M1 as the builds have already started. It will be delivered afterwards.

**Comment by pshipton** [comment]
@pmhayward can you please change the commit message not to refer to Milestone 1, the change went in afterwards.

**Comment by pshipton** [comment]
@SueChaplain fyi

**Comment by SueChaplain** [comment]
@pshipton - I'll handle this in a separate PR and close this one when I do. Peter is now on vacation.

**Comment by SueChaplain** [comment]
Change handled in https://github.com/eclipse/openj9/pull/5511
Closing this PR.

**Pull request closed without merging**
