### PR TITLE
Remove obsolete Panama build spec

### PR DESCRIPTION
**Pull request by keithc-ca**

### CODE REVIEW

**Comment by DanHeidinga** [comment]
fyi @tajila

**Comment by DanHeidinga** [comment]
It would have been nice to give @tajila a chance to weigh in on this as he's the primary user of the Panama spec...

**Comment by keithc-ca** [comment]
We did discuss this with @tajila.

**Comment by DanHeidinga** [comment]
Glad to hear it!  When there's no evidence of a discussion (even a +1 somewhere) or a reference to an issue about how future panama testing will be handled, this looks abrupt.

**Pull request merged**
