### PR TITLE
Add OSX ifdefs to redirector

### PR DESCRIPTION
**Pull request by DanHeidinga**
issue: #36 

Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile plinux

**Comment by pshipton** [comment]
grrr

**Comment by pshipton** [comment]
I want a web UI for launching PRs, showing the choices as clickable buttons.

**Comment by DanHeidinga** [comment]
> I want a web UI for launching PRs, showing the choices as clickable buttons.

I have some saved responses that I use as a basis and then edit as necessary

**Pull request merged**
