### PR TITLE
Allow System.exit from finalizer during DestroyJavaVM

### PR DESCRIPTION
**Pull request by gacholio**
[ci skip]

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Jenkins test sanity xlinux jdk8

**Comment by DanHeidinga** [comment]
Jenkins test extended win jdk11

**Comment by DanHeidinga** [comment]
Related to - and builds on -  https://github.com/eclipse/openj9/pull/9864

**Comment by DanHeidinga** [comment]
Targeting this for inclusion in 0.21.0 as we had intended to have the fix in that release

**Comment by gacholio** [comment]
For 0.21 the previously offending change was reverted, so it will need to be re-included before porting this.

**Pull request merged**
