### PR TITLE
Back port various changes from master to jitaas

### PR DESCRIPTION
**Pull request by harryyu1994**
Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@mpirvu This back port item is ready for review.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaas

**Comment by harryyu1994** [comment]
Fixed a typo, need a jenkins re-launch.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Only the known `cmdLineTester_gcsuballoctests_0` test fails, hence merging.

**Pull request merged**
