### PR TITLE
Add FileUtilities

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Add the initial version of FileUtilities with one method:
recursive file/directory deletion.

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pdbain-ibm** [comment]
I would like to factor this method (originally in the attach API tests) out for use in other test cases,
particularly a new test case for https://github.com/eclipse/openj9/pull/1947.

Please let me know if you would like the code or classes rearranged or modified to suit preferred practice.

Thank you
     -p

**Comment by pdbain-ibm** [comment]
@smlambert or @llxia do you have any comments or changes?

FYI @chandrams

**Comment by llxia** [comment]
- Where will the new test be added? Java9andUp?
- Do you mind of removing `deleteRecursive ` in current attach API tests in Java8andUp?

**Comment by pdbain-ibm** [comment]
> Where will the new test be added? Java9andUp?

Yes.  I have an upcoming test related to modular findResource.

> Do you mind of removing deleteRecursive in current attach API tests in Java8andUp?

Can do in this commit if you would like.

**Comment by pdbain-ibm** [comment]
Updated attach API utilities.  Running a personal build.

**Comment by llxia** [comment]
Jenkins test extended plinux jdk10

**Comment by pdbain-ibm** [comment]
Attach API tests passed in personal build.

**Pull request merged**
