### PR TITLE
Add missing opcodes to InterpreterEmulator

### PR DESCRIPTION
**Pull request by cathyzhyi**
Fixes: https://github.com/eclipse/openj9/issues/3940
Fixes: https://github.com/eclipse/openj9/issues/8431

Signed-off-by: Yi Zhang <yizhang@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
@cathyzhyi Does this handle all bytecodes now?  I took a quick look and didn't see `invokedynamic` in the list - is it handled specially?

**Comment by cathyzhyi** [comment]
> @cathyzhyi Does this handle all bytecodes now? I took a quick look and didn't see `invokedynamic` in the list - is it handled specially?

This code only needs to handle bytecodes exists in method handle thunk.

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk11

**Comment by pshipton** [comment]
Jenkins test sanity all jdk11

**Comment by DanHeidinga** [comment]
> > @cathyzhyi Does this handle all bytecodes now? I took a quick look and didn't see `invokedynamic` in the list - is it handled specially?
> 
> This code is for method handle inlining and only needs to handle bytecodes exists in method handle thunk.

Unfortunately, that can be any legal bytecode.  Users bytcode agents can modify classes in the ClassFileLoadHook (basically, before we've loaded them) and insert arbitrary code into these methods, or into methods that get inlined into them.

We can't know a priori which bytecodes will be in the thunks.

**Pull request merged**
