### PR TITLE
Generate read barrier for Concurrent Scavenger

### PR DESCRIPTION
**Pull request by 0dvictor**
Under Concurrent Scavenger, read barriers when accessing
non-compressed instance fields will be generated.

Part of Issue #3338 

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win jdk8,jdk11

**Comment by andrewcraik** [comment]
@0dvictor Why is the code living here rather than with the rest of the rdbar addition logic which isn't in this particular area of the codegen?

**Comment by dsouzai** [comment]
@fjeremic Once Z has the `ardbari` evaluator, this code pretty much removes the need to anchor `aload`s under CS...though we still need something similar for `aload`s for statics.

**Comment by 0dvictor** [comment]
> Why is the code living here rather than with the rest of the rdbar addition logic which isn't in this particular area of the codegen?

If you mean the existing rdbar addition logic for compressedrefs, it locates inside `lowerCompressedRefs`, which does not apply to non-compressedrefs case.

**Comment by andrewcraik** [comment]
Right I see

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win jdk8,jdk11

**Pull request merged**
