### PR TITLE
Add variableHeapBarrier to AOT compatibility check

### PR DESCRIPTION
**Pull request by harryyu1994**
Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@dsouzai @mpirvu Could you please help review this one?

**Review by dsouzai — APPROVED** [review]

**Comment by dsouzai** [comment]
jenkins test sanity xlinux jdk11

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
@harryyu1994 
Looking closer, there are four parameters that we lookup in GC, but only three are used for AOT validation
```
j9gc_modron_configuration_heapBaseForBarrierRange0_isVariable
j9gc_modron_configuration_heapSizeForBarrierRange0_isVariable
j9gc_modron_configuration_activeCardTableBase_isVariable
j9gc_modron_configuration_heapAddressToCardAddressShift  --> This is one is missing
```
I do see it used by the optimizer. Isn't this important?

**Comment by mpirvu** [comment]
Actually it would help to document what these four GC parameters are used for:
```
j9gc_modron_configuration_heapBaseForBarrierRange0_isVariable
j9gc_modron_configuration_heapSizeForBarrierRange0_isVariable
j9gc_modron_configuration_activeCardTableBase_isVariable
j9gc_modron_configuration_heapAddressToCardAddressShift
```
 @amicic could you please help us in this respect? Thanks

**Comment by harryyu1994** [comment]
> j9gc_modron_configuration_heapAddressToCardAddressShift

From the comments, it looks to me only 3 of them are related to fixed/variable heap size.
```cpp
	j9gc_modron_configuration_heapAddressToCardAddressShift,	/* a UDATA representing the shift amount to convert from heap granularity to card table granularity */
	j9gc_modron_configuration_heapBaseForBarrierRange0_isVariable,	/* a UDATA (TRUE or FALSE) representing whether or not the J9VMThread->heapBaseForBarrierRange0 can change during the run (FALSE implies constant) */
	j9gc_modron_configuration_activeCardTableBase_isVariable,	/* a UDATA (TRUE or FALSE) representing whether or not the J9VMThread->activeCardTableBase can change during the run (FALSE implies constant) */
	j9gc_modron_configuration_heapSizeForBarrierRange0_isVariable,	/* a UDATA (TRUE or FALSE) representing whether or not the J9VMThread->heapSizeForBarrierRange0 can change during the run (FALSE implies constant) */
```

And only the values of those 3 could be changed in JIT code
```cpp
   if (vmThread)
      {
      self()->setHeapBaseForBarrierRange0((uintptr_t)vmThread->heapBaseForBarrierRange0);
      self()->setHeapSizeForBarrierRange0((uintptr_t)vmThread->heapSizeForBarrierRange0);
      self()->setActiveCardTableBase((uintptr_t)vmThread->activeCardTableBase);
      }
   else
      {
      // The heap information could not be found at compile-time.  Make sure this information
      // is loaded from the vmThread at runtime.
      //
      self()->setIsVariableHeapBaseForBarrierRange0(true);
      self()->setIsVariableHeapSizeForBarrierRange0(true);
      self()->setIsVariableActiveCardTableBase(true);
      }
```

**Comment by mpirvu** [comment]
After talking to @amicic I determined the following:
`j9gc_modron_configuration_heapAddressToCardAddressShift` cannot be changed at runtime. The value comes from a constant, so the only way to get a different value is to recompile the code. We are safe here and no AOT validation is needed.

`j9gc_modron_configuration_activeCardTableBase_isVariable` is always set to FALSE in this code
```
	case j9gc_modron_configuration_activeCardTableBase_isVariable:
		if (extensions->isVLHGC()) {
			*((UDATA *)value) = FALSE;
			keyFound = TRUE;
		} else if (extensions->isStandardGC()) {
			*((UDATA *)value) = FALSE;
			keyFound = TRUE;
		} else {
			keyFound = FALSE;
		}
		break;
```
Again, without recompiling the code we cannot get to a different value, so we are also safe.

`j9gc_modron_configuration_heapBaseForBarrierRange0_isVariable` could in theory be TRUE, but right now, an all initialization paths it is set to FALSE. We could add a validation check just to be sure.
```
	case j9gc_modron_configuration_heapBaseForBarrierRange0_isVariable:
		if (extensions->isVLHGC()) {
			*((UDATA *)value) = FALSE;
			keyFound = TRUE;
		} else if (extensions->isStandardGC()) {
			*((UDATA *)value) = FALSE;
			keyFound = TRUE;
		} else {
			keyFound = FALSE;
		}
		break;
```
`j9gc_modron_configuration_heapSizeForBarrierRange0_isVariable` is the one we have to be worried about because it can change based on options:
```
	case j9gc_modron_configuration_heapSizeForBarrierRange0_isVariable:
		if (extensions->isVLHGC()) {
			*((UDATA *)value) = FALSE;
			keyFound = TRUE;
		} else if (extensions->isStandardGC()) {
			if (extensions->minOldSpaceSize == extensions->maxOldSpaceSize) {
				*((UDATA *)value) = FALSE;
			} else {
				*((UDATA *)value) = TRUE;
			}
			keyFound = TRUE;
		} else {
			keyFound = FALSE;
		}
		break;
```

**Comment by mpirvu** [comment]
jenkins test sanity all jdk11

**Comment by harryyu1994** [comment]
@mpirvu I think this one is ready to go in.

**Pull request merged**
