### PR TITLE
Add Value Type build flag so DDR can recognize it

### PR DESCRIPTION
**Pull request by tajila**
Add Value Type build flag so DDR can recognize it

Add VT build flag to j9cfg.h template file and cmake options file 
so it can be generated in the J9BuildFlags.java DDR class.

Signed-off-by: tajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
@gacholio please review this change

**Comment by dnakamura** [comment]
This commit shouldn't be necessary. The freeemarker code in j9cfg.h.ftl auto generates #define/#undef s for all flags in `j9.flags`.

**Comment by tajila** [comment]
@dnakamura we stopped using the j9.flags for new features because we are not able to conditionally turn the on/off for specific java levels.

**Comment by dnakamura** [comment]
Ah, so Im assuming then that you are manually adding the undef, so that you can later remove it from `j9.flags` without breaking builds.
Also it probably makes sense to add the flag to `include/j9cfg.h.in`

**Comment by tajila** [comment]
> Ah, so Im assuming then that you are manually adding the undef, so that you can later remove it from j9.flags without breaking builds.

Yes, Ill be removing all the `opt_valhallaValueTypes` in the spec files.

> Also it probably makes sense to add the flag to include/j9cfg.h.in

If I add it to include/j9cfg.h.in, is the options.cmake change required at all?

**Comment by gacholio** [comment]
@tajila @dnakamura What's happening with this?

**Comment by tajila** [comment]
@dnakamura I made the change you suggested. 

Are the changes in options.cmake required?

**Comment by dnakamura** [comment]
The changes in  `options.cmake` actually should have been there before

**Comment by tajila** [comment]
@gacholio the changes are ready for another look

**Comment by gacholio** [comment]
jenkins test sanity xlinux jdk8

**Comment by gacholio** [comment]
jenkins test sanity plinux jdk11

**Pull request merged**
