### PR TITLE
Update Lithuanian tests to conform to Unicode 10 for Java 11

### PR DESCRIPTION
**Pull request by fjeremic**
According to #1875 the Unicode 10 will be used for Java 11. We must
update our Lithuanian tests with the new codepoints as per [1].

[1] https://www.unicode.org/Public/10.0.0/ucd/extracted/DerivedCombiningClass.txt

Fixes: #2890

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Leaving as WIP until I've done some testing. Feel free to review.

**Comment by fjeremic** [comment]
Jenkins test sanity xlinux JDK11

**Comment by fjeremic** [comment]
I don't see the failure in the Sanity builds, but the build doesn't succeed because of other issues. I'm currently compiling my own JDK11 in a Docker image to validate the `test_toLowerCase_lithuanian` test failure and that the new fix to the test will make it pass. Will have this done by sometime tomorrow.

**Comment by pshipton** [comment]
jenkins test sanity aix jdk8,jdk10

**Comment by pshipton** [comment]
jenkins test sanity aix jdk8

**Comment by pshipton** [comment]
@fjeremic the fact that JCL_Test_0 passed should be good enough. Once jdk8 and jdk10 pass I'm happy to merge.

**Comment by pshipton** [comment]
Although there is a blocking problem atm for building OpenJ9, unrelated to this change.

**Comment by andrewcraik** [comment]
@pshipton the blocking failure was fixed by the merge of #2649.

**Comment by fjeremic** [comment]
Jenkins test sanity aix jdk8,jdk10

**Comment by pshipton** [comment]
@andrewcraik doesn't seem fixed, or there is another problem.
`"/home/u0020236/workspace/PullRequest-Sanity-JDK8-aix_ppc-64_cmprssptrs-OpenJ9/build/aix-ppc64-normal-server-release/vm/compiler/../compiler/codegen/CodeGenGPU.cpp", line 1314.1: 1540-5220 (S) "Number of elements in nvvmOpCodeNames does not match the value of TR::NumIlOps"`

**Comment by fjeremic** [comment]
> @andrewcraik doesn't seem fixed, or there is another problem.

I forgot to rebase after the fix in OpenJ9 was merged. Will do this first thing in the morning. Don't have my SSH key setup at home unfortunately.

**Comment by fjeremic** [comment]
Jenkins test sanity aix jdk8,jdk10

**Comment by pshipton** [comment]
Jenkins test sanity aix jdk8,jdk10

**Comment by pshipton** [comment]
I give up on the PR testing. The change looks good, should not affect 8/9/10, and worked on jdk11. I'm just going to merge it and if it causes problems we can deal with it.

**Pull request merged**
