### PR TITLE
Added additional JDK_IMPL parameter to compile

### PR DESCRIPTION
**Pull request by LongyuZhang**
- In makefile, added one more parameter JDK_IMPL to compile
[ci skip]

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
reviewers @llxia

**Comment by llxia** [comment]
jenkins test sanity plinux jdk11

**Comment by llxia** [comment]
This is needed for compiling specific JDK impl tests.

**Comment by llxia** [comment]
jenkins test sanity plinux jdk11

**Comment by pdbain-ibm** [comment]
Please hold off on this change; it may be unnecessary.

**Comment by llxia** [comment]
> Please hold off on this change; it may be unnecessary.

This is needed for compiling specific JDK impl tests (i.e., hotspot, sap, etc). It is not specific for the recent attachAPI issue.

**Comment by llxia** [comment]
jenkins test sanity plinux jdk11

**Comment by llxia** [comment]
jenkins test sanity plinux jdk11

**Comment by llxia** [comment]
`UnsafeTests_0 ` failure is the same as https://github.com/eclipse/openj9/issues/4470

**Pull request merged**
