### PR TITLE
Replaced JAVA_BIN with TEST_JDK_HOME in several tests

### PR DESCRIPTION
**Pull request by LongyuZhang**
- replaced path JAVA_BIN with new TEST_JDK_HOME variable in tests of JLM, Java8andUp, Java9andUp, Java11andUp.
[ci skip]

Signed-off-by: Longyu <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
reviewers: @llxia @renfeiw

**Comment by LongyuZhang** [comment]
Tested internally using JDK 8 & 11 with sanity functional and extended functional.

**Comment by llxia** [comment]
Related to #1058

The rest of test projects will be updated in another PR.

**Comment by llxia** [comment]
jenkins test sanity xlinux jdk8,jdk11

**Comment by llxia** [comment]
jenkins test sanity win,aix jdk8,jdk11

**Comment by llxia** [comment]
jenkins test extended win,aix jdk8,jdk11

**Comment by llxia** [comment]
JDK11 extended aix test failure is related to https://github.com/eclipse/openj9/issues/3081

```
[AttachApiTest] [ERROR] com.sun.tools.attach.AttachNotSupportedException: acknowledgement timeout from 12058696 on port 36429
03:04:41.217  	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.tryAttachTarget(OpenJ9VirtualMachine.java:443)
03:04:41.217  	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.attachTarget(OpenJ9VirtualMachine.java:121)
```

**Pull request merged**
