### PR TITLE
Adjust DDR namespace annotations

### PR DESCRIPTION
**Pull request by keithc-ca**
* declarations in stackwalk.h grouped to reduce number of annotations required
* also in generated constant pool
* added VMCPTool option '-verbose' (default off)

Issue: #378
Signed-off-by: Keith W. Campbell <keithc@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
@gacholio Can you review?  In particular the stackwalk.h changes

**Comment by gacholio** [comment]
Two things:

1) What is this change for?

2) I really object to changesets that are 90% blank line additions and reordering - makes it very hard to find what to review.

The stackwalk.h change itself seems functionally correct.

**Comment by keithc-ca** [comment]
The new OMR-based DDR generation tool looks for annotations of the form `@ddr_namespace: map_to_type=XXX` for guidance about what namespace the constants belong in. The old annotations were not consistent with the legacy tooling.

**Comment by gacholio** [comment]
jenkins test sanity plinux

**Comment by pshipton** [comment]
> hoping this eventually leads to no constant namespacing at all

I expect we'd have to make a choice to discard the namespaces, check if there are any collisions, and fix up all the DDR code to match.

**Comment by gacholio** [comment]
It's a non-trivial change, to be sure.

**Comment by keithc-ca** [comment]
There shouldn't be any collisions, but adjusting all the references would be tedious.

**Pull request merged**
