### PR TITLE
Add jit support for Reference.reachabilityFence

### PR DESCRIPTION
**Pull request by yanluo7**
Signed-off-by: Yan Luo <yan_luo@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
Can you please add a more detailed commit and pull request message that more fully describes what is involved in this.

**Comment by yanluo7** [comment]
Implemented JIT support for Reference.reachabilityFence API to allow the garbage collector to keep alive the object argument passed in, up to the point of the call.

**Comment by andrewcraik** [comment]
Can you please keep the titles to within the commit guidelines in the CONTRIBUTING.md - the longer description can follow in the commit message body. Thanks!

**Comment by andrewcraik** [comment]
@yanluo7 any idea about the conflicts being reported?

**Comment by charliegracie** [comment]
#589 was just merged which means all open PRs with changes to compiler code will need to be rebased.

**Comment by yanluo7** [comment]
Rebased to solve merge conflicts.

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Pull request merged**
