### PR TITLE
Merge master into jitserver

### PR DESCRIPTION
**Pull request by a7ehuo**
Build against OMR `b372b24c8cb05c9a26f3fc21ffe4e8817ae488d6`: eclipse/openj9-omr#44

### CODE REVIEW

**Comment by a7ehuo** [comment]
b9c7c3d updated the files to eliminate the difference from the `master` branch on extra lines. 

With b9c7c3d and after this rebase, there are still files that are different between the `master` and the `jitaas` branch in three categories: 

1. Files that still need to be updated/merged into the `master` branch from the `jitaas` branch 
```
LICENSE <= https://github.com/eclipse/openj9/pull/6091
longabout.html <=  https://github.com/eclipse/openj9/pull/6091

runtime/compiler/build/toolcfg/gnu/common.mk <= https://github.com/eclipse/openj9/pull/6990
runtime/compiler/codegen/J9TreeEvaluator.cpp <= https://github.com/eclipse/openj9/pull/6909

runtime/compiler/env/VMJ9.cpp <= https://github.com/eclipse/openj9/pull/6909
runtime/compiler/env/VMJ9.h <= https://github.com/eclipse/openj9/pull/6909
runtime/compiler/env/VMJ9Server.cpp <= https://github.com/eclipse/openj9/pull/6909
runtime/compiler/env/VMJ9Server.hpp <= https://github.com/eclipse/openj9/pull/6909
runtime/compiler/il/J9Node.cpp <= https://github.com/eclipse/openj9/pull/7391
runtime/compiler/ilgen/Walker.cpp <= https://github.com/eclipse/openj9/pull/7385
runtime/compiler/net/protos/compile.proto <= https://github.com/eclipse/openj9/pull/6909
runtime/compiler/p/codegen/CallSnippet.cpp <= https://github.com/eclipse/openj9/pull/7386
runtime/compiler/p/codegen/J9PPCInstruction.cpp <= https://github.com/eclipse/openj9/pull/7384
runtime/compiler/p/codegen/PPCJNILinkage.cpp <=https://github.com/eclipse/openj9/pull/7391
runtime/compiler/p/runtime/Recomp.cpp <= https://github.com/eclipse/openj9/pull/7392
runtime/compiler/z/codegen/J9TreeEvaluator.cpp <= https://github.com/eclipse/openj9/pull/6909

runtime/compiler/control/CompilationController.hpp <= update copyright to 2019
runtime/compiler/control/rossa.cpp <= remove white trailing 
runtime/compiler/runtime/CMakeLists.txt <= update to properly indent with tab
test/docs/OpenJ9TestUserGuide.md <= Update JITServer test info 
```

2. Files that will or need to be updated on the `jitaas` branch
```
runtime/compiler/control/JITClientCompilationThread.cpp <= https://github.com/eclipse/openj9/pull/7731
runtime/compiler/control/JITServerCompilationThread.cpp <= https://github.com/eclipse/openj9/pull/7731
runtime/compiler/env/j9method.cpp <= https://github.com/eclipse/openj9/pull/7731
runtime/compiler/env/j9methodServer.cpp <= https://github.com/eclipse/openj9/pull/7731

runtime/compiler/env/JITServerPersistentCHTable.cpp <= TODO: TR_ASSERT or TR_ASSERT_FATAL
```

3. Files that should remain different between the `master` branch and the `jitaas` branch.

```
runtime/compiler/CMakeLists.txt
runtime/compiler/compiler.mk

buildenv/docker/jdk8/s390x/ubuntu16/jitserver/build/Dockerfile
buildenv/docker/jdk8/s390x/ubuntu16/jitserver/buildenv/Dockerfile
buildenv/docker/jdk8/x86_64/rhel7/jitserver/build/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu16/jitserver/build/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu16/jitserver/buildenv/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu18/jitserver/build/Dockerfile
buildenv/docker/jdk8/x86_64/ubuntu18/jitserver/buildenv/Dockerfile
doc/compiler/jitserver/Build.md
doc/compiler/jitserver/Docker.md
doc/compiler/jitserver/Usage.md
```

**Comment by a7ehuo** [comment]
Looked at the rebased files in this PR under  `runtime/compiler/env/` and `runtime/compiler/runtime`, so far looks like only #7724 needs to be implemented for `JITServer`.

**Comment by a7ehuo** [comment]
@mpirvu Ready for review. Thanks! I ran acmeair and didn't observe performance drop. The results are as below: 

=== With master rebase ===
```
Results for JDK=/opt/IBM/DT7/scripts/ahuoScripts/sdk/j2sdk-image-rebased/j2sdk-image jvmOpts=-XX:+UseJITServer -Xjit:dontDowngradeToCold,sampleThreshold=0,scorchingSampleThreshold=0 -Xshareclasses:cacheDir=/opt/IBM/DT7/scripts/ahuoScripts/AcmeAir-mpirvu/AcmeAir/.classCache,name=libertyscc -Xmx256m -Xscmx200m -Xscmaxaot150m -Xaot:forceAOT
Throughput	avg=11312.64	min=11075.90	max=11601.00	stdDev=145.1	maxVar=4.74%	confInt=0.74%	samples=10
Intermediate results:
Run 0	981.4	10968.8	11075.9	Avg=11076	CPU=18387 ms  Footprint=258660 KB
Run 1	1339.1	11176.0	11281.2	Avg=11281	CPU=7473 ms  Footprint=253228 KB
Run 2	1385.0	11337.4	11353.0	Avg=11353	CPU=7451 ms  Footprint=255636 KB
Run 3	1369.3	11407.0	11388.3	Avg=11388	CPU=7433 ms  Footprint=253768 KB
Run 4	1353.6	10939.1	11180.7	Avg=11181	CPU=7135 ms  Footprint=260072 KB
Run 5	1404.7	11430.6	11601.0	Avg=11601	CPU=7624 ms  Footprint=264620 KB
Run 6	1400.2	11331.8	11435.0	Avg=11435	CPU=6957 ms  Footprint=261268 KB
Run 7	1394.3	11151.9	11290.0	Avg=11290	CPU=7396 ms  Footprint=261220 KB
Run 8	1389.9	11127.0	11303.8	Avg=11304	CPU=7390 ms  Footprint=261252 KB
Run 9	1379.2	11188.6	11217.5	Avg=11218	CPU=7358 ms  Footprint=251004 KB
CompTime	avg=8460.40	min=6957.00	max=18387.00	stdDev=3492.8	maxVar=164.29%	confInt=23.93%	samples=10
Footprint	avg=258072.80	min=251004.00	max=264620.00	stdDev=4413.8	maxVar=5.42%	confInt=0.99%	samples=10
```

==== without master rebase === 
```
Results for JDK=/opt/IBM/DT7/scripts/ahuoScripts/sdk/j2sdk-image-jitaas/j2sdk-image jvmOpts=-XX:+UseJITServer -Xjit:dontDowngradeToCold,sampleThreshold=0,scorchingSampleThreshold=0 -Xshareclasses:cacheDir=/opt/IBM/DT7/scripts/ahuoScripts/AcmeAir-mpirvu/AcmeAir/.classCache,name=libertyscc -Xmx256m -Xscmx200m -Xscmaxaot150m -Xaot:forceAOT
Throughput	avg=11291.94	min=10917.60	max=11482.60	stdDev=184.1	maxVar=5.18%	confInt=0.95%	samples=10
Intermediate results:
Run 0	982.9	10823.2	10917.6	Avg=10918	CPU=24824 ms  Footprint=247464 KB
Run 1	1310.3	11045.7	11094.6	Avg=11095	CPU=8290 ms  Footprint=265640 KB
Run 2	1336.3	11248.3	11346.4	Avg=11346	CPU=8310 ms  Footprint=264984 KB
Run 3	1339.2	11148.4	11247.5	Avg=11248	CPU=8344 ms  Footprint=264684 KB
Run 4	1312.7	10993.1	11162.5	Avg=11162	CPU=7495 ms  Footprint=257900 KB
Run 5	1335.2	11255.0	11397.0	Avg=11397	CPU=7314 ms  Footprint=263520 KB
Run 6	1349.5	11442.2	11462.0	Avg=11462	CPU=7865 ms  Footprint=269504 KB
Run 7	1345.6	11233.1	11440.7	Avg=11441	CPU=7657 ms  Footprint=260280 KB
Run 8	1347.0	11207.8	11368.5	Avg=11368	CPU=7455 ms  Footprint=261976 KB
Run 9	1342.7	11457.9	11482.6	Avg=11483	CPU=7628 ms  Footprint=262736 KB
CompTime	avg=9518.20	min=7314.00	max=24824.00	stdDev=5391.3	maxVar=239.40%	confInt=32.83%	samples=10
Footprint	avg=261868.80	min=247464.00	max=269504.00	stdDev=5957.4	maxVar=8.91%	confInt=1.32%	samples=10
```

**Comment by mpirvu** [comment]
I evaluated the performance of AcmeAir with this PR and it's stable

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#44

**Comment by mpirvu** [comment]
For Java 11 I am seeing the following failures

J9vmTest_4 | 3 min 31 sec |  
```
Type=Segmentation error vmState=0x0005ffff
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F9B32ECBA40 Handler2=00007F9B327B0010 InaccessibleAddress=0000001200000028
RDI=00000000019CF600 RSI=00000000FF182900 RAX=0000001200000000 RBX=0000000000000004
RCX=00007F9B2C0103F0 RDX=0000000000000000 R8=00007F9B30F0380D R9=000000000000001D
R10=00007F9B3136DAC0 R11=0000000000000206 R12=000000000000001D R13=00007F9B30F37DEA
R14=00000000019CF600 R15=0000000000000004
RIP=00007F9B32EF0E2F GS=0000 FS=0000 RSP=00007F9B134BA410
EFlags=0000000000010246 CS=0033 RBP=00000000FF182900 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000001200000028
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm4 000000ff00000000 (f: 0.000000, d: 5.411089e-312)
xmm5 ffff000000000000 (f: 0.000000, d: -nan)
xmm6 0000180080000000 (f: 2147483648.000000, d: 1.303860e-310)
xmm7 0200100000000400 (f: 1024.000000, d: 4.796975e-299)
xmm8 0000000000000001 (f: 1.000000, d: 4.940656e-324)
xmm9 0004000000000400 (f: 1024.000000, d: 5.562685e-309)
xmm10 ffffffffffffffff (f: 4294967296.000000, d: -nan)
xmm11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so
Module_base_address=00007F9B32E2C000

Method_being_compiled=java/lang/invoke/BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(I)I
.......
*** Test FAILED *** (j9vm.test.arraylets.ArrayletAllocateTest)
```



228 - - JLM_Tests_interface_1
```
===============================================
    TestMemoryManagerMXBean
    Tests run: 9, Failures: 0, Skips: 0
===============================================

#0: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x8a3635) [0x7f19938d6635]
#1: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x8af840) [0x7f19938e2840]
#2: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x171e4e) [0x7f19931a4e4e]
#3: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x2023a) [0x7f1999cd723a]
#4: /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7f199c065390]
#5: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so(+0xc4dc0) [0x7f199a417dc0]
#6: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so(+0xc55de) [0x7f199a4185de]
#7: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so(+0xc5882) [0x7f199a418882]
#8: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so(+0xc5907) [0x7f199a418907]
#9: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1cffb2) [0x7f1993202fb2]
#10: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1c5302) [0x7f19931f8302]
#11: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1f5fbf) [0x7f1993228fbf]
#12: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x2ce83b) [0x7f199330183b]
#13: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x2d4f66) [0x7f1993307f66]
#14: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1842e1) [0x7f19931b72e1]
#15: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x184f81) [0x7f19931b7f81]
#16: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x20d73) [0x7f1999cd7d73]
#17: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x186b95) [0x7f19931b9b95]
#18: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x18712e) [0x7f19931ba12e]
#19: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x182df3) [0x7f19931b5df3]
#20: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1832e2) [0x7f19931b62e2]
#21: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x18338a) [0x7f19931b638a]
#22: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x20d73) [0x7f1999cd7d73]
#23: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1837b4) [0x7f19931b67b4]
#24: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9thr29.so(+0xe146) [0x7f199a146146]
#25: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f199c05b6ba]
#26: function clone+0x6d [0x7f199b97c41d]
Unhandled exception
Type=Segmentation error vmState=0x0005ffff
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F199A3F2A40 Handler2=00007F1999CD7010 InaccessibleAddress=0000000000000008
RDI=00000000010D3E00 RSI=0000000000000000 RAX=00007F1974A186A8 RBX=0000000000000010
RCX=0000000000000010 RDX=00007F1993B1C82B R8=00007F1993B222F6 R9=0000000000000012
R10=00007F1993F86AC0 R11=00007F199BA09F90 R12=0000000000000012 R13=00007F1993B1C82B
R14=00000000010D3E00 R15=0000000000000010
RIP=00007F199A417DC0 GS=0000 FS=0000 RSP=00007F1974A18410
EFlags=0000000000010202 CS=0033 RBP=0000000000000000 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000008
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm8 0000000004000000 (f: 67108864.000000, d: 3.315618e-316)
xmm9 0000044020020000 (f: 537001984.000000, d: 2.308997e-311)
xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm11 0000000049d70a38 (f: 1238829568.000000, d: 6.120632e-315)
xmm12 000000004689a022 (f: 1183424512.000000, d: 5.846894e-315)
xmm13 0000000047ac082f (f: 1202456576.000000, d: 5.940925e-315)
xmm14 0000000048650dc0 (f: 1214582272.000000, d: 6.000833e-315)
xmm15 0000000046b73e38 (f: 1186414080.000000, d: 5.861665e-315)
Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so
Module_base_address=00007F199A353000

Method_being_compiled=java/lang/invoke/AsTypeHandle.invokeExact_thunkArchetype_X(I)I
```

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#44

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#44

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#44

**Comment by mpirvu** [comment]
The only test failing is the known `cmdLineTester_gcsuballoctests_0`, hence merging.

**Pull request merged**
