### PR TITLE
Cache well-known class chain offsets in JITServer client session

### PR DESCRIPTION
**Pull request by AlexeyKhrabrov**
Every AOT compilation using SVM at the JITServer sends a SharedCache_storeSharedData message to the client in SymbolValidationManager::populateWellKnownClasses(). Most of these calls return a pointer to the same existing version of well-known class chain offsets in the client's SCC (after all well-known classes are loaded, which normally happens early on during start-up). To avoid these repeated messages, we cache the pointers to well-known class chain offsets in the ClientSession. The key in the map is a combination of the bit mask describing included classes and the list of ROMClass offsets in the client's SCC, and the value is the client-side pointer to the well-known class chain offsets structure in the SCC. This replicates the behaviour of the underlying SCC store operation: a new structure is created only if the bit mask (used as the SCC key) is different, or if the contents (the list of ROMClass offsets) are different.

Closes: #11137

### CODE REVIEW

**Comment by AlexeyKhrabrov** [comment]
Here are some message statistics for an AcmeAir + jmeter run (forceAOT is enabled, SVM at startup is disabled).
Before the change:
`
JITServer Message Type Statistics:
Type# #called           Max             Min             Mean            StdDev          Sum             TypeName
...
#0198    3835   176.000000      176.000000      176.000000      0.000000        674960.000000           SharedCache_storeSharedData
...
Total number of messages: 434623. Average number of messages per compilation:43.584335
`
After the change:
`
JITServer Message Type Statistics:
Type# #called           Max             Min             Mean            StdDev          Sum             TypeName
...
#0198       1   176.000000      176.000000      176.000000      0.000000        176.000000              SharedCache_storeSharedData
...
Total number of messages: 426660. Average number of messages per compilation:42.919224
`

**Comment by AlexeyKhrabrov** [comment]
@mpirvu This PR is ready for review.

**Review by mpirvu — COMMENTED** [review]
LGTM.
I see that for an AOT compilation, the client does not issue `populateWellKnownClasses()` but the server does and it comes back to the client. One other idea could be to allow the client to call `populateWellKnownClasses()` and pass the pointer that we get back to the server, together with the compilation request. Would such an approach save messages resulting from `rememberClass()` which is called for every class from the known set at the beginning of the compilation?

**Comment by AlexeyKhrabrov** [comment]
> One other idea could be to allow the client to call `populateWellKnownClasses()` and pass the pointer that we get back to the server, together with the compilation request. Would such an approach save messages resulting from `rememberClass()` which is called for every class from the known set at the beginning of the compilation?

It would only save a handful of messages for the first few AOT compilations if SVM is enabled during start-up, since the class chains are cached at the server. It might be a cleaner solution since it doesn't introduce an additional cache map in the client session. But it would move a bit of overhead (looking up class chains) from the server to the client (although it's likely negligible). Which option do you prefer?

**Comment by mpirvu** [comment]
I guess we don't want more overhead at the client. However, I am thinking that the map at the server is overkill. Maybe it's better to have a new data structure `WelKnownClassesCache` which includes the key and the value from your proposed map. In this case you don't need a string because you'll always compare the key for equality, piece by piece.

**Comment by AlexeyKhrabrov** [comment]
I'm not sure if I understand your suggestion correctly. Should the map itself be a part of a separate class/struct instead of a member of ClientSessionData? I think an easy way to avoid using `std::string` (and a separate memory allocation for the list of offsets) is to store the map key as something like `std::pair<uintptr_t, std::array<uintptr_t, WELL_KNOWN_CLASS_COUNT>>` (can be a typedef for readability).

**Comment by AlexeyKhrabrov** [comment]
Not using `std::string` will require adding a bit more code, for instance an `std::hash` specialization. The map will normally contain only a few entries, so I'm not sure if avoiding these few extra memory allocations is worth it. Your call.

**Comment by mpirvu** [comment]
I was thinking that the map, logically, contains exactly one entry (the most current one) with older entries being just stale. Correct me if I am wrong on this one. If that's the case, we don't need a map at all, just a struct that holds what would have been the key and the value in the map entry.

**Comment by AlexeyKhrabrov** [comment]
I see what you mean now. I think you're right - we can keep only the most recent version, and if its key is different from what `populateWellKnownClasses()` wants to store, we send the message to the client and overwrite the cached key and value. I'll make the changes.

**Comment by AlexeyKhrabrov** [comment]
@mpirvu Changes made, ready for another review.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit jdk11

**Comment by mpirvu** [comment]
There is one failure on x86, but this has happened before:

```
Running test cmdLineTester_jvmtitests_7
...
Testing: emeng001
Test start time: 2020/11/12 03:40:51 Eastern Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal_testList_0/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump    -agentlib:jvmtitest=test:emeng001 -cp "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal_testList_0/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
Time spent starting: 4 milliseconds
Time spent executing: 320 milliseconds
Test result: FAILED
Output from test:
 [ERR] JITServer is currently a technology preview. Its use is not yet supported
 [ERR] Exception in thread "main" java/lang/NullPointerException
 [ERR] 	at java/lang/String.hashCodeImplDecompressed (java.base@9/String.java:4294967295)
 [ERR] 	at java/lang/String.hashCode (java.base@9/String.java:1894)
 [ERR] 	at java/util/concurrent/ConcurrentHashMap.putVal (java.base@9/ConcurrentHashMap.java:1012)
 [ERR] 	at java/util/concurrent/ConcurrentHashMap.put (java.base@9/ConcurrentHashMap.java:1006)
 [ERR] 	at java/util/Properties.put (java.base@9/Properties.java:1340)
 [ERR] 	at java/lang/System.ensureProperties (java.base@9/System.java:325)
 [ERR] 	at java/lang/System.afterClinitInitialization (java.base@9/System.java:127)
 [ERR] 	at java/lang/Thread.initialize (java.base@9/Thread.java:378)
 [ERR] 	at java/lang/Thread.<init> (java.base@9/Thread.java:154)
>> Success condition was not found: [Return code: 0]
```
I am going to trigger the testing again to prove that this PR has not made this issue more frequent.

**Comment by mpirvu** [comment]
jenkins test sanity xlinuxjit jdk11

**Comment by mpirvu** [comment]
Tests have passed, hence this PR is ready to be merged.

**Pull request merged**
