### PR TITLE
Update to for changes coming in OMR PR1764

### PR DESCRIPTION
**Pull request by charliegracie**
This change provides defines for macros that were renamed in OMR and also changes function calls to the new names used in OMR.

This change is dependent on eclipse/omr#1764 and should only be merged once the OMR PR is merged.

### CODE REVIEW

**Comment by charliegracie** [comment]
Jenkins test sanity depends eclipse/omr#1764

**Comment by charliegracie** [comment]
I expect the travis build to fail since the dependency on OMR can not be specified.

**Comment by charliegracie** [comment]
The dependent eclipse/omr#1764 has been merged.  Once that code makes it into the OpenJ9 OMR repo you can merge this PR.  Thanks

**Comment by pshipton** [comment]
Started a new pipeline build to include the OpenJ9 changes.
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OMR-Acceptance/61/

**Pull request merged**
