### PR TITLE
enable dynamic parallel in extended.functional_x86-64_linux_Nightly

### PR DESCRIPTION
**Pull request by llxia**
[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
jenkins test sanity xlinux jdk8

**Comment by llxia** [comment]
jenkins test extended xlinux jdk11

**Comment by llxia** [comment]
Tested internally in personal build using 
```
if (testJobName.contains("extended.functional_x86-64_linux_Personal")) {
``` 
`Pipeline-Build-Test-Personal/6106/` triggered test build in parallel `Test_openjdk8_j9_extended.functional_x86-64_linux_Personal/206/` and `Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Personal/44/` remains in serial.

**Comment by llxia** [comment]
FYI @pshipton @AdamBrousseau

**Comment by pshipton** [comment]
Awesome. @smlambert are you ready to merge? After merge I'll start a "nightly" build for testing.

**Comment by AdamBrousseau** [comment]
If we'd rather get this merged now, I can move it in a follow-up PR.

**Comment by llxia** [comment]
> I think this should be moved into the variable file.

Move to the variable file means we have the values set twice (in openj9 and internal variable file respectively), correct?

**Comment by AdamBrousseau** [comment]
>values set twice (in openj9 and internal variable file

Yes

**Comment by AdamBrousseau** [comment]
Also realized this would only apply specifically for the nightly build.  Is there a specific reason for this?

**Comment by llxia** [comment]
> Also realized this would only apply specifically for the nightly build. Is there a specific reason for this?

Due to the limited machines, the plan is to start with nightly, observe the jobs, and adjust as needed going forward.

Since the test params are the same for openj9 and internal and we will adjust them as needed in the near future, I will prefer to keep it in pipeline-functions.groovy. If you still prefer to put them in the variable file, could we do a follow-up PR for it?

**Comment by pshipton** [comment]
> we will adjust them as needed in the near future

What I'm thinking, if this goes well, we'll aim for something like
- roll this out for all platforms, and all builds
- maybe adjust the number of machines to 3 for extended.functional
- add parallel for sanity.functional, all platforms/builds, 2 machines

**Comment by AdamBrousseau** [comment]
So it sounds like we want smart parallelization for the targets today but not the number of machine buckets (yet). Maybe this is a good idea. I think the number of buckets is significantly harder to "calculate". It should depend on several factors and the more factors we can incorporate into the calculation the better we can predict the best number.

**Comment by smlambert** [comment]
Yes, I will merge this as-is, as the intended plan is to observe how this approach works.

In fact, we may find that the very simple approach of setting NUM_MACHINES to a low number greater than 1 and putting a 'cap' on it, by checking the number of online machines, dividing by 2 to say you are limited by that cap, is as good as any more sophisticated approach that may be introduced.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-All-11/178/

**Comment by llxia** [comment]
[Parent test build](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly/362/) triggers two test builds:


| Test Build | Time |
--- | --- |
| [Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly_testList_0](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly_testList_0/1/ ) | 1h58m |
| [Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly_testList_1](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly_testList_1/1/ ) | 2h23m |

Parallel test build total time: 2h31m
[Serial test build](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly/buildTimeTrend): 4h+

**Comment by smlambert** [comment]
Not too shabby for falling back to default timings!  :)

**Comment by pshipton** [comment]
I think this is wonderful. Being able to run the test in 2:23 instead of 4h is a big improvement!

**Pull request merged**
