### PR TITLE
Declare obsolete J9_JAVA constants in DDR blob for compatibility

### LINKED ISSUE #6316: Removing duplicate macros used by DDR breaks the IBM DTFJ MAT plugin
https://github.com/eclipse/openj9/issues/4198 breaks the "IBM Diagnostic Tool Framework for Java" plugin used by Eclipse MAT to read OpenJ9 system dumps. There doesn't seem to be a plugin update from IBM available to resolve it.

```
java.lang.NoSuchFieldError: com/ibm/j9ddr/vm29/structure/J9Consts.J9_JAVA_CLASS_RAM_ARRAY
	at com.ibm.j9ddr.vm29.pointer.helper.J9ClassHelper.isArrayClass(J9ClassHelper.java:72)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectModel_V1.isIndexable(GCObjectModel_V1.java:188)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectModel_V1.isIndexable(GCObjectModel_V1.java:182)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectModel_V1.getSizeInBytesWithHeader(GCObjectModel_V1.java:157)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectModel_V1.getConsumedSizeInBytesWithHeader(GCObjectModel_V1.java:90)
	at com.ibm.j9ddr.vm29.j9.ObjectModel.getConsumedSizeInBytesWithHeader(ObjectModel.java:199)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectHeapIteratorAddressOrderedList_V1.advanceScanPointer(GCObjectHeapIteratorAddressOrderedList_V1.java:169)
	at com.ibm.j9ddr.vm29.j9.gc.GCObjectHeapIteratorAddressOrderedList_V1.next(GCObjectHeapIteratorAddressOrderedList_V1.java:244)
	at com.ibm.j9ddr.vm29.j9.walkers.HeapWalker.walk(HeapWalker.java:107)
	at com.ibm.j9ddr.vm29.view.dtfj.java.j9.HeapObjectIterator.hasNext(HeapObjectIterator.java:38)
	at com.ibm.j9ddr.vm29.view.dtfj.java.DTFJJavaHeap$1.hasNext(DTFJJavaHeap.java:106)
	at org.eclipse.mat.dtfj.DTFJIndexBuilder.fill(DTFJIndexBuilder.java:1138)
	at org.eclipse.mat.parser.internal.SnapshotFactoryImpl.parse(SnapshotFactoryImpl.java:222)
	at org.eclipse.mat.parser.internal.SnapshotFactoryImpl.openSnapshot(SnapshotFactoryImpl.java:126)
	at org.eclipse.mat.snapshot.SnapshotFactory.openSnapshot(SnapshotFactory.java:145)
	at org.eclipse.mat.ui.snapshot.ParseHeapDumpJob.run(ParseHeapDumpJob.java:83)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

The error message is for J9Consts.J9_JAVA_CLASS_ARRAY, but looking at the PR changes, some or all of the following will also be problematic. They are listed with the replacement macro. I expect we can declare these in the DDR blob to get the old DTFJ plugin working again.

J9_JAVA_CLASS_ARRAY J9AccClassArray
J9_JAVA_CLASS_REFERENCE_MASK J9AccClassReferenceMask
J9_JAVA_CLASS_GC_SPECIAL J9AccClassGCSpecial
J9_JAVA_CLASS_RAM_SHAPE_SHIFT J9AccClassRAMShapeShift
J9_JAVA_STATIC J9AccStatic
J9_JAVA_CLASS_RAM_ARRAY J9AccClassRAMArray
J9_JAVA_INTERFACE J9AccInterface
J9_JAVA_CLASS_DEPTH_MASK J9AccClassDepthMask
J9_JAVA_CLASS_HOT_SWAPPED_OUT J9AccClassHotSwappedOut
J9_JAVA_INTERFACE J9AccInterface
J9_JAVA_CLASS_DYING J9AccClassDying
J9_JAVA_NATIVE J9AccNative

### PR DESCRIPTION
**Pull request by pshipton**
Closes #6316

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile plinux jdk8

**Comment by pshipton** [comment]
Confirmed Eclipse MAT was able to open a core file that includes these changes.

**Comment by DanHeidinga** [comment]
Jenkins test sanity,extended zlinux jdk8

**Comment by DanHeidinga** [comment]
@pshipton this seems like a good candidate for 0.15.0 as well.  Can you prepare a PR for that stream as well?

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9/pull/6321 for the 0.15.0 release.

**Comment by DanHeidinga** [comment]
Thanks @pshipton I've merged the 0.15.0 version as well

**Pull request merged**
