### PR TITLE
Rename -XX:+StringCompression to -XX:+CompactStrings

### LINKED ISSUE #948: Rename -XX:+StringCompression to -XX:+CompactStrings
OpenJDK introduced String compression in Java 9 which seems to be enabled by default and is guarded with option `-XX:+CompactStrings`. We have a different implementation of String compression but we piggyback off of OpenJDK JCL (StringCoding for example, among others) for certain APIs.

To avoid intorducing confusion and unnecessary JDK differences we should rename `-XX:+StringCompression` to `-XX:+CompactStrings` for JDK compatibility.

### PR DESCRIPTION
**Pull request by pshipton**
Use the same option as OpenJDK for compatibility.

Closes: #948

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Thanks for this! More compatibility is always a good thing.

**Comment by fjeremic** [comment]
Thanks for this! More compatibility is always a good thing.

Jenkins test all

**Comment by pshipton** [comment]
I have a fix for the commit comment footer, but I won't push it yet since that will remove the links to the PR testing (although it doesn't seem to be working anyway).

**Comment by pshipton** [comment]
Some of the ppcle testing failed because there is something wrong with the ub16-ppcle-4 machine. Not sure if they need to be re-run, there seems to be adequate coverage by the other tests.

**Comment by fjeremic** [comment]
> Some of the ppcle testing failed because there is something wrong with the ub16-ppcle-4 machine. Not sure if they need to be re-run, there seems to be adequate coverage by the other tests.

I agree. I'll merge as soon as you push the amended commit.

**Comment by pshipton** [comment]
The commit is updated

**Comment by pshipton** [comment]
Guess I'll rebase to fix the copyright failures, they are not caused by this change.

**Comment by fjeremic** [comment]
Skipping CI testing on https://github.com/eclipse/openj9/pull/1177/commits/a84b4f42b0dad319e8fde7bf16f4cc9753a66e16 due to https://github.com/eclipse/openj9/pull/1177#issuecomment-365790204.

**Pull request merged**
