### PR TITLE
Add workflows for auto test exclusion

### PR DESCRIPTION
**Pull request by renfeiw**
- autoTestPR for auto exclusion
- rmAutoTestPRBranch for deleting branch after PR is closed

[ci skip]

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewers: @smlambert @llxia

**Comment by llxia** [comment]
With this PR, we can use auto test exclusion at openj9. Please see readme at https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/doc/userGuide.md#automatically-exclude-a-test-target

**Comment by llxia** [comment]
Please update after PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/2244

**Comment by renfeiw** [comment]
> Please update after PR [AdoptOpenJDK/openjdk-tests#2244](https://github.com/AdoptOpenJDK/openjdk-tests/pull/2244)

Updated, thanks!

**Comment by llxia** [comment]
This PR adds the github workflow and it cannot be tested with PR builds. Therefore, I will forgo the PR builds.

**Review by llxia — APPROVED** [review]
LGTM. We will have further enhancements added in the future PR. i.e., update year in the copyright, add `test excluded` label in the issue, etc.

**Pull request merged**
