### PR TITLE
Use FrontEnd implementations of instanceOfOrCheckCast routines

### PR DESCRIPTION
**Pull request by dchopra001**
This PR is a double delivery of #6909

### CODE REVIEW

**Comment by dchopra001** [comment]
@mpirvu Can I get a review please?

**Comment by mpirvu** [comment]
Jenkins test sanity plinuxjit jdk8,jdk11

**Comment by mpirvu** [comment]
Many tests fails with
```
JVMJ9VM011W Unable to load j9jit29: libssl.so.1.1: cannot open shared object file: No such file or directory
JVMJ9VM004E Cannot load library required by: -Xjit
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
no-zero exit value: 1
```
I'll see if the situation is the same on xlinux

**Comment by mpirvu** [comment]
Jenkins test sanity xlinuxjit jdk8

**Comment by mpirvu** [comment]
@dchopra001 @a7ehuo JITServer testing on Power fails due to inability to find libssl.so.1.1.  See error message above. It works on x86

**Comment by a7ehuo** [comment]
Likely the build and the test machines don't have the right version of `OpenSSL` installed, which is required to load and run `JITServer`. 

It's built against the fetched OpenSSL `1.1.1d (0x1010104fL)` for `linux-ppc64le` that is stored under the build directory `/home/jenkins/workspace/Build_JDK8_ppc64le_linux_jit_Personal/openssl`. 

```
18:33:50  + bash configure --with-freemarker-jar=/home/jenkins/freemarker.jar --with-boot-jdk=/usr/lib/jvm/adoptojdk-java-11 --enable-cuda --with-cuda=/usr/local/cuda-9.0 --with-openssl=fetched --enable-jitserver=yes
```

But when it runs to load `libj9jit.so`, it will link against the system installed `OpenSSL` which might not be installed or installed with a lower version.

**Comment by dchopra001** [comment]
@a7ehuo Do you know what the fix would be here?

**Comment by a7ehuo** [comment]
@AdamBrousseau helped check the machines that failed builds/tests have `1.0.2g` installed. When enabling OpenSSL is checked in, the PPC linux Jenkins build passed with a machine that has `1.1.1b` installed. (https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_jit_Personal/8/consoleFull). Will open an infrastructure issue to have the OpenSSL updated on these PPC linux machines.

**Comment by mpirvu** [comment]
Jenkins test sanity all jdk8

**Comment by mpirvu** [comment]
Since the failures seen here have nothing to do with the PR changes, I trigerred non-jitserver tests. I expect those to pass and I will merge this item at that time.

**Comment by mpirvu** [comment]
Jenkins test sanity all jdk11

**Comment by mpirvu** [comment]
All tests have passed, hence merging.

**Pull request merged**
