### PR TITLE
Improve attach API access checking

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Ensure that files have the correct owner and access permissions,
delete suspect directories instead of re-using them.

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk8

**Comment by pshipton** [comment]
jenkins test sanity win jdk8

**Comment by pdbain-ibm** [comment]
Travis build failure unrelated:
```
J9Optimizer.cpp:(.text._ZN27TR_JProfilingRecompLoopTestC2EPN2TR19OptimizationManagerE[_ZN27TR_JProfilingRecompLoopTestC5EPN2TR19OptimizationManagerE]+0x2a): undefined reference to `vtable for TR_JProfilingRecompLoopTest'
```

**Comment by pshipton** [comment]
NPT ERROR failures are unrelated.

**Pull request merged**
