### PR TITLE
Purge deprecated  code from compiler

### PR DESCRIPTION
**Pull request by nanjekyejoannah**
Purge deprecated code from the compiler.

This commit removes the MTUnresolvedXXX code that is deprecated. The helpers have been purged from each code generator and runtime.

Closes: #1116 
Signed-off-by: Joannah Nanjekye <nanjekyejoannah@gmail.com>

### CODE REVIEW

**Comment by nanjekyejoannah** [comment]
@0xdaryl I have done necessary changes. PTAL. Thanks for the review.

**Comment by andrewcraik** [comment]
@0xdaryl / @nanjekyejoannah is this still relevant or should we close it since it has been open for nearly a year with no activity?

**Comment by 0xdaryl** [comment]
This is still a valid requirement, although the PR has gone stale and needs a rebase.  Sorry I missed your previous comment asking for a review.

Would you mind rebasing this so that we can resume the review process?   Unfortunately, I believe the dates on the files will need to be changed to 2019 as well or else the copyright check will fail.

**Comment by 0xdaryl** [comment]
These helpers were purged as part of #8379 several months back.  Closing.

**Pull request closed without merging**
