### PR TITLE
Remove redundant SSE availability check from JIT

### PR DESCRIPTION
**Pull request by 0dvictor**
As VM guarantees SSE/SSE2 available, JIT should never reach a
state that SSE/SSE2 is unsupported. Therefore, removing such
redundant checks from jit.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by 0dvictor** [comment]
As @DanHeidinga pointed out, VM ensures that SSE/SSE2 is supported, otherwise it would refuse to start JVM. There is no chance that JIT might reach into a state where SSE/SSE2 is not available. Therefore, SSE/SSE2 availability checks should be removed from JIT.
Further details can be found from `jvminit.c`

**Comment by andrewcraik** [comment]
@0xdaryl would appreciate your input on this - I think it looks good. Since there are changes to files used on multiple platforms I will fire sanity

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by andrewcraik** [comment]
@0dvictor could you checkout the copyright failure?

**Comment by 0dvictor** [comment]
The copyrights have been updated.

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by andrewcraik** [comment]
@AdamBrousseau we are seeing:
`15:06:51 downloading https://adopt-openjdk.ci.cloudbees.com/view/OpenJDK/job/asmtools/ws/asmtools-6.0-build/release/lib/asmtools.jar 
15:06:51 ERROR: sha1 sum check error.`
Since the build is clean apart from that I'm inclined to merge, but wanted your input on why this is happening.

**Comment by AdamBrousseau** [comment]
>ERROR: sha1 sum check error

This is a test issue that @TianyuZuo is fixing. I'm not sure if he has an issue for it.
>Since the build is clean apart from that

The compiles are "clean" but no testing has been run on any platform

**Comment by AdamBrousseau** [comment]
Looks like he has a temp fix in #280 waiting to be merged

**Comment by AdamBrousseau** [comment]
Jenkins test sanity

**Pull request merged**
