### PR TITLE
Avoid recursive crashes when dumping current IL during jitdump generation

### PR DESCRIPTION
**Pull request by fjeremic**
- Rename a few functions in JitDump.cpp to more meaningful names
- Standardize flags passed to `j9sig_protect`
- Fix types used for OMR APIs
- Remove unneeded ifdefs
- Only `sig_protect` methods that can crash
- Ensure the closing XML tag is always printed
- Properly print the symbol reference table
- Add comments to tricky places in the code

Closes: #9227

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Suggesting @dsouzai for review/committer.

**Review by dsouzai — COMMENTED** [review]
LGTM. One question regarding:
```
uintptr_t
jitDumpSignalHandler(struct J9PortLibrary *portLibrary, uint32_t gpType, void *gpInfo, void *handler_arg)
   {
   TR_VerboseLog::writeLineLocked(TR_Vlog_JITDUMP, "vmThread = %p Recursive crash occurred. Aborting JIT dump.", reinterpret_cast<J9VMThread*>(handler_arg));

   // Returning J9PORT_SIG_EXCEPTION_RETURN will make us come back to the same crashing instruction over and over
   //
   return J9PORT_SIG_EXCEPTION_RETURN;
   }
```
that comment makes it seem like we shouldn't return `J9PORT_SIG_EXCEPTION_RETURN`. Maybe this comment should be updated? I didn't see this comment in `blankSignalHandler`

**Comment by fjeremic** [comment]
> that comment makes it seem like we shouldn't return `J9PORT_SIG_EXCEPTION_RETURN`. Maybe this comment should be updated? I didn't see this comment in `blankSignalHandler`

Yeah the comment is wrong. Also the verbose output is unguarded. I plan on addressing this in the last round of cleanup. I plan to use proper VM tracepoints for everything and add documentation to entire JitDump.cpp.

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8

**Review by dsouzai — APPROVED** [review]

**Comment by fjeremic** [comment]
This one should be good to go.

**Pull request merged**
