### PR TITLE
Move lookupswitch match order verification to second pass

### PR DESCRIPTION
**Pull request by sharon-wang**
Related: https://github.com/eclipse/openj9/issues/9323, https://github.com/eclipse/openj9/issues/9336, https://github.com/eclipse/openj9/issues/9357

Demonstrated in the related issues, it appears that the verification of `lookupswitch` bytecode order is being done too early. For example, in #9323, the test results in `java.lang.VerifyError: JVMCFRE072 entries not sorted in lookupswitch bytecode` instead of a `NoClassDefFoundError`, which the reference implementation throws. Moving the `lookupswitch` bytecode order check to the second verification pass should be more appropriate timing.

This PR moves the `lookupswitch` check to the second verification pass. I have tested these changes against the related issues listed above and the test output now matches the user's expected output/RI output.

---

Moving the `lookupswitch` check to the second pass verification appears to be working as expected (shown in the output below). However, there is less detail in the exception message. Do we want to maintain the same level of exception message detail?

Previous exception message:
```
Exception in thread "main" java.lang.VerifyError: JVMCFRE072 entries not sorted in lookupswitch bytecode; class=Example, method=sampleSwitch()V, pc=4
Exception Details:
  Location:
    Example.sampleSwitch()V @4: JBlookupswitch
  Reason:
    Error exists in the bytecode.
  Stackmap Table:
    append_frame(@32,integer)
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:479)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:440)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:392)
	at CustomClassLoader.getClass(Main.java:32)
	at Main.main(Main.java:18)
```

Exception message after relocated `lookupswitch` order check:
```
Exception in thread "main" java.lang.VerifyError: JVMVRFY043 entries not sorted in lookupswitch bytecode; class=Example, method=sampleSwitch()V, pc=4
	at java.base/java.lang.J9VMInternals.prepareClassImpl(Native Method)
	at java.base/java.lang.J9VMInternals.prepare(J9VMInternals.java:342)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:803)
	at Main.main(Main.java:21)
```

@gacholio Please review. Should a new test be added to confirm these changes are working?

### CODE REVIEW

**Comment by gacholio** [comment]
I don't think a test needs to be added - it's unlikely the code would ever be accidentally moved back.

**Comment by gacholio** [comment]
I think it would be best not to move the NLS message. Including the appropriate header should work - NLS messages are not tied to any particular VM module/directory.

**Comment by gacholio** [comment]
@DanHeidinga What do you think about the NLS message?

Also, in the "after" example exception, there's a lot less detail. Is that how it is with all of the 2nd pass exceptions?

**Comment by sharon-wang** [comment]
@gacholio yes there's much less detail in the second pass, since only these fields are set:
https://github.com/eclipse/openj9/blob/49b6ce63ea00fbaa1cd8cb51fe9d8bed84c84123/runtime/oti/bcverify.h#L64-L67

whereas in the first pass, there's quite a bit more:
https://github.com/eclipse/openj9/blob/49b6ce63ea00fbaa1cd8cb51fe9d8bed84c84123/runtime/verutil/cfrerr.c#L170-L201

**Comment by sharon-wang** [comment]
@gacholio I was able to match the level of detail from the first pass by leveraging `storeVerifyErrorData()` in https://github.com/eclipse/openj9/pull/9660/commits/e9194a3477708ce25e52ff95ea2cdf264d5d9578.

With these changes, the 2nd pass lookupswitch error message looks like this:

```
Exception in thread "main" java.lang.VerifyError: JVMVRFY043 entries not sorted in lookupswitch bytecode; class=Example, method=sampleSwitch()V, pc=4
Exception Details:
  Location:
    Example.sampleSwitch()V @4: JBlookupswitch
  Reason:
    Error exists in the bytecode.
  Stackmap Table:
    append_frame(@32,integer)
	at java.base/java.lang.J9VMInternals.prepareClassImpl(Native Method)
	at java.base/java.lang.J9VMInternals.prepare(J9VMInternals.java:342)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:803)
	at Main.main(Main.java:21)
```

1st pass error message for comparison:
```
Exception in thread "main" java.lang.VerifyError: JVMCFRE072 entries not sorted in lookupswitch bytecode; class=Example, method=sampleSwitch()V, pc=4
Exception Details:
  Location:
    Example.sampleSwitch()V @4: JBlookupswitch
  Reason:
    Error exists in the bytecode.
  Stackmap Table:
    append_frame(@32,integer)
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:479)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:440)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:392)
	at CustomClassLoader.getClass(Main.java:32)
	at Main.main(Main.java:18)
```

I added `BCV_ERR_BYTECODE_ERROR` = `"Error exists in the bytecode."` - not sure if this is ideal. The only other existing error that is similar is `BCV_ERR_BAD_BYTECODE` = `"The bytecode is unrecognizable."` However, both our current implementation and the RI use `"Error exists in the bytecode"` as the reason.

Reference implementation output:
```
Exception in thread "main" java.lang.VerifyError: Bad lookupswitch instruction
Exception Details:
  Location:
    Example.sampleSwitch()V @4: lookupswitch
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 1006 3c1b ab00 0000 0000 001c 0000 0002
    0000010: 0000 0006 0000 001c 0000 0001 0000 001c
    0000020: b1                                     
  Stackmap Table:
    append_frame(@32,Integer)

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3215)
	at java.base/java.lang.Class.getConstructor0(Class.java:3420)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2631)
	at Main.main(Main.java:21)
```

**Comment by DanHeidinga** [comment]
> I think it would be best not to move the NLS message. Including the appropriate header should work - NLS messages are not tied to any particular VM module/directory.

> What do you think about the NLS message?

It's convenient when the messages map nice to a directory or set of code but I don't think that's worth preserving here.  Keeping the original message makes sense and reusing the original location saves adjusting the translation files.

I'm onboard with not moving it

**Comment by sharon-wang** [comment]
An update: NLS message is in the original location - only the lookupswitch order check has been moved.

The `VerifyError` output now looks like:
```
Exception in thread "main" java.lang.VerifyError: JVMVRFY072 ; class=Example, method=sampleSwitch()V, pc=4
	at java.base/java.lang.J9VMInternals.prepareClassImpl(Native Method)
	at java.base/java.lang.J9VMInternals.prepare(J9VMInternals.java:342)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:803)
	at Main.main(Main.java:21)
```

@gacholio Please review

**Comment by gacholio** [comment]
The message seems to have lost its detail again. Is it not possible to use the detailed error message when using the old NLS key?

**Comment by sharon-wang** [comment]
I had to update `errorModule` so that it looks in CFR_ERR for the NLS message instead of the default BCV_ERR. Looks correct now.

Error message output:
```
Exception in thread "main" java.lang.VerifyError: JVMCFRE072 entries not sorted in lookupswitch bytecode; class=Example, method=sampleSwitch()V, pc=4
	at java.base/java.lang.J9VMInternals.prepareClassImpl(Native Method)
	at java.base/java.lang.J9VMInternals.prepare(J9VMInternals.java:342)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:803)
	at Main.main(Main.java:21)
```

**Comment by gacholio** [comment]
Can you restore the "Exception details" portion of the message?

**Comment by sharon-wang** [comment]
@gacholio I have added the detail back in: https://github.com/eclipse/openj9/pull/9660/commits/b57e635a65249140911b90bcd499bf774c5ebcbc

To do this, a new error const needs to be created `BCV_ERR_BYTECODE_ERROR` = `Error exists in the bytecode.` Is this preferable? 

In the CFR_ERR handling, "Error exists in the bytecode." is the default error message in the error handling framework, so it can't be reused in BCV error handling.

https://github.com/eclipse/openj9/blob/0394f7080f5b6b5144757a9e351950b4990e1728/runtime/verbose/errormessageframeworkcfr.c#L309-L310

**Comment by sharon-wang** [comment]
Thank you to @ChengJin01 for pointing out that https://github.com/eclipse/openj9/issues/9336 and https://github.com/eclipse/openj9/issues/9357 are similar to the issue this PR resolves (https://github.com/eclipse/openj9/issues/9323).

I tested these changes against the example code provided in those issues and can confirm that this PR also resolves those issues.

**Comment by gacholio** [comment]
jenkins test sanity plinux jdk8

**Pull request merged**
