### PR TITLE
WIP: Generate rdbar/wrtbar when field watch is enabled

### PR DESCRIPTION
**Pull request by cathyzhyi**
This change geneartes rdbar/wrtbar in ilgen for field watch
and also teach optimizations to be aware of the new opcodes.

Signed-off-by: Yi Zhang <yizhang@ca.ibm.com>

### CODE REVIEW

**Comment by cathyzhyi** [comment]
This PR  is dependent on https://github.com/eclipse/openj9/pull/3138, https://github.com/eclipse/omr/pull/3027 and https://github.com/eclipse/openj9/pull/3134

**Comment by AdamBrousseau** [comment]
Jenkins copyright check

**Comment by AdamBrousseau** [comment]
Jenkins line endings check

**Comment by andrewcraik** [comment]
So #3138 #3134 and eclipse/omr#3027 are all merged now - @cathyzhyi can you address the merge conflict and un-WIP when ready for review please?

**Comment by cathyzhyi** [comment]
this change was delivered in another PR already https://github.com/eclipse/openj9/pull/4010

**Pull request closed without merging**
