### PR TITLE
Run explicit new initialization pass after local VP to recognize more field initialization

### PR DESCRIPTION
**Pull request by yanluo7**
Signed-off-by: Yan Luo <Yan_Luo@ca.ibm.com>

### CODE REVIEW

**Comment by yanluo7** [comment]
- During the early stage of the optimization, after object allocation the newly allocated object is typically temporarily held in an auto; this means object field stores in the constructor are represented as store into a temp instead of the new object directly, this prevents Explicit New Initialization to recognize the indirect store as a valid field initialization. Later on in the optimization passes, local VP will remove the temp and replace it with a direct reference to "new" node. So we add a pass of explicit new initialization after local VP to allow these field stores to be recognized.

**Comment by yanluo7** [comment]
Performance implication:

This change allows Explicit New Initialization to recognize more object fields to be marked as already initialized in the constructor, hence reducing the amount of uninitialized fields that need to be initialized. This change, along with another change in VP that remove redundant null checks for certain objects, showed about 0.3-0.4% throughput improvement for a server benchmark.

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Pull request merged**
