### PR TITLE
Limit CacheManagement compile job to JDK_IMPL=openj9 | IBM

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
@llxia 

Fix https://github.com/AdoptOpenJDK/openjdk-tests/issues/1468

**Comment by llxia** [comment]
jenkins test sanity plinux jdk8

**Comment by llxia** [comment]
jenkins test extended plinux jdk11

**Comment by llxia** [comment]
jenkins test extended plinux jdk11

**Comment by llxia** [comment]
JDK11 plinux test build: https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64le_linux_Personal/70/

The failure is related to https://github.com/eclipse/openj9/issues/7820

**Pull request merged**
