### PR TITLE
Simplify build instructions for Windows

### PR DESCRIPTION
**Pull request by keithc-ca**
The cygwin version of `nasm` is sufficient.

### CODE REVIEW

**Comment by pshipton** [comment]
It seems the cygwin version of nasm wasn't sufficient in the past. We should list a minimum version of cygwin or nasm, as someone looking at the instructions with an older version of cygwin already installed may have issues.

**Comment by keithc-ca** [comment]
The minimum version of `nasm` is 2.11, which is verified at configuration time; see [`custom-hook.m4`](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/closed/autoconf/custom-hook.m4#L464).

**Comment by pshipton** [comment]
> The minimum version of nasm is 2.11

This is a contradiction to https://github.com/eclipse/openj9/pull/3459, which imposed the minimum 2.13.3 level.

@0xdaryl @nbhuiyan do you have any concerns with using the 2.11 or even 2.13.1 version of nasm as the minimum level? Is there a reason that 2.13.3 was chosen as the minimum level? I notice the OpenJ9 build machines have 2.13.1 provided by cygwin but we have 2.13.3 separately installed and added to the path.

**Comment by keithc-ca** [comment]
We don't seem to have the `-I` problems discussed in #3459, and don't seem to have ever required 3.14 as proposed there.

**Comment by pshipton** [comment]
All build/testing for a long time has been done with 2.13.3. Even if older versions compile the code, it's possible the generated code could be different. It seems not worth the effort to validate older levels just to simplify the build instructions.

**Comment by nbhuiyan** [comment]
NASM v2.13.3 was selected as the minimum at the time for two main reasons: it was a fairly recent release when we were working on the macOS port, and secondly, between 2.11 and 2.13.02 there were many major fixes to the Mach-O backend (see [NASM version history](https://nasm.us/doc/nasmdocc.html)). Therefore, even if v2.11 works for Windows and Linux, we may see issues on macOS. The lower minimum version of v2.11 specified in [`custom-hook.m4`](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/closed/autoconf/custom-hook.m4#L464) was set because it broke builds for many users who were successfully able to build using v2.11 before this version check was put in place and in some cases required building NASM from source to get the required version. On macOS, Homebrew keeps up with the latest NASM stable releases, which is why we may have not seen any issues that may arise from using an older version on macOS. 

To answer @pshipton 's question, if we want to update the specified minimum required version to simplify Windows builds, I believe setting it as v2.13.1 will be better than 2.11 as we are more likely to see issues on macOS with the latter.

**Comment by keithc-ca** [comment]
I haven't changed the macOS part of the instructions, which still advises 2.13.03.

If we believe that 2.13.03 is needed on all x86 platforms, then we ought to fix the check in `custom-hook.m4` and the error message there so as not to mislead people.

**Pull request closed without merging**
