### PR TITLE
Enable more specs for x86 and Linux 390

### PR DESCRIPTION
**Pull request by vsebe**
- add more x86 and Linux 390 plaforms to the playlist variable file
- add extra cflags for x86 and Linux 390 platforms
- update the gc glue configuration for the new specs

[ci skip]

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
@jdekonin @pshipton please review

**Comment by vsebe** [comment]
@llxia @smlambert fyi

**Comment by llxia** [comment]
Thanks for updating ottawa.csv!

**Comment by pshipton** [comment]
@llxia if you are good with the changes please merge.

**Comment by pshipton** [comment]
Oops, just realized this is WIP. @vsebe is it intended to be WIP still?

**Comment by vsebe** [comment]
@llxia or @pshipton - ready to merge, thank you!

**Pull request merged**
