### PR TITLE
Add support for Valhalla PR builds

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Add Valhalla as a spec extension. This allows
any existing spec to become Valhalla capable.
Note: Only enabled for xlinux jdkNext to start.

Issue #4719
[skip ci]

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins test sanity xlinuxval jdknext

**Comment by AdamBrousseau** [comment]
Jenkins test sanity xlinuxval jdknext

**Comment by AdamBrousseau** [comment]
Jenkins test sanity xlinuxval jdknext

**Comment by AdamBrousseau** [comment]
Jenkins test sanity xlinuxval jdknext

**Comment by AdamBrousseau** [comment]
Jenkins test sanity xlinuxval jdknext

**Comment by AdamBrousseau** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Comment by AdamBrousseau** [comment]
@vsebe and @tajila for review

**Comment by tajila** [comment]
LGTM

**Pull request merged**
