### PR TITLE
Remove use of get and setAccessStaticsIndirectly APIs

### PR DESCRIPTION
**Pull request by dchopra001**
Fixes: #3610

Signed-off-by: Dhruv Chopra <Dhruv.C.Chopra@ibm.com>

### CODE REVIEW

**Comment by dchopra001** [comment]
Depends on https://github.com/eclipse/omr/pull/5731

**Comment by fjeremic** [comment]
Jenkins test sanity.functional,system.extended all

**Comment by fjeremic** [comment]
Jenkins test sanity.functional,system.extended all jdk8

**Comment by fjeremic** [comment]
Uuups:

```
14:00:51  Running system.extended ...
14:00:51  There is no test for target system.extended
```

I messed up the launch command, but the sanity tests all passed. This was just me trying to be extra careful. I'm ok to merge this with the sanity passing given the extra internal testing performed.

**Review by fjeremic — APPROVED** [review]

**Pull request merged**
