### PR TITLE
Update boot JDKs for jdknext

### PR DESCRIPTION
**Pull request by keithc-ca**
See #10737.

### CODE REVIEW

**Comment by pshipton** [comment]
Do the machines actually contain those builds?

**Comment by keithc-ca** [comment]
> Do the machines actually contain those builds?

I don't know, but those are the expected locations, following the patterns for existing boot JDKs.
We need to both install the boot JDKs and refer to them: this is just the second part. Without both changes builds will continue to fail.

**Comment by jdekonin** [comment]
> Do the machines actually contain those builds?

Yes they do now.

**Review by jdekonin — APPROVED** [review]

**Comment by jdekonin** [comment]
jenkins compile all jdknext

**Review by pshipton — APPROVED** [review]

**Pull request merged**
