### PR TITLE
Fix the `dsqrt` transformation 

### PR DESCRIPTION
**Pull request by simonameng**
Choose the API that can recreate the node with valid properties instead of no property.

Signed-off-by: simonameng <simonameng97@gmail.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Requesting review from either @andrewcraik or @cathyzhyi.

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8

**Comment by andrewcraik** [comment]
I think the change looks ok - @simonameng would you mind just describe what situation made you want to make this change? eg what flags are we hoping to have propagated? Once I have that context I will complete a review record.

**Comment by simonameng** [comment]
@andrewcraik I asked for the opinion from @cathyzhyi, she thought it's unsafe to directly copy the children of `acall` node to `dsqrt` node in the `recreateWithoutProperties`. Also, I checked the properties of `dsqrt`, it doesn't have the `ILProp1::HasSymbolRef` property. So we shouldn't copy the symbol reference when recreating. And there are some properties we should copy from the `acall` node like `_numChildren`.

**Comment by fjeremic** [comment]
> I think the change looks ok - @simonameng would you mind just describe what situation made you want to make this change?

Just for further context the original issue arose from a `DEBUG` build of the JIT asserting that we're attempting to call `setSymbolReference` on a node (`dsqrt`) which is not supposed to have symbol references. Previously we had used `recreateWithoutProperties` API incorrectly to transform an `dcall` to a Java method into the `dsqrt` IL, while also passing the symbol reference to the API.

The fix here is to not pass the symbol reference and in addition copy any properties from the call over to the `dsqrt` node so that other optimizations _may_ make use of them. For example I can envision if some optimization has determined that the call will yield a non-zero result we want to preserve such a property on the `dsqrt` as well.

**Pull request merged**
