### PR TITLE
Increase scratchSpaceLimit for JITServer

### PR DESCRIPTION
**Pull request by harryyu1994**
Increase scratchSpaceLimit by a factor of 2 on JITServer
[skip ci]
Issue: #5644

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@mpirvu This item is ready for review.

**Comment by harryyu1994** [comment]
Should we be using this:
```cpp
bool isJSR292 = TR::CompilationInfo::isJSR292(details.getMethod());
```
instead of
```cpp
bool isJSR292 = TR::CompilationInfo::isJSR292(details.getRomMethod());
```

```cpp
bool
TR::CompilationInfo::isJSR292(const J9ROMMethod *romMethod)
   {
   return (_J9ROMMETHOD_J9MODIFIER_IS_SET(romMethod, J9AccMethodHasMethodHandleInvokes));
   }

bool
TR::CompilationInfo::isJSR292(J9Method *j9method)
   {
#if defined(JITSERVER_SUPPORT)
   if (auto stream = TR::CompilationInfo::getStream())
      {
         {
         ClientSessionData *clientSessionData = TR::compInfoPT->getClientData();
         OMR::CriticalSection getRemoteROMClass(clientSessionData->getROMMapMonitor());
         auto it = clientSessionData->getJ9MethodMap().find(j9method);
         if (it != clientSessionData->getJ9MethodMap().end())
            {
            return isJSR292(it->second._romMethod);
            }
         }
      stream->write(JITServer::MessageType::CompInfo_isJSR292, j9method);
      return std::get<0>(stream->read<bool>());
      }
#endif /* defined(JITSERVER_SUPPORT) */
   return isJSR292(J9_ROM_METHOD_FROM_RAM_METHOD(j9method));
   }
```

**Comment by harryyu1994** [comment]
Ready for review.

**Comment by harryyu1994** [comment]
"in the long run I think we want to have this value per compilation". So what do you think should be the parameters needed to generate this factor?

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Only the known `cmdLineTester_gcsuballoctests_0` failed, so this PR is good to be merged.

**Pull request merged**
