### PR TITLE
Change Windows Openssl location to match playbooks

### PR DESCRIPTION
**Pull request by jdekonin**
[skip ci]

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Will this affect the 0.14 branch builds? Either way, seems a good idea to keep the files in the old location until 0.14 is completed.

**Comment by pshipton** [comment]
```
10:02:56  checking for OPENSSL... configure: The path of OPENSSL_DIR, which resolves as "/cygdrive/c/openjdk/OpenSSL-1.1.1-x86_64", is invalid.
10:02:56  configure: error: Cannot locate the the path of OPENSSL_DIR
```

**Comment by jdekonin** [comment]
jenkins test sanity win jdk8

**Comment by jdekonin** [comment]
I did 1-4, 5 and 6 I had forgot existed.  

> Will this affect the 0.14 branch builds?

I just did a copy of the contents for now as I did think of 0.14 requirements.

**Pull request merged**
