### PR TITLE
Some VMThread reclamation cleanup on x86

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Remove setVMThreadRequired calls on x86
* Remove deprecated VMThread reclamation control logic

OpenJ9 cleanup for Issue eclipse/omr#2256

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@0dvictor would you mind reviewing this please?

**Comment by 0dvictor** [comment]
I'm so happy seeing these deprecated code will be gone. Assuming there will be separated pull requests cleaning up VMThread reclamation logic related to `TR_OutlinedInstructions`, this PR looks good to me.

**Comment by 0xdaryl** [comment]
Thanks @0dvictor.  Yes, there are more pull requests coming.  I'm doing this very incrementally because the logic is very entangled unfortunately.

@andrewcraik or @fjeremic, I'd appreciate a merge (and a review if you like).  Thanks.

**Comment by andrewcraik** [comment]
Jenkins test sanity win.xlinux

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win

**Pull request merged**
