### PR TITLE
 Cmake: allow build to define version identifiers

### PR DESCRIPTION
**Pull request by keithc-ca**
Currently, cmake builds yield a VM that is missing the openj9 SHA in `-version` output (see [1]):
```
+./build/linux-x86_64-normal-server-release/images/jdk/bin/java -version
openjdk version "11.0.4-internal" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4-internal+0-adhoc.travis.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build master-5043cfea, JRE 11 Linux amd64-64-Bit Compressed References 20190715_0000 (JIT enabled, AOT enabled)
OpenJ9   - j9vm_build_tag
OMR      - 3a01d35f
JCL      - 411f32dbb based on jdk-11.0.4+10)
```
This, together with ibmruntimes/openj9-openjdk-jdk11#197, fixes that.

[1] https://travis-ci.org/eclipse/openj9/jobs/558950982

### CODE REVIEW

**Comment by pshipton** [comment]
@dnakamura any concerns with this?

**Comment by dnakamura** [comment]
LGTM

**Comment by pshipton** [comment]
jenkins compile zlinux jdk8

**Comment by pshipton** [comment]
jenkins compile plinux jdk8

**Comment by pshipton** [comment]
zlinux is backlogged, I stopped that build to run plinux instead.

**Pull request merged**
