### PR TITLE
Detect internal class refs in JNI check pedantic mode

### PR DESCRIPTION
**Pull request by gacholio**
[ci skip]

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
Do we need some additional testing enabled for pedantic mode?

**Comment by gacholio** [comment]
I don't think so.

**Comment by pshipton** [comment]
Well obviously we are missing testing for this case.

**Comment by gacholio** [comment]
I suppose I really mean "not as part of this PR". Pedantic only affects local ref detection.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
