### PR TITLE
Groundwork changes for some expected performance improvements with value types enabled

### PR DESCRIPTION
**Pull request by hzongaro**
This makes some simple changes to IL generation for array element access with value types enabled:

- Disable generation of calls to `jit{Load|Store}FlattenableArrayElement` helpers if arraylets are supported, as garbage collection policies that use arraylets do not yet work with flattenable array elements.  That will avoid having optimizations that operate on such calls having to worry about handling arraylets.
- Added debug counters to track calls to the array element helpers in order to track calls to them as well as allowing subsequent optimizations that might be able to eliminate such calls to track such elimination.

### CODE REVIEW

**Comment by a7ehuo** [comment]
LGTM

**Review by Leonardo2718 — APPROVED** [review]
Change LGTM :+1: 

For arraylets, it would be good to have some way of remembering that this needs to be fixed, if and when flattened arrays are supported with arraylets. Maybe opening an issue about it? Though, ideally, we would also have an automated way of detecting this.

**Review by vijaysun-omr — APPROVED** [review]

**Comment by vijaysun-omr** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by vijaysun-omr** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by hzongaro** [comment]
Failures on Windows both appear to be infrastructure-related. . . .

**Comment by vijaysun-omr** [comment]
Checks seem to have passed, except for infrastructure issues in a couple of cases and two reviewers have approved. Merging.

**Pull request merged**
