### PR TITLE
Backport JITServer VMJ9-related changes from master

### PR DESCRIPTION
**Pull request by harryyu1994**
Remove unused TR_J9VMBase::getArrayLengthOfStaticAddress
Fix getReportByteCodeInfoAtCatchBlock bug, instead of querying the Options API, we switch it to the frontend API which has additional handling for JITServer.

[skip ci]

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@mpirvu Hi Marius, could you help review this one?

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Compilation errors
```
15:31:43  /home/jenkins/workspace/Build_JDK8_x86-64_linux_Personal/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/control/JITClientCompilationThread.cpp: In function ‘bool handleServerMessage(JITServer::ClientStream*, TR_J9VM*, JITServer::MessageType&)’:
15:31:43  /home/jenkins/workspace/Build_JDK8_x86-64_linux_Personal/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/control/JITClientCompilationThread.cpp:1055:25: error: ‘VM_getArrayLengthOfStaticAddress’ is not a member of ‘JITServer::MessageType’
15:31:43         case MessageType::VM_getArrayLengthOfStaticAddress:
15:31:43                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
15:31:43  /home/jenkins/workspace/Build_JDK8_x86-64_linux_Personal/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/control/JITClientCompilationThread.cpp:1060:24: error: ‘class TR_J9VM’ has no member named ‘getArrayLengthOfStaticAddress’; did you mean ‘getArrayLengthInElements’?
15:31:43            bool ok = fe->getArrayLengthOfStaticAddress(ptr, length);
15:31:43                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
15:31:43                          getArrayLengthInElements
```

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Java 11 is failing 3 tests:
```
cmdLineTester_gcsuballoctests_0
cmdLineTester_jvmtitests_5 
J9vmTest_2
```

**Comment by mpirvu** [comment]
```
 [OUT] *** Testing [3/3]:	testVerboseGCSubscription_3alarm
 [OUT] Subscribing to verbose GC
 [OUT] Waiting for buffers to be passed to subscriber
 [ERR] 03:58:09.495 0x272da00    j9mm.141    *   ** ASSERTION FAILED ** at ../gc_glue_java/MetronomeDelegate.hpp:231: ((false))
 [ERR] JVMDUMP039I Processing dump event "traceassert", detail "" at 2019/09/29 00:58:09 - please wait.
```
```
+++ j9vm.test.jni.CriticalRegionTest: +++
command: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/bin/java -XX:+UseJITServer -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump -Xms64m -Xmx64m    -classpath /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.jni.CriticalRegionTest 

Exception in thread "main" java.lang.BootstrapMethodError: java.lang.invoke.StringConcatException: Generator failed
	at j9vm.test.jni.CriticalRegionTest.testAcquireAndSleep(CriticalRegionTest.java:756)
	at j9vm.test.jni.CriticalRegionTest.runBlockingTests(CriticalRegionTest.java:733)
	at j9vm.test.jni.CriticalRegionTest.main(CriticalRegionTest.java:191)
Caused by: java.lang.invoke.StringConcatException: Generator failed
	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:764)
	at java.base/java.lang.invoke.StringConcatFactory.doStringConcat(StringConcatFactory.java:665)
	at java.base/java.lang.invoke.StringConcatFactory.makeConcatWithConstants(StringConcatFactory.java:581)
	at java.base/java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:963)
	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1093)
	... 3 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.WeakHashMap.get(WeakHashMap.java:399)
	at java.base/java.util.Collections$SynchronizedMap.get(Collections.java:2594)
	at java.base/java.lang.invoke.MethodType.probeTable(MethodType.java:706)
	at java.base/java.lang.invoke.MethodType.intern(MethodType.java:661)
	at java.base/java.lang.invoke.MethodType.methodType(MethodType.java:650)
	at java.base/java.lang.invoke.MethodType.methodType(MethodType.java:640)
	at java.base/java.lang.invoke.ThunkKey.computeThunkableType(MethodHandle.java:1478)
	at java.base/java.lang.invoke.ThunkKey.computeThunkableType(MethodHandle.java:1467)
	at java.base/java.lang.invoke.ThunkKey.computeThunkableType(MethodHandle.java:1464)
	at java.base/java.lang.invoke.PermuteHandle.computeThunks(PermuteHandle.java:73)
	at java.base/java.lang.invoke.MethodHandle.<init>(MethodHandle.java:235)
	at java.base/java.lang.invoke.PermuteHandle.<init>(PermuteHandle.java:32)
	at java.base/java.lang.invoke.MethodHandle.permuteArguments(MethodHandle.java:761)
	at java.base/java.lang.invoke.MethodHandles.dropArgumentsUnsafe(MethodHandles.java:2870)
	at java.base/java.lang.invoke.MethodHandles.dropArguments(MethodHandles.java:2887)
	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleInlineCopyStrategy.generate(StringConcatFactory.java:1529)
	at java.base/java.lang.invoke.StringConcatFactory.generate(StringConcatFactory.java:756)
	... 7 more
no-zero exit value: 1
*** Test FAILED *** (j9vm.test.jni.CriticalRegionTest)
```

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Only the known `cmdLineTester_gcsuballoctests_0` failure shows now, hence merging.

**Pull request merged**
