### PR TITLE
Build DDR test only if j9ddr.jar is present in JDK

### PR DESCRIPTION
**Pull request by keithc-ca**
This should address #6979.

### CODE REVIEW

**Comment by llxia** [comment]
- The change in build.xml is for test compilation. It does not control test execution. If the `TEST_JDK_HOME ` does not contain `j9ddr.jar `, the test will still execute and fail.

- Also, with this change, if `j9ddr.jar ` is missing unexpectedly (i.e.,  j9ddr.jar has build issue. j9ddr.jar is not in the expected place), test compilation will pass. And the test will fail during the execution. It is harder to debug.

**Comment by smlambert** [comment]
To cover the test execution part, all tests in all applicable playlists should get updated to not run ddr tests on platforms that do not support ddr (if they are not already updated).

like this, but the broader set of non-supported systems: https://github.com/eclipse/openj9/blob/master/test/functional/DDR_Test/playlist.xml#L157

**Comment by keithc-ca** [comment]
I do agree we would like to avoid false positive results.

However, it isn't about whether a _platform_ supports DDR, it's about whether the _JDK_ in particular supports DDR.

**Comment by smlambert** [comment]
Sure, 2 cases, the JDK may or may not support it, and the JDK build on a particular platform may not build it, in either case, the tests should not get executed.

In the case where its a hotspot-based SDK, we have restricted the test targets to only openj9/ibm implementations (example: https://github.com/eclipse/openj9/blob/master/test/functional/DDR_Test/playlist.xml#L165), but for the 2nd case, we need to restrict the test execution in some way, and I have suggested a way to do this in https://github.com/eclipse/openj9/pull/6994#issuecomment-528947969

**Comment by smlambert** [comment]
After discussion with @keithc-ca and @llxia - proceeding with this PR and I will follow with a PR to update to the playlist files (to add ^arch.aarch64).  Prior to delivering the follow-up PR, expect to see the DDR tests get executed and fail on aarch64.

**Comment by smlambert** [comment]
Grinders to show expected behaviour:
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/487 - functional builds on aarch64, but test fails
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/484 - functional continues to build on other platforms

**Pull request merged**
