### PR TITLE
Add XLC 13.1.3 to the PATH for AIX pipeline build

### PR DESCRIPTION
**Pull request by vsebe**
Add the XLC 13.1.3 path to the build environment variables on AIX
platforms.

[ci skip]

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
[Build_JDK8_ppc64_aix_Personal](https://ci.eclipse.org/openj9/job/Build_JDK8_ppc64_aix_Personal/3)

**Comment by vsebe** [comment]
[Pipeline_Build_Test_JDK8_ppc64_aix](https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK8_ppc64_aix/38/) passed

**Comment by vsebe** [comment]
@jdekonin @pshipton please review, thx

**Comment by pshipton** [comment]
Note this doesn't change anything but makes the path to xlc explicit for builds.

**Pull request merged**
