### PR TITLE
Test support for *BSD

### PR DESCRIPTION
**Pull request by battleblow**
The AdoptOpenJDK test infrastructure uses portions of the openj9 repository, specifically openj9/test/TestConfig, I believe.  This commit adds support for using this on the BSD OS family.

Tested on FreeBSD within the context of the AdoptOpenJDK tests.  I've made no attempt to port OpenJ9 overall.

### CODE REVIEW

**Comment by smlambert** [comment]
thanks @battleblow - you will need to sign the Eclipse contribution agreement (https://accounts.eclipse.org/legal/eca/validation/13536).

We will also create a bsd spec, so that you do not have to refer to osx.  (see the addition of sparc support for a similar story: https://github.com/eclipse/openj9/pull/6953/files).

**Comment by battleblow** [comment]
Thanks, Shelley!

I'll look at getting the contribution agreement sorted out.  This may be a little complicated from the FreeBSD Foundation sponsoring this work, but I'll raise it with them and figure out our way forward there.

I'll adjust this as [WIP] until then.

Would you like me to make a pass at creating a BSD spec and, if so, would you like that as a follow up or incorporated into this change?

**Comment by smlambert** [comment]
You could include a spec change in this PR for sure, I can give guidance if you need.  BTW, I will request that there is a FreeBSD machine added at the AdoptOpenJDK project for use by test, so we can verify all of the recent test changes work.  Thanks for initiating this.

**Comment by battleblow** [comment]
I'm working with George  Adams to get a FreeBSD build up and going.  I believe that there are already FreeBSD machines available for this :).

Locally I've gotten to the point where I can run tests, but haven't yet started digging into test failures at all.

**Comment by emaste** [comment]
Is the Eclipse contributor agreement text available online?

**Comment by smlambert** [comment]
Believe you can see it here:
https://www.eclipse.org/legal/ecafaq.php

**Comment by battleblow** [comment]
I think the text is at

https://www.eclipse.org/legal/ECA.php

**Comment by battleblow** [comment]
Hi Shelley, I've taken a bit of a look at ```ottawa.csv``` where the various specs are set up, and I have a couple of questions.

* There appear to be a number of different set ups for a given OS/arch combination, particularly for Linux.  E.g. _cmprssptrs, _purec, _codecov, _sp, _le, _hrt, etc.  I was wondering if there was documentation for what these meant?  I've had a look through some of the markdown files and some of the makefiles, and have guesses at some of them, but I was wondering if there was a file that described them all.  Note that maybe the right thing to do initially is to ignore these and just create one for bsd_x86-64.
* A comment in the file itself references ```/lib/makelib/default/variations.mk``` and ```/lib/makelib/default/modes.mk``` for the list of what the actual variations that one sets to yes or no are.  I don't see these anywhere though?  I can take a related operating system and copy it (e.g. OS X) but I didn't know if there was a reference to what something like "variation:Mode110" referred to that would perhaps allow me to make better judgements.

Thanks for any guidance you may have there

**Comment by smlambert** [comment]
hi @battleblow - ottawa.csv is an old carry-over file from our internal/proprietary system (which we still support, but hopefully for not much longer).  I will suggest that some of the 'modes', which are essentially a shortcut way of listing JVM option combinations, are openj9 specific JVM options which are not relevant to *BSD, given there is not a port to that platform for now.  Not that it matters too much as no one will be trying to build a _purec, _codecov or _hrt build on *bsd platform, but the 'map' for modes to JVM options can be seen in the [modes.xml](https://github.com/eclipse/openj9/blob/master/test/TestConfig/resources/modes.xml) file. 

If you want to push past this, just take the same approach we are taking for [solaris test support](https://github.com/eclipse/openj9/pull/6953).  Our plan is to actually move the testkitgen (test/TestConfig) portion out of the eclipse/openj9 repo and place it in its own repo at AdoptOpenJDK (likely in 4Q), at which point we may be able to break from this particularly funky set of changes that are currently needed.

**Comment by battleblow** [comment]
Hi Shelley,

I spoke to Ed separately and he said the Foundation was comfortable with executing the ECA.  He just wasn't sure how to do so in a manner that it would cover the work I'm being sponsored by them to do.  Would it just make sense for both the Foundation and I to execute the ECA?  That way it would seem like we'll pass checks here as well as be covered legally.  Is there another way this is usually done in similar situations?

**Comment by smlambert** [comment]
As long as you have the permission / rights to contribute the work you are sponsored to do, then you can sign as an individual and we can proceed.  

Its also fine for the Foundation to sign, but believe its unnecessary from the standpoint of merging your PR (but from your perspective as a sponsored contributor it is good to have verified with your sponsor that you are allowed to contribute under your agreement with them).

**Comment by emaste** [comment]
To be explicit, @battleblow has permission to contribute changes sponsored by the FreeBSD Foundation under the ECA.

**Comment by battleblow** [comment]
I've also completed the ECA personally.  I amended the commit messages with the appropriated "Signed-off-by" line and force pushed them.  That looks like it has made the ECA check pass.

**Comment by battleblow** [comment]
Looks like changing the commit messages and force pushing has triggered another CI build.  Will wait for that to complete.

**Comment by battleblow** [comment]
It looks like the copyright check failure is because ottawa.csv has no copyright information in it.

Shelley, let me know if you can override that or if I should add a copyright comment to that file.

**Comment by smlambert** [comment]
That copyright check one I can and will override, thanks

**Comment by smlambert** [comment]
Jenkins test sanity plinux jdk11

**Comment by battleblow** [comment]
Thanks!  It looks like all the checks other than the copyright check passed :)

**Pull request merged**
