### PR TITLE
Align mutable fields of x86 PIC data

### PR DESCRIPTION
**Pull request by jdmpapin**
To prevent tearing, this series aligns fields of the x86 VPIC and IPIC data that are written at runtime. The IPIC data is aligned simply by adjusting the start of the snippet. In the VPIC data snippet, the _end_ of the VPIC data is already aligned, so we get the necessary field alignment by reordering the fields. This reordering requires some changes to PicBulider to remove lingering implicit assumptions about data layout. There is an unused and (almost certainly) broken function in PicBuilder which is removed instead of modified. See the individual commit messages for more.

### CODE REVIEW

**Comment by andrewcraik** [comment]
@0dvictor this looks good to me but would appreciate your expert opinion on the x codegen changes.

**Comment by 0dvictor** [comment]
The changes look good to me.
Just one comment: I'm not sure if it is beneficial to update deprecated `X86PicBuilder.inc` and `X86PicBuilder.pasm`. I believe both file are being deleted soon and large portion of the code is not tested and potentially out-of-date.

**Comment by 0dvictor** [comment]
FYI, https://github.com/eclipse/openj9/pull/4627 removes the `X86PicBuilder.inc` and `X86PicBuilder.pasm`.

**Comment by jdmpapin** [comment]
Yeah I knew the deletion was coming. I modified the .inc and .pasm files because they were still in use on 32-bit when I started writing this change. Should I revert them? I've already had to rebase this and re-test once due to a conflict with the removal of an `ifdef WINDOWS` related to a `lock cmpxchg` in the deleted function. I guess if #4627 is merged quickly enough there won't even be a choice though

**Comment by andrewcraik** [comment]
@jdmpapin can you fix the merge conflicts please?

**Comment by jdmpapin** [comment]
Updated to leave the (now deleted) old asm files unmodified

**Comment by andrewcraik** [comment]
@0dvictor are you good with this now?

**Comment by 0dvictor** [comment]
LGTM.

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win jdk8,jdk11

**Comment by jdmpapin** [comment]
Is this good to go now?

**Pull request merged**
