### PR TITLE
Remove use of environment variables from variables file

### PR DESCRIPTION
**Pull request by vsebe**
Use full path to avoid variables expansion issues

[ci skip]

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@vsebe do you have test builds for 8 and 9 at ci.eclipse?

**Comment by vsebe** [comment]
@AdamBrousseau see: 
[Build-JDK8-linux_390-64_cmprssptrs](https://ci.eclipse.org/openj9/job/vsebe_Build-JDK8-linux_390-64_cmprssptrs/50/consoleFull) configure step passed
[Build-JDK9-linux_390-64_cmprssptrs](https://ci.eclipse.org/openj9/job/vsebe_Build-JDK8-linux_390-64_cmprssptrs/47/consoleFull)

**Comment by vsebe** [comment]
@AdamBrousseau comment updated

**Comment by vsebe** [comment]
@pshipton, @DanHeidinga please review

**Pull request merged**
