### PR TITLE
Enhance DDR support

### PR DESCRIPTION
**Pull request by keithc-ca**
* PointerGenerator should map to simple types only for the 29 stream
* restore support for older streams in StructureReader
* remove unused imports
* remove unused ant scripts
* define and use AUTOBLOB_JAR in makefiles (use $() instead of ${} for makefile macro references)

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity,extended zlinux jdk8

**Comment by keithc-ca** [comment]
Rebased and updated.

**Comment by pshipton** [comment]
The testing run earlier, which passed, is sufficient.

**Comment by pshipton** [comment]
jenkins copyright check

**Review by pshipton — APPROVED** [review]

**Pull request merged**
