### PR TITLE
Update parallel setting none value

### PR DESCRIPTION
**Pull request by hmainismael**
Changing attribute parallel setting "none" instead of "false"

### CODE REVIEW

**Comment by pshipton** [comment]
Hi @hmainismael. Please follow the https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md guidelines from the "Legal considerations" section, in order to pass the ip-validation check. Until that check succeeds we cannot accept your contribution.

**Comment by llxia** [comment]
Please use `[ci skip]` in your commit message to skip travis ci build as this change doesn't require compilation check.

**Comment by hmainismael** [comment]
Thanks a lot. I just created an Eclipse account.


Do I have to create a new Pull Request ?


________________________________
De : Peter Shipton <notifications@github.com>
Envoyé : jeudi 15 février 2018 21:15
À : eclipse/openj9
Cc : hmainismael; Mention
Objet : Re: [eclipse/openj9] Update parallel setting none value (#1187)


Hi @hmainismael<https://github.com/hmainismael>. Please follow the https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md guidelines from the "Legal considerations" section, in order to pass the ip-validation check. Until that check succeeds we cannot accept your contribution.

**Comment by pshipton** [comment]
You don't need to create a new Pull Request. You can update your branch with a new commit containing an updated commit message that includes the Signed-off-by: field at the end.

**Comment by hmainismael** [comment]
I just updatted my commit message : I added the [ci skip] and include the Signed-off-by at the end.
As I told before I created my Eclipse account too, hoping I did all well.

**Comment by pshipton** [comment]
Thanks @hmainismael, the ip-validation check is passing now.

**Comment by smlambert** [comment]
Jenkins test sanity plinux jdk8

**Comment by hmainismael** [comment]
Please I wanted to know if my PR will be merged soon ?

**Comment by smlambert** [comment]
Thanks @hmainismael ! - I am on vacation until next week, so had been nudging this one along slowly.  It is now merged.

**Comment by hmainismael** [comment]
Good thing ! As a beginner, I also want to thank you @smlambert for your help and your explanations.

**Pull request merged**
