### PR TITLE
Fix typos in MemorySourceTable.MergedMemoryRange.isReadOnly()

### PR DESCRIPTION
**Pull request by keithc-ca**

### CODE REVIEW

**Comment by pshipton** [comment]
Does this fix anything? Is it likely to change the results of any testing (doesn't look like it to me)?

**Comment by keithc-ca** [comment]
At most, I would expect this to affect the `info heap` output (if any of the sections of the heap were read-only, which seems unlikely).

**Comment by pshipton** [comment]
jenkins test sanity,extended zlinux jdk8

**Comment by pshipton** [comment]
zlinux is broken waiting on omr promotion.

jenkins test sanity,extended plinux jdk8

**Pull request merged**
