### PR TITLE
Migrate callsitedbgddrext test to openj9

### PR DESCRIPTION
**Pull request by renfeiw**
[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
Reviewer: @llxia

**Comment by llxia** [comment]
Jenkins test sanity all jdk10

**Comment by llxia** [comment]
Jenkins test sanity plinux jdk8

**Comment by llxia** [comment]
cmdLineTester_callsitedbgddrext_0 failed on aix https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK10-aix_ppc-64_cmprssptrs-OpenJ9/81/tapResults/

**Comment by pshipton** [comment]
Right, there is no DDR support for aix yet, any DDR testing will need to be excluded there for now.

**Comment by renfeiw** [comment]
Updated the commit to exclude this test for AIX.

**Pull request merged**
