### PR TITLE
Set prexArg for method handle thunks

### PR DESCRIPTION
**Pull request by cathyzhyi**
The receiver of a method handle thunk is always a known object. Set
prexArg for methodhandle thunks in all cases to propagate the info
without peeking in inlining or global VP.

In the special case of a method handle thunk being  mutable callsite
target, the known object info is only available in the inlined body
rather than taken side of the guard.

issue: #4837

Signed-off-by: Yi Zhang <yizhang@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
@cathyzhyi is something missing? The CI build failed with
```../../compiler/optimizer/InlinerTempForJ9.cpp: In member function ‘void TR_J9TransformInlinedFunction::createKnownObjReceiverTemp(TR_VirtualGuardSelection*)’:
../../compiler/optimizer/InlinerTempForJ9.cpp:5481:7: error: ‘_knownObjReceiverSymRef’ was not declared in this scope
       _knownObjReceiverSymRef = knownObjSymRef;
       ^
```

**Comment by cathyzhyi** [comment]
This change is dependent on https://github.com/eclipse/omr/pull/3700

**Comment by cathyzhyi** [comment]
This change is dependent on https://github.com/eclipse/omr/pull/3700

**Comment by cathyzhyi** [comment]
@vijaysun-omr this one is ready to be merged

**Comment by vijaysun-omr** [comment]
I understand the first part of the rationale for the change. Could you please elaborate on :
"In the special case of a method handle thunk being mutable callsite target, the known object info is only available in the inlined body rather than taken side of the guard." ?

**Comment by cathyzhyi** [comment]
> I understand the first part of the rationale for the change. Could you please elaborate on :
> "In the special case of a method handle thunk being mutable callsite target, the known object info is only available in the inlined body rather than taken side of the guard." ?

For mutable callsite, the inlined method handle thunk is guarded by `MutableCallSiteTargetGuard` in case the call site target, which is also the method handle object, changed. The known object info here only applies to the inlined body and needs special handling so that when inliner replaces the arguments with priv arg temps it only use known object temps on the inlined body but not the taken side.

**Comment by cathyzhyi** [comment]
@vijaysun-omr could you help to launch `Jenkins test sanity xlinux,win,plinux jdk8,jdk11` tests? Thanks!!

**Comment by vijaysun-omr** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Pull request merged**
