### PR TITLE
Replace JAVA_BIN with TEST_JDK_HOME

### PR DESCRIPTION
**Pull request by renfeiw**
- expect user to export TEST_JDK_HOME instead of JAVA_BIN
- figure out where JAVA_BIN is based on JDK_VERSION
- remove JDK_HOME, replace it with TEST_JDK_HOME
- remove JAVA_BIN_TMP
- update readme

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by llxia** [comment]
Copyright check failed for `test/TestConfig/makefile`

**Comment by llxia** [comment]
We delivered a couple of changes for TKG into master. Since these changes (i.e., run and list disabled tests) do not affect regular builds, we will only deliver the `TEST_JDK_HOME` related change into the `v0.14.2-release` branch.

Thanks @renfeiw for testing internally.

**Comment by llxia** [comment]
fyi @pshipton

**Pull request merged**
