### PR TITLE
Explicitly export LIBPATH JDK8 folder structure updates

### PR DESCRIPTION
**Pull request by sophia-guo**
[ci skip]

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Relates with https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/210

**Comment by sophia-guo** [comment]
FYI @llxia

**Comment by llxia** [comment]
jenknins test extended xlinux jdk8

**Comment by llxia** [comment]
Jenkins test extended xlinux jdk8

**Comment by llxia** [comment]
jenkins test extended xlinux jdk8

**Pull request merged**
