### PR TITLE
(0.21.0) DDR Back compatible for TLH enable/disable change

### PR DESCRIPTION
**Pull request by LinHu2016**
TLH enabling/disabling has been changed by using realHeapTop
	instead of realHeapAlloc for faking TLH full, so old core file
	only contains realHeapAlloc and new core file only contains
	realHeapTop. Update DDR to support analyzing old core file too.

	GCObjectHeapIteratorAddressOrderedList_V1 for old core support
	GCObjectHeapIteratorAddressOrderedList_V2 for the latest core support

relate: #9745

Port of https://github.com/eclipse/openj9/pull/9813 for the 0.21.0 release.

Signed-off-by: Lin Hu <linhu@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
@LinHu2016 pls cherry pick the change. I expect this change to be the same as #9813 but there are minor differences, indicating you created this by hand.

**Comment by LinHu2016** [comment]
> @LinHu2016 pls cherry pick the change. I expect this change to be the same as #9813 but there are minor differences, indicating you created this by hand.

@pshipton I have included that @keithc-ca suggested "import order" change in PR and comments, I can rollback the changes

**Comment by keithc-ca** [comment]
There are still differences relative to #9813 for `algorithm_versions.c` and `GCObjectHeapIteratorAddressOrderedList_V1`.

**Comment by pshipton** [comment]
Pls cherry pick #9813 for the 0.21 release, and made any additional changes suggested by Keith in another PR delivered to master.

**Comment by LinHu2016** [comment]
> Pls cherry pick #9813 for the 0.21 release, and make any additional (non-functional) changes suggested by Keith in another PR delivered to master.

sure

**Comment by keithc-ca** [comment]
This still isn't a cherry-pick: `GCObjectHeapIteratorAddressOrderedList_V1.java` isn't what it should be.

**Pull request merged**
