### PR TITLE
Enable JIT Server for xlinux jdk8 and jdk11

### PR DESCRIPTION
**Pull request by pshipton**
Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity,extended,sanity.system,extended.system xlinux jdk8,jdk11

**Comment by pshipton** [comment]
@mpirvu fyi. Failures in these tests block enabling JIT server by default.
The crash in https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Personal/50/ with `vmState=0x000532ff` has the same state as https://github.com/eclipse/openj9/issues/8097, however this was resolved with an OMR change. This crash is easily repeatable, I saw it in a previous internal build as well.

**Comment by mpirvu** [comment]
Thanks. Will look into it.

**Comment by pshipton** [comment]
Crashed in https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Personal/6 as well.

**Comment by mpirvu** [comment]
I reproduced a problem in the test that was failing in the links above and I am about to fix it in https://github.com/eclipse/openj9/pull/8153
The symptoms I saw were different than the ones in the test above, but the problem I fixed can manifest in many ways, so I hope I nailed it.

**Comment by mpirvu** [comment]
Since the original problem has been fixed in #8153 I will trigger the tests again.

**Comment by mpirvu** [comment]
jenkins test sanity,extended,sanity.system,extended.system xlinux jdk8,jdk11

**Comment by mpirvu** [comment]
@pshipton All tests have passed for compiling-in JITServer code

**Comment by pshipton** [comment]
@mpirvu should it be enabled for jdk13 and jdknext (15) as well?

**Comment by pshipton** [comment]
I've reworded the commit comment and removed the WIP.

**Comment by mpirvu** [comment]
> @mpirvu should it be enabled for jdk13 and jdknext (15) as well?

I am torn about this one because we haven't tested at all JITServer functionality for jdk13 and jdknext. On the other hand I don't expect any problems when JITServer options are not used, so maybe that's ok as long as we make it clear that only Java8/11 are supported at the moment.

**Comment by pshipton** [comment]
We haven't tested jdk13 and jdknext yet, I'll create a separate PR for it.

**Comment by pshipton** [comment]
Note this change only affect PR builds and nightly builds at OpenJ9 (head stream) and doesn't affect builds done by AdoptOpenJDK.net

**Comment by mpirvu** [comment]
jenkins test sanity,extended,sanity.system,extended.system xlinux jdk8,jdk11

**Comment by mpirvu** [comment]
jenkins test sanity,extended,sanity.system,extended.system xlinux jdk8,jdk11

**Comment by mpirvu** [comment]
All tests have passed, hence merging.

**Comment by pshipton** [comment]
The large heap build is failing to compile with this change. I'm going to revert it for now. It can be re-done to only enable JITserver for the compressed refs build, or the large heap problem can be fixed.
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_xl_Nightly/251
```
22:49:09  /opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: //usr/local/lib/libprotobuf.a(common.o): relocation R_X86_64_32S against symbol `_ZTVN6google8protobuf7ClosureE' can not be used when making a shared object; recompile with -fPIC
22:49:09  /opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: //usr/local/lib/libprotobuf.a(int128.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
22:49:09  /opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: //usr/local/lib/libprotobuf.a(once.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
etc
```

**Comment by pshipton** [comment]
This change can't be automatically reverted. I've created https://github.com/eclipse/openj9/pull/8202 in case we need it.

The jdk8 build worked. Not sure if it's a machine problem or a jdk11 specific problem. I've restarted the failing build to see if it occurs again.

**Comment by pshipton** [comment]
It was actually a machine problem, the build worked on restart. Opened #8203 to get the machine fixed.

**Pull request merged**
