### PR TITLE
Update Windows to openssh 1.1.1h

### PR DESCRIPTION
**Pull request by jdekonin**
* [skip ci]
* eclipse/openj9#10666

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
jenkins compile win32,win jdk8,jdk11,jdk15

**Comment by jdekonin** [comment]
fyi @pshipton

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
Pls cherry pick this change for the 0.23.0 release branch. OpenJDK is building with 1.1.1h already, so the release builds should match that.

**Comment by pshipton** [comment]
Actually, if you want to change to 1.1.1h for all the platforms, I can merge it all in one.

**Comment by jdekonin** [comment]
Other platforms were done via #10669 for master already.  But I can certainly cherry pick that change and include the 2 for 0.23.0 release branch.

**Pull request merged**
