### PR TITLE
Move DSL step outside setup step and into parallel

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Issue #6274
[skip ci]

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
jenkins compile all jdk8,jdk11,jdk12

**Comment by AdamBrousseau** [comment]
jenkins compile all jdk8,jdk11,jdk12

**Comment by AdamBrousseau** [comment]
jenkins compile all jdk8,jdk11,jdk12

**Comment by AdamBrousseau** [comment]
jenkins compile all jdk8,jdk11,jdk12

**Comment by AdamBrousseau** [comment]
jenkins compile all jdk8,jdk11,jdk12

**Comment by AdamBrousseau** [comment]
jenkins compile all jdk8,jdk11,jdk12

**Comment by AdamBrousseau** [comment]
I think I'm happy with this solution and the numbers I'm seeing in #6274.

**Comment by AdamBrousseau** [comment]
jenkins compile all jdk8,jdk11,jdk12

**Comment by jdekonin** [comment]
@pshipton for review/merge.

**Pull request merged**
