### PR TITLE
Remove JVM_DTrace*, JVM_GetInterfaceVersion from Java 17+

### PR DESCRIPTION
**Pull request by keithc-ca**
Removed by openjdk:
* 8260193: Remove JVM_GetInterfaceVersion() and JVM_DTraceXXX

### CODE REVIEW

**Comment by keithc-ca** [comment]
Marked as draft while I update to also remove `JVM_DTrace*` functions.

**Comment by pshipton** [comment]
jenkins compile zlinux jdk16,jdknext

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
Hmm, it would have been to confirm Windows is working. I'll run a test build outside of PR testing just in case.

**Comment by keithc-ca** [comment]
> Hmm, it would have been good to confirm Windows is working. I'll run a test build outside of PR testing just in case.

What could go wrong!?! ;-)

**Pull request merged**
