### PR TITLE
Update playlist subset to version

### PR DESCRIPTION
**Pull request by renfeiw**
[ci skip]

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
personal builds: Grinder_TKG/1159, Grinder_TKG/1160

**Comment by renfeiw** [comment]
reviewers: @smlambert @llxia

**Review by smlambert — APPROVED** [review]
thanks @renfeiw !

**Comment by llxia** [comment]
jenkins test sanity,extended xlinux jdk11

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
