### PR TITLE
Add test for Make -XX:HeapDumpPath an alias for -Xdump:directory

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Test for https://github.com/eclipse/openj9/pull/2508
Check that "-XX:HeapDumpPath=" is equivalent to "-Xdump:directory=".

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pdbain-ibm** [comment]
@llxia or @smlambert for your review.
@pshipton FYI.

**Comment by llxia** [comment]
LGTM.
Just for future reference, please add `[ci skip]` in commit msg for changes that do not need SDK compilation. Thanks.

**Comment by llxia** [comment]
Jenkins test extended xlinux,win jdk10

**Comment by pdbain-ibm** [comment]
@llxia the Windows test seems to have failed: https://ci.eclipse.org/openj9/blue/organizations/jenkins/PullRequest-Extended-JDK10-win_x86-64_cmprssptrs-OpenJ9/detail/PullRequest-Extended-JDK10-win_x86-64_cmprssptrs-OpenJ9/23/pipeline could you please restart the job?

**Comment by llxia** [comment]
Jenkins test extended win jdk10

**Comment by pdbain-ibm** [comment]
@llxia  Do we have a log file from the failing VmArgumentTests_0?

**Comment by llxia** [comment]
I do not think PR archive any test log. Please try to run the test in grinder.

**Comment by pdbain-ibm** [comment]
This test hangs on Windows.  Closing this pull request.  Will open a new one when I have fixed the problem.

**Comment by pdbain-ibm** [comment]
Updated the test to use a trivial program (`HelloWorld`) instead of the argument dumper.
Ran a personal build on Windows:
```
08:35:58 [IncludeExcludeTestAnnotationTransformer] [INFO] disable method is testCrNocrdiabled annotation [level.extended, disabled.generic-all]
08:38:16 PASSED: testArgEncodingInIbmJavaOptions
...
08:38:16 PASSED: testDisableXcheckMemory
08:38:16 PASSED: testDumpDirectory
08:38:16 PASSED: testEmptyArgument
08:38:16 PASSED: testEnvironmentCmdlineOrdering
...
08:38:16 PASSED: testXprod
08:38:16 PASSED: testXserviceInOptionsFile
08:38:16 
08:38:16 ===============================================
08:38:16     VmArgumentTests
08:38:16     Tests run: 51, Failures: 0, Skips: 0
08:38:16 ===============================================
```

@llxia would you kindly run a pull request build on Linux and Windows, and other platforms as you see fit.  Thank you.
     -p

**Comment by llxia** [comment]
Jenkins test extended xlinux,win jdk10

**Comment by pdbain-ibm** [comment]
@llxia all tests passed.

**Pull request merged**
