### PR TITLE
Add missing spec ppc64_aix_uma and others

### PR DESCRIPTION
**Pull request by pshipton**
The short forms are there, and the instructions in defaults.yml
Also remove jdk11 restrictions.

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Tried to run an uma PR build in https://github.com/eclipse/openj9/pull/10889 and ran into the missing ppc64_aix_uma spec.

**Comment by keithc-ca** [comment]
I fixed the typo in the description; can you fix the commit message, please?

**Comment by keithc-ca** [comment]
@AdamBrousseau If someone says 'jenkins compile all jdkN', how is duplication avoided? For example, how do we build only `x86-64_linux_cm` and `x86-64_linux_uma` but not also `x86-64_linux` (which would be a repeat of `x86-64_linux_cm` or `x86-64_linux_uma`)?

I thought it was because of this pattern (which goes away with this PR):
```
    'x86-64_linux'     : CURRENT_RELEASES,
    'x86-64_linux_cm'  : CURRENT_RELEASES - '11',
    'x86-64_linux_uma' : ['11'],
```

**Comment by AdamBrousseau** [comment]
`all` is a subset which is hardcoded [here](https://github.com/eclipse/openj9/blob/dd7618019da330d0bbac4aff5bee5d0518b24750/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy#L120)
```
['all' : ['ppc64le_linux','ppc64le_linux_xl','s390x_linux','s390x_linux_xl','x86-64_linux','x86-64_linux_xl','ppc64_aix','x86-64_windows','x86-32_windows','x86-64_mac'],
```

**Comment by pshipton** [comment]
Fixed the typo.

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
