### PR TITLE
Merge test source directories for Java 9

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Delete the source directory for Java 9 Build 148 tests. Merge the directory for
OpenJ9 tests into the main directory. Update the build script.

Fixes https://github.com/eclipse/openj9/issues/2005

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pdbain-ibm** [comment]
FYI @smlambert or @llxia

**Comment by llxia** [comment]
Jenkins test sanity,extended xlinux jdk11

**Comment by llxia** [comment]
Jenkins test all xlinux jdk11

**Comment by llxia** [comment]
jenkins test extended xlinux jdk11

**Comment by llxia** [comment]
jenkins test sanity xlinux jdk11

**Pull request merged**
