### PR TITLE
Runtime compressed refs work

### PR DESCRIPTION
**Pull request by gacholio**
Use the compressed/full crypto entry points on PPC.

[ci skip]

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
Note that the changes are all the `J9VM_OPT_JAVA_CRYPTO_ACCELERATION` ifdef, so they will not affect OpenJ9 at all.

**Comment by andrewcraik** [comment]
@ashbm5 I know you have expertise in the crypto acceleration areas - is there anything of concern to you in this change? FYI @gita-omr as this is a PPC change

**Comment by andrewcraik** [comment]
Change seems reasonable - going to run a plinux sanity for completeness now

**Comment by andrewcraik** [comment]
Jenkins test sanity plinux,plinuxxl jdk15

**Comment by ashbm5** [comment]
no concern from me

**Comment by gacholio** [comment]
@andrewcraik This is ready to merge.

**Comment by gita-omr** [comment]
The change looks safe to me.

**Comment by keithc-ca** [comment]
Does this imply we'll also need to build the JIT twice for mixed mode?

**Comment by gacholio** [comment]
> Does this imply we'll also need to build the JIT twice for mixed mode?

No, I've already updated the JIT to use entirely runtime queries.

**Comment by keithc-ca** [comment]
Thanks. I looked too quickly and thought I saw static initialization of a table.

**Pull request merged**
