### PR TITLE
Fix memory leak in JITServer related to IProfiler

### PR DESCRIPTION
**Pull request by mpirvu**
JITServerIProfiler::setCallCount uses two types of caches to reduce
the number of messages sent to the client: a per-client cache which
uses persistent memory and a per-compilation cache which uses scratch
memory. The memory leak happens because we use persistent memory to
store an entry in the per-compilation cache. This cache will vanish
when the compilation is over because all of the backing scratch
memory segments are returned to the OS but the attached entries
allocated with persistent memory will leak.
The fix is to use scratch memory for the per-compilation cache and
persistent memory for the per-client cache.

Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
This is a cherry-pick of commit in PR #7862 (from the jitaas branch)

**Comment by ymanton** [comment]
Jenkins test sanity.functional all jdk8,jdk13

**Comment by mpirvu** [comment]
`SharedCPEntryInvokerTests_1` failing on AIX Java13.
I think I've seen this before on some other PR. However, since this PR contains code strictly related to JITServer which is not enabled on AIX, I am fairly confident that the test failure seen here is not due to these changes. Hence, this PR should be ready to be merged.

**Comment by pshipton** [comment]
`SharedCPEntryInvokerTests_1` showed up when running testing on one of the new AIX machines. #7821

**Pull request merged**
