### PR TITLE
Backport various changes from master

### PR DESCRIPTION
**Pull request by harryyu1994**
Backport the following changes:
https://github.com/eclipse/openj9/pull/7319
https://github.com/eclipse/openj9/pull/7485

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@mpirvu Hi Marius, this one is ready for review.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Java11 failures:
```
===============================================
Running test J9vmTest_2 ...
===============================================
...
+++ j9vm.test.jni.CriticalRegionTest: +++
command: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/bin/java -XX:+UseJITServer -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump -Xms64m -Xmx64m    -classpath /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.jni.CriticalRegionTest 

04:06:58.958 0x20e8a00    j9mm.141    *   ** ASSERTION FAILED ** at ../gc_glue_java/MetronomeDelegate.hpp:231: ((false))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2019/10/18 01:06:58 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15713669931370/J9vmTest_2/core.20191018.010658.16678.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.16712.

JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15713669931370/J9vmTest_2/core.20191018.010658.16678.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15713669931370/J9vmTest_2/javacore.20191018.010658.16678.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15713669931370/J9vmTest_2/javacore.20191018.010658.16678.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15713669931370/J9vmTest_2/Snap.20191018.010658.16678.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15713669931370/J9vmTest_2/Snap.20191018.010658.16678.0003.trc
JVMDUMP013I Processed dump event "traceassert", detail "".
no-zero exit value: 255
*** Test FAILED *** (j9vm.test.jni.CriticalRegionTest)
```

```
===============================================
    JCL_TEST_Test-Annotation
    Tests run: 158, Failures: 0, Skips: 0
===============================================

java.lang.ClassLoader$ClassNameBasedLock@7535e15
java.lang.ClassLoader$ClassNameBasedLock@7535e15
java.lang.ClassLoader$ClassNameBasedLock@2a75e614
java.lang.ClassLoader$ClassNameBasedLock@2a75e614
#0: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x895b35) [0x7f86af8dfb35]
#1: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x8a1d90) [0x7f86af8ebd90]
#2: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x17222e) [0x7f86af1bc22e]
#3: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x1ed7a) [0x7f86b56b2d7a]
#4: /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7f86b7a2a390]
#5: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so(+0xc4750) [0x7f86b5dde750]
#6: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so(+0xc4f6e) [0x7f86b5ddef6e]
#7: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so(+0xc5212) [0x7f86b5ddf212]
#8: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so(+0xc5297) [0x7f86b5ddf297]
#9: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1cd212) [0x7f86af217212]
#10: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1c2292) [0x7f86af20c292]
#11: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1f2bcf) [0x7f86af23cbcf]
#12: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x2c0e6f) [0x7f86af30ae6f]
#13: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x2cd2b6) [0x7f86af3172b6]
#14: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x184f89) [0x7f86af1cef89]
#15: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x185628) [0x7f86af1cf628]
#16: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x1f8b3) [0x7f86b56b38b3]
#17: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1871a5) [0x7f86af1d11a5]
#18: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x18773e) [0x7f86af1d173e]
#19: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1833b3) [0x7f86af1cd3b3]
#20: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x183802) [0x7f86af1cd802]
#21: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1838aa) [0x7f86af1cd8aa]
#22: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x1f8b3) [0x7f86b56b38b3]
#23: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x183d04) [0x7f86af1cdd04]
#24: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9thr29.so(+0xe156) [0x7f86b5b0d156]
#25: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f86b7a206ba]
#26: function clone+0x6d [0x7f86b734141d]
Unhandled exception
Type=Segmentation error vmState=0x0005ffff
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F86B5DB9530 Handler2=00007F86B56B2B50 InaccessibleAddress=0000000000000008
RDI=000000000213F100 RSI=0000000000000000 RAX=00007F869051B748 RBX=0000000000000010
RCX=0000000000000010 RDX=00007F86AFB21806 R8=00007F86AFB2799D R9=0000000000000012
R10=00007F86AFF85F10 R11=00007F86B73CEF90 R12=0000000000000012 R13=00007F86AFB21806
R14=000000000213F100 R15=0000000000000010
RIP=00007F86B5DDE750 GS=0000 FS=0000 RSP=00007F869051B4B0
EFlags=0000000000010202 CS=0033 RBP=0000000000000000 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000008
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 00ff000000000000 (f: 0.000000, d: 7.063274e-304)
xmm2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm5 ff00000000000000 (f: 0.000000, d: -5.486124e+303)
xmm6 0000000000008000 (f: 32768.000000, d: 1.618954e-319)
xmm7 0000000000000120 (f: 288.000000, d: 1.422909e-321)
xmm8 0000180080000000 (f: 2147483648.000000, d: 1.303860e-310)
xmm9 0000000002000200 (f: 33554944.000000, d: 1.657835e-316)
xmm10 ffffffffffffffff (f: 4294967296.000000, d: -nan)
xmm11 0000000049d70a38 (f: 1238829568.000000, d: 6.120632e-315)
xmm12 000000004689a022 (f: 1183424512.000000, d: 5.846894e-315)
xmm13 0000000047ac082f (f: 1202456576.000000, d: 5.940925e-315)
xmm14 0000000048650dc0 (f: 1214582272.000000, d: 6.000833e-315)
xmm15 0000000046b73e38 (f: 1186414080.000000, d: 5.861665e-315)
Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so
Module_base_address=00007F86B5D1A000

Method_being_compiled=java/lang/invoke/BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(I)I
Target=2_90_20191017_389 (Linux 4.4.0-140-generic)
CPU=amd64 (8 logical CPUs) (0x3eae99000 RAM)
```

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Only the known `cmdLineTester_gcsuballoctests_0` test fails, hence merging.

**Pull request merged**
