### PR TITLE
Fix Java_VMBench_GPTests_GPTest_gpHardwareFloat

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Use a non-unity dividend in the test to prevent clang from optimizing out the
hardware divide instruction. See
https://github.com/eclipse/openj9/issues/3789#issuecomment-456443740

Fixes (partly) issue #3789.

Also delete some legacy code that is always ifdef'ed out.

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Relaunching the osx build as the failure doesn't look related to this chagne - seems to be a compile failure with no details

Jenkins test sanity osx jdk8

**Comment by DanHeidinga** [comment]
@pdbain-ibm Any idea why the osx build is failing?

**Comment by pdbain-ibm** [comment]
Looks like a machine issue on osx1011-x86-1 and osx1011-x86-2.  A PR build for another issue https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-osx_x86-64_cmprssptrs-OpenJ9/65/console, https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-osx_x86-64_cmprssptrs-OpenJ9/62/ are failing the same way.m  FYI @jdekonin and @AdamBrousseau .

**Comment by DanHeidinga** [comment]
The OSX javac failure was unrelated to this PR.

**Pull request merged**
