### PR TITLE
Support JDKnext repo for dependent changes

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- If SDK_VERSION is next, Extentions repo suffix will be blank,
  otherwise use SDK_VERSION.

[skip ci]
Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins compile plinux jdknext depends ibmruntimes/openj9-openjdk-jdk#81

**Comment by AdamBrousseau** [comment]
```
00:02:15.681  Look for Dependent Changes
[Pipeline] echo
00:02:15.686  PullRequest source repo appears to be OpenJ9
[Pipeline] echo
00:02:15.696  Dependent OpenJDK change found: #81
[Pipeline] echo
00:02:15.699  SDK: next
[Pipeline] echo
00:02:15.700  REPO: openj9-openjdk-jdk
[Pipeline] sh
00:02:18.376  + git fetch --progress origin +refs/pull/81/merge:refs/remotes/origin/pr/81/merge
00:02:19.381  remote: Enumerating objects: 5, done.        
00:02:19.381  remote: Counting objects:  20% (1/5)           
remote: Counting objects:  40% (2/5)           
remote: Counting objects:  60% (3/5)           
remote: Counting objects:  80% (4/5)           
remote: Counting objects: 100% (5/5)           
remote: Counting objects: 100% (5/5), done.        
00:02:19.381  remote: Compressing objects:  20% (1/5)           
remote: Compressing objects:  40% (2/5)           
remote: Compressing objects:  60% (3/5)           
remote: Compressing objects:  80% (4/5)           
remote: Compressing objects: 100% (5/5)           
remote: Compressing objects: 100% (5/5), done.        
00:02:19.381  remote: Total 5 (delta 0), reused 4 (delta 0), pack-reused 0        
00:02:19.381  From https://github.com/ibmruntimes/openj9-openjdk-jdk
00:02:19.381   * [new ref]                 refs/pull/81/merge -> origin/pr/81/merge
[Pipeline] sh
00:02:22.777  + git checkout refs/remotes/origin/pr/81/merge
00:02:22.777  Previous HEAD position was b0f7ca063d0... Merge pull request #74 from pdbain-ibm/openj9-jdk
00:02:22.777  HEAD is now at 721efbc0569... Merge b7a55d0623655f6f55530dfc0b3f43191566e8cf into b0f7ca063d053c71dea9fabd1eb7b77ae4b34102
```

**Comment by AdamBrousseau** [comment]
@pshipton for review

**Comment by pshipton** [comment]
Jenkins compile plinux jdk8 depends ibmruntimes/openj9-openjdk-jdk8#273

**Comment by AdamBrousseau** [comment]
```
00:01:24.032  Look for Dependent Changes
[Pipeline] echo
00:01:24.055  PullRequest source repo appears to be OpenJ9
[Pipeline] echo
00:01:24.067  Dependent OpenJDK change found: #273
[Pipeline] echo
00:01:24.069  SDK: 8
[Pipeline] echo
00:01:24.071  REPO: openj9-openjdk-jdk8
[Pipeline] sh
00:01:26.937  + git fetch --progress origin +refs/pull/273/merge:refs/remotes/origin/pr/273/merge
00:01:26.937  remote: Enumerating objects: 13, done.        
00:01:26.937  remote: Counting objects:   8% (1/12)           
remote: Counting objects:  16% (2/12)           
remote: Counting objects:  25% (3/12)           
remote: Counting objects:  33% (4/12)           
remote: Counting objects:  41% (5/12)           
remote: Counting objects:  50% (6/12)           
remote: Counting objects:  58% (7/12)           
remote: Counting objects:  66% (8/12)           
remote: Counting objects:  75% (9/12)           
remote: Counting objects:  83% (10/12)           
remote: Counting objects:  91% (11/12)           
remote: Counting objects: 100% (12/12)           
remote: Counting objects: 100% (12/12), done.        
00:01:26.937  remote: Compressing objects:  14% (1/7)           
remote: Compressing objects:  28% (2/7)           
remote: Compressing objects:  42% (3/7)           
remote: Compressing objects:  57% (4/7)           
remote: Compressing objects:  71% (5/7)           
remote: Compressing objects:  85% (6/7)           
remote: Compressing objects: 100% (7/7)           
remote: Compressing objects: 100% (7/7), done.        
00:01:26.937  remote: Total 7 (delta 5), reused 1 (delta 0), pack-reused 0        
00:01:26.937  From https://github.com/ibmruntimes/openj9-openjdk-jdk8
00:01:26.937   * [new ref]                 refs/pull/273/merge -> origin/pr/273/merge
[Pipeline] sh
00:01:30.838  + git checkout refs/remotes/origin/pr/273/merge
00:01:30.838  Previous HEAD position was 514f6986c07... Merge pull request #268 from jerrylui803/openj9_issue_4530
00:01:30.838  HEAD is now at 487ec5c8230... Merge 8a343d6250bece70acf31c6246d388be892e0cd0 into 514f6986c07ea2dbde7cf7264e9d7e66884cc26c
```

**Pull request merged**
