### PR TITLE
Add JDK11 new java.lang.Access methods

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
getBytesNoRepl(String, Charset)
newStringNoRepl(byte[], Charset)

Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
jenkins compile pLinux

**Comment by andrew-m-leonard** [comment]
Jenkinx compile xlinux

**Comment by andrew-m-leonard** [comment]
Jenkins compile xlinux

**Comment by JasonFengJ9** [comment]
fyi https://github.com/eclipse/openj9/pull/2201

**Comment by pshipton** [comment]
Closing as a dup of #2201, which is now merged.

**Pull request closed without merging**
