### PR TITLE
(v0.22.0) Hidden class implementation 4

### LINKED ISSUE #9328: JEP 371 Hidden Classes
https://openjdk.java.net/jeps/371

This is delivered to OpenJDK now, affecting OpenJ9 builds of jdk15.

### PR DESCRIPTION
**Pull request by hangshao0**
1. Add checks for class bytes for hidden classes in MethodHanles.
2. Do bytecode verification for hidden classes.
3. Do not allow record and enum to be defined as hidden classes.
4. Fix APIs for hidden classes in Class.java.

Closes #9328

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
Cherry picked on https://github.com/eclipse/openj9/commit/c464059fca87b49a6d1d61a22af3bc4c0e16c66f + updated the copyright date of vrfyhelp.c

**Comment by gacholio** [comment]
Closing this and reopening #10517

**Comment by gacholio** [comment]
Nope, guess that's not going to work.

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk15

**Comment by gacholio** [comment]
Builds don't work properly from a branch, it seems, so I'll just go ahead and merge this.

**Pull request merged**
