### PR TITLE
Utilize perl module to parse playlist.xml in testKitGen

### PR DESCRIPTION
**Pull request by renfeiw**
- use XML::Parser module
- update playlist.xml to escape special characters

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by llxia** [comment]
jenkins test sanity all

**Comment by llxia** [comment]
jenkins test all sanity jdk11

**Comment by llxia** [comment]
jenkins test sanity all jdk11

**Comment by llxia** [comment]
jenkins test extended all jdk11

**Comment by llxia** [comment]
jenkins test sanity all jdk12

**Comment by llxia** [comment]
JDK12 PR builds failure are related to https://github.com/eclipse/openj9/issues/4661.

**Pull request merged**
