### PR TITLE
Use cache name for HelperCompatabilityTests and URLHelperTests

### PR DESCRIPTION
**Pull request by hangshao0**
[ci skip]

Signed-off-by: hangshao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
I've seen failures of -Xshareclasses:destroy in these tests when the default cache is hold open by another process on Windows. Such failures will be more often if shared class is enabled by default.  So I am adding a shared cache name for this tests.

**Comment by llxia** [comment]
Jenkins test sanity plinux jdk10,jdk8

**Comment by llxia** [comment]
Jenkins test sanity win jdk10,jdk8

**Comment by llxia** [comment]
Test failures are related to #2129

**Comment by pdbain-ibm** [comment]
Typo: should be "HelperCompatibilityTests"

**Comment by hangshao0** [comment]
> Typo: should be "HelperCompatibilityTests"

Thanks for pointing it out. The test name and target name are also wrong.

**Comment by llxia** [comment]
Thanks Peter. Hang, please open another issue to fix this. Thanks.

**Pull request merged**
