### PR TITLE
Fix line endings

### PR DESCRIPTION
**Pull request by keithc-ca**
The hope is that the CR characters removed by this commit will allow XML validation to remain enabled in the final version of #1685.

### CODE REVIEW

**Comment by keithc-ca** [comment]
https://github.com/eclipse/openj9/pull/1743/files?w=1 shows that only copyright dates are modified (and minor whitespace changes).

**Comment by pshipton** [comment]
jenkins compile plinux jdk8

**Comment by pshipton** [comment]
The copyright failure for notices.html is expected.

**Comment by pshipton** [comment]
jenkins compile aix jdk8

**Pull request merged**
