### PR TITLE
Support OpenJDK MethodHandle Unsafe call in Java 8

### PR DESCRIPTION
**Pull request by fengxue-IS**
- Correct the export name of Unsafe.shouldBeInitialized

#Related: #7352 

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
@fengxue-IS Are we going to need the jdk.misc.Usafe version for JDK11+?

**Comment by DanHeidinga** [comment]
Also, can you link this to the epic for the MH work and provide more details on why this change is required?  It'll help to understand it in the future.

**Comment by fengxue-IS** [comment]
The `Unsafe.shouldBeInitialized` method used to be only used by OpenJ9 for Java 9+ under the `jdk.internal.misc.Unsafe` package.
The OpenJDK JCL make use of this method in JSR292 code starting from Java 8 under the ` sun.misc.Unsafe package`.
This change will make the `Unsafe.shouldBeInitialized` method available under the sun.misc.Unsafe package in Java 8

**Comment by babsingh** [comment]
Replacing `Java_jdk_internal_misc_Unsafe_shouldBeInitialized` with `Java_sun_misc_Unsafe_shouldBeInitialized` won't break existing OpenJ9 functionality?

**Comment by fengxue-IS** [comment]
I have updated to name in `registerJdkInternalMiscUnsafeNativesCommon` which should still link the native method to `Java_jdk_internal_misc_Unsafe_shouldBeInitialized`, this change only adds the sun.misc.Unsafe path

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux jdk8

**Comment by DanHeidinga** [comment]
Jenkins test sanity zlinux jdk11

**Review by DanHeidinga — APPROVED** [review]

**Pull request merged**
