### PR TITLE
Re-enable DDR for AIX

### LINKED ISSUE #1769: Enable DDR support for AIX
Ties into #378 

There is work needed in OpenJ9 and [eclipse/omr](https://github.com/eclipse/omr) order to bring up DDR on AIX 7.1 and up. Broadly, this work will consist of:

- [x] Changing makefiles in order to add the debug flags necessary for DDR on AIX and account for platform differences when building DDR on AIX

- [x] Fixing any issues with compiling the DDR code on AIX

- [x] DDR relies on libdwarf, however, AIX does not seem to have a supported library, and OMR's DDR does not use it. Instead OMR has its own parser. This parser needs to be fixed or replaced with libdwarf if we can compile it on AIX.

- [ ] Enable DDR by default in the extensions repos.
ibmruntimes/openj9-openjdk-jdk8#223
ibmruntimes/openj9-openjdk-jdk11#76
ibmruntimes/openj9-openjdk-jdk#59

- [ ] Enabling `-g` causes the AIX stackframe to be too large.  Need an alternative approach to ensure good perf with DDR enabled. See #3248. Fixed by #3995

- [ ] Enable DDR tests on AIX #3995

### PR DESCRIPTION
**Pull request by keithc-ca**
* restore use of `-g` on AIX except for interpreter source files
* re-enable DDR testing on AIX

Depends on:
* https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/223
* https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/76
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/59

Closes #1769 

Doc issue https://github.com/eclipse/openj9-docs/issues/92

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity aix jdk8 depends ibmruntimes/openj9-openjdk-jdk8#223

**Comment by pshipton** [comment]
jenkins test sanity aix jdk11 depends ibmruntimes/openj9-openjdk-jdk8#223

**Comment by pshipton** [comment]
jenkins test sanity aix jdk11 depends ibmruntimes/openj9-openjdk-jdk11#76

**Comment by pshipton** [comment]
jenkins test extended aix jdk8 depends ibmruntimes/openj9-openjdk-jdk8#223

**Comment by pshipton** [comment]
jenkins test extended aix jdk11 depends ibmruntimes/openj9-openjdk-jdk11#76

**Comment by keithc-ca** [comment]
Jenkins test extended aix jdk8 depends ibmruntimes/openj9-openjdk-jdk8#223

**Comment by keithc-ca** [comment]
* Add types to vmddr.cpp that would be available if the interpreters were compiled with debugging information.
* Stop blacklisting 'signed char' which is need to properly define jbyte.
* Rebased on latest commit from 'master'.

**Comment by pshipton** [comment]
jenkins test extended zlinux,aix,win jdk8 ibmruntimes/openj9-openjdk-jdk8#223

**Comment by pshipton** [comment]
Eclipse ci seems down, will try PR testing again later.

**Comment by pshipton** [comment]
jenkins test extended zlinux,aix,win jdk8 ibmruntimes/openj9-openjdk-jdk8#223

**Comment by pshipton** [comment]
jenkins test extended zlinux,aix,win jdk8 depends ibmruntimes/openj9-openjdk-jdk8#223

**Comment by pshipton** [comment]
jenkins test extended zlinux,aix,win jdk11 depends ibmruntimes/openj9-openjdk-jdk11#76

**Comment by pshipton** [comment]
jenkins test sanity aix jdk8 depends ibmruntimes/openj9-openjdk-jdk8#223

**Comment by pshipton** [comment]
jenkins test sanity aix jdk11 depends ibmruntimes/openj9-openjdk-jdk11#76

**Comment by keithc-ca** [comment]
@llxia Isn't that test currently enabled?

**Comment by llxia** [comment]
No, it is disabled using `</disabled>`

https://github.com/eclipse/openj9/blob/30b1abac596af3e1af7b88557f864ebefa4beb85/test/functional/cmdLineTests/classesdbgddrext/playlist.xml#L117

If you check the aix extended PR build, `cmdLineTester_classesdbgddrext_aix` is not in. https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK11-aix_ppc-64_cmprssptrs-OpenJ9/15/tapResults/

**Comment by keithc-ca** [comment]
I think it should be safe to enable now. @llxia Will you create a PR or should I?

**Pull request merged**
