### PR TITLE
Common monexitfenceEvaluator, removed arch specific versions

### PR DESCRIPTION
**Pull request by mflawn**
Created common monexitfenceEvaluator, removed arch specific versions.
Common monexitfenceEvaluator to be shared across backends. Removed P,X and Z versions of the evaluator. All removed versons of monexitfenceEvaluator were the same. Included helpful comment that was included in the Z version of evaluator.

Signed-off-by: Michael Flawn <mflawn@unb.ca>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Thanks for your first contribution!  While this is correct, I'm wondering if you'd indulge me while I propose a slightly different way of implementing this since you're already in the code.

Currently, each code generator implements exactly the same function for `TR::monexitfenceEvaluator` (i.e., something that simply returns NULL), so can you create a common `TR::monexitfenceEvaluator` in `codegen/J9TreeEvaluator.[ch]pp`, delete the versions in each code generator, and have each backend use the common function as its implementation?  Generally, sharing code across the backends is the preferred approach.

**Comment by mflawn** [comment]
Per your suggestion I made a common monexitfenceEvaluator and removed the arch specific versions for P,Z and X. The comment on the Z version seemed helpful so I left that in the common version. Also ARM32 seems to implement monexitfenceEvaluator in OMR  (OMRTreeEvaluators.cpp) so I left that alone for now.

**Comment by aarongraham9** [comment]
Thoughts on this one @0xdaryl?

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
Once @aarongraham9 adds the AArch64 evaluator table overrides in #6176 then an entry can be made in that table for `monexitfenceEvaluator`.   I'm hoping #6176 will merge first so that the entry can be added as part of this PR.  In the meantime, I kicked off a sanity build on all platforms to see if anything breaks.

**Comment by fjeremic** [comment]
Very nice to see more code moving into the common code generator. Thanks for this work!

**Comment by 0xdaryl** [comment]
Please resolve merge conflicts and add this evaluator to the Tree Evaluator Table (just merged as part of #6176)

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by mflawn** [comment]
Added monexitfence to new tree evaluator table of arm J9TreeEvalutator.

**Comment by 0xdaryl** [comment]
Prior to the ARM-specific push, the previous Jenkins tests all passed successfully.  I ran an internal build with the ARM change to prove it builds successfully.  Re-running Jenkins will not test the ARM change, so I will merge this based on the previous Jenkins testing.

**Pull request merged**
