### PR TITLE
Simplify testKitGen

### PR DESCRIPTION
**Pull request by renfeiw**
- only generate targets that match JAVA_VERSION
- remove JAVA_VERSION suffix from internal target
- run_configure.mk requires JAVA_VERSION
- define Panama/Valhalla with JAVA_VERSION instead of JCL_VERSION
- use JAVA_VERSION to separate build process in build_test.xml

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewers: @llxia @smlambert

**Comment by llxia** [comment]
jenkins test sanity

**Comment by llxia** [comment]
@smlambert , could you please do a post review? I will merge the code for now, so that we can focus on add new features for testKitGen without too many conflicts. Thanks.

**Comment by smlambert** [comment]
thanks @llxia I reviewed most of it last night, will finish today, looks good from what i have seen!

**Pull request merged**
