### PR TITLE
Removed preprocessor flag interp_useSplitSideTables

### PR DESCRIPTION
**Pull request by fengxue-IS**
Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fengxue-IS** [comment]
Relates to #551

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux

**Comment by DanHeidinga** [comment]
The travis build is failing due to a reference to the flag in one of the module.xmls `runtime/verbose/module.xml`

Deleting the flag from the core.feature was what I meant by removing from the build specs.  I'm not clear on whether removing it from the DDR specs - typically we need to keep that data to allow debugging older releases but this flag has been true for so long, I'm not sure it matters.  @keithc-ca thoughts?

**Comment by keithc-ca** [comment]
The references to `J9BuildFlags.interp_useSplitSideTables` in Java source in DDR_VM will need to be addressed else a NoSuchFieldError will be thrown at runtime. The description in j9.flags should be removed. Also lines of the form:
```
C|interp_useSplitSideTables
```
should be removed from DDR_Artifacts/specs/29/* and DDR_Artifacts/supersets/29/superset.ibuild.dat.

**Comment by DanHeidinga** [comment]
@keithc-ca Thanks for the confirmation regarding the superset.ibuild.dat and the DDR_Artifact files.

**Comment by DanHeidinga** [comment]
The copyright check failure is expected as the DDR_Artifact spec files don't contain a copyright due to the format not supporting it.

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux

Kicking a new build due to the getDependency issue downloading the asmtools.jar.

**Comment by keithc-ca** [comment]
I'd like to see these commits squashed before being merged, but the result looks good to me.

**Comment by fengxue-IS** [comment]
commits squashed

**Comment by keithc-ca** [comment]
@DanHeidinga I think all your comments have been addressed. I'll let you merge assuming you agree.

**Pull request merged**
