### PR TITLE
Handle the case where getClass returns NULL

### PR DESCRIPTION
**Pull request by liqunl**
Check if getClass returns NULL before trying to do instanceOf with its
result.

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@andrewcraik May I ask for a review?

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by andrewcraik** [comment]
looks like the infra shutdown at UNB is affecting ability to do testing - unless this is urgent I think we should wait for the CI build to be available again.

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8,jdk11

**Pull request merged**
