### PR TITLE
WIP: fix aix home dir for freemarker

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Issue #1406

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Ahh, I see @jdekonin  added a symlink in `/home/jenkins -> /home/u0020236/` on the aix machines.
Looks like `#1` was missed
```
Running on aix71-p8-1 in /home/u0020236/workspace/Build-JDK9-aix_ppc-64_cmprssptrs
...
00:03:15.793 + bash ./configure --with-freemarker-jar=/home/jenkins/freemarker.jar --with-boot-jdk=/usr/java8_64 --with-cups-include=/opt/freeware/include --with-extra-ldflags=-lpthread --with-extra-cflags=-lpthread --with-extra-cxxflags=-lpthread DF=/usr/sysv/bin/df --disable-warnings-as-errors --with-jobs=8
...
00:03:16.712 checking checking that '/home/jenkins/freemarker.jar' exists... no
00:03:16.712 configure: error: freemarker.jar not found at '/home/jenkins/freemarker.jar'
00:03:17.389 configure exiting with result code 1
```
```
ls -al /home
total 16
drwxr-xr-x    8 bin      bin             256 Mar 01 05:58 .
drwxr-xr-x   25 root     system         4096 Mar 08 14:08 ..
drwxr-xr-x    2 dradmin  staff           256 Aug 17 2010  dradmin
drwxr-xr-x    2 guest    usr             256 Aug 07 2010  guest
drwxr-xr-x    2 idsldap  idsldap         256 Aug 01 2014  idsldap
drwx------    2 root     system          256 Nov 08 2010  lost+found
drwxr-xr-x    2 srvproxy system          256 Feb 03 2016  srvproxy
drwxr-xr-x    6 u0020236 staff          4096 Mar 03 16:40 u0020236
```
I can't ssh in, keeps timing out. Will disable machine for the weekend and investigate next week.

**Comment by DanHeidinga** [comment]
@jdekonin's analysis makes sense.  Is the machine's config under version control (ansible, etc)?

**Comment by AdamBrousseau** [comment]
We try to follow the Ansible from [Adopt](https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/ansible) as close as we can.

**Comment by DanHeidinga** [comment]
> We try to follow the Ansible from Adopt as close as we can.

Not the discussion for this item but we should look at keeping our machines consistent with Adopt's by using their Ansible scripts.  Will save on the "works at OpenJ9", "fails at Adopt" issues.

**Pull request closed without merging**
