### PR TITLE
Remove unused definePackage()

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Also do some other minor cleanup:
- fix warnings about empty blocks
- make methods static
- add type parameter

This completes work started in 
https://github.com/eclipse/openj9/pull/4008

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pdbain-ibm** [comment]
@keithc-ca would you please review? This should finish the classloader cleanup for now.

**Comment by keithc-ca** [comment]
Jenkins test extended xlinux,win jdk8

**Comment by keithc-ca** [comment]
PR testing will have to wait for OMR changes to promote to the openj9 branch.

**Comment by keithc-ca** [comment]
Jenkins test extended xlinux,win jdk8

**Pull request merged**
