### PR TITLE
rename MT field access outside of MethodType.java

### PR DESCRIPTION
**Pull request by fengxue-IS**
MT.returnType       -> MT.returnType()
MT.arguments        -> MT.ptypes()
MT.arguments[?]     -> MT.parameterType(?)
MT.arguments.length -> MT.parameterCount()

Related: #7352 

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Can you link this to the epic for the MH work?  It would also be good to provide more details on why this change is required and what it does.  It'll help to understand it in the future.

**Comment by fengxue-IS** [comment]
The OpenJDK MethodType class defines return_type and parameter_type variable as private variables.
In order to adopt the OpenJDK implementation, this change modifies the OpenJ9 access to these info using public APIs.

**Review by DanHeidinga — APPROVED** [review]
lgtm.

Performance overhead here should be minimal as this replaces direct field access with trusted calls that don't allocate (ie: the `arguments[]`) on a final class.

**Comment by DanHeidinga** [comment]
Jenkins test sanity win jdk8

**Comment by DanHeidinga** [comment]
Jenkins test extended osx jdk11

**Pull request merged**
