### PR TITLE
Add comment about DSL changes

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- DSL changes require Jenkins admin approval
  unless the dsl security setting is disabled.

[skip ci]
Related #10016

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@keithc-ca for merge.
I realized as I was making the change that this no longer applies because we've unticked the box.

**Comment by keithc-ca** [comment]
If 'script security for Job DSL scripts' were enabled, are only these the only files for which that check would apply?

**Comment by AdamBrousseau** [comment]
>these the only files for which that check would apply?

Yes. Those are the only 2 I am aware of.

**Comment by keithc-ca** [comment]
How would I check if 'script security for Job DSL scripts' has been re-enabled before approving a future change to either of those files?

**Comment by AdamBrousseau** [comment]
You would need Jenkins admin access to see the checkbook on the configure global security page.

**Pull request merged**
