### PR TITLE
Add protobuf to plinux containers

### PR DESCRIPTION
**Pull request by jdekonin**
* eclipse/openj9#7099
* [skip ci]

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
@mpirvu for your review/merge.

**Comment by jdekonin** [comment]
Jenkins build docker ppcle ubuntu18

**Comment by jdekonin** [comment]
jenkins build docker ppc64le centos7
jenkins build docker ppc64le ubuntu16
jenkins build docker ppc64le ubuntu18

**Comment by jdekonin** [comment]
Pr testing doesn't appear functional for centos7.
https://ci.eclipse.org/openj9/job/PullRequest-Build-Jenkins-Agent-Container/118/console

**Comment by jdekonin** [comment]
jenkins build docker ppc64le ubuntu16

**Comment by mpirvu** [comment]
I checked the content of the files modified here for P against the similar ones for x86. protobufs does not appear to be correctly configured on x86, i.e. the line that says `&& ./configure \` should have been `&& ./configure --disable-shared --with-pic \` like we do for P

**Comment by mpirvu** [comment]
All checks have passed, so this PR can be merged.

**Comment by jdekonin** [comment]
I'll follow up on the x86 container updates.

**Pull request merged**
