### PR TITLE
Decode new IPIC iTable offset slot in stack walk

### PR DESCRIPTION
**Pull request by jdmpapin**
When encountering a JIT resolve frame for jitLookupInterfaceMethod, the
stack walk uses the itable index to determine the signature and number
of parameters of the callee. However, the IPIC slot is no longer an
itable index. It's now typically an itable offset, although it can also
be a tagged J9Method pointer or VFT offset in case of private methods or
Object methods.

### CODE REVIEW

**Comment by gacholio** [comment]
Good catch - a matching change will need to be made in DDR. I'm not sure if the bits will be visible in DDR.

**Comment by gacholio** [comment]
DDR code in question:

https://github.com/eclipse/openj9/blob/master/debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/stackwalker/JITStackWalker.java#L406

The constants should be available as we "import static J9Consts.*".

If you're unfamiliar with DDR, I can make the change in a separate PR - this case doesn't really ever come up.

**Comment by jdmpapin** [comment]
@gacholio If you can change DDR separately, that would be a big help

**Comment by gacholio** [comment]
No problem.

**Comment by gacholio** [comment]
It occurs to me that the existing code is completely incorrect for inherited interface methods (a little while back I changed iTables such that they contain entries for all method from all inherited interfaces, rather than just the methods in the resolved interface class).

I'm going to fix that problem, so I may as well roll the other changes from here into that (and do the equivalent DDR work). I'll close this off once the work is complete if you don't object.

**Comment by DanHeidinga** [comment]
@gacholio @jdmpapin Is this ready to go?

**Comment by gacholio** [comment]
@DanHeidinga No - I'm going to fix it along with other things. For the record, this case essentially never comes up (only possibility of a stack walk is when an exception is thrown from jitLookupInterfaceMethod), so it's quite low-priority. It's already broken by my semi-recent change to expand the iTables to include inherited interfaces.

I'll close this to prevent confusion.

**Pull request closed without merging**
