### PR TITLE
Temporarily support for JAVA_VERSION=SE130

### PR DESCRIPTION
**Pull request by llxia**
[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
JAVA_VERSION is deprecating. We aim to stop supporting JAVA_VERSION for jdk13+.

**Comment by llxia** [comment]
jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
jenkins test sanity zlinux jdk11

**Comment by llxia** [comment]
xlinux PR build failed due to machine issue:
```
Using context: Sanity - JDK11 - linux_x86-64_cmprssptrs
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to ub16x64j94
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
```

**Comment by llxia** [comment]
Grinder: https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/325/consoleFull

```
-DJVM_VERSION=openjdk11-openj9
```

**Comment by smlambert** [comment]
Thanks @llxia !

**Pull request merged**
