### PR TITLE
Don't set JNI symbol's linkage to TR_JNILinkage in directCallEvaluator()

### PR DESCRIPTION
**Pull request by klangman**
When the IL has two JNI calls to the same method it's possible for the 1st
call to be devirtulized and the 2nd to be left as an indirect call.
Setting the method symbol's linkage to JNI would be incorrect for the
upcoming indirect call using the same method symbol so we must not
set the linkage to JNI!

Signed-off-by: Kevin Langman <langman@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
@klangman can you shorten the pull request title to fit within the character limit? @gita-omr to review in the first instance as a POWER change.

**Comment by gita-omr** [comment]
Jenkins test sanity aix,plinux jdk8,jdk11

**Comment by gita-omr** [comment]
Jenkins test extended aix,plinux jdk8,jdk11

**Comment by gita-omr** [comment]
AIX sanity failed with "error: module not found: jdk.hotspot.agent"  @AdamBrousseau is it some known issue?

**Comment by AdamBrousseau** [comment]
Looks like the error we saw yesterday. Change was reverted (#4861). I will relaunch it.

**Comment by AdamBrousseau** [comment]
Jenkins test sanity aix jdk11

**Comment by AdamBrousseau** [comment]
Jenkins test sanity aix jdk11

**Comment by gita-omr** [comment]
Jenkins test extended aix jdk11

**Comment by gita-omr** [comment]
Extended test failed with "error: module not found: jdk.hotspot.agent" @AdamBrousseau could you please take a look ?

**Comment by AdamBrousseau** [comment]
I see that error in green builds. Not sure what it means. The reason your build is yellow is due to a test failure
```
org.openj9.test.attachAPI.TestAttachErrorHandling.testPrematureSocketClose
java.lang.AssertionError: com.sun.tools.attach.AttachNotSupportedException: acknowledgement timeout from 19988568 on port 38860
```

**Comment by gita-omr** [comment]
Extended aix_ppc_64 has one failure but it also happened in another build that does not include this PR: https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK11-aix_ppc-64_cmprssptrs-OpenJ9/34/testngreports/org.openj9.test.attachAPI/TestAttachErrorHandling/testPrematureSocketClose/

It was also happening before intermittently. So it's unrelated to this this change.

**Pull request merged**
