### PR TITLE
Enable JIT Server for plinux jdk8 and jdk11

### PR DESCRIPTION
**Pull request by jdekonin**
* [skip ci]
* eclipse/openj9#8257

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
jenkins test sanity plinux jdk8,jdk11

**Comment by pshipton** [comment]
It worked on ub16p8j95 and ub16p8j96, trying again since only particular machines were broken (ub16-ppcle-1 -> 3).

jenkins compile plinux jdk8,jdk11

**Comment by pshipton** [comment]
We got ub16p8j95 and ub16p8j96 again, cancelling these builds. We'll have to disable machines to get the machine we want.

**Comment by pshipton** [comment]
jenkins compile plinux jdk8,jdk11

**Comment by pshipton** [comment]
jenkins compile plinux jdk8,jdk11

**Comment by pshipton** [comment]
This set is running on ub16-ppcle-1 and 2

**Comment by pshipton** [comment]
The `-version` output doesn't indicate any problems.
```
11:20:37  openjdk version "11.0.6-internal" 2020-01-14
11:20:37  OpenJDK Runtime Environment (build 11.0.6-internal+0-adhoc.jenkins.BuildJDK11ppc64lelinuxPersonal)
11:20:37  Eclipse OpenJ9 VM (build HEAD-cf5fd57, JRE 11 Linux ppc64le-64-Bit Compressed References 20200129_660 (JIT enabled, AOT enabled)
11:20:37  OpenJ9   - cf5fd57
11:20:37  OMR      - 3b9951e
11:20:37  JCL      - 9f54681 based on jdk-11.0.6+10)
```

**Comment by pshipton** [comment]
Not sure how the machines got fixed, perhaps via a reboot.
I'll check all the suites just in case.

jenkins test sanity,extended,sanity.system,extended.system plinux jdk8,jdk11

**Comment by pshipton** [comment]
Although not reflected here, the testing all passed.

**Comment by pshipton** [comment]
@mpirvu fyi

**Pull request merged**
