### PR TITLE
Rename asm-8.0.1.jar to asm.jar

### PR DESCRIPTION
**Pull request by llxia**
Resolve: https://github.com/AdoptOpenJDK/TKG/issues/90
Related: https://github.com/AdoptOpenJDK/TKG/pull/93

[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
This should be merged after the release. Otherwise, we need to port the change into the release branch.

**Comment by pshipton** [comment]
It may be worth doing this now, before the weekend release testing. If merged after the release, and the release needs to be re-spun for any reason, it will have to be done then anyway.

**Comment by llxia** [comment]
Tested with AdoptOpenJDK/TKG#93:
jdk11 sanity.functional Grinder_TKG/674
jdk8 sanity.functional Grinder_TKG/675

**Comment by llxia** [comment]
This PR has to be merged together with AdoptOpenJDK/TKG#93. And it cannot be tested in PR builds.

**Pull request merged**
