### PR TITLE
Enable gcc-7 on zLinux 64bits platforms

### PR DESCRIPTION
**Pull request by vsebe**
Update graph_enable_gcc7_cmd property to enable gcc-7 environment

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Is this gcc 7.3 that is being enabled here?

**Comment by vsebe** [comment]
@fjeremic - yes, it is.

**Comment by pshipton** [comment]
There is a potential performance concern, setting WIP for now.

**Comment by vsebe** [comment]
Rebased, resolved merge conflict.

**Comment by pshipton** [comment]
The -Xint performance concern is now understood, related to the gcc LRA (the register allocator). It can be worked around by using the `-mno-lra` debug option. Since we know using `-mno-lra` is a possibility, if necessary, I'm going ahead with this change.

**Pull request merged**
