### PR TITLE
Add libffi preconf files for AArch64

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds two header files in runtime/libffi/preconf/ for
aarch64.

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
I chose the directory name `xr64` for Linux ARM 64-bit.  Should it be anything else?

**Comment by knn-k** [comment]
> Is that naming scheme consistent with the m4 files added to support the Unsafe(?) helpers?

Yes, I added it in #3502 (not merged yet).

**Comment by DanHeidinga** [comment]
Jenkins test sanity xlinux jdk8

**Comment by DanHeidinga** [comment]
Testing an x86 compile to ensure that these files aren't picked up by the build system on other platforms. (don't expect them to be)

**Comment by knn-k** [comment]
I added changes for aarch64 support to libffi/module.xml.

**Pull request merged**
