### PR TITLE
Deprecate value assertions for NULLVALUE

### PR DESCRIPTION
**Pull request by rohitp27**
The changes include :
- Code folding for #if directives for NULLVALUE value checks
- Remove assert statements
- Remove range check asserts for Power systems immediate range

Closes: #7870
Signed-off-by: Rohit Pandey rohit.pandey.h@gmail.com

### CODE REVIEW

**Comment by rohitp27** [comment]
@0xdaryl @dsouzai Can you check and merge this commit? Thanks!

**Comment by dsouzai** [comment]
jenkins test sanity all jdk8

**Comment by dsouzai** [comment]
jenkins test sanity all jdk8

**Comment by rohitp27** [comment]
Thank you @dsouzai . Hopefully I'll be able to do more in the future.

**Pull request merged**
