### PR TITLE
Merge JITServerHelpers to the master branch

### PR DESCRIPTION
**Pull request by a7ehuo**
Merge `JITServerHelpers` to the master branch.

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Comment by a7ehuo** [comment]
Since this PR needs to rebase after #7066, will resolve the conflicts all together after #7066 is merged.

**Comment by a7ehuo** [comment]
@mpirvu Conflicts are resolved. Ready for review. Thanks!

**Comment by mpirvu** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by mpirvu** [comment]
Jenkins test sanity aix jdk8

**Comment by mpirvu** [comment]
Tests passed, hence merging.

**Pull request merged**
