### PR TITLE
Wrapped job creation to reduce ConcurrentModificationException

### PR DESCRIPTION
**Pull request by JennyChenyj**
Added a retry block to reduce ConcurrentModificationException, and
deleted the create variable to save memory.

[skip ci]

Signed-off-by: Jenny Chen <Jenny.Chen@ibm.com>

### CODE REVIEW

**Comment by JennyChenyj** [comment]
Hi @AdamBrousseau~ Thanks for reviewing it!

**Comment by JennyChenyj** [comment]
> Since this is the second time we're written this code I'm wondering if we should either try and make a generic function to do this or alternatively enhance the retry step in Jenkins.

Good idea! I will do some research.

**Comment by AdamBrousseau** [comment]
Let's open a second PR for the generic function. I think this can be merged now.

**Comment by JennyChenyj** [comment]
> Let's open a second PR for the generic function. I think this can be merged now.

https://github.com/eclipse/openj9/pull/7208

**Pull request merged**
