### PR TITLE
Temporarily turn off mode service

### PR DESCRIPTION
**Pull request by renfeiw**
[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by DanHeidinga** [comment]
@llxia @renfeiw Is the mode service used / usable outside of IBM?  If not, this may be code that needs a deeper look to determine it's future.

**Comment by llxia** [comment]
No, mode service is not used outside (as it cannot be accessed outside). 
We are going to have a further discussion with @smlambert to determine its future.

**Comment by smlambert** [comment]
My opinion is that there would be no reason why this 'modes service' could not be used externally or internally, and is part of a larger story of feeding data to the test systems we use from services running in the cloud.  

At the moment, I do not think we should remove it completely.  I would like to explore options to connect to public cloud services (where this and other services could be hosted).

**Comment by llxia** [comment]
jenkins test sanity xlinux jdk11

**Pull request merged**
