### PR TITLE
Add Modules memory info to Javacore

### PR DESCRIPTION
**Pull request by ShishirH**
The modules memory category J9MEM_CATEGORY_MODULES in `include/j9memcategories.h`
was not added to the category table at `j9vm/j9memcategories.c`.
With its inclusion, it is possible to track the amount of memory that constitute modules.

Added the modules category, J9MEM_CATEGORY_MODULES, to the category table at
`j9vm/j9memcategories.c`

Signed-off-by: Shishir Halaharvi <shishir.neo95@gmail.com>

### CODE REVIEW

**Comment by ShishirH** [comment]
Javacore without this change:
```
NULL           ------------------------------------------------------------------------
0SECTION       NATIVEMEMINFO subcomponent dump routine
NULL           =================================
0MEMUSER
1MEMUSER       JRE: 1,062,116,768 bytes / 1903 allocations
1MEMUSER       |
2MEMUSER       +--VM: 772,625,432 bytes / 1525 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Classes: 3,351,464 bytes / 110 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Memory Manager (GC): 548,731,784 bytes / 411 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Heap: 536,932,352 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 11,799,432 bytes / 410 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Threads: 10,693,248 bytes / 152 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Stack: 185,400 bytes / 15 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Native Stack: 10,354,688 bytes / 16 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 153,160 bytes / 121 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Trace: 170,384 bytes / 260 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JVMTI: 17,776 bytes / 13 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JNI: 29,432 bytes / 43 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Port Library: 208,655,576 bytes / 72 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Unused <32bit allocation regions: 208,645,112 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 10,464 bytes / 71 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 975,768 bytes / 464 allocations
1MEMUSER       |
2MEMUSER       +--JIT: 288,467,400 bytes / 114 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Code Cache: 268,435,456 bytes / 1 allocation
2MEMUSER       |  |
3MEMUSER       |  +--JIT Data Cache: 2,097,216 bytes / 1 allocation
2MEMUSER       |  |
3MEMUSER       |  +--Other: 17,934,728 bytes / 112 allocations
1MEMUSER       |
2MEMUSER       +--Class Libraries: 1,020,672 bytes / 248 allocations
2MEMUSER       |  |
3MEMUSER       |  +--VM Class Libraries: 1,020,672 bytes / 248 allocations
1MEMUSER       |
2MEMUSER       +--Unknown: 3,264 bytes / 16 allocations
NULL           
NULL           ------------------------------------------------------------------------
```

Javacore with this change:
```

**Comment by ShishirH** [comment]
@DanHeidinga Can you please take a look.

**Comment by ashu-mehra** [comment]
@ShishirH lgtm! thanks for fixing this issue.

**Comment by DanHeidinga** [comment]
Jenkins test sanity,extended zlinux jdk11

**Comment by DanHeidinga** [comment]
Jenkins test sanity osx jdk8

**Comment by DanHeidinga** [comment]
@ShishirH Can you confirm that the modules category reports 0 allocations in a JDK8 build?

**Comment by ShishirH** [comment]
@DanHeidinga Just checked, and that's a negative. I'm still seeing some module allocations even on JDK8. Looking into why that's happening

**Comment by pshipton** [comment]
I don't understand this change. J9MEM_CATEGORY_MODULES was added, but no allocations were modified to use it.

**Comment by DanHeidinga** [comment]
The category already existed.  It wasn't being reported though.
https://github.com/eclipse/openj9/search?q=J9MEM_CATEGORY_MODULES&unscoped_q=J9MEM_CATEGORY_MODULES

**Comment by pshipton** [comment]
The moduleNameTable is created even in Java 8.

https://github.com/eclipse/openj9/blob/fa147d9f48455cae01fa4e7c53d74628892c0303/runtime/vm/classallocation.c#L175

**Comment by JasonFengJ9** [comment]
> The moduleNameTable is created even in Java 8.

Will have a look this.

**Comment by DanHeidinga** [comment]
I think this is good to merge like this.  The allocation of module data in JDK8 should be handled as a separate item

**Comment by pshipton** [comment]
OMRMEM_CATEGORY_9_CHILDREN doesn't exist, and https://github.com/eclipse/omr/pull/3916 has been created. I'm reverting this until we get the macro created.

**Comment by pshipton** [comment]
eclipse/omr#3916 is merged and promoted, this change has be restored via #5953

**Pull request merged**
