### PR TITLE
Fixing compilation warning and typo

### PR DESCRIPTION
**Pull request by dmitripivkine**
Signed-off-by: Dmitri Pivkine <Dmitri_Pivkine@ca.ibm.com>

### CODE REVIEW

**Comment by dmitripivkine** [comment]
Jenkins test compile windows jdk8

**Comment by dmitripivkine** [comment]
Jenkins test sanity windows jdk8

**Comment by gacholio** [comment]
jenkins compile win jdk8

**Comment by gacholio** [comment]
CI build failed for silly reasons - ignoring.

**Comment by dmitripivkine** [comment]
@gacholio thank you

**Pull request merged**
