### PR TITLE
WIP: Recognize FMA method on aarch64

### PR DESCRIPTION
**Pull request by wbh123456**
- Enable inlineDirectCall() in aarch64 for recognizing methods.
- Added FMA methods in inlineDirectCall()

Note that this PR requires support from OMR: https://github.com/eclipse/omr/pull/4893

Issue: #7474
Signed-off-by: Bohao(Aaron) Wang aaronwang0407@gmail.com

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins test sanity alinux64xl jdk11 depends eclipse/omr#4893

**Comment by 0xdaryl** [comment]
Jenkins test sanity alinux64xl jdk11 depends eclipse/omr#4893

**Comment by 0xdaryl** [comment]
Jenkins test sanity alinux64xl jdk11 depends eclipse/omr#4893

**Comment by 0xdaryl** [comment]
Jenkins test sanity alinux64xl jdk11 depends eclipse/omr#4893

**Comment by 0xdaryl** [comment]
Jenkins test sanity alinux64xl jdk11 depends eclipse/omr#4893

**Comment by 0xdaryl** [comment]
Jenkins test sanity alinux64xl jdk11 depends eclipse/omr#4893

**Comment by 0xdaryl** [comment]
Jenkins test sanity alinux64xl jdk11 depends eclipse/omr#4893

**Comment by 0xdaryl** [comment]
Jenkins test sanity alinux64xl jdk11 depends eclipse/omr#4893

**Comment by knn-k** [comment]
eclipse/omr#4893 has been merged.
Please remove "WIP:" when this PR is ready.

**Comment by wbh123456** [comment]
The recognized methods still not recognized on aarch64, still need some debugging process on this PR. Since the aarch64 hardware is not yet available for debugging, I will close this PR.

**Pull request closed without merging**
