### PR TITLE
Clean up reference to DecimalFormatHelper in the JIT

### PR DESCRIPTION
**Pull request by liqunl**
DecimalFormatHelper has been deleted in #5666, clean up its referencce
in the JIT.

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@andrewcraik @JamesKingdon May I have your review?

**Comment by JamesKingdon** [comment]
Looks good to me.

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8

**Comment by knn-k** [comment]
This PR introduced a build break with a debug build at the following line:
https://github.com/eclipse/openj9/blob/f07d6dc970bdcc8e7a19b9475ca0f902cdf1bbb3/runtime/compiler/optimizer/StringPeepholes.cpp#L160
```
compiler/optimizer/StringPeepholes.cpp:160:20: error: 'START_BIG_DECIMAL_HELPER_METHODS' was not declared in this scope
    TR_ASSERT(m !=  START_BIG_DECIMAL_HELPER_METHODS &&
```

**Comment by knn-k** [comment]
I opened Issue #9377 for the build break.

**Pull request merged**
