### PR TITLE
Apply -Xshareclasses:destroyAll only when JDK_IMPL=openj9 or ibm

### LINKED ISSUE #3975: -Xshareclasses:destroyAll should only apply if JDK_IMPL=openj9 or ibm
`-Xshareclasses:destroyAll` is added by default for all JDK_IMPL. 
https://github.com/eclipse/openj9/blob/82d9955f5b161cc1fb90742ca6d23272d929cbfe/test/TestConfig/settings.mk#L223

This caused `hotspot` test builds failure

```
01:22:20.816 ===============================================
01:22:20.816 Running test jdk_nio_0 ...
01:22:20.816 ===============================================
01:22:20.816 jdk_nio_0 Start Time: Fri Dec  7 20:38:01 2018 Epoch Time (ms): 1544215081587
01:22:20.816 "/home/jenkins/workspace/openjdk11_hs_openjdktest_x86-64_linux/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll || echo "cache cleanup done";
01:22:20.816 Unrecognized option: -Xshareclasses:destroyAll
01:22:20.816 Error: Could not create the Java Virtual Machine.
01:22:20.816 Error: A fatal exception has occurred. Program will exit.
01:22:20.816 cache cleanup done
```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_x86-64_linux/95/console

### PR DESCRIPTION
**Pull request by renfeiw**
- add the conditional check in settings.mk

[ci skip]

Fixes #3975 

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by llxia** [comment]
jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
jenkins test sanity xlinux,win,aix jdk11

**Comment by llxia** [comment]
Is it possibe to remove `:;` in the console output?

```
00:02:05.772 ===============================================
00:02:05.772 Running test jdk_math_0 ...
00:02:05.772 ===============================================
00:02:05.772 jdk_math_0 Start Time: Wed Dec 12 13:34:19 2018 Epoch Time (ms): 1544621659337
00:02:05.772 :;
00:02:05.772 variation: NoOptions
00:02:05.772 JVM_OPTIONS:  
00:02:05.772 { mkdir -p "/home/jenkins/workspace/Test-Grinder/openjdk-
```
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/117/console

**Comment by llxia** [comment]
jenkins test sanity xlinux,win,aix jdk11

**Comment by hangshao0** [comment]
Just tried on Linux x86-64, -Xshareclasses:destroyAll also destroy the nonpersistent cache. So using -Xshareclasses:destroyAll should be sufficient. 

```
java -Xshareclasses:name=Cache2,nonpersistent -version

java -Xshareclasses:destroyAll

Attempting to destroy all caches in cacheDir /tmp/javasharedresources/

JVMSHRC808I Compressed references shared cache "Cache2" is destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
```

 #3947 is caused by an SVT test that left a non-persistent cache behind. Are we also adding (or do we have plans to add) -Xshareclasses:destroyAll to the SVT test ?

**Comment by renfeiw** [comment]
@hangshao0  This change applies to SVT as well.

**Comment by hangshao0** [comment]
The nonpersistent cache left on the machine that caused #3947 is under /tmp, so I guess it was created with groupAccess. 

Probably it is better to run both -Xshareclasses:destroyAll and -Xshareclass:groupAccess,destroyAll.  
-Xshareclasses:destroyAll will destroy all the caches in users home
-Xshareclass:groupAccess,destroyAll will destroy all the caches under /tmp/

**Comment by renfeiw** [comment]
updated based on  @hangshao0 's comment

**Comment by llxia** [comment]
jenkins test sanity xlinux,win,aix,plinux,osx jdk11

**Comment by llxia** [comment]
jenkins test sanity xlinux,win jdk8

**Comment by llxia** [comment]
Seen crash in osx build: https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-osx_x86-64_cmprssptrs-OpenJ9/57/console
```
03:30:18.011 Test 16. test_v0_nStMNc started
03:30:18.011 
03:30:18.011 An unhandled error (4) has occurred.
03:30:18.011 J9Generic_Signal_Number=00000004
03:30:18.011 Signal_Number=0000000b
03:30:18.011 Error_Value=00000000
03:30:18.011 Signal_Code=00000001
03:30:18.011 Handler1=000000000BB7FFB0
03:30:18.011 Handler2=000000000BBE5350
03:30:18.011 InaccessibleAddress=0000000000000038
03:30:18.011 RDI=00007FFA978A3FD8
03:30:18.011 RSI=0000000000000007
03:30:18.011 RAX=0000000000000028
03:30:18.011 RBX=0000000000000800
03:30:18.011 RCX=0000000000000000
03:30:18.011 RDX=0000000000000000
03:30:18.011 R8=0000000000000000
03:30:18.011 R9=0000000000000000
03:30:18.011 R10=0000000000000001
03:30:18.011 R11=00007FFEE407F4F0
03:30:18.011 R12=00007FFEE407F4E0
03:30:18.011 R13=00007FFEE407F4F0
03:30:18.011 R14=000000000E4ADB00
03:30:18.011 R15=0000000000000000
03:30:18.011 RIP=000000000BB9CDBF
03:30:18.011 RSP=00007FFEE407F3A8
03:30:18.011 RFlags=0000000000010206
03:30:18.011 RBP=00007FFEE407F4B0
03:30:18.011 ERR=0000003800000004
03:30:18.011 TRAPNO=000000040000000E
03:30:18.011 CPU=0038000000040000
03:30:18.011 FAULTVADDR=0000000000000038
03:30:18.011 XMM0=00000000000000ff
03:30:18.011 XMM1=0000000000000000
03:30:18.011 XMM2=0000000000000000
03:30:18.011 XMM3=0000000000000000
03:30:18.011 XMM4=0000000000000000
03:30:18.011 XMM5=3fd4be6100000000
03:30:18.011 XMM6=000fffffffffffff
03:30:18.011 XMM7=3ff0000000000000
03:30:18.011 XMM8=ffffffffffffffff
03:30:18.011 XMM9=0000000000000003
03:30:18.011 XMM10=0000000000000000
03:30:18.011 XMM11=0000000000000000
03:30:18.011 XMM12=0000000000000000
03:30:18.011 XMM13=0000000000000000
03:30:18.011 XMM14=0000000000000000
03:30:18.011 XMM15=0000000000000000
03:30:18.011 Module=/Users/jenkins/workspace/PullRequest-Sanity-JDK11-osx_x86-64_cmprssptrs-OpenJ9/build/macosx-x86_64-normal-server-release/images/test/openj9//thrstatetest
03:30:18.011 Module_base_address=000000000BB7F000
03:30:18.011 Symbol=getVMThreadFromOMRThread
03:30:18.011 Symbol_address=000000000BB9CD90
03:30:18.011 JVMDUMP039I Processing dump event "abort", detail "" at 2018/12/13 15:47:24 - please wait.
03:30:18.011 JVMDUMP032I JVM requested System dump using '/Users/jenkins/workspace/PullRequest-Sanity-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/test_output_15447389792417/thrstatetest_0/core.20181213.154724.8352.0001.dmp' in response to an event
03:30:27.021 JVMDUMP010I System dump written to /Users/jenkins/workspace/PullRequest-Sanity-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/test_output_15447389792417/thrstatetest_0/core.20181213.154724.8352.0001.dmp
03:30:27.021 JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/PullRequest-Sanity-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/test_output_15447389792417/thrstatetest_0/javacore.20181213.154724.8352.0002.txt' in response to an event
```

And aix cannot build. Rerun these two builds.

**Comment by llxia** [comment]
jenkins test sanity aix,osx jdk11

**Pull request merged**
