### PR TITLE
Create Java10 compatible class source files.

### LINKED ISSUE #650: JDK10 mono-repo compilation errors due to multiple classes in single .java file
The new make file changes in OpenJDK10 for the Oracle change to a single src "repo" have resulted in several of the following types of errors. This is due to a J9 class java file declaring multiple "classes". This is fine in a single compilation unit, however with the repo changes the "nashorn" build is a special separate compilation unit, and the compiler cannot find these hidden classes as a result.
```
* For target support_special_classes_jdk.scripting.nashorn__the.jdk.scripting.nashorn_batch:
/home/admin/mydocker/ccm/jdk18.3/build/linux-x86_64-normal-server-release/support/j9jcl_sources/java.base/share/classes/java/lang/invoke/MethodHandle.java:224: error: cannot find symbol
	CacheKey cacheKey;			/* Strong reference to a CacheKey to ensure the WeakHashMap doesn't immediately collect the item */
	^
  symbol:   class CacheKey
  location: class MethodHandle
```

I have moved the problem classes into their own Java file, and this solves the problem.
Classes affected are:
- Class java.lang.invoke.CacheKey declared in HandleCache.java. => Create CacheKey.java
- Class java.lang.invoke.BruteArgumentMoverHandle declared in ArgumentMoverHandle.java. => Create BruteArgumentMoverHandle.java
- Class java.lang.invoke.VarHandleInvokeExactHandle declared in VarHandleInvokeHandle.java. => Create VarHandleInvokeExactHandle.java

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Fixes #650 

Signed-off-by: Andrew Leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
@andrew-m-leonard Can you provide some details about the reason for this change?  It'll make it easier to understand why the change occurred when looking at it in months (or years) down the road.

**Comment by andrew-m-leonard** [comment]
Fixes https://github.com/eclipse/openj9/issues/650

@DanHeidinga sure, I talked to Peter a while back about this. OpenJDK10 has changed its build repo structure as you know, to a single repo, and as part of that they changed the make compilation structure somewhat. In doing that in compiling some of the java compilation units if a class is not discoverable because the public class is not in a file with it's name<.java> then it fails, see: https://github.com/eclipse/openj9/issues/650

**Comment by andrew-m-leonard** [comment]
@DanHeidinga if you could review please?
we currently have a hacky overlay workaround in openj9-jdk10 to workaround this issue, so I am keen to get it fixed....

**Comment by pshipton** [comment]
The changes affect all streams but since they are requested to help jdk10 I'll add the jdk10 tag.

**Comment by pshipton** [comment]
@andrew-m-leonard can you please provide more information about what you are running to expose the problem? A simple jdk10 build seems to work fine, its not clear what use case is exposing the problem.

**Comment by andrew-m-leonard** [comment]
@pshipton The openj9-jdk10 build works because we put a "hacky" workaround to overlay the openj9 classes with those in this PR...!
See: https://github.ibm.com/runtimes/openj9-openjdk/tree/openj9-jdk10/openj9overlay/jcl/src/java.base/share/classes/java/lang/invoke
Without this, you will get the errors shown in the Issue: https://github.com/eclipse/openj9/issues/650

**Comment by DanHeidinga** [comment]
@andrew-m-leonard Why are these subset of the classes necessary to move into their own files?  I still see several additional classes defined in `HandleCache.java` - why is only one of them required to move out?

Is this related to using `sjavac`?  To generating javadoc?  Or something else?

I'm struggling to understand the rationale here beyond "if we hack it like this, it works"

**Comment by andrew-m-leonard** [comment]
@DanHeidinga sorry putting the workaround in may not have been a good idea in hindsight! i'm going to remove our workaround so the build breaks.... we can then all see and recreate the issue....!

**Comment by andrew-m-leonard** [comment]
Here is the error:
* For target support_special_classes_jdk.scripting.nashorn__the.jdk.scripting.nashorn_batch:
/home/admin/mydocker/ccm/openj9-openjdk/openj9-openjdk/build/linux-x86_64-normal-server-release/support/j9jcl_sources/java.base/share/classes/java/lang/invoke/MethodHandle.java:233: error: cannot find symbol
	CacheKey cacheKey;			/* Strong reference to a CacheKey to ensure the WeakHashMap doesn't immediately collect the item */
	^
  symbol:   class CacheKey
  location: class MethodHandle
/home/admin/mydocker/ccm/openj9-openjdk/openj9-openjdk/build/linux-x86_64-normal-server-release/support/j9jcl_sources/java.base/share/classes/java/lang/System.java:589: warning: [removal] runFinalizersOnExit(boolean) in Runtime has been deprecated and marked for removal
	Runtime.runFinalizersOnExit(flag);
	       ^
/home/admin/mydocker/ccm/openj9-openjdk/openj9-openjdk/build/linux-x86_64-normal-server-release/support/j9jcl_sources/java.base/share/classes/java/lang/invoke/MethodHandle.java:739: error: cannot find symbol
			result = new BruteArgumentMoverHandle(permuteType, this, permute, EMPTY_CLASS_ARRAY, result);
			             ^
  symbol:   class BruteArgumentMoverHandle
   ... (rest of output omitted)

* All command lines available in /home/admin/mydocker/ccm/openj9-openjdk/openj9-openjdk/build/linux-x86_64-normal-server-release/make-support/failure-logs.

**Comment by andrew-m-leonard** [comment]
@DanHeidinga building the runtimes:openjdk-jdk10 branch now demonstrates this problem (now that Unsafe has been fixed...). See build: https://hyc-rt-openjdk-jenkins.swg-devops.com/job/build_ibmsdk/271/console

**Comment by pdbain-ibm** [comment]
What's the ETA for this?

**Comment by andrew-m-leonard** [comment]
@DanHeidinga ETA ?

**Comment by DanHeidinga** [comment]
I've been looking at this and took a different approach for dealing with splitting `ArgumentMoverHandle` and `BruteArgumentMoverHandle`.  

You took the right approach with the `CacheKey`.  Although I'd like to keep it, `MethodCacheKey`, & `FieldCacheKey` in the same file, there doesn't seem to be a way to do that and allow JDK 10 to build.

When splitting `VarHandleInvokeHandle.java`, we have to also move `VarHandleInvokeGenericHandle` to its own file.

I'll open a PR with my version of this today.

**Comment by DanHeidinga** [comment]
Thanks for putting this together Andrew!  As discussed, I extended the approach in #1425 which is merged.  Closing this pr.

**Pull request closed without merging**
