### PR TITLE
Add sign extension for reduce synchronized field load

### PR DESCRIPTION
**Pull request by NigelYiboYu**
The ReduceSynchronizedFieldLoad codegen path did not check the load node's
isSignExtendedTo64BitAtSource flag. As a result, a 32-bit value without sign
extension can lead to program crashes.

This commit fixes this issue by performing a sign extension on the
loaded 32-bit field.

Signed-off-by: Nigel Yu <yunigel@ca.ibm.com>

### CODE REVIEW

**Comment by NigelYiboYu** [comment]
Marking this as WIP until fully tested.

**Comment by fjeremic** [comment]
Jenkins test sanity zlinux

**Comment by NigelYiboYu** [comment]
Tests passed. Ready to merge.

**Comment by fjeremic** [comment]
Jenkins test sanity zlinux jdk10

**Comment by fjeremic** [comment]
The JDK10 Linux builds have been having issues with slow running tests which is causing problems, hence why I had to restart in the previous comment. See #2329. I'm comfortable merging this change with the JDK8 testing given the high impact it has.

**Pull request merged**
