### PR TITLE
DDR: generalize return types of bitfield and SRP accessor methods

### PR DESCRIPTION
**Pull request by keithc-ca**
* make PointerGenerator consistent with BytecodeGenerator

* clean up
  - remmove unused method parameters
  - remove redundant type arguments
  - make methods static as appropriate
  - fix return type in bitfield sample comment

### CODE REVIEW

**Comment by keithc-ca** [comment]
This should address inconsistencies discovered with #7064.

**Comment by pshipton** [comment]
jenkins test sanity,extended aix,osx,plinux,win jdk8

**Comment by pshipton** [comment]
jenkins test sanity,extended win32 jdk8

**Comment by pshipton** [comment]
jenkins test sanity,extended plinux,win jdk11

**Comment by keithc-ca** [comment]
I don't think either of the AIX failures are related to this.

**Comment by pshipton** [comment]
The failures aren't related to this PR.

**Pull request merged**
