### PR TITLE
Reword and reformat StringBuilderTransformer documentation

### PR DESCRIPTION
**Pull request by fjeremic**
Eliminate references to undefined pull requests and leave instructions
on how to add instrumentation for use in the defined environment
variables for future reference.

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
The source of StringBuilder.java may change over time so I will not provide a diff but rather the set of changes to be applied to get the instrumentation to work as a sequence of steps:

1. Introduce several fields:

```
    private transient boolean collectAppendStatistics;
    private transient boolean collectAllocationStatistics;
    private transient boolean collectAllocationBacktraces;
    private transient boolean collectAppendObjectTypes;

    // Used to track the total number of allocated chars, including the initial chars for the StringBuilder, throughout the lifetime of the application
    private static long totalAllocatedChars = 0;
  
    // Used with addAllocationBacktrace for collecting the locations of where the allocations happen 
    private static java.util.HashMap<String, Long> allocationBacktraces = new java.util.HashMap<String, Long>();

    // Used to the frequency of the lengths of objects that are to be appended 
    private static java.util.HashMap<Long, Long> appendZCount = new java.util.HashMap<Long, Long>();
    private static java.util.HashMap<Long, Long> appendCCount = new java.util.HashMap<Long, Long>();
    private static java.util.HashMap<Long, Long> appendDCount = new java.util.HashMap<Long, Long>();
    private static java.util.HashMap<Long, Long> appendFCount = new java.util.HashMap<Long, Long>();
    private static java.util.HashMap<Long, Long> appendICount = new java.util.HashMap<Long, Long>();
    private static java.util.HashMap<Long, Long> appendJCount = new java.util.HashMap<Long, Long>();
    private static java.util.HashMap<Long, Long> appendSCount = new java.util.HashMap<Long, Long>();
    private static java.util.HashMap<Long, Long> appendOCount = new java.util.HashMap<Long, Long>();

    // Used to track the types and char lengths of objects passing through the java/lang/Object append overload
    private static java.util.HashMap<Long, java.util.HashMap<Class, Long>> appendOTypes = new java.util.HashMap<Long, java.util.HashMap<Class, Long>>();
```

2. Add a utility method for appending statistics:

```
    private void addAllocationBacktrace(int numAllocatedChars) 
    {
        StringBuilder builder = new StringBuilder(128);

        boolean firstNonStringBuilderMethodSeen = false;

        for (StackTraceElement element : (new Throwable()).getStackTrace()) {
            String method = element.toString();
            
            if (firstNonStringBuilderMethodSeen || !method.startsWith("java.lang.StringBuilder.")) {
                firstNonStringBuilderMethodSeen = true;
                
                builder.append(method);
                builder.append("\n");
            }
        }

        String backtrace = builder.toString();

        if (allocationBacktraces.containsKey(backtrace)) {
            allocationBacktraces.put(backtrace, allocationBacktraces.get(backtrace) + (long)numAllocatedChars);
        } else {
            allocationBacktraces.put(backtrace, new Long((long)numAllocatedChars));
        }
    }
```

3. Add an initialization hook:

```
    static
    {
        Runtime.getRuntime().addShutdownHook(new Thread()
        {
            public void run()
            {
                Object[] allocationBacktraceList = allocationBacktraces.entrySet().toArray();

                Arrays.sort(allocationBacktraceList, new Comparator()
                {
                    @Override
                    public int compare(Object o1, Object o2)
                    {
                        return (((Map.Entry<String, Long>)o2).getValue()).compareTo(((Map.Entry<String, Long>)o1).getValue());
                    }
                });

                System.out.println("StringBuilderTransformer: Printing backtrace statistics");
                System.out.println();
                
                for (Object entry : allocationBacktraceList) {
                    System.out.println("----------------------------------");
                    System.out.print("Total allocated chars from callsite: ");
                    System.out.println(((Map.Entry<String, Long>)entry).getValue());
                    System.out.println(((Map.Entry<String, Long>)entry).getKey());
                }

                System.out.println("----------------------------------");
                System.out.println();
                System.out.println("StringBuilderTransformer: Printing total allocated chars");
                System.out.println();

                System.out.println("----------------------------------");
                System.out.print("Total Allocated Chars = ");
                System.out.print(totalAllocatedChars);
                System.out.println();
                System.out.println("----------------------------------");
                System.out.println();

                Object[] appendZCountList = appendZCount.entrySet().toArray();
                Object[] appendCCountList = appendCCount.entrySet().toArray();
                Object[] appendDCountList = appendDCount.entrySet().toArray();
                Object[] appendFCountList = appendFCount.entrySet().toArray();
                Object[] appendICountList = appendICount.entrySet().toArray();
                Object[] appendJCountList = appendJCount.entrySet().toArray();
                Object[] appendSCountList = appendSCount.entrySet().toArray();
                Object[] appendOCountList = appendOCount.entrySet().toArray();

                Comparator comparator = new Comparator()
                {
                    @Override
                    public int compare(Object o1, Object o2)
                    {
                        return (((Map.Entry<Long, Long>)o1).getKey()).compareTo(((Map.Entry<Long, Long>)o2).getKey());
                    }
                };

                Arrays.sort(appendZCountList, comparator);
                Arrays.sort(appendCCountList, comparator);
                Arrays.sort(appendDCountList, comparator);
                Arrays.sort(appendFCountList, comparator);
                Arrays.sort(appendICountList, comparator);
                Arrays.sort(appendJCountList, comparator);
                Arrays.sort(appendSCountList, comparator);
                Arrays.sort(appendOCountList, comparator);

                System.out.println("StringBuilderTransformer: Printing append statistics: format - (length in chars, invocation count)");
                System.out.println();
                
                System.out.println("------------------ Boolean ---------------");
                
                for (Object entry : appendZCountList) {
                    System.out.print(((Map.Entry<Long, Long>)entry).getKey());
                    System.out.print(",");
                    System.out.println(((Map.Entry<Long, Long>)entry).getValue());
                }

                System.out.println("------------------ Char ------------------");

                for (Object entry : appendCCountList) {
                    System.out.print(((Map.Entry<Long, Long>)entry).getKey());
                    System.out.print(",");
                    System.out.println(((Map.Entry<Long, Long>)entry).getValue());
                }

                System.out.println("------------------ Double ----------------");

                for (Object entry : appendDCountList) {
                    System.out.print(((Map.Entry<Long, Long>)entry).getKey());
                    System.out.print(",");
                    System.out.println(((Map.Entry<Long, Long>)entry).getValue());
                }

                System.out.println("------------------ Float -----------------");

                for (Object entry : appendFCountList) {
                    System.out.print(((Map.Entry<Long, Long>)entry).getKey());
                    System.out.print(",");
                    System.out.println(((Map.Entry<Long, Long>)entry).getValue());
                }

                System.out.println("------------------ Integer ---------------");

                for (Object entry : appendICountList) {
                    System.out.print(((Map.Entry<Long, Long>)entry).getKey());
                    System.out.print(",");
                    System.out.println(((Map.Entry<Long, Long>)entry).getValue());
                }

                System.out.println("------------------ Long ------------------");

                for (Object entry : appendJCountList) {
                    System.out.print(((Map.Entry<Long, Long>)entry).getKey());
                    System.out.print(",");
                    System.out.println(((Map.Entry<Long, Long>)entry).getValue());
                }

                System.out.println("------------------ String ----------------");

                for (Object entry : appendSCountList) {
                    System.out.print(((Map.Entry<Long, Long>)entry).getKey());
                    System.out.print(",");
                    System.out.println(((Map.Entry<Long, Long>)entry).getValue());
                }

                System.out.println("------------------ Object ----------------");

                for (Object entry : appendOCountList) {
                    System.out.print(((Map.Entry<Long, Long>)entry).getKey());
                    System.out.print(",");
                    System.out.println(((Map.Entry<Long, Long>)entry).getValue());
                }

                System.out.println();
                System.out.println("StringBuilderTransformer: Printing append object type statistics");
                System.out.println();

                Object[] appendOTypesList = appendOTypes.entrySet().toArray();

                Arrays.sort(appendOTypesList, new Comparator()
                {
                    @Override
                    public int compare(Object o1, Object o2)
                    {
                        return (((Map.Entry<Long, java.util.HashMap<Class, Long>>)o1).getKey()).compareTo(((Map.Entry<Long, java.util.HashMap<Class, Long>>)o2).getKey());
                    }
                });

                for (Object entry1 : appendOTypesList) {
                    Object[] mapList = ((Map.Entry<Long, java.util.HashMap<Class, Long>>)entry1).getValue().entrySet().toArray();

                    System.out.println("----------------------------------");
                    System.out.print("Length in chars: ");
                    System.out.println(((Map.Entry<Long, java.util.HashMap<Class, Long>>)entry1).getKey());
                    System.out.println();
                    System.out.println("Object type breakdown: format - (type, invocation count):");
                    
                    for (Object entry2 : mapList) {
                        Class type = ((Map.Entry<Class, Long>)entry2).getKey();
                        
                        System.out.print("    ");
                        System.out.print(type == null ? "null" : type.toString());
                        System.out.print(",");
                        System.out.println(((Map.Entry<Class, Long>)entry2).getValue());
                    }
                } 
            }
        });
    }
```

**Comment by andrewcraik** [comment]
Could this class transformation not be accomplished with either a native or Java agent? If so wouldn't it make more sense to check that in as code so that it will always work and can be loaded against an unmodified VM easily rather than keeping all that in the docs?

**Comment by andrewcraik** [comment]
Secondly, the documentation is great, but a note about applicability to Java 9 indified string concatenation is probably warranted since this pattern is a Java 8 and earlier pattern - the newer javac (when not in compatibility mode) will generate a different sequence using method handles that will be optimized differently.

**Comment by fjeremic** [comment]
> Could this class transformation not be accomplished with either a native or Java agent?

The code is non-trivial. For example handling the infinite recursion case, etc. You would have to redefine quite a lot of the methods to achieve everything.

> the newer javac (when not in compatibility mode) will generate a different sequence using method handles that will be optimized differently.

I've opened up https://github.com/eclipse/openj9/issues/139 to investigate this.

**Comment by andrewcraik** [comment]
Yes a simple agent should be able to handle the necessary redefinitions and then we can actually have the agent available to easily do the changes and is probably a great item for a beginner to start getting familiar with how the lower level of a Java system actually works.

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by fjeremic** [comment]
> Yes a simple agent should be able to handle the necessary redefinitions and then we can actually have the agent available to easily do the changes and is probably a great item for a beginner to start getting familiar with how the lower level of a Java system actually works.

I've opened up https://github.com/eclipse/openj9/issues/156 to address this.

**Comment by andrewcraik** [comment]
ok I'm fine with this - since the changes were in code files I fired of tests - once done we should be able to merge this.

**Pull request merged**
