### PR TITLE
Add extra U_64 data field to Indexable Object Headers

### PR DESCRIPTION
**Pull request by bragaigor**
Same PR/commit as https://github.com/eclipse/openj9/pull/11507 . 
The issue related to concurrent scavenger (https://github.com/eclipse/openj9/issues/11616) was solved by https://github.com/eclipse/omr/pull/5751 

We can now safely re-introduce `dataAddr` again.

Signed-off-by: Igor Braga <higorb1@gmail.com>

### CODE REVIEW

**Comment by bragaigor** [comment]
cc: @amicic @dmitripivkine @fjeremic

**Comment by amicic16** [comment]
Jenkins test sanity all jdk8

**Review by amicic16 — APPROVED** [review]

**Review by amicic — APPROVED** [review]

**Comment by amicic** [comment]
Jenkins test sanity all jdk8

**Comment by pshipton** [comment]
The OMR acceptance this morning failed, probably an infra issue. Pls don't merge this until after we get the OMR change promoted.

**Comment by pshipton** [comment]
This should fix it. https://ci.eclipse.org/openj9/job/Pipeline-OMR-Acceptance/2199/
After this promotes, we can try some sanity.system PR testing since that is the suite which failed before.

**Comment by pshipton** [comment]
Windows 32-bit hung. Trying again https://ci.eclipse.org/openj9/job/Pipeline-OMR-Acceptance/2200/

**Comment by pshipton** [comment]
OMR is promoted now.

Jenkins test sanity,sanity.system all jdk8

**Comment by pshipton** [comment]
The remaining build https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK8_x86-64_windows/2705/ is hung due to a machine issue.

The half that did already run on Windows seems sufficient as it passed theses tests: DaaLoadTest_daa1_ConcurrentScavenge_0, DaaLoadTest_daa2_ConcurrentScavenge_0. 
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_windows_Personal_testList_1/2/tapResults/

**Review by fjeremic — APPROVED** [review]

**Pull request merged**
