### PR TITLE
Disable Fixed Heap Simple Write Barriers for PortableSharedCache

### PR DESCRIPTION
**Pull request by harryyu1994**
Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
```
./java -Xshareclasses:name=fix_heap,cacheDir=/root/ -Xmx100m -Xms100m -Xscminaot300m -Xscmx600m -Xjit:verbose,count=0 -version
```

```
./java -Xshareclasses:name=fix_heap,cacheDir=/root/ -Xmx100m -Xscminaot300m -Xscmx600m -Xjit:verbose,count=0 -version
```

**Comment by harryyu1994** [comment]
- generated AOT with this option (fixed heap)
```
ENV JVM_ARGS="-Xshareclasses:name=fix_heap,cacheDir=/opt/ibm/java/ -Xmx1000m -Xms1000m -XX:-PortableSharedCache -Xscmx500M -Xscmaxaot300M -Xjit:verbose"
```
- then load AOT using this option (variable heap
```
ENV JVM_ARGS="-Xshareclasses:name=fix_heap,cacheDir=/opt/ibm/java/ -Xmx1000m -XX:-PortableSharedCache -Xscmx500M -Xscmaxaot300M -Xjit:verbose"
```

@mpirvu Hi Marius, I did not observe an issue even without this change. We seem to load AOT fine with my AcmeAir application. Also another question is if this will cause AOT incompatibility how come we do not have a AOT compatibility check for this?

**Comment by mpirvu** [comment]
> if this will cause AOT incompatibility how come we do not have a AOT compatibility check for this?

Good question, unless we don't understand what fixed heap size is or how to enable it. @dsouzai do you have an idea on this matter?

**Comment by dsouzai** [comment]
I guess we've never properly accounted for this case. We don't seem to check for `isVariableHeapBaseForBarrierRange0` or `isVariableHeapSizeForBarrierRange0` in the Feature Flags. Probably also need to also check for `isVariableActiveCardTableBase`.

These added to the Feature Flags.

**Comment by harryyu1994** [comment]
> I guess we've never properly accounted for this case. We don't seem to check for `isVariableHeapBaseForBarrierRange0` or `isVariableHeapSizeForBarrierRange0` in the Feature Flags. Probably also need to also check for `isVariableActiveCardTableBase`.

I guess I will open another PR to include them in the check.

**Comment by harryyu1994** [comment]
@mpirvu Hi Marius, this one is ready for review.

**Comment by mpirvu** [comment]
As discussed, I would like to make sure that we have a real problem before merging a "solution" for it.

**Comment by harryyu1994** [comment]
@dsouzai https://github.com/eclipse/openj9/issues/7710 is the only place I've seen this problem mentioned. Do you still remember who raised this problem and if there's any evidence that this is actually a problem. My local testing has shown that AOT was loading fine and no crashes when I switched from a fixed-heap configuration to a variable-heap configuration.

**Comment by dsouzai** [comment]
I know @fjeremic had mentioned in in the past that that writebar sequence is simpler if Xmx and Xms are the same (he's on vacation till late next week I think?).

I don't think we've ever run into a problem, but I suppose theoretically we could if the heap size changes if the loaded AOT code could be using the wrong writebars.

**Comment by andrewcraik** [comment]
Would we ever actually allow the heap size to be adjusted/changed between runs? This would cause a lot of differences for the runtime and it seems like this is quite different to the original purpose of portable SCC in that we were trying to avoid over dependence on the machine architecture. This is a performance trade for a different purpose - does it make sense to wrap it under the same banner? Might it be better to just produce a better diagnostic to inform users when we reject AOT code due to a GC configuration change so they can decide whether to build the image with a variable heap size or to actually fix their heap for a performance boost?

**Comment by mpirvu** [comment]
> When both fix heap and PortableAOT are specified we are going to produce an error message to the user and let them choose between the two

I am also ok with forcing `self()->setIsVariableHeapSizeForBarrierRange0(true);`  when portableAOT is in effect, provided the effect from it on performance is small (this solution is more user friendly).

**Comment by harryyu1994** [comment]
> > When both fix heap and PortableAOT are specified we are going to produce an error message to the user and let them choose between the two
> 
> I am also ok with forcing `self()->setIsVariableHeapSizeForBarrierRange0(true);` when portableAOT is in effect, provided the effect from it on performance is small (this solution is more user friendly).

@andrewcraik Any objections on this?

**Comment by mpirvu** [comment]
> Wondering if you have any idea how much of a performance boost fixed heap provides.

This needs to be measured, because even if we had estimations based on old experiments, behavior might have changed.

**Comment by harryyu1994** [comment]
x86: Did not observe performance penalty with my setup.
Z: 42 hours worth of run (specjbb2015)
```
fixheap 1: RUN RESULT: hbIR (max attempted) = 11245, hbIR (settled) = 10712, max-jOPS = 10120, critical-jOPS = 2738
fixheap 2: RUN RESULT: hbIR (max attempted) = 11548, hbIR (settled) = 10532, max-jOPS = 9931, critical-jOPS = 2872
fixheap 3: RUN RESULT: hbIR (max attempted) = 10712, hbIR (settled) = 10269, max-jOPS = 9855, critical-jOPS = 3079

varheap 1: RUN RESULT: hbIR (max attempted) = 11548, hbIR (settled) = 10532, max-jOPS = 9816, critical-jOPS = 2865
varheap 2: RUN RESULT: hbIR (max attempted) = 11548, hbIR (settled) = 10532, max-jOPS = 9816, critical-jOPS = 2412
varheap 3: RUN RESULT: hbIR (max attempted) = 11548, hbIR (settled) = 10924, max-jOPS = 10278, critical-jOPS = 2972
```
critical-jOPS:
- 2896
- 2918.5 (excluding that really bad run)

max-jOPS:
- 9968
- 9970

**Comment by harryyu1994** [comment]
@mpirvu See above for performance numbers. I think this one is safe to go in.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity all jdk11

**Pull request merged**
