### PR TITLE
Remove uses of INTERP_COMPRESSED_OBJECT_HEADER

### PR DESCRIPTION
**Pull request by gacholio**
Replace with GC_COMPRESSED_POINTERS (J9VM/OMR/DDR versions). In every
build, either both or neither the flags are set. Removal of the flag
definitions will follow later.

[ci skip]

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
Jenkins test sanity plinux jdk8

**Comment by charliegracie** [comment]
Jenkins test sanity plinux jdk8

**Comment by AdamBrousseau** [comment]
Jenkins test sanity plinux jdk8

**Comment by gacholio** [comment]
Seems pretty clear that the build system is simply not working this week.

**Comment by charliegracie** [comment]
Jenkins test sanity plinux jdk8

**Comment by gacholio** [comment]
Related to #643

**Pull request merged**
