### PR TITLE
Building DDR for AArch64

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds build configuration for DDR for AArch64.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
@keithc-ca

**Comment by keithc-ca** [comment]
@knn-k Do you have a plan to fix OMR's ddrgen for cross-compile use-cases such as this?

**Comment by knn-k** [comment]
Yes, I am trying to enable DDR in the cross compilation environment.

**Comment by keithc-ca** [comment]
@knn-k Can you share a link to your work (a branch or a pull request) so we can follow along (and perhaps help)?

**Comment by knn-k** [comment]
I have not opened PRs other than this PR and #8171 so far.  I have also edited closed/autoconf/custom-hook.m4 in openj9-openjdk-jdk11 locally, adding `xr64` to the list of targets for DDR.
I am seeing a problem to solve: `HAVE_LIBDWARF_DWARF_H` and `HAVE_LIBDWARF_LIBDWARF_H` are undefined in omr/include_core$/omrcfg.h.  libdwarf-dev is available in the cross-compile environment (See buildenv/docker/jdk11/aarch64_CC/arm-linux-aarch64/Dockerfile).

**Comment by knn-k** [comment]
`HAVE_LIBDWARF_DWARF_H` and `HAVE_LIBDWARF_LIBDWARF_H` are defined in omrcfg.h as expected when I try building in the native AArch64 environment.  Full build is not successful yet.

**Comment by knn-k** [comment]
I see the following error during the build in the native AArch64 environment:
```
Generating DDR pointer class source files
superset directory name : /home/nano/openj9/openj9-openjdk-jdk11/build/linux-aarch64-normal-server-release/vm/
superset file name : superset.dat
Writing generated classes to /home/nano/openj9/openj9-openjdk-jdk11/build/linux-aarch64-normal-server-release/support/ddr/gensrc/com/ibm/j9ddr/vm29/pointer/generated
Unhandled structure type: _IO_FILEPointer->_lock _IO_lock_t*
java.lang.IllegalArgumentException: Type is not a recognized array: __int128 unsigned[]
        at com.ibm.j9ddr.tools.PointerGenerator.getArrayType(PointerGenerator.java:960)
        at com.ibm.j9ddr.tools.PointerGenerator.writeArrayMethod(PointerGenerator.java:873)
        at com.ibm.j9ddr.tools.PointerGenerator.generateImplementationMethods(PointerGenerator.java:564)
        at com.ibm.j9ddr.tools.PointerGenerator.generateClass(PointerGenerator.java:329)
        at com.ibm.j9ddr.tools.PointerGenerator.generateClasses(PointerGenerator.java:157)
        at com.ibm.j9ddr.tools.PointerGenerator.main(PointerGenerator.java:117)
Processing failed
```

**Comment by keithc-ca** [comment]
> java.lang.IllegalArgumentException: Type is not a recognized array: __int128 unsigned[]
>         at com.ibm.j9ddr.tools.PointerGenerator.getArrayType(PointerGenerator.java:960)

It may make sense to add support for 128-bit scalar types, but until then, you will need to blacklist the type `__int128 unsigned` or apply some `typeoverride` to the fields using that array type.

**Comment by knn-k** [comment]
@keithc-ca Thank you for your comment.  What do other platforms do for adding support for new types or blacklisting types?

**Comment by keithc-ca** [comment]
Blacklisted types are listed in [1]; you may need to blacklist the type(s) that have fields which are arrays of `__int128 unsigned`.

[1] https://github.com/eclipse/openj9/blob/master/runtime/ddr/blacklist

**Comment by knn-k** [comment]
I added a line in the `blacklist`, and now the build in AArch64 native environment finishes successfully.
The `HAVE_LIBDWARF_DWARF_H` problem with cross build is not fixed yet.

Build depends on https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/259 .

**Comment by 0xdaryl** [comment]
@keithc-ca : would you mind reviewing this please?

**Comment by keithc-ca** [comment]
> Build depends on [ibmruntimes/openj9-openjdk-jdk11#259](https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/259) .

I think the dependency is the reverse: enabling DDR for aarch64 by _default_ depends on this change.

**Comment by knn-k** [comment]
I wanted to say "ibmruntimes/openj9-openjdk-jdk11#259 needs to be applied for the changes in this PR to work."

**Comment by knn-k** [comment]
You can use the `--disable-ddr` option for `configure` in the cross build environment, when this PR and openj9-openjdk-jdk11#259 are merged.

**Comment by keithc-ca** [comment]
> I wanted to say "[ibmruntimes/openj9-openjdk-jdk11#259](https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/259) needs to be applied for the changes in this PR to work."

Technically, no, this can be tested via `configure --enabled-ddr ...` without ibmruntimes/openj9-openjdk-jdk11#259.

**Comment by keithc-ca** [comment]
The travis build is sufficient testing for this. Further testing can occur in ibmruntimes/openj9-openjdk-jdk11#259.

**Pull request merged**
