### PR TITLE
No longer pass VENDOR variables to Test jobs

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Adopt test pipelines do not use these variables.
- These were originally used when we had our own test jobs
- Cleanup dead code

[skip ci]
Related #1450

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@llxia Please confirm the Test pipelines do not use these variables.

**Comment by AdamBrousseau** [comment]
I'll do a test build with and without Artifactory before we merge this.

**Comment by llxia** [comment]
If I am not wrong, these variables were created for getting test material from other repos (i.e., internal test repos). Are we using the same script for internal builds? If so, we may still need these for internal builds.

**Comment by AdamBrousseau** [comment]
The variables I am removing are used for Vendor variable file
```
VARIABLE_FILE
VENDOR_CREDENTIALS_ID
VENDOR_REPO
VENDOR_BRANCH
```
The variables you are thinking of are used for Vendor tests:
```
VENDOR_TEST_REPOS
VENDOR_TEST_BRANCHES
VENDOR_TEST_SHAS
VENDOR_TEST_DIRS
USER_CREDENTIALS_ID
```
I think we used them in our test jobs before we switched to Adopt test pipelines in order to set up our envs.

**Comment by llxia** [comment]
> I'll do a test build with and without Artifactory before we merge this.

Please paste the test build link. If it passes, I will merge this PR. Thanks.

**Comment by llxia** [comment]
Jenkins test sanity xlinux jdk12

**Comment by AdamBrousseau** [comment]
@llxia better late than never :)
https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK11-linux_x86-64_cmprssptrs/707

**Pull request merged**
