### PR TITLE
Rename global register allocated indexes on ParameterSymbol

### PR DESCRIPTION
**Pull request by 0xdaryl**
Use renamed API from OMR #4025.

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
@fjeremic , I'd appreciate a review and merge once testing completes please.

**Comment by fjeremic** [comment]
We'll have to wait for OMR-Acceptance promotion to kick off builds for this one.

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk11

**Pull request merged**
