### PR TITLE
Enable OpenJ9 OpenJDK8 build flag

### PR DESCRIPTION
**Pull request by vsebe**
Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Please fix the copyright

**Comment by vsebe** [comment]
Noted, copyright fixed, thank you!

**Comment by DanHeidinga** [comment]
I'm assuming this change is for IBM's internal builds, correct?  (We've really got to finish moving that infrastructure code out of the Eclipse project.....)

**Comment by vsebe** [comment]
@DanHeidinga correct

**Pull request merged**
