### PR TITLE
Deprecate unused transformStringIndexOfCall

### PR DESCRIPTION
**Pull request by fjeremic**
The corresponding String API has not existed since the inception of
OpenJ9 and I cannot find any traces of it internally as far back as I
look. The JIT code is therefore dead, so we should not waste compile
time cycles on this.

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
This was first seen in a miscellaneous JITaaS PR #4320. @mpirvu could I please get a review?

**Comment by mpirvu** [comment]
Jenkins test sanity all jdk8

**Comment by mpirvu** [comment]
All sanity tests failed due to infra. Let's try again:

Jenkins test sanity all jdk8

**Comment by mpirvu** [comment]
Failing tests are due to infra, hence merging.

**Pull request merged**
