### PR TITLE
Implement methods in TR_ResolvedRelocatableJ9JITaaSServerMethod

### PR DESCRIPTION
**Pull request by a7ehuo**
Implement methods in TR_ResolvedRelocatableJ9JITaaSServerMethod

Issue: 4401

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Comment by a7ehuo** [comment]
@mpirvu FYI

**Comment by mpirvu** [comment]
Please rebase so that I can merge

**Comment by a7ehuo** [comment]
@mpirvu Will do.

**Comment by a7ehuo** [comment]
@mpirvu Conflicts resolved. Please help review and merge. Thanks.

**Pull request merged**
