### PR TITLE
Enable OpenSSL for JDK11 on zLinux

### PR DESCRIPTION
**Pull request by keithc-ca**
Previously included in https://github.com/eclipse/openj9/pull/3992.

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile zlinux jdk11 depends ibmruntimes/openj9-openjdk-jdk11#79

**Comment by pshipton** [comment]
@enasser seems openssl is still not working on zlinux. Here is the new build https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK11-linux_390-64_cmprssptrs-OpenJ9/29

**Comment by enasser** [comment]
> @enasser seems openssl is still not working on zlinux. Here is the new build https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK11-linux_390-64_cmprssptrs-OpenJ9/29

I think the changes from Moving CONFIGURE_OPENSSL from CUSTOM_EARLY_HOOK to CUSTOM_LATE_HOOK #79 are not included in this build as it's based on SHA 928b09c2f39f1d89

I have tested in my zLinux box and confirmed it's working and successfully built.

**Comment by pshipton** [comment]
@enasser see the next part of the build
```
16:37:10  * [new ref]         refs/pull/79/merge -> origin/pr/79/merge
[Pipeline] sh
16:37:11 + git checkout refs/remotes/origin/pr/79/merge
16:37:12 Previous HEAD position was 928b09c... Merge pull request #78 from keithc-ca/openssl
16:37:12 HEAD is now at 8a3f4fa... Merge 84aeadb1edf6800659f973a03b4f6c95a00c927f into 928b09c2f39f1d893ee6a9559f3642b89afc69cf
```

**Comment by enasser** [comment]
@pshipton Thank you for your response. Yes,  I noticed it and updated my previous comment. Looks like it was not updated earlier. I will analyze whether there is any issue in the path where fetching the source but using pre-built openssl.

**Comment by pshipton** [comment]
ibmruntimes/openj9-openjdk-jdk11#79 is merged. I'll try another build just in case.

**Comment by pshipton** [comment]
jenkins compile zlinux jdk11

**Comment by pshipton** [comment]
The new build with merged ibmruntimes/openj9-openjdk-jdk11#79 still doesn't work
https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK11-linux_390-64_cmprssptrs-OpenJ9/30

**Comment by pshipton** [comment]
@enasser is it possible to use `--with-openssl=fetched` for zlinux on jdk11?

**Comment by pshipton** [comment]
I found https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/122#issuecomment-427731387
The openssl issues are closed and I think part of 1.1.1a

@jdekonin try changing to `--openssl-version=1.1.1a` and for zlinux `--with-openssl=fetched`. Could do that for 8 as well, and I'll run all the PR testing to confirm it is good. If it works we won't need `/home/jenkins/openssl-1.1.1`

**Comment by pshipton** [comment]
Oops, @keithc-ca I should have pinged you in the previous comment rather than Joe. https://github.com/eclipse/openj9/pull/4020#issuecomment-447025705

**Comment by keithc-ca** [comment]
Ok, I'll give that a try.

**Comment by keithc-ca** [comment]
Updated to fetch 1.1.1a.

**Comment by keithc-ca** [comment]
Jenkins compile zlinux jdk8,jdk11

**Comment by pshipton** [comment]
The PR testing is still getting the 1.1.1 sources and ignoring the change to get 1.1.1a. Strangely this worked for jdk11 but not jdk8. I suppose this means it is related to the gcc version being used. It does mean we could enable openssl for zlinux jdk11 while considering how to upgrade to 1.1.1a without the automated PR testing.

**Comment by keithc-ca** [comment]
Jenkins compile zlinux jdk8,jdk11

**Pull request merged**
