### PR TITLE
Add String.charAt in list of alwaysWorthInlining list

### PR DESCRIPTION
**Pull request by r30shah**
Add String.charAt in list of alwaysWorthInlining list

Signed-off-by: Rahil Shah <rahil@ca.ibm.com>

### CODE REVIEW

**Comment by r30shah** [comment]
@fjeremic  @andrewcraik  Can I please get review on this change?

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8

**Comment by andrewcraik** [comment]
Given that this is a perf change what perf evaluation has been done to justify it?

**Comment by r30shah** [comment]
I will do some sanity perf testing in a day or two on these changes with both JDK11 and JDK8 and post results here.

**Comment by andrewcraik** [comment]
@r30shah any perf data to support his change yet?

**Comment by r30shah** [comment]
@andrewcraik  I ran Daytrader-7 with Liberty server using OpenJDK11-OpenJ9 with this change. 
Here are the throughput results. 

|                           | OpenJ9-OpenJDK11 Baseline | OpenJ9-OpenJDK11 String Inl Changes | 
|---------------|-------------------------------|----------------------------------------|
| % Throughput | 100 |  101   |
| % STDEV         | 0.78 | 0.52 |

With the changes, I am seeing **1 % ** improvement in the throughput. For compilation time, I did not launched a large batch of runs but collected average compilation time from couple of runs and I do not see any noticeable impact on the compile time performance. 
Please let me know if you want me to try any other workload.

**Comment by andrewcraik** [comment]
Thanks for the data @r30shah - I think that is sufficient to justify the change. I will start the sanity builds.

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by r30shah** [comment]
Seems like build does not even start, failing on some infrastructure issue. 
```
java.io.IOException: Tried to load head FlowNodes for execution Owner[Build_JDK11_s390x_linux_Personal/335:Build_JDK11_s390x_linux_Personal #335] but FlowNode was not found in storage for head id:FlowNodeId 1:51
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.initializeStorage(CpsFlowExecution.java:679)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:716)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:665)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.onLoad(WorkflowRun.java:529)
	at hudson.model.RunMap.retrieve(RunMap.java:225
```

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by DanHeidinga** [comment]
Jenkins test sanity all jdk8

**Comment by DanHeidinga** [comment]
Relaunching the JDK8 builds on this as starting both 8 & 11 at once is overwhelming jenkins.  Someone will need to relaunch the 11 builds after a suitable delay

**Comment by r30shah** [comment]
Still fails in https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/2165/ , not sure if it is infrastructure issue or something oddly wrong with the commit.

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8

**Comment by r30shah** [comment]
Looking at the macOS falure, I do not see any test failing, just seeing following message which seems like trying to connect to host but failed. Do not think so changes in this PR can cause this. 
```
12:31:33  _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
16:20:03  Cannot contact osx1013-x86-3: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on osx1013-x86-3 failed. The channel is closing down or has closed down
Cancelling nested steps due to timeout
```

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk11

**Comment by r30shah** [comment]
Looking at the failures, 
x86Linux JDK11 failure,
```
Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on cent6-x64-6 failed. The channel is closing down or has closed down
	at hudson.remoting.Channel.call(Channel.java:950)
	at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1060)
	at hudson.Launcher$ProcStarter.start(Launcher.java:455)
```

x86MacOS failures,
```
 Cannot contact osx1013-x86-3: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on osx1013-x86-3 failed. The channel is closing down or has closed down
```
Seems like infrastructure failures. Can we launch the build again?

**Comment by r30shah** [comment]
@andrewcraik  / @fjeremic  Not sure why we had failures previously. Can we try a sanity build again?

**Comment by andrewcraik** [comment]
@r30shah could you update the copyright header and then message me so I can start the sanity

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8

**Pull request merged**
