### PR TITLE
Fix boolean return in SCC API

### PR DESCRIPTION
**Pull request by tajila**
Fix boolean return in SCC API

Signed-off-by: tajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Comment by DanHeidinga** [comment]
Related to https://github.com/eclipse/openj9/pull/3678

**Comment by DanHeidinga** [comment]
@tajila Can you also search for other JNI natives in the OpenJ9 that return jboolean and ensure they return clean booleans?

**Comment by tajila** [comment]
I checked `/runtime/jcl` and `/runtime/j9vm` and the boolean returns look correct

**Pull request merged**
