### PR TITLE
Revert "Revert to gcc 7.3 on xlinux" which switches to gcc 7.5

### LINKED ISSUE #8534: xlinux switch to gcc 7.5 causing protobuf undefined symbol
https://github.com/eclipse/openj9/pull/8443 caused a protobuf undefined symbol on xlinux.

`undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev`

https://github.com/eclipse/openj9/pull/8533 reverts back to gcc 7.3 while we sort it out.

I expect https://github.com/eclipse/openj9/pull/8486 "Remove protobuf from JITServer" will resolve it, but not sure how long before it gets merged.

### PR DESCRIPTION
**Pull request by pshipton**
Reverts eclipse/openj9#8533

Closes #8534

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Change itself is fine.  Can you add a comment as to why this is OK to revert the revert now?

**Comment by jdekonin** [comment]
> Change itself is fine. Can you add a comment as to why this is OK to revert the revert now?

There was a problem with the setup concerning gcc-7.5 on the x86 machines, and it appears that protobuf needed to be recompiled with the new version of gcc.

jenkins test sanity xlinux,linuxxl jdk8,jdk11

**Comment by jdekonin** [comment]
jenkins test sanity xlinux,xlinuxxl jdk8,jdk11

**Comment by jdekonin** [comment]
- [ ] cent6-x64-1
- [ ] cent6-x64-2
- [ ] cent6-x64-3
- [ ] cent6-x64-4
- [ ] cent6-x64-5

**Comment by pshipton** [comment]
>  Can you add a comment as to why this is OK to revert the revert now?

This can be merged when #8534 is resolved.

**Comment by pshipton** [comment]
The 4 machines used for the PR builds are fine. Assuming the rest are as well.

**Comment by pshipton** [comment]
The last sanity build hasn't finished, but gcc 7.5 is obviously working. Trying to compile with 7.3 results in an undefined symbol now, so I'll go ahead and merge this.

**Pull request merged**
