### PR TITLE
Migrate Test Kit Gen to its own repo

### PR DESCRIPTION
**Pull request by renfeiw**
- remove Test Kit Gen from TestConfig
- add build.xml to TestConfig folder
- update documents
- udpate .gitignore

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by renfeiw** [comment]
related PR: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1472

**Comment by llxia** [comment]
I think we are missing `gitignore` file

**Comment by llxia** [comment]
Depending on the merging order, this PR may affect 
https://github.com/eclipse/openj9/pull/7867 
https://github.com/eclipse/openj9/pull/7882

We will use `resultsSum.pl` and `ottawa.csv` in TKG repo after this PR.

**Comment by renfeiw** [comment]
updated .gitignore file

**Comment by llxia** [comment]
#7882 is merged. Please rebase.

**Comment by llxia** [comment]
I will deliver #7882 into TKG

**Comment by llxia** [comment]
PR https://github.com/AdoptOpenJDK/TKG/pull/13

**Comment by llxia** [comment]
Cannot test using PR builds as this PR needs the changes in Adopt. Tested in internally.

**Comment by keithc-ca** [comment]
Are documentation updates (e.g. documents in https://github.com/eclipse/openj9/tree/master/doc/build-instructions) and script updates (e.g. https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/get_source.sh and https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/closed/get_j9_source.sh for each extension repo) coming soon?

**Comment by llxia** [comment]
This is a test change and does not affect build at all. The test docs are updated.

**Pull request merged**
