### PR TITLE
Enable class sharing by default on OSX

### LINKED ISSUE #3333: -Xshareclasses by default causes a number of issues
When -Xshareclasses:bootClassesOnly was enabled by default on xlinux jdk11, a number of issues occurred which I believe are all caused by AOT code in the shared cache.

https://github.com/eclipse/omr/issues/3075 / https://github.com/eclipse/openj9/issues/3319
https://github.com/eclipse/omr/issues/3076
https://github.com/eclipse/omr/issues/3077
https://github.com/eclipse/openj9/issues/3316

### PR DESCRIPTION
**Pull request by hangshao0**
Closes #3333

Doc issue https://github.com/eclipse/openj9-docs/issues/149

Signed-off-by: hangshao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity osx jdk11

**Comment by pshipton** [comment]
jenkins test sanity osx jdk8

**Comment by pshipton** [comment]
jenkins compile osx jdk8

**Comment by pshipton** [comment]
jenkins compile osx jdk8

**Comment by pshipton** [comment]
jenkins compile osx jdk8

**Comment by pshipton** [comment]
jenkins test sanity osx jdk11

**Comment by pshipton** [comment]
jenkins compile osx jdk8

**Comment by pshipton** [comment]
@hangshao0 I  notice there is a test excluded via #3333 here https://github.com/eclipse/openj9/blob/82c8e950375ca004e6ae370bf47421f96e63fbc8/test/functional/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml#L400
If it was excluded because of the AOT problem then it should be enabled again before #3333 is closed.

**Comment by AdamBrousseau** [comment]
jenkins test sanity osx jdk8

**Comment by pshipton** [comment]
Not seeing any new failures in sanity testing.
I note this problem can still occur, in jdk8 testing on osx1011-x86-2
```
 [ERR] JVMSHRC659E An error has occurred while opening shared memory
 [ERR] JVMSHRC336E Port layer error code = -393970
 [ERR] JVMSHRC337E Platform error message: shmget : Cannot allocate memory
 [ERR] JVMSHRC029E Not enough memory left on the system
```

**Comment by pshipton** [comment]
jenkins test sanity osx jdk8,jdk11

**Comment by hangshao0** [comment]
> I notice there is a test excluded via #3333 here...

The change to enable this test on OSX is in this PR.

**Pull request merged**
