### PR TITLE
Misc. CodeCache and Trampoline cleanup

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Use CodeGenerator CodeCache functions
* Use NumReservedIPICTrampoline getter/setters from CodeGenerator

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Dependence on eclipse/omr#3371.

**Comment by 0xdaryl** [comment]
Jenkins test all jdk11 depends eclipse/omr#3371

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11 depends eclipse/omr#3371

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
The copyright failures are due to the calendar year roll-over.  I verified each file has the correct modification date (in some cases it was 2018).

**Comment by 0xdaryl** [comment]
eclipse/omr#3371 has merged and extra testing on this is complete (and successful!).  Removing WIP.

I'd appreciate a review and merge @fjeremic please.

**Comment by fjeremic** [comment]
Jenkins test sanity xlinux,zlinux JDK8

**Pull request merged**
