### PR TITLE
Remove unused RemoteCompilationRequest methodEvent

### PR DESCRIPTION
**Pull request by harryyu1994**
[skip ci]

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@mpirvu It looks like we no longer use `TR_MethodEvent::RemoteCompilationRequest` to do anything, thus removing dead code. Ready for review.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Java failure for JCL_Test_0:
```
===============================================
    JCL_TEST_Test-Annotation
    Tests run: 158, Failures: 0, Skips: 0
===============================================

java.lang.ClassLoader$ClassNameBasedLock@5fa5819f
java.lang.ClassLoader$ClassNameBasedLock@5fa5819f
java.lang.ClassLoader$ClassNameBasedLock@e7e4b239
java.lang.ClassLoader$ClassNameBasedLock@e7e4b239
#0: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x895b15) [0x7f441e2d2b15]
#1: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x8a1d70) [0x7f441e2ded70]
#2: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x17222e) [0x7f441dbaf22e]
#3: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x1ed7a) [0x7f441fdb9d7a]
#4: /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7f44261ba390]
#5: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1c5663) [0x7f441dc02663]
#6: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1f2b5a) [0x7f441dc2fb5a]
#7: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x2c0e16) [0x7f441dcfde16]
#8: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x2cd276) [0x7f441dd0a276]
#9: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x184f89) [0x7f441dbc1f89]
#10: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x185628) [0x7f441dbc2628]
#11: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x1f8b3) [0x7f441fdba8b3]
#12: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1871a5) [0x7f441dbc41a5]
#13: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x18773e) [0x7f441dbc473e]
#14: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1833b3) [0x7f441dbc03b3]
#15: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x183802) [0x7f441dbc0802]
#16: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1838aa) [0x7f441dbc08aa]
#17: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x1f8b3) [0x7f441fdba8b3]
#18: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x183d04) [0x7f441dbc0d04]
#19: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9thr29.so(+0xe156) [0x7f442429d156]
#20: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f44261b06ba]
#21: function clone+0x6d [0x7f4425ad141d]
Unhandled exception
Type=Segmentation error vmState=0x0005ffff
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F4424549530 Handler2=00007F441FDB9B50 InaccessibleAddress=0000000000000000
RDI=00007F43EC007390 RSI=0000000000000000 RAX=00007F441E978F10 RBX=00007F43EC007390
RCX=00007F441E5147C8 RDX=00007F441E978F10 R8=0000000000000000 R9=0000000000000000
R10=0000000000000000 R11=0000000000000004 R12=00007F441E54784A R13=00007F441E5147C8
R14=00007F441DC07C70 R15=00007F44101E4AA0
RIP=00007F441DC02663 GS=0000 FS=0000 RSP=00007F43FAEF9858
EFlags=0000000000010206 CS=0033 RBP=0000000000000000 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000000
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 000000ffffffffff (f: 4294967296.000000, d: 5.432309e-312)
xmm2 6e616c2f6176616a (f: 1635148160.000000, d: 5.038250e+223)
xmm3 6f766e692f676e61 (f: 795307648.000000, d: 8.502194e+228)
xmm4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm6 0018008000000015 (f: 21.000000, d: 3.337882e-308)
xmm7 0010008000040000 (f: 262144.000000, d: 2.225345e-308)
xmm8 0000000000000100 (f: 256.000000, d: 1.264808e-321)
xmm9 0004000000000400 (f: 1024.000000, d: 5.562685e-309)
xmm10 ff000000000000ff (f: 255.000000, d: -5.486124e+303)
xmm11 0000000049d70a38 (f: 1238829568.000000, d: 6.120632e-315)
xmm12 000000004689a022 (f: 1183424512.000000, d: 5.846894e-315)
xmm13 0000000047ac082f (f: 1202456576.000000, d: 5.940925e-315)
xmm14 0000000048650dc0 (f: 1214582272.000000, d: 6.000833e-315)
xmm15 0000000046b73e38 (f: 1186414080.000000, d: 5.861665e-315)
Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so
Module_base_address=00007F441DA3D000

Method_being_compiled=java/lang/invoke/FoldNonvoidHandle.invokeExact_thunkArchetype_X(I)I
```

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
`JCL_Test_0` failed again
```
===============================================
    JCL_TEST_Test-Annotation
    Tests run: 158, Failures: 0, Skips: 0
===============================================

java.lang.ClassLoader$ClassNameBasedLock@5fa5819f
java.lang.ClassLoader$ClassNameBasedLock@5fa5819f
java.lang.ClassLoader$ClassNameBasedLock@e7e4b239
java.lang.ClassLoader$ClassNameBasedLock@e7e4b239
#0: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x895b15) [0x7f441e2d2b15]
#1: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x8a1d70) [0x7f441e2ded70]
#2: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x17222e) [0x7f441dbaf22e]
#3: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x1ed7a) [0x7f441fdb9d7a]
#4: /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7f44261ba390]
#5: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1c5663) [0x7f441dc02663]
#6: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1f2b5a) [0x7f441dc2fb5a]
#7: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x2c0e16) [0x7f441dcfde16]
#8: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x2cd276) [0x7f441dd0a276]
#9: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x184f89) [0x7f441dbc1f89]
#10: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x185628) [0x7f441dbc2628]
#11: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x1f8b3) [0x7f441fdba8b3]
#12: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1871a5) [0x7f441dbc41a5]
#13: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x18773e) [0x7f441dbc473e]
#14: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1833b3) [0x7f441dbc03b3]
#15: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x183802) [0x7f441dbc0802]
#16: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1838aa) [0x7f441dbc08aa]
#17: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x1f8b3) [0x7f441fdba8b3]
#18: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x183d04) [0x7f441dbc0d04]
#19: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9thr29.so(+0xe156) [0x7f442429d156]
#20: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f44261b06ba]
#21: function clone+0x6d [0x7f4425ad141d]
Unhandled exception
Type=Segmentation error vmState=0x0005ffff
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F4424549530 Handler2=00007F441FDB9B50 InaccessibleAddress=0000000000000000
RDI=00007F43EC007390 RSI=0000000000000000 RAX=00007F441E978F10 RBX=00007F43EC007390
RCX=00007F441E5147C8 RDX=00007F441E978F10 R8=0000000000000000 R9=0000000000000000
R10=0000000000000000 R11=0000000000000004 R12=00007F441E54784A R13=00007F441E5147C8
R14=00007F441DC07C70 R15=00007F44101E4AA0
RIP=00007F441DC02663 GS=0000 FS=0000 RSP=00007F43FAEF9858
EFlags=0000000000010206 CS=0033 RBP=0000000000000000 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000000
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 000000ffffffffff (f: 4294967296.000000, d: 5.432309e-312)
xmm2 6e616c2f6176616a (f: 1635148160.000000, d: 5.038250e+223)
xmm3 6f766e692f676e61 (f: 795307648.000000, d: 8.502194e+228)
xmm4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm6 0018008000000015 (f: 21.000000, d: 3.337882e-308)
xmm7 0010008000040000 (f: 262144.000000, d: 2.225345e-308)
xmm8 0000000000000100 (f: 256.000000, d: 1.264808e-321)
xmm9 0004000000000400 (f: 1024.000000, d: 5.562685e-309)
xmm10 ff000000000000ff (f: 255.000000, d: -5.486124e+303)
xmm11 0000000049d70a38 (f: 1238829568.000000, d: 6.120632e-315)
xmm12 000000004689a022 (f: 1183424512.000000, d: 5.846894e-315)
xmm13 0000000047ac082f (f: 1202456576.000000, d: 5.940925e-315)
xmm14 0000000048650dc0 (f: 1214582272.000000, d: 6.000833e-315)
xmm15 0000000046b73e38 (f: 1186414080.000000, d: 5.861665e-315)
Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so
Module_base_address=00007F441DA3D000

Method_being_compiled=java/lang/invoke/FoldNonvoidHandle.invokeExact_thunkArchetype_X(I)I
```

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
This time only the known `cmdLineTester_gcsuballoctests_0` test failed, hence merging.

**Pull request merged**
