### PR TITLE
Increase scratchSpaceLimit for JITServer

### PR DESCRIPTION
**Pull request by harryyu1994**
Increase scratchSpaceLimit by a factor of 2 on JITServer
Issue: #5644

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
Origin PR here: https://github.com/eclipse/openj9/pull/7943

**Comment by harryyu1994** [comment]
@mpirvu This one is ready for review.

**Comment by mpirvu** [comment]
Jenkins test sanity xlinux jdk8

**Comment by mpirvu** [comment]
The code delivered is JITServer specific and testing has passed, hence merging.

**Pull request merged**
