### PR TITLE
Create HeapRegionStateTable on VLHGC startup

### PR DESCRIPTION
**Pull request by youngar**
The table will track the current state of each region in VLHGC.

cc @amicic @charliegracie @rwy0717

### CODE REVIEW

**Comment by amicic** [comment]
Looks good to me.

I wish though the table name were more specific, something like Evacuate (or CopyForward) Region Lookup table.

**Comment by youngar** [comment]
The idea is we could stuff other region states in there that have nothing to do with CopyForward, or even VLHGC.  I think that might have made more sense when I was trying to provide some utility to stuff arbitrary language data at the header of the region. I'll put it on my list of TODOs since there isn't a reason for it to be so generic.

**Comment by amicic** [comment]
We have Region Descriptors and Region Managers (tables of descriptors) for various other states (where even Copy Forward state info could go), but access is rather slow (not cache friendly) Lookup table like this one should be the leanest most optimized variant for specific purpose and would then carry a specific name. If there is a chance to stuff in something else (for example info if region is to be marked rather than evacuated), then give a more appropriate name, or just leave it as is.

**Comment by youngar** [comment]
I have started this work in https://github.com/eclipse/omr/pull/4055. It would be easier for me to wait until all the current PRs are accepted and then change it.

**Comment by dmitripivkine** [comment]
Jenkins compile win jdk8

**Comment by dmitripivkine** [comment]
Jenkins test sanity xLinux jdk11

**Pull request merged**
