### PR TITLE
Add Test subfolder to repo path

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- The subfolder 'Test' is added to test jobs when
  they upload to Artifactory. This extra bit is set in
  the Test Autogen job.

[skip ci]

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Marked as draft for now. Pointed the job at my branch temporarily until I decide if this is the right fix.

**Comment by AdamBrousseau** [comment]
@pshipton

**Comment by pshipton** [comment]
jenkins test extended.system zlinux jdk8

**Comment by pshipton** [comment]
> The subfolder 'Test' is added to test jobs when they upload to Artifactory

Has this always been true?

**Comment by AdamBrousseau** [comment]
PR testing won't excersize the change. The [cleanup job](https://ci.eclipse.org/openj9/job/Cleanup_Artifactory/) is currently pointed at this branch and it seems to be cleaning test artifats now..

> Has this always been true?

I think as long as we've had Artifactory externally. This script is only used externally. Internally we have Pro edition so there's no need for this manual cleanup.

**Pull request merged**
