### PR TITLE
Implement JIT hook for static final field modification

### PR DESCRIPTION
**Pull request by liqunl**
Add the JIT infrastructure of registering assumptions for static final
field folding and implement the JIT hook to patch guards for violated
assumptions.

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@andrewcraik Could you review?

**Comment by andrewcraik** [comment]
@jdmpapin would appreciate your thoughts when you get time too since you are familiar with the assumptions infrastructure.

**Comment by liqunl** [comment]
@jdmpapin ping?

**Comment by liqunl** [comment]
Set the bit in JIT hook since VM has stopped setting the bit.

**Comment by andrewcraik** [comment]
@liqunl can you reply to the question above about the unused variable? if it is dead please clean it up so we can get this merged.

**Comment by liqunl** [comment]
The copyright and line endings check are broken. @AdamBrousseau

**Comment by AdamBrousseau** [comment]
Jenkins copyright check
Jenkins line endings check

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Pull request merged**
