### PR TITLE
Pull artifacts from Artifactory for Dockerfile

### PR DESCRIPTION
**Pull request by JennyChenyj**
- Files for IBM Docker images were uploaded to    
 Artifactory.
 - Modified the docker build command to pass
 the Artifactory link to Dockerfile.

[skip ci]

Signed-off-by: Jenny Chen <Jenny.Chen@ibm.com>

### CODE REVIEW

**Comment by JennyChenyj** [comment]
Hey @AdamBrousseau! I tried the password and username did not work for curl and then switched to API keys. Thanks for your feedback!

**Comment by JennyChenyj** [comment]
Hey @AdamBrousseau! Thanks for reviewing it! :)

**Comment by JennyChenyj** [comment]
Hey @AdamBrousseau! Could I close this issue for now?

**Comment by AdamBrousseau** [comment]
Sure, I don't think we will need this anytime soon.

**Pull request closed without merging**
