### PR TITLE
Stop translating invokevirtual to invokespecial during HCR

### PR DESCRIPTION
**Pull request by gacholio**
Normal class loading stopped doing this a while ago, but for some reason
the HCR path did not get fixed. Remove the caller and implementation of
the translator.

Fixes: #7696

[ci skip]

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk8

**Comment by gacholio** [comment]
jenkins test extended plinux jdk11

**Comment by pshipton** [comment]
jenkins test extended win32 jdk8

**Comment by DanHeidinga** [comment]
Original change that stopped the conversion of invokevirtual -> invokespecial: https://github.com/eclipse/openj9/pull/7666

**Pull request merged**
