### PR TITLE
TestKitGen Java

### PR DESCRIPTION
**Pull request by renfeiw**
- redesign testKitGen in object oriented structure
- java implementation allows tkg to run on all platforms
- remove dependencies on perl and its modules
- keep the java tkg run on the side of perl tkg
- match java tkg result with perl tkg result for testing
- will make update to java tkg after it's tested

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewers: @smlambert @llxia

**Comment by llxia** [comment]
jenkins test sanity,extended all jdk8

**Comment by llxia** [comment]
jenkins test sanity all jdk8

**Comment by llxia** [comment]
Jenkins is down. Will launch PR builds later

**Comment by llxia** [comment]
jenkins test sanity,extended all jdk8

**Comment by llxia** [comment]
`testSCCMLTests1_openj9` failure is related to https://github.com/eclipse/openj9/issues/6801

**Pull request merged**
