### PR TITLE
Flip order of exports in LIBPATH

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Fixes https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/129
Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity aix jdk8

**Comment by smlambert** [comment]
jenkins test all xlinux jdk8

**Comment by pshipton** [comment]
i.e. https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/111/console

**Comment by pshipton** [comment]
The job shows:
`LIBPATH=/usr/java8_64/jre/lib/ppc64/j9vm:/usr/java8_64/jre/lib/ppc64:/usr/java8_64/jre/lib/ppc64/jli:/usr/java8_64/jre/../lib/ppc64:/usr/lib`

**Comment by pshipton** [comment]
Perhaps this is the problem?
https://github.com/eclipse/openj9/blob/ab4c516e988d931a266b91eff789be2d9dd0c80e/test/TestConfig/openj9Settings.mk#L101

**Comment by pshipton** [comment]
@Mesbah-Alam can you please try the grinder and see if its working now.

**Comment by Mesbah-Alam** [comment]
The process works when I run manually logging onto the machine. 
Here's what I have done: 
Logging into pll011.rtp.raleigh.ibm.com: 
```
1) cd /tmp/mesbah
2)  git clone https://github.com/AdoptOpenJDK/openjdk-tests
3) cd openjdk-tests
4)  /get.sh -s /tmp/mesbah -t /tmp/mesbah/openjdk-tests -p ppc64_aix -r nightly -j SE80 -i openj9 --openj9_repo https://github.com/Mesbah-Alam/openj9.git --openj9_branch update_libpath
5) cd TestConfig
6) export JAVA_BIN=/tmp/mesbah/openjdkbinary/j2sdk-image/jre/bin
7) export SPEC=aix_ppc-64_cmprssptrs
8) export BUILD_LIST=systemtest
9) export JDK_VERSION=8
10) make -f run_configure.mk
11) make compile <---- This is where it breaks in the build, but running manually, it works fine! 
```

**Pull request merged**
