### PR TITLE
Cleanup work for deprecated IL opcodes

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Remove merged new allocation code
* Cleanup work for deprecated IL opcodes

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk8,jdk11 depends eclipse/omr#5941

**Comment by 0xdaryl** [comment]
Jenkins test sanity win,xlinux jdk11 depends eclipse/omr#5941

**Comment by 0xdaryl** [comment]
Jenkins test sanity win32 jdk8 depends eclipse/omr#5941

Win32 build was aborted for some reason.

**Comment by 0xdaryl** [comment]
Jenkins test sanity win32 jdk8 depends eclipse/omr#5941

Another Win32 infra issue (lost contact with slave).  Trying again.

**Comment by 0xdaryl** [comment]
Jenkins test sanity win32 jdk8 depends eclipse/omr#5941

The previous 3 attempts ended with infra issues.  One more try.

**Comment by 0xdaryl** [comment]
@AdamBrousseau : is the Windows 32-bit CI issue a known issue? -> https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_Personal/807/

**Comment by AdamBrousseau** [comment]
I have not seen that Artifactory error before that I recall. The build did fail to compile. I'm not sure why, but it is passing in the [Nightly](https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_Nightly/). Does the compile work either by hand or on an internal personal build?

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk8,jdk11 depends eclipse/omr#5941

Re-running testing to pick up an OMR CMake fix that was preventing the Win32 build from running.

**Comment by 0xdaryl** [comment]
Un-WIPing and assigning to @fjeremic as this PR and eclipse/omr#5941 must be a coordinated merge.

**Review by fjeremic — APPROVED** [review]

**Pull request merged**
