### PR TITLE
Remove use of DecimalFormatHelper in JITServer

### PR DESCRIPTION
**Pull request by liqunl**
Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@andrewcraik WIP this PR while I'm testing

**Comment by liqunl** [comment]
@andrewcraik Change has been tested

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk14

**Comment by liqunl** [comment]
@andrewcraik Test has passed

**Pull request merged**
