### PR TITLE
Add generic test target

### PR DESCRIPTION
**Pull request by renfeiw**
Generic target includes all subtests with different variations.

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewers: @llxia @TianyuZuo

**Comment by llxia** [comment]
Jenkins test sanity

**Comment by smlambert** [comment]
To be clear about what this PR does, in a playlist.xml file, when there is more than 1 variation defined (the test should be run in more than 1 mode or set of commandline options), this PR creates a test target that will run all of them.

For example, if my playlist contained something like this:
		<testCaseName>jit_hw</testCaseName>
		<variations>
			<variation>-Xdump:java -Xgcpolicy:gencon -Xjit:count=0,optLevel=hot</variation>
			<variation>-Xdump:java -Xgcpolicy:optavgpause -Xjit:count=0</variation>
			<variation>-Xdump:java -Xjit:enableHCR,enableOSR,count=0</variation>
		</variations> ...

And I wanted to run this test, I would run jit_hw_0 (which would execute the test with the gencon option, and jit_hw__1, which would execute it with the optavgpause option, and jit_hw_2 would use the enableHCR option). Now if I run jit_hw, it will run the test 3x, first with gencon, then with optavgpause option and finally with enableHCR.

Correct?

**Comment by renfeiw** [comment]
Thanks @smlambert for clarifying the content of this PR.

**Comment by renfeiw** [comment]
@fjeremic thanks, updated commit message and PR comment.

**Comment by smlambert** [comment]
Jenkins test sanity plinux

**Comment by smlambert** [comment]
JDK8 sanity test failure is a separate issue being worked, will proceed with merging this PR.

**Pull request merged**
