### PR TITLE
Remove unnecessary UMA_SP_CFLAGS, and the _sp SPECs from gc_glue_java

### PR DESCRIPTION
**Pull request by pshipton**
Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Jenkins compile win,aix,plinux jdk8

**Comment by DanHeidinga** [comment]
@pshipton can you resolve the conflicts?

**Comment by DanHeidinga** [comment]
I'll note that all the compiles testing this have passed

**Comment by pshipton** [comment]
@DanHeidinga merge conflicts are resolved.

**Pull request merged**
