### PR TITLE
Use TestKitGen java for testing

### PR DESCRIPTION
**Pull request by renfeiw**
- use tkg java and assert the result in tkg perl

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by llxia** [comment]
jenkins test sanity,extended all jdk8

**Comment by llxia** [comment]
jenkins test sanity,extended all jdk8

**Comment by llxia** [comment]
jenkins test sanity,extended win jdk8

**Comment by llxia** [comment]
jenkins test sanity,extended all jdk11

**Comment by llxia** [comment]
jenkins test sanity,extended plinux,linux,osx jdk11

**Comment by llxia** [comment]
jenkins test sanity,extended plinux,xlinux,osx jdk11

**Comment by llxia** [comment]
jenkins test sanity,extended xlinuxxl jdk11

**Pull request merged**
