### PR TITLE
Support exception event hooks in AOT

### PR DESCRIPTION
**Pull request by dsouzai**
At JIT bootstrap, if the compiler detects that an exception event could
be hooked, it prevents AOT compilation. There isn't any apparent reason
for why this should be the case. This PR allows AOT compilation to
occur if an exception event can be hooked. However, if a method was
AOT compiled with the assumption that no exception event could be
hooked then the method isn't loaded.

Small test I wrote:
```
class SpecialException extends Throwable {
}

class ExceptionTest {

        public int count;
        public int sleep;

        public ExceptionTest() {
                count = 0;
        }

        public void doSomeWork(boolean doThrow) throws SpecialException {
                count++;
                if (doThrow) {
                        throw new SpecialException();
                }

        }
}

public class TestAOTException {

        public static void main(String args[]) throws SpecialException {

                ExceptionTest test = new ExceptionTest();

                for (int i = 0; i < 1000; i++) {
                        test.doSomeWork(false);
                }

                try {
                        Thread.sleep(4000);
                } catch (InterruptedException e) {}

                try {
                        test.doSomeWork(true);
                } catch (SpecialException e) {
                        System.out.println("Caught Exception, count = " + test.count);
                }
        }
}
```
### Enabling exception hook on second run but not first
```
[dsouzai@localhost testAOTException]$ ../jdk11/bin/java -Xshareclasses:name=test_aot_exception '-Xjit:count=100,verbose={compilePerformance},vlog=vlog,disableSuffixLogs' TestAOTException
Caught Exception, count = 1001
[dsouzai@localhost testAOTException]$ ../jdk11/bin/java -Xshareclasses:name=test_aot_exception '-Xjit:count=100,verbose={compilePerformance},vlog=vlog,disableSuffixLogs' TestAOTException
Caught Exception, count = 1001
```
Note the body gets loaded if no hook is specified:
```
[dsouzai@localhost testAOTException]$ grep 'doSomeWork' vlog 
 (cold) Compiling ExceptionTest.doSomeWork(Z)V  OrdinaryMethod j9m=00000000001C5120 t=60 compThreadID=0 memLimit=262144 KB freePhysicalMemory=13106 MB
+ (AOT load) ExceptionTest.doSomeWork(Z)V @ 00007FB1114C6AC0-00007FB1114C6C15 Q_SZ=31 Q_SZI=31 QW=140 j9m=00000000001C5120 bcsz=23 time=42us compThreadID=0
```
However, when the hook is specified, the method is not loaded:
```
[dsouzai@localhost testAOTException]$ ../jdk11/bin/java -Xshareclasses:name=test_aot_exception '-Xjit:count=100,verbose={compilePerformance},vlog=vlog,disableSuffixLogs' -Xdump:java:events=throw,filter=SpecialException TestAOTException
JVMDUMP039I Processing dump event "throw", detail "SpecialException" at 2020/12/11 16:16:19 - please wait.
JVMDUMP032I JVM requested Java dump using '/home/dsouzai/dev/src/openj9/testAOTException/javacore.20201211.161619.24322.0001.txt' in response to an event
JVMDUMP010I Java dump written to /home/dsouzai/dev/src/openj9/testAOTException/javacore.20201211.161619.24322.0001.txt
JVMDUMP013I Processed dump event "throw", detail "SpecialException".
Caught Exception, count = 1001
[dsouzai@localhost testAOTException]$ grep 'doSomeWork' vlog 
 (cold) Compiling ExceptionTest.doSomeWork(Z)V  OrdinaryMethod j9m=00000000001D8220 t=140 compThreadID=0 memLimit=262144 KB freePhysicalMemory=13108 MB
! (cold) ExceptionTest.doSomeWork(Z)V time=57us compilationAotValidateExceptionHookFailure memLimit=262144 KB freePhysicalMemory=13108 MB mem=[region=64 system=16384]KB
```
The javacore shows an interpreted method:
```
[dsouzai@localhost testAOTException]$ grep 'doSomeWork' javacore.20201211.161619.24322.0001.txt
4XESTACKTRACE                at ExceptionTest.doSomeWork(TestAOTException.java:16)
```

### Enabling exception hook on both runs
```
[dsouzai@localhost testAOTException]$ ../jdk11/bin/java -Xshareclasses:name=test_aot_exception '-Xjit:count=100,verbose={compilePerformance},vlog=vlog,disableSuffixLogs' -Xdump:java:events=throw,filter=SpecialException TestAOTException
JVMDUMP039I Processing dump event "throw", detail "SpecialException" at 2020/12/11 16:12:45 - please wait.
JVMDUMP032I JVM requested Java dump using '/home/dsouzai/dev/src/openj9/testAOTException/javacore.20201211.161245.23696.0001.txt' in response to an event
JVMDUMP010I Java dump written to /home/dsouzai/dev/src/openj9/testAOTException/javacore.20201211.161245.23696.0001.txt
JVMDUMP013I Processed dump event "throw", detail "SpecialException".
Caught Exception, count = 1001
[dsouzai@localhost testAOTException]$ ../jdk11/bin/java -Xshareclasses:name=test_aot_exception '-Xjit:count=100,verbose={compilePerformance},vlog=vlog,disableSuffixLogs' -Xdump:java:events=throw,filter=SpecialException TestAOTException
JVMDUMP039I Processing dump event "throw", detail "SpecialException" at 2020/12/11 16:12:52 - please wait.
JVMDUMP032I JVM requested Java dump using '/home/dsouzai/dev/src/openj9/testAOTException/javacore.20201211.161252.23729.0001.txt' in response to an event
JVMDUMP010I Java dump written to /home/dsouzai/dev/src/openj9/testAOTException/javacore.20201211.161252.23729.0001.txt
JVMDUMP013I Processed dump event "throw", detail "SpecialException".
Caught Exception, count = 1001
```
Notice now body is loaded:
```
[dsouzai@localhost testAOTException]$ grep 'doSomeWork' vlog 
 (cold) Compiling ExceptionTest.doSomeWork(Z)V  OrdinaryMethod j9m=00000000001CD0C8 t=50 compThreadID=0 memLimit=262144 KB freePhysicalMemory=13108 MB
+ (AOT load) ExceptionTest.doSomeWork(Z)V @ 00007FD3D4FD8940-00007FD3D4FD8A95 Q_SZ=27 Q_SZI=27 QW=137 j9m=00000000001CD0C8 bcsz=23 time=152us compThreadID=0
```
Additionally, the javacore shows a compiled body:
```
[dsouzai@localhost testAOTException]$ grep 'doSomeWork' javacore.20201211.161252.23729.0001.txt
4XESTACKTRACE                at ExceptionTest.doSomeWork(TestAOTException.java:16(Compiled Code))
```
Added benefit; if the hook is not specified in the second run, we will still successfully load. This is because the code is still perfectly functional; it's just less optimized:
```
[dsouzai@localhost testAOTException]$ ../jdk11/bin/java -Xshareclasses:name=test_aot_exception '-Xjit:count=100,verbose={compilePerformance},vlog=vlog,disableSuffixLogs' TestAOTException
Caught Exception, count = 1001
[dsouzai@localhost testAOTException]$ grep 'doSomeWork' vlog 
 (cold) Compiling ExceptionTest.doSomeWork(Z)V  OrdinaryMethod j9m=00000000001C5120 t=60 compThreadID=0 memLimit=262144 KB freePhysicalMemory=13106 MB
+ (AOT load) ExceptionTest.doSomeWork(Z)V @ 00007F17A1085B80-00007F17A1085CD5 Q_SZ=30 Q_SZI=30 QW=147 j9m=00000000001C5120 bcsz=23 time=39us compThreadID=0
```

### CODE REVIEW

**Comment by dsouzai** [comment]
@vijaysun-omr question for you. This PR adds support for allowing AOT code to get loaded if an exception event was hooked. However, if in the compile run we didn't specify something like `-Xdump:java:events=throw....` but in the load run we **did** specify it, then we won't load it. 

Now, we _could_ always assume that an exception event could be hooked in some future load run. This would mean always generating AOT code with `TR_DisableThrowToGoto` set and `J9::Options::_reportByteCodeInfoAtCatchBlock` set to true (the latter of which results disabling merging of GC Maps). However, this is going to result in less optimal AOT code. Do you think it's reasonable take the code quality hit, or is the approach taken in this PR sufficient?

**Comment by dsouzai** [comment]
> Now, we could always assume that an exception event could be hooked in some future load run. 

Maybe something for portable AOT if we don't want it on by default?

**Comment by dsouzai** [comment]
@mpirvu @mstoodle I'd appreciate your opinions as well.

**Comment by mpirvu** [comment]
What is the most common scenario here? I envision that users would generate AOT without `-Xdump:java:events=throw`, then some bug is detected in one of the 'warm' runs and service will ask the user to add `-Xdump:java:events=throw` to the command line, but this makes the bug go away. We could tell the user to keep `-Xdump:java:events=throw` on the command line as an workaround, but the performance takes a hit because many methods will end up interpreted (we should JIT compile the methods that fail with compilationAotValidateExceptionHookFailure if not already).
We could also tell the user to destroy the SCC and generate another one with `-Xdump:java:events=throw` and then hope the bug reproduces so that we can fix it. If @klangman is ok with this course of events I am ok with this PR.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by klangman** [comment]
> If @klangman is ok with this course of events I am ok with this PR.

Yes, the scenario is exactly what happened. It took some time to understand that the option was disabling AOT loads and now we are stuck without a reasonable way to debug the problem.

**Comment by dsouzai** [comment]
@mpirvu before you merge, I guess I need a JITServer version of `canExceptionEventBeHooked` right?

**Comment by mpirvu** [comment]
>  I guess I need a JITServer version of canExceptionEventBeHooked right?

Yes, could you please add that similar to how we've done the tracing stuff? Thanks

**Comment by dsouzai** [comment]
@mpirvu added JITServer implementation

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity all jdk11

**Comment by mpirvu** [comment]
Tests have passed, hence merging

**Pull request merged**
