### PR TITLE
Update paths for debug information files

### PR DESCRIPTION
**Pull request by keithc-ca**
This updates the file-name patterns to match expectations of openjdk (for inclusion in the 'debug-image').

* DDR temporarily accepts .dbg files generated by OMR (j9thr29)
* on AIX & Linux, generate .debuginfo files instead of .dbg files
* on MacOSX, generate .dSYM folders instead of flat .dbg files
* on Windows, continue using .pdb files
* on z/OS, continue using .dbg files for now

### CODE REVIEW

**Comment by pshipton** [comment]
Jenkins test sanity aix,osx,plinux,win,win32 jdk8

**Comment by pshipton** [comment]
Jenkins test sanity aix,osx,plinux,win jdk11

**Comment by keithc-ca** [comment]
@DanHeidinga Can you please explain why you closed this?

**Comment by DanHeidinga** [comment]
> @DanHeidinga Can you please explain why you closed this?

By accident when I merged https://github.com/eclipse/openj9/pull/8695.  It had the incorrect `closes:` tag and I didn't notice.  Thanks for catching and reopening this

**Pull request merged**
