### PR TITLE
Update Load Extensions deprecated APIs

### PR DESCRIPTION
**Pull request by fjeremic**
Load Extensions has been refactored and rewritten in OMR. Update the
references to deprecated APIs.

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
The dependent PR has been merged. @joransiu could I please get a review for this PR as it is currently blocking the promotion builds? If you are satisfied with the changes a merge would be great as well!

**Comment by fjeremic** [comment]
Jenkins test sanity all

**Comment by fjeremic** [comment]
Jenkins test sanity all depends eclipse/omr#2205

**Comment by joransiu** [comment]
The PR build failures seems tooling related as @fjeremic mentioned in https://github.com/eclipse/openj9/issues/935.

**Pull request merged**
