### PR TITLE
Add mac osx `PLATFORM-oa64` to the jpp config

### PR DESCRIPTION
**Pull request by DanHeidinga**
As requested in https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/118#discussion_r222369505

issue: #36 

Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
The line endings check is failing for:
```
Using context: Line Endings Check
java.lang.OutOfMemoryError: Java heap space
Caused: java.io.IOException: Remote call on proxy_worker failed
```

**Comment by DanHeidinga** [comment]
Updated to put `o` after `m` =)

**Comment by keithc-ca** [comment]
jenkins copyright check

**Comment by keithc-ca** [comment]
jenkins line endings check

**Comment by keithc-ca** [comment]
We don't need a build for this change; cancelling travis job.

**Pull request merged**
