### PR TITLE
Use TR::MemoryReference::create API

### PR DESCRIPTION
**Pull request by r30shah**
Use TR::MemoryReference::create API for constructing memory reference from node.

Signed-off-by: Rahil Shah <rahil@ca.ibm.com>

### CODE REVIEW

**Comment by r30shah** [comment]
depends on https://github.com/eclipse/omr/pull/5712

**Comment by fjeremic** [comment]
@r30shah weren't there a lot more use cases in OMR? I thought we replaced all `generateS390MemoryReference` that used the `TR::Node*` overload with the new constructor?

**Comment by r30shah** [comment]
> @r30shah weren't there a lot more use cases in OMR? I thought we replaced all generateS390MemoryReference that used the TR::Node* overload with the new constructor?

Yes, there are. I am cherry picking the commits from the snapshot repo and the one commit that replaces `generateS390MemoryReference` in `TR::MemoryReference::create` API also contains changes that removes the `generateS390MemoryReference`. So Once the introduction to TR::MemoryReference::create is merged, Next this one should go which replaces the API so that when we remove it in OMR builds won't break

> It seems we're missing the changes in awrtbariEvaluator and ardbariEvaluator.

Yes thanks a lot for pointing out, I missed them. Let me add them

**Comment by r30shah** [comment]
@fjeremic  I believe the OMR change to introduce TR::MemoryReference::create has been propagated to openj9-omr. Can we launch test on this PR ?

**Comment by fjeremic** [comment]
Jenkins test sanity.functional zlinux jdk8

**Review by fjeremic — APPROVED** [review]

**Comment by r30shah** [comment]
All checks has been passed. This one is good to go

**Pull request merged**
