### PR TITLE
Don't access ROM class from RAM class directly

### PR DESCRIPTION
**Pull request by dchopra001**
Signed-off-by: Dhruv Chopra <Dhruv.C.Chopra@ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by mpirvu** [comment]
3 failures due to infra

**Comment by mpirvu** [comment]
Jenkins test sanity xlinux jdk11

**Comment by dchopra001** [comment]
I see the following failures in the failing builds:
```
Receiving objects:  30% (2165/7140), 39.07 MiB | 474.00 KiB/s   
error: index-pack died of signal 15
fatal: index-pack failed
error: RPC failed; curl 56 SSL read: error:00000000:lib(0):func(0):reason(0), errno 110

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2042)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1761)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$400(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:442)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:655)
```

And

```
21:53:45  curl error code: 23. Sleep 300 secs, then retry 4...
21:58:36  curl -OLJks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_mac_Personal/120/OpenJ9-JDK11-x86-64_mac-20190903-004244.tar.gz
21:58:36  curl error code: 23. Sleep 300 secs, then retry 5...
22:03:45  curl -OLJks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_mac_Personal/120/OpenJ9-JDK11-x86-64_mac-20190903-004244.tar.gz
22:03:45  curl error code: 23
22:03:45  Failed to retrieve https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_mac_Personal/120/OpenJ9-JDK11-x86-64_mac-20190903-004244.tar.gz, exiting. This is what we received of the file and MD5 sum:
22:03:45  ls: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_mac_Personal/120/OpenJ9-JDK11-x86-64_mac-20190903-004244.tar.gz: No such file or directory
```

These both look like infra issues as well.

**Comment by mpirvu** [comment]
Jenkins test sanity xlinuxxl,osx jdk11

**Pull request merged**
