### PR TITLE
WIP: Update makeGen to use standard XML parser

### PR DESCRIPTION
**Pull request by renfeiw**
Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by llxia** [comment]
Please make sure to update Prerequisites in the readme file.

**Comment by mstoodle** [comment]
@renfeiw @llxia what's the current status here, please?

**Comment by renfeiw** [comment]
We are still waiting for perl XML::Parser module to be installed on all machines.

**Comment by smlambert** [comment]
Blocked by infra issue (/runtimes/tooling/issues/290).

**Comment by DanHeidinga** [comment]
@renfeiw @llxia Is this still relevant?  If so can we get it finished off?

**Comment by renfeiw** [comment]
This is not a mandotory, the current parsing code (written by ourselves) works without any problem so far. But it may require more effort to add any new parsing feature. To utilize the standard parser, we need to have perl XML::Parser module installed on all the machines. @AdamBrousseau Do we already have it installed?

**Comment by AdamBrousseau** [comment]
I see XML Parser in the Adopt Unix playbooks [here](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/7172efb95e875c7dae26c4596e4dbdf106b01aef/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/CPAN/tasks/main.yml#L42). So it may be on some machines. I recall an issue on this a while back. I could try and dig it up. We would have to verify all the machines have it. I assume it would be needed on any machine we compile test material on, ie. any machine we test on.

**Comment by llxia** [comment]
@AdamBrousseau Do you have any update on this? We would like to use the standard XML parser. Thanks.

**Comment by AdamBrousseau** [comment]
I don't think it is installed on all the machines. Please open an issue at Adopt/openjdk-infrastructure to add it to the remaining playbooks.

**Comment by llxia** [comment]
Change is merged in https://github.com/eclipse/openj9/pull/4785
Close this PR.

**Pull request closed without merging**
