### PR TITLE
Remove J9_PROJECT_SPECIFIC guards

### PR DESCRIPTION
**Pull request by tmcdermo**
Remove J9_PROJECT_SPECIFIC guards

This patch removes all 14 J9_PROJECT_SPECIFIC guards from
InlinerTempForJ9.cpp.

Closes: #1117
Signed-off-by: Thomas McDermott <mcdermot@oregonstate.edu>

### CODE REVIEW

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by fjeremic** [comment]
Sadly our builds seem to be having a bad day. I suspect it's related to all the infrastructure issues with disk space over at Eclipse CI. I checked all the failing builds and it's all related to infrastructure. I would say this PR should be good to go.

**Comment by andrewcraik** [comment]
I agree the change looks fine - I'd just like to see some sanity builds before the official merge; welcome @tmcdermo!

**Comment by andrewcraik** [comment]
so the two failures are infrastructure, the test has passed on win_x86-64_comprssptrs for Java 8 and the same code will run across all platforms and for all JVM versions so this should be good to merge. Change is also easy to visually verify so I will merge this now.

**Pull request merged**
