### PR TITLE
Fix JITServer init bug

### PR DESCRIPTION
**Pull request by harryyu1994**
- Move "jitHookVMInitialized()" to be called only in JITServer::SERVER mode
- Replace J9_CLASS_FROM_CP with getClassFromCP API

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@mpirvu This one is ready for review.

**Comment by mpirvu** [comment]
Jenkins test sanity all jdk8

**Comment by harryyu1994** [comment]
I added another commit. There are no more differences between jitaas and master branch except 1. makefile-related changes 2. dhruv's new Power changes 3. spaces.

**Comment by mpirvu** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by mpirvu** [comment]
On AIX there is a failure: jsigjnitest_0 
```
==============================================
Running test jsigjnitest_0 ...
===============================================
jsigjnitest_0 Start Time: Sat Oct 26 01:08:04 2019 Epoch Time (ms): 1572070084656
variation: NoOptions
JVM_OPTIONS: -Xcompressedrefs 
Usage: jvmlibpath[-java options]

failed to open </usr/java8_64/jre/lib/ppc64//libjvm.so> - reason: <	0509-022 Cannot load module /usr/java8_64/jre/lib/ppc64//libjvm.so.
	0509-026 System error: A file or directory in the path name does not exist.>
Attempting to open /home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_Personal/openjdkbinary/j2sdk-image/jre/bin/../lib/ppc64/j9vm/libjvm.so
About to invoke JNI_CreateJavaVM with 2 option(s).
Starting test.
Primary handler set.
Secondary handler set.
Raising signal.
Test passed. Both signal handlers invoked.
Internal Error: Failed to initialize redirector - exiting

jsigjnitest_0_FAILED
```
This doesn't seem to be caused by this PR. I'll start again.

**Comment by mpirvu** [comment]
Jenkins test sanity aix jdk11

**Comment by mpirvu** [comment]
AIX test failure does not look to be related to this PR, hence merging

**Pull request merged**
