### PR TITLE
Throw ClassCastException for Byte to char during invocation

### PR DESCRIPTION
**Pull request by fengxue-IS**
Close: #3185 

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
@fengxue-IS Is there a similar issue in the JIT implementation of the AsTypeHandle?  There should be an equivalent java method for this in AsType or a superclass.

**Comment by fengxue-IS** [comment]
I'm not sure how JIT uses asType conversion, but the method `ConvertHandle.checkConversion()` calls `checkIfWideningPrimitiveConversion()` follows the correct behaviour

**Comment by DanHeidinga** [comment]
Jenkins test all xlinux jdk11

**Comment by DanHeidinga** [comment]
Jenkins test sanity xlinux jdk11

**Comment by DanHeidinga** [comment]
Jenkins test functional xlinux jdk11

**Comment by DanHeidinga** [comment]
Jenkins test extended xlinux jdk11

**Comment by DanHeidinga** [comment]
Failures are related to `Method_being_compiled=java/util/WeakHashMap.put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;`

**Comment by DanHeidinga** [comment]
Since the fix for that issue has been merged, relaunching the builds on this.

**Comment by DanHeidinga** [comment]
Jenkins test extended xlinux jdk11

**Comment by DanHeidinga** [comment]
Jenkins test sanity xlinux jdk11

**Comment by DanHeidinga** [comment]
@fengxue-IS There are a couple of tests in the extended build failing after this change due to assertions on:
`
com.ibm.j9.jsr292.api.MethodHandleAPI_tryFinally.test_tryFinally_TryCharMethod_CharReturnType_Throwable(MethodHandleAPI_tryFinally.java:332)
`

**Comment by fengxue-IS** [comment]
> @fengxue-IS There are a couple of tests in the extended build failing after this change due to assertions on:
> `com.ibm.j9.jsr292.api.MethodHandleAPI_tryFinally.test_tryFinally_TryCharMethod_CharReturnType_Throwable(MethodHandleAPI_tryFinally.java:332)`

Looking into the test code

**Comment by fengxue-IS** [comment]
The extended test failure is due to invocation casting exception in `MethodHandles.tryFinally()`, when the `tryHandle` failed with a throwable, we pass a zero value into the `finallyHandle` as result from the `tryHandle` which used `(byte)0` as the default value, and auto-boxed to `Byte.class`

@DanHeidinga can you take another look please?

**Comment by DanHeidinga** [comment]
Jenkins test extended xlinux jdk11

**Comment by DanHeidinga** [comment]
Jenkins test sanity xlinux jdk11

**Pull request merged**
