### PR TITLE
Add wrtbar for UnsafeFastPath static field writes

### PR DESCRIPTION
**Pull request by cathyzhyi**
In generational GC mode, wrtbar is needed for writes to static object fields.

Fixes: #8838 

Signed-off-by: Yi Zhang <yizhang@ca.ibm.com>

### CODE REVIEW

**Comment by cathyzhyi** [comment]
@liqunl could you review the change?

**Comment by liqunl** [comment]
LGTM

**Comment by cathyzhyi** [comment]
@andrewcraik Hey Andrew, could you do a final review?

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk14

**Comment by andrewcraik** [comment]
The two failures are not new and everything else is clean so I'm merging this - @cathyzhyi can you open a PR against the 0.21 release branch?

**Pull request merged**
