### PR TITLE
Exclude TestJcmd on zos

### PR DESCRIPTION
**Pull request by llxia**
[ci skip]

Issue: runtimes/backlog/issues/291

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Grinder_zos/17

**Comment by pshipton** [comment]
I added a comment to runtimes/backlog/issues/291, I wonder if this will be fixed by a zos change that just got merged today.

**Comment by llxia** [comment]
Keep the PR in draft for now. We will monitor the build for the next couple of days to check if this is fixed.

**Comment by llxia** [comment]
It looks like the hanging issue is fixed. Close this PR.

**Pull request closed without merging**
