### PR TITLE
Enable testDDRExt_Callsites test

### PR DESCRIPTION
**Pull request by renfeiw**
- Add playlist entires for openj9 and ibm

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by llxia** [comment]
jenkins test sanity win,xlinux jdk11

**Comment by llxia** [comment]
jenkins test extended zlinux,xlinux jdk11

**Comment by llxia** [comment]
jenkins test sanity win,xlinux jdk8

**Pull request merged**
