### PR TITLE
Use OMR Compiler's renamed ExternalRelocation APIs

### PR DESCRIPTION
**Pull request by ymanton**
This patch primarily changes calls to addAOTRelocation() to addExternalRelocation() as the former will be removed and the latter better reflects that ExternalRelocations are not necessarily AOT-specific. No functionality has changed.

### CODE REVIEW

**Comment by ymanton** [comment]
Jenkins test sanity

**Comment by fjeremic** [comment]
@ymanton there are some copyright checks. Can you please fix but don't push the change. We can wait until the builds complete and merge once you push the fixes in to avoid rerunning the tests.

**Comment by fjeremic** [comment]
Windows failures due to #2129. @ymanton I'm happy to merge the change. Could you fix the copyright and let me know when that is done. I'll merge assuming no semantic code modifications are made.

**Comment by ymanton** [comment]
Done.

**Pull request merged**
