### PR TITLE
Fixup module-info.java.extra files

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
Fixes https://github.com/eclipse/openj9/issues/2587

**Comment by andrew-m-leonard** [comment]
jenkins compile all

**Comment by andrew-m-leonard** [comment]
Jenkins test sanity all jdk11

**Comment by andrew-m-leonard** [comment]
Jenkins test sanity all jdk8

**Comment by andrew-m-leonard** [comment]
jenkins compile jdk11

**Comment by andrew-m-leonard** [comment]
@keithc-ca Hi Keith, I can't seem to get ci builds to run for this... can you?

**Comment by keithc-ca** [comment]
I built JDK 8-12 on a local system before merging.

**Comment by keithc-ca** [comment]
I'm testing a fix to `ModuleInfoMerger.java` together with these changes.

**Pull request merged**
