### PR TITLE
Expand j9vmemtest on Z/OS

### PR DESCRIPTION
**Pull request by AlenBadel**
Expanding the current tests to add cases where `J9PORT_VMEM_PAGE_FLAG_PREFER_PAGEABLE` may be used.

Signed-off-by: AlenBadel <Alen.Badel@ibm.com>

### CODE REVIEW

**Comment by AlenBadel** [comment]
FYI @gita-omr @babsingh @dmitripivkine

**Comment by gita-omr** [comment]
The change seems to be matching the design in https://github.com/eclipse/openj9/issues/8671#issue-571666508.

**Comment by gita-omr** [comment]
Somehow could not assign @babsingh as a reviewer but could you please review?

**Comment by pshipton** [comment]
Only committers can be assigned as reviewers or as Assignees. After a non-committer adds a comment to a PR, they can be added as Assignee, not sure if they can be assigned a review. They can however approve a review.

**Comment by fjeremic** [comment]
What is the difference between this PR and eclipse/omr#4918? Seems to be a lot of duplication here.

**Comment by AlenBadel** [comment]
> What is the difference between this PR and [eclipse/omr#4918](https://github.com/eclipse/omr/pull/4918)? Seems to be a lot of duplication here.

There's always been duplication in omrvmemtest/j9vmemtest. 
Unless there exists a good reason, I don't see why j9vmemtest is needed. Internal sanity currently uses pltest, but that can be removed since omrporttest is also used during omr sanity testing.

**Comment by pshipton** [comment]
> Unless there exists a good reason, I don't see why j9vmemtest is needed. Internal sanity currently uses pltest, but that can be removed since omrporttest is also used during omr sanity testing.

@smlambert any thoughts on this?

**Comment by DanHeidinga** [comment]
> Internal sanity currently uses pltest, but that can be removed since omrporttest is also used during omr sanity testing.

The phrase "Internal sanity currently ..." is concerning.  This project cannot depend on IBM's internal testing.

**Comment by AlenBadel** [comment]
> > Internal sanity currently uses pltest, but that can be removed since omrporttest is also used during omr sanity testing.
> 
> The phrase "Internal sanity currently ..." is concerning. This project cannot depend on IBM's internal testing.

Agreed. It's not a justification, just curious on what the rationale was.

**Comment by pshipton** [comment]
OpenJ9 pltest runs in the sanity.functional suite.

**Comment by babsingh** [comment]
it may require effort: `pltest` can directly use the OMR test code instead of duplicating code, in the future.

**Comment by AlenBadel** [comment]
> it may require effort: `pltest` can directly use the OMR test code instead of duplicating code, in the future. OR OpenJ9 sanity.functional can run OMR tests in their builds, which will allow us to remove the duplicate `pltest` code.

@pshipton 
@babsingh 

I suggest that we create an issue to investigate removing the redundant parts of `pltest`, and if it's completely redundant then replacing it with `omrporttest`. I also suggest that these test cases be added to OMR, and not OpenJ9.

**Comment by pshipton** [comment]
> I suggest that we create an issue to investigate removing the redundant parts of pltest, and if it's completely redundant then replacing it with omrporttest. I also suggest that these test cases be added to OMR, and not OpenJ9.

yes, this makes sense. I'm not sure why we have "duplicate" tests.

**Comment by smlambert** [comment]
In reply to https://github.com/eclipse/openj9/pull/8791#issuecomment-597232770 and the befuddling question of why there are duplicate tests, short answer is dev team would not delete them.  Long answer, one has to go back in history, to when a bunch of test material was prepped and pushed into the omr project, including pltest -> porttest.  

At that time, it was suggested that the internal pltest be removed, but for each of the attempts to remove it there was something blocking their full removal (see Sept 2015 RTC 100752 work item for details), but the last note was citing the fact that there was not full spec coverage in OMR, so the dev team decided these tests could not be removed from the jvm component.  

I am glad that the request to remove the duplicate tests may finally happen.

**Comment by DanHeidinga** [comment]
I'm onboard with deleting duplicate tests provided that we're still running a copy of them in the OpenJ9 build.  I don't want to rely on the test having run at OMR as it may run on different machine configurations, with different compilers, etc.

**Comment by AlenBadel** [comment]
I've went ahead and created the issue to have these portests removed on OpenJ9. 
https://github.com/eclipse/openj9/issues/8876

I'll be closing this PR, and these changes will go into OMR instead.

**Pull request closed without merging**
