### PR TITLE
Removed macros related to multitenancy in PicBuilder

### PR DESCRIPTION
**Pull request by mw918**
Resolves issue #9034 raised by @0xdaryl

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Please sign off your commit.  Not sure why the ECA check didn't run automatically and warn you.

The code looks ok though.

**Comment by 0xdaryl** [comment]
Jenkins compile plinux,aix jdk11

**Comment by 0xdaryl** [comment]
Please see Power CI failures.

**Comment by mw918** [comment]
Jenkins compile plinux,aix jdk11

**Comment by 0xdaryl** [comment]
Jenkins compile plinux,aix jdk11

**Comment by 0xdaryl** [comment]
Jenkins compile plinux,aix jdk11

**Pull request merged**
