### PR TITLE
Use TraceException rather than TraceEvent for failure conditions

### PR DESCRIPTION
**Pull request by pshipton**
Updated tracepoints for startJavaThread()

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Seems reasonable.  I've been hunting for the description of allowed trace point changes but can't find it.  Have you confirmed this doesn't change the tracepoint id in any way?

**Comment by DanHeidinga** [comment]
Jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
> Have you confirmed this doesn't change the tracepoint id in any way?

It doesn't, but I will confirm this when the running build completes. We can look at the id in the J9TraceFormat.dat and compare to a previous build.

**Comment by pshipton** [comment]
New tracepoints have the same ids.
```
j9vm.202 0 1 1 N Trc_VM_startJavaThread_failedToCreateOSThreadOBSOLETE "  startJavaThread omrthread_create failed (retVal=%d)"
j9vm.203 1 1 1 N Trc_VM_startJavaThread_failedVMThreadAlloc "* startJavaThread vm thread alloc failed"
j9vm.204 1 1 1 N Trc_VM_startJavaThread_failedOOMAlloc "* startJavaThread OOM error alloc failed"
j9vm.205 1 1 1 N Trc_VM_startJavaThread_failedLockAlloc "* startJavaThread lock obj alloc failed"
```

**Pull request merged**
