### PR TITLE
Eliminate VM_getClassNameSignatureFromMethod message

### PR DESCRIPTION
**Pull request by dmitry-ten**
Rewrite `TR_J9ServerVM::sampleSignature` to access
class/name/signature from a ROM class, instead of
making a remote call every time. Since ROM classes
are persistently cached this reduces the number of total
messages and eliminates the need for specialized message.

### CODE REVIEW

**Comment by dmitry-ten** [comment]
@mpirvu fyi. This should be reviewed after #11280 is merged.

**Comment by dmitry-ten** [comment]
@mpirvu ready for review now.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit jdk11

**Comment by mpirvu** [comment]
Test passed, hence merging.

**Pull request merged**
