### PR TITLE
Modify codegens to call addDependency from CodeGeneratorUtils

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Modify Power codegen to call addDependency from CodeGeneratorUtils
* Modify ARM codegen to call addDependency from CodeGeneratorUtils

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins test sanity plinux,aix jdk11

**Comment by 0xdaryl** [comment]
Jenkins test sanity plinux,aix jdk11

Power and ARM changes only.  A Power Jenkins build is all that's required.

**Comment by 0xdaryl** [comment]
@ymanton, would you mind reviewing and merging please?

**Comment by ymanton** [comment]
AIX failure looks spurious, build and tests completed successfully but Jenkins threw an exception for whatever reason. Merging.

**Pull request merged**
