### PR TITLE
Eliminate all traces of `gen` directory used by protobuf

### PR DESCRIPTION
**Pull request by mpirvu**
Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
jenkins compile xlinuxcm java8

**Comment by mpirvu** [comment]
jenkins compile xlinuxcm jdk8

**Comment by pshipton** [comment]
Travis failed for some reason, try a PR build instead.

jenkins compile xlinuxcm jdk11

**Comment by ymanton** [comment]
Both CMake builds passed, merging.

**Pull request merged**
