### PR TITLE
Add EXTRA_OPTIONS for jck tests

### PR DESCRIPTION
**Pull request by llxia**
Issue: runtimes/backlog/issues/167

[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
jenkins test sanity plinux jdk8,jdk11

**Comment by llxia** [comment]
jenkins test sanity plinux jdk8,jdk11

**Comment by llxia** [comment]
jenkins test sanity plinux jdk8,jdk11

**Comment by llxia** [comment]
jenkins test sanity plinux jdk8,jdk11

**Comment by llxia** [comment]
Reviewers: @jdekonin @smlambert 
fyi @JasonFengJ9

**Comment by JasonFengJ9** [comment]
Existing `jck` script already adds `-Xfuture`, does this change override that?
It probably is not harmful to have two `-Xfuture` though.

**Comment by llxia** [comment]
> Existing `jck` script already adds `-Xfuture`, does this change override that?
> It probably is not harmful to have two `-Xfuture` though.

The plan is to set `EXTRA_OPTIONS ` value at test job triggering time (upstream job), not in the test job template. Since the test job template is a general template and for all sites to use, I will remove `-Xfuture` in the test job template after this PR.

For the time being, `EXTRA_OPTIONS ` set in this PR will override the default value in the test job template.

**Comment by llxia** [comment]
> I don't understand why we would want to add option specific to testing into the jobs that launch them. Why can this be added at the test level?

Openj9 upstream job generates test jobs and triggers test jobs. I do not think we should hardcode the `EXTRA_OPTIONS` in any generic Jenkins script.

**Comment by smlambert** [comment]
This belongs here in the parent job.  

To aid your understanding, some of the reasons are: 
1) This is an OpenJ9 specific request
2) Its done in a generic way so that if there are more openJ9 specific requests they can be easily handled
3) Reduces the amount of code changes required to put it at the top level

Unless there is a compelling reason not to make this change here, I will proceed to merge this today.

**Pull request merged**
