### PR TITLE
Configure z/TPF to disable Guarded Storage

### PR DESCRIPTION
**Pull request by jjohnst-us**
z/TPF does not currently support guarded storage.
This Pull Requests disables the support for guarded
storage using z/TPF guard macros.

Signed-off-by: James D Johnston <jjohnst@us.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk10 depends eclipse/omr#2796

**Comment by pshipton** [comment]
jenkins test sanity zlinux depends eclipse/omr#2796

**Comment by AdamBrousseau** [comment]
jenkins test sanity zlinux jdk10 depends eclipse/omr#2796

**Comment by AdamBrousseau** [comment]
jenkins test sanity zlinux jdk10 depends eclipse/omr#2796

**Comment by DanHeidinga** [comment]
Merging as PR testing has already been run

**Pull request merged**
