### PR TITLE
Enable SVM during startup

### PR DESCRIPTION
**Pull request by dsouzai**
Fixes https://github.com/eclipse/openj9/issues/4138
Fixes https://github.com/eclipse/openj9/issues/4201

### CODE REVIEW

**Comment by dsouzai** [comment]
jenkins test sanity all jdk8,jdk11

**Comment by dsouzai** [comment]
I verified that enabling the SVM during startup does not result in a startup regression, thanks to all of @jdmpapin 's excellent work in https://github.com/eclipse/openj9/issues/3752

**Comment by dsouzai** [comment]
@mpirvu for your review.

**Comment by mpirvu** [comment]
There is one failure in Java11 LinuxAMD64
```
18:51:23         FAILED: testAnonClassCodePaths
18:51:23         java.lang.NullPointerException
18:51:23         	at java.base/java.lang.Integer.valueOf(Integer.java:1049)
```
Is there any chance the failure is due to SVM being enabled during startup?

**Comment by dsouzai** [comment]
No, doesn't look like it. The test was run with
```
JVM_OPTIONS: -Xnocompressedrefs -Xjit -Xgcpolicy:gencon -Xnocompressedrefs 
```
so there was no AOT code.

**Pull request merged**
