### PR TITLE
Skip bound checks for HashMap.getNode and HashIterator.<init> 

### PR DESCRIPTION
**Pull request by yanluo7**
- Both `HashMap.getNode` and `HashIterator.<init>` are used frequently by various Java applications. In both methods, when accessing the element of the underlying array using `table[x]`, the array index value `x` is already pre-checked to ensure it is `>=0 and <table.length`, therefore no array bound check is required.

Signed-off-by: Yan Luo <Yan_Luo@ca.ibm.com>

### CODE REVIEW

**Comment by cathyzhyi** [comment]
LGTM

**Comment by yanluo7** [comment]
Could this be merged soon?

**Comment by cathyzhyi** [comment]
@vijaysun-omr Hey Vijay, could you help to merge this one? thanks!

**Comment by vijaysun-omr** [comment]
The change looks okay to me. @yanluo7 and @cathyzhyi has this been tested thoroughly ?

**Comment by yanluo7** [comment]
@vijaysun-omr We've done personal build with the change, along with a slew of standard server benchmarks.

**Comment by andrewcraik** [comment]
Travis build failed - might be resolved with a rebase? That way we could run sanity to check the change here as well.

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by andrewcraik** [comment]
390 failures are unrelated

**Comment by yanluo7** [comment]
The travis build failure on Z doesn't seem to be related to this change -- the compilation failure happened in methods (e.g. `JITHelpers.getCharFromArrayByIndex`) that don't call any HashMap methods.

**Comment by andrewcraik** [comment]
LGTM

**Pull request merged**
