### PR TITLE
Ability to set test param KEEP_REPORTDIR per target

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Use variable file to set KEEP_REPORTDIR per test target.
- Set false by default.
- Set true for all openjdk targets

Related #7780 #8434
Depends #8421
[skip ci]

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins test sanity.functional,sanity.openjdk plinux jdk11

**Comment by AdamBrousseau** [comment]
Jenkins test sanity.functional,sanity.openjdk plinux jdk11

**Comment by AdamBrousseau** [comment]
Jenkins test sanity.functional,sanity.openjdk plinux jdk11

**Comment by AdamBrousseau** [comment]
@vsebe for review
```
11:32:22  TEST_KEEP_REPORTDIR:'[sanity.functional:false, sanity.openjdk:true]'
```

**Comment by pshipton** [comment]
@AdamBrousseau pls fix the merge conflicts

**Comment by AdamBrousseau** [comment]
Resolved

**Comment by pshipton** [comment]
jenkins test extended.system,sanity.openjdk zlinux jdk8

**Comment by pshipton** [comment]
@AdamBrousseau the extended.system run still deployed an artifact
```
10:46:47  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_extended.system_s390x_linux_Personal/5/system_test_output.tar.gz
```
https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk8_j9_extended.system_s390x_linux_Personal/5/

**Comment by pshipton** [comment]
It is quite small, 175 bytes, perhaps this is expected behavior. @llxia ?

I'll try a sanity.functional as well to double check.

jenkins test sanity zlinux jdk8

**Comment by AdamBrousseau** [comment]
Yes I believe this is expected. When it is set to true, all the folders are kept and the artifacts are larger. This is required in order for the JUnit plugin to calculate the correct number of tests run (used by the openjdk suite only). When it is false there is much less kept or possibly only the failed ones. Lan would know better.

**Comment by llxia** [comment]
> the extended.system run still deployed an artifact
> It is quite small, 745 bytes, perhaps this is expected behavior. @llxia ?

If a build passes, it should only deploy `SHA.txt`, nothing else. But the build deployed both `SHA.txt` and `system_test_output.tar.gz`. The behavior is not expected. 

However, this behavior is not related to this PR. I will look into this.

**Pull request merged**
