### PR TITLE
Rename MasterGCThread files to MainGCThread in omr

### PR DESCRIPTION
**Pull request by theresa-m**
Merge to be coordinated with: https://github.com/eclipse/omr/pull/5384
Related to: https://github.com/eclipse/openj9/issues/10071

I'm starting with renaming files since this is a refactor, name replacements for master will come in a later pr to make it easier to review.

Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Are there going to be many of these coordinated changes? It takes some manual effort to run a special OMR acceptance PR build and coordinate the merging so OpenJ9 doesn't end up in a broken state. Better if there aren't too many, even if there is more to review at once. You can always create multiple commits.

**Comment by pshipton** [comment]
jenkins compile zlinux jdk11 depends eclipse/omr#5384

**Comment by theresa-m** [comment]
Yes I'm planning for one more. I can add those commits here as well.

**Comment by pshipton** [comment]
Two PRs is fine, in particular if they depend on separate OMR changes. I just didn't want a whole series of dependent changes.

**Comment by pshipton** [comment]
jenkins compile win jdk11 depends eclipse/omr#5384

**Comment by pshipton** [comment]
jenkins test sanotu win jdk11 depends eclipse/omr#5384

**Comment by pshipton** [comment]
jenkins test sanity win,zlinux jdk11 depends eclipse/omr#5384

**Pull request merged**
