### PR TITLE
Print cpu feature in Xshareclasses:printStats for Power

### PR DESCRIPTION
**Pull request by harryyu1994**
Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@mpirvu This one is ready for review&merge.

Output looks like this:
```
Current statistics for cache "hi": 

Cache created with:
	-Xnolinenumbers                      = false
	BCI Enabled                          = true
	Restrict Classpaths                  = false
	Feature                              = cr
	Processor Features                   = vsx dfp vec htm

Cache contains only classes with line numbers
```

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity aix,plinux jdk11

**Comment by mpirvu** [comment]
FYI: @gita-omr

**Pull request merged**
