### PR TITLE
Add test to verify JITaaS is started

### PR DESCRIPTION
**Pull request by llxia**
[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Tested in grinder:
```
00:06:44.884 
00:06:44.884 Testing: Test option -verbose to verify JITaaS is started
00:06:44.884 Test start time: 2018/11/16 18:14:28 Coordinated Universal Time
00:06:44.884 Running command: "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/java" -XX:JITaaSClient -Xcompressedrefs  -Xdump -verbose -version
00:06:44.884 Time spent starting: 1 milliseconds
00:06:45.544 Time spent executing: 153 milliseconds
00:06:45.544 Test result: PASSED
```

**Comment by smlambert** [comment]
Not sure why this never got merged in (did I just forget?!), but if its still needed, will need to resolve conflicts

**Comment by mpirvu** [comment]
This is targeting the JITaaS branch which is no longer maintained. I feel that the testing we have currently in place for JITServer is sufficient.

**Comment by llxia** [comment]
I will close this PR.

**Pull request closed without merging**
