### PR TITLE
Update Windows to openssh 1.1.1i

### PR DESCRIPTION
**Pull request by jdekonin**
Closes eclipse/openj9#11407

### CODE REVIEW

**Comment by jdekonin** [comment]
jenkins compile win32,win jdk8,jdk11,jdk15

**Comment by pshipton** [comment]
The builds all succeeded, but the copyright needs to be updated.

**Comment by jdekonin** [comment]
Copyright updated.

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
Pls cherry pick this change for the 0.24 branch as well.

**Pull request merged**
