### PR TITLE
Migrate shrcdbgddrext test to openj9

### PR DESCRIPTION
**Pull request by renfeiw**
[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by llxia** [comment]
jenkins test extended zlinux,plinux jdk8,jdk10

**Comment by llxia** [comment]
cmdLineTester_shrcdbgddrext_1 failure
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK8-linux_390-64_cmprssptrs-OpenJ9/50/tapResults/

**Comment by renfeiw** [comment]
Fixed the failed test case, please run a java 8 build to verify, thanks.

**Comment by llxia** [comment]
jenkins test extended zlinux jdk8

**Comment by llxia** [comment]
jenkins test extended aix,plinux jdk8,jdk10

**Comment by llxia** [comment]
jenkins test extended zlinux jdk8

**Pull request merged**
