### PR TITLE
Remove -verbose flag in playlist.xml

### PR DESCRIPTION
**Pull request by OscarQQ**
[ci skip]

Signed-off-by: Yixin Qian <Yixin.Qian@ibm.com>

### CODE REVIEW

**Comment by OscarQQ** [comment]
internal Grinder/13522

**Comment by llxia** [comment]
In this PR, we removed -verbose flag in cmdlinetests to reduce the console output. If the test fails, the output will be printed.

```
00:08:50.827  Testing: Test 0: Destroy existing shared class cache
00:08:50.827  Test start time: 2021/01/26 23:58:02 Pacific Standard Time
00:08:50.827  Running command: "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java"    -Xshareclasses:name=cdsadaptor_cache,destroy
00:08:50.828  Time spent starting: 43 milliseconds
00:08:50.828  Time spent executing: 62 milliseconds
00:08:50.828  Test result: FAILED
00:08:50.828  Output from test:
00:08:50.828   [ERR] JVMSHRC023E Cache does not exist
00:08:50.828  >> Failure condition was not found: [Output match: has been destroyed]
00:08:50.828  >> Failure condition was not found: [Output match: is destroyed]
00:08:50.828  >> Failure condition was found: [Output match: Cache does not exist]
00:08:50.828  >> Failure condition was not found: [Output match: Unhandled Exception]
00:08:50.828  >> Failure condition was not found: [Output match: Exception:]
00:08:50.828  >> Failure condition was not found: [Output match: corrupt]
00:08:50.828  >> Failure condition was not found: [Output match: Processing dump event]
00:08:50.828  
00:08:50.828  Testing: Test 1-a: Create a shared class cache while using weaving hooks
00:08:50.828  Test start time: 2021/01/26 23:58:02 Pacific Standard Time
00:08:50.828  Running command: "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java"    -Xshareclasses:name=cdsadaptor_cache -cp /home/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/CDSAdaptorTest:/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/lib/org.eclipse.osgi-3.16.100.jar org.openj9.test.cdsadaptortest.CDSAdaptorOrphanTest -frameworkBundleLocation /home/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/CDSAdaptorTest/FrameworkBundles -testBundleLocation /home/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/CDSAdaptorTest/CDSAdaptorOrphanTestBundles
00:08:50.828  Time spent starting: 7 milliseconds
00:08:52.146  Time spent executing: 1423 milliseconds
00:08:52.146  Test result: PASSED
```

FYI @pshipton

**Comment by llxia** [comment]
Jenkins test sanity,extended all jdk8,jdk11

**Comment by pshipton** [comment]
Sometimes I've used the verbose output to help diagnose a problem, but probably not very often, we'll see how goes. Some day we should fix pltest to reduce the output. There is a memory overlap test that puts out way too much.

**Comment by llxia** [comment]
This PR reduced the console output significantly.
||Build|Total Size of all child test jobs output|
|--|--|--|
|Before| https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Personal/119/|  9.4M |
|After| https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Personal/120/|  7.7M |

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
