### PR TITLE
Bringup JDK15

### PR DESCRIPTION
**Pull request by JasonFengJ9**
**Bringup JDK15**

Added `JAVA15 pConfig`;
Added `J2SE_V15` & `BCT_Java15MajorVersionShifted`;
Added implementation of `ExtendedOperatingSystemMXBeanImpl` methods: `getCpuLoad()`, `getTotalMemorySize()`, `getFreeMemorySize()` which were added since `Java 14`;
Added stub classes within package `java/lang/invoke`: `AddressVarHandleGenerator`, `VarHandleMemoryAddressBase`, `VarHandles`;
Added `latest_exclude_15.txt`, `jvmtitests_excludes_15.xml`;
Updated tests accordingly.

Verified `JDK15 -version`:
```
openjdk version "15-internal" 2020-09-15
OpenJDK Runtime Environment (build 15-internal+0-adhoc.fengjcaibmcom.openj9-openjdk-jdk)
Eclipse OpenJ9 VM (build master-76c715d16, JRE 15 Mac OS X amd64-64-Bit Compressed References 20191217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 76c715d16
OMR      - 88f4df72d
JCL      - 48957d40f1 based on jdk-15+1)
``` 

closes: #8103 
fixes: #8143

Reviewer: @pshipton 
FYI: @DanHeidinga 

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile plinux jdknext

**Comment by pshipton** [comment]
I guess these build failures are due to having a JCL which is too old. It means that when this change is merged, it will break jdknext until the latest can be promoted. I'll try running a promotion build with this change. 
```
09:04:42  /home/jenkins/jenkins-agent/workspace/Build_JDKnext_ppc64le_linux_Personal/build/linux-ppc64le-server-release/support/j9jcl_sources/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedOperatingSystemMXBeanImpl.java:171: error: method does not override or implement a method from a supertype
09:04:42  	@Override
09:04:42  	^
09:04:42  /home/jenkins/jenkins-agent/workspace/Build_JDKnext_ppc64le_linux_Personal/build/linux-ppc64le-server-release/support/j9jcl_sources/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedOperatingSystemMXBeanImpl.java:179: error: method does not override or implement a method from a supertype
09:04:42  	@Override
09:04:42  	^
09:04:42  /home/jenkins/jenkins-agent/workspace/Build_JDKnext_ppc64le_linux_Personal/build/linux-ppc64le-server-release/support/j9jcl_sources/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedOperatingSystemMXBeanImpl.java:187: error: method does not override or implement a method from a supertype
09:04:42  	@Override
09:04:42  	^
```

**Comment by pshipton** [comment]
jenkins compile plinux jdk13

**Comment by JasonFengJ9** [comment]
> 9:04:42  /home/jenkins/jenkins-agent/workspace/Build_JDKnext_ppc64le_linux_Personal/build/linux-ppc64le-server-release/support/j9jcl_sources/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedOperatingSystemMXBeanImpl.java:171: error: method does not override or implement a method from a supertype
09:04:42  	@Override

That's correct, it works with `openj9-staging` branch.

**Comment by pshipton** [comment]
It doesn't compile with openj9-staging either.
```
09:23:34  /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_Personal/src/java.base/share/classes/java/lang/invoke/AddressVarHandleGenerator.java:120: error: cannot access VarForm
09:23:34      private final VarForm form;
09:23:34                    ^
09:23:34    bad source file: /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_Personal/build/macosx-x86_64-server-release/support/j9jcl_sources/java.base/share/classes/java/lang/invoke/VarForm.java
09:23:34      file does not contain class java.lang.invoke.VarForm
09:23:34      Please remove or make sure it appears in the correct subdirectory of the sourcepath.
09:23:34  /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_Personal/build/macosx-x86_64-server-release/support/j9jcl_sources/java.base/share/classes/java/lang/String.java:3929: warning: no @param for <R>
09:23:34  	public <R> R transform(Function<? super String, ? extends R> f) {
09:23:34  	             ^
09:23:34  /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_Personal/build/macosx-x86_64-server-release/support/j9jcl_sources/java.base/share/classes/java/lang/Thread.java:491: warning: no description for @exception
09:23:34   * @exception	UnsupportedOperationException
09:23:34     ^
09:23:34  /Users/jenkins/workspace/Build_JDKnext_x86-64_mac_Personal/build/macosx-x86_64-server-release/support/j9jcl_sources/java.base/share/classes/java/lang/invoke/VarHandle.java:1018: warning: no comment
09:23:34  	public static final class VarHandleDesc extends DynamicConstantDesc<VarHandle> implements ConstantDesc {
09:23:34  	                    ^
09:23:34     ... (rest of output omitted)
```

**Comment by pshipton** [comment]
I could try an earlier version of the openj9-staging branch.

**Comment by JasonFengJ9** [comment]
Failed `AddressVarHandleGenerator.java` just was merged before this PR creation.
Am going to try another build.

**Comment by pshipton** [comment]
Confirmed that openjdk-jdk 78a8a59 compiles, also trying 5486034 which would be preferred if it works.

**Comment by pshipton** [comment]
Confirmed 5486034 does not work as per https://github.com/eclipse/openj9/pull/8139#issuecomment-567086275

Something in this list of changes is causing the problem.
https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/78a8a59...5486034

For now I'll proceed to fully test 78a8a59.

**Comment by pshipton** [comment]
Quite a few failures https://ci.eclipse.org/openj9/job/Test_openjdkNext_j9_sanity.functional_ppc64le_linux_Personal/7
- some are related to the addition of new OperatingSystemMXBean APIs. 
- some are related to missing exclude files for jdk15.
- I notice this
```
Exception in thread "main" java/lang/Error: JVM can't set custom SecurityManager due to java.lang.NoSuchMethodException: org.openj9.test.java.lang.Test_System$TestSecurityManagerNonPublicConstructor.<init>()
	at java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:232)
	at java/lang/Thread.initialize (java.base@9/Thread.java:430)
	at java/lang/Thread.<init> (java.base@9/Thread.java:155)
```
- not sure what is causing this
```
FAILED: test_loadMessages_EN
java.lang.AssertionError: Expected 'Error message 1: 1', found K0001
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59) from jdk.internal.loader.ClassLoaders$AppClassLoader@cd9f9c81(file:/home/jenkins/workspace/Test_openjdkNext_j9_sanity.functional_ppc64le_linux_Personal/openjdk-tests/TKG/lib/testng.jar)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24) from jdk.internal.loader.ClassLoaders$AppClassLoader@cd9f9c81(file:/home/jenkins/workspace/Test_openjdkNext_j9_sanity.functional_ppc64le_linux_Personal/openjdk-tests/TKG/lib/testng.jar)
	at org.openj9.test.vm.Test_MsgHelp.test_loadMessages_EN(Test_MsgHelp.java:57) from jdk.internal.loader.ClassLoaders$AppClassLoader@cd9f9c81(file:/home/jenkins/workspace/Test_openjdkNext_j9_sanity.functional_ppc64le_linux_Personal/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

**Comment by pshipton** [comment]
@JasonFengJ9 I could accept the jdk15 changes if they were seperate, but I can't accept the ExtendedOperatingSystemMXBeanImpl changes until all the test problems are resolved as well.

**Comment by JasonFengJ9** [comment]
`ExtendedOperatingSystemMXBeanImpl` change is required for JDK15 compilation though.

**Comment by pshipton** [comment]
> ExtendedOperatingSystemMXBeanImpl change is required for JDK15 compilation though.

Understood, but it breaks the code in openjdk-jdk openj9 branch, while the other changes do not. The changes don't need to be separated, they can be delivered together once all the test problems are fixed. I was offering to merge the subset of changes in case it made something easier for you.

**Comment by JasonFengJ9** [comment]
>Exception in thread "main" java/lang/Error: JVM can't set custom SecurityManager due to java.lang.NoSuchMethodException: org.openj9.test.java.lang.Test_System$TestSecurityManagerNonPublicConstructor.<init>()
	at java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:232)
	at java/lang/Thread.initialize (java.base@9/Thread.java:430)
	at java/lang/Thread.<init> (java.base@9/Thread.java:155) 

This is the expected output (also appears in those green builds such as https://ci.eclipse.org/openj9/job/Test_openjdkNext_j9_sanity.functional_ppc64le_linux_Personal/6/consoleFull)
https://github.com/eclipse/openj9/blob/f1717341ff71052cd79e78b85a4d7ab097d4fa84/test/functional/Java8andUp/src_110_up/org/openj9/test/java/lang/Test_System.java#L377-L405

**Comment by pshipton** [comment]
Note there are extended test failures as well. See the entire build at https://ci.eclipse.org/openj9/job/Pipeline-Release-Build/127/

**Comment by JasonFengJ9** [comment]
Updated the PR, it passes `sanity.functional` in an internal build. The `Unsupported class file major version 59` failure in `extended.functional` is because `ASM 7.2` hasn't support `Java 15` yet.
I am leaning to build one asm jar with additional `org/objectweb/asm/Opcodes.V15` before an official build is available.

@pshipton please review.

**Comment by pshipton** [comment]
PR build https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/131

**Comment by pshipton** [comment]
There is still a failure related to asm. I expect we need to exclude this test temporarily.

https://ci.eclipse.org/openj9/job/Test_openjdkNext_j9_extended.functional_ppc64le_linux_Personal/4
cmdLineTester_lockWordAlignment_Object_i_0
```
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 59
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
```

**Comment by JasonFengJ9** [comment]
> There is still a failure related to asm. 

Switched the usage of `org.objectweb.asm` from pre-build ASM jar to JDK build-in `jdk.internal.org.objectweb.asm` which supports `Opcodes.V15`.
Verified in an internal build that this works for `Java 8/11/15`.

@pshipton please have another look.

**Comment by pshipton** [comment]
JDKnext staging build passed https://ci.eclipse.org/openj9/job/Pipeline-Release-Build/140/

**Comment by pshipton** [comment]
jenkins test sanity,extended plinux,win jdk8,jdk11

**Pull request merged**
