### PR TITLE
Rename master/slave for omr dependent files

### PR DESCRIPTION
**Pull request by theresa-m**
OMR dependent: https://github.com/eclipse/omr/pull/5398

Related to: https://github.com/eclipse/openj9/issues/10071

There are more replacements but I've tried to make this pr "smaller" by including mostly dependent omr changes.

Everything is a direct replacement slave->worker and master->main.

Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
The copyrights need to be updated.

**Comment by theresa-m** [comment]
Updated copyrights and opened dependent OMR pr.

**Comment by SueChaplain** [comment]
@theresa-m - we believe that this work will result in a change needed at the user docs where system output shows `GC master/slave`. See https://www.eclipse.org/openj9/docs/tool_jdmpview/#example.

Please can you open a doc issue so that we don't forget to do this when the work is complete?

**Comment by theresa-m** [comment]
> @theresa-m - we believe that this work will result in a change needed at the user docs where system output shows `GC master/slave`. See https://www.eclipse.org/openj9/docs/tool_jdmpview/#example.
> 
> Please can you open a doc issue so that we don't forget to do this when the work is complete?

https://github.com/eclipse/openj9-docs/issues/605
I'll make sure to update when this is merged.

**Comment by theresa-m** [comment]
any takers for review?

**Comment by pshipton** [comment]
jenkins compile aix,xlinux,osx,win jdk8,jdk11 depends eclipse/omr#5398

**Comment by pshipton** [comment]
jenkins test sanity ppc64_aix,x86-64_linux,x86-64_linux_xl,ppc64le_linux,ppc64le_linux_xl,s390x_linux,s390x_linux_xl,x86-64_windows,x86-32_windows,x86-64_mac jdk8,jdk11 depends eclipse/omr#master

**Pull request merged**
