### PR TITLE
Fix JITServer message type mismatch

### PR DESCRIPTION
**Pull request by harryyu1994**
The main cause of the message type mismatches is
due to JITServer/JITClient messages not being 1-to-1. 
In order to make sure that the messages always get 
received by the correct receiver, we must avoid double
 sending of messages.

In this problem, JITClient sends a compilationRequest 
but immediately realized that it needs to abort the 
compilation so it sends another "writeError()" message. 
This double sending from the JITClient has caused both 
JITServer and JITClient not receiving correct messages 
sometimes. We eliminated the double sending and resolved 
the issue by having the JITClient wait for the next message
from JITServer before sending out the "writeError()" message.

Additionally, when JITServer is at the "early translation" 
stage and JITClient issues an interruption, an exception
will be thrown in the next JITServer read. However,
the catch statement did not include handling of
StreamInterrupted and as a result will treat the
interruption as a "compilationFailure" though it
really should have been an interruption. An client-issued
interruption and an actual compilationFailure are
handled differently. For the actual compilationFailure,
JITserver has to tell JITclient about it. But for
an interruption, since it's issued by JITclient,
JITserver should not tell JITclient about it again.

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@mpirvu Hi Marius, this one is ready for review.

**Comment by mpirvu** [comment]
Jenkins test sanity xlinux jdk11

**Comment by harryyu1994** [comment]
This PR is a mirrored PR of https://github.com/eclipse/openj9/pull/7646 from the `jitaas` branch. More details are included there.

I think this PR is ready for merge. Don't know why the "CI" is showing pending here, when you click into it it says "passing".

**Comment by mpirvu** [comment]
Jenkins test sanity all jdk11

**Comment by mpirvu** [comment]
Tests have passed, hence merging.

**Pull request merged**
