### PR TITLE
Update testSCCMLTests6 to check for cache full message.

### LINKED ISSUE #4425: Test-extended.functional-JDK8-linux_ppc-64_cmprssptrs_le testSCCMLTests6_1 cache not full
Looks like a test problem and we are just getting unlucky.

https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-linux_ppc-64_cmprssptrs_le/203
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-linux_ppc-64_cmprssptrs_le/204
```
Testing: Test 200-b: CMVC 197811: Make sure cache created in previous test is full
Test start time: 2019/01/23 09:27:36 Coordinated Universal Time
Running command: "/home/jenkins/jenkins-agent/workspace/Test-extended.functional-JDK8-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/jre/bin/java"  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses:name=ShareClassesCMLTests,printStats
Time spent starting: 1 milliseconds
Time spent executing: 36 milliseconds
Test result: FAILED
 [ERR] 
 [ERR] Current statistics for cache "ShareClassesCMLTests": 
 [ERR] 
 [ERR] Cache created with:
 [ERR] 	-Xnolinenumbers                      = false
 [ERR] 	BCI Enabled                          = true
 [ERR] 	Restrict Classpaths                  = false
 [ERR] 	Feature                              = cr
 [ERR] 
 [ERR] 
 [ERR] base address                         = 0x00003FFF76810000
 [ERR] end address                          = 0x00003FFF76900000
 [ERR] allocation pointer                   = 0x00003FFF76810000
 [ERR] 
 [ERR] cache size                           = 1047968
 [ERR] softmx bytes                         = 1047968
 [ERR] free bytes                           = 4
 [ERR] ROMClass bytes                       = 0
 [ERR] AOT bytes                            = 0
 [ERR] Reserved space for AOT bytes         = -1
 [ERR] Maximum space for AOT bytes          = -1
 [ERR] JIT data bytes                       = 0
 [ERR] Reserved space for JIT data bytes    = -1
 [ERR] Maximum space for JIT data bytes     = -1
 [ERR] Zip cache bytes                      = 916632
 [ERR] Startup hint bytes                   = 0
 [ERR] Data bytes                           = 64928
 [ERR] Metadata bytes                       = 868
 [ERR] Metadata % used                      = 0%
 [ERR] Class debug area size                = 65536
 [ERR] Class debug area used bytes          = 0
 [ERR] Class debug area % used              = 0%
 [ERR] 
 [ERR] # ROMClasses                         = 0
 [ERR] # AOT Methods                        = 0
 [ERR] # Classpaths                         = 0
 [ERR] # URLs                               = 0
 [ERR] # Tokens                             = 0
 [ERR] # Zip caches                         = 4
 [ERR] # Startup hints                      = 0
 [ERR] # Stale classes                      = 0
 [ERR] % Stale classes                      = 0%
 [ERR] 
 [ERR] Cache is 100% full
 [ERR] 
 [ERR] Cache is accessible to current user = true
>> Success condition was not found: [Output match: free bytes[\s]*= 0]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]
>> Failure condition was not found: [Output match: corrupt]
>> Failure condition was not found: [Output match: Processing dump event]
```

### PR DESCRIPTION
**Pull request by hangshao0**
Check for cache full message instead of free bytes on a full cache.

Fixes #4425  

Signed-off-by: hangshao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test extended plinux jdk8

**Comment by pshipton** [comment]
jenkins test extended win jdk8

**Comment by pshipton** [comment]
@hangshao0 the test failed on Windows as the cache is 99% full.

**Comment by hangshao0** [comment]
Updated the test to check for 99% full on Windows and 100% full on non-Windows.

**Comment by pshipton** [comment]
@hangshao0 please cherry pick the commit and create a PR against the v0.12.0-release branch

**Pull request merged**
