### PR TITLE
Fold TR_ S390LinkageConventions into TR_LinkageConventions

### PR DESCRIPTION
**Pull request by dchopra001**
This PR combines the two enums as they serve the same purpose. See https://github.com/eclipse/omr/pull/5732 for related OMR PR.

### CODE REVIEW

**Comment by dchopra001** [comment]
Depends on  eclipse/omr#5732

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8 depends eclipse/omr#5732

**Comment by fjeremic** [comment]
Looks like some weird `curl` failures on x86. This change is Z specific though so I'm not too worried about it. Going to go ahead and merge + promote the branches after the 4:00 p.m. acceptance build promotes.

**Comment by pshipton** [comment]
xlinux curl problems were introduced yesterday afternoon and fixed sometime this morning.

**Comment by fjeremic** [comment]
Still looking for a good time to merge this. There is an OMR-Acceptance triggered 1.5 hours ago. So will be waiting for that.

**Pull request merged**
