### PR TITLE
Replace JAVA_BIN with TEST_JDK_HOME for PR builds

### PR DESCRIPTION
**Pull request by jdekonin**
* AdoptOpenJDK/openjdk-tests#1093
* [skip ci]

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
jenkins test sanity xlinux jdk8

**Comment by jdekonin** [comment]
jenkins test sanity plinux jdk11

**Comment by jdekonin** [comment]
jenkins test sanity xlinux jdk8

**Comment by jdekonin** [comment]
jenkins test sanity xlinux jdk8

**Comment by jdekonin** [comment]
jenkins test sanity xlinux jdk8

**Comment by jdekonin** [comment]
jenkins test sanity xlinux jdk8

**Comment by jdekonin** [comment]
jenkins test sanity plinux jdk11

**Comment by keithc-ca** [comment]
PR builds are still failing; e.g. https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_ppc-64_cmprssptrs_le-OpenJ9/966 :
```
00:35:24.735  + make -f run_configure.mk
00:35:24.735  run_configure.mk:31: *** Please provide TEST_JDK_HOME value..  Stop.
```

**Pull request merged**
