### PR TITLE
Enable OMRChecker linting for openj9

### PR DESCRIPTION
**Pull request by nbhuiyan**
OMRChecker is a clang plugin designed to look for issues in the
implementation of extensible classes. OMRChecker is already
used to lint in the eclipse/OMR Travis CI build process.

Issue: #729
Depends on #1521 , #2749 

Signed-off-by: Nazim Uddin Bhuiyan <nazim.uddin.bhuiyan@ibm.com>

### CODE REVIEW

**Comment by nbhuiyan** [comment]
Looks like OMRChecker detected some errors. I will provide fixes in separate PRs.

**Comment by nbhuiyan** [comment]
@0xdaryl This PR is ready for review.

**Comment by xliang6** [comment]
@AdamBrousseau @0xdaryl @DanHeidinga Can one of you review this PR and provide feedback? If not, can you suggest someone who can? Thanks.

**Comment by nbhuiyan** [comment]
I think it would be good to enable it on Jenkins for other platforms, since this PR would only do the checks for Linux on x86-64-specific implementation issues

**Comment by xliang6** [comment]
Thanks @AdamBrousseau ! 
@0xdaryl Can you merge this when you get a chance?

Currently OMRChecker is only running on x86-64 Linux for Eclipse OMR and we are trying to enable the same checking for OpenJ9 via this PR.

In the long run, I agree that it would be nice to enable this checker for other platforms as well. This checker is a clang plugin, so we have to make sure clang works on those platforms. It currently supports x86-64 Linux, Windows (32 and 64), and macOS. @nbhuiyan Please correct me if I am wrong.

**Comment by nbhuiyan** [comment]
@xliang6 Clang works on the platforms you mentioned, however I never tried running Clang with plugins natively on any platform other than Linux on x86-64. There are a number of dependencies that Clang plugins need to be linked with when building.

**Comment by DanHeidinga** [comment]
@nbhuiyan Can you split this into two PRs?  One to enable the Travis linter and the other with the changes to `runtime/compiler/trj9/runtime/J9CodeCacheManager.cpp`?

The J9CodeCacheManager.cpp changes are potential bugs and shouldn't be hidden a linter PR as the two changes have very different purposes.

**Comment by xliang6** [comment]
FYI, changes to J9CodeCacheManager.cpp should go in first so it doesn't break the Travis linter once it's merged.

**Comment by nbhuiyan** [comment]
Prerequisite:  https://github.com/eclipse/openj9/pull/1521

**Comment by mstoodle** [comment]
@nbhuiyan wow, this one has sat for a while. Can you please rebase and we'll re-run the tests and (hopefully) get it merged?

**Comment by nbhuiyan** [comment]
PR #2749 contains fixes to issues that a recent run of the OMRChecker tool reported.

**Comment by nbhuiyan** [comment]
This is back to working again! Ready for another review. @0xdaryl

**Comment by 0xdaryl** [comment]
Jenkins build sanity

**Comment by 0xdaryl** [comment]
Jenkins test sanity

**Comment by 0xdaryl** [comment]
Windows JDK10 failure appears to be infrastructure (appears after tests all pass).

**Comment by 0xdaryl** [comment]
And the JDK8 failures both appear to be infra as well.  Merging...

**Pull request merged**
