### PR TITLE
Refactor IncrementalGenerationalGC/CopyForward code

### PR DESCRIPTION
**Pull request by bragaigor**
Refactor VLHGC collector code in preparation for concurrent
Copy Forward collector. This is the first step of a series of
steps in order to introduce the low-pause collector that’s
based on the balanced GC policy.

Here we divide pre/post GC processing related to Copy
Forward. We also introduce concurrentCopyForwardCollectionSet
as well as isConcurrentCycleInProgress which will be used
by concurrent copy forward.

Enable concurrent Copy Forward in Linux x86 platforms.

This is phase 1 of #12089

Same PR as #12187 with Windows 32bit fix

Signed-off-by: Igor Braga <higorb1@gmail.com>

### CODE REVIEW

**Comment by bragaigor** [comment]
cc: @amicic . I've been running Windows 32bit builds this morning and the build has passed.

**Comment by amicic** [comment]
Jenkins compile all jdk11

**Comment by amicic** [comment]
Jenkins test sanity win jdk8

**Comment by amicic** [comment]
Jenkins test sanity win jdk8

**Review by amicic — APPROVED** [review]

**Pull request merged**
