### PR TITLE
Avoid load rewrites for cold escapes of immutable discontiguous objects

### PR DESCRIPTION
**Pull request by hzongaro**
Ordinarily Escape Analysis avoids fix-up of fields of stack allocated objects in cold block escapes, but as a special case, fix-up still happens for immutable discontiguous objects, as the initialization of the temporary used to represent a field of such an object might end up in such a cold block.

However, the fix-up for the fields of such an object in a cold block escape was happening for both loads and stores.  That's not usually a problem except if the load refers to the vft-symbol, as no temporary is ever properly initialized to represent the vft-symbol for a discontiguously stack allocated object.

Avoided this situation by only performing the special case fix-up for immutable discontiguously stack allocated objects for store operations.  It's safe to load the field from the heapified object.

Also added a check for the environment variable `TR_disableEAImmutableObjectHandling` to allow special handle of immutable objects by EA to be disabled.

Fixes:  #7584

Signed-off-by:  Henry Zongaro <zongaro@ca.ibm.com>

### CODE REVIEW

**Comment by hzongaro** [comment]
This change appears to fix the problem described in issue #7584.  I have testing in progress, and I will remove the WIP prefix once that completes, but I would appreciate any early review feedback.
@vijaysun-omr @andrewcraik

**Comment by vijaysun-omr** [comment]
Is it possible to run the test for which this fix was done originally ?

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by vijaysun-omr** [comment]
I approve the change but I'd like my question to be answered before merging.

**Comment by hzongaro** [comment]
> Is it possible to run the test for which the fix caused this bug to occur ?

Yes - just digging it up again, and I'll check whether the situation that it was trying to fix still arises. . . .

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by andrewcraik** [comment]
loads of infra fails so re-doing sanity.

**Comment by hzongaro** [comment]
@vijaysun-omr Vijay, I reran four tests that were originally affected by the problem for which I introduced pull request #4282; each passed two 100/100 runs.  I also ran those same tests using a JIT that would trigger a fatal assert anytime it encountered the situation that pull request #4282 was attempting to fix, and one of the four tests did hit the assert 4/100 times.

Earlier in the week, I started a complete test run on all platforms using that same JIT that would abort to try to find another test that encountered the situation that pull request #4282 was trying to fix. I found one additional test that encountered that situation when running on z/OS.  That test also passed with this pull request in 100/100 test runs.

Dropping the "WIP" prefix.

**Comment by vijaysun-omr** [comment]
Thanks @hzongaro. I approve merging this fix.

**Comment by andrewcraik** [comment]
All approved - merging

**Pull request merged**
