### PR TITLE
AArch64: Allow both native build and cross build

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds a new flag for cross build in j9.flags, and new spec
files that use the flag for cross build of AArch64 runtime.

Fixes: #5285

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
Cross builds call `qemu-aarch64` for running `constgen` and `j9ddrgen`.  (DDR is not enabled for AArch64 yet.  See #5221)

The spec files with `_cross` in their names are enabled by https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/149.

**Comment by knn-k** [comment]
I found a problem with cross build with compressed references.  Marking with "WIP:" until resolved.

**Comment by knn-k** [comment]
Updated `configure_linux_aarch64.mk`, and removed the "WIP:" prefix.

**Comment by hangshao0** [comment]
Can you please add the issue number to the commit message ?

**Comment by knn-k** [comment]
Updated the commit message with the issue number.

**Pull request merged**
