### PR TITLE
Check for int overflow in StringBuffer and StringBuilder

### LINKED ISSUE #8403: Crash after creating large objects
This test case crashes consistently on jdk8, at least on Windows.
Happens on the latest, 0.18.1, 0.17.0 and I think older builds as well.
```
public class Test {
	public static void main(String[] args) throws Throwable {
		StringBuffer sb = new StringBuffer(Integer.MAX_VALUE - 8);
		int sz = 16;
		while(true) {
			char[] cbuf = new char[sz];
			try {
				sb.append(cbuf);
			} catch (ArrayIndexOutOfBoundsException e) {
				// just ignore it and keep looping to generate more garbage
			} catch (OutOfMemoryError e) {
				// just ignore it and keep looping
			}
			int newsz = sz << 1;
			if (newsz > 0 && newsz <= (Integer.MAX_VALUE - 8)) sz = newsz;
			else sz = Integer.MAX_VALUE - 8;
			System.out.print('.');
		}
	}
}
```
`java -Xmx10g -Xdump:none Test`

```
...........................Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFFDB9C4E01 ContextFlags=0010005f
Handler1=00007FFFDB9DCAA0 Handler2=00007FFFDC27C910 InaccessibleReadAddress=00000000000001F8
RDI=0000000000000570 RSI=00000006801024F8 RAX=0000000000000000 RBX=00000000034B9A00
RCX=00000000000001F8 RDX=0000000003587150 R8=000000000320F880 R9=0000000000000000
R10=00000007FFC30000 R11=000000000320F388 R12=00000000014243B8 R13=00007FFFDBFE843C
R14=0000000000000000 R15=000000000000001E
RIP=00007FFFDB9C4E01 RSP=000000000320F2D0 RBP=00000007FFC30000 GS=002B
FS=0053 ES=002B DS=002B
XMM0 00000000437536f9 (f: 1131755264.000000, d: 5.591614e-315)
XMM1 0000000047bb8a80 (f: 1203473024.000000, d: 5.945947e-315)
XMM2 000000003f800000 (f: 1065353216.000000, d: 5.263544e-315)
XMM3 3fc7565060000000 (f: 1610612736.000000, d: 1.823216e-001)
XMM4 402d1cb7c6000000 (f: 3321888768.000000, d: 1.455609e+001)
XMM5 bf52f43f6e6b74b9 (f: 1852535936.000000, d: -1.156866e-003)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=C:\sdks\jdk8u242-b08\jre\bin\compressedrefs\j9vm29.dll
Module_base_address=00007FFFDB960000 Offset_in_DLL=0000000000064e01
Target=2_90_20200122_564 (Windows 10 10.0 build 18362)
CPU=amd64 (8 logical CPUs) (0x7f5a13000 RAM)

JavaVMInitArgs.nOptions=15:
    -Xoptionsfile=C:\sdks\jdk8u242-b08\jre\bin\compressedrefs\options.default
    -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple
    -Xjcl:jclse29
    -Dcom.ibm.oti.vm.bootstrap.library.path=C:\sdks\jdk8u242-b08\jre\bin\compressedrefs;C:\sdks\jdk8u242-b08\jre\bin
    -Dsun.boot.library.path=C:\sdks\jdk8u242-b08\jre\bin\compressedrefs;C:\sdks\jdk8u242-b08\jre\bin
    -Djava.library.path=C:\sdks\jdk8u242-b08\jre\bin\compressedrefs;C:\sdks\jdk8u242-b08\jre\bin;C:\WINDOWS\system32;C:\WINDOWS
Generated system dump: C:\sdks\jdk8u242-b08\bin\java.dmp
----------- Stack Backtrace -----------
(0x00007FFFDB9C4E01 [j9vm29+0x64e01])
(0x00007FFFDB9CF3E8 [j9vm29+0x6f3e8])
(0x00007FFFDB9D1456 [j9vm29+0x71456])
(0x00007FFFDB9D9842 [j9vm29+0x79842])
(0x00007FFFDB9D9FBC [j9vm29+0x79fbc])
Java_java_lang_invoke_MutableCallSite_invalidate+0x5d628d (0x0000000055909ADD [j9jit29+0x669add])
Java_java_lang_invoke_MutableCallSite_invalidate+0x5c3858 (0x00000000558F70A8 [j9jit29+0x6570a8])
---------------------------------------
```

### PR DESCRIPTION
**Pull request by pshipton**
Fixes #8403

### CODE REVIEW

**Comment by pshipton** [comment]
@fjeremic I still need to port the changes to StringBuilder, can you please take a look before I do that.

**Comment by pshipton** [comment]
@fjeremic All calls to ensureCapacityImpl() look like the following, which will have to change in order to put the check into ensureCapacityImpl(). I can go either way, let me know which is better for the JIT.
```
			if (newLength > currentCapacity) {
				ensureCapacityImpl(newLength);
			}
```

**Comment by fjeremic** [comment]
It shouldn't matter really. There will be an equivalent amount of code added in both cases. We should likely never run into this path and it will be marked as cold form the JIT side. You can go ahead with the current change.

**Comment by pshipton** [comment]
jenkins test sanity,extended plinux jdk11

**Comment by pshipton** [comment]
@fjeremic I've made some changes to StringBuffer and added the StringBuilder changes.

**Comment by pshipton** [comment]
Arg, tested the wrong version.

jenkins test sanity,extended plinux jdk8

**Comment by pshipton** [comment]
jenkins compile win jdk8

**Pull request merged**
