### PR TITLE
Execute all tests in report dir

### PR DESCRIPTION
**Pull request by renfeiw**
- cd into report dir before each test target
- cd out and remove test result if test passed

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
Reviewer: @llxia

**Comment by llxia** [comment]
Jenkins test all

**Comment by llxia** [comment]
Jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
Jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
Jenkins test all

**Comment by llxia** [comment]
Jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
Jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
Jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
Jenkins test all

**Comment by llxia** [comment]
Jenkins test all xlinux jdk11

**Comment by llxia** [comment]
Jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
Jenkins test extended xlinux jdk11

**Comment by llxia** [comment]
Jenkins test all

**Comment by smlambert** [comment]
Note: this change accomplishes 2 things
1) reducing the amount of space by not keeping test output for tests that pass
2) executes tests inside output folder, which means that any tests that crash and produce a core file will now see the core file included in the test artifact that will be downloadable via Jenkins (Fixes #969)

**Pull request merged**
