### PR TITLE
Remove unnecessary execute permissions from files

### PR DESCRIPTION
**Pull request by keithc-ca**
None of the files in this repo need execute permissions.
Shell and perl scripts are launched as `sh script.sh` and `perl script.pl`, respectively, which doesn't require execute permission.
Source files (`*.c`, `*.h`, `*.java`, etc.) don't need execute permission.

### CODE REVIEW

**Comment by keithc-ca** [comment]
@pshipton What are your thoughts about whether the copyright dates should be updated when the contents have not changed, only the permissions?

**Comment by pshipton** [comment]
The copyright check is failing.

**Comment by pshipton** [comment]
There was this comment.
https://github.com/eclipse/openj9/pull/5722#issuecomment-491355192

@AdamBrousseau will having old copyright dates on files modified in 2019 cause any copyright check problems in other PRs? I know occasionally we see copyright failures in files not being modified by the PR.

**Comment by pshipton** [comment]
@keithc-ca ottawa.csv appears to have modified contents (line endings?). Is this going to cause any problems in downstream builds?

**Comment by keithc-ca** [comment]
The comment in 5722 was in connection with content changes to files. Other than line-end fixes, this doesn't (yet) change any content. I asked Adam about changing the copyright checking script: he thinks it's doable (if we agree that's the right answer).

I don't expect the line-end change to `ottawa.csv` to be problematic.

**Comment by AdamBrousseau** [comment]
>will having old copyright dates on files modified in 2019 cause any copyright check problems in other PRs?

No. We usually hit those when someone has a merge conflict in their PR.

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk8

**Comment by pshipton** [comment]
jenkins compile win jdk8

**Comment by pshipton** [comment]
It seems reasonable to not update copyrights for file permission changes.

**Pull request merged**
