### PR TITLE
Adding gr11 as dependency before calling VMHelper during Field Watch

### PR DESCRIPTION
**Pull request by midronij**
Both the generateFillInDataBlockSequenceForUnresolvedField() and generateReportFieldAccessOutlinedInstructions() functions store their first argument in gr3 and call a VM helper function via a trampoline that uses gr11 to store the callee address. Before implementing this fix, the contents of gr3 were stored to gr11 before the helper function call and loaded back to gr3 after. However, since gr11 was being used by the trampoline, after the helper function call, the wrong data would be loaded back, corrupting gr3 and causing a segmentation fault. In this commit, gr11 has been added as a dependency to ensure that it used only for the callee address (and not to back up gr3), and that gr3 is not corrupted.

### CODE REVIEW

**Comment by midronij** [comment]
@gita-omr @AlenBadel

**Comment by gita-omr** [comment]
@AlenBadel could you review the change?

**Comment by AlenBadel** [comment]
I think the title of the commit can be a little more representative of the actual change. I would suggest something like "Adding gr11 as dependency before calling VMHelper during Field Watch". 

Other than that it LGTM.

**Comment by gita-omr** [comment]
Good point. @midronij could you please rename the PR and I will merge? Thanks for the fix!

**Comment by midronij** [comment]
@gita-omr Done! I made the commit message/PR description more descriptive too.

**Comment by gita-omr** [comment]
Jenkins test sanity aix,plinux jdk8,jdk11

**Pull request merged**
