### PR TITLE
Explicitly include required header files

### PR DESCRIPTION
**Pull request by 0xdaryl**
Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Required for upstream code changes.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk15

**Comment by andrewcraik** [comment]
Jenkins test sanity plinux,plinuxxl,xlinux,xlinuxxl,osx jdk15

**Review by andrewcraik — APPROVED** [review]

**Pull request merged**
