### PR TITLE
Mirror new changes in JIT to JITServer

### PR DESCRIPTION
**Pull request by harryyu1994**
Reflect new changes from JIT in JITServer.
Original JIT change can be found here
https://github.com/eclipse/openj9/pull/6305

Issue: #7674

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@mpirvu Hi Marius, could you please help review this one?

**Comment by mpirvu** [comment]
Jenkins test sanity xlinuxjit jdk8

**Comment by mpirvu** [comment]
Again errors in `cmdLineTester_gcsuballoctests_0`
```
---SUMMARY OF FAILED TESTS---
-Xgc:suballocatorCommitSize=300m
-Xgc:suballocatorCommitSize=512m Xgc:suballocatorInitialSize=256m
-Xmcrs4294967040
```
```
Output from test:
 [ERR] JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate compressed references metadata.  4G requested
 [ERR] ** ASSERTION FAILED ** omrport.359 at ../../omr/port/common/omrmemtag.c:145 Trc_Assert_PRT_memory_corruption_detected((memoryCorruptionDetected))
 [ERR] *** Error in `/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/bin/java': free(): invalid size: 0x00007f565733bd90 ***
 [ERR] ======= Backtrace: =========
 [ERR] /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f565e2ef7e5]
 [ERR] /lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f565e2f837a]
 [ERR] /lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f565e2fc53c]
 [ERR] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9prt29.so(+0x4dbc6)[0x7f565c739bc6]
 [ERR] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9gc29.so(+0x126f1a)[0x7f5655fb9f1a]
 [ERR] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9gc29.so(+0x126d32)[0x7f5655fb9d32]
 [ERR] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9gc29.so(+0x4aed3)[0x7f5655edded3]
 [ERR] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9gc29.so(J9VMDllMain+0xac)[0x7f5655eba76c]
 [ERR] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9vm29.so(+0xab8bb)[0x7f565ce338bb]
 [ERR] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9vm29.so(+0xac567)[0x7f565ce34567]
 [ERR] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9vm29.so(+0xacc7f)[0x7f565ce34c7f]
 [ERR] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9vm29.so(J9_CreateJavaVM+0x75)[0x7f565ce2bd55]
 [ERR] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libjvm.so(JNI_CreateJavaVM+0x7f9)[0x7f565d32d199]
 [ERR] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/jre/lib/amd64/j9vm/libjvm.so(JNI_CreateJavaVM+0xa52)[0x7f565e06da32]
 [ERR] /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/bin/../lib/amd64/jli/libjli.so(+0x7f44)[0x7f565e84df44]
 [ERR] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f565ea656ba]
 [ERR] /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f565e37f41d]
```

**Comment by mpirvu** [comment]
Jenkins test sanity xlinux jdk8

**Comment by mpirvu** [comment]
The gc error would come from
```
jint
gcInitializeDefaults(J9JavaVM* vm)
{
...
	memoryParameterTable = (IDATA *)j9mem_allocate_memory(tableSize, OMRMEM_CATEGORY_MM);
	if (!memoryParameterTable) {
		loadInfo->fatalErrorStr = (char *)j9nls_lookup_message(J9NLS_DO_NOT_PRINT_MESSAGE_TAG | J9NLS_DO_NOT_APPEND_NEWLINE, J9NLS_GC_FAILED_TO_INITIALIZE_OUT_OF_MEMORY, "Failed to initialize, out of memory.");
		goto error;
	}
	memset(memoryParameterTable, -1, tableSize);
...
		/* Verify all memory parameters */
		if (JNI_OK != gcInitializeVerification(vm, memoryParameterTable, flatConfiguration)) {
			loadInfo->fatalErrorStr = (char *)j9nls_lookup_message(J9NLS_DO_NOT_PRINT_MESSAGE_TAG | J9NLS_DO_NOT_APPEND_NEWLINE, J9NLS_GC_FAILED_TO_INITIALIZE, "Failed to initialize.");
			goto error;
		}
...
error:
	if (memoryParameterTable) {
		j9mem_free_memory(memoryParameterTable);
	}
	return J9VMDLLMAIN_FAILED;
```
If this is the place were the error comes from, then this is done in stage 2
```
		case ALL_LIBRARIES_LOADED:
			/* Note: this must happen now, otherwise -verbose:sizes will not work, as verbose 
			 * support is initialized during this stage.
			 */
			rc = gcInitializeDefaults(vm);
			break;
```
which is very early. The JIT will start to do something in stage 11.

**Comment by mpirvu** [comment]
The non-jitserver build failed due to an unrelated issue:
```
15:41:57  com.ibm.j9tools.om.InvalidFactoryException: Error(s)encountered while initializing the object factory.:
15:41:57   - Error(s) encountered in the specification. "linux_riscv64_cmprssptrs_cross":
15:41:57      - Flag: build_product requires build_autobuild to be enabled.
15:41:57   - Error(s) encountered in the specification. "linux_riscv64_cross":
15:41:57      - Flag: build_product requires build_autobuild to be enabled.
15:41:57   - Error(s) encountered in the specification. "linux_riscv64_cmprssptrs":
15:41:57      - Flag: build_product requires build_autobuild to be enabled.
15:41:57   - Error(s) encountered in the specification. "linux_riscv64":
15:41:57      - Flag: build_product requires build_autobuild to be enabled.
15:41:57  
15:41:57  Exception in thread "main" com.ibm.j9tools.om.InvalidFactoryException: Error(s)encountered while initializing the object factory.:
15:41:57   - Error(s) encountered in the specification. "linux_riscv64":
15:41:57      - Flag: build_product requires build_autobuild to be enabled.
15:41:57   - Error(s) encountered in the specification. "linux_riscv64_cmprssptrs":
15:41:57      - Flag: build_product requires build_autobuild to be enabled.
15:41:57   - Error(s) encountered in the specification. "linux_riscv64_cmprssptrs_cross":
15:41:57      - Flag: build_product requires build_autobuild to be enabled.
15:41:57   - Error(s) encountered in the specification. "linux_riscv64_cross":
15:41:57      - Flag: build_product requires build_autobuild to be enabled.
15:41:57  
15:41:57  	at com.ibm.j9tools.om.ObjectFactory.initialize(ObjectFactory.java:788)
15:41:57  	at com.ibm.j9tools.om.ObjectFactory.initialize(ObjectFactory.java:800)
15:41:57  	at com.ibm.oti.VMCPTool.UmaFlagInfo.<init>(UmaFlagInfo.java:41)
15:41:57  	at com.ibm.oti.VMCPTool.Main.main(Main.java:276)
15:41:57  buildtools.mk:236: recipe for target 'uma' failed
15:41:57  gmake[2]: *** [uma] Error 255
15:41:57  gmake[2]: *** Waiting for unfinished jobs....
15:41:57  buildtools.mk:248: recipe for target 'constantpool' failed
15:41:57  gmake[2]: *** [constantpool] Error 1
```

**Comment by mpirvu** [comment]
The code in this commit is enterely surrounded by `#ifdef JITSERVER_SUPPORT` so it cannot affect the non-jitserver builds.
With jitserver testing Java8 everything was fine except the `cmdLineTester_gcsuballoctests_0` command line test which remains a mystery.

**Comment by mpirvu** [comment]
Jenkins test sanity xlinuxjit jdk11

**Comment by mpirvu** [comment]
Jenkins test sanity xlinux jdk8,jdk11

**Pull request merged**
