### PR TITLE
Fix typo in testing code.

### PR DESCRIPTION
**Pull request by hangshao0**
"Compatability" should be "Compatibility"

Signed-off-by: hangshao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
The typo is noticed here: https://github.com/eclipse/openj9/pull/2221#issuecomment-398445479
Reviewer: @smlambert

**Comment by smlambert** [comment]
Jenkins test sanity plinux jdk8

**Comment by smlambert** [comment]
Jenkins test sanity windows jdk10

**Comment by smlambert** [comment]
Jenkins test sanity win jdk10

**Comment by smlambert** [comment]
Travis failure unrelated.

**Pull request merged**
