### PR TITLE
Prevent recognizing JIT Helpers not for their ISA

### PR DESCRIPTION
**Pull request by 0dvictor**
1. Prevent recognizing JIT Helpers intended for 32-bit on 64-bit ISA;
2. Prevent recognizing JIT Helpers intended for 64-bit on 32-bit ISA.

Issue #2175 

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by andrewcraik** [comment]
the travis failure is infra related. windows fails are due to #2129. The only failure I am suspicious about is the ppc-64_cmprssptrs_le since I haven't seen that before.

**Comment by 0dvictor** [comment]
Rebased the changes, and Travis CI passed. @andrewcraik could you re-launch the sanity tests?

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by andrewcraik** [comment]
Windows failures due to #2129 - LGTM

**Pull request merged**
