### PR TITLE
Update linkToVirtual to correctly handle J9JNIMethodID->vTableIndex

### PR DESCRIPTION
**Pull request by babsingh**
`linkToVirtual` behaviour is corrected for cases where `J9JNIMethodID->vTableIndex`
is 0.

Related: https://github.com/eclipse/openj9/pull/11367

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Review by DanHeidinga — APPROVED** [review]
lgtm

**Comment by DanHeidinga** [comment]
jenkins test sanity winojdk292,xlinuxojdk292 jdk16 depends ibmruntimes/openj9-openjdk-jdk16#29

**Comment by babsingh** [comment]
**Linux ojdk292 test build output:** https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal/12/tapResults/

re https://github.com/eclipse/openj9/pull/12515#issuecomment-823794628: @fengxue-IS The `test_doPrivilegedFrameStackWalking` failure is also seen in this PR. So, it may not be related to our changes. Another recent change may have triggered the `test_doPrivilegedFrameStackWalking` failure.

I also noticed a JITServer failure in this PR:
```
FAILED: testServerUnreachableForAWhile
java.lang.AssertionError: Expected an exit value of 0 or 143, got 255 instead.
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:153)
	at jit.test.jitserver.JITServerTest.testServerUnreachableForAWhile(JITServerTest.java:327)
```
The JITServer failure seems unrelated to this PR. @dmitry-ten Can you confirm this detail? Should the JITServer failure be tracked in a new issue?

All other failures are preexisting and documented in https://github.com/eclipse/openj9/labels/project%3AMH. The Github issues for the known failures start with `OJDK MH: ...`.

**Comment by dmitry-ten** [comment]
Yeah, this failure is caused by https://github.com/eclipse/openj9/pull/12162 being merged. I'm currently working on a PR to make those changes compatible with JITServer. There's already an issue #11923 to track failures in `testJITServer` so I don't think a new one is necessary, I'll just add a comment to it.

**Comment by babsingh** [comment]
@DanHeidinga Ref: https://github.com/eclipse/openj9/pull/12515#issuecomment-825179424. `test_doPrivilegedFrameStackWalking` failure won't be seen once the PR build is relaunched. This PR is good to be merged.

**Pull request merged**
