### PR TITLE
Remove unused compile_ddr.xml file from DDR_VM debugtools

### PR DESCRIPTION
**Pull request by acrowthe**
Remove unused compilation file from DDR_VM.

Original message and reason for changing file:
Remove unused dependency from compile_ddr.xml due to issues with Java 8
compilation

Signed-off-by: Andrew Crowther <acrowthe3388@gmail.com>

### CODE REVIEW

**Comment by pshipton** [comment]
As this file is not used by openj9 it should just be deleted.

**Comment by tajila** [comment]
@acrowthe can you modify this PR to delete the file instead

**Comment by acrowthe** [comment]
@pshipton @tajila File deleted

**Comment by pshipton** [comment]
This was not a good idea as this file is still needed, reverting.

**Pull request merged**
