### PR TITLE
move fv tests into functional folder

### PR DESCRIPTION
**Pull request by TianyuZuo**
* move all functional tests into functional folder
* this re-organization helps to unify the test code structure
  bewteen OpenJ9 and AdoptOpenJDK
* the getdependency task will only be called during compile
  functional tests
* build_test.xml was cleaned for generic test projects
* update copyright of affected files to 2018

Fixed:#1160

[ci skip]

Signed-off-by: Tianyu Zuo <tianyu@ca.ibm.com>

### CODE REVIEW

**Comment by smlambert** [comment]
For the benefit of others reading this PR, can you update the commit message to add a short statement about why we want to do this, something like "move fv tests into functional folder to make it easy to overlay this test material with those at AdoptOpenJDK"

**Comment by TianyuZuo** [comment]
yes, I will update the commit message and give more details about why this PR is needed and what was done and how it will helps the build structure and process for both OpenJ9 and AdoptOpenJDK.

**Comment by llxia** [comment]
jenkins test sanity zlinux,plinux,aix jdk9

**Comment by llxia** [comment]
jenkins test extended zlinux,plinux,aix jdk8

**Comment by llxia** [comment]
Could you squash your two commits into one? Thanks.

**Comment by TianyuZuo** [comment]
Hi @llxia  Separate these two commits are on purpose. The first commit is to move files to functional folder without any changes, git will keep each file's history in this way. If two commits are merged together, files with changes will be regarded as new files but not kept with previous history.

**Comment by llxia** [comment]
jenkins test sanity zlinux,plinux,aix jdk9,jdk8

**Comment by TianyuZuo** [comment]
HI @llxia  @smlambert 
This PR is ready for review. All tests passed in local run and axxon server run.

**Comment by llxia** [comment]
jenkins test extended zlinux,plinux,aix jdk8

**Comment by llxia** [comment]
@renfeiw could you also review this PR? Thanks.

**Pull request merged**
