### PR TITLE
(0.26.0) Update accessCheckArgRetTypes to always check array component type

### PR DESCRIPTION
**Pull request by fengxue-IS**
Port of #12371 to 0.26 release.

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
Review complete in https://github.com/eclipse/openj9/pull/12371

**Comment by tajila** [comment]
Jenkins test sanity xlinux jdk11

**Comment by tajila** [comment]
testing passed in #12371 but I'll run jdk11 here since this stream has deviated a little from head

**Comment by tajila** [comment]
Compilation failure is caused by mismatch between openj9 and omr branches in PR build testing.

Ill merge now and this will be verified with the jenkins build for the 0.26 stream

**Comment by babsingh** [comment]
OpenJDK bug report: https://bugs.openjdk.java.net/browse/JDK-8266269

**Pull request merged**
