### PR TITLE
Format playlist files

### PR DESCRIPTION
**Pull request by renfeiw**
- use a python xml parser to format the playlist
- this prepares the files for auto modifying

[ci skip]

Signed-off-by: renfeiw <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
tested in internal grinder: Grinder_TKG/1149

**Comment by fjeremic** [comment]
> * use a python xml parser to format the playlist

Is this available somewhere in our repos or is it private?

**Comment by renfeiw** [comment]
> > * use a python xml parser to format the playlist
> 
> Is this available somewhere in our repos or is it private?

It is available in TKG repo as part of the auto disable tool: https://github.com/AdoptOpenJDK/TKG/blob/master/scripts/testBot/playlistModifier.py

**Comment by renfeiw** [comment]
reviewers: @smlambert @llxia

**Comment by llxia** [comment]
This PR ensures that playlist files are using the standard format so that we can enable auto test exclusion using Github workflow (PR https://github.com/eclipse/openj9/pull/11785)

**Comment by llxia** [comment]
jenkins test sanity,extended all jdk8,jdk11

**Review by smlambert — APPROVED** [review]
Awesome @renfeiw !

**Comment by llxia** [comment]
jenkins test sanity,extended win32,win jdk8

**Comment by llxia** [comment]
The windows compilation issue and cmdLineTester_jep178_staticLinking_SE80 test failure are related to this PR.

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
