### PR TITLE
enable dynamic parallel for all functional test builds

### PR DESCRIPTION
**Pull request by llxia**
[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
FYI @pshipton @AdamBrousseau

**Comment by llxia** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1563

**Comment by pshipton** [comment]
I thought we needed a script approval first? Did we get that?

**Comment by pshipton** [comment]
Got some clarification on Slack. It's not this change, but any future changes to https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate will require script approval before any OpenJ9 testing can run afterwards.

**Pull request merged**
