### PR TITLE
Ensure resolved final methods are called directly

### LINKED ISSUE #4334: Test-extended.system-JDK8-aix_ppc-64_cmprssptrs SharedClasses.SCM23.MultiThread_0 crash Compiled_method fastIdentityHashCode
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-aix_ppc-64_cmprssptrs/125
```
MT1 stderr Unhandled exception
MT1 stderr Type=Segmentation error vmState=0x00000000
MT1 stderr J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000032
MT1 stderr Handler1=09001000A2772300 Handler2=09001000A2748BF0
MT1 stderr R0=00000000FFF58C78 R1=00000001100452C0 R2=00000000300213F0 R3=00000000FFF00250
MT1 stderr R4=0000000030008200 R5=000000000000000E R6=00000000FFF00250 R7=09001000A27D0F30
MT1 stderr R8=0000000000000000 R9=0000000000000000 R10=0000000000000002 R11=090000004B255D04
MT1 stderr R12=0000000042008848 R13=000000011004E800 R14=00000000300C5590 R15=0000000030008200
MT1 stderr R16=0000000121112F18 R17=FFFFFFFFFFFFFFFF R18=0000000000000000 R19=0000000000000000
MT1 stderr R20=0000000110045510 R21=0000000000000000 R22=0000000000000000 R23=0000000000000000
MT1 stderr R24=0000000000000000 R25=09001000A2775DB0 R26=0000000000000000 R27=0000000000000000
MT1 stderr R28=0000000000000000 R29=00000000FFF06C58 R30=00000000E0011160 R31=0000000000000000
MT1 stderr IAR=0000000110529CF8 LR=090000004B2553B8 MSR=A00000000200D032 CTR=0000000110529CDC
MT1 stderr CR=2200888000000004 FPSCR=8202000000000000 XER=0000000482020000
MT1 stderr FPR0 0000000000000055 (f: 85.000000, d: 4.199558e-322)
MT1 stderr FPR1 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
MT1 stderr FPR2 bfe002294874d0e5 (f: 1215615232.000000, d: -5.002638e-01)
MT1 stderr FPR3 3fa05cc875900bba (f: 1972374400.000000, d: 3.195788e-02)
MT1 stderr FPR4 3fa0a06f209fb76a (f: 547338112.000000, d: 3.247401e-02)
MT1 stderr FPR5 3fda7aecbeba4e46 (f: 3199880704.000000, d: 4.137527e-01)
MT1 stderr FPR6 3fd5555555555611 (f: 1431655936.000000, d: 3.333333e-01)
MT1 stderr FPR7 3f514726f2cfbe13 (f: 4073700864.000000, d: 1.054562e-03)
MT1 stderr FPR8 bfb96bfae093ca0d (f: 3767781888.000000, d: -9.930389e-02)
MT1 stderr FPR9 40fb39456ab53250 (f: 1790259840.000000, d: 1.115083e+05)
MT1 stderr FPR10 407816625220ec6e (f: 1377889408.000000, d: 3.853990e+02)
MT1 stderr FPR11 3fbc73cd95d5986d (f: 2513803264.000000, d: 1.111420e-01)
MT1 stderr FPR12 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
MT1 stderr FPR13 4020800000000000 (f: 0.000000, d: 8.250000e+00)
MT1 stderr FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MT1 stderr 
MT1 stderr Compiled_method=java/lang/J9VMInternals.fastIdentityHashCode(Ljava/lang/Object;)I
MT1 stderr Target=2_90_20190116_964 (AIX 7.1)
MT1 stderr CPU=ppc64 (8 logical CPUs) (0x200000000 RAM)
MT1 stderr ----------- Stack Backtrace -----------
MT1 stderr runCallInMethod+0x200 (0x090000004AD68F24 [libj9vm29.so+0x56f24])
MT1 stderr gpProtectedRunCallInMethod__FPv+0x48 (0x090000004AD77D2C [libj9vm29.so+0x65d2c])
MT1 stderr signalProtectAndRunGlue+0x28 (0x090000004AD71FAC [libj9vm29.so+0x5ffac])
MT1 stderr omrsig_protect+0x3cc (0x090000004B018E70 [libj9prt29.so+0x68e70])
MT1 stderr gpProtectAndRun+0xf8 (0x090000004AD720FC [libj9vm29.so+0x600fc])
MT1 stderr gpCheckCallin+0x100 (0x090000004AD77CA4 [libj9vm29.so+0x65ca4])
MT1 stderr callStaticVoidMethod+0x48 (0x090000004ADAE38C [libj9vm29.so+0x9c38c])
MT1 stderr J9_CreateJavaVM+0x278 (0x090000004AD3A6FC [libj9vm29.so+0x286fc])
MT1 stderr JNI_CreateJavaVM+0xa0c (0x090000004ACC0C90 [libjvm.so+0x28c90])
MT1 stderr JNI_CreateJavaVM+0x1c4 (0x090000004AC82848 [libjvm.so+0x24848])
MT1 stderr (0x0000000100003940 [java+0x3940])
MT1 stderr _pthread_body+0xf0 (0x0900000000526E14 [libpthreads.a+0x3e14])
```

### PR DESCRIPTION
**Pull request by jdmpapin**
In 3b2830ef `genInvokeVirtual()` was modified to detect resolved private methods for nestmates. If a private method is found, it generates a direct call, and otherwise (including when the method reference is unresolved) it generates a virtual call. In order to generate a virtual call, it queries the constant pool a second time, and if the constant pool entry was originally unresolved, it might have become resolved since. In this case, ilgen could fail to identify for a resolved call that the called method is final, and generate an indirect instead of a direct call. Normally it's harmless for the call to be indirect, but there are a number of final methods recognized by the JIT compiler that undergo transformations assuming that calls to them are direct.

To prevent this problem, `genInvokeVirtual()` will now re-read method from the result of `findOrCreateVirtualMethodSymbol()` whenever that result is resolved.

Fixes #4334

### CODE REVIEW

**Comment by DanHeidinga** [comment]
This looks like a change to common jit code - @andrewcraik Can you review this?  It's one of the fixes for the remaining `0.13.0` issues

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Comment by jdmpapin** [comment]
Rebased

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Pull request merged**
