### PR TITLE
Use LIB_DIR in build.xml

### PR DESCRIPTION
**Pull request by renfeiw**
- we can then update LIB_DIR in one spot when we migrate TKG

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @smlambert

**Comment by llxia** [comment]
jenkins test sanity aix jdk8

**Comment by llxia** [comment]
jenkins test sanity,extended xlinux,aix jdk13

**Comment by llxia** [comment]
jenkins test sanity aix jdk13

**Pull request merged**
