### PR TITLE
Update Windows to openssh 1.1.1j

### PR DESCRIPTION
**Pull request by jdekonin**
* [skip ci]
* #11980

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
jenkins compile win32,win jdk8,jdk11,jdk16

**Comment by pshipton** [comment]
and I just said on the call today that I hadn't seen this in a while.
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/1102/
```
13:24:18  [WS-CLEANUP] Deleting project workspace...
13:24:18  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
13:24:20  ERROR: Cannot delete workspace :Unable to delete 'F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Personal\build'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
[Pipeline] cleanWs
13:24:20  [WS-CLEANUP] Deleting project workspace...
13:24:20  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
13:24:21  Cannot delete workspace: null
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/computer/win2012-x86-4/ might need a reboot again.

**Comment by pshipton** [comment]
Guess not, win2012-x86-4 seems to be running a sanity.functional test just fine.

**Comment by jdekonin** [comment]
jenkins compile win jdk8

**Comment by jdekonin** [comment]
For reference the PR jobs landed on win2012-x86-4, win2012-x86-4, win2012-x86-5 and win2012-x86-6.  I used the same script for installing on each of the machines, so I don't foresee any problems with the other 2.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
