### PR TITLE
Do not cache array class of RAM class

### PR DESCRIPTION
**Pull request by dmitry-ten**
Array class of RAM class can be initialized
    when the class is already loaded, so it is not
    safe to cache NULL as array class.
    Only cache non-NULL values, make remote call otherwise.
    If a remote call returns non-NULL, it means that array
    class has been initiailized. It should not change anymore
    so it's safe to cache it.

Fixes: #5124

### CODE REVIEW

**Comment by ymanton** [comment]
> @mpirvu @ymanton do you think there is a way we can at least partially cache array class?
> If not, I'll also have to remove the entry for array class from `ClassInfo` struct and all related code.

We have various class loading hooks in the JIT that get called when classes are loaded; I assume the hooks would be called when an array class gets created. We could keep track of changing array classes and send deltas to the server on each compilation, but I don't know if it's really worth it.

It's a little surprising to me that the array class of a class can change. Are you sure that the `internalCreateRAMClassDone` code you pointed out in #5124 can overwriting an existing array class, or is it simply initializing it? Can you figure out under which conditions this happens? Then maybe we can figure out how important it is to optimize.

**Comment by dmitry-ten** [comment]
I think you are right.
When we initialize a new array class, `internalCreateRAMClassDone` is the last function called in a long call stack that begins in `ByteCodeInterpreter.hpp` with call to `internalCreateArrayClass`, from functions such as  `inlArrayNewArrayIMpl`, `anewarray`, `multianewarray` etc.
Possible callstack:
```
# internalCreateRAMClassDone
# ...
# <more functions>
# ...
# internalCreateArrayClass
# anewArray
```
In all of these functions, we first check if `componentClass->arrayClass` is NULL, and only if it is NULL, we create a new array class, which results in `componentClass->arrayClass` pointer being set.
Otherwise, we use an already existing array class.
Example:
```
        VMINLINE VM_BytecodeAction
        inlClassArrayTypeImpl(REGISTER_ARGS_LIST)
        {
                VM_BytecodeAction rc = EXECUTE_BYTECODE;
                J9Class *componentClazz = J9VM_J9CLASS_FROM_HEAPCLASS(_currentThread, *(j9object_t*)_sp);
                J9Class *arrayClazz = componentClazz->arrayClass;
                if (NULL == arrayClazz) {
                        arrayClazz = internalCreateArrayClass(_currentThread,
                                (J9ROMArrayClass *) J9ROMIMAGEHEADER_FIRSTCLASS(_currentThread->javaVM->arrayROMClasses),
                                componentClazz);
                }
                if (NULL == arrayClazz) {
                        rc = GOTO_THROW_CURRENT_EXCEPTION;
                } else {
                        returnObjectFromINL(REGISTER_ARGS, J9VM_J9CLASS_TO_HEAPCLASS(arrayClazz), 1);
                }
                return rc;
        }
```

**Comment by dmitry-ten** [comment]
So in this case, the fix is to only cache non-NULL array classes.

**Comment by dmitry-ten** [comment]
Updated.

**Pull request merged**
