### PR TITLE
Fix incorrect tests for mtvsr* instruction support

### PR DESCRIPTION
**Pull request by harryyu1994**
Closes: #9698

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@zl-wang Hi Julian, this one is ready for review and merge.

**Comment by zl-wang** [comment]
Jenkins test sanity aix,plinux jdk8,jdk11

**Comment by harryyu1994** [comment]
@zl-wang I have rebased this one. Ready for sanity test and merge.

**Comment by zl-wang** [comment]
Jenkins test sanity aix,plinux jdk8,jdk11

**Pull request merged**
