### PR TITLE
Enable JIT Server for plinux jdk8 and jdk11

### PR DESCRIPTION
**Pull request by mpirvu**
Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
jenkins test sanity,extended,sanity.system,extended.system plinux jdk8,jdk11

**Comment by mpirvu** [comment]
Infra failure:
```
22:49:59  Scheduling project: Pipeline_Build_Test_JDK11_ppc64le_linux
22:50:08  Starting building: Pipeline_Build_Test_JDK8_ppc64le_linux #1429
22:50:09  Starting building: Pipeline_Build_Test_JDK11_ppc64le_linux #1433
Creating placeholder flownodes because failed loading originals.
Setting status of 7df080a8f34a4384055c7babd6320dd4d6cc19b7 to FAILURE with url https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/2394/ and message: ' '
Using context: Pull Request - OpenJ9
java.io.IOException: Tried to load head FlowNodes for execution Owner[PullRequest-OpenJ9/2394:PullRequest-OpenJ9 #2394] but FlowNode was not found in storage for head id:FlowNodeId 1:104
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.initializeStorage(CpsFlowExecution.java:679)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:716)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:665)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.onLoad(WorkflowRun.java:529)
	at hudson.model.RunMap.retrieve(RunMap.java:225)
	at hudson.model.RunMap.retrieve(RunMap.java:57)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:501)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:483)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.getByNumber(AbstractLazyLoadRunMap.java:381)
	at hudson.model.RunMap.getById(RunMap.java:205)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.run(WorkflowRun.java:902)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.get(WorkflowRun.java:913)
	at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:65)
	at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:57)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$ItemListenerImpl.onLoaded(FlowExecutionList.java:178)
	at jenkins.model.Jenkins.<init>(Jenkins.java:1022)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Finished: FAILURE
```

**Comment by mpirvu** [comment]
jenkins test sanity,extended,sanity.system,extended.system plinux jdk8,jdk11

**Comment by mpirvu** [comment]
Java8 extended suite failed one of the `cmdLineTester_jep178_staticLinking_SE80_0` tests
```
Testing: jep178 testing dynamic linking
Test start time: 2020/01/08 17:38:52 Coordinated Universal Time
Running command: /home/jenkins/jenkins-agent/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_Personal/openjdkbinary/openjdk-test-image/openj9/testjep178_dynamic -jvmpath:/home/jenkins/jenkins-agent/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_Personal/openjdkbinary/j2sdk-image/jre/bin/../lib/ppc64le/j9vm -classpath:/home/jenkins/jenkins-agent/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_Personal/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/jep178staticLinkingTest/jep178staticLinkingTest.jar -Xcompressedrefs  com/ibm/j9/tests/jeptests/StaticLinking
Time spent starting: 201 milliseconds
Time spent executing: 40130 milliseconds
Test result: FAILED
Output from test:
 [OUT] [MSG] Starting up JEP 178 test.
 [OUT] [MSG] Opening jvm from /home/jenkins/jenkins-agent/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_Personal/openjdkbinary/j2sdk-image/jre/bin/../lib/ppc64le/j9vm/libjvm.so
 [OUT] [MSG] Reached OnLoad (testlibA): JNI_OnLoad [dynamically]
 [OUT] [MSG] Reached OnLoad (testlibB): JNI_OnLoad [dynamically]
 [OUT] [MSG] Calling native instance method fooImpl.
 [OUT] [MSG] Reached native fooImpl() [dynamically]
 [OUT] [MSG] Calling native static method barImpl.
 [OUT] [MSG] Reached native barImpl() [dynamically]
 [OUT] [MSG] Test jep178 passed with error code: 0
>> Required condition was found: [Output match: [MSG] Reached OnLoad (testlibA): JNI_OnLoad [dynamically]]
>> Required condition was found: [Output match: [MSG] Reached OnLoad (testlibB): JNI_OnLoad [dynamically]]
>> Required condition was found: [Output match: [MSG] Reached native fooImpl() [dynamically]]
>> Required condition was found: [Output match: [MSG] Reached native barImpl() [dynamically]]
>> Required condition was not found: [Output match: [MSG] Reached OnUnload (testlibA): JNI_OnUnload [dynamically]]
>> Required condition was not found: [Output match: [MSG] Reached OnUnload (testlibB): JNI_OnUnload [dynamically]]
>> Failure condition was not found: [Output match: [ERR]]
>> Failure condition was not found: [Output match: [statically]]
>> Success condition was found: [Output match: [MSG] Test jep178 passed with error code: 0]
```

**Comment by pshipton** [comment]
> Java8 extended suite failed one of the cmdLineTester_jep178_staticLinking_SE80_0 tests

There is already an issue opened for this https://github.com/eclipse/openj9/issues/8021

**Comment by mpirvu** [comment]
> There is already an issue opened for this #8021

Thanks. I was about to post that myself. In this case the PR looks good. I am removing "WIP" from title

**Comment by mpirvu** [comment]
@pshipton Could you please review this PR and merge it if you find it fit? Thanks

**Comment by pshipton** [comment]
Reverted due to #8257 which I suspect is a bad protobuf version on some compile machines.

**Pull request merged**
