### PR TITLE
Remove extra directories from SDK tarballs

### LINKED ISSUE #1451: Change Archived SDK tars to start at folder 'jdk' instead of 'build'
Blocks #1450 #1409 

Adopt test pipeline expects this structure.
The only reason we had this was for consistent JAVA_BIN location between PR and Test builds. Also since the OpenJDK repo has a `jdk` folder at the root.

Will need to add an if around JAVA_BIN var to set differently for PR builds until 1450 is resolved.

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Remove build/RELEASE/images
- Set JAVA_BIN differently in PR builds

[ci skip]

Fixes #1451

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
adam test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
[PR job](https://ci.eclipse.org/openj9/job/Adam_PullRequest-Sanity-JDK9-linux_ppc-64_cmprssptrs_le-OpenJ9/31/)
[Build Job](https://ci.eclipse.org/openj9/view/Sandbox/job/Adam_Build-JDK8-linux_390-64_cmprssptrs/17/)
[Test Job]()

**Comment by AdamBrousseau** [comment]
Please review @sophia-guo or @llxia and @vsebe

**Comment by pshipton** [comment]
Does this fix #1451? If so please use a keyword to automatically close it.

**Comment by AdamBrousseau** [comment]
updated keyword

**Pull request merged**
