### PR TITLE
Fix Start PC race condition (0.23)

### PR DESCRIPTION
**Pull request by dsouzai**
Port of https://github.com/eclipse/openj9/pull/10672 into 0.23

### CODE REVIEW

**Comment by dsouzai** [comment]
@mpirvu @pshipton

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
The travis failure on a branch is expected.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
Because this is a fix for a bug it's warranted that we backport it to the 0.23.release

**Pull request merged**
