### PR TITLE
Enable jvmnativestest

### PR DESCRIPTION
**Pull request by sophia-guo**
[ci skip]

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by smlambert** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by smlambert** [comment]
Jenkins test sanity win jdk8,jdk11

**Comment by smlambert** [comment]
Jenkins test xLinux jdk8,jdk11

**Comment by smlambert** [comment]
Jenkins test sanity xlinux jdk8

**Comment by AdamBrousseau** [comment]
Jenkins test sanity xlinux jdk8

**Comment by smlambert** [comment]
Jenkins test sanity win jdk8

**Comment by AdamBrousseau** [comment]
Jenkins test sanity win jdk8

**Comment by smlambert** [comment]
First win job aborted, aix failure unrelated.

**Pull request merged**
