### PR TITLE
port xlpTests, xlpCodeCacheTests into openj9

### PR DESCRIPTION
**Pull request by OscarQQ**
[ci skip]

Signed-off-by: OscarQQ <Yixin.Qian@ibm.com>

### CODE REVIEW

**Comment by OscarQQ** [comment]
| Build       | Platform           | Java Version  | JDK Impl |
|:-------------:|:-------------:|:-----:|:-----------:|
| Grinder/11541     | ppc64le_linux | 8 | IBM|
| Grinder/11542     | s390x_linux      |   8 | IBM|
| Grinder/11543 | x86-64_linux      |    8 | IBM|
| Grinder/11544     | s390x_zos      |   8 | IBM|
| Grinder/11545 | ppc64_aix      |    8 | IBM|
|Grinder/11518|ppc64_aix,ppc64le_linux,ppc64le_linux_xl,s390x_linux,s390x_linux_xl,x86-64_linux,x86-64_linux_xl,x86-64_mac,x86-64_mac_xl,x86-64_windows,x86-64_windows_xl|8,11|OpenJ9|

**Comment by OscarQQ** [comment]
@llxia could you review this? thanks

**Comment by OscarQQ** [comment]
vmfarm build id = 458299

**Comment by OscarQQ** [comment]
s390x_linux failure is related to https://github.com/eclipse/openj9/issues/8972

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
