### PR TITLE
DDR updates for examining thread stacks

### PR DESCRIPTION
**Pull request by keithc-ca**
This is a replay of https://github.com/eclipse/openj9/pull/3518 with a couple of additions. 

- an adapter is added to bridge the differences between OMR's ddrgen and the legacy DDR tools used in IBM builds
- some useless code is removed from `StructureStubGenerator`

### CODE REVIEW

**Comment by keithc-ca** [comment]
This should fix #3472 without the problems of #3518.

**Comment by pshipton** [comment]
jenkins test all xlinux,plinux,zlinux jdk8

**Comment by pshipton** [comment]
PR builds:
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_x86-64_cmprssptrs-OpenJ9/443/
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_ppc-64_cmprssptrs_le-OpenJ9/646/
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_390-64_cmprssptrs-OpenJ9/445/

https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK8-linux_x86-64_cmprssptrs-OpenJ9/59/
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK8-linux_ppc-64_cmprssptrs_le-OpenJ9/147/
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK8-linux_390-64_cmprssptrs-OpenJ9/93/

**Comment by pshipton** [comment]
I don't believe the extended test failures are related to this change.

**Comment by pshipton** [comment]
@keithc-ca in case you didn't notice, there is a typo. Once this is fixed I will merge.

**Comment by keithc-ca** [comment]
Typo in comment fixed; no other changes.

**Pull request merged**
