### PR TITLE
Pass through tool selections to OMR

### PR DESCRIPTION
**Pull request by keithc-ca**
* respect tool choices made at configuration time.
* fix Linux 390 default for CXX

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux jdk8

**Comment by DanHeidinga** [comment]
jenkins test sanity zlinux jdk8

**Comment by DanHeidinga** [comment]
jenkins test sanity xlinux jdk8

**Comment by pshipton** [comment]
Was asking Keith why we set a default for CXX and not CC and now I believe he's going to make additional changes.

**Comment by keithc-ca** [comment]
Updated to supply a default for CC (gcc) and use g++ as the default for CXX.
For the xlc toolchain on Power, don't assume that CC is a C++ compiler.

**Comment by DanHeidinga** [comment]
@pshipton I'm still OK with this change.  Do you any further comments?

**Comment by pshipton** [comment]
lgtm

jenkins compile xlinux,plinux,zlinux jdk8

**Comment by pshipton** [comment]
PR tested passed, but got an error afterward, which I assume is related to eclipse ci being down.

**Pull request merged**
