### PR TITLE
Remove remaining JITServer caches and messages for parts of ROMClass data

### PR DESCRIPTION
**Pull request by AlexeyKhrabrov**
With the full serialization of ROMClasses implemented in #11331, the remaining JITServer messages that request and cache parts of ROMClass data (`ResolvedMethod_classCPIndexOfMethod` and `ResolvedMethod_fieldOrStaticName`) are no longer needed.

### CODE REVIEW

**Comment by AlexeyKhrabrov** [comment]
@mpirvu Can I please get a review for this PR? Thanks.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit jdk11

**Comment by mpirvu** [comment]
Merging, since all tests have passed.

**Pull request merged**
