### PR TITLE
Remove deprecated snippets on X86 [Phase 1/2]

### PR DESCRIPTION
**Pull request by 0dvictor**
Following snippets are deprecated, cleaning up.

X86StackOverflowCheckSnippet
IA32WriteBarrierSnippet
AMD64WriteBarrierSnippet
X86JNIPauseSnippet
X86PassJNINullSnippet

Note that this commit still keeps some of deprecated files,
a subsequent commit will remove them completely.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
This makes sense, but is a bit ugly because of the dependencies. Since @0xdaryl is looking at the OMR clean-up as well I'd like his opinion on this before we make a decision to accept.

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win jdk8,jdk11

**Comment by andrewcraik** [comment]
looks like an infra fail and a conflict (possibly due to a header rename - @0dvictor could you fix the conflict and push - I'll try rerunning the sanity once done.

**Comment by 0dvictor** [comment]
Conflicts have been resolved.

**Comment by 0dvictor** [comment]
Once this PR get merged, https://github.com/eclipse/omr/pull/3472 can be merged; after that all deprecated .cpp files will be deleted.

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win jdk8,jdk11

**Comment by andrewcraik** [comment]
Sanity is clean and I'm happy to proceed with the review form @0xdaryl - merging

**Pull request merged**
