### PR TITLE
Check if pointer is in the SCC before loading it

### PR DESCRIPTION
**Pull request by dsouzai**
Closes https://github.com/eclipse/openj9/issues/7890

### CODE REVIEW

**Comment by mpirvu** [comment]
Jenkins test sanity all jdk8

**Comment by mpirvu** [comment]
All tests have passed, hence merging.

**Comment by mpirvu** [comment]
Please create the corresponding 0.18.0 PR and I'll merge it

**Comment by dsouzai** [comment]
> Please create the corresponding 0.18.0 PR and I'll merge it

Opened https://github.com/eclipse/openj9/pull/8243

**Pull request merged**
