### PR TITLE
Deprecate trj9 compiler directory

### PR DESCRIPTION
**Pull request by fjeremic**
The runtime/compiler/trj9 directory currently serves no purpose as its
parent directory is completely empty. In an effort to simplify the
codebase and closely match the directory layout of OMR we fold this
trj9 directory away so that understanding how OMR and OpenJ9 fit
together with respect to the compiler component is much easier.

Fixes: #667

Signed-off-by: Filip Jeremic fjeremic@ca.ibm.com

### CODE REVIEW

**Comment by fjeremic** [comment]
This PR depends on https://github.com/eclipse/omr/pull/2586.

**Comment by fjeremic** [comment]
Jenkins test sanity depends eclipse/omr#2586

**Comment by fjeremic** [comment]
Updated all copyrights.

Jenkins test sanity depends eclipse/omr#2586

**Comment by fjeremic** [comment]
Windows builds are failing due to an infrastructure issue. This is a known problem. FYI to committers/reviewers.

**Comment by mstoodle** [comment]
I suspect I may not be the only one to be confused by, e.g. this file:
`runtime/compiler/z/codegen/TreeEvaluatorTable.hpp` which contains the magic line:
`#include "compiler/z/codegen/TreeEvaluatorTable.hpp"`

And I'm betting that's supposed to actually pull in the file from OMR:
`omr/compiler/z/codegen/TreeEvaluatorTable.hpp`

I would have to imagine it's the IPATH that makes it work properly, presumably by never adding the `runtime/` directory to IPATH. But I had to think about it a few times to imagine how it would work.

I admire the amount of work that went into this PR, and feel bad for complaining about it, but I really this this set up will confuse even somewhat advanced developers like myself. Maybe this file (and others like it) should have a leading `omr/` like you did in the `.mk` files to make it more clear what's happening?

**Comment by fjeremic** [comment]
> I would have to imagine it's the IPATH that makes it work properly, presumably by never adding the runtime/ directory to IPATH. But I had to think about it a few times to imagine how it would work.

That's precisely how and why it works. The `runtime/` directory is not included in the compiler's IPATH.



> I admire the amount of work that went into this PR, and feel bad for complaining about it, but I really think this set up will confuse even somewhat advanced developers like myself. Maybe this file (and others like it) should insert into the #include "omr/... like you did in the .mk files to make it more clear what's happening?

This is a reasonable request. I agree. I will work on this now.

**Comment by fjeremic** [comment]
@mstoodle fixed in b6fea32. I also took this opportunity to rebase so we can pick up the wonderful fix in https://github.com/eclipse/openj9/pull/1982.

**Comment by fjeremic** [comment]
@mstoodle fixed in b6fea32. I also took this opportunity to rebase so we can pick up the wonderful fix in https://github.com/eclipse/openj9/pull/1982.

Jenkins test sanity

**Comment by fjeremic** [comment]
@mstoodle fixed in b6fea32. I also took this opportunity to rebase and pick up the fix in https://github.com/eclipse/openj9/pull/1982.

Jenkins test sanity depends eclipse/omr#2586

**Comment by mstoodle** [comment]
I like the way this change folds away a lot of the unnecessary `trj9/` directories in our #includes....Much cleaner looking!

**Comment by AdamBrousseau** [comment]
jenkins test sanity win jdk9,jdk10

**Comment by mstoodle** [comment]
I have reviewed and approved all three PRs associated with this change, but I cannot (at this time) afford to oversee the merge process.

If any other committer wants to do the merge based on my approval of the changes, that's fine. Otherwise, I'm afraid I probably won't be able to properly take care of it until Monday (sorry @fjeremic).

**Comment by mstoodle** [comment]
@fjeremic, I have another observation about this pull request that prevents me from merging.

Did you use `git mv` to move all the files out of `trj9/` or did you just use the file system to do it?

It looks to me like we've lost all the history on every file within the compiler component with this change, unless I'm mistaken.....

i.e. `git log <any file name in compiler directory>` only shows:
```
commit 7a71544d5ea28ff38bca158e4bda5e4234b77469
Author: Filip Jeremic <fjeremic@ca.ibm.com>
Date:   Thu May 24 15:09:45 2018 -0400

    Move all files from compiler/trj9 to compiler
    
    In addition delete the trj9 directory all together.
    
    Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>
```

I would prefer not to lose our 8.5 months of history :) .

**Comment by AdamBrousseau** [comment]
I think Git is smart enough to know you moved it. `mv` and rename are the same. If you do `git log --follow -- <filename>` you get the history.

**Comment by fjeremic** [comment]
> I think Git is smart enough to know you moved it. mv and rename are the same. If you do
> git log --follow -- <filename> you get the history.

You're right. I did `git mv` and it made no difference. Reading up more on this it seems there is no clean way of keeping the history intact other than rewriting the entire thing which will never fly in a shared repository [OpenJ9] already forked by hundreds of people. @mstoodle I don't think we have an alternative here other than fixing up our gitconfig to alias `log` with `log --follow`.

**Comment by fjeremic** [comment]
Interestingly enough comparing the old "Move files from runtimes/tr.source to runtimes/compiler" commit git does seem to have kept the history of the rename. It doesn't seem to like moving files around though.

https://github.com/eclipse/openj9/commit/1aa5228bf80cde37c76fdd427b9f72660cb09908

vs.

https://github.com/eclipse/openj9/pull/1992/commits/7a71544d5ea28ff38bca158e4bda5e4234b77469

**Comment by fjeremic** [comment]
Pushed a fix to `JIT_SRCBASE` when doing out of source builds with a sane default value. Also amended ac5d80c with an `*** IMPORTANT ***` message regarding history and `git log --follow` for future readers that may get stumped by this.

**Comment by fjeremic** [comment]
Jenkins test sanity

**Comment by fjeremic** [comment]
@mstoodle as suspected the Travis CI issues have been fixed via #2002. The build has now passed after rebasing on the fix. I've launched the Jenkins builds. Hopefully these pass as well. We should be good to go here now.

**Comment by fjeremic** [comment]
Jenkins test sanity depends eclipse/omr#2586

**Comment by fjeremic** [comment]
Wohoo! All 20 checks successful!

**Comment by fjeremic** [comment]
Just to update anyone who is watching this PR. We have merged the OMR bit but are waiting for an OMR-Acceptance [1] promotion to unblock this change. I am watching it like a hawk and helping it along with all the machine/infrastructure issues.

[1] https://ci.eclipse.org/openj9/job/Pipeline-OMR-Acceptance/

**Comment by pshipton** [comment]
Because of all the PR builds, and the 8 hour timeout on the OMR acceptance, the builds started this morning are unlikely to succeed.

**Comment by fjeremic** [comment]
> Because of all the PR builds, and the 8 hour timeout on the OMR acceptance, the builds started this morning are unlikely to succeed.

Perhaps I'll kick one off very late tonight. Hopefully the farm is not as loaded then?

**Comment by pshipton** [comment]
> Perhaps I'll kick one off very late tonight. Hopefully the farm is not as loaded then?

We expect #2020 to help somewhat in the future. Depends on the backlog left by all the PR builds started during the day. Then there are the nightly builds that start around midnight...

I think the first one from today https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OMR-Acceptance/491/ is going to promote, which I believe contains your change.

**Comment by fjeremic** [comment]
> I think the first one from today ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OMR-Acceptance/491 is going to promote, which I believe contains your change.

It just promoted actually with less than an hour until Armageddon! I'm rebasing this change now.

**Comment by fjeremic** [comment]
@mstoodle rebase was clean and with no merge conflicts. We should be ready to merge here.

**Pull request merged**
