### PR TITLE
Correct function signatures

### PR DESCRIPTION
**Pull request by keithc-ca**

### CODE REVIEW

**Comment by keithc-ca** [comment]
FYI @babsingh

**Comment by DanHeidinga** [comment]
@keithc-ca what is the impact of this change?  What's the reason for it?

**Comment by keithc-ca** [comment]
> @keithc-ca what is the impact of this change? What's the reason for it?

Sorry, I forgot you can't see IBM slack channels anymore. The legacy DDR tooling complains (since #10557):
```
     [exec] "../oti/VMHelpers.hpp", line 1749: error: argument of type "const U_8 *" is
     [exec]           incompatible with parameter of type "void *"
     [exec]      if ((0 == memcmp(methodNameData, "get", methodNameLength))
```

**Comment by DanHeidinga** [comment]
Jenkins test sanity xlinux jdk8

**Review by DanHeidinga — APPROVED** [review]
Change looks fine

**Comment by pshipton** [comment]
jenkins compile win,aix,osx jdk8,jdk11

**Comment by pshipton** [comment]
Keith doesn't think this file is even used by OpenJ9 builds, I'll go ahead and merge.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
