### PR TITLE
Address potential null dereference & memory leak in getEnv2

### PR DESCRIPTION
**Pull request by DanHeidinga**
There have been recent crashes in getEnv2 on OSX.  Reviewing the
code indicated a potential use of null pointer if the allocation
failed.

Fixed the use of the null pointer and cleaned up the allocation
in the case where the subsequent getEnv failed.

Related: #5061

Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Thanks @DanHeidinga! @andrewcraik you're probably the best person to shepherd this PR given your involvement.

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,plinux,win jdk8,jdk11

**Comment by DanHeidinga** [comment]
All the builds have passed.  @andrewcraik are there any review comments that need to be addressed or is this ready to merge?

**Comment by andrewcraik** [comment]
This is good to go - merging.

**Pull request merged**
