### PR TITLE
Remove terminated threads from map of historical names

### PR DESCRIPTION
**Pull request by keithc-ca**
Avoids a memory leak.

### CODE REVIEW

**Comment by DanHeidinga** [comment]
If I'm reading the code correctly we now have a 1-1 mapping of thread to name as this removes the historical names (`Map<threadID>, Set<String>`) keeping the Set size at 1.  

Do we still need the `knownThreads` map with this change?

**Comment by keithc-ca** [comment]
> If I'm reading the code correctly we now have a 1-1 mapping of thread to name as this removes the historical names (`Map<threadID>, Set<String>`) keeping the Set size at 1.
> 
> Do we still need the `knownThreads` map with this change?

Yes. An `OMR_TraceThread` can be reused for multiple Java threads (with different names). It's only when `omr_trc_stopThreadTrace()` is called that the sequence ends.

**Comment by DanHeidinga** [comment]
OpenJ9 caches and reused J9VMThreads which would mean we don't issue the `omr_trc_stopThreadTrace()` until the J9VMThread is actually deallocated, correct?  Won't the leak still occur?  I'm struggling to see how this isn't either 1-1 or continuing to leak.

**Comment by keithc-ca** [comment]
From a small sample, `traceformat` writes:
```
Active threads
    0x0000000000016700  (id reused)
                        (unnamed thread)
                        main
                        Initialization thread
...
```
If we collapse the set so it only remembers the last name for a given thread we get this instead (which is less helpful):
```
Active threads
    0x0000000000016700  (unnamed thread)
...
```

**Comment by DanHeidinga** [comment]
I agree the output is more useful when it has all - some - of the names.  What I'm missing is when the cleanup is triggered as we recycle J9VMThread's at the VM-level and I don't see an obvious call to `omr_trc_stopThreadTrace` that doesn't depend on the thread actually be deallocated.

Basically, doesn't this still leak due to the thread recycling?

**Comment by keithc-ca** [comment]
> Basically, doesn't this still leak due to the thread recycling?

I suppose it depends on your perspective whether you call it a 'leak'. Yes, it's true, that with thread recycling, there's no upper bound to the number of names it may have. If we want to report all those names, then we must wait for its last exit.

**Comment by DanHeidinga** [comment]
Thank Keith.  This looks correct to me

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux jdk8

**Comment by DanHeidinga** [comment]
Jenkins test extended zlinux jdk11

**Pull request merged**
