### PR TITLE
Makefile update to make use of ELFGenerator

### PR DESCRIPTION
**Pull request by nbhuiyan**
ELF generating capabilities in OMR are now handled by
ELFGenerator and its derived classes, all defined in
ELFGenerator.cpp.

Depends on: eclipse/omr#2321

Signed-off-by: Nazim Uddin Bhuiyan <nazimudd@ualberta.ca>

### CODE REVIEW

**Comment by nbhuiyan** [comment]
@0xdaryl

**Comment by 0xdaryl** [comment]
Jenkins test sanity depends eclipse/omr#2321

**Comment by 0xdaryl** [comment]
Jenkins test sanity depends eclipse/omr#2321

**Comment by 0xdaryl** [comment]
@nbhuiyan , would you mind rebasing please?

**Comment by nbhuiyan** [comment]
@0xdaryl done

**Pull request merged**
