### PR TITLE
AArch64: Implement functions for sampling recompilation

### PR DESCRIPTION
**Pull request by knn-k**
This commit implements some functions for sampling recompilation for
AArch64.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
This PR depends on https://github.com/eclipse/omr/pull/5132

**Comment by knn-k** [comment]
jenkins compile alinux64 jdk11 depends eclipse/omr#5132

**Comment by knn-k** [comment]
jenkins test sanity alinux64 jdk11

**Comment by knn-k** [comment]
@0xdaryl This PR is ready for review.

**Comment by knn-k** [comment]
This PR depends on https://github.com/eclipse/omr/pull/5207.

**Comment by knn-k** [comment]
eclipse/omr#5132 and eclipse/omr#5207 have not promoted yet.

**Comment by knn-k** [comment]
jenkins compile alinux64 jdk11

**Comment by knn-k** [comment]
I stopped the jenkins job above.  I will run it later again.

**Comment by knn-k** [comment]
jenkins compile alinux64 jdk11

**Comment by knn-k** [comment]
The build failed with the following message:
> JVMJ9VM011W Unable to load j9jit29: /home/jenkins/workspace/Build_JDK11_aarch64_linux_Personal/build/linux-aarch64-normal-server-release/jdk/lib/compressedrefs/libj9jit29.so: undefined symbol: arm64IndirectCallPatching_unwrapper

**Comment by knn-k** [comment]
The symbol is introduced by #9765.

**Comment by knn-k** [comment]
I didn't notice that dependency on #9765.

**Comment by 0xdaryl** [comment]
Jenkins compile alinux64 jdk11

**Pull request merged**
