### PR TITLE
Add command line flag to enable ConcurrentCopyForward

### PR DESCRIPTION
**Pull request by youngar**

### CODE REVIEW

**Comment by youngar** [comment]
cc @dmitripivkine @amicic @rwy0717 @charliegracie

**Comment by youngar** [comment]
This does depend on a merged OMR commit, not sure if it made it through acceptance yet.

**Comment by amicic** [comment]
Should add noConcurrentCopyForward, too.

**Comment by youngar** [comment]
> Should add noConcurrentCopyForward, too.
Fixed. Thanks

**Comment by charliegracie** [comment]
I do not believe any further testing is required

**Pull request merged**
