### PR TITLE
Use Adopt-OpenJ9 on ppcle systems for bootjdk

### PR DESCRIPTION
**Pull request by jdekonin**
Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
I have manually verified openj9 ci machines have the sdk present on the system, but have not verified compilation differences between openjdk and ibm sdks.

Currently compiles on ppcle are ~20 mins for JDK8 and ~15 mins for JDK9.  If the change to using what AdoptOpenJDK is using as a default negatively impacts these time, there will need to be a review.

**Comment by DanHeidinga** [comment]
@jdekonin Are we able to use OpenJ9 as the bootJDK?  I would rather that we dogfood our own VM instead of using OJDK.

**Comment by keithc-ca** [comment]
The flip side of 'dogfooding' is that we might unknowingly have a dependency on OpenJ9 such that a build would fail using OpenJDK as the boot JDK.

**Comment by DanHeidinga** [comment]
Agreed @keithc-ca - that's a real risk.  Given Adopt is using OJDK as the bootJDK, I think we'll detect that issue fairly early.

I suggested to Joe that we get an extension mechanism in place so Adopt can continue to use OJDK and we can override that with OJ9 on platforms where it works today and roll that out to all platforms as issues are addressed.

**Comment by DanHeidinga** [comment]
My understanding is that on Linux s390, the only OJDK build is interpreter only which will severely affect build times if we're unable to use OJ9.

**Comment by keithc-ca** [comment]
Yes, I think OpenJDK for s390 is interpreter only.

We'll also mitigate the risk if we have at least one build that uses OpenJDK as the boot JDK.

**Comment by DanHeidinga** [comment]
@jdekonin A path forward is to change the OpenJ9 machines to use an OpenJ9-based binary from Adopt to build OpenJ9.  We can start by hardcoding it similar to the existing SDKs and when we commonize the infrastructure scripts, we can make the bootjdk configurable so we can use OJ9 and Adopt can choose which JDK to use.

**Comment by jdekonin** [comment]
WIP because I still need to add to all the machines.

zLinux SDKs are already using Adopt-OpenJ9 as are AIX even though its not obvious from the directory name.  I'll work to add as an extra install in the AdoptOpenJDK/infrastructure scripts separately.

**Comment by jdekonin** [comment]
Machines are configured now.  The last push I did was a rebase only.

**Comment by DanHeidinga** [comment]
@jdekonin can you confirm its valid to use 8 as the bootjdk for 8?

**Comment by jdekonin** [comment]
http://hg.openjdk.java.net/jdk8/jdk8/file/1773f1fd0fac/README-builds.html
```
Building JDK 8 requires use of a version of JDK 7 that is at Update 7 or newer. 
JDK 8 developers should not use JDK 8 as the boot JDK, to ensure that JDK 8 dependencies 
are not introduced into the parts of the system that are built with JDK 7.
```
So I guess I'll drop the bootjdks for 8 to use openjdk7.

**Comment by jdekonin** [comment]
@DanHeidinga, next action is yours.

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux zlinux

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux zlinux

**Comment by DanHeidinga** [comment]
I'm having trouble launching a PR build for this as the jenkins pr builder has started respecting the `skip ci` tag.  Maybe a setting change on Jenkins?

**Comment by DanHeidinga** [comment]
@jdekonin as ridiculous as this is, can you amend your commit to remove the skip ci text so I can launch the PR build?

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux zlinux

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux zlinux

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux

**Comment by DanHeidinga** [comment]
Jenkins test sanity zlinux

**Pull request merged**
