### PR TITLE
Add compressedrefs modes to jsr335 tests

### PR DESCRIPTION
**Pull request by DanHeidinga**
This test is only run in -Xnocompressedrefs modes which are the less common PR test modes.  Enabling this test for -Xcompressedrefs as well.

Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk8,jdk11

**Comment by pshipton** [comment]
Did you want to fix it for Java 11+ as well? I think only Java 8 testing is affected by this change. See `<testCaseName>jsr335tests</testCaseName>`

**Comment by DanHeidinga** [comment]
Yes, pushed a new commit to enable this for 11 as well.  Thanks for catching that!

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk11

**Comment by pshipton** [comment]
My jdk8 build https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/338/

**Pull request merged**
