### PR TITLE
Print processor feature in Xshareclasses:printStats for Z

### PR DESCRIPTION
**Pull request by harryyu1994**
depends on: https://github.com/eclipse/omr/pull/5570

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
OMR dependent change has propagated.

jenkins test sanity all jdk11

**Comment by harryyu1994** [comment]
I think I need to enable this test on Z.
```
Testing: Test 66: Processor Features PrintStats Test : Ensure -Xshareclasses:printStats cache contains processor feature info
Test start time: 2020/10/05 14:02:50 Eastern Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Personal_testList_1/openjdkbinary/j2sdk-image/bin/java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses:name=ShareClassesCMLTests,printStats -version
Time spent starting: 0 milliseconds
	Match (failure): Processor Features                   = esan3 zarch stfle
Time spent executing: 29 milliseconds
Test result: FAILED
	Match (failure): Processor Features                   = esan3 zarch stfle
 [ERR] 
 [ERR] Current statistics for cache "ShareClassesCMLTests": 
 [ERR] 
 [ERR] Cache created with:
 [ERR] 	-Xnolinenumbers                      = false
 [ERR] 	BCI Enabled                          = true
 [ERR] 	Restrict Classpaths                  = false
 [ERR] 	Feature                              = cr
 [ERR] 	Processor Features                   = esan3 zarch stfle
 [ERR] 	                                       msa dfp hpage te
 [ERR] 	                                       msa_e3 msa_e4 ld ei
 [ERR] 	                                       et3 etf3 css css2
 [ERR] 	                                       gi ee fpe hw mi
 [ERR] 	                                       lzrb msa_e5 mi_e2
 [ERR] 	                                       sema mi_e3 vec sea
 [ERR] 	                                       gs vec_pd vec_e1
 [ERR] 	                                       msa_e8 vec_e2
 [ERR] 	                                       vec_pde
 [ERR] 
 [ERR] Cache contains only classes with line numbers
 [ERR] 
 [ERR] base address                         = 0x000003FF3D459000
 [ERR] end address                          = 0x000003FF50000000
 [ERR] allocation pointer                   = 0x000003FF3D6952F8
 [ERR] 
 [ERR] cache layer                          = 0
 [ERR] cache size                           = 314572192
 [ERR] softmx bytes                         = 67108864
 [ERR] free bytes                           = 63676272
 [ERR] Reserved space for AOT bytes         = -1
 [ERR] Maximum space for AOT bytes          = -1
 [ERR] Reserved space for JIT data bytes    = -1
 [ERR] Maximum space for JIT data bytes     = -1
 [ERR] Metadata bytes                       = 38584
 [ERR] Metadata % used                      = 1%
 [ERR] Class debug area size                = 25133056
 [ERR] Class debug area used bytes          = 554520
 [ERR] Class debug area % used              = 2%
 [ERR] 
 [ERR] ROMClass bytes                       = 2343672
 [ERR] AOT bytes                            = 129916
 [ERR] JIT data bytes                       = 1356
 [ERR] Zip cache bytes                      = 0
 [ERR] Startup hint bytes                   = 0
 [ERR] Data bytes                           = 363936
 [ERR] 
 [ERR] # ROMClasses                         = 759
 [ERR] # AOT Methods                        = 61
 [ERR] # Classpaths                         = 2
 [ERR] # URLs                               = 0
 [ERR] # Tokens                             = 0
 [ERR] # Zip caches                         = 0
 [ERR] # Startup hints                      = 0
 [ERR] # Stale classes                      = 0
 [ERR] % Stale classes                      = 0%
 [ERR] 
 [ERR] 
 [ERR] Cache is 5% soft full
 [ERR] 
 [ERR] Cache is accessible to current user = true
>> Failure condition was found: [Output match: Processor Features[\s]*= .*]
>> Success condition was found: [Output match: Current statistics for cache]
```

**Comment by harryyu1994** [comment]
@mpirvu let's rerun the tests, should be able to pass them now.

**Comment by mpirvu** [comment]
jenkins test sanity all jdk11

**Comment by mpirvu** [comment]
jenkins test sanity all jdk11

**Pull request merged**
