### PR TITLE
Add defines within port library for OSX

### PR DESCRIPTION
**Pull request by jdekonin**

### CODE REVIEW

**Comment by jdekonin** [comment]
Github is not displaying commits I am attempting to merge that were created by Dan.

**Comment by DanHeidinga** [comment]
@jdekonin I think these changes have all been merged already in different commits.  This is likely due to my workflow of hack on a main branch, cut a new branch from that, rebase to include the small piece ready to commit, then open a PR.

This leaves the "same" changes in the original branch with different shas.

Is this still needed for anything?

**Comment by jdekonin** [comment]
This is ready for review.

**Comment by DanHeidinga** [comment]
Jenkins test sanity
Jenkins copyright check
Jenkins line endings check

**Comment by DanHeidinga** [comment]
Jenkins test sanity
Jenkins copyright check
Jenkins line endings check

**Comment by DanHeidinga** [comment]
@jdekonin Can you update the copyrights?
```
08:54:40 The following files were modified and have incorrect copyrights
08:54:40 runtime/port/sysvipc/j9sharedhelper.c
08:54:40 runtime/port/sysvipc/j9shsemun.h
08:54:40 runtime/port/unix/j9ipcmutex.c
```

**Comment by jdekonin** [comment]
Copyrights updated.

**Pull request merged**
