### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by keithc-ca**
* fix charReplace() so compilers don't think we're writing out-of-bounds
* J9UTF8 strings are not NUL-terminated (and don't reserve space for terminators)

Without these changes, gcc 10 complains:

```
In function ‘charReplace’,
    inlined from ‘addModuleExportsOrOpens’ at ../../../../../../openj9/runtime/jvmti/jvmtiModules.c:99:4:
../../../../../../openj9/runtime/jvmti/jvmtiModules.c:34:25: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
   34 |    J9UTF8_DATA(utf8)[i] = newChar;
In file included from ../../../../../../openj9/runtime/oti/j9generated.h:69,
                 from ../../../../../../openj9/runtime/oti/j9.h:82,
                 from ../../../../../../openj9/runtime/oti/jvmtiInternal.h:29,
                 from ../../../../../../openj9/runtime/jvmti/jvmtiHelpers.h:28,
                 from ../../../../../../openj9/runtime/jvmti/jvmtiModules.c:22:
../../../../../../openj9/runtime/jvmti/jvmtiModules.c: In function ‘addModuleExportsOrOpens’:
../../../../../../openj9/runtime/oti/j9nonbuilder.h:3223:6: note: at offset 2 to object ‘data’ with size 2 declared here
 3223 |  U_8 data[2];
      |      ^~~~
../../../../../../openj9/runtime/jvmti/jvmtiModules.c: In function ‘jvmtiGetNamedModule’:
../../../../../../openj9/runtime/jvmti/jvmtiModules.c:316:47: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  316 |   J9UTF8_DATA(packageName)[packageNameLength] = '\0';
In file included from ../../../../../../openj9/runtime/oti/j9generated.h:69,
                 from ../../../../../../openj9/runtime/oti/j9.h:82,
                 from ../../../../../../openj9/runtime/oti/jvmtiInternal.h:29,
                 from ../../../../../../openj9/runtime/jvmti/jvmtiHelpers.h:28,
                 from ../../../../../../openj9/runtime/jvmti/jvmtiModules.c:22:
../../../../../../openj9/runtime/oti/j9nonbuilder.h:3223:6: note: at offset [0, 9223372036854775805] to object ‘data’ with size 2 declared here
 3223 |  U_8 data[2];
      |      ^~~~
```

### CODE REVIEW

**Comment by Hello71** [comment]
This might fix the warning for now, but it doesn't fix the underlying correctness issue. It sounds like @gacholio will be able to fix the issue blocking a proper fix, and I think that would be much better.

**Comment by gacholio** [comment]
This will be largely moot once my PR is merged (removing the data field from UTF8 entirely). Let's revisit after that.

**Comment by gacholio** [comment]
@keithc-ca I believe this now unncessary.

**Comment by keithc-ca** [comment]
> @keithc-ca I believe this now unncessary.

Agreed.

**Pull request closed without merging**
