### PR TITLE
Update ROMClass walk implementation to support ROMClass serialization in JITServer

### PR DESCRIPTION
**Pull request by AlexeyKhrabrov**
JITServer will use ROMClass walk (`allSlotsInROMClassDo()` from `romclasswalk.c`) to fully serialize a ROMClass (including possibly interned UTF8 strings that it refers to) when it's sent from the client to the server. This PR updates the walk implementation such that it properly visits all SRPs to UTF8 strings in the ROMClass:
- Some `J9ROM_SRP` slots are changed to `J9ROM_UTF8` since they actually point to UTF8 strings.
- `J9ROM_UTF8` is used instead of `J9ROM_UTF8_NOSRP` for strings in method debug info.
- Out-of-line method debug info is walked unless skipped by the `validateRangeCallback`. (This shouldn't affect any existing code that uses ROMClass walk.)

### CODE REVIEW

**Comment by AlexeyKhrabrov** [comment]
This PR is a prerequisite for #11331. @mpirvu FYI

**Comment by mpirvu** [comment]
@tajila Toby, could I please get a review from you or suggest someone from your team for this PR which covers VM code?
Thank you

**Comment by tajila** [comment]
@AlexeyKhrabrov 

> J9ROM_UTF8 is used instead of J9ROM_UTF8_NOSRP for strings in method debug info.

Why are those changed?

**Comment by tajila** [comment]
FYI @gacholio

**Comment by AlexeyKhrabrov** [comment]
> > J9ROM_UTF8 is used instead of J9ROM_UTF8_NOSRP for strings in method debug info.
> 
> Why are those changed?

Because we need to visit the actual SRP slot instead of the string that it points to, in order to update this SRP in the serialized ROMClass.

**Comment by tajila** [comment]
The equivalent DDR versions of these methods need to be kept consistent with the VM implementation. See `/openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/RomClassWalker.java`

**Comment by gacholio** [comment]
> The equivalent DDR versions of these methods need to be kept consistent with the VM implementation.

I'm not sure that's necessary in this case, other than to keep the walkers similar - the changes are not needed to keep the DDR commands working.

**Comment by AlexeyKhrabrov** [comment]
I'll update the DDR walker. Handling method parameter names as raw SRPs rather than strings is a bug that should be fixed (please correct me if I'm wrong). It looks like the DDR walker already walks out-of-line method debug info, so now they will actually be more consistent. I'll make the changes shortly.

**Comment by AlexeyKhrabrov** [comment]
I've opened a separate PR #11362 with DDR changes since they are not dependent on this PR. I've also slightly changed the code handling out-of-line method debug info to match the code in the DDR walker more closely.

I marked the DDR PR a draft until I can properly test it and this one is merged. What would be the right way to test DDR changes?

**Comment by gacholio** [comment]
DDR testing is included in all of our builds, so a `sanity,extended` test for the PR should be sufficient. As I said before, there's little if any reason to update DDR for this change.

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test extended zlinux jdk8

**Comment by tajila** [comment]
Jenkins test sanity plinux jdk11

**Comment by mpirvu** [comment]
Tests have passed, hence merging.

**Pull request merged**
