### PR TITLE
Adopt OMR's TR_OutlinedInstructionsGenerator

### PR DESCRIPTION
**Pull request by 0dvictor**
eclipse/omr#2640 introduced TR_OutlinedInstructionsGenerator, which uses RAII
to hide the management of the instruction stream manipulations.
OpenJ9 now adopts it.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win

**Comment by fjeremic** [comment]
FYI @0dvictor if you specify the name of the repo, followed by a # with a PR number GitHub will auto link it as eclipse/omr#2640.

**Comment by andrewcraik** [comment]
hmm need x32 before we merge this one I think

**Comment by andrewcraik** [comment]
Jenkins test sanity win32,xlinux32

**Comment by andrewcraik** [comment]
Jenkins test sanity win32

**Comment by 0dvictor** [comment]
Windows failure due to #2129

**Pull request merged**
