### PR TITLE
Abort ILGen for non supported features in AOT

### PR DESCRIPTION
**Pull request by dsouzai**
Constant Dynamic, Method Handle Constant, and Method Type Constant
 is not currently supported in AOT. Therefore, in this
PR, the compiler throws the appropriate exception in ILGen if this
condition is met. However, because all of these exceptions are a
TR::RecoverableILGenException, if the compiler is generating IL for an
inlined method, it will not abort the compile, but simply refuse to
inline that particular method.

Fixes https://github.com/eclipse/openj9/issues/6011

### CODE REVIEW

**Comment by dsouzai** [comment]
jenkins test sanity.functional+aot xlinux jdk11

**Comment by dsouzai** [comment]
Yay the AOT test passed.

**Comment by dsouzai** [comment]
@andrewcraik @cathyzhyi could you please review?

**Comment by dsouzai** [comment]
@andrewcraik do we need to be also aborting an AOT compile in these conditions?

```
         else if (method()->isMethodHandleConstant(cpIndex))
            {
            loadSymbol(TR::aload, symRefTab()->findOrCreateMethodHandleSymbol(_methodSymbol, cpIndex));
            }
         else
            {
            TR_ASSERT(method()->isMethodTypeConstant(cpIndex), "Address-type CP entry %d must be class, string, methodHandle, or methodType", cpIndex);
            loadSymbol(TR::aload, symRefTab()->findOrCreateMethodTypeSymbol(_methodSymbol, cpIndex));
            }
```

**Comment by cathyzhyi** [comment]
The change looks good to me.

**Comment by andrewcraik** [comment]
@dsouzai I think the answer to your question on constant handles is yes - those constants could change in a new run.

**Comment by dsouzai** [comment]
@andrewcraik @cathyzhyi PR is ready for full review now.

**Comment by andrewcraik** [comment]
The aborts for the 292 handles are conservative - I am fine with doing it as discussed above, but there should be an issue to track disabling the code that would fold these so that we just leave them as loads. They would need a relocation to load them from the constant pool, but assuming we did that then it should work, just the scope of optimization will be limited because we cannot treat them as constant.

**Comment by dsouzai** [comment]
@andrewcraik opened https://github.com/eclipse/openj9/issues/9106 to track this (and also added it to https://github.com/eclipse/openj9/issues/2921).

**Comment by dsouzai** [comment]
jenkins test sanity.functional all jdk11

**Pull request merged**
