### PR TITLE
Update to openssl 1.1.1j for all platforms but Windows

### PR DESCRIPTION
**Pull request by pshipton**
Issue https://github.com/eclipse/openj9/issues/11980

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity.openjdk zlinux,plinux,xlinux,mac,aix jdk11

**Review by keithc-ca — APPROVED** [review]

**Comment by pshipton** [comment]
jenkins test sanity.openjdk zlinux,plinux,xlinux,mac,aix jdk8,jdk16

**Comment by pshipton** [comment]
jenkins test sanity.openjdk zlinux,plinux,xlinux,osx,aix jdk8,jdk11,jdk16

**Comment by pshipton** [comment]
The openjdk failure https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Personal/11/ is a known issue https://github.com/eclipse/openj9/issues/11899

**Comment by pshipton** [comment]
Seems the jdk16 AIX build timed out before completion. Likely this can be merged anyway, but if necessary this build can be re-run.

**Comment by keithc-ca** [comment]
It seems the AIX build got 'stuck':
```
[2021-02-16T17:29:42.117Z] [ 41%] Building CXX object runtime/compiler/CMakeFiles/j9jit.dir/runtime/ArtifactManager.cpp.o
[2021-02-16T22:09:22.166Z] Cancelling nested steps due to timeout
```
I don't anticipate problems specific to AIX, so I'll merge this without further ado.

**Pull request merged**
