### PR TITLE
Add protobuf 3.7.1 to x86 and 390 docker containers

### PR DESCRIPTION
**Pull request by jdekonin**
* [skip ci]
* addition to eclipse/openj9#6863
* supporting eclipse/openj9#7099

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
This commit changes protobufs on x86 from 3.5.1 to 3.7.1.
While it's nice to have the same version of protobufs on all machines, we have not yet validated 3.7.1 on x86. We started with 3.5.1 on x86, then, much later, we discovered that on Z/P we needed version 3.7.1 due to some bugs that were fixed in that release.
I would like to run some tests with protobufs 3.7.1 on x86 before delivering this PR.

**Comment by mpirvu** [comment]
The JIT dll size increases by 92K or 0.5% when moving up from protobufs 3.5.1. to 3.7.1 on x86. This is a small increase and we should be able to tolerate it.
I am in the process of running performance and functional tests. Will post results once I am done.

**Comment by mpirvu** [comment]
There is no change in performance when switching from protobufs 3.5.1. to 3.7.1 on x86. Also sanity tests look good so we should be able to switch to 3.7.1

**Comment by mpirvu** [comment]
@jdekonin If you resolve the conflicts I can merge this PR

**Comment by mpirvu** [comment]
@jdekonin Just a gentle reminder to rebase the files of this PR do that I can merge it. Thanks!

**Comment by jdekonin** [comment]
@mpirvu, finally got this rebased and merged for review.

**Comment by mpirvu** [comment]
@jdekonin   Is there any testing I should be triggering on this PR before merging?

**Comment by jdekonin** [comment]
We don't have any PR based testing enabled for docker containers at OpenJ9 atm, so no.

**Pull request merged**
