### PR TITLE
WIP: Create Shared Cache earlyinit/earlystartup routine

### PR DESCRIPTION
**Pull request by harryyu1994**
- Step 1: Split SH_CompositeCacheImpl::startup() into SH_CompositeCacheImpl::earlystartup() and SH_CompositeCacheImpl::startup()

Issue: https://github.com/eclipse/openj9/pull/11232

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@pshipton Do you think we should get this cleaned up/reviewed/tested/merged first? I'm also fine with including other changes in this PR.

**Comment by harryyu1994** [comment]
```
TEST TARGETS SUMMARY
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
PASSED test targets:
	shrtest_linux_SE80_1

TOTAL: 1   EXECUTED: 1   PASSED: 1   FAILED: 0   DISABLED: 0   SKIPPED: 0
ALL TESTS PASSED
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by harryyu1994** [comment]
FYI @mpirvu.

The Shared Cache tests seem to be passing. This one is ready for review. @pshipton

**Comment by pshipton** [comment]
I think we need to prove the whole things works before merging anything.

**Comment by harryyu1994** [comment]
Okay we will just have this 1 PR here then. It will be done incrementally. Each step is one commit.

**Comment by pshipton** [comment]
> Each step is one commit.

+1. These changes look fine.

**Pull request closed without merging**
