### PR TITLE
Remove VarHandle equals and hashCode

### PR DESCRIPTION
**Pull request by theresa-m**
Fixes: https://github.com/AdoptOpenJDK/run-aqa/issues/49

Port to 0.24: https://github.com/eclipse/openj9/pull/11533

- These methods were originally intended to be part of Java 12 and then removed. https://bugs.openjdk.java.net/browse/JDK-8215648
- updated Constants API functional tests

Signed-off-by: Theresa Mammarella <tmammare@redhat.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Why `depends:doc`, because the javadoc needs to be re-generated?

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk15

**Comment by pshipton** [comment]
We should probably add this to the 0.24 release, which will be the last release for Java 15.

**Comment by pshipton** [comment]
Running other tests as well just in case this exposes a problem.
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1321 - extended.functional
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1322 - sanity.system
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1323 - extended.system

**Comment by pshipton** [comment]
All the testing passed. Pls create a PR against the 0.24 branch, and explain why the `depends:doc` label was added.

**Review by pshipton — APPROVED** [review]

**Comment by theresa-m** [comment]
> All the testing passed. Pls create a PR against the 0.24 branch, and explain why the `depends:doc` label was added.

I was thinking the change should be mentioned in the release notes. If not if can be removed.

**Comment by pshipton** [comment]
> I was thinking the change should be mentioned in the release notes. If thats not necessary it can be removed.

It doesn't seem necessary. We don't typically mention bug fixes. We publish the list of fixes.

**Comment by theresa-m** [comment]
0.24 port: https://github.com/eclipse/openj9/pull/11533

**Pull request merged**
