### PR TITLE
Modify the translated PII files in nls folder

### PR DESCRIPTION
**Pull request by XiaojuanChen**
Files update for PII_Ship1.

Signed-off-by: Xiao Juan Chen <bjchenxj@cn.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
@XiaojuanChen these errors are occurring
```
* Failure occured during the process *
Error: J9NLS_VM_LOADING_CONSTRAINT_OVERRIDE_VIOLATION Message "betöltési korlátsértés a(z) "%2$.*1$s.%4$.*3$s%6$.*5$s" metódus felülbírálásakor: a(z) "%8$.*7$s@%9$x" betöltő a(z) "%11$.*10$s" osztályban és a(z) "%13$.*12$s@%14$x" betöltő a(z) "%16$.*15$s" osztályban eltérő típusú metódusaláírásokat tartalmaznak" in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/j9vm/j9vm_hu.nls is different from "loading constraint violation when overriding method "%2$.*1$s.%4$.*3$s%6$.*5$s" during creation of class "%18$.*17$s": loader "%8$.*7$s@%9$x" of class "%11$.*10$s" and loader "%13$.*12$s@%14$x" of class "%16$.*15$s" have different types for the method signature" in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/j9vm/j9vm.nls

* Failure occured during the process *
Error: J9NLS_VM_NESTMATES_CLASS_FAILED_TO_LOAD Message "Il membro nidificato %2$.*1 deve essere in grado di caricare l'host nest %4$. * 3" in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/j9vm/j9vm_it.nls is different from "Nest member %2$.*1$s must be able to load nest host %4$.*3$s" in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/j9vm/j9vm.nls
```

**Comment by XiaojuanChen** [comment]
@Peter_Shipton@ca.ibm.com Could you help to review and merge? Thanks!

**Comment by pshipton** [comment]
@XiaojuanChen please fix the list of commits to contain only your changes. Also each commit must have a Signed-off-by footer. There is a merge conflict now with runtime/nls/exel/exelib_zh_CN.nls that also needs to be resolved.

**Comment by XiaojuanChen** [comment]
Due to conflict translation files runtime/nls/exel/exelib_xx.nls, I close this PR to create a new one.

**Pull request closed without merging**
