### PR TITLE
Update test lib location

### PR DESCRIPTION
**Pull request by renfeiw**
- change test lib location to TKG/lib

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by renfeiw** [comment]
related PR: https://github.com/AdoptOpenJDK/TKG/pull/21

**Comment by renfeiw** [comment]
The copyright check failure is expected, as the files get changed are .classpath files

**Comment by llxia** [comment]
This PR updated .classpath. No PR build is needed.

**Pull request merged**
