### PR TITLE
Removed single line annotation comments from #include directives

### PR DESCRIPTION
**Pull request by fjeremic**
Removed annotation describing feature included from the file. This is a
port of the work done in eclipse/omr#3522.

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Jenkins test sanity all JDK8

**Comment by fjeremic** [comment]
@0xdaryl I think these conflicts will happen as the volume of code changed in the include directives here touches basically every file. Rather than fighting to stay ahead of other people I'll let the builds finish as they are now and add a new commit on top to fix the conflicts so it's obvious I didn't change the prior commit. We can then re-review and merge without testing as the delta will be super small to resolve the conflict.

Does that sound reasonable?

**Comment by 0xdaryl** [comment]
Yes, that should be fine.  These changes are very safe.

**Comment by fjeremic** [comment]
Linux build failed because we're waiting for OMR Acceptance to pick up the big Z RA change.

**Comment by 0xdaryl** [comment]
Testing completed successfully (except for Z as @fjeremic justified above).  If you rebase to remove the merge conflicts I will merge straight away to avoid further merge conflicts.

**Comment by fjeremic** [comment]
> Testing completed successfully (except for Z as @fjeremic justified above). If you rebase to remove the merge conflicts I will merge straight away to avoid further merge conflicts.

@0xdaryl done!

**Pull request merged**
