### PR TITLE
Check verbose option before printing to log

### PR DESCRIPTION
**Pull request by dsouzai**
Signed-off-by: Irwin D'Souza <dsouzai@ca.ibm.com>

### CODE REVIEW

**Comment by dsouzai** [comment]
fyi @sehirst

**Comment by dsouzai** [comment]
@mpirvu could you please review.

**Comment by sehirst** [comment]
It would be interesting to understand why the line is being printed even though it's reported that no `-Xjit` is set, however the added guard will prevent it from being printed so that's good for me. Thanks!

**Comment by fjeremic** [comment]
Jenkins test sanity

**Comment by fjeremic** [comment]
Jenkins test sanity

**Comment by dsouzai** [comment]
Rebased my changes onto the latest master; @fjeremic you mind running the sanity again?

**Comment by fjeremic** [comment]
Jenkins test sanity

**Pull request merged**
