### PR TITLE
Remove spurious volatile qualifier

### PR DESCRIPTION
**Pull request by gacholio**
Related: #11315

[ci skip]

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
fyi @babsingh

**Review by babsingh — APPROVED** [review]
LGTM.

**Comment by DanHeidinga** [comment]
@gacholio anything in the internal history to describe why the volatile was added in the first place?

**Comment by DanHeidinga** [comment]
Reading the code, the field that is more likely to need the volatile modifier is `cachedHandle` - though any "read-once" enforcement would be preferred to volatile.

**Comment by gacholio** [comment]
I've always thought the use of volatile on locals was a hack to fix a compiler issue (which might well be some bad code on our part that's rarely exposed on some compilers).

**Comment by DanHeidinga** [comment]
Less a compiler issue and more we write racy code which violates some constraints in the spec.  The volatile forces us to read it once onto the stack and then (unfortunately) re-read it from the local all the time rather than letting the compiler re-read it from the original source.

**Comment by gacholio** [comment]
There's nothing useful in the history. I was hoping that const would do what you say above, so maybe this is actually introducing more problems.

**Comment by DanHeidinga** [comment]
> There's nothing useful in the history. I was hoping that const would do what you say above, so maybe this is actually introducing more problems.

I don't trust const to mean anything to the compiler.  It's more documentation to the programmer that the programmer won't change it in this function.  The compiler can see that we don't change it without needing const.

**Comment by gacholio** [comment]
@DanHeidinga Do you have some documentation about volatile locals, or is this just an assumption based on what I observed with gcc?

**Comment by DanHeidinga** [comment]
> Every access (both read and write) made through an lvalue expression of volatile-qualified type is considered an observable side effect for the purpose of optimization and is evaluated strictly according to the rules of the abstract machine (that is, all writes are completed at some time before the next sequence point). This means that within a single thread of execution, a volatile access cannot be optimized out or reordered relative to another visible side effect that is separated by a sequence point from the volatile access.
https://en.cppreference.com/w/c/language/volatile

So every access (read/write) must occur which is where the "volatile forces us to read it once onto the stack and then (unfortunately) re-read it from the local all the time " behaviour comes from.

Not a great reference but the clearest I've found in the digging this morning

**Comment by gacholio** [comment]
Closing this as it will have no positive effect.

**Pull request closed without merging**
