### PR TITLE
Merge master to jitaas

### PR DESCRIPTION
**Pull request by harryyu1994**
I made the following 4 commits to fix build and test issues with the merge.
e9adf4ec225ede4590915107e154c89f0a10bd7a ------> https://github.com/eclipse/openj9/pull/6575
5784cf40246c94fb873d4facb67cd02b2a37b86a ------> https://github.com/eclipse/openj9/pull/6793
fdaba699247a45e25b6902f2b95ab3cce240177f  ------> https://github.com/eclipse/openj9/pull/6791
c49b971d95c118831ed6eb79ec65059b888f3426 ------> https://github.com/eclipse/openj9/pull/6575

Files to focus on:
CompilationThread.cpp
J9Options.cpp
PersistentCHTable.hpp
RuntimeAssumptions.hpp

OMR: https://github.com/eclipse/openj9-omr/pull/36

### CODE REVIEW

**Comment by mpirvu** [comment]
Following the code, `TR_ResolvedJ9Method::archetypeArgPlaceholderSlot()` could just return _paramSlots. Unfortunately, there is no immediate getter for this field. The getter that comes close is:
```
U_16
TR_ResolvedJ9Method::numberOfParameterSlots()
   {
   return _paramSlots + (isStatic()? 0 : 1);
   }
```
That `1` is for `this` parameter (the receiver), I think.
The comment in the code says:
` +1 :thunk archetype are always virtual method and has a receiver`
so we need to return `numberOfParameterSlots()-1` which is what the old solution did:
```
U_16
TR_ResolvedJ9Method::archetypeArgPlaceholderSlot(TR_Memory *mem)
   {
   TR_ASSERT(isArchetypeSpecimen(), "should not be called for non-ArchetypeSpecimen methods");
   // Note that this creates and discards a TR_ResolvedMethod, so it leaks heap memory.
   // TODO: Need a better implementation.  Probably should just re-parse the archetype's signature.
   // Then we won't need the TR_Memory argument anymore either.
   //
   TR_ResolvedMethod *archetype = fej9()->createResolvedMethod(mem, getNonPersistentIdentifier());
   //TR_ASSERT(((TR_ResolvedMethod*)this)->numberOfParameterSlots() == archetype->numberOfParameterSlots(), "not equal %d %d", ((TR_ResolvedMethod*)this)->numberOfParameterSlots(), archetype->numberOfParameterSlots());
   return archetype->numberOfParameterSlots() - 1; // "-1" because the placeholder is a 1-slot type (int)
   }
```
I just don't understand why in the old solution we needed to create another resolvedMethod when the one at hand had everything we needed.
The comment mentions about re-parsing the archetype's signature, so maybe the existing signature is not good enough for some reason.

**Comment by harryyu1994** [comment]
I have verified with my build that the existing signature is not good enough. So I decided to go with using `romOfRamMethod()` to get the original ROM method. I have tested it and it works now. Previously with existing _signature, we failed with NullPointerException for a testcase. I also moved the `romOfRamMethod()` into `JITServerHelpers`, previously it was only used in one file and it didn't belong to any class. I have updated the changes and have the new SHA updated in the first comment. Ready for review and test. My sanity is still running but looking good so far.

**Comment by harryyu1994** [comment]
> J9VMMethodEnv

Okay I also think it's a good idea to create a new API in `J9VMMethodEnv.cpp` that deals with getting `originalROMMethod` for both mainline and JITServer. But I feel like we should deal with that in a separate PR as this one has way too many commits already. I'm just hoping to get an error-free merge in first.

**Comment by harryyu1994** [comment]
```
        ShareClassesCMLOpenJ9_1
        cmdLineTester_SCCommandLineOptionTests_1
        cmdLineTester_SCHelperCompatibilityTests_unix_1
        cmdLineTester_ShareClassesSimpleSanity_1
        cmdLineTester_SCURLHelperTests_80_1
        cmdLineTest_sigxfszHandlingTest_0
        cmdLineTester_XcheckJNI_0
        testXXArgumentTesting_0

FAILED test targets:
        cmdLineTester_CryptoTest_0
        cmdLineTester_pltest_0

TOTAL: 203   EXECUTED: 117   PASSED: 115   FAILED: 2   DISABLED: 5   SKIPPED: 81
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

The results look like this. Those two failures are there even without JITServer. Checking to see if mainline gives us the same thing. And we probably need to merge even more things if it's a problem with mainline.

**Comment by harryyu1994** [comment]
the two failures failed with latest `master` as well. So it's a mainline problem. Well hopefully it's my setup problem. @mpirvu I think we can trigger a PR test to see what happens. I get same test results for both `master` and this PR.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaas

**Comment by harryyu1994** [comment]
OMR change available here: https://github.com/eclipse/openj9-omr/pull/36

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#36

**Comment by harryyu1994** [comment]
```
17:45:50  FAILED test targets:
17:45:50  	cmdLineTester_gcsuballoctests_0
17:45:50  
17:45:50  TOTAL: 204   EXECUTED: 117   PASSED: 116   FAILED: 1   DISABLED: 6   SKIPPED: 81
```
Looks like this test is still failing, can't reproduce locally though. Other than that, everything passed.

**Comment by mpirvu** [comment]
I am going to run some performance tests before merging this

**Comment by mpirvu** [comment]
Performance looks stable overall, though at some point I had the feeling that fluctuations are larger than usual.

**Comment by mpirvu** [comment]
As with any merge master-->jitaas we have to scan for changes to frontend queries. In this case there are two changes that we need to address in the future:
```
bool TR_J9VMBase::generateCompressedPointers()
  return TR::Compiler->om.compressObjectReferences();
  
bool TR_J9VMBase::generateCompressedLockWord()
   return TR::Compiler->om.compressObjectReferences();
```   
   
Looking at `J9::ObjectModel`

```
 bool compressObjectReferences() { return _compressObjectReferences; }
```
 
The field is set in
```
J9::ObjectModel::initialize()
  // Compressed refs
   uintptr_t result = mmf->j9gc_modron_getConfigurationValueForKey(vm,
                                                                   j9gc_modron_configuration_compressObjectReferences,
                                                                   &value);
   if (result == 1 && value == 1)
      _compressObjectReferences = true;
   else
      _compressObjectReferences = false;
```
      
If the same server can compile for both compressed and non-compressedrefs the we need to make _compressObjectReferences a property of the client and store it per client.

**Comment by mpirvu** [comment]
Java11 tests show a crash during `JCL_Test_1`:
```
Type=Segmentation error vmState=0x0005ffff
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F99A3CFD530 Handler2=00007F99A3811B50 InaccessibleAddress=0000000000000008
RDI=00000000010C8B00 RSI=0000000000000000 RAX=00007F99801807F8 RBX=0000000000000004
RCX=0000000000000004 RDX=00007F99A1FA08EA R8=00007F99A1F6DA39 R9=000000000000001D
R10=00007F99A23D0998 R11=0000000000000206 R12=000000000000001D R13=00007F99A1FA08EA
R14=00000000010C8B00 R15=0000000000000004
RIP=00007F99A3D22750 GS=0000 FS=0000 RSP=00007F9980180560
EFlags=0000000000010206 CS=0033 RBP=0000000000000000 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000008
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm4 000000ff00000000 (f: 0.000000, d: 5.411089e-312)
xmm5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm6 0018008000000015 (f: 21.000000, d: 3.337882e-308)
xmm7 0010008000040000 (f: 262144.000000, d: 2.225345e-308)
xmm8 0000000000000100 (f: 256.000000, d: 1.264808e-321)
xmm9 0004000000000400 (f: 1024.000000, d: 5.562685e-309)
xmm10 00ffffffffffffff (f: 4294967296.000000, d: 7.291122e-304)
xmm11 0000000049d70a38 (f: 1238829568.000000, d: 6.120632e-315)
xmm12 000000004689a022 (f: 1183424512.000000, d: 5.846894e-315)
xmm13 0000000047ac082f (f: 1202456576.000000, d: 5.940925e-315)
xmm14 0000000048650dc0 (f: 1214582272.000000, d: 6.000833e-315)
xmm15 0000000046b73e38 (f: 1186414080.000000, d: 5.861665e-315)
Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so
Module_base_address=00007F99A3C5E000

Method_being_compiled=java/lang/invoke/FoldNonvoidHandle.invokeExact_thunkArchetype_X(I)I
```
I am guessing we try to access a field of a NULL object.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional xlinux jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Jenkins test sanity.functional xlinux jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Jenkins test sanity.functional xlinux jdk11 depends eclipse/openj9-omr#36

**Comment by mpirvu** [comment]
Without JITaaS I see only `cmdLineTester_gcsuballoctests_0` failure, but `JCL_Test_1` failures could be intermittent.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#36

**Comment by mpirvu** [comment]
This time there is only the known `cmdLineTester_gcsuballoctests_0 ` failure.

**Pull request merged**
