### PR TITLE
Export JAVA_HOME in TestKitGen

### PR DESCRIPTION
**Pull request by renfeiw**
- export JAVA_HOME=JDK_HOME

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by llxia** [comment]
jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
jenkins test extended xlinux jdk11

**Comment by llxia** [comment]
jenkins test sanity all jdk8

**Comment by llxia** [comment]
Failure in aix JDK8 is a known issue: https://github.com/eclipse/openj9/issues/4643

**Pull request merged**
