### PR TITLE
Enable the OpenJDK292 setting on Aarch64

### PR DESCRIPTION
**Pull request by ChengJin01**
Signed-off-by: Cheng Jin <jincheng@ca.ibm.com>

### CODE REVIEW

**Comment by ChengJin01** [comment]
Reviewer: @jdekonin, @AdamBrousseau

**Review by AdamBrousseau — COMMENTED** [review]
The change looks fine to me functionally. Additionally, if you want, you can define a short name for the PR trigger in SHORT_NAMES but I see none of the other 292 specs are there. If not, you can launch with the full spec name.

I will leave it up to @pshipton to decide if we want aarch64_linux added to `all` for PR triggers.

**Comment by pshipton** [comment]
We can't add aarch64_linux to `all`, we only have the one machine, which isn't enough for all the PR testing that uses `all`.

**Comment by ChengJin01** [comment]
I remove the changes at /buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy as the SHORT_NAMES & SPEC are already set up on Aarch64 as follows:
```
SPECS = ['ppc64_aix' : CURRENT_RELEASES,
...
         'aarch64_linux_ojdk292' : CURRENT_RELEASES,  <-----
         'aarch64_linux_xl_ojdk292' : CURRENT_RELEASES,
// SHORT_NAMES is used for PullRequest triggers
// TODO Combine SHORT_NAMES and SPECS
SHORT_NAMES = ['all' : ['ppc64le_linux','s390x_linux','x86-64_linux','ppc64_aix','x86-64_windows','x86-32_windows','x86-64_mac'],
            'aix' : ['ppc64_aix'],
            'aixcm': ['ppc64_aix_cm'],
            'aixuma' : ['ppc64_aix_uma'],
            'aixlargeheap' : ['ppc64_aix_xl'],
            'aixxl' : ['ppc64_aix_xl'],
            ...
            'alinux64' : ['aarch64_linux'], <-------
            'alinux64cm' : ['aarch64_linux_cm'],
        ....
```
But I am wondering why it still failed to locate the image after successful compilation with the file unchanged
```
02:08:48  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDK16aarch64linuxojdk292Personal)
02:08:48  Eclipse OpenJ9 VM (build jep389_ffi_downcall_phase_1_primitive_final-82495c7f7d6, JRE 16 Linux aarch64-64-Bit Compressed References 20210409_1 (JIT enabled, AOT enabled)
02:08:48  OpenJ9   - 82495c7f7d6
02:08:48  OMR      - e0b3f5c8bd4
02:08:48  JCL      - e27a2cbf227 based on jdk-16+36)
02:08:52  Creating support/demos/image/jfc/CodePointIM/CodePointIM.jar
02:08:52  Creating support/demos/image/jfc/Font2DTest/Font2DTest.jar
02:08:52  Creating support/demos/image/jfc/FileChooserDemo/FileChooserDemo.jar
02:08:52  Creating support/demos/image/jfc/SwingSet2/SwingSet2.jar
02:08:52  Creating support/demos/image/jfc/Metalworks/Metalworks.jar
02:08:52  Creating support/demos/image/jfc/SampleTree/SampleTree.jar
02:08:52  Creating support/demos/image/jfc/Notepad/Notepad.jar
02:08:55  Creating support/demos/image/jfc/Stylepad/Stylepad.jar
02:08:55  Creating support/demos/image/jfc/TransparentRuler/TransparentRuler.jar
02:08:55  Creating support/demos/image/jfc/TableExample/TableExample.jar
02:08:55  Creating java.base.jmod
02:08:55  Creating support/demos/image/jfc/J2Ddemo/J2Ddemo.jar
02:09:10  Creating jdk image
02:09:28  Stopping sjavac server
02:09:28  Finished building target 'all' in configuration 'linux-aarch64-server-release'
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Java Version)
[Pipeline] dir
02:09:29  Running in /home/jenkins/workspace/Build_JDK16_aarch64_linux_ojdk292_Personal
[Pipeline] {
[Pipeline] sh
02:09:35  + build/null/images/jdk/bin/java -Xjit -version
02:09:35  /home/jenkins/workspace/Build_JDK16_aarch64_linux_ojdk292_Personal@tmp/durable-8e9991bd/script.sh: 
line 1: build/null/images/jdk/bin/java: No such file or directory  <------------------
```

**Comment by AdamBrousseau** [comment]
jenkins compile aarch64_linux_ojdk292 jdk11

**Comment by AdamBrousseau** [comment]
Build appears to work. Not sure where your build is from. Maybe internal? Which needs to be based on the internal branches due to a diff. The Artifactory upload fails. Not seen that before, should be unrelated to this change.

**Comment by ChengJin01** [comment]
> 
> 
> Build appears to work. Not sure where your build is from. Maybe internal? Which needs to be based on the internal branches due to a diff. The Artifactory upload fails. Not seen that before, should be unrelated to this change.

Yes this is the jenkins personal build from internal. It seems it doesn't work on both case (external & internal builds).
I tried to manually compiled which works good. So there should be something else (whether it is internal or external) in setting which needs to be updated to get this working.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
