### PR TITLE
Remove obsolete -Xdiagnosticscollector option

### LINKED ISSUE #1192: Remove -Xdiagnosticscollector option
-Xdiagnosticscollector just prints a warning. 

`JVMJ9VM138W The -Xdiagnosticscollector option is not supported by this JVM.`

As it is obsolete it should be removed.

### PR DESCRIPTION
**Pull request by pshipton**
All it did was output a warning:
The -Xdiagnosticscollector option is not supported by this JVM.

Fixes #1192
Obsoletes #1595

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Change looks fine once the copyright check is passing

**Comment by DanHeidinga** [comment]
Down to one file needing copyright updates: `runtime/nls/j9vm/j9vm_pl.nls`

**Comment by pshipton** [comment]
Fixed copyright. Set to WIP while I confirm internal testing isn't going to break.

**Comment by pshipton** [comment]
No test issues found, remove WIP.

**Comment by DanHeidinga** [comment]
The travis build succeed which should be sufficient for this PR

**Pull request merged**
