### PR TITLE
Fast path for Reflection.getClassAccessFlags()

### PR DESCRIPTION
**Pull request by gacholio**
Implement an INL version of the native.

[ci skip]

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
jenkins test sanity win jdk8

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk11

**Comment by tajila** [comment]
Do we still need the `JVM_GetClassAccessFlags_Impl` in sunvmi.c?

**Comment by gacholio** [comment]
> Do we still need the `JVM_GetClassAccessFlags_Impl` in sunvmi.c?

The symbol likely has to exist as the existing JNI native links against it. Given how trivial the code is, I would just leave it in as-is.

**Review by tajila — APPROVED** [review]

**Comment by gacholio** [comment]
```
17:08:15  FAILED test targets:
17:08:15  	cmdLineTester_getPid_0
```
I can't see how this could be this change - I suspect the test is just flaky.

**Comment by pshipton** [comment]
This isn't a test we normally see failing intermittently. Running some grinders, each of these is 10x. 1461 ran on the same machine and failed 5/10. 1462 ran on the other Ubuntu 18 machine and failed 5/10 as well. The rest passed. Next I'll try the nightly build from last night.
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1460
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1461
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1462
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1463
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1464

**Comment by pshipton** [comment]
Last night's build passed 10x on ub18-390-2.
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1465

I'll build the latest code delivered today and check it as well.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1466 is failing, so something else has been delivered since last night which caused this regression.

Last night:
OpenJ9: d132a6b
OMR: b38b0b7
OpenJDK11: b608a89

Later build:
19:22:51  OpenJ9   - fb8c08c7db2
19:22:51  OMR      - 5ad82738f7e
19:22:51  JCL      - f7475ea97ee based on jdk-11.0.10+9)

https://github.com/eclipse/openj9/compare/d132a6b...fb8c08c7db2
https://github.com/eclipse/openj9-omr/compare/b38b0b7...5ad82738f7e
https://github.com/ibmruntimes/openj9-openjdk-jdk11/compare/b608a89...f7475ea97ee

**Comment by gacholio** [comment]
Thanks for tracking it down @pshipton

**Comment by gacholio** [comment]
@tajila This is ready to merge.

**Pull request merged**
