### PR TITLE
Enable -XX:+EnableValhalla by default in Valhalla builds

### LINKED ISSUE #11920: Enable valhalla as default in VT build
Currently the `-XX:+EnableValhalla` option needs to be turned on to enable value types in the VT build. Given that there has been more progress the JIT and the interpreter this can be enabled by default.

We can keep the option so it can be used for debugging purposes but we can make `-XX:+EnableValhalla` true by default so it doesn't need to be added in test cases.

We will need to update the option parsing code in jvminit.c to make it default. Also we will need to update the test code in `/openj9/test/functional/Valhalla/playlist.xml` to remove the option.

### PR DESCRIPTION
**Pull request by hangshao0**
Closes #11920

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
With -XX:+EnableValhalla on by default, we seems to see #10365 and #10869 more frequently in `x86-64_linux_vt_standard` builds.

**Comment by tajila** [comment]
@hzongaro @0xdaryl 
> With -XX:+EnableValhalla on by default, we seems to see #10365 and #10869 more frequently in x86-64_linux_vt_standard builds.

If we introduce this change now, it will make the `x86-64_linux_vt_standard` mode unreliable. We could introduce an option (ie. EXTRA_OPTIONS) to the internal personal builds to allow one to append cmdline args such as `-XX:+EnableValhalla` that way you could still test with the JIT enabled for VTs.

What are your thoughts?

**Comment by hzongaro** [comment]
I believe [OMR pull request 5807](https://github.com/eclipse/omr/pull/5807) and [OpenJ9 pull request 11968](https://github.com/eclipse/openj9/pull/11968) will fix the problems reported in issue #10869.  Leo @Leonardo2718, are you able to verify that?

I suspect those changes also fix the problem reported in issue #10365.  Annabelle @a7ehuo, I can't tell from the analysis in that issue whether this problem was also an example of the "late liveness analysis" issue that would also be resolved by Leo's changes.  May I you and/or Leo to check that?

**Comment by a7ehuo** [comment]
>I suspect those changes also fix the problem reported in issue #10365. Annabelle @a7ehuo, I can't tell from the analysis in that issue whether this problem was also an example of the "late liveness analysis" issue that would also be resolved by Leo's changes.

I highly suspect it'd be related to liveness analysis issue. There were two types of missing live local info:
1. The live local info is not copied from the previous blocks to the newly split blocks 
2. New live local info needs to be added to the the newly split blocks due to the split

I'll run the test from  #10365 with Leo's change.

**Comment by a7ehuo** [comment]
I ran `30x` the following two tests locally with Leo's change and JDK16. All passed. 
```
ValueTypeTestsJIT_0:  -Xjit:count=0
ValueTypeTestsJIT_1:  -Xjit:count=1,disableAsyncCompilation
```

**Comment by Leonardo2718** [comment]
#11968 has been merged now, so the issues should have been resolved.

**Comment by tajila** [comment]
Thanks @Leonardo2718

**Comment by tajila** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity,extended xlinuxval jdknext

**Pull request merged**
