### PR TITLE
Add healthcenter sanity test

### PR DESCRIPTION
**Pull request by keithc-ca**
Run `java -Xhealthcenter -version` if the test JDK appears to include support for healthcenter.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins test sanity zlinux jdk8,jdk11

**Comment by llxia** [comment]
I wonder if we can just add it as cmdlinetest in https://github.com/eclipse/openj9/blob/master/test/functional/cmdLineTests/xxargtest/XXArgumentTesting.xml as following:

```
<test id="Verify -Xhealthcenter">
  <exec command="ls healthcenter.properties" />
  <command>$EXE$ -Xhealthcenter -version</command>
  <output type="success" caseSensitive="yes" regex="yes" javaUtilPattern="yes">No such file</output>
  <output type="success" caseSensitive="yes" regex="yes" javaUtilPattern="yes">(java|openjdk) version</output>
  <output regex="no" type="failure">Command-line option unrecognised</output>
  <output type="failure" caseSensitive="no" regex="no">Unhandled Exception</output>
  <output type="failure" caseSensitive="yes" regex="no">Exception:</output>
  <output type="failure" caseSensitive="yes" regex="no">Processing dump event</output>
</test>

```

**Comment by keithc-ca** [comment]
> I wonder if we can just add it as cmdlinetest in XXArgumentTesting.xml as following:
> ```
> <test id="Verify -Xhealthcenter">
>   <command>ls healthcenter.properties && $EXE$ -Xhealthcenter -version</command> // or find
>   <output type="success" caseSensitive="yes" regex="yes" javaUtilPattern="yes">No such file</output>
>   <output type="success" caseSensitive="yes" regex="yes" javaUtilPattern="yes">(java|openjdk) version</output>
>   <output regex="no" type="failure">Command-line option unrecognised</output>
>   <output type="failure" caseSensitive="no" regex="no">Unhandled Exception</output>
>   <output type="failure" caseSensitive="yes" regex="no">Exception:</output>
>   <output type="failure" caseSensitive="yes" regex="no">Processing dump event</output>
> </test>
> ```
We could probably do something like that, but the command would have to be somewhat more involved than above and the case where the properties file is not present would have to be handled properly. Do you think that would be significantly better?

**Comment by llxia** [comment]
I think we can enable the test first. And we can check if https://github.com/eclipse/openj9/pull/12290#issuecomment-806812203 can handle properties not present case properly at a later stage.

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
