### PR TITLE
Pass BUILD_LIST from PBT-All

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Personal builds have the option to enter
  BUILD_LIST but the option was never passed
  along to the Pipeline jobs

[skip ci]

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@vsebe for review

**Comment by AdamBrousseau** [comment]
BUILD_LIST is already passed
here: https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-Any-Platform#L42
here: https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/pipeline-functions#L317
here: https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/pipeline-functions#L319
here: https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/pipeline-functions#L182
and here: https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/pipeline-functions#L204

**Comment by AdamBrousseau** [comment]
@pshipton for mrge

**Comment by pshipton** [comment]
@AdamBrousseau Pls fix the conflict.

**Comment by AdamBrousseau** [comment]
Fixed

**Pull request merged**
