### PR TITLE
Use null test for compressionFlag as a check to see if string is compressed for length, getBytes, hashCode, regionMatches

### PR DESCRIPTION
**Pull request by yanluo7**
Use null test for compressionFlag as a check to see if string is compressed, 
for public APIs length, getBytes, hashCode, regionMatches.

Signed-off-by: Yan Luo <yan_luo@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
@yanluo7 Can you add more details to the description for this change?  Are there performance results to validate this change?

**Comment by yanluo7** [comment]
@DanHeidinga Currently, we check if a String is compressed by checking its count field is non-negative. We can optimize by checking if the static `compressionFlag` field is null instead. Because `StringCompressionFlag` class is only initialized if an uncompressed String is constructed, we can tell there's no uncompressed String objects in the JVM as long as the field is null.
On the JIT side, we can tell the optimizer to generate guarded NOP for these null checks, effectively skipping `(compressionFlag == null || count >= 0)`. When an uncompressed String is constructed, 'StringCompressionFlag' class is initialized and this triggers the JIT to patch all the NOP sites, restoring the `(compressionFlag == null || count >= 0)` check. 
Corresponding JIT change: https://github.com/eclipse/omr/pull/2013

**Comment by yanluo7** [comment]
Using BumbleBench microbenchmark, we measured about 2-3% throughput improvement for `String.hashcode`, `String.equals`, and `String.getBytes(Charset)`.

**Comment by DanHeidinga** [comment]
Thanks for the background @yanluo7.  I see another ~27 of the `enableCompression && count >= 0` checks in String.  Is there a reason to only change the set in the PR?

**Comment by yanluo7** [comment]
@DanHeidinga This is the first batch of public APIs involving this change. Writing and tetsing BumbleBench testcases for each API can take some time, so Andrew and I decided to break all the APIs into batches to commit, so we don't build too much of a change set.

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by pshipton** [comment]
jenkins test sanity

**Comment by andrewcraik** [comment]
@DanHeidinga I'm good with this change - if you are good could you merge now that sanity has passed?

**Comment by andrewcraik** [comment]
@DanHeidinga just needs a Java code review from you I think - sanity is clean and LGTM from me.

**Comment by DanHeidinga** [comment]
The Java code looks fine.  Can you add a comment to the definition of the compressionFlag,
```
	// Singleton used by all String instances to share the compression flag
	private static StringCompressionFlag compressionFlag;
```
to explain that the JIT optimizes based on whether this is null or not and has special recognition to detect / patch when the instance is created?  This helps tie the JIT optimization and java code together for future reviewers & editors of String.

**Comment by andrewcraik** [comment]
Thanks @DanHeidinga - if the only change is the comment then hopefully we don't need another sanity since the last one was clean :)

**Comment by yanluo7** [comment]
Amended the comment to the definition of compressionFlag in String.java.

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux  Running the plinux sanity build as it only takes an ~hour.

**Comment by andrewcraik** [comment]
Sanity clean - I approve the changes and @DanHeidinga has approved them as well. Merging.

**Pull request merged**
