### PR TITLE
Add -Xdump on ClassCastException to osx,xlinux builds

### PR DESCRIPTION
**Pull request by pshipton**
Debugging for #8173, create diagnostic files if the problem occurs again.

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile osx jdk11

**Comment by pshipton** [comment]
jenkins compile osx,xlinux jdk11

**Comment by keithc-ca** [comment]
Is this intended to be temporary?
Will it interfere with tests (that might not tolerate extra output or dumps)?

**Comment by pshipton** [comment]
> Is this intended to be temporary?

Yes, it's intended to help diagnose #8173. Once that problem is resolved, the -Xdump option will no longer be needed.

> Will it interfere with tests (that might not tolerate extra output or dumps)?

I think the environment variable is only set during builds, but let's try a sanity test to confirm.

jenkins test sanity plinux jdk11

**Comment by pshipton** [comment]
jenkins test sanity osx jdk11

**Pull request merged**
