### PR TITLE
Fix typo and related tests

### PR DESCRIPTION
**Pull request by hangshao0**
Signed-off-by: hangshao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by hangshao0** [comment]
Launched a grinder on this change. Will update once the grinder finished.

**Comment by pshipton** [comment]
Added WIP to title until this is ready.

**Comment by hangshao0** [comment]
Something was wrong with the build system. I have manually tested on linux_x86-64_cmprssptrs Java 8. cmdLineTester_SCCommandLineOptionTests_1 passed.

```
TEST TARGETS SUMMARY
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
PASSED test targets:
        cmdLineTester_SCCommandLineOptionTests_1

TOTAL: 2   EXECUTED: 1   PASSED: 1   FAILED: 0   SKIPPED: 1
ALL TESTS PASSED
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
_sanity done
```

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Pull request merged**
