### PR TITLE
Add support for compatibility constants

### PR DESCRIPTION
**Pull request by keithc-ca**
This is part of the solution to eclipse/openj9#12182.

* enhance `StructureReader` to support compatibility constants

* add `superset-constants.dat`
  - a copy of a superset.dat from the first release containing only constants (in canonical form)

* enhance `StructureStubGenerator` to support limiting available constants and compatibility constants
  - rework option parsing
  - use try-with-resources
  - add '-r' option for restricting the set of constants
  - add '-c' option for adding compatibility constants

* remove unnecessary uses of `J9ConstantHelper`

### CODE REVIEW

**Comment by keithc-ca** [comment]
The file `superset-constants.dat` has a format that doesn't permit a copyright notice, hence the copyright check failure.

**Comment by pshipton** [comment]
jenkins test sanity,extended zlinux jdk11

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
Please create a PR for the 0.26 release as well. We'll move the extensions changes when we merge in new openjdk levels so we don't need new PRs there.

**Comment by keithc-ca** [comment]
> Please create a PR for the 0.26 release as well.

See #12212.

**Pull request merged**
