### PR TITLE
Add links to 'info thread' command for '!j9vmthread' and '!stack'

### PR DESCRIPTION
**Pull request by keithc-ca**
First commit: a general cleanup
* avoid raw types
* remove assumption that line separator is '\n'
* use streams to print thread properties

Second commit adds links requested by #5295.

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk8

**Comment by pshipton** [comment]
jenkins test extended plinux jdk8

**Comment by pshipton** [comment]
Internal build testing 413925

**Comment by pshipton** [comment]
Not sure why the travis-ci build failed, but it doesn't seem related to this change.

**Comment by keithc-ca** [comment]
I think the travis failure is due to a problem fixed via ibmruntimes/openj9-openjdk-jdk11#153.

**Pull request merged**
