### PR TITLE
Exclude j9vm.test.invalidclasspath.SetClasspathTest for windows

### PR DESCRIPTION
**Pull request by vsebe**
Issue #680 

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
@smlambert please review, thank you!

**Comment by hangshao0** [comment]
On windows -Xss2048k can be added to the test command line to make the test pass.

**Comment by pshipton** [comment]
@smlambert I see you approved this one but didn't merge it. Any reason not to merge? Do we need a sanity build first?

**Comment by smlambert** [comment]
No, I must have timed out... also saw a red x (travis build fail), and didn't proceed beyond that.  sanity test not required (won't show us much as we have no windows machines in the open at the moment).  Merging now.

**Pull request merged**
