### PR TITLE
Add missing throws CharacterCodingException

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
OpenJDK11 have added throws CharacterCodingException...

**Comment by andrew-m-leonard** [comment]
jenkinx compile pLinux

**Comment by andrew-m-leonard** [comment]
jenkins compile pLinux

**Comment by DanHeidinga** [comment]
jenkins compile pLinux jdk10,jdk8

**Comment by AdamBrousseau** [comment]
Jenkins signed off by check

**Pull request merged**
