### PR TITLE
Remove dup cleanWs command on Win/zOS

### PR DESCRIPTION
**Pull request by AdamBrousseau**
We already to a cleanWs on all platforms in biild_all
See #10834

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@vsebe for review
jenkins compile win jdk11

**Comment by AdamBrousseau** [comment]
Jenkins copyright check

**Comment by pshipton** [comment]
Jenkins copyright check

**Comment by pshipton** [comment]
jenkins compile win jdk11

**Comment by pshipton** [comment]
jenkins copyright check

**Comment by pshipton** [comment]
@AdamBrousseau Could the PR failures be related to the credential ID changes?

**Comment by pshipton** [comment]
jenkins copyright check

**Comment by pshipton** [comment]
jenkins compile win jdk11

**Review by vsebe — APPROVED** [review]

**Review by pshipton — APPROVED** [review]

**Pull request merged**
