### PR TITLE
AArch64: Update build instructions

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds description in the AArch64 section.

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
I need the following PRs to be merged for AArch64 VM to be buildable:
- #3502
- #3559
- #4447
- #4487

**Comment by SueChaplain** [comment]
@knn-k 

A suggestion for your last sentence to help clarify use for the `-Xint` option:

>You will see a warning for `libj9jit29.so` if you don't use the `-Xint` option.

How about "If you don't disable the JIT compiler with the `-Xint` option, you will see a warning for `libj9jit29.so`.

**Comment by knn-k** [comment]
@SueChaplain Thank you for your comment.  I am going to change it following your suggestion.

**Comment by knn-k** [comment]
Removed `--with-noncompressedrefs` from the `configure` options, and added a comment for `Non-compressed references support:` instead, as #4749 has been merged.

**Comment by knn-k** [comment]
Building the runtime with OpenSSL support `--with-openssl=fetched` fails because the build process compiles the OpenSSL library not for aarch64 but x86-64.

**Comment by 0xdaryl** [comment]
@SueChaplain , are you fine with these changes?

**Comment by SueChaplain** [comment]
@0xdaryl - LGTM. Thanks!

**Comment by knn-k** [comment]
I opened #5018 for the issue in building with OpenSSL I mentioned before.

**Comment by knn-k** [comment]
Is there anything blocking this PR from getting merged?

**Pull request merged**
