### PR TITLE
Updated playlist.xml to use jdkVersion+

### PR DESCRIPTION
**Pull request by Yuehan-Lin**
[ci skip]

Signed-off-by: Yuehan-Lin <Yuehan.Lin@ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Please resolve the copyright and IP failure. Thanks.

**Comment by llxia** [comment]
jenkins test sanity all jdk8

**Comment by llxia** [comment]
jenkins test sanity all jdk11

**Comment by llxia** [comment]
jenkins test sanity xlinuxlargeheap jdk11

**Comment by llxia** [comment]
jenkins test extended all jdk11

**Comment by llxia** [comment]
All PR tests passed. The test number is the same or more compared to the previous PR build.

**Comment by llxia** [comment]
With this PR, functional tests in Openj9 are ready to run against future jdk version.

**Comment by smlambert** [comment]
Thanks for this work @Yuehan-Lin @renfeiw and @llxia !  
These kinds of changes really helps us by greatly reducing the need for future changes to playlists.

**Pull request merged**
