### PR TITLE
Add aot builds which set test_flags: 'AOT'

### PR DESCRIPTION
**Pull request by pshipton**
Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
@AdamBrousseau pls review.

**Comment by pshipton** [comment]
jenkins test sanity x86-64_linux_aot jdk8

**Comment by pshipton** [comment]
Seems I've done something wrong , as the test run is failing with `Cannot find key PLATFORM: x86-64_linux_aot in PLATFORM_MAP`.

**Comment by pshipton** [comment]
jenkins test sanity s390x_linux_aot jdk8

**Comment by pshipton** [comment]
jenkins copyright check

**Comment by pshipton** [comment]
jenkins copyright check

**Comment by pshipton** [comment]
Looks better now.

**Review by AdamBrousseau — APPROVED** [review]
Looks like you found the special suffix list. If you want shortnames for pr triggers you can add then in Pipeline-Build-Test-All otherwise it lgtm.

**Comment by pshipton** [comment]
The plan is to add a nightly build, assuming there is enough machine time. But maybe somebody else would want short name, so I'll add them.

The previous PR build shows that testing can be run. https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/5481/

**Comment by pshipton** [comment]
jenkins compile zlinuxaot jdk8

**Comment by pshipton** [comment]
jenkins copyright check

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
