### PR TITLE
Suppress warnings regarding flexible array members

### PR DESCRIPTION
**Pull request by keithc-ca**
This is a prerequisite to merging eclipse/omr#5444.

### CODE REVIEW

**Comment by gacholio** [comment]
jenkins compile win jdk8

**Comment by gacholio** [comment]
@keithc-ca Looks like you may have missed a spot - build failing due to warning 4200.

**Comment by keithc-ca** [comment]
I tested this in conjunction with a fixed version of omr#5444 (see my [comment](https://github.com/eclipse/omr/pull/5444#discussion_r472414565)).

Perhaps the change to `j9nonbuilder.h` needs to wait. Let me give that a spin.

**Comment by keithc-ca** [comment]
Jenkins compile win jdk8

**Pull request merged**
