### PR TITLE
 Move jvmtitests native code to runtime/tests to build automatically

### LINKED ISSUE #252: libjvmtitest.so is missing
This is causing issue https://github.com/eclipse/openj9/issues/238
libjvmtitest.so is an example JVMTI agent used for JVMTI and Attach API tests.
Source is in openj9/test/cmdLineTests/jvmtitests/.

### PR DESCRIPTION
**Pull request by pshipton**
The native code needs to be in the "all" makefile target in order for OpenJ9 to build it.

Fixes #252

### CODE REVIEW

**Comment by pshipton** [comment]
@smlambert fyi

**Comment by pshipton** [comment]
Good idea. Lets see what happens. All the excludes look like extended testing to me.

jenkins test extended plinux jdk8

**Comment by smlambert** [comment]
18:11:36 [Test] PASSED: testAgentLoading
18:11:36 [Test] PASSED: testAttachToOtherProcess
18:11:36 [Test] PASSED: testAttachToSelf
18:11:36 [Test] 
18:11:36 [Test] ===============================================
18:11:36 [Test]     TestSunAttachClasses
18:11:36 [Test]     Tests run: 3, Failures: 0, Skips: 0
18:11:36 [Test] ===============================================

Looks good.

**Comment by smlambert** [comment]
Ignoring travis failure, as is unrelated.

**Pull request merged**
