### PR TITLE
Replace ptrj_t with the standard ptr_t types

### PR DESCRIPTION
**Pull request by dsouzai**
Closes https://github.com/eclipse/openj9/issues/6846

### CODE REVIEW

**Comment by dsouzai** [comment]
Extremely tedious PR I know, but could one of you @fjeremic or @ymanton please review :)

**Comment by fjeremic** [comment]
@dsouzai can we assume you did a global search replace? I loaded your branch and did the opposite replace then compared against master. The diff was nil, so I'm feeling pretty confident about letting the test weed any potential bugs here given the size of the change which is largely mechanical.

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk11

**Comment by dsouzai** [comment]
> can we assume you did a global search replace? 

yeah:

```
[dsouzai@localhost j9]$ pwd
/home/dsouzai/dev/src/openj9/openj9
[dsouzai@localhost j9]$ grep -r 'intptr_t' runtime | wc
   5881   34935  694032
[dsouzai@localhost j9]$ grep -r 'uintptr_t' runtime | wc
   4319   26409  523307
[dsouzai@localhost j9]$ grep -r 'uintptrj_t' runtime | wc
      0       0       0
[dsouzai@localhost j9]$ grep -r 'intptrj_t' runtime | wc
      0       0       0
```

**Comment by dsouzai** [comment]
> Build_JDK11_s390x_linux_xl_Personal — Build FAILED

seems to be a similar to https://github.com/eclipse/openj9/issues/8738

**Pull request merged**
