### PR TITLE
Update consumers of loadAddressConstant API

### PR DESCRIPTION
**Pull request by dchopra001**
loadAddressConstant's definition was recently changed in OMR. This commit updates the consumers of this API in order to conform to the new API definition.

Signed-off-by: Dhruv Chopra <Dhruv.C.Chopra@ibm.com>

### CODE REVIEW

**Comment by dchopra001** [comment]
This PR depends on https://github.com/eclipse/omr/pull/4441

**Comment by dchopra001** [comment]
@ymanton I'll need a review for this as well. 

Note:  eclipse/omr#4441 is needed to properly build and run the tests in this PR.

**Comment by ymanton** [comment]
As discussed you should change the API in OMR to introduce an overloaded function so that we can pick it up in OpenJ9 without breaking existing code, after which we can deal with this PR.

**Comment by dchopra001** [comment]
The OMR change was merged on Friday and is available now. So we can launch PR testing and run this merge this.

**Comment by mpirvu** [comment]
Jenkins test sanity plinux,aix jdk8,jdk11

**Comment by mpirvu** [comment]
I've launched tests only on P because the code that was changes was Power specific.

**Comment by mpirvu** [comment]
All tests have passed, hence merging.

**Pull request merged**
