### PR TITLE
Fixup varHandleMethodTypes in HCR

### PR DESCRIPTION
**Pull request by tajila**
Fixup varHandleMethodTypes in HCR

Signed-off-by: Tobi Ajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
I think this may have been missed in the initial varhandle implementation. Basically what happens is that in the the varhandle methodtype is resolved in the old version of the class. Then we do the in place HCR, so the old version is a new ramClass but retains its ramCP which has the varhandle resolved. However it does not retain the varHandleMethodTypes array so it ends up running invokeVarHandle with NULL MT loaded from varHandleMethodTypes

**Comment by tajila** [comment]
@gacholio please take a look

**Review by gacholio — APPROVED** [review]

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk8

**Comment by gacholio** [comment]
Might this fix #11315 ?

**Comment by tajila** [comment]
I looks like a similar issue, Ill run tests to see if its fixed

**Pull request merged**
