### PR TITLE
Add an entry to support newvalue into CodeGenGPU

### PR DESCRIPTION
**Pull request by Charlmzz**
Add an entry to support newvalue into CodeGenGPU.

Issue: #4028

Signed-off-by: Yiling Han <Yiling.Han@ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
This must depend on an OMR change? If so can you please identify which one?

**Comment by andrewcraik** [comment]
Could you also please make the PR title and message a bit more meaningful so that one doesn't have to read the commit?

**Comment by Charlmzz** [comment]
The change depends on https://github.com/eclipse/omr/pull/4156.

**Comment by andrewcraik** [comment]
This is a simple add and the sanity won't work with the OMR now out of whack so I'm going to merge this now to get an acceptance build going. I have checked the change it is a single line addition at the correct point in the opcode table to make the opcodes in OpenJ9 line up with OMR once again.

**Pull request merged**
