### PR TITLE
Add module access tests

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Add tests to check visibility of types and methods in foreign modules under
various module relationships and access mechanisms.

Note that the new tests need a custom testng control file and cannot use
generaltest.jar.

This re-incorporates these tests which were excluded due to build problems on Windows.

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pdbain-ibm** [comment]
Tested on Linux and Windows.  This commit is essentially equal to commit 937c790a5c348da166ed157f48c5c2dd886cf01c with changes to playlist.xml and build.xml.  The java files are unchanged.

@llxia or @smlambert would you kindly run a sanity and extended test on Windows and Linux.
Thank you.

**Comment by llxia** [comment]
Jenkins test extended win,plinux jdk10

**Comment by llxia** [comment]
Jenkins test sanity win,plinux jdk10

**Comment by llxia** [comment]
Jenkins test sanity win jdk10

**Pull request merged**
