### PR TITLE
Move JAVA_VERSION and JCL_VERSION check in each test project build.xml

### PR DESCRIPTION
**Pull request by llxia**
each test project should have logic to check whether or not its test
material can be compiled against current sdk. Removed the check in
top level build_test.xml and added check in each test project build.xml.

[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Reviewers: @smlambert @sophia-guo

**Comment by smlambert** [comment]
@sophia-guo - I won't merge until you review/comment.  Thanks.

**Comment by llxia** [comment]
We still call `check_sdk` target in internal build. More investigation is needed if we want to remove this target.

**Comment by sophia-guo** [comment]
Internal personal build has set xa platform is a must, so this can be deleted. Agreed do it in a separate PR, which is not a high priority as tooling will need to update too.

**Pull request merged**
