### PR TITLE
Add NODE_NAME to build description

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- For any Compile or Test build
- Also includes PRs

[skip ci]

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins test sanity zlinux jdk8

**Comment by AdamBrousseau** [comment]
Jenkins test sanity zlinux jdk8

**Comment by AdamBrousseau** [comment]
Jenkins compile zlinux jdk8

**Comment by AdamBrousseau** [comment]
Jenkins compile zlinux jdk8

**Comment by AdamBrousseau** [comment]
Jenkins test sanity zlinux jdk8

**Comment by AdamBrousseau** [comment]
Jenkins compile zlinux jdk8

**Comment by AdamBrousseau** [comment]
@vsebe for review

**Comment by AdamBrousseau** [comment]
Because PR builds already have a description, we need to add the `<br/>`. This creates a blank line for builds & tests which do not already have a description. Example https://ci.eclipse.org/openj9/view/Build/job/Build-JDK10-linux_390-64_cmprssptrs/

**Comment by pshipton** [comment]
Can you test if currentBuild.description is empty before adding the `<br/>`?

**Comment by AdamBrousseau** [comment]
Jenkins compile zlinux jdk8

**Comment by AdamBrousseau** [comment]
[Build Job](https://ci.eclipse.org/openj9/view/Sandbox/job/Adam_Build-JDK8-linux_390-64_cmprssptrs/22/)

**Comment by AdamBrousseau** [comment]
Jenkins compile zlinux jdk8

**Comment by AdamBrousseau** [comment]
Jenkins compile zlinux jdk8

**Comment by AdamBrousseau** [comment]
Jenkins compile zlinux jdk8

**Comment by AdamBrousseau** [comment]
Updated function, still works as desired
[Buld job](https://ci.eclipse.org/openj9/view/Sandbox/job/Adam_Build-JDK8-linux_390-64_cmprssptrs/23/)
[PR job](https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK8-linux_390-64_cmprssptrs-OpenJ9/14/)

**Pull request merged**
