### PR TITLE
AArch64: Fix arraylengthEvaluator()

### PR DESCRIPTION
**Pull request by knn-k**
This commit fixes arraylengthEvaluator() for AArch64, changing the
mnemonic for loading the array length from memory.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
What would be the best way to implement this evaluator for AArch64?

(A) No conditional branches / Always two loads (original implementation for AArch64 in #6077)

```
  ldrimmw R1, [B, contiguousSize]
  cmpimmw R1, 0
  ldrimmw R2, [B, discontiguousSize]
  cselw R1, R1, R2, ne
```

(B) Shortest sequence / Branch with contiguous case

```
  ldrimmw R, [B, contiguousSize]
  cbnzw R, doneLabel
  ldrimmw R, [B, discontiguousSize]
doneLabel:
```

(C) Use OOL / p version is similar to this

```
  ldrimmw R, [B, contiguousSize]
  cbzw R, OOLLabel
doneLabel:
  ...

OOLLabel:
  ldrimmw R, [B, discontiguousSize]
  b doneLabel
```

**Comment by 0xdaryl** [comment]
Zero length arrays will be processed in the discontiguous path, and they are not that uncommon.  I would start with "A" until we have reason to change it.

**Comment by 0xdaryl** [comment]
Jenkins test sanity alinux64 jdk11

**Comment by knn-k** [comment]
There is a test failure in https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_Personal_testList_0/40/tapResults/ with `testSCCMLTests1_openj9_1`.  It will be resolved by #10323.

**Pull request merged**
