### PR TITLE
Restore --disable-zip-debug-info for jdk8 Windows builds

### PR DESCRIPTION
**Pull request by keithc-ca**
This depends on ibmruntimes/openj9-openjdk-jdk8#384.

Fixes: #8834.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins compile win jdk8 depends ibmruntimes/openj9-openjdk-jdk8#384

**Comment by pshipton** [comment]
Jenkins compile win32 jdk8

**Comment by pshipton** [comment]
Pls create PRs for this and ibmruntimes/openj9-openjdk-jdk8#384 for the 0.20 branches.

**Comment by keithc-ca** [comment]
> Pls create PRs for this and [ibmruntimes/openj9-openjdk-jdk8#384](https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/384) for the 0.20 branches.

See ibmruntimes/openj9-openjdk-jdk8#385 and #8860.

**Pull request merged**
