### PR TITLE
Update MH.asSpreader tests

### PR DESCRIPTION
**Pull request by fengxue-IS**
Fixes: #7246 

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fengxue-IS** [comment]
@pshipton can you please take a look

**Comment by pshipton** [comment]
lgtm

**Comment by DanHeidinga** [comment]
Jenkins test sanity,extended xlinux jdk8

**Comment by DanHeidinga** [comment]
Jenkins test extended zlinux jdk11

**Comment by fengxue-IS** [comment]
@DanHeidinga The java 11 test failed when JitCount=0, I think the JIT team need to have a similar fix to #7062 done for spreadhandle invoke

**Comment by pshipton** [comment]
@andrewcraik see previous comment

**Comment by DanHeidinga** [comment]
The JIT side of the fix is a straightforward change to the thunkArchetype.  Pulling together a PR now

**Comment by DanHeidinga** [comment]
See https://github.com/eclipse/openj9/pull/7261 as the fix for the JIT-side of the SpreadHandle change

**Comment by pshipton** [comment]
As the test failure should be fixed by #7261, which I've merged, I'll go ahead and merge this as well.

**Comment by pshipton** [comment]
Running some after merge testing to confirm extended testing is good now.
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-All/656/

**Comment by DanHeidinga** [comment]
Thanks @pshipton for helping get all the pieces of this merged!

**Pull request merged**
