### PR TITLE
Clear the JVMTI exception throw flag before reporting event

### PR DESCRIPTION
**Pull request by fengxue-IS**
Fix: #5784 

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
Should there be a test for this? At the very least, I'd like to see some evidence here that something has been fixed.

**Comment by gacholio** [comment]
Maybe show some post-fix results of the provided test in the issue...

**Comment by gacholio** [comment]
I'll let @DanHeidinga comment on the test addition (if we do, it should be in the existing JVMTI test suite). For now I'll launch some testing.

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk11

**Comment by DanHeidinga** [comment]
I'd like to see the test added at the same time even if it's done in a separate PR.

**Comment by fengxue-IS** [comment]
working on creating a jvmti test, will link to this PR once done

**Pull request merged**
