### PR TITLE
WIP: Add correctness checks for certain validations/relocations

### PR DESCRIPTION
**Pull request by dsouzai**
To fix a fundamental issue with the way the AOT relocations/validations are performed (see https://github.com/eclipse/openj9/issues/4135#issuecomment-449504268 for more detail), this PR adds

1. cpIndex bounds checks
2. constant type checks

to
1. inlined special method relocations
2. inlined static method relocations
3. inlined virtual method relocations
4. inlined abstract method relocations
5. inlined interface method relocations
6. class validations
7. field validations

Fixes https://github.com/eclipse/openj9/issues/4135

### CODE REVIEW

**Comment by dsouzai** [comment]
WIP because I haven't test this at all; I opened it to get people's eyes on the fix.

**Comment by dsouzai** [comment]
@pshipton @DanHeidinga @mstoodle @jdmpapin @andrewcraik 

could you guys please take a look and see if everything looks ok?

**Comment by mstoodle** [comment]
Maybe an alternative fix would be to verify that the (rom) constant pool offset in the shared cache that's stored in the relocation record matches the offset of the actual (rom) constant pool for the inlined site?

**Comment by dsouzai** [comment]
Closing this, since these "correctness" checks are unneeded given the discussion in https://github.com/eclipse/openj9/issues/4135

**Pull request closed without merging**
