### PR TITLE
Misc. compiler runtime cleanup

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Formatting cleanup of X86PicBuilder.nasm and X86Unresolveds.nasm
* Remove deprecated `MTUnresolved` code from compiler runtime

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
@ymanton @dsouzai : this is a straightforward cleanup.  Would one of you please review and merge?

**Comment by 0xdaryl** [comment]
I opened #8383 for the PPC LE balanced failure.  It could not have been caused by this PR.

**Comment by dsouzai** [comment]
Merging as @ymanton has also approved.

**Pull request merged**
