### PR TITLE
Consolidate some optimizer trace options

### PR DESCRIPTION
**Pull request by fjeremic**
This PR is a series of commits, similar to that of #9477, which consolidates some of the optimizer trace options. Each commit has as part of the commit message the justification for why the change was made. Some further details on the background for this imitative can be found in #9428.

There is no trace statements removed as part of this PR (except one I think), only the options used to enable some of the tracing has changed.

Issue: #9428

### CODE REVIEW

**Comment by fjeremic** [comment]
Depends on eclipse/omr#5179.

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8 depends eclipse/omr#5179

**Comment by andrewcraik** [comment]
@cathyzhyi could you just check you are happy with the change to the inliner? I think this is looking good.

**Comment by fjeremic** [comment]
Windows failures are due to #9707.

**Comment by cathyzhyi** [comment]
looks good to me as well.

**Comment by pshipton** [comment]
Run an OMR acceptance build.

jenkins test sanity ppc64_aix,x86-64_linux,x86-64_linux_xl,ppc64le_linux,ppc64le_linux_xl,s390x_linux,s390x_linux_xl,x86-64_windows,x86-32_windows,x86-64_mac jdk8,jdk11 depends eclipse/openj9-omr#master

**Comment by pshipton** [comment]
Merging and promoting OMR.

**Pull request merged**
