### PR TITLE
Update getters/setters in CompilationInfo for merging into mast…

### PR DESCRIPTION
**Pull request by a7ehuo**
Update getters/setters in `CompilationInfo` for merging into the `master` branch.

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Comment by a7ehuo** [comment]
@mpirvu This PR matches the changes in PR #6986 for the `master` branch. Updated again. Ready for another review.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
The only failure is the known `cmdLineTester_gcsuballoctests_0 ` test

**Comment by mpirvu** [comment]
The only failure is the known `cmdLineTester_gcsuballoctests_0` test, hence merging.

**Pull request merged**
