### PR TITLE
Call j2iTransition directly from PIC builder on X86

### PR DESCRIPTION
**Pull request by 0dvictor**
Calling `j2iTransition` directly from PIC builder and remove related dead code.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win jdk8,jdk11

**Comment by andrewcraik** [comment]
From the JIT design side of this and looking at the removal I think it looks ok. @gacholio since this is another cleanup to the VM/JIT hookup could you review and approve so I can merge once sanity is clean?

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win jdk8,jdk11

**Comment by 0dvictor** [comment]
The failure is known as https://github.com/eclipse/openj9/issues/4657.

**Comment by 0dvictor** [comment]
Merge conflicts have been resolved.

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win jdk8,jdk11

**Comment by 0dvictor** [comment]
Merge conflicts have been resolved.

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win jdk8,jdk11

**Comment by pshipton** [comment]
@andrewcraik @0dvictor Should this change also be merged to the 0.14 release branch?

**Comment by andrewcraik** [comment]
@pshipton no this is strictly an improvement not a bug fix so we can hold it for 0.15 to maintain the 0.14 stability.

**Pull request merged**
