### PR TITLE
Add code for AArch64 to ProcessorDetection.cpp

### PR DESCRIPTION
**Pull request by knn-k**
This commits adds code for AArch64 to ProcessorDetection.cpp.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
There is only one processor type (`TR_DefaultARM64Processor`) for AArch64 at this point.

**Comment by 0xdaryl** [comment]
Please create an issue to track the work to properly detect the CPU type, and update the TODO with the issue number.

**Comment by knn-k** [comment]
I opened #6637, and updated the comment in the code.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Pull request merged**
