### PR TITLE
Update getPidTest.pl to parse output for PID

### PR DESCRIPTION
**Pull request by ashu-mehra**
Using JVM options like -XX:+UseJITServer can generate additional
output which causes getPidTest.pl to fail incorrectly.
Updated the script to look for PID in the Java process output, and
ignore other messages.

Fixes: #8220

Signed-off-by: Ashutosh Mehra <mehra.ashutosh@ibm.com>

### CODE REVIEW

**Comment by ashu-mehra** [comment]
tested with personal build: https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/73/consoleText

As the above link takes a lot of time to load, adding the output of the test here:
```
[2020-02-04T19:54:39.151Z] ===============================================
[2020-02-04T19:54:39.151Z] Running test cmdLineTester_getPid_0 ...
[2020-02-04T19:54:39.151Z] ===============================================
[2020-02-04T19:54:39.151Z] cmdLineTester_getPid_0 Start Time: Tue Feb  4 11:53:23 2020 Epoch Time (ms): 1580846003626
[2020-02-04T19:54:39.151Z] "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
[2020-02-04T19:54:39.151Z] JVMSHRC005I No shared class caches available
[2020-02-04T19:54:39.151Z] JVMSHRC005I No shared class caches available
[2020-02-04T19:54:39.151Z] cache cleanup done
[2020-02-04T19:54:39.151Z] variation: NoOptions
[2020-02-04T19:54:39.151Z] JVM_OPTIONS: -XX:+UseJITServer -Xcompressedrefs 
[2020-02-04T19:54:39.151Z] { itercnt=1; \
[2020-02-04T19:54:39.151Z] mkdir -p "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../TKG/test_output_15808417998111/cmdLineTester_getPid_0"; \
[2020-02-04T19:54:39.151Z] cd "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../TKG/test_output_15808417998111/cmdLineTester_getPid_0"; \
[2020-02-04T19:54:39.151Z] "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -Xcompressedrefs  -DTESTDIR="/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/runtimemxbeanTests" -DEXE='"/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -Xcompressedrefs ' -DTESTSJARPATH="/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/runtimemxbeanTests/runtimemxbeanTests.jar" -jar "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_tester/cmdlinetester.jar" -config "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/runtimemxbeanTests/getPidTest.xml" -explainExcludes -nonZeroExitWhenError; \
[2020-02-04T19:54:39.151Z]  		if [ $? -eq 0 ] ; then echo ""; echo "cmdLineTester_getPid_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/..; rm -f -r "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../TKG/test_output_15808417998111/cmdLineTester_getPid_0"; else echo ""; echo "cmdLineTester_getPid_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../TKG/test_output_15808417998111/TestTargetResult";
[2020-02-04T19:54:39.151Z] JITServer is currently a technology preview. Its use is not yet supported
[2020-02-04T19:54:39.151Z] *** Starting test suite: getPid test ***
[2020-02-04T19:54:39.151Z] Testing: Compare RuntimeMXBean.getPid() with getting PID from system
[2020-02-04T19:54:39.151Z] Test start time: 2020/02/04 11:53:24 Pacific Standard Time
[2020-02-04T19:54:39.152Z] Running command: perl /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/runtimemxbeanTests/getPidTest.pl "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -Xcompressedrefs  -cp /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Personal/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/runtimemxbeanTests/runtimemxbeanTests.jar GetPid
[2020-02-04T19:54:39.152Z] Time spent starting: 151 milliseconds
[2020-02-04T19:54:39.152Z] Time spent executing: 690 milliseconds
[2020-02-04T19:54:39.152Z] Test result: PASSED
[2020-02-04T19:54:39.152Z] 
[2020-02-04T19:54:39.152Z] 
[2020-02-04T19:54:39.152Z] ---TEST RESULTS---
[2020-02-04T19:54:39.152Z] Number of PASSED tests: 1 out of 1
[2020-02-04T19:54:39.152Z] Number of FAILED tests: 0 out of 1
[2020-02-04T19:54:39.152Z] 
```

**Comment by ashu-mehra** [comment]
fyi - @mpirvu 
@llxia can you please review this pr.

**Comment by llxia** [comment]
jenkins test sanity all jdk11

**Comment by llxia** [comment]
jenkins test sanity all jdk11

**Pull request merged**
