### PR TITLE
Remove hardcoded jobs=8 from AIX configure options

### PR DESCRIPTION
**Pull request by AdamBrousseau**
[skip ci]

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Depends #5787 to be properly tested

**Comment by AdamBrousseau** [comment]
jenkins compile aix jdk11

**Comment by AdamBrousseau** [comment]
jenkins compile aix jdk11

**Comment by AdamBrousseau** [comment]
Guess that fix hasn't gone in yet
```
00:04:53.113  Build performance summary:
00:04:53.113  * Cores to use:   2
00:04:53.113  * Memory limit:   8192 MB
```

**Comment by AdamBrousseau** [comment]
jenkins compile aix jdknext

**Comment by AdamBrousseau** [comment]
jdknext (13+)
```
00:04:38.191  Build performance summary:
00:04:38.191  * Cores to use:   8
00:04:38.191  * Memory limit:   8192 MB
```
@andrew-m-leonard Is this correct that your change was delivered to HEAD and not backported to 12 or less?

**Comment by andrew-m-leonard** [comment]
It's not been backported to jdk12or less yet...: https://github.ibm.com/runtimes/openjdk-contribution/issues/845

**Comment by AdamBrousseau** [comment]
jenkins compile aix jdk8,jdk11,jdk13,jdknext

**Comment by AdamBrousseau** [comment]
jenkins compile aix jdk8

**Comment by AdamBrousseau** [comment]
8
```
14:56:51  * Cores to use:   2
```

**Comment by andrew-m-leonard** [comment]
The fix is in jdk8u232-b05 this is in extensions "master" as of friday but i've got a merge conflict to resolve...

**Comment by andrew-m-leonard** [comment]
@AdamBrousseau merge conflict resolved, it's now in jdk8 openj9-staging:
https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/eba1c8927e3a8cf62013f45851b0ee88536a23c7

**Comment by andrew-m-leonard** [comment]
acceptance job running: https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK8-Acceptance/20/

**Comment by AdamBrousseau** [comment]
jenkins compile aix jdk8

**Comment by AdamBrousseau** [comment]
jenkins compile aix jdk8

**Comment by AdamBrousseau** [comment]
I think this can be delivered now.

**Comment by pshipton** [comment]
jdk8 `* Cores to use:   7`

**Comment by pshipton** [comment]
Is it expected for jdk8 to find 7 cores and not 8?

**Comment by AdamBrousseau** [comment]
@andrew-m-leonard can you comment on the 7 vs 8 cores to use?

**Comment by AdamBrousseau** [comment]
Is the calculation the same for 8 as the other versions? The others all calculated 8. Is the ram number based on total ram or available ram? If there former, perhaps a cleanup and rerun could help find 8.

**Comment by AdamBrousseau** [comment]
jenkins compile aix jdk8,jdk11

**Comment by AdamBrousseau** [comment]
jenkins compile aix jdk11

**Comment by AdamBrousseau** [comment]
jenkins compile aix jdk11

**Comment by AdamBrousseau** [comment]
@andrew-m-leonard I still see jdk11 getting 8 cores vs jdk8 using 7. There must be something different in 8. Is this expected or is there a bug in the logic?

**Comment by andrew-m-leonard** [comment]
Yes the logic is "slightly" different:
jdk8:
```
    # Approximate memory in GB, rounding up a bit.
    memory_gb=`expr $MEMORY_SIZE / 1100`
```
jdk11:
```
   # Approximate memory in GB.
    memory_gb=`expr $MEMORY_SIZE / 1024`
```

```
    # Pick the lowest of memory in gb and number of cores.
    if test "$memory_gb" -lt "$NUM_CORES"; then
      JOBS="$memory_gb"
    else
      JOBS="$NUM_CORES"
    fi
```

**Comment by andrew-m-leonard** [comment]
I actually think the jdk8 "1100" factor is slightly better, as we've seen instance at Adopt of the new calculated jobs causing resource exhaustion and we've had to override it to limit it...

**Comment by AdamBrousseau** [comment]
On OpenJ9 farm we've always hardcoded jobs=8. I don't believe we have resource problems but we get our machines from a different source which could contribute to the difference. I also don't see a noticeable compile time difference between 7 and 8 on jdk8 (~48min). 
@pshipton any comments or can this be merged?

**Comment by pshipton** [comment]
If there isn't a compile time difference then I'm good with it.

**Comment by pshipton** [comment]
Strange, I thought I had merged this.

**Pull request merged**
