### PR TITLE
Remove gRPC code from the codebase

### PR DESCRIPTION
**Pull request by dmitry-ten**
There are no reasonable use cases for gRPC,
since raw sockets can do everything that gRPC
can, but has much better CPU consumption.
Thus, all code related to gRPC can be removed.

### CODE REVIEW

**Comment by dmitry-ten** [comment]
@mpirvu this is ready for review.

**Comment by dmitry-ten** [comment]
I tested that it works.
There is a couple of mentions of gRPC in the docs, will remove them.

**Comment by dmitry-ten** [comment]
Done.

**Comment by mpirvu** [comment]
Could you please fix the copyright message for 
```
16:34:02  doc/compiler/jitaas/Sockets.md
16:34:02  	IBM Copyright date appears to be incorrect
[Pipeline] echo
```

**Comment by dmitry-ten** [comment]
Done. Could you restart copyright check?

**Pull request merged**
