### PR TITLE
Remove unused JIT debug stats

### PR DESCRIPTION
**Pull request by 0xdaryl**
The JIT debug flag `-Xjit:stats` is only available in a debug build and has not
been useful for many years.  Remove it and all the logic it enables.  This includes
removing a number of now unused data counter fields in the JitConfig struct.

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@mpirvu, I'd appreciate a review and merge please.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
@andrewcraik @0dvictor : do you have any opinions on the debug monenter stats this PR removes?

**Comment by 0xdaryl** [comment]
The Jenkins builds are not debug builds.  I will try one manually on x86 to verify it builds.

**Comment by 0xdaryl** [comment]
Jenkins test sanity xlinux jdk11

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

Re-running tests after rebase.

**Comment by 0xdaryl** [comment]
I can confirm that a DEBUG JIT builds successfully on x86 for JDK11 with this PR.

The CI builds for this PR are having a hard time today.  I will rebase, push again, and then restart them.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by mpirvu** [comment]
The test failures have nothing to do with this PR, hence merging.

**Pull request merged**
