### PR TITLE
Reduce use of OMR_HOST_OS

### PR DESCRIPTION
**Pull request by keithc-ca**
* prefer flags over string comparisons

Flag            | Replaces
:---            | :-------
OMR_OS_AIX      | OMR_HOST_OS STREQUAL "aix"
OMR_OS_BSD      | OMR_HOST_OS STREQUAL "bsd"
OMR_OS_LINUX    | OMR_HOST_OS STREQUAL "linux"
OMR_OS_OSX      | OMR_HOST_OS STREQUAL "osx"
OMR_OS_WINDOWS  | OMR_HOST_OS STREQUAL "win"
OMR_OS_ZOS      | OMR_HOST_OS STREQUAL "zos"

See https://github.com/eclipse/omr/blob/master/cmake/modules/OmrDetectSystemInformation.cmake#L160-L180.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins copyright check

**Review by fjeremic — APPROVED** [review]

**Comment by fjeremic** [comment]
Feel free to launch the tests once the copyright is fixed. I can merge after they're done and succeed.

**Comment by keithc-ca** [comment]
Jenkins copyright check

**Comment by keithc-ca** [comment]
Jenkins test sanity aix,osx,plinux,xlinux,zlinux,win jdk11

**Review by pshipton — APPROVED** [review]

**Review by dnakamura — APPROVED** [review]

**Pull request merged**
