### PR TITLE
Enable NewROMCreationAfterModifyingExistingClassTest test

### PR DESCRIPTION
**Pull request by sophia-guo**
[ci skip]

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
@hangshao0 FYI

**Comment by llxia** [comment]
Jenkins test sanity plinux jdk9

**Comment by llxia** [comment]
Jenkins test sanity plinux jdk9

**Comment by llxia** [comment]
Jenkins test sanity plinux jdk9

**Pull request merged**
