### PR TITLE
Disable AutoSIMD of loops with asyncchecks

### PR DESCRIPTION
**Pull request by IBMJimmyk**
Changes default behavior for AutoSIMD under SPMDParallelizer to bail out if
there are asynccheck nodes in the loop.

Currently, calling out to handle asyncchecks does not interact well with
vector registers. It requires all vector registers to be spilled before the
call out. This is now avoided by AutoSIMD bailing out if there are asyncchecks
in the loop.

This also adds a new TR_enableAutoSIMDSkipAsynccheck env variable. When
TR_enableAutoSIMDSkipAsynccheck is set, AutoSIMD will remove asynccheck nodes
in a loop when parallelzing them instead of bailing out.

In both cases, asynccheck nodes should no longer appear inside a vectorized
loop.

Closes: #11125
Signed-off-by: jimmyk <jimmyk@ca.ibm.com>

### CODE REVIEW

**Comment by IBMJimmyk** [comment]
@gita-omr You might want to look at this.

I'm currently in the middle of running some final tests but things look good so far so I opened a WIP PR so others can take a look.

**Comment by gita-omr** [comment]
Definitely, will take a look soon.

**Review by gita-omr — APPROVED** [review]

**Comment by gita-omr** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by andrewcraik** [comment]
The main danger of this is that we could get stuck in a long running loop where we would not yield to the VM to allow the GC to run or other book keeping activities to take place. I am hesitant to say that we should merge this as is without even an env var to revert the behaviour. FYI @vijaysun-omr . I think at a minimum there needs to be a way to stop this from happening. I don't know if the danger is sufficient to warrant not doing this by default but putting it under something like -Xaggressive - thoughts @vijaysun-omr ? I am inclined to say at least having the ability to disable the remove is necessary for debugging and support.

**Comment by gita-omr** [comment]
Another option is not to vectorize loops with asynchecks, at least until we find a better solution for spilling vector registers around them.

**Comment by vijaysun-omr** [comment]
Is spilling all the vector registers before the async check call out occurs (I assume quite an infrequent event) really going to affect performance measurably ? i.e. what is the expected performance impact of this change (e.g. how much % in which application) ?

**Comment by gita-omr** [comment]
The problem with current implementation is:

1) On Intel vector registers are not spilled around asyncheck at all, which causes a bug
2) On AIX they are spilled even if a call to the helper does not occur, which is too expensive

Both are fixable, but it will take some time to do it. We will open a separate issue for that, so this PR will be a temporary solution.

**Comment by vijaysun-omr** [comment]
Okay, as long as those underlying issues are in fact worked on (since they do seem like bugs that would surface again wrt the Vector api support) then a workaround can be delivered. I'll ask @gita-omr question from before, i.e. why not skip vectorizing loops with async checks. Note there is a versioning transformation that gets rid of async checks from loops and if that did not kick in in some important test case that you are running, you should look into why.

**Comment by gita-omr** [comment]
> I'll ask @gita-omr question from before, i.e. why not skip vectorizing loops with async checks. Note there is a versioning transformation that gets rid of async checks from loops and if that did not kick in in some important test case that you are running, you should look into why.

I agree. I think we should do the following:

1) as a part of this API stop vectorizing loops that have asynchecks in them
2) check why asyncheck was not removed by LoopVersioner in the test case in which we saw the bug
3) open a new issue for vector register spills around asynchecks and re-enable them with autoSIMD when it's fixed
4) handle vector spills properly around any calls as part of the Vector API work

**Comment by gita-omr** [comment]
@andrewcraik I think we discussed that before... but maybe you can remind me once again why LoopVersioner would not remove asynccheck out of a loop?

**Comment by IBMJimmyk** [comment]
I changed the default behavior for AutoSIMD under SPMDParallelizer to bail out if there are asynccheck nodes in the loop.

I also added a new `TR_enableAutoSIMDSkipAsynccheck` env variable. When `TR_enableAutoSIMDSkipAsynccheck` is set AutoSIMD will remove asynccheck nodes in a loop when parallelzing them.

I then rebased my change on a more recent master branch.

How do these changes look and are there any other changes that should be made?

**Comment by gita-omr** [comment]
Thanks! I will take a look soon.

**Review by gita-omr — APPROVED** [review]

**Comment by gita-omr** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by IBMJimmyk** [comment]
I flattened the two commits into a single commit and updated the commit message. Everything should be good now.

**Comment by gita-omr** [comment]
Please also change the PR title: we don't remove but disable...

**Pull request merged**
