### PR TITLE
Use consistent line-endings

### PR DESCRIPTION
**Pull request by keithc-ca**
Remove the few stray CRs at the ends of lines.
These are the only two files I found with this property.

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins test sanity

**Comment by genie-openj9** [comment]
Can one of the admins verify this patch?

**Comment by genie-openj9** [comment]
Can one of the admins verify this patch?

**Comment by AdamBrousseau** [comment]
Jenkins test sanity

**Comment by AdamBrousseau** [comment]
Jenkins test sanity plinux

**Pull request merged**
