### PR TITLE
Improve jextract for ELF core files

### PR DESCRIPTION
**Pull request by keithc-ca**
* use any FILE notes to help locating shared libraries, etc.

* significant clean-up
  - avoid using raw types
  - fix NLS warnings
  - close files when no longer needed

Issue: #9549.

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity,extended xlinux,plinux,zlinux jdk15

**Comment by pshipton** [comment]
This doesn't seem to change anything. On my fyre machine I got the most recent plinux jdk15 nightly build from Adopt, created a core file with `-Xdump:system:events=vmstop`. Run jdmpview and `info mod`, most libraries show `<no section information>`. Took the PR build from here, run jdmpview on the same core, and got the same output.

**Comment by pshipton** [comment]
Since the title is `Improve jextract` I tried jextract and do see an improvement. 
Original
```
Warning:  Could not find file "libgcc_s.so.1" for inclusion in archive
Warning:  Could not find file "libnet.so" for inclusion in archive
Warning:  Could not find file "libjava.so" for inclusion in archive
Warning:  Could not find file "ld64.so.2" for inclusion in archive
Warning:  Could not find file "libzip.so" for inclusion in archive
Warning:  Could not find file "librt.so.1" for inclusion in archive
Warning:  Could not find file "libm.so.6" for inclusion in archive
Warning:  Could not find file "libz.so.1" for inclusion in archive
Warning:  Could not find file "libjclse29.so" for inclusion in archive
Warning:  Could not find file "libj9zlib29.so" for inclusion in archive
Warning:  Could not find file "libdl.so.2" for inclusion in archive
Warning:  Could not find file "libpthread.so.0" for inclusion in archive
Warning:  Could not find file "libnss_nis.so.2" for inclusion in archive
Warning:  Could not find file "libj9dmp29.so" for inclusion in archive
Warning:  Could not find file "libj9trc29.so" for inclusion in archive
Warning:  Could not find file "libc.so.6" for inclusion in archive
Warning:  Could not find file "libjimage.so" for inclusion in archive
Warning:  Could not find file "libjvm.so" for inclusion in archive
Warning:  Could not find file "linux-vdso64.so.1" for inclusion in archive
Warning:  Could not find file "libj9vm29.so" for inclusion in archive
Warning:  Could not find file "libjli.so" for inclusion in archive
Warning:  Could not find file "libj9prt29.so" for inclusion in archive
Warning:  Could not find file "libnss_compat.so.2" for inclusion in archive
Warning:  Could not find file "libomrsig.so" for inclusion in archive
Warning:  Could not find file "libj9hookable29.so" for inclusion in archive
Warning:  Could not find file "libj9vrb29.so" for inclusion in archive
Warning:  Could not find file "libnsl.so.1" for inclusion in archive
Warning:  Could not find file "libj9thr29.so" for inclusion in archive
Warning:  Could not find file "libj9gc29.so" for inclusion in archive
Warning:  Could not find file "libj9shr29.so" for inclusion in archive
Adding "bin/java" (found at "/home/pete/infomod/jdk-15+36/bin/java")
Warning:  Could not find file "libnio.so" for inclusion in archive
Warning:  Could not find file "libnss_files.so.2" for inclusion in archive
Warning:  Could not find file "libj9jvmti29.so" for inclusion in archive
```

With the fix
```
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libj9jvmti29.so"
Warning:  Could not find file "ld64.so.2" for inclusion in archive
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libj9shr29.so"
Adding "/home/pete/infomod/jdk-15+36/lib/libzip.so"
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libj9thr29.so"
Adding "/home/pete/infomod/jdk-15+36/lib/server/libjvm.so"
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libj9hookable29.so"
Warning:  Could not find file "librt.so.1" for inclusion in archive
Warning:  Could not find file "libm.so.6" for inclusion in archive
Warning:  Could not find file "libz.so.1" for inclusion in archive
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libj9prt29.so"
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libj9vm29.so"
Warning:  Could not find file "libdl.so.2" for inclusion in archive
Warning:  Could not find file "libpthread.so.0" for inclusion in archive
Adding "/home/pete/infomod/jdk-15+36/lib/libjava.so"
Adding "/home/pete/infomod/jdk-15+36/lib/libjli.so"
Adding "/home/pete/infomod/jdk-15+36/lib/libnet.so"
Warning:  Could not find file "libnss_nis.so.2" for inclusion in archive
Warning:  Could not find file "libc.so.6" for inclusion in archive
Warning:  Could not find file "linux-vdso64.so.1" for inclusion in archive
Adding "/home/pete/infomod/jdk-15+36/lib/libnio.so"
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libj9zlib29.so"
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libj9dmp29.so"
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libjvm.so"
Warning:  Could not find file "libnss_compat.so.2" for inclusion in archive
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libj9trc29.so"
Adding "/lib/powerpc64le-linux-gnu/libgcc_s.so.1"
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libj9gc29.so"
Adding "libnsl.so.1" (found at "/lib/powerpc64le-linux-gnu/libnsl.so.1")
Adding "bin/java" (found at "/home/pete/infomod/jdk/bin/java")
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libj9vrb29.so"
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libomrsig.so"
Adding "/home/pete/infomod/jdk-15+36/lib/libjimage.so"
Adding "libnss_files.so.2" (found at "/lib/powerpc64le-linux-gnu/libnss_files.so.2")
Adding "/home/pete/infomod/jdk-15+36/lib/compressedrefs/libjclse29.so"
```

It found all the java libraries, and some of the system libraries, but not all. 

I can merge this "improvement", but not with the `Fixes: #9549.`

**Comment by pshipton** [comment]
Tried it on an OpenJ9 cent7 machine as well (cent7-ppcle-3), where it found all the java libraries, but none of the system libraries.

**Comment by keithc-ca** [comment]
On Linux x86 the only file not found is `linux-vdso.so.1` - I'm not sure it's worth the special treatment to find that shared library. (On my system, I think it resolves to `/lib/modules/4.15.0-117-generic/vdso/vdso64.so`.)

On ppc64le, things like `libc.so.6` are not found because the `FILE` note only mentions the file `/lib/powerpc64le-linux-gnu/libc-2.23.so` which is what you get by resolving the symbolic link `/lib/powerpc64le-linux-gnu/libc.so.6`. That could be fixed by building a mapping that gives the soname of loaded shared libraries and using it to identify the desired files. The names in the zip file need to use the soname so `jdmpview` can find them, so we may need to make the assumption that there won't be two libraries (ignoring symbolic links) in the same directory with the same soname.

I'll remove the 'fixes' part of the description and work on a separate pull request to make that next improvement.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
