### PR TITLE
enable TestCollisionResilientHashtable in DDR_Test

### PR DESCRIPTION
**Pull request by OscarQQ**
related issue: https://github.com/eclipse/openj9/issues/1511

Signed-off-by: Yixin Qian <Yixin.Qian@ibm.com>

### CODE REVIEW

**Comment by OscarQQ** [comment]
| Build       | Platform           | Java Version  | JDK Impl |
|:-------------:|:-------------:|:-----:|:-----------:|
| Grinder/8733     | ppc64le_linux | 8 | openj9|
| Grinder/8734     | s390x_linux      |   8 | openj9|
| Grinder/8736 | x86-64_linux      |    8 | openj9|
| Grinder/8738 | x86-64_windows      |    8 | openj9|
| Grinder/8739 | x86-64_mac      |    8 | openj9|
| Grinder/8755 | ppc64_aix     |    8 | openj9|
| Grinder/8747     | ppc64le_linux | 8 | IBM|
| Grinder/8748     | s390x_linux      |   8 | IBM|
| Grinder/8749 | x86-64_linux      |    8 | IBM|
| Grinder/8750 | x86-64_windows      |    8 | IBM|
| Grinder/8751 | s390x_zos     |    8 | IBM|
| Grinder/8758 | ppc64_aix     |    8 | IBM|
| Grinder/8760     | ppc64le_linux | 11 | openj9|
| Grinder/8761     | s390x_linux      |   11 | openj9|
| Grinder/8763 | x86-64_linux      |   11 | openj9|
| Grinder/8764 | x86-64_windows      |    11 | openj9|
| Grinder/8768 | x86-64_mac      |    11 | openj9|
| Grinder/8767 | ppc64_aix     |   11 | openj9|

**Comment by OscarQQ** [comment]
FYI @llxia

**Comment by OscarQQ** [comment]
| Build       | Platform           | Java Version  | JDK Impl |
|:-------------:|:-------------:|:-----:|:-----------:|
| Grinder/8790     | ppc64le_linux | 8 | IBM|
| Grinder/8791     | s390x_linux      |   8 | IBM|
| Grinder/8792 | x86-64_linux      |    8 | IBM|
| Grinder/8793 | x86-64_windows      |    8 | IBM|
| Grinder/8794 | s390x_zos     |    8 | IBM|
| Grinder/8795 | ppc64_aix     |    8 | IBM|

**Comment by llxia** [comment]
jenkins test extended all jdk8,jdk11

**Pull request merged**
