### PR TITLE
Disable vmcheck test on MacOS temporarily

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Disable until https://github.com/eclipse/openj9/issues/4279 is fixed.

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pdbain-ibm** [comment]
FYI @llxia @pshipton 
This test runs on my Mac and on other platforms.  Excluding the test while I investigate.

**Comment by llxia** [comment]
jenkins test extended osx jdk11

**Comment by pshipton** [comment]
This test only needs to be excluded for jdk8. It wasn't failing or hanging on jdk11. Is that possible?

**Comment by pshipton** [comment]
Meanwhile I'll run a jdk8 build so we can see how that stands without this test.

**Comment by pshipton** [comment]
jenkins test extended osx jdk8

**Comment by llxia** [comment]
jdk8 failed at git fetch
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK8-osx_x86-64_cmprssptrs-OpenJ9/6/console

Going to rerun jdk8

**Comment by llxia** [comment]
jenkins test extended osx jdk8

**Comment by llxia** [comment]
> This test only needs to be excluded for jdk8. It wasn't failing or hanging on jdk11. Is that possible?


yes, we can use `latest_exclude_8.txt` to exclude the TestNG test only for jdk8. Since `testvmcheck` is using testNG, so we should be able to use it.
https://github.com/eclipse/openj9/blob/master/test/TestConfig/resources/excludes/latest_exclude_8.txt

I initially suggested playlist.xml because it is the easiest way to do temporary exclude. But yes, it will exclude both jdk11 and jdk8 on osx in this case.

**Comment by pdbain-ibm** [comment]
I hope to have a fix for this today.  If so, I will close this PR.

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9/issues/4316 for the jdk8 extended test failure.

**Comment by pdbain-ibm** [comment]
Testing the fix.  Won't need this.

**Pull request closed without merging**
