### PR TITLE
remove unused target dist_functional in build.xml

### PR DESCRIPTION
**Pull request by OscarQQ**
Signed-off-by: Yixin Qian <Yixin.Qian@ibm.com>

### CODE REVIEW

**Comment by OscarQQ** [comment]
Grinder:  Internal/Grinder/14350/
Vmfarm: build_info.php?build_id=468007 extended.  
                build_info.php?build_id=468009 sanity

**Comment by OscarQQ** [comment]
@renfeiw @llxia

**Review by renfeiw — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
jenkins test sanity,extended xlinux jdk8,jdk11

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
