### PR TITLE
Map  and test -XX:MaxHeapSize and -XX:InitialHeapSize

### PR DESCRIPTION
**Pull request by pshipton**
Map -XX:MaxHeapSize= to -Xmx
-XX:InitialHeapSize= to -Xms

Issue #2834
Doc issue https://github.com/eclipse/openj9-docs/issues/96

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
Create https://github.com/eclipse/openj9/issues/3092 for the travis failure, which seems unrelated to this change.

**Comment by pshipton** [comment]
jenkins compile xlinux jdk9

**Comment by pshipton** [comment]
jenkins compile xlinux jdk10

**Comment by pshipton** [comment]
Wierd errors compiling jdk9+. I will rebase this when I get a chance, and retry the jdk9+ compile

**Comment by pshipton** [comment]
jenkins compile jdk11 xlinux

**Comment by pshipton** [comment]
jenkins compile xlinux jdk11

**Comment by pshipton** [comment]
Rebasing didn't help, I'm guessing implementing -XX:ThreadStackSize is causing the problem. I found the following in the output but not sure if this is where things are going wrong.
```
checking flags for boot jdk java command for big workloads...  -Xms64M -Xmx1600M -XX:ThreadStackSize=1536
checking flags for bootcycle boot jdk java command for big workloads... -Xms64M -Xmx1600M -XX:ThreadStackSize=1536
```

**Comment by pshipton** [comment]
-XX:ThreadStackSize is supposed to take a size in KB, its not equivalent to -Xss.

**Comment by pshipton** [comment]
The -XX:ThreadStackSize value is in KB, i.e. the value specified is multiplied by 1024.

**Comment by AdamBrousseau** [comment]
Jenkins copyright check

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8,jdk11

**Comment by pshipton** [comment]
@DanHeidinga ready for review

**Pull request merged**
