### PR TITLE
Revert "Merge pull request #2245 from pdbain-ibm/jar"

### PR DESCRIPTION
**Pull request by AdamBrousseau**
This reverts commit 49d6e21edb16ebc1a075ab2928a0c613c3bafc9a, reversing
changes made to a934bafb5a8ce637674000a21756f3f86cf7b7a6.

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins test sanity zlinux jdk10

**Comment by AdamBrousseau** [comment]
Jenkins test sanity zlinux jdk10

**Comment by DanHeidinga** [comment]
@AdamBrousseau Why do you want to revert this?

**Comment by AdamBrousseau** [comment]
We (@llxia) suspect it may be the cause of the recent slowness of the jdk10 zlinux sanity builds. I will open an issue with the details.

**Comment by AdamBrousseau** [comment]
parent #2329

**Pull request closed without merging**
