### PR TITLE
Disable harmony by default

### PR DESCRIPTION
**Pull request by pdbain-ibm**
If required, opt_harmony can be forced on vi the command line UMA option.

Issue: https://github.com/eclipse/openj9/issues/529

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Is this the last change required for the issue?

**Comment by pdbain-ibm** [comment]
I believe this removes substantially all references to Harmony from OpenJ9 builds.  IBM SDKs will still include Harmony.

**Comment by pshipton** [comment]
What I meant was, do we want to keep the issue open after this is merged? To answer my own question, when Harmony is not included the list of port library socket APIs can be reduced, and this could be done under the same Issue.

**Comment by pdbain-ibm** [comment]
I concur that we can keep the issue open to cover other Harmony-related changes.

**Pull request merged**
