### PR TITLE
Check for null source reference for ArrayStoreCHK to value type array

### PR DESCRIPTION
**Pull request by hzongaro**
In prototype support for value types, the `AASTORE` bytecode will throw a `NullPointerException` if the source operand is a null reference, and the component type of the array being stored to a value type.  This change implements the required run-time checking for that situation on x86.

### CODE REVIEW

**Comment by hzongaro** [comment]
Andrew @andrewcraik, may I ask you to review this change?

Note that this change is interdependent with [OMR pull request #5203](https://github.com/eclipse/omr/pull/5203), but as the changes resulting from the two pull requests only have effect when value type support is enabled, the order in which they are merged should not matter.

**Comment by hzongaro** [comment]
I'm not sure why the [copyright check](https://ci.eclipse.org/openj9/job/PullRequest-CopyrightCheck-OpenJ9/24812/) is failing - it appears to be checking many files unaffected by this pull request.

**Comment by andrewcraik** [comment]
So silly question - could we do this in lowering in trees so that we don't have to do the same change on every codegen? Otherwise it seems reasonable...

**Comment by hzongaro** [comment]
> could we do this in lowering in trees
Thanks, Andrew.  I will try it out.

**Comment by hzongaro** [comment]
Dropping this version in favour of pull request #10034

**Pull request closed without merging**
