### PR TITLE
Clean up deprecated code resulting from migrating to a unified assembler across x86

### PR DESCRIPTION
**Pull request by nbhuiyan**
This PR removes the MASM assembly files and cleans up the dual (or triple, if you want to count masm2gas) assembler solutions that existed during the transition period.

Closes: #3148

### CODE REVIEW

**Comment by nbhuiyan** [comment]
@0xdaryl ready for review

**Comment by 0xdaryl** [comment]
Jenkins test sanity win,xlinux,xlinuxlargeheap jdk11

**Comment by 0xdaryl** [comment]
Jenkins test sanity win32 jdk8

**Comment by 0xdaryl** [comment]
Changes look reasonable to me.  One unfortunate consequence is that we lose the history on the deleted assembly files without doing a bit of git work to dig it out.  However, this probably isn't such a big deal in practice because there isn't much of a history on these assembly files in the 1.5 years this code has been open sourced.

@0dvictor , I'd appreciate a +1 from you too.

**Comment by 0dvictor** [comment]
Changes look good to me. I totally agree deleting these deprecated files; they are slowly out-of-sync and likely stop work in the future. Despite the short history of these files, all histories are still in git though it takes more effort retrieving it. I don't anticipate frequent need of these histories.

**Comment by 0xdaryl** [comment]
Jenkins test sanity plinux,zlinux jdk11

**Pull request merged**
