### PR TITLE
Enable more specs for PPC and PPC LE

### PR DESCRIPTION
**Pull request by vsebe**
[ci skip]

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
@jdekonin @pshipton please review

**Comment by vsebe** [comment]
@llxia please review

**Comment by pshipton** [comment]
lgtm

btw, unrelated to this change, do the obsolete _purec configs need to stick around, or could they be removed?

**Comment by llxia** [comment]
> unrelated to this change, do the obsolete _purec configs need to stick around, or could they be removed?

I have the same question. I would like to clean up ottawa.csv and remove the unused specs (i.e., _purec, _hrt, _cloud, _gcnext). This is unrelated to this PR. I can open a separate issue if needed.

**Comment by vsebe** [comment]
@pshipton - Please merge this PR. The clean up of the obsolete specs would go into another PR.

**Pull request merged**
