### PR TITLE
Properly register assumptions on mergedWithOSRGuard

### PR DESCRIPTION
**Pull request by liqunl**
In commiting virtual guards, mergedWithOSRGuard is not handled
correctly, resulting in some guards of this kind always be patched at
compile time.

Fixes: #2475

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
Will remove `WIP: ` when all testing is done. @cathyzhyi Can you review?

**Comment by cathyzhyi** [comment]
LGTM

**Comment by liqunl** [comment]
Change has been fully tested.

**Comment by liqunl** [comment]
@pshipton Can we get a jenkins build for this PR?

**Comment by DanHeidinga** [comment]
@andrewcraik @fjeremic @vijaysun-omr Can a JIT committer handle the review and merging of this PR?  Getting it addressed is a high priority for the 0.9.0 release branch refresh.

**Comment by fjeremic** [comment]
Approved based on @cathyzhyi's review.

Jenkins test sanity

**Comment by liqunl** [comment]
@fjeremic The ppc build failed in fetching the repo, can we restart it? The windows failures are known issue https://github.com/eclipse/openj9/issues/2129

**Comment by fjeremic** [comment]
> @fjeremic The ppc build failed in fetching the repo, can we restart it? The windows failures are known issue #2129

The PPC issues I've seen in #2462. Restarting does not help unfortunately (@AdamBrousseau FYI). I'm merging as is since all failures are related to infrastructure issues.

**Pull request merged**
