### PR TITLE
Add object header size to correctly locate the CallSite.target field

### PR DESCRIPTION
**Pull request by babsingh**
Fixes: https://github.com/eclipse/openj9/issues/12404

Co-authored-by: Dan Heidinga <heidinga@redhat.com>
Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by babsingh** [comment]
@DanHeidinga Request for review.

**Review by DanHeidinga — APPROVED** [review]
lgtm

**Comment by DanHeidinga** [comment]
jenkins test sanity winojdk292,xlinuxojdk292 jdk16 depends ibmruntimes/openj9-openjdk-jdk16#29

**Comment by babsingh** [comment]
The Windows test build failed due to a remote connection issue. The Linux test build was aborted midway. @DanHeidinga can you relaunch the `ojdk292` test builds?

**Comment by DanHeidinga** [comment]
jenkins test sanity winojdk292,xlinuxojdk292 jdk16 depends ibmruntimes/openj9-openjdk-jdk16#29

**Pull request merged**
