### PR TITLE
Update testKitGen

### PR DESCRIPTION
**Pull request by renfeiw**
- update skip logic
- remove unnecessary TEST_ITERATION statement

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by llxia** [comment]
jenkins test sanity,extended all jdk8,jdk11

**Comment by llxia** [comment]
jenkins test extended mac jdk8

**Comment by llxia** [comment]
jenkins test extended osx jdk8

**Comment by renfeiw** [comment]
The test failure in PR build is not related to this change. It is a known issue: https://github.com/eclipse/openj9/issues/3081

**Pull request merged**
