### PR TITLE
Contribute Logo

### PR DESCRIPTION
**Pull request by rservant**
This is a contribution of a logo to the Eclipse OpenJ9 project.

It includes a regular logo OpenJ9.svg for general use, and ready to
print hex sticker logo, OpenJ9-hex.svg, for use a laptop sticker.

[skip ci]

Signed-off-by: Ronald Servant <ronald_servant@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
@rservant Can you confirm that you have the ownership rights to give this to the project?  Are there any restrictions on reproducing this logo, modifying it, etc?

**Comment by pshipton** [comment]
Note this is a temporary logo, so OpenJ9 has something. Still seeking something better.

**Comment by rservant** [comment]
@DanHeidinga Yes, I full ownership of the logo.  I contribute it to this project granting the project the rights to use and modify the contribution as it sees fit.

**Comment by rservant** [comment]
@pshipton enjoy the simple elegance of this logo while it lasts :)

**Pull request merged**
