### PR TITLE
Eliminate protobuf from JITServer code (0.20.0) 

### PR DESCRIPTION
**Pull request by mpirvu**
This is a collection of cherry-picked commits from the master branch 
that relate to the elimination of protobuf from JITServer code.

### CODE REVIEW

**Comment by mpirvu** [comment]
The item is marked WIP because it needs some OMR changes as well: https://github.com/eclipse/omr/pull/4943

**Comment by mpirvu** [comment]
Jenkins copyright check

**Comment by mpirvu** [comment]
Copyright check fails due to 'longabout.html'

@pshipton This PR is ready to be delivered to the 0.20 release branch. On top of the main PR I have added two commits for issues discovered after removing protobuf. Thanks

**Comment by pshipton** [comment]
PR testing https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/182/

**Pull request merged**
