### PR TITLE
Adding missing hostClass field to J9ArrayClass

### PR DESCRIPTION
**Pull request by XxAdi101xX**
Signed-off-by: Adithya Venkatarao <adi_101@live.com>

### CODE REVIEW

**Comment by XxAdi101xX** [comment]
@tajila here's the separate pr for the J9ArrayClass fix

**Comment by gacholio** [comment]
jenkins test sanity xlinux jdk11

**Comment by DanHeidinga** [comment]
There's a second problem with the sizes here - found by adding a static assert.  See https://github.com/eclipse/openj9/pull/7678

**Comment by XxAdi101xX** [comment]
Oh great, I guess we don't need to merge in this one then since yours covers this as well

**Comment by gacholio** [comment]
Holding off merge until the various contending PRs are sorted out.

**Pull request closed without merging**
