### PR TITLE
Don't compress debug information for jdk8

### PR DESCRIPTION
**Pull request by keithc-ca**
Compression is not the default for other jdk versions.

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile plinux jdk8

**Comment by pshipton** [comment]
jenkins compile aix,xlinux,osx,zlinux,win,win32 jdk8

**Comment by pshipton** [comment]
The win32 build failed
```
19:34:41  make[2]: *** No rule to make target '/cygdrive/c/Users/jenkins/workspace/Build_JDK8_x86-32_windows_Personal/build/windows-x86-normal-server-release/jdk/bin/verify.map', needed by 'all'.  Stop.
```

**Comment by pshipton** [comment]
win as well. Every other platform passed, I've disabled Windows in a second commit and will merge this.

**Comment by keithc-ca** [comment]
That's right (but I forgot): on Windows when not compressing debug information, the [makefiles express dependencies](https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/make/common/NativeCompilation.gmk#L522) on `.map` and `.pdb` files, but don't define rules that explain how to build those files. That is something that ought to be fixed upstream.

**Comment by pshipton** [comment]
> That is something that ought to be fixed upstream

Which probably means fixing it and then trying to contribute the fix to OpenJDK. Is it something you are going to tackle, or should we ask Andrew and co. to look at it?

**Comment by keithc-ca** [comment]
I'll give it a try. I believe I just commented out the offending lines, but that might not be the right approach.

**Comment by keithc-ca** [comment]
@andrew-m-leonard Can you look into upstreaming the fix for the windows build problem (fixed via https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/384), please? I think it's only jdk8 that needs attention.

**Pull request merged**
