### PR TITLE
Change to use Reflection.getClassAccessFlags in MHs.checkClassAccess

### PR DESCRIPTION
**Pull request by fengxue-IS**
Using class.getModifiers() for an innerclass will return the source code
level modifiers from the innerclass attribute, which may be different
from the runtime class header.

Change to use Reflection.getClassAccessFlags will ensure the actual
JVM ROMClass modifiers are used for access checks.

Fixes: #11538 

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fengxue-IS** [comment]
@tajila can you take a look please

**Comment by tajila** [comment]
wondering if the switch to access_flags breaks anything, we have jsr292 test in the extended variant that tests this sort of thing. Will run those to see if there is anything relying on this behaviour.

**Comment by tajila** [comment]
Jenkins test extended plinux jdk8,jdk11

**Review by tajila — APPROVED** [review]
I am onboard with this change. I think there may be some potential perf issues since the new implementation is not optimized. I would like to hear comments from Dan and Gac regarding https://github.com/eclipse/openj9/issues/11538#issuecomment-765525174 before merging this.

**Comment by DanHeidinga** [comment]
I think this change is incomplete as it leaves all the code related to " Modifier.isProtected" untouched.  We would need to figure out which of those cases no longer apply and deal with any special casing related to those checks today (I think there may be some special cases to interfaces?).

**Comment by DanHeidinga** [comment]
As to the perf concerns, as @gacholio states, they can be trivially addressed

**Comment by tajila** [comment]
> I think this change is incomplete as it leaves all the code related to " Modifier.isProtected" untouched. 

I think the `Modifier.isProtected` checks no longer apply. With the change to access flags it is impossible for that check to ever return true given that `ACC_PROTECTED` doesn't exist in the class access flags.

There are 3 other places where we need a similar change, my intention was to open another issue to track those. But at this point it might be worth it to address everything here.

**Comment by tajila** [comment]
We can focus on the JCL changes here,  GAC is adding the C_INL/fastJNI paths for the native

**Comment by tajila** [comment]
Here are the other places that need to be fixed:
https://github.com/eclipse/openj9/blob/master/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L2037
https://github.com/eclipse/openj9/blob/master/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L834
https://github.com/eclipse/openj9/blob/master/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L1325

**Comment by DanHeidinga** [comment]
It's also a good idea to check the `git blame` for those sections of code and see if they reference tests that we can rerun to validate they are still pass

**Comment by fengxue-IS** [comment]
Comparing the impl for `class.getModifiers()` and `Reflection.getClassAccessFlags()` it seems that the two have different handling for primitive/array classes as while:

`class.getModifiers` return componentClass modifiers plus `Abstract|Final` flag for array classes
`Reflection.getClassAccessFlags()` returns `Abstract|Final|Public` for primitive classes

I verified the OJDK behavior and it seemed that they have an explicit check such that primitive/array classes use `getModifiers` while other classes use `getClassAccessFlags`. should we adopt a similar approach? 

PS: While looking through git history, I found #3047 which mentioned that JTREG tests covers these access checks

**Comment by tajila** [comment]
> I verified the OJDK behavior and it seemed that they have an explicit check such that primitive/array classes use getModifiers while other classes use getClassAccessFlags. should we adopt a similar approach?

Yes we should match that behaviour.

**Comment by fengxue-IS** [comment]
Marking PR as WIP while I re-test the new approach

**Review by DanHeidinga — APPROVED** [review]
This approach looks good to me and I'm glad to see the `isProtected` checks removed in it

**Comment by tajila** [comment]
Jenkins test sanity.openjdk plinux jdk16

**Comment by tajila** [comment]
Jenkins test sanity plinux jdk11

**Comment by fengxue-IS** [comment]
local testing passed, @tajila can you please restart the PR test, I think the failure are either network issue or unrelated (ByteBuffer not supported)

**Comment by tajila** [comment]
Jenkins test sanity plinux jdk11

**Comment by tajila** [comment]
Jenkins test sanity.openjdk plinux jdk16

**Comment by tajila** [comment]
The failures were:

```
STDERR:
18:01:56  java.lang.Exception: Wrong update return len (BYTE):  rlen=0, expected output len=16
18:01:56  	at GCMBufferTest.crypto(GCMBufferTest.java:423)
18:01:56  	at GCMBufferTest.encrypt(GCMBufferTest.java:303)
18:01:56  	at GCMBufferTest.test(GCMBufferTest.java:281)
18:01:56  	at GCMBufferTest.main(GCMBufferTest.java:631)
18:01:56  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:01:56  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
18:01:56  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:01:56  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
18:01:56  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
18:01:56  	at java.base/java.lang.Thread.run(Thread.java:853)
```

```
18:01:58  java.lang.Exception: Error with base offset -1
18:01:58  	at OverlapByteBuffer.main(OverlapByteBuffer.java:147)
18:01:58  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:01:58  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
18:01:58  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:01:58  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
18:01:58  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
18:01:58  	at java.base/java.lang.Thread.run(Thread.java:853)
18:01:58  Caused by: java.lang.UnsupportedOperationException: ByteBuffer not supported
18:01:58  	at java.base/com.sun.crypto.provider.FeedbackCipher.encryptFinal(FeedbackCipher.java:261)
18:01:58  	at java.base/com.sun.crypto.provider.CipherCore.gcmDoFinal(CipherCore.java:1313)
18:01:58  	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:671)
18:01:58  	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2500)
18:01:58  	at OverlapByteBuffer.main(OverlapByteBuffer.java:116)
18:01:58  	... 6 more
```

```
18:01:59  java.lang.UnsupportedOperationException: ByteBuffer not supported
18:01:59  	at java.base/com.sun.crypto.provider.FeedbackCipher.encryptFinal(FeedbackCipher.java:261)
18:01:59  	at java.base/com.sun.crypto.provider.CipherCore.gcmDoFinal(CipherCore.java:1313)
18:01:59  	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:671)
18:01:59  	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2500)
18:01:59  	at SameBuffer.runGCMWithSeparateBuffers(SameBuffer.java:323)
18:01:59  	at SameBuffer.doTestWithSeparatedBuffer(SameBuffer.java:197)
18:01:59  	at SameBuffer.runTest(SameBuffer.java:126)
18:01:59  	at SameBuffer.main(SameBuffer.java:90)
18:01:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:01:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
18:01:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:01:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
18:01:59  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
18:01:59  	at java.base/java.lang.Thread.run(Thread.java:853)
```

@pshipton are these known failures being address in https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/266 ?

**Comment by tajila** [comment]
jenkins test sanity.openjdk win jdk16

**Comment by tajila** [comment]
Looks like the cipher tests are failing everywhere.

**Comment by tajila** [comment]
@fengxue-IS can you make the equivalent PR for the 0.25 branch

**Comment by fengxue-IS** [comment]
> @fengxue-IS can you make the equivalent PR for the 0.25 branch

Created #11914

**Pull request merged**
