### PR TITLE
Hoist compiler code from OMR to OpenJ9

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Move TR_SetMonitorStateOnBlockEntry to OpenJ9
* Relocate live monitors TR_BitVector to J9 CodeGenerator

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Testing is successful.  Removing WIP.

I'd appreciate a review from at least one of @fjeremic @andrewcraik @ymanton please.

**Comment by andrewcraik** [comment]
@cathyzhyi I'd appreciate your thoughts since you are probably the person most familiar with this part of the JIT implementation at present.

**Comment by ymanton** [comment]
LGTM. Good catch on killing the useless live restricted regs bit.

**Comment by fjeremic** [comment]
@0xdaryl I can assume this is another code migration?

**Comment by fjeremic** [comment]
@0xdaryl I can assume this is another code migration?

Jenkins test sanity

**Pull request merged**
