### PR TITLE
Add -Xshareclasses:noPersistentDiskSpaceCheck option

### LINKED ISSUE #6720: -Xshareclasses causes crash on Google Cloud Run
The **-Xshareclasses** option causes a jvm crash when runing on[ Google Cloud Run](
https://cloud.google.com/run/) 

The error message tells that there is **no free space available**.

As Stated on the Filesystem Access section of [this](https://cloud.google.com/run/docs/reference/container-contract) page, **Cloud Run uses some kind of In memory file system**

I tried this with Micronaut and Spring Boot helloworld applications with both java8 and java11, I assume that any application will fail. **After removing the -Xshareclasses option both appications worked**.
I also tried to set Temporary Directory with TMPDIR env variable to another folder, but that didn't helped either.
Setting the **readonly** option for -Xshareclasses didn't made any difference.

I set the allocated memory to 1GB so **there should be a lot of free space**, I assume that **OpenJ9 can't determine the free space available with the in memory filesystem**.

The Dockerfiles I tested with:
FROM adoptopenjdk/openjdk11-openj9:alpine
WORKDIR /app
ADD target/backend*.jar backend.jar
ENV PORT 8080
ENV JAVA_OPTS -Xmx256m -Xms256m -Xquickstart -Xtune:virtualized 
ENV TMPDIR /app/temp
ENTRYPOINT java $JAVA_OPTS -XshowSettings:vm -Xshareclasses -Dserver.port=${PORT} -Djava.security.egd=file:/dev/./urandom -jar backend.jar

FROM adoptopenjdk/openjdk8-openj9:alpine
WORKDIR /app
ADD target/backend*.jar backend.jar
ENV PORT 8080
ENV JAVA_OPTS -Xmx256m -Xms256m -Xquickstart -Xtune:virtualized 
ENV TMPDIR /app/temp
ENTRYPOINT java $JAVA_OPTS -XshowSettings:vm -Xshareclasses -Dserver.port=${PORT} -Djava.security.egd=file:/dev/./urandom -jar backend.jar

FROM adoptopenjdk/openjdk8-openj9:alpine
WORKDIR /app
ADD target/backend*.jar backend.jar
ENV PORT 8080
ENV JAVA_OPTS -Xmx256m -Xms256m -Xquickstart -Xtune:virtualized 
ENTRYPOINT java $JAVA_OPTS -XshowSettings:vm -Xshareclasses -Dserver.port=${PORT} -Djava.security.egd=file:/dev/./urandom -jar backend.jar

The full error message from Cloud Run logs:
{app_name: Java, facility: 1, hostname: IBM, message: JVMSHRC561E Failed to initialize the shared classes cache, there is not enough space in the file system. Available free disk space bytes = 0, requested bytes = 67108864. , msgid: , procid: 1, severity: 3, structured_data: , timestamp: 2019-08-09T…
JVMSHRC561E Failed to initialize the shared classes cache, there is not enough space in the file system. Available free disk space bytes = 0, requested bytes = 67108864.
JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed

### PR DESCRIPTION
**Pull request by pshipton**
Provide a way to skip the disk space check before creating or opening
a persistent cache, for file systems which don't support checking
free space. The disk check is also skipped when running read-only
since no addition disk space is required when not writing to the
cache.

Fixes #6720

Doc issue https://github.com/eclipse/openj9-docs/issues/357

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile xlinux jdk8,jdk11

**Comment by pshipton** [comment]
@hangshao0 can you pls review

**Comment by pshipton** [comment]
jenkins compile zlinux jdk8

**Comment by hangshao0** [comment]
There is another disk space check here:

https://github.com/eclipse/openj9/blob/master/runtime/shared_common/shrinit.cpp#L5055

We may want to skip this one as well.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK8_s390x_linux/658/

@hangshao0 updated based on your comment.

**Comment by pshipton** [comment]
partial help output looks like the following, with noPersistentDiskSpaceCheck added.
```
 cacheRetransformed          Cache classes that are retransformed via JVMTI
 noBootclasspath             Disable caching of classes loaded by the bootstrap class loader.
 bootClassesOnly             Disable caching of classes loaded by the non-bootstrap class loaders. This option also turns on option "nonfatal".
 enableBCI                   Create the cache with support for byte-code instrumentation.
 disableBCI                  Disable support for byte-code instrumentation.
 restrictClasspaths          Classpaths can only be added by first JVM initializing the cache.
 allowClasspaths             Allows a JVM to store classpaths in the cache created with "restrictClasspaths" option.
 noPersistentDiskSpaceCheck  Don't check free disk space before creating a persistent cache.

 invalidateAotMethods=help|{<method_specification>[,<method_specification>]}
```

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk8

**Comment by pshipton** [comment]
@DanHeidinga or @keithc-ca this is ready for review.

**Comment by pshipton** [comment]
Added these changes. Ready for re-review.
- No need to do this disk check if _runningReadOnly is true
- we can mention this new option in J9NLS_SHRC_OSCACHE_MMAP_DISK_FULL.user_response

**Comment by DanHeidinga** [comment]
Jenkins test sanity zlinux jdk8

**Comment by hangshao0** [comment]
I don't have any more comments.

**Comment by keithc-ca** [comment]
Compile error:
```
../../../../../openj9/runtime/shared_common/shrinit.cpp: In function ‘bool isFreeDiskSpaceLow(J9JavaVM*, U_64*)’:
../../../../../openj9/runtime/shared_common/shrinit.cpp:5050:15: error: ‘runtimeFlags’ was not declared in this scope
  if (J9_ARE_ANY_BITS_SET(runtimeFlags, J9SHR_RUNTIMEFLAG_NO_PERSISTENT_DISK_SPACE_CHECK)) {
               ^~~~~~~~~~~~
```

**Comment by pshipton** [comment]
Jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
copyright check passed https://ci.eclipse.org/openj9/job/PullRequest-CopyrightCheck-OpenJ9/18764/

@keithc-ca @DanHeidinga I think this is ready to be merged.

**Pull request merged**
