### PR TITLE
DDR updates for examining thread stacks

### LINKED ISSUE #3472: Changed behaviour in DDR gccheck threadstacks
When I worked on core provided in https://github.com/eclipse/openj9/issues/3467 I noticed change of behaviour in DDR: with latest it returns an error
```
> !gccheck threadstacks
Starting GC Check
Checking THREAD STACKS...Problem running command:
Array index out of range: 7
```
This behaviour has been introduced in iBuild 400030. Previous behaviour was an exception:
```
> !gccheck threadstacks
Starting GC Check
Checking THREAD STACKS...Error executing DDR command !gccheck threadstacks : null
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
    at java.lang.reflect.Method.invoke(Method.java:508)
    at com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:260)
    at com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:170)
    at com.ibm.jvm.dtfjview.Session.execute(Session.java:819)
    at com.ibm.jvm.dtfjview.Session.execute(Session.java:773)
    at com.ibm.jvm.dtfjview.tools.ToolsRegistry.executeJdmpviewCommand(ToolsRegistry.java:183)
    at com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:107)
    at com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:88)
    at com.ibm.jvm.dtfjview.tools.ToolsRegistry.recordAndExecute(ToolsRegistry.java:72)
    at com.ibm.jvm.dtfjview.Session.runInteractive(Session.java:747)
    at com.ibm.jvm.dtfjview.Session.run(Session.java:671)
    at com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:52)
    at com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
Caused by: java.lang.NoSuchFieldError: com/ibm/j9ddr/vm29/structure/MethodMetaDataConstants.J9TR_SHRINK_WRAP
    at com.ibm.j9ddr.vm29.j9.stackwalker.MethodMetaData$MethodMetaData_29_V0.getJitRegisterSaveDescription(MethodMetaData.java:570)
    at com.ibm.j9ddr.vm29.j9.stackwalker.MethodMetaData$MethodMetaData_29_V0.jitAddSpilledRegisters(MethodMetaData.java:435)
    at com.ibm.j9ddr.vm29.j9.stackwalker.MethodMetaData.jitAddSpilledRegisters(MethodMetaData.java:147)
    at com.ibm.j9ddr.vm29.j9.stackwalker.JITStackWalker$JITStackWalker_29_V0.jitWalkStackFrames(JITStackWalker.java:271)
    at com.ibm.j9ddr.vm29.j9.stackwalker.JITStackWalker.jitWalkStackFrames(JITStackWalker.java:102)
    at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkStackFrames(StackWalker.java:484)
    at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkStackFrames(StackWalker.java:165)
    at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker.walkStackFrames(StackWalker.java:96)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.CheckVMThreadStacks.check(CheckVMThreadStacks.java:66)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.Check.run(Check.java:55)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.CheckCycle.run(CheckCycle.java:469)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.GCCheckRunner.run(GCCheckRunner.java:60)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.GCCheckCommand.run(GCCheckCommand.java:47)
    at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
    at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
    at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:385)
    at com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:79)
    at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:360)
    ... 16 more
>
```

### PR DESCRIPTION
**Pull request by keithc-ca**
DDR code was using `TRBuildFlags` which weren't accurately captured in the blob included in core files. This fixes those flags for future core files and updates the DDR code so older core files can be properly interpreted (using equivalent flags in `J9BuildFlags`).

* fix host_XXX macro definitions for DDR
Use "env/defines.h" to get TR_HOST_XXX definitions rather than relying on command-line options.

* use more reliable constants from blob

Updating references as listed below allows DDR to operate on core files that predate the fix to TRBuildFlags.
```
TRBuildFlags.host_32BIT -> J9BuildFlags.!env_data64
TRBuildFlags.host_64BIT -> J9BuildFlags.env_data64
TRBuildFlags.host_ARM   -> J9BuildFlags.J9VM_ARCH_ARM
TRBuildFlags.host_POWER -> J9BuildFlags.J9VM_ARCH_POWER
TRBuildFlags.host_S390  -> J9BuildFlags.arch_s390
TRBuildFlags.host_X86   -> J9BuildFlags.J9VM_ARCH_X86
```

* avoid redundant conditions

Fixes #3472.

### CODE REVIEW

**Comment by fjeremic** [comment]
I'll leave this open until tomorrow if others wish to review as well.

**Comment by fjeremic** [comment]
Jenkins test sanity xlinux JDK8

**Comment by fjeremic** [comment]
Jenkins test sanity all JDK8

**Comment by keithc-ca** [comment]
@jdekonin tells me the JDK8-osx_x86-64_cmprssptrs failure is to be expected: the build machines are not fully ready.

**Comment by pshipton** [comment]
This fix isn't working as expected. Given its late on Friday I'm just going to revert it, and it will be fixed next week.

**Pull request merged**
