### PR TITLE
Rework pipeline scripts to not archive test or sdk on pr builds

### PR DESCRIPTION
**Pull request by jdekonin**
Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
@AdamBrousseau @DanHeidinga please review

**Comment by jdekonin** [comment]
jenkins test sanity plinux jdk10

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux jdk8

**Comment by DanHeidinga** [comment]
Jenkins compile xlinux jdk10

**Comment by DanHeidinga** [comment]
This looks good to me.  Launching a sanity and a compile to validate the two code paths.

Will need to ensure no SDK gets archived in these PR builds

**Comment by AdamBrousseau** [comment]
Jenkins compile xlinux jdk10

**Comment by AdamBrousseau** [comment]
Jenkins test sanity win jdk8

**Pull request merged**
