### PR TITLE
Port cmdLineTester_pltest_j9sig_ext Test

### PR DESCRIPTION
**Pull request by nikolamilijevic1**
-added cmdLineTester_pltest_j9sig_ext test to playlist.xml
-fixed error with _JVM_OPTIONS, all occurrences changed to JVM_OPTIONS

[ci skip]
Signed-off-by: Nikola Milijevic <nmilijev@uwaterloo.ca>

### CODE REVIEW

**Comment by nikolamilijevic1** [comment]
tested internally:
| BUILD | PLATFORM | TARGET  | BUILD_LIST | JAVA_VERSION |
--- | --- | --- |  --- |--- |
| Grinder/8107 | x86-64_linux | cmdLineTester_pltest_j9sig_ext | functional | 8 |
| Grinder/8108 | ppc64le_linux | cmdLineTester_pltest_j9sig_ext | functional | 8 |
| Grinder/8109 | s390x_linux | cmdLineTester_pltest_j9sig_ext | functional | 8 |
| Grinder/8111 | ppc64le_linux | cmdLineTester_pltest_j9sig_ext | functional | 11 |
| Grinder/8112 | s390x_linux | cmdLineTester_pltest_j9sig_ext | functional | 11 |
| Grinder/8113 | x86-64_linux | cmdLineTester_pltest_j9sig_ext | functional | 11 |

**Comment by nikolamilijevic1** [comment]
reviewers: @llxia @renfeiw

**Comment by llxia** [comment]
jenkins test sanity,extended all jdk11

**Comment by llxia** [comment]
jenkins test extended all jdk8

**Comment by llxia** [comment]
jenkins test extended zlinux,plinux,xlinuxlargeheap jdk8

**Comment by llxia** [comment]
jenkins test sanity zlinuxlargeheap jdk11

**Comment by llxia** [comment]
`testSCCacheManagement_0 ` failure in [Test_openjdk8_j9_extended.functional_s390x_linux_xl_Personal](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_s390x_linux_xl_Personal_testList_1/1/tapResults/) is unrelated to this PR

**Comment by llxia** [comment]
Reran [Test_openjdk8_j9_extended.functional_ppc64le_linux_xl_Personal](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_ppc64le_linux_xl_Personal/13/) in https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_ppc64le_linux_xl_Personal/14/

**Pull request merged**
