### PR TITLE
remove -Xdump:none and add verbosegclog for all SoftMx tests

### PR DESCRIPTION
**Pull request by llxia**
Issue: #4090
[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
jenkins test extended xlinux,aix,win jdk11

**Comment by llxia** [comment]
jenkins test extended xlinux,win jdk8

**Comment by DanHeidinga** [comment]
@llxia Can you check the internal history for the rationale on why we added `-Xdump:none` in the first place?  If I had to guess, it would be related to the test generating cores too frequently for a case that was generally expected to occur.

**Comment by llxia** [comment]
Unfortunately, we cannot find the rationale from the history. It seems the tests were migrated from cvs to rtc in 2013 and we do not have cvs history anymore.

How about we still keep `-Xdump:none` in command and move `$(JVM_OPTIONS)` after hardcoded options? 

```
$(JAVA_COMMAND) \
-Xdump:none -Xmx1024m -Xsoftmx512m -Xmn1m -verbose:gc -Xverbosegclog:$(REPORTDIR)$(D)vgc.log $(JVM_OPTIONS) \
```

In this way, the tests will not generate cores and users can debug it by specifying `-Xdump:XXXX` in `EXTRA_OPTIONS` in Grinder.

**Comment by DanHeidinga** [comment]
`-Xdump:system:none:events=systhrow,filter=java/lang/OutOfMemoryError` would disable the system core on OOM - https://www.eclipse.org/openj9/docs/xdump/ - and leave the javacore.

@dmitripivkine Would that be sufficient to give you info you need to validate the GC functionality isn't broken?

**Comment by dmitripivkine** [comment]
> Failures are intermittent and usually we need to make a decision on every failed case. So I believe it is important to have (at least) javacore to verify that GC Softmx functionality is not broken but OS environment somehow does not provide report about returned memory in time

... or may be GC verbose log might help in this case and we can suppress dumps if it is critical

**Comment by dmitripivkine** [comment]
> `-Xdump:system:none:events=systhrow,filter=java/lang/OutOfMemoryError` would disable the system core on OOM - https://www.eclipse.org/openj9/docs/xdump/ - and leave the javacore.
> 
> @dmitripivkine Would that be sufficient to give you info you need to validate the GC functionality isn't broken?

The OOM is not usual for this test. It something needs to be investigated. So it would not help unfortunately. Cores are requested explicitly from https://github.com/eclipse/openj9/blob/master/test/functional/JLM_Tests/src/j9vm/test/softmx/SoftmxAdvanceTest.java lines 167-169. This code can be changed (may be we have more copy/paste places)

**Comment by dmitripivkine** [comment]
Just to summarize: if we believe that check of free memory in OS has a value we can add gc verbose log generation and move -Xdump:none to external options it should be sufficient for now.

**Comment by dmitripivkine** [comment]
> @dmitripivkine It sounds like we should proceed with @llxia's change as the reason for the `-Xdump:none` is lost. It can always be modified if we find there's a problem.

Yes, this is my point exactly.

**Pull request merged**
