### PR TITLE
Add new VT tests for default value

### PR DESCRIPTION
**Pull request by tajila**
Add new VT tests for default value

- Refactor existing VT generator and reduce code duplication
- Update VT generator to use defaultValue bytecode
- update comment in tests to show flattened vs ref
- add new generic VT creator for Q types 

Signed-off-by: tajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
@llxia can you please review this PR

**Comment by llxia** [comment]
Run PR build just to make sure regular build does not get affected.

**Comment by llxia** [comment]
jenkins test sanity xlinux jdk11

**Comment by tajila** [comment]
https://github.com/eclipse/openj9/issues/1390

**Pull request merged**
