### PR TITLE
Add initial Compiler Best Practices doc

### PR DESCRIPTION
**Pull request by dsouzai**
Motivated by https://openj9.slack.com/archives/C8312LCV9/p1564603107022100?thread_ts=1564547206.018100&cid=C8312LCV9, this PR adds a Best Practices doc to follow / keep in mind when developing on the Compiler. It is currently small, but the hope is that over time, we add to it.

### CODE REVIEW

**Comment by andrewcraik** [comment]
I like this, but I helped suggest it :) I've asked @mstoodle for a review in his capacity as one of the project leads and as an opinion outside the group of people who thought up this idea.

**Comment by mstoodle** [comment]
Actually, I do have one request @dsouzai : would you please make the commit title more clear that this (hopefully) initial contribution is specifically related to the compiler component?

**Comment by dsouzai** [comment]
Done :)

**Comment by mstoodle** [comment]
Thanks @dsouzai !

**Pull request merged**
