### PR TITLE
WIP: Set PATH for Windows build to clang binaries

### PR DESCRIPTION
**Pull request by jdekonin**
* [skip ci]

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
jenkins compile win jdk11

**Comment by jdekonin** [comment]
jenkins compile win jdk11

**Comment by jdekonin** [comment]
jenkins compile win jdk11

**Comment by jdekonin** [comment]
jenkins compile win jdk11

**Comment by jdekonin** [comment]
jenkins compile win jdk11

**Comment by jdekonin** [comment]
jenkins compile win jdk11

**Comment by jdekonin** [comment]
jenkins test sanity win,win32 jdk8

**Comment by jdekonin** [comment]
jenkins test sanity win jdk11

**Comment by jdekonin** [comment]
jenkins test sanity win jdk8

**Comment by jdekonin** [comment]
jenkins test sanity win jdk8

**Comment by jdekonin** [comment]
jenkins test sanity win jdk8

**Comment by jdekonin** [comment]
jenkins test sanity win jdk11

**Comment by jdekonin** [comment]
jenkins test sanity win32 jdk8

**Comment by jdekonin** [comment]
jenkins test sanity win jdk8

**Comment by jdekonin** [comment]
jenkins test sanity win32 jdk8

**Comment by jdekonin** [comment]
jenkins test sanity win jdk11

**Comment by ChengJin01** [comment]
I noticed that these builds (Java 8 and Java 11) are still compiled with mingw rather than clang.

e.g.
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-win_x86-64_cmprssptrs-OpenJ9/77/consoleFull
13:55:56 x86_64-w64-mingw32-g++ -O3 -DWIN32 -D_WIN32 -DOMR_OS_WINDOWS ... -DUT_DIRECT_TRACE_REGISTRATION -DTR_HOST_X86 -c BytecodeInterpreter.cpp -o BytecodeInterpreter.obj

**Comment by jdekonin** [comment]
Performed via #2979

**Pull request closed without merging**
