### PR TITLE
Updated error handling for MethodHandle invocation

### PR DESCRIPTION
**Pull request by DanHeidinga**
This commit applies the fix from #7062 to the JIT thunkArchetype
for the SpreadHandle.

For Java 11 and up, throw a NullPointerException in stead of
IlleagalArgumentException when SpreadHandle expect non-zero
length array argument and received null

Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux jdk11

**Comment by DanHeidinga** [comment]
Jenkins test sanity zlinux jdk11

**Comment by pshipton** [comment]
Note the previous PR testing passed.

**Comment by DanHeidinga** [comment]
backported to 0.17 https://github.com/eclipse/openj9/pull/7466

**Pull request merged**
