### PR TITLE
Remove use of DecimalFormatHelper related enum

### PR DESCRIPTION
**Pull request by liqunl**
Closes: #9377 
Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@andrewcraik @knn-k

**Comment by andrewcraik** [comment]
Jenkins test sanity plinux,xlinux,xlinuxxl jdk14

**Comment by liqunl** [comment]
@andrewcraik The x86 JDK14 builds completed compiling but failed to upload artifact to server.

**Comment by andrewcraik** [comment]
Given the need to merge this, that the change only affects a debug assert that is not compiled in I think the successful builds are sufficient. I will merge this to save burning more farm time on needless testing (the generated code will not be affected by this change.

**Pull request merged**
