### PR TITLE
Release notes for 0.13.0 milestone 1

### PR DESCRIPTION
**Pull request by SueChaplain**
Created a new release note, with work in progress
for milestone 1.

[ci skip]

Signed-off-by: Sue Chaplain <sue_chaplain@uk.ibm.com>

### CODE REVIEW

**Comment by SueChaplain** [comment]
@pshipton - I've added all the content for milestone 1 now. One question. There is an issue about bundling OpenSSL for AIX. Do you want me to remove this, now that our intention is not to bundle going forward?

**Comment by pshipton** [comment]
@SueChaplain AIX doesn't work with OpenSSL yet. Steve mentioned he might have a fix. I think we need to wait and confirm it is working before removing the note.

**Comment by pshipton** [comment]
This also means that "OpenSSL 1.0.2 support *(all platforms)*" isn't quite true.

**Comment by SueChaplain** [comment]
@pshipton - I removed the issue from the table about us not being able to bundle OpenSSL on AIX due to an issue as we no longer want to.

I think these notes are ready for the milestone build.

**Pull request merged**
