### PR TITLE
Update buildenv/docker/jdk9/* Dockerfile(s)

### PR DESCRIPTION
**Pull request by babsingh**
- Use AdoptOpenJDK OpenJ9 build as the boot jdk for JDK9 DockerFile(s).
```
AdoptOpenJDK OpenJ9 build is used as the boot jdk:
1) arm-linux-aarch64 (x64_linux):
https://api.adoptopenjdk.net/openjdk8-openj9/releases/x64_linux/latest/binary
2) arm-linux-gnueabihf (x64_linux):
https://api.adoptopenjdk.net/openjdk8-openj9/releases/x64_linux/latest/binary
3) ppc64le (ppc64le_linux):
https://api.adoptopenjdk.net/openjdk8-openj9/releases/ppc64le_linux/latest/binary
4) s390x (s390x_linux):
https://api.adoptopenjdk.net/openjdk8-openj9/releases/s390x_linux/latest/binary
5) x86_64 (x64_linux):
https://api.adoptopenjdk.net/openjdk8-openj9/releases/x64_linux/latest/binary

For s390x and ppc64le, the base image is changed to "ubuntu:16.04".
```
- Update download links to libcups2-dev and libcupsimage2-dev libraries in JDK9 DockerFile(s).
```
For aarch64_CC and armhf_CC DockerFile(s), download links for the
following libraries were updated: libcups2-dev_2.2.1-8 and
libcupsimage2-dev_2.2.1-8. Old download links don't work anymore.
```

[skip ci]

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
@JamesKingdon please review the arm changes.

**Comment by JamesKingdon** [comment]
@babsingh Why were the changes to cups needed?

**Comment by babsingh** [comment]
@JamesKingdon old download links don't exist. so, i had to replace them with working links.

**Comment by JamesKingdon** [comment]
Ah, right you are - many thanks for fixing!

**Comment by babsingh** [comment]
Testing was done successfully for `x86` and `arm` platforms using the below instructions. Based upon Joe's `s390` testing for https://github.com/eclipse/openj9/pull/1545 and https://github.com/eclipse/openj9/pull/1514, these changes should work fine on `s390`. Testing can't be done on `ppcle` since no machines are available. It will take some time to get access to Ubuntu `ppcle` machines with docker installed. When `ppcle` machines become available, fixes will be pushed in a new pull request if testing fails.

```
    Build docker: docker build -f buildenv/docker/jdk9/${platform}/ubuntu16/Dockerfile -t=openj9 .
    Run docker: docker run -i -t openj9:latest /bin/bash
    Test boot jdk: java -version
    Build Java 9
        git clone https://github.com/ibmruntimes/openj9-openjdk-jdk9.git
        cd openj9-openjdk-jdk9
        bash ./get_source.sh
        bash ./configure --with-freemarker-jar=/root/freemarker.jar
        make images
    Test Java 9: build/${platform}/images/jdk/bin/java -version
```

**Comment by babsingh** [comment]
@keithc-ca can you review these changes as well? similar to https://github.com/eclipse/openj9/pull/1514, testing is pending for `ppcle`. can you please test the DockerFile on `ppcle`? Thanks.

**Comment by keithc-ca** [comment]
Skipping PR testing; these files should not affect builds.

**Comment by keithc-ca** [comment]
@babsingh Can you please squash before I merge?

**Comment by babsingh** [comment]
@keithc-ca the two commits cover two distinct issues. do we squash if each commit covers a different issue?

**Comment by keithc-ca** [comment]
Ok, we don't need to squash.

**Pull request merged**
