### PR TITLE
Made a change to the docker file

### PR DESCRIPTION
**Pull request by adam-thorpe**
Edited dockerjdk11 file to add libxrandr-dev to the install list

Signed-off-by: Adam Thorpe <adam.thorpe@ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
@adam-thorpe have you signed the Eclipse ECA, because the check is failing?
http://www.eclipse.org/legal/ECA.php

In the commit, please explain why you are adding libxrandr-dev, update the commit "title" to be more specific about the change, and remove the .DS_Store files from the commit.

**Comment by adam-thorpe** [comment]
Hi, yes I have signed the ECA already so am not sure why the checks are failing? Will change the commit in the meanwhile.

**Comment by pshipton** [comment]
The actual eca check error is `Anonymous (adamthorpe@****.local) is not covered by the necessary legal agreements in order to proceed.`

**Comment by pshipton** [comment]
Checking at Eclipse, `There is a valid ECA on file for adam.thorpe@ibm.com`

**Comment by pshipton** [comment]
You'll need to squash your commits. What I'm looking for as the first line of the commit is like `Add libxrandr-dev to the dockerjdk11 file`. This is a good summary because it explains the change without having to look for more details. Then include more detail in the body about why libxrandr-dev is added, as you have. `Edited the docker file for jdk11 to add "libxrandr-dev" to the install list.` in the body should be redundant, so not necessary. 

See https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md for more info about creating commit comments.

**Comment by pshipton** [comment]
Here is the checklist for contributions to be acceptable, copied from https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md

Create an account at Eclipse.
- Add your GitHub user name in your account settings.
- Log into the project's portal and sign the "Eclipse ECA".
- Ensure that you sign-off your Git commits.
- Ensure that you use the same email address as your Eclipse account in commits.

**Comment by pshipton** [comment]
Also, please add `[ci skip]` in your commit message when you squash, as we don't need the travis CI build for this change.

**Comment by pshipton** [comment]
I can't merge this with the failing eca check. Since it wasn't fixed, I'll just close it.

**Pull request closed without merging**
