### PR TITLE
Add bootjdk for jdk15 aarch builds

### PR DESCRIPTION
**Pull request by jdekonin**
Closes eclipse/openj9#10641

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
jenkins compile alinux64 jdk8,jdk11,jdk15

**Comment by jdekonin** [comment]
fyi @pshipton

**Comment by pshipton** [comment]
I expected the OpenJ9 jdk15 0.22 M2 build to be used. 
https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15%2B36_openj9-0.22.0-m2/OpenJDK15U-jdk_aarch64_linux_openj9_15_36_openj9-0.22.0-m2.tar.gz

**Comment by jdekonin** [comment]
jenkins compile alinux64 jdk15

**Comment by jdekonin** [comment]
jenkins compile alinux64 jdk15

**Comment by jdekonin** [comment]
Previous compile passed but the last part of the job is running `java -version` in the build/$release directory.  $release is now 'linux-aarch64-server-release' whereas it use to be 'linux-aarch64-normal-server-release'.  Most recent update is a change to that.  Should work this time.

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
Pls fix the commit title to contain jdk15 instead of jdk14 and then I'll merge.

**Pull request merged**
