### PR TITLE
Fix quoting of LD_LIBRARY_PATH

### PR DESCRIPTION
**Pull request by keithc-ca**
Remove unwanted quotes in `TEST_LIB_PATH_VALUE`.

### CODE REVIEW

**Comment by pshipton** [comment]
@smlambert @llxia

**Comment by llxia** [comment]
jenkins test sanity all jdk8

**Comment by keithc-ca** [comment]
Jenkins test sanity aix,xlinux,win32 jdk8

**Comment by llxia** [comment]
Got "ERROR: Error fetching remote repo 'origin'" in aix and xlinux PR build again. Relaunch.

**Comment by llxia** [comment]
Jenkins test sanity aix,xlinux jdk8

**Comment by llxia** [comment]
jenkins test sanity xlinuxlargeheap jdk8

**Pull request merged**
