### PR TITLE
modify the translated PII files in nls folder

### PR DESCRIPTION
**Pull request by panlei080988**
Check in the Shipment 1 translation package for J182F's TVT

Signed-off-by: Lei Pan pleinb@cn.ibm.com

### CODE REVIEW

**Comment by pshipton** [comment]
Note you need to sign the Eclipse ECA in order to pass the ip-validation checks.
http://www.eclipse.org/legal/ECA.php

**Comment by panlei080988** [comment]
@pshipton  But I have signed it before
image

**Comment by pshipton** [comment]
Ok. Please add the Signed-off-by: line into your commit.

**Comment by panlei080988** [comment]
I create the pull request through the UI, how could I add a Signed-off-by: line from UI?
In the commit above, I add the line manually

**Comment by pshipton** [comment]
When you create the commit using the UI there is a place to add the commit title and also a place to add commit comments ("Add an optional extended description..."). Put the Signed-off-by: line into the commit comment.

**Pull request closed without merging**
