### PR TITLE
Use byteswap to implement reverseBytes

### PR DESCRIPTION
**Pull request by aviansie-ben**
Previously, it was up to each individual codegen to perform inlining of
the Short, Integer, and Long class' reverseBytes methods. However, now
that the full suite of byteswap evaluators are available in OMR, this
transformation can be performed in the optimizer using these opcodes.

Signed-off-by: Ben Thomas <ben@benthomas.ca>

### CODE REVIEW

**Review by fjeremic — APPROVED** [review]

**Comment by fjeremic** [comment]
Jenkins test sanity,system all jdk8

**Comment by fjeremic** [comment]
Jenkins test sanity,system all jdk8

**Comment by aviansie-ben** [comment]
Looked into the failures on zLinux. Looks like I forgot that Java shorts are treated as ints during calls, so the `Short.reverseBytes` recognition needs to perform an additional `i2s` and `s2i` surrounding the `sbyteswap`. By pure coincidence, my simple test case worked perfectly fine on Power since we don't seem to do any IL type validation there.

Working on a fix now.

**Comment by aviansie-ben** [comment]
Alright, the issue with the inlining of `Short.reverseBytes` should be fixed now.

**Comment by fjeremic** [comment]
Jenkins test sanity,system all jdk8

**Pull request merged**
