### PR TITLE
Exclude default/forceLazySymbolResolution test for jdk15+ 

### PR DESCRIPTION
**Pull request by pshipton**
Issue https://github.com/eclipse/openj9/issues/11076

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test extended zlinux jdk15

**Review by llxia — APPROVED** [review]
LGTM

**Comment by llxia** [comment]
[PR build failed](https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_extended.functional_s390x_linux_Personal/8/tapResults/) due to cmdLineTester_forceLazySymbolResolution. Do we want to exclude cmdLineTester_forceLazySymbolResolution as well?

**Comment by pshipton** [comment]
Yup, I forgot there were 2.

**Comment by pshipton** [comment]
jenkins test extended zlinux jdk15

**Comment by pshipton** [comment]
@llxia testing passed this time.

**Pull request merged**
