### PR TITLE
Contribute the source code of CDS adapter to OpenJ9

### PR DESCRIPTION
**Pull request by hangshao0**
Contribute only the java source files of the CDS adapter project to
OpenJ9

Signed-off-by: hangshao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
@tjwatson is this license (EPL v2) going to be ok for Eclipse to use the files?

**Comment by pshipton** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16749

**Comment by tjwatson** [comment]
@pshipton Yes, we are moving to EPL v2 for the Eclipse project already.

**Comment by hangshao0** [comment]
I've added the .project file to this commit.

**Comment by hangshao0** [comment]
Copyright check failure is from the .project file which does not have a copyright.

**Comment by pshipton** [comment]
jenkins compile plinux jdk8

**Pull request merged**
