### PR TITLE
Add tests for heap dump enabling and disabling

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Exercise the -XX:[+-]HeapDumpOnOutOfMemoryError option added by
https://github.com/eclipse/openj9/pull/2533.  Add a trivial "HelloWorld"
program to exercise program launching.
[ci skip]
Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pdbain-ibm** [comment]
@llxia I tested this manually.  Personal builds are not working due to machine issues (though I will keep trying). Would you kindly start a pull request build?  Linux x86 extended should be sufficient.

**Comment by llxia** [comment]
Jenkins test extended xlinux jdk10

**Comment by pdbain-ibm** [comment]
My changes broke some other tests.  I will re-work this.

**Comment by pdbain-ibm** [comment]
Tests updated and manually tested.  @llxia would you kindly review.  Thank you

**Comment by llxia** [comment]
Jenkins test extended xlinux jdk10

**Comment by llxia** [comment]
The failure is not related to your PR. This test failed in nightly build https://ci.eclipse.org/openj9/view/Test/job/Test-extended.functional-JDK10-linux_x86-64_cmprssptrs/48/tapResults/

You opened an issue for jdk8: https://github.com/eclipse/openj9/issues/2644

**Comment by llxia** [comment]
Going to merge this PR as VmArgumentTests_0 passed.

**Pull request merged**
