### PR TITLE
Add option to limit identity hash code to positive values

### PR DESCRIPTION
**Pull request by gacholio**
Add command line option "-XX:[+|-]PositiveIdentityHash" to
enable/disable forcing identity hash code to be a positive value.

Fixes: #3062

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
@gacholio please open an issue at https://github.com/eclipse/openj9-docs for the doc change.

**Comment by vijaysun-omr** [comment]
Thanks @DanHeidinga and @gacholio for this change. 

I think a small unit test that computes indentityHashCode many times should tell us the relative cost of adding the option check on this code path. The baseline would be a build without this change. 

I can also get Liberty tried with this change just to make sure it does not regress. I believe some code in a Lucene test we had exercised identity hash codes but I cannot be sure but I'll ask the team members I was working with at that time if we still have the test.

**Comment by vijaysun-omr** [comment]
I asked and we don't have the Lucene testing I was thinking of anymore. So I will just get this evaluated on Liberty.

**Comment by gacholio** [comment]
-Xjit results (10x the iteration count of -Xint):

Before:

1000000000 iterations took 9923 ms
1000000000 iterations took 9785 ms
1000000000 iterations took 9789 ms

After:

1000000000 iterations took 10815 ms
1000000000 iterations took 10812 ms
1000000000 iterations took 10865 ms

Seems consistently slower.

**Comment by vijaysun-omr** [comment]
I assume this is comparing a build without the option vs a build with the option (but the option is not specified on the command line). ?

**Comment by gacholio** [comment]
@vijaysun-omr The JIT seems to recognize and replaced identityHashCode, but it looks like that's guarded by an option that is not set, and the replacement code is unimplmeneted. Can you confirm?

I can't explain why the JIT would be slower (the JITs were not identical in the builds, but they were no more than a day different).

**Comment by gacholio** [comment]
Yes, the "before" is a build from today and the "after" is a build from yesterday with this PR added. The new option was not enabled.

**Comment by vijaysun-omr** [comment]
I've never seen identityHashCode take more than a couple of percent in any profile really; it's much lower than that in the profiles of benchmarks we work with usually. So I am thinking this is acceptable since the overhead of the extra check you added would be < 0.2% in those benchmarks.

**Comment by gacholio** [comment]
There is a Fast JNI implementation in use by the JIT (and that will get the change from this PR).

**Comment by vijaysun-omr** [comment]
Is it possible to swap the JIT module between these 2 builds and see if we can get a run with literally the same JIT ?

**Comment by gacholio** [comment]
@vijaysun-omr For the Liberty bench, it would be good to know the cost of enabling the new option, not just the cost of the new code.

**Comment by gacholio** [comment]
Copying the "before" JIT into the "after" VM:

1000000000 iterations took 10844 ms
1000000000 iterations took 10856 ms
1000000000 iterations took 10876 ms

yields essentially identical results.

**Comment by DanHeidinga** [comment]
@vijaysun-omr @gacholio I'm OK with merging this now so it makes the 0.11.0 release and we can update with the Liberty results when they're available.

Any objections?

**Comment by gacholio** [comment]
I guess I can just say "unknowable performance impact" in the doc.

**Comment by vijaysun-omr** [comment]
Given that I don't expect any measurable regression in Liberty I have no issue merging this now without waiting for the Liberty result.

**Comment by vijaysun-omr** [comment]
@gacholio yes we don't do anything special for the identityHashCode computation in the JIT as far as I know.

**Comment by gacholio** [comment]
Doc issue: https://github.com/eclipse/openj9-docs/issues/109

**Pull request merged**
