### PR TITLE
Use TR::MemoryReference::create API where applicable

### PR DESCRIPTION
**Pull request by r30shah**
Signed-off-by: Rahil Shah <rahil@ca.ibm.com>

### CODE REVIEW

**Comment by r30shah** [comment]
@fjeremic  Looks like I missed couple of places in OpenJ9 to change the API causing the compilation failures in the build. Can you please launch Jenkins build on this changes?

**Comment by pshipton** [comment]
jenkins compile zlinux jdk8,jdk11 depends eclipse/omr#master

**Comment by pshipton** [comment]
I assume this is related to https://openj9.slack.com/archives/CDS7QE9HB/p1607728791147100

**Comment by r30shah** [comment]
Thanks @pshipton for launching the build. Yes this is related to the failure you mentioned in slack chat. It should fix the OMR acceptance failures.

**Comment by pshipton** [comment]
This is what was built, which is the latest omr master branch atm. I think what you saw is a known misleading problem.
```
19:15:04    Source version info:
19:15:04      openjdk - c47c5c113fb
19:15:04      openj9  - b1a93345660
19:15:05      omr     - f2f2788c03c
```

**Comment by pshipton** [comment]
Also reflected in the `-version` output which is part of the build. The `Source version info` is printed for those times we don't get any `-version` output.
```
19:27:13  openjdk version "11.0.10-internal" 2021-01-19
19:27:13  OpenJDK Runtime Environment (build 11.0.10-internal+0-adhoc.jenkins.BuildJDK11s390xlinuxPersonal)
19:27:13  Eclipse OpenJ9 VM (build HEAD-b1a93345660, JRE 11 Linux s390x-64-Bit Compressed References 20201212_952 (JIT enabled, AOT enabled)
19:27:13  OpenJ9   - b1a93345660
19:27:13  OMR      - f2f2788c03c
19:27:13  JCL      - c47c5c113fb based on jdk-11.0.10+6)
```

**Review by fjeremic — APPROVED** [review]

**Comment by fjeremic** [comment]
Jenkins test sanity zlinux jdk8

**Pull request merged**
