### PR TITLE
Add Dockerfile for ARM cross compilation

### PR DESCRIPTION
**Pull request by JamesKingdon**
Add a Dockerfile with the toolchain and native libraries for
cross compiling for armhf.

Signed-off-by: James Kingdon <jkingdon@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
@0xdaryl I'm not an expert on reviewing these kind of infra changes - who would be the right person? you?

**Comment by 0xdaryl** [comment]
Sure, I'll take a look at it.

**Comment by 0xdaryl** [comment]
Seems reasonable to me.

@rwy0717 @dsouzai : I'd appreciate a +1 from one of you.

**Comment by DanHeidinga** [comment]
`OJ_CC` Are these OpenJDK specific env vars or something new from OpenJ9?  Can you link this to the relevant PRs on the extensions repo that use the env vars?

**Comment by JamesKingdon** [comment]
@DanHeidinga The OJ* variables are new, and the code to use them is still in progress.

**Comment by dsouzai** [comment]
It looks reasonable to me but unfortunately I'm not an expert with the infra changes either. @mgaudet do you mind giving it a once over on my behalf :P.

The only thing that is worth pointing out is the line containing `ENV OPENJDK_DOCKER_CC_ARM 1`; from the discussion in https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/88, that may have to be changed in the future.

**Comment by JamesKingdon** [comment]
Yes, OPENJDK_DOCKER_CC_ARM was only intended to be a get-us-going bootstrap. It will be trivial to remove it later when cmake has been implemented across all the projects.

**Comment by mgaudet** [comment]
I think my only real comment would be: Why `OJ_*` and not `OJ9_*`?

**Comment by JamesKingdon** [comment]
Deliberate ambiguity? Happy to call them anything you want.

**Comment by mgaudet** [comment]
I lean `OJ9_`, (or even `OPENJ9_`), to try to reduce said ambiguity.

**Comment by JamesKingdon** [comment]
Updated variable names, removed the trailing '-' from OPENJ9_CC_PREFIX.

**Comment by JamesKingdon** [comment]
Consumers of the Dockerfile:
https://github.com/eclipse/openj9/pull/686
https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/88
https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/87
https://github.com/eclipse/omr/pull/2057

**Comment by JamesKingdon** [comment]
@0xdaryl Any more changes wanted?

**Comment by pshipton** [comment]
Is this PR obsolete? The Dockerfile is in #686

**Comment by JamesKingdon** [comment]
@pshipton I was hoping that adding an independent docker file would be uncontroversial and that this PR would have been merged quickly. But since everything has dragged on for nearly a month the newer PRs also contain the earlier material which makes reviewing more difficult.

**Comment by JamesKingdon** [comment]
@pshipton And to answer your question more directly, the changes that have been requested to the dockerfile in the later PR do indeed render this request obsolete. Closing.

**Pull request closed without merging**
