### PR TITLE
Revert "JIT support for re-sizable SCC"

### PR DESCRIPTION
**Pull request by ymanton**
Reverts eclipse/openj9#9772

> JITServer tests are failing solidly after this PR.

as per https://github.com/eclipse/openj9/pull/9772#issuecomment-670927672

### CODE REVIEW

**Comment by dsouzai** [comment]
I was talking to @mpirvu offline; the stack trace was
```
#18 <signal handler called>
#19 0x00007f98d3216fd9 in TR_J9SharedCache::isPointerInROMClassesSectionInCache(J9SharedClassCacheDescriptor const*, void*) ()
#20 0x00007f98d3217290 in TR_J9SharedCache::isROMStructureInSharedCache(void*, unsigned long*) ()
#21 0x00007f98d318fae6 in J9::AheadOfTimeCompile::offsetInSharedCacheFromROMClass(TR_SharedCache*, J9ROMClass*) ()
#22 0x00007f98d318fe2e in J9::AheadOfTimeCompile::initializeCommonAOTRelocationHeader(TR::IteratedExternalRelocation*, TR_RelocationRecord*) ()
#23 0x00007f98d33c3bbb in J9::X86::AheadOfTimeCompile::initializeAOTRelocationHeader(TR::IteratedExternalRelocation*) ()
```
From the code, it looks like the only place that could cause a crash is `J9SharedClassCacheDescriptor *cacheDesc`; however that was used even before this change. 

What's different is
```
uintptr_t romclassEndAddress   = reinterpret_cast<uintptr_t>(SEGUPDATEPTR(cacheDesc->cacheStartAddress)); // Exclusive
```
where `SEGUPDATEPTR` is
```
#define SEGUPDATEPTR(ca) (((uint8_t *)(ca)) + (ca)->segmentSRP)
```
`cacheStartAddress` is:
```
struct J9SharedCacheHeader* cacheStartAddress;
```
The `cacheStartAddress` is probably invalid. Marius said that the client sends over the `J9SharedClassCacheDescriptor`; it looks like we're also going to have to send over the `struct J9SharedCacheHeader* cacheStartAddress` field.

**Comment by dsouzai** [comment]
Gonna open a PR, likely by the end of the day, to send over the `J9SharedCacheHeader*` structure as well.

**Comment by dsouzai** [comment]
After further discussion with @mpirvu, it looks like the changes required on JITServer are going to be considerably more complicated than it seemed at first glance. The reason is because with the new JIT changes, it requires knowing where the ROMClasss section / Metadata section ends. However, these change over time. If a JITServer compilation requires remembering a class (ie creating a class chain), it will update the metadata section pointer. However, currently the cache description is sent over just once. This means that we'll run into problems because we'll have a pointer on our hands that is in the cache, but when we go to do our sanity checks, it'll look like it's not and assert.

Therefore, I have to merge this revert until we have a proper solution for JITServer.

**Comment by mpirvu** [comment]
The problem with JITServer is the end of the ROMClass section and metadata section because those change all the time. They are used to determine whether a pointer (or offset) is in the ROMClass section or metadata section. Typically we know what kind of pointer or offset we are dealing with, so what we really need to check is whether the pointer/offset is within the current cache bounds; the check whether or not it's in ROMClass section or metadata section is just a nice-to-have extra check. I am proposing to eliminate this extra check on JITServer.
For example: `isPointerInMetadataSectionSectionInCache()` is used only in `TR_J9SharedCache::isPointerInSharedCache()`, but for JITServer this can easily be replaced with `isPointerInCache()`

**Pull request merged**
