### PR TITLE
Backport multi-layered SCC change from master to jitaas

### PR DESCRIPTION
**Pull request by harryyu1994**
Backport multi-layered SCC change from master.
Add multi-layered SCC support for JITServer. JITClient packs the circular linked list data structure that stores SCC offset and size information into vectors and send them to JITServer. JITServer then uses the vectors to reconstruct the circular linked list on the server side so that correct offsets can be calculated by methods like TR_J9SharedCache::offsetInSharedCacheFromPointer. Removed TR_J9JITServerSharedCache::offsetInSharedCacheFromPointer, TR_J9JITServerSharedCache::pointerFromOffsetInSharedCache and isPointerInSharedCache because they are outdated and no longer needed. We can reuse the calculations of the base clase implementations.

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@mpirvu @ymanton Hi Marius and Younes, I have migrated changes from https://github.com/eclipse/openj9/pull/7209 to here. Now this only includes the multi-layered SCC change from master + my patch to make JITServer work.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Test failures:
```
J9vmTest_2
StringPeepholeTest_0  
cmdLineTester_gcsuballoctests_0
AttachAPISanity_0
```
We've seen last 2 before, but StringPeepholes is a new one. A crash during compilation, but outside ilgen/optmizer/codegen
```
Type=Segmentation error vmState=0x0005ffff
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007FAEF60B4530 Handler2=00007FAEF59ADB50 InaccessibleAddress=0000000000007140
RDI=00007FAEF005E628 RSI=0000000000007100 RAX=0000000000007100 RBX=00007FAEC80072A0
RCX=00007FAECEF25730 RDX=0000000000000000 R8=00007FAEF0060CF8 R9=0000000000000000
R10=0000000000000000 R11=0000000000000006 R12=00007FAEDEF3B070 R13=00007FAECEF25060
R14=0000000000007100 R15=00007FAECEF24A30
RIP=00007FAEF41E4B87 GS=0000 FS=0000 RSP=00007FAECEF246F0
EFlags=0000000000010206 CS=0033 RBP=00007FAECEF24DC0 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000007140
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 616f4c7373616c43 (f: 1935764608.000000, d: 2.200154e+161)
xmm2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm3 49294949425b4942 (f: 1113278848.000000, d: 2.819514e+44)
xmm4 4040404040404040 (f: 1077952512.000000, d: 3.250196e+01)
xmm5 5b5b5b5b5b5b5b5b (f: 1532713856.000000, d: 1.213625e+132)
xmm6 2020202020202020 (f: 538976256.000000, d: 6.013470e-154)
xmm7 2000000000000000 (f: 0.000000, d: 1.491668e-154)
xmm8 ff00000000000000 (f: 0.000000, d: -5.486124e+303)
xmm9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm10 00ffffffffffffff (f: 4294967296.000000, d: 7.291122e-304)
xmm11 0000000049d70a38 (f: 1238829568.000000, d: 6.120632e-315)
xmm12 000000004689a022 (f: 1183424512.000000, d: 5.846894e-315)
xmm13 0000000047ac082f (f: 1202456576.000000, d: 5.940925e-315)
xmm14 0000000048650dc0 (f: 1214582272.000000, d: 6.000833e-315)
xmm15 0000000046b73e38 (f: 1186414080.000000, d: 5.861665e-315)
Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so
Module_base_address=00007FAEF4021000

Method_being_compiled=java/lang/StringCoding.decode(Ljava/nio/charset/Charset;[BII)Ljava/lang/StringCoding$Result;
Target=2_90_20191003_332 (Linux 2.6.32-754.11.1.el6.x86_64)
CPU=amd64 (4 logical CPUs) (0x1ec001000 RAM)
----------- Stack Backtrace -----------
(0x00007FAEF41E4B87 [libj9jit29.so+0x1c3b87])
(0x00007FAEF432D3A8 [libj9jit29.so+0x30c3a8])
(0x00007FAEF42E4E9F [libj9jit29.so+0x2c3e9f])
(0x00007FAEF42EEE56 [libj9jit29.so+0x2cde56])
(0x00007FAEF41A5F19 [libj9jit29.so+0x184f19])
(0x00007FAEF41A65B8 [libj9jit29.so+0x1855b8])
(0x00007FAEF59AE8B3 [libj9prt29.so+0x1f8b3])
(0x00007FAEF41A8135 [libj9jit29.so+0x187135])
(0x00007FAEF41A86CE [libj9jit29.so+0x1876ce])
(0x00007FAEF41A4343 [libj9jit29.so+0x183343])
(0x00007FAEF41A4792 [libj9jit29.so+0x183792])
(0x00007FAEF41A483A [libj9jit29.so+0x18383a])
(0x00007FAEF59AE8B3 [libj9prt29.so+0x1f8b3])
(0x00007FAEF41A4C94 [libj9jit29.so+0x183c94])
(0x00007FAEF5E08156 [libj9thr29.so+0xe156])
(0x0000003545A07AA1 [libpthread.so.0+0x7aa1])
clone+0x6d (0x00000035456E8C4D [libc.so.6+0xe8c4d])
```

**Comment by harryyu1994** [comment]
My sanity test results with java 8 with `TEST_FLAG=AOT`

```
TEST TARGETS SUMMARY
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DISABLED test targets:
	recreateClassTest_0
	CFdumptest_0
	cmdLineTester_pltest_tty_extended_0
	cmdLineTester_pltest_numcpus_notBound_0
	cmdLineTester_pltest_numcpus_bound_win_0

SKIPPED test targets due to capabilities:
	cmdLineTester_pltest_hyp_HV_vmware_0 - capabilities (hypervisor:VMWare)
	cmdLineTester_pltest_hyp_HV_kvm_0 - capabilities (hypervisor:KVM)

PASSED test targets:
	jit_vich_0
	stringConcatOptTest_0
	jit_jitt_0
	jit_jitt_1
	jit_jitt_2
	jit_jitt_3
	jit_jar_0
	jit_tr_0
	jit_ra_0
	JLM_Tests_interface_SE80_0
	JLM_Tests_interface_SE80_1
	JLM_Tests_class_SE80_0
	JLM_Tests_class_SE80_1
	JLM_Tests_IBMinternal_SE80_0
	JLM_Tests_IBMinternal_SE80_1
	pthreadDestructor_0
	reattachAfterExit_0
	generalSanityTest_0
	truncatedReturnTest_0
	regressionFastresolve_mode150_0
	jsr335_interfacePrivateMethod_1
	AttachAPISanity_SE80_0
	CtorBCVTests_0
	JCL_Test_OutOfMemoryError_SE80_0
	JCL_Test_OutOfMemoryError_SE80_1
	J9VMInternals_Test_SE80_0
	J9VMInternals_Test_SE80_1
	JCL_TEST_Java-Security_SE80_0
	JCL_Test_JITHelpers_SE80_0
	JCL_TEST_MathMethods_0
	TestArrayCopy_2
	TestArrayCopy_3
	testReflectInvoke_0
	testInvokeSpecialInsideInterface_0
	reflect_0
	NoSuchMethodTests_0
	JCL_Test_Package_0
	hanoiTest_0
	memleaksTest_0
	fibTest_0
	testStringInterning_1
	testStringIndexOfString_0
	testStringIndexOfString_1
	testStringStreams_0
	floatSanityTests_0
	floatSanityTests_2
	FileSystem-isAccessUserOnlyTests_SE80_0
	TestFlushReflectionCache_SE80_0
	TestRefreshGCSpecialClassesCache_NOBCI_SE80_0
	TestRefreshGCSpecialClassesCache_BCI_FAST_HCR_SE80_0
	jsr335tests_SE80_1
	jsr335tests_SE80_3
	jsr335tests_SE80_5
	algotest2_0
	ctest_0
	jniargtests_0
	jniargtests_1
	jniargtests_2
	vmtest_0
	jsigjnitest_0
	gc_rwlocktest_0
	shrtest_linux_SE80_0
	thrstatetest_0
	SharedCPEntryInvokerTests_0
	SharedCPEntryInvokerTests_1
	UnsafeTests_SE80_0
	UnsafeTests_SE80_1
	J9vmTest_2
	J9vmTest_4
	J9vmTest_5
	jvmnativestest_0
	SharedClassesSysVTesting_0
	cmdLineTester_J9securityTests_0
	SCURLClassLoaderTests_SE80_1
	SCURLClassLoaderNPTests_SE80_1
	cmdLineTester_callsitedbgddrext_openj9_0
	cmdLineTest_J9test_SE80_0
	cmdLineTester_test_0
	cmdLineTester_GCRegressionTests_2
	cmdLineTester_GCRegressionTests_3
	cmdLineTest_gpTest_0
	cmdLineTester_jrvTest_0
	cmdLineTester_jvmtitests_5
	cmdLineTester_jvmtitests_7
	cmdLineTester_jvmtitests_8
	cmdLineTester_jvmtitests_hcr_SE80_7
	cmdLineTester_jvmtitests_hcr_SE80_8
	cmdLineTester_jvmtitests_hcr_SE80_10
	cmdLineTester_jvmtitests_debug_3
	cmdLineTester_jvmtitests_debug_5
	cmdLineTester_jvmtitests_debug_7
	cmdLineTester_jvmtitests_debug_8
	cmdLineTester_jvmtitests_debug_9
	cmdLineTester_jvmtitests_debug_11
	cmdLineTester_decompilationTests_1
	decompileAtMethodResolve_0
	cmdLineTester_libpathTestRtf_0
	cmdLineTester_libpathTestRtfChild_0
	cmdLineTester_loopReduction_0
	cmdLineTester_pltest_numcpus_bound_linux_0
	cmdLineTester_DataHelperTests_1
	testSCCMLListALLCaches_1
	testSCCMLTests1_openj9_1
	ShareClassesCMLOpenJ9_1
	cmdLineTester_SCCommandLineOptionTests_1
	cmdLineTester_SCHelperCompatibilityTests_unix_1
	cmdLineTester_ShareClassesSimpleSanity_1
	cmdLineTester_SCURLHelperTests_80_1
	cmdLineTest_sigxfszHandlingTest_0
	cmdLineTester_XcheckJNI_0
	testXXArgumentTesting_0

FAILED test targets:
	cmdLineTester_gcsuballoctests_0
	cmdLineTester_CryptoTest_0
	cmdLineTester_pltest_0

TOTAL: 200   EXECUTED: 114   PASSED: 111   FAILED: 3   DISABLED: 5   SKIPPED: 81
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

_sanity done
```

**Comment by harryyu1994** [comment]
Looks like it's intermittent, my own jdk11 personal build on jenkins:
```
19:18:50  	SharedCPEntryInvokerTests_1
19:18:50  	UnsafeTests_0
19:18:50  	UnsafeTests_1
19:18:50  	J9vmTest_2
19:18:50  	J9vmTest_4
19:18:50  	J9vmTest_5
19:18:50  	jvmnativestest_0
19:18:50  	SharedClassesSysVTesting_0
19:18:50  
19:18:50  FAILED test targets:
19:18:50  	cmdLineTester_gcsuballoctests_0
19:18:50  	AttachAPISanity_0
19:18:50  
19:18:50  TOTAL: 226   EXECUTED: 138   PASSED: 136   FAILED: 2   DISABLED: 4   SKIPPED: 84
19:18:50  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by harryyu1994** [comment]
Going to try to reproduce the `StringPeepholeTest_0` issue manually.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#jitaas

**Comment by harryyu1994** [comment]
I came up with a working version on my debug branch(by overriding the set of isPointerInSharedCache APIs for JITServer: https://github.com/harryyu1994/openj9/commit/5f23ac3e411ba41e1f86e3b60641ad04059541bf
Still need some time to figure out what exactly went wrong

**Comment by harryyu1994** [comment]
Looks like removing unused variable `UDATA _cacheStartAddress;` (even though it doesn't look like it's used anywhere) causes the testcase to fail. Looking into it.

**Comment by harryyu1994** [comment]
```
/**
      @class VMInfo
      @brief Struct which contains information about VM that does not change during its lifetime
   */
   struct VMInfo
      {
      void *_systemClassLoader;
      uintptrj_t _processID;
      bool _canMethodEnterEventBeHooked;
      bool _canMethodExitEventBeHooked;
      bool _usesDiscontiguousArraylets;
      bool _isIProfilerEnabled;
      int32_t _arrayletLeafLogSize;
      int32_t _arrayletLeafSize;
      uint64_t _overflowSafeAllocSize;
      int32_t _compressedReferenceShift;
      // UDATA _cacheStartAddress;
      bool _stringCompressionEnabled;
      bool _hasSharedClassCache;
      bool _elgibleForPersistIprofileInfo;
      TR_OpaqueClassBlock *_arrayTypeClasses[8];
      bool _reportByteCodeInfoAtCatchBlock;
      MM_GCReadBarrierType _readBarrierType;
      MM_GCWriteBarrierType _writeBarrierType;
      bool _compressObjectReferences;
      TR_ProcessorFeatureFlags _processorFeatureFlags;
      J9Method *_invokeWithArgumentsHelperMethod;
      void *_noTypeInvokeExactThunkHelper;
      void *_int64InvokeExactThunkHelper;
      void *_int32InvokeExactThunkHelper;
      void *_addressInvokeExactThunkHelper;
      void *_floatInvokeExactThunkHelper;
      void *_doubleInvokeExactThunkHelper;
      size_t _interpreterVTableOffset;
      J9SharedClassCacheDescriptor *_j9SharedClassCacheDescriptorList;
      }; // struct VMInfo
```
The crash on JITClient happens when we remove `_cacheStartAddress` from `VMInfo`, something I'm yet to figure out why.

**Comment by harryyu1994** [comment]
Simply by reordering the fields in `VMInfo` struct, we are able to get rid of the error. I do not understand why though.

**Comment by mpirvu** [comment]
> Simply by reordering the fields in VMInfo struct, we are able to get rid of the error. I do not understand why though. Perhaps we need a proper default constructor for VMInfo,

From what order to what order? This looks that a hidden bug waiting to happen

**Comment by harryyu1994** [comment]
From this order
```
struct VMInfo
      {
      void *_systemClassLoader;
      uintptrj_t _processID;
      bool _canMethodEnterEventBeHooked;
      bool _canMethodExitEventBeHooked;
      bool _usesDiscontiguousArraylets;
      bool _isIProfilerEnabled;
      int32_t _arrayletLeafLogSize;
      int32_t _arrayletLeafSize;
      uint64_t _overflowSafeAllocSize;
      int32_t _compressedReferenceShift;
      // UDATA _cacheStartAddress;
      bool _stringCompressionEnabled;
      bool _hasSharedClassCache;
      bool _elgibleForPersistIprofileInfo;
      TR_OpaqueClassBlock *_arrayTypeClasses[8];
      bool _reportByteCodeInfoAtCatchBlock;
      MM_GCReadBarrierType _readBarrierType;
      MM_GCWriteBarrierType _writeBarrierType;
      bool _compressObjectReferences;
      TR_ProcessorFeatureFlags _processorFeatureFlags;
      J9Method *_invokeWithArgumentsHelperMethod;
      void *_noTypeInvokeExactThunkHelper;
      void *_int64InvokeExactThunkHelper;
      void *_int32InvokeExactThunkHelper;
      void *_addressInvokeExactThunkHelper;
      void *_floatInvokeExactThunkHelper;
      void *_doubleInvokeExactThunkHelper;
      size_t _interpreterVTableOffset;
      J9SharedClassCacheDescriptor *_j9SharedClassCacheDescriptorList;
      }; // struct VMInfo
```
to this order:
```
struct VMInfo
      {
      void *_systemClassLoader;
      uintptrj_t _processID;
      bool _canMethodEnterEventBeHooked;
      bool _canMethodExitEventBeHooked;
      bool _usesDiscontiguousArraylets;
      bool _isIProfilerEnabled;
      int32_t _arrayletLeafLogSize;
      int32_t _arrayletLeafSize;
      uint64_t _overflowSafeAllocSize;
      int32_t _compressedReferenceShift;
      J9SharedClassCacheDescriptor *_j9SharedClassCacheDescriptorList;
      bool _stringCompressionEnabled;
      bool _hasSharedClassCache;
      bool _elgibleForPersistIprofileInfo;
      TR_OpaqueClassBlock *_arrayTypeClasses[8];
      bool _reportByteCodeInfoAtCatchBlock;
      MM_GCReadBarrierType _readBarrierType;
      MM_GCWriteBarrierType _writeBarrierType;
      bool _compressObjectReferences;
      TR_ProcessorFeatureFlags _processorFeatureFlags;
      J9Method *_invokeWithArgumentsHelperMethod;
      void *_noTypeInvokeExactThunkHelper;
      void *_int64InvokeExactThunkHelper;
      void *_int32InvokeExactThunkHelper;
      void *_addressInvokeExactThunkHelper;
      void *_floatInvokeExactThunkHelper;
      void *_doubleInvokeExactThunkHelper;
      size_t _interpreterVTableOffset;
      }; // struct VMInfo
```

**Comment by harryyu1994** [comment]
> > Simply by reordering the fields in VMInfo struct, we are able to get rid of the error. I do not understand why though. Perhaps we need a proper default constructor for VMInfo,
> 
> From what order to what order? This looks that a hidden bug waiting to happen

Essentially moving the new `J9SharedClassCacheDescriptor *_j9SharedClassCacheDescriptorList;` to the location of the old `_cacheStartAddress`.

**Comment by ymanton** [comment]
Is the crash that this move fixes the one with the following backtrace? It's hard to see how they are related. This backtrace looks like a crash due to a bad RAM class pointer being passed to the client, but the SCC deals with ROM classes so its hard to connect the two.

> Going to try to reproduce the `StringPeepholeTest_0` issue manually.
> 
> ```
> #13 0x00007ff9fc7facf7 in TR_J9VMBase::getMethods(TR_OpaqueClassBlock*) [clone .localalias.222] ()
>    from /root/Harry_JITaaS_Full_Build/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/lib/compressedrefs/libj9jit29.so
> #14 0x00007ff9fc94551b in JITServerHelpers::packRemoteROMClassInfo[abi:cxx11](J9Class*, J9VMThread*, TR_Memory*) ()
>    from /root/Harry_JITaaS_Full_Build/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/lib/compressedrefs/libj9jit29.so
> #15 0x00007ff9fc8fc4fa in handleServerMessage(JITServer::ClientStream*, TR_J9VM*, JITServer::MessageType&) ()
>    from /root/Harry_JITaaS_Full_Build/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/lib/compressedrefs/libj9jit29.so
> #16 0x00007ff9fc9072aa in remoteCompile(J9VMThread*, TR::Compilation*, TR_ResolvedMethod*, J9Method*, TR::IlGeneratorMethodDetails&, TR::CompilationInfoPerThreadBase*) ()
>    from /root/Harry_JITaaS_Full_Build/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/lib/compressedrefs/libj9jit29.so
> ```

**Comment by harryyu1994** [comment]
> Is the crash that this move fixes the one with the following backtrace? It's hard to see how they are related. This backtrace looks like a crash due to a bad RAM class pointer being passed to the client, but the SCC deals with ROM classes so its hard to connect the two.
> 
> > Going to try to reproduce the `StringPeepholeTest_0` issue manually.
> > ```
> > #13 0x00007ff9fc7facf7 in TR_J9VMBase::getMethods(TR_OpaqueClassBlock*) [clone .localalias.222] ()
> >    from /root/Harry_JITaaS_Full_Build/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/lib/compressedrefs/libj9jit29.so
> > #14 0x00007ff9fc94551b in JITServerHelpers::packRemoteROMClassInfo[abi:cxx11](J9Class*, J9VMThread*, TR_Memory*) ()
> >    from /root/Harry_JITaaS_Full_Build/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/lib/compressedrefs/libj9jit29.so
> > #15 0x00007ff9fc8fc4fa in handleServerMessage(JITServer::ClientStream*, TR_J9VM*, JITServer::MessageType&) ()
> >    from /root/Harry_JITaaS_Full_Build/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/lib/compressedrefs/libj9jit29.so
> > #16 0x00007ff9fc9072aa in remoteCompile(J9VMThread*, TR::Compilation*, TR_ResolvedMethod*, J9Method*, TR::IlGeneratorMethodDetails&, TR::CompilationInfoPerThreadBase*) ()
> >    from /root/Harry_JITaaS_Full_Build/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/lib/compressedrefs/libj9jit29.so
> > ```

Yes that's the crash this move fixes.

**Comment by mpirvu** [comment]
Could you please check that all fields from VMInfo struct are initialized properly?

Also, just in case this is a weird padding problem, could you change this order
```
      uint64_t _overflowSafeAllocSize;
      int32_t _compressedReferenceShift;
      // UDATA _cacheStartAddress;
      bool _stringCompressionEnabled;
      bool _hasSharedClassCache;
      bool _elgibleForPersistIprofileInfo;
      TR_OpaqueClassBlock *_arrayTypeClasses[8];
      bool _reportByteCodeInfoAtCatchBlock;
```
into
```
      uint64_t _overflowSafeAllocSize;
      int32_t _compressedReferenceShift;
      // UDATA _cacheStartAddress;
      bool _stringCompressionEnabled;
      bool _hasSharedClassCache;
      bool _elgibleForPersistIprofileInfo;
      bool _reportByteCodeInfoAtCatchBlock;
      TR_OpaqueClassBlock *_arrayTypeClasses[8];
```
basically moving `bool _reportByteCodeInfoAtCatchBlock;` up so that you have 4 bools in sequence.

**Comment by harryyu1994** [comment]
I checked that all fields are properly initialized. The current code works fine.

**Comment by harryyu1994** [comment]
functional.extended passed cleanly. Only one known failure(cmdLineTester_gcsuballoctests_0) with functional.sanity.

**Comment by harryyu1994** [comment]
actually JITServer crashed during functional.extended.

**Comment by mpirvu** [comment]
> actually JITServer crashed during functional.extended. 

You could be hitting this issue:  https://github.com/eclipse/openj9/issues/7361

**Comment by mpirvu** [comment]
I pushed one of Annabelle's commits and now there are conflicts again. However, her changes were small so I expected this to be an easy rebase.

**Comment by harryyu1994** [comment]
Rebased

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Only the known `cmdLineTester_gcsuballoctests_0` test failed, hence merging.

**Pull request merged**
