### PR TITLE
WIP Build Windows jdk8 with VS2017

### PR DESCRIPTION
**Pull request by pshipton**

### CODE REVIEW

**Comment by pshipton** [comment]
@jdekonin I tried a Pipeline build with this change, but it didn't take affect. Is there a way to get a build other than manually?
https://ci.eclipse.org/openj9/job/Build-JDK8-win_x86-64_cmprssptrs/924

**Comment by jdekonin** [comment]
jenkins compile win,win32 jdk8

**Comment by jdekonin** [comment]
jenkins compile win jdk8

**Comment by pshipton** [comment]
@jdekonin it did pick up the `--with-toolchain-version=2017` in the PR build. Failed for other reasons.

```
20:13:36 configure: Could not compile and link with freetype. This might be a 32/64-bit mismatch.
20:13:36 configure: Using FREETYPE_CFLAGS=-I/cygdrive/c/openjdk/freetype-2.5.3/include and FREETYPE_LIBS=/cygdrive/c/openjdk/freetype-2.5.3/lib64/freetype.lib
20:13:36 configure: error: Can not continue without freetype. 
```

The output also contains
`20:12:53 configure: Found Microsoft Visual Studio 2017 - CURRENTLY NOT WORKING`

**Comment by jdekonin** [comment]
Those are the same errors I got when I tried myself last week.  I initially thought I did something wrong, but not now.  For the record this is how win32, win64 failed with the error @pshipton posted in his comment.
```
19:51:40 checking for Visual Studio variables... ok
19:51:40 configure: Found msvcp100.dll at /cygdrive/c/Windows/system32/msvcp100.dll using well-known location in SYSTEMROOT
19:51:40 checking found msvcp100.dll architecture... incorrect, ignoring
19:51:40 configure: The file type of the located msvcp100.dll is PE32+ executable (DLL) (GUI) x86-64, for MS Windows
19:51:44 checking for msvcp100.dll... no
19:51:44 configure: error: Could not find msvcp100.dll. Please specify using --with-msvcp-dll.
```

**Pull request closed without merging**
