### PR TITLE
Remove old pipeline files

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Pipeline* files
- Build* files
- Test* files
- These have been replaced by Pipeline-Build-Test-Any-Platform
  and Build-Test-Any-Platform and Adopt's openjdk-tests

[skip ci]
Issue #1897

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@vsebe please review
All the Build* and Pipeline* jobs now use the new generic files.

**Comment by vsebe** [comment]
The `Test*` pipelines could also be removed. The Jenkins `Test-Extended|Sanity-JDK*` jobs could use Build-Test-Any-Platform too.

On JDK 8 & 10 the aix, and p|x|zlinux files are not used anymore, they can safely be deleted.

The `Test-Extended|Sanity-JDK9-*`, `Test-Extended|Sanity-JDK8|10-win*` pipelines are still in use. 
The `Test-Extended|Sanity-JDK8|10-win*` will be replaced by AdoptOpenJDK/openjdk-tests files soon. 
The `Test-Extended|Sanity-JDK9-*` would probably continue to be used even if occasionally. They should be replaced by Build-Test-Any-Platform.

**Comment by AdamBrousseau** [comment]
I would prefer to remove them all in 1 shot. Apparently Win is close. I will mark this back to WIP and then we can add the test files when we're done with them.

**Comment by AdamBrousseau** [comment]
blocked by #2638

**Comment by AdamBrousseau** [comment]
@smlambert for final review

**Pull request merged**
