### PR TITLE
Fix getUnixPID() for jdk11+ and stop waiting for tests after 10 min

### PR DESCRIPTION
**Pull request by pshipton**
Fixes https://github.com/eclipse/openj9/issues/11196
Fixes https://github.com/eclipse/openj9/issues/11197

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
jenkins test sanity all jdk8,jdk11

**Comment by llxia** [comment]
Test compilation error:

```
13:53:21      [javac] /home/****/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_Personal_testList_1/openjdk-tests/functional/cmdline_options_tester/src/Test.java:432: error: cannot find symbol
13:53:21      [javac] 			Method pidMethod = Process.class.getMethod("pid");
13:53:21      [javac] 			^
13:53:21      [javac]   symbol:   class Method
13:53:21      [javac]   location: class Test
13:53:21      [javac] Note: Some input files use unchecked or unsafe operations.
13:53:21      [javac] Note: Recompile with -Xlint:unchecked for details.
13:53:21      [javac] 1 error
```

**Comment by pshipton** [comment]
Missing import.

jenkins test sanity zlinux jdk8,jdk11

**Comment by pshipton** [comment]
@llxia fixed now

**Review by llxia — APPROVED** [review]

**Pull request merged**
