### PR TITLE
Reduce limits for keeping artifacts and logs

### PR DESCRIPTION
**Pull request by pshipton**
Try to avoid running out of space, in particular before testing for 0.21.0 M2 this weekend.

### CODE REVIEW

**Comment by pshipton** [comment]
@AdamBrousseau 
- do the build_discarder settings get rid of associated artifacts?
- what is the Pipeline setting for? It seems quite high.

**Comment by AdamBrousseau** [comment]
There's a comment a few lines up
`if numArtifacts not set, use build_discarder`
which is the case for `osu`, so yes, these setting will not only reduce logs but also reduce artifacts.

`Pipeline` is for the middle layer build, which does not archive artifacts. It is reused between all the build identifiers so that is why the count is high.

**Comment by pshipton** [comment]
Today's space usage was reported as `877G/985G -> 94%`, at the rate it has been increasing, we could run out by the weekend.

**Comment by keithc-ca** [comment]
Is the plan to revert this once #9996 is fixed?

**Comment by pshipton** [comment]
We can revert it, or part of it once there is more space available, however it may be obtained.

**Pull request merged**
