### PR TITLE
Look for right caller method when handling OSR in context of inliner

### PR DESCRIPTION
**Pull request by hzongaro**
In many places, OSR-related code in the inliner is calling `getOwningMethodSymbol()` on a symbol reference in order to access information about the calling method.  However, the owning method for a symbol reference is not necessarily the calling method.

Instead, code should call `getInlinedResolvedMethodSymbol()` on the `TR::Compilation` object for the bytecode's caller index or, if the caller index is -1, call `getMethodSymbol()`.

Signed-off-by:  Henry Zongaro <zongaro@ca.ibm.com>

### CODE REVIEW

**Comment by hzongaro** [comment]
I have marked this pull request as a work in progress as it interacts with [OMR pull request #4177](https://github.com/eclipse/omr/pull/4177), which makes the same change in OSR-related inliner code in OMR.  Andrew Craik @andrewcraik , who advised me on this fix, indicated that the way the calling method is found should be kept consistent.

So, I'm wondering whether I should protect the change in OMR under some OpenJ9-specific macro, and mark this OpenJ9 pull request dependent on the corresponding OMR pull request, so that the change in OMR is only enabled when the change in OpenJ9 is available and enabled.

Once both pull requests were merged, I would then submit new pull requests so that it would no longer be protected by a macro.

**Comment by hzongaro** [comment]
I've put the changes under #if defined(INLINER_OSR_CALLING_METHOD) so that they can be enabled at the same time with corresponding changes in OMR.   Removed the WIP prefix from this pull request.

I will submit a subsequent pull requests to make the change unconditional once its been enabled in OMR.

**Comment by andrewcraik** [comment]
No functional change at this time - change looks good - will merge after sanity

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Pull request merged**
