### PR TITLE
Resynchronize the relocation header size table and introduce TR_MethodCallAddress relocation entry on Z

### PR DESCRIPTION
**Pull request by dchopra001**
Signed-off-by: Dhruv Chopra <Dhruv.C.Chopra@ibm.com>

### CODE REVIEW

**Comment by dchopra001** [comment]
@mpirvu I have done the re-synchronization here: 166b883a7844bab1cd4081edb8def7a7261c0064

**Comment by mpirvu** [comment]
> @mpirvu I have done the re-synchronization here: 166b883

I see that the 32-bit versions of `uint32_t J9::X86::AheadOfTimeCompile::_relocationTargetTypeToHeaderSizeMap[TR_NumExternalRelocationKinds] ` have a significantly smaller number of entries. @dsouzai is that by design or it's something we need to fix?

**Comment by dsouzai** [comment]
> is that by design or it's something we need to fix?

Not by design, the tables have just become out of date. The long term fix is https://github.com/eclipse/openj9/issues/4803, but I suppose until then, the 32-bit version _should_ have the same number of entries as the 64-bit version.

**Comment by mpirvu** [comment]
@dchopra001 Would you be able to fix the 32-bit tables as well? Thanks

**Comment by mpirvu** [comment]
I have opened #6968 to tackle the number of entries in `J9::X86::AheadOfTimeCompile::_relocationTargetTypeToHeaderSizeMap` for 32-bit

**Comment by mpirvu** [comment]
Jenkins test sanity xlinux,zlinux jdk8,jdk11

**Comment by mpirvu** [comment]
Tests passed, so merging.

**Pull request merged**
