### PR TITLE
Add JAVA_VERSION to JDK_VERSION mapping for Java12

### PR DESCRIPTION
**Pull request by llxia**
Fixes: #4638
[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Just a note, this temporary code as the following will be removed once we completely switch to 
`JDK_VERSION`:

```
ifeq ($(JAVA_VERSION), SE80)
	JDK_VERSION:=8
endif
ifeq ($(JAVA_VERSION), SE90)
	JDK_VERSION:=9
endif
ifeq ($(JAVA_VERSION), SE100)
	JDK_VERSION:=10
endif
ifeq ($(JAVA_VERSION), SE110)
	JDK_VERSION:=11
endif
ifeq ($(JAVA_VERSION), SE120)
	JDK_VERSION:=12
endif
```

**Comment by llxia** [comment]
jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
Tested in Grinder for Java12: https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/254/consoleFull
DDR compilation passed. It failed in `Java8andUp` compilation as I do not apply PR #4531 in my branch.

**Comment by smlambert** [comment]
I do not need to wait for sanity run to complete, the test for this PR was that they would still compile and execute.

**Pull request merged**
