### PR TITLE
Turn on nestmates test in Java11

### PR DESCRIPTION
**Pull request by tajila**
Turn on nestmates test in Java11

Signed-off-by: tajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
@llxia can you please review

**Comment by tajila** [comment]
> Also, does this mean we will not have JAVA_VERSION=Valhalla case any more?
I'd like to keep it for the valueTypes work and Nestmates2

**Comment by llxia** [comment]
Jenkins test sanity plinux jdk10

**Comment by tajila** [comment]
@llxia can this be merged?

**Comment by llxia** [comment]
Jenkins test sanity xlinux jdk11

**Comment by tajila** [comment]
The JDK11 failures are in Java8andUp

**Comment by llxia** [comment]
JDK11 test compilation failed due to https://github.com/eclipse/openj9/pull/2503
Cannot verify the change in PR build. 
The change LGTM. Merge it for now.

**Pull request merged**
