### PR TITLE
Remove OpenJ9 Java code surrounded by the Panama JPP flag

### PR DESCRIPTION
**Pull request by babsingh**
Related: #11269

This PR only removes the:
- Java code surrounded by the `Panama` JPP flag
- `PANAMA` JPP configuration
- `Panama` JPP flag

The corresponding native and test code will be be removed in separate
PRs.

Depends on https://github.com/eclipse/openj9/pull/11437.

Co-authored-by: Tobi Ajila <atobia@ca.ibm.com>
Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by babsingh** [comment]
@tajila request for review.

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity win jdk8,jdk11,jdknext

**Comment by babsingh** [comment]
Windows build failed due to a timeout: https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/1003/

```
Timeout has been exceeded
Finished: ABORTED
```

**Comment by tajila** [comment]
Jenkins test sanity zlinux jdk8

**Comment by tajila** [comment]
@babsingh there are merge confilcts

**Comment by babsingh** [comment]
> there are merge confilcts

Rebased to resolve conflicts. Good to be merged. Previous PR builds had passed.

**Pull request merged**
