### PR TITLE
WIP: only publish TAP results

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Remove JUnit and TestNG result publishing

[ci skip]

Issue #981

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Adam test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
adam test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
adam test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
adam test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
adam test sanity

**Comment by AdamBrousseau** [comment]
adam test all

**Comment by AdamBrousseau** [comment]
jenkins test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
jenkins test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
jenkins test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
jenkins test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
adam test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
adam test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
adam test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
adam test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
adam test sanity plinux jdk9

**Comment by AdamBrousseau** [comment]
jenkins help

**Comment by genie-openj9** [comment]
[Jenkins README](https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/README.md)
Syntax: `Jenkins <build type> <level> [<platform(s)> [<java version(s)> [depends <org>/<repo>#<PR_ID>]]]`
- Build Types: `compile,test`
- Levels: `sanity,extended` (only if Build Type is test)
- Platforms: `zlinux,plinux,aix`
- Java Versions: `jdk8,jdk9`
- Orgs: `eclipse,ibmruntimes`
- Repos: `omr,openj9-omr,openj9,openj9-openjdk-jdk[8,9]`
- PR_ID: Pull Request ID containing the dependent change
##### Note: You can use keyword all for level, platform or version

**Pull request closed without merging**
