### PR TITLE
Remove deadcode in X86::J9TreeEvaluator

### PR DESCRIPTION
**Pull request by 0dvictor**
General code cleanup, removing deadcode.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
Could you just explain a little bit about how the cases you are cleaning up as dead are being handled in the codegen?

**Comment by 0dvictor** [comment]
The codes related to iabs and labs are not deleted in this PR. They won't be removed until OMR's evaluators are ready.

**Comment by andrewcraik** [comment]
ok makes sense

**Comment by andrewcraik** [comment]
Jenkins test xlinux sanity

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux

**Comment by andrewcraik** [comment]
Jenkins test sanity win

**Comment by andrewcraik** [comment]
@0dvictor I think a rebase forward is warranted so we can try to get the sanity builds clean and get this merged.

**Comment by 0dvictor** [comment]
Rebased.

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win

**Comment by andrewcraik** [comment]
windows fails are due to #2129

**Pull request merged**
