### PR TITLE
enable cmdLine tests on OpenJ9

### PR DESCRIPTION
**Pull request by TianyuZuo**
* enable cmdLine tests on Openj9
* excluded some failed test and open issue for them

Fixes:#305
Signed-off-by: Tianyu Zuo <tianyu@ca.ibm.com>

### CODE REVIEW

**Comment by TianyuZuo** [comment]
Reviewer: @renfeiw  
Reviewer: @llxia 

change set passed on local tests sanity and extended

**Comment by llxia** [comment]
Please open issues to track excluded tests.
Please do not edit space for lines that you are not updating. Thanks.

**Comment by TianyuZuo** [comment]
@llxia  related issues have been open and change set updated.

**Comment by llxia** [comment]
Thanks for your update. :+1:

**Pull request merged**
