### PR TITLE
Enable openssl on OSX for JDK8 & JDK11

### PR DESCRIPTION
**Pull request by jdekonin**
* [skip ci]
* related #31

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
fyi @pshipton

**Comment by jdekonin** [comment]
Note there is no JDK available devices to perform a pull request against at this time.  Although we might have 2 online later today or tomorrow???

**Comment by pshipton** [comment]
> Note there is no JDK available devices to perform a pull request against at this time. Although we might have 2 online later today or tomorrow???

I don't understand this comment. Is it specific to jdk8?

**Comment by pshipton** [comment]
jenkins compile osx jdk8

**Comment by pshipton** [comment]
jenkins compile osx jdk11

**Comment by pshipton** [comment]
I guess #3992 needs to be merged first, because we need 
```
extra_getsource_options:
  11: '--openssl-version=1.1.1'
```
@jdekonin I think this same change could be added to this PR.

**Comment by pshipton** [comment]
@jdekonin please rebase to pick up the #3992 changes, and then I can rerun the PR testing.

**Comment by jdekonin** [comment]
jenkins compile osx jdk11

**Comment by jdekonin** [comment]
jenkins compile osx jdk8

**Comment by jdekonin** [comment]
jenkins compile osx jdk8

**Comment by jdekonin** [comment]
jenkins compile osx jdk8

**Comment by jdekonin** [comment]
jenkins compile osx jdk8

**Comment by pshipton** [comment]
jdk11 is confirmed working, and the jdk8 build is failing for other reasons that will be addressed separately.

**Pull request merged**
