### PR TITLE
Delete obsolete Dockerfiles and build instructions for jdk9, 10, 12

### PR DESCRIPTION
**Pull request by pshipton**
These older, out of support versions can no longer be built with OpenJ9. 

Update the Dockerfile and README in the docker/test directory to refer
to jdk11 instead of jdk9.

I didn't delete the jdk9 arm 32-bit Dockerfile as it may contain some
useful information if support ever picks up for this processor.

Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>

### CODE REVIEW

**Comment by keithc-ca** [comment]
What should we do about `buildenv/docker/test/Dockerfile` which makes reference to some of the deleted Dockerfiles?

**Comment by pshipton** [comment]
I've updated the test/Dockerfile and README to refer to jdk11 instead of jdk9. Does that fix the concern?

**Comment by keithc-ca** [comment]
@0xdaryl Are you happy with this too?

**Comment by keithc-ca** [comment]
No response from @0xdaryl - assuming no news is good news.

**Pull request merged**
