### PR TITLE
Fix value Type generator

### PR DESCRIPTION
**Pull request by tajila**
Fix value Type generator

This PR contains the changes in A. Crowthers PR in #3960 minus 
the additional tests for the verifier changes.

Since the vm verifier changes are not in yet those will come at a 
later time.

Signed-off-by: tajila <atobia@ca.ibm.com>

### CODE REVIEW

**Comment by tajila** [comment]
@llxia Please review these changes

**Comment by llxia** [comment]
Please fix the copyright issue. Thsnks.

**Comment by tajila** [comment]
@llxia I have fixed the copywrites

**Comment by llxia** [comment]
@AdamBrousseau Is there any update on Valhalla PR build? Thanks

**Comment by llxia** [comment]
Thanks Tobi for sending me the internal build link.
Will forgo the PR build as it will not build/execute Valhalla tests.

**Comment by AdamBrousseau** [comment]
No update from me on Valhalla builds. I asked Tobi to open an issue so we can prioritise. It will be blocked by #2836 too.

**Pull request merged**
