### PR TITLE
Fix the JAVA_VERSION conditional logic in build.xml

### LINKED ISSUE #1543: JDK10 sanity tests don't compile
See the problem by running `jenkins test sanity <plat> jdk10`. We don't think the problem is platform specific.

https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK10-aix_ppc-64_cmprssptrs/1/console

### PR DESCRIPTION
**Pull request by renfeiw**
- The current logic doesn't support JAVA_VERSION higher than SE90.
- Replace logic from JAVA_VERSION==SE90 to JAVA_VERSION!=SE80.

Fixes #1543

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewers: @llxia @smlambert

**Comment by smlambert** [comment]
Jenkins test sanity plinux jdk10

**Comment by smlambert** [comment]
Jenkins test sanity plinux jdk9

**Comment by llxia** [comment]
Jenkins test sanity plinux jdk9

**Comment by smlambert** [comment]
Jenkins test sanity plinux jdk10

**Pull request merged**
