### PR TITLE
Report final field modification by calling runtime helper

### PR DESCRIPTION
**Pull request by liqunl**
Keeping the Unsafe call as the slow path is suboptimal compared to using
the runtime helper.
- Unsafe call consumes more arguments, which means more registers.
- Unsafe call has more use and def aliases and not transparent to the
  optimizer.
- For Unsafe call that returns a result, a temp has to be created to
  store result from the fast path and from the slow path.

Therefore, report the ilegal modification through the runtime helper
jitReportFinalFieldModified.

Also Enable the illegal write notification in this PR.

closes: #4385

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
Depends on https://github.com/eclipse/omr/pull/3523 and https://github.com/eclipse/omr/pull/3528.
WIP this PR, will add a commit to enable notification once perf evaluation is done.

**Comment by liqunl** [comment]
Performance comparison between proposed change and baseline. Positive number means better than baseline, negative number means worse than baseline.

The performance difference between the proposed change and the baseline is within the noise margin for the following benchmarks.

| Benchmark | Relative perf| Standard deviation|
| ------------- | ------------- |------------- |
| daytrader3 | +0.02% | 0.38% |
| AcmeAir | -0.32% | 0.8% |
| ILOG 300RuleSet | +0.11% | 3.65% |
| ILOG 5Path| -0.15% | 1.43% |
| Pagerank  | -0.45%  | 1.34% |
| Sort | +0.01% | 2.07% |
| Terasort | +0.08% | 1.15%
|Wordcount|+0.4%|1.55%|

**Comment by liqunl** [comment]
@andrewcraik Could you review?

**Comment by andrewcraik** [comment]
Have you looked at any startup metrics to see what impact the compiel-time has on them specifically? I suspect it should be fine since HiBench is ok but an explicit measure would be good. Actual changes look ok to me.

**Comment by liqunl** [comment]
@andrewcraik Yes, looked at liberty start up sufpdt7, there is no regression. 

| Benchmark | Relative perf | Standard deviation|
| ------------- | ------------- |------------- |
| sufpdt7 | +0.04% | 1.4% |

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Comment by andrewcraik** [comment]
@mpirvu any object to turning this on again? @liqunl has fixed the regressions and the data looks good. If any perf issues surface again we'll have a look for sure, but I think this should be good to go now.

**Comment by mpirvu** [comment]
If start-up regressions have been eliminated I am ok with the change.

**Comment by liqunl** [comment]
@mpirvu Yes, the start up is verified on sufpdt7, a liberty DT7 benchmark.

**Pull request merged**
