### PR TITLE
Fix variable precision off by one issue and improve checking

### PR DESCRIPTION
**Pull request by fjeremic**
ZAP instruction immediate length has an implied length of one if zero is
encoded in the instruction. As such we need to determine the number of
bytes from the precision minus one. 

In addition add TP instructions for pd2i and pd2l (as well as variable
precision) to check the contents of the packed decimal before executing
ZAP / CVB / CVBG. This is to ensure that if a zero initialized array is
passed through we directly branch to the OOL path to execute the Java
implementation rather than taking the signal handler path.

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
@NigelYiboYu could you please review? We may need to also benchmark the `TP` change.

**Comment by mgaudet** [comment]
Your commit message got spliced a bit during editing, so the first sentence half-repeats.

**Comment by fjeremic** [comment]
> Your commit message got spliced a bit during editing, so the first sentence half-repeats.

You're right! Thanks! Fixed in 78f75f5

**Comment by fjeremic** [comment]
Replaced by a more complete version tackling vector registers as well in https://github.com/eclipse/openj9/pull/226.

**Pull request closed without merging**
