### PR TITLE
Fix J9BuildFlags aliases

### PR DESCRIPTION
**Pull request by keithc-ca**
The DDR tools from OMR, normally generate constants with names as they appear in the source code. Unfortunately, the legacy tools used in IBM builds yield different names for 'build flags'. A field override was added to provide compatibility with those legacy tools for s390
```
  J9VM_ARCH_S390=arch_s390
```
but not for other architectures. `J9ConfigFlags` was introduced in an attempt to handle this difference in naming convention, but it incorrectly assumed the fields it referenced would be dynamically generated according to the blob found in the associated core file, rather than being fixed at build time. The set of aliases here replaces the ineffective mapping in `J9ConfigFlags`. The result is that OpenJ9 builds have additional fields in `J9BuildFlags` that are copied from the OMR-derived names. For example, `arch_x86` is present when the legacy tools are used; when OMR tools are used, `arch_x86` is a copy of `J9VM_ARCH_X86`.

Remove `J9ConfigFlags` and redirect references to `J9BuildFlags`.

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile xlinux jdk11

**Comment by pshipton** [comment]
jenkins test extended zlinux jdk8

**Comment by pshipton** [comment]
There is a build failure, see
https://ci.eclipse.org/openj9/job/Build_JDK8_ppc64_aix_Personal/561
```
11:42:58  Compiling tools to generate DDR pointer classes and structure stubs
11:42:59  /home/jenkins/workspace/Build_JDK8_ppc64_aix_Personal/openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/BytecodeGenerator.java:88: error: method addFlagAliasesFor in class BytecodeGenerator cannot be applied to given types;
11:42:59  		return addFlagAliasesFor(new HashMap<>(), className);
11:42:59  		       ^
11:42:59    required: Map<String,String>,String
11:42:59    found: HashMap<Object,Object>,String
11:42:59    reason: actual argument HashMap<Object,Object> cannot be converted to Map<String,String> by method invocation conversion
11:43:01  1 error
```

**Comment by keithc-ca** [comment]
I guess the type inference in Java 8 isn't what we've gotten used to in newer versions: I'll fix this.

**Pull request merged**
