### PR TITLE
WIP: Atomic-free JNI work

### PR DESCRIPTION
**Pull request by gacholio**
- refactor code to make it more readable, less invasive
- add build flags to control vm access options
- fix AMD64 JIT to be consistent with VM

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
jenkins test sanity plinux

**Comment by gacholio** [comment]
Review changes made.

**Comment by DanHeidinga** [comment]
Jenkins test sanity all jdk8

**Comment by fjeremic** [comment]
> Approving the JIT changes as well as they are only ever run on the the Atomic Free prototype. They'll need another look over by the JIT team before the prototype gets enabled.

@0dvictor FYI so this is on your radar in the near future.

**Pull request merged**
