### PR TITLE
Fix decomposition of blob version

### PR DESCRIPTION
**Pull request by keithc-ca**
The expression to compute the fourth byte was wrong.

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
@keithc-ca does this fix anything important, should it be included in the 0.14 release?

**Comment by pshipton** [comment]
jenkins test extended zlinux jdk8

**Comment by pshipton** [comment]
Testing with internal build 413864

**Comment by keithc-ca** [comment]
> does this fix anything important, should it be included in the 0.14 release?

The only use of the broken method that I could find didn't use the fourth byte (that should now be correct), so I don't think think this needs to go into the 0.14 release.

**Pull request merged**
