### PR TITLE
Remove initialization logic from default CodeGenerator constructor

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Remove default CodeGenerator constructor implementation and make protected
* Add warning comment to CodeGenerator constructor

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Requires eclipse/omr#5584 to merge and promote first.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11 depends eclipse/omr#5584

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
@dsouzai @ymanton : Would one of you mind reviewing and merging this please?  It is simply cleaning up the now-obsolete CodeGenerator constructor initialization (the initialization is now handled by the `initialize()` function, not the constructor).

**Comment by ymanton** [comment]
Jenkins test sanity all jdk11

**Comment by ymanton** [comment]
Woops, didn't see that testing was already done and passed completely. Cancelled the job on Eclipse CI.

**Comment by 0xdaryl** [comment]
>Woops, didn't see that testing was already done and passed completely. Cancelled the job on Eclipse CI.

Thanks.  Can you merge then please?  :-)

**Comment by pshipton** [comment]
@ymanton not sure what happened, but the aborted build was still running on all the worker nodes and blocking anything else from running. I forcibly terminated the job to clear the worker nodes. If you abort something, pls make sure it does stop.

**Pull request merged**
