### PR TITLE
Fix the incorrect whitespace characters on the comments

### PR DESCRIPTION
**Pull request by doomerxe**
Fix comments which contain incorrect whitespace characters.

Signed-off-by: Jiahan Xi <doomerXe@gmail.com>

### CODE REVIEW

**Comment by doomerxe** [comment]
Hi @hangshao0, could you please review it? Thank you!

**Comment by pshipton** [comment]
There are some non-spaces in oti/bcverify_api.h, can you please fix those as well.

**Comment by doomerxe** [comment]
> There are some non-spaces in oti/bcverify_api.h, can you please fix those as well.

Sure! I will fix them.

**Comment by doomerxe** [comment]
Hi @pshipton , I have fixed the characters on the other files, please re-review. Thank you!

**Comment by pshipton** [comment]
jenkins compile plinux jdk8

**Pull request merged**
