### PR TITLE
Clean up J9VM_INTERP_USE_SPLIT_SIDE_TABLES flag

### PR DESCRIPTION
**Pull request by fengxue-IS**
Removed all use of J9VM_INTERP_USE_SPLIT_SIDE_TABLES flag
since this optimization is always enabled

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
@fengxue-IS Did you use a tool (sunifdef?) to remove the #ifdefs?  Using a well known / trusted tool makes this easier to review.

**Comment by fengxue-IS** [comment]
@DanHeidinga, this is done manually, I am installing sunifdef to check right now

**Comment by fengxue-IS** [comment]
the old tool `unifdef` seem to have problems detecting all the instance of J9VM_INTERP_USE_SPLIT_SIDE_TABLES in the code

**Comment by fengxue-IS** [comment]
diffed against code generated by `sunifdef`, identical except with tab and newline.
@DanHeidinga would like to me to use the generated version?
(main difference is tool didn't change 
```} else
{
```
to 
``` } else {```

**Comment by DanHeidinga** [comment]
Thanks for confirming @fengxue-IS.  I'll proceed with the review as is.

**Comment by DanHeidinga** [comment]
@fengxue-IS Can you update the copyright dates in the following files:
```
13:43:32 runtime/bcutil/ConstantPoolMap.cpp
13:43:32 runtime/jvmti/jvmtiMethod.c
13:43:32 runtime/stackmap/stackmap.c
13:43:32 runtime/util/bcdump.c
```

**Comment by DanHeidinga** [comment]
One further change and its fine to do it in a separate PR is to remove the flag from j9.flags:
```
	<flag id="interp_useSplitSideTables">
		<description>Use split side tables for handling constant pool entry shared between multiple invoke bytecodes</description>
		<ifRemoved></ifRemoved>
	</flag>
```

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux

**Pull request merged**
