### PR TITLE
Correct formatting of test build.xml for zOS

### PR DESCRIPTION
**Pull request by jdekonin**
Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
@llxia @pshipton

**Comment by pshipton** [comment]
Test via grinder https://ci.eclipse.org/openj9/view/Test/job/Grinder/1451/

**Comment by pshipton** [comment]
Technically there should be a better commit comment, like "Correct formatting of test build.xml for zOS"

**Comment by pshipton** [comment]
Building the test worked in the grinder, which is a good enough validation of this change. The grinder wasn't set up properly to run the test.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
