### PR TITLE
Switch Linux platforms to compile with gcc 7

### PR DESCRIPTION
**Pull request by pshipton**
Doc issue https://github.com/eclipse/openj9-docs/issues/191

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity xlinux,plinux,zlinux jdk8

**Comment by pshipton** [comment]
@DanHeidinga @keithc-ca I think is ready to go.

**Comment by pshipton** [comment]
@jdekonin fyi

**Comment by DanHeidinga** [comment]
+1 from me as this makes the compilers consistent with what Adopt is using.

**Comment by DanHeidinga** [comment]
fyi @dnakamura the cmake scripts (lists?) probably need to be updated for this as well

**Pull request merged**
