### PR TITLE
Consolidate Relocation Records

### PR DESCRIPTION
**Pull request by dsouzai**
https://github.com/eclipse/openj9/issues/3031

This PR consolidates a few Relocation Records, removing code duplication. It is the first of several PRs.

### CODE REVIEW

**Comment by dsouzai** [comment]
WIP because I need to run personal tests.

**Comment by dsouzai** [comment]
@mstoodle even though this is a WIP, could you please review?

**Comment by dsouzai** [comment]
Personal build passed on all platforms.

**Comment by mstoodle** [comment]
Can you also remove the TR_ClassObject and TR_InterfaceObject values from the enum and, um, add some commit messages? I'm not sure casual git log reader will naturally understand the fully import of  "consolidate" in the commit title. You might also explain that you're deleting ClassObject and InterfaceObject because they're no longer used by anything ....

**Comment by dsouzai** [comment]
>Can you also remove the TR_ClassObject and TR_InterfaceObject values from the enum

The enum is in OMR :) And I can't just remove it because there are multiple table of sizes that have to be in sync with the enum, not to mention the enum is manually numbered, so removing an enum requires fixing up the numbering heh.

>add some commit messages?

Heh sure

**Comment by mstoodle** [comment]
ok, can i ask you to please mark those enum values as deprecated (at your convenience) ?

**Comment by mstoodle** [comment]
jenkins test sanity all jdk11

**Comment by dsouzai** [comment]
Windows failed because of 
```
13:16:09 make[7]: [../makelib/targets.mk:381: VerboseEventMetronomeSynchronousGCEnd.i] Error 1 (ignored)
13:16:09 /usr/bin/tee: 'standard output': No space left on device
13:16:09 /bin/sh: VerboseEventPercolateCollect.i: No space left on device
```
osx failed because of 
```
11:54:09 In file included from MHInterpreter.cpp:24:
11:54:09 ./../oti/clang/stddef.h:24:9: error: 'offsetof' macro redefined [-Werror,-Wmacro-redefined]
11:54:09 #define offsetof(type, member) __builtin_offsetof(type, member)
11:54:09         ^
11:54:09 /Library/Developer/CommandLineTools/usr/lib/clang/9.1.0/include/stddef.h:120:9: note: previous definition is here
11:54:09 #define offsetof(t, d) __builtin_offsetof(t, d)
11:54:09         ^
```

@mstoodle could you please merge (or re-test) if everything looks good?

**Comment by mstoodle** [comment]
jenkins test sanity win,osx jdk11

**Comment by dsouzai** [comment]
@mstoodle do you think it's worth retrying the the two builds? osx is very likely going to fail again, but I suppose the windows build never ran.

**Comment by dsouzai** [comment]
@mstoodle I rebased on to the latest master and updated the commit message. Feel free to retest if you feel it appropriate.

**Comment by mstoodle** [comment]
jenkins test sanity all jdk11

**Comment by dsouzai** [comment]
@mstoodle the osx failures are all from `thrstatetest_0` which don't run using `-Xsharedclasses`.

**Comment by mstoodle** [comment]
yep, i am good to merge this one now. Thanks @dsouzai !

**Pull request merged**
