### PR TITLE
Function implementation for TR_ResolvedRelocatableJ9JITaaSServerMethod

### PR DESCRIPTION
**Pull request by a7ehuo**
Function implementation for TR_ResolvedRelocatableJ9JITaaSServerMethod

Issue: #4401

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Comment by a7ehuo** [comment]
@mpirvu FYI

**Comment by dmitry-ten** [comment]
All of the specializations for these methods are in the beginning of `TR_ResolvedRelocatableJ9Method` definition.

**Comment by a7ehuo** [comment]
@mpirvu @dmitry-ten These methods are implemented the same in `TR_ResolvedRelocatableJ9Method` and `TR_ResolvedJ9Method`. As Marius mentioned, we don't need to override them in `TR_ResolvedRelocatableJ9JITaaSServerMethod` since `TR_ResolvedRelocatableJ9JITaaSServerMethod` extends from `TR_ResolvedJ9Method` already. I'll remove them from the header file.

**Comment by dmitry-ten** [comment]
Ah, I see. Thanks.

**Pull request merged**
