### PR TITLE
Round up romClassMinimalSize to sizeof(U_64).

### PR DESCRIPTION
**Pull request by hangshao0**
Fixes: #4976

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity win jdk11

**Comment by pshipton** [comment]
jenkins test extended win jdk11

**Comment by pshipton** [comment]
@hangshao0 please fix the asserts so misalignment isn't a quiet failure.
`Trc_SHR_Assert_True(0 != (sizes->romClassSizeFullSize & (sizeof(U_64) - 1)));`

**Comment by hangshao0** [comment]
Changed
Trc_SHR_Assert_True(0 != (sizes->romClassSizeFullSize & (sizeof(U_64) - 1)));
to 
Trc_SHR_Assert_ShouldNeverHappen();

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk8,jdk11

**Comment by pshipton** [comment]
jenkins test extended plinux jdk8,jdk11

**Pull request merged**
