### PR TITLE
WIP: Remove unused macro and functions from JIT runtime

### PR DESCRIPTION
**Pull request by 0xdaryl**
* remove unused deprecated functions from JIT runtime
* remove host_PPC and TR_HOST_PPC macro from DDR

### CODE REVIEW

**Comment by 0xdaryl** [comment]
WIP: only because testing hasn't completed yet.

In the meantime, I would appreciate a review of the DDR commit from either @DanHeidinga or @pshipton and the JIT runtime changes from @ymanton .

**Comment by ymanton** [comment]
JIT runtime changes LGTM. The platformLightweightLocking stuff was used by IProfiler back when it had locks. I don't recall ever seeing the fixup functions being used.

**Comment by genie-openj9** [comment]
Can one of the admins verify this patch?

**Comment by andrewcraik** [comment]
@0xdaryl looks like this pull request has gone a bit stale - could you rebase and resolve conflicts if you still wish to proceed with making this request?

**Comment by fjeremic** [comment]
@0xdaryl any updates?

**Comment by andrewcraik** [comment]
@0xdaryl should this be closed? it has been open a long time with no updates...

**Pull request closed without merging**
