### PR TITLE
Fail the build if j9ddr.jar is missing

### PR DESCRIPTION
**Pull request by OscarQQ**
This PR depends on [PR#9580](https://github.com/eclipse/openj9/pull/9580)
related to: #9539
Signed-off-by: Yixin Qian <Yixin.Qian@ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Please change `closes: #9539`, to `related: #9539`. This is not a fix for #9539, this PR is for making the failure more clear to the user. If j9ddr.jar is missing, instead of failing at the test execution stage, we fail at the test compilation stage.

**Comment by llxia** [comment]
jenkins test extended xlinux,win jdk8

**Comment by llxia** [comment]
jenkins test extended all jdk11

**Comment by llxia** [comment]
Please also add the check for `JDK_IMPL `. We only fail the build if the `JDK_IMPL ` is `ibm` or `openj9`. Something as the following:

```
<if>
   <or>
      <equals arg1="${JDK_IMPL}" arg2="ibm"  />
      <equals arg1="${JDK_IMPL}" arg2="openj9" />
   </or>
   <then>
      <if>
         <available file="${j9ddr}" />
         <then>
            <antcall target="clean" inheritall="true" />
        </then>
        <else>
            <fail message="File '${j9ddr}' not found; assuming JDK '${TEST_JDK_HOME}' does not support DDR."/>
        </else>
      </if>
</if>
```

**Comment by llxia** [comment]
jenkins test extended all jdk11,jdk8

**Comment by llxia** [comment]
jenkins test extended all jdk11,jdk8

**Comment by pshipton** [comment]
The PR build got a ConcurrentModificationException and is hung on the jenkins workers, blocking everything else from running. I'm killing the jobs. The PR testing will have to be re-run.

**Comment by llxia** [comment]
jenkins test extended all jdk11,jdk8

**Comment by llxia** [comment]
All PR builds passed, please see https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/3617/
For some reason, the above results in checks still show some old PR builds.

**Pull request merged**
