### PR TITLE
Update modes.xml parsing logic

### PR DESCRIPTION
**Pull request by renfeiw**
- use perl XML:Parser to parse modes.xml

[ci skip]

Signed-off-by: Renfei Wang <renfeiw@ca.ibm.com>

### CODE REVIEW

**Comment by renfeiw** [comment]
reviewer: @llxia

**Comment by llxia** [comment]
jenkins test sanity all jdk11

**Comment by llxia** [comment]
jenkins test sanity all jdk11

**Comment by llxia** [comment]
jenkins test sanity all jdk11

**Comment by llxia** [comment]
jenkins test sanity all jdk8

**Comment by llxia** [comment]
`-Xcompressedrefs` is used for cmprssptrs build:
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-linux_x86-64_cmprssptrs-OpenJ9/491/tapResults/

```
===============================================
Running test cmdLineTester_jvmtitests_hcr_4 ...
===============================================
cmdLineTester_jvmtitests_hcr_4 Start Time: Wed Mar 13 11:55:38 2019 Epoch Time (ms): 1552488938171
variation: Mode148
JVM_OPTIONS: -Xcompressedrefs -Xjit -Xgcpolicy:gencon -Xshareclasses:name=bcienabled,enableBCI -Xnocompressedrefs 
Selected VM [default] by option -Xnocompressedrefs does not exist.
This JVM package only includes the '-Xcompressedrefs' configuration. Please run the VM without specifying the '-Xnocompressedrefs' option or by specifying the '-Xcompressedrefs' option.
To compile the other configuration, please run configure with '--with-noncompressedrefs.

cmdLineTester_jvmtitests_hcr_4_FAILED
````

**Comment by renfeiw** [comment]
After the investigation, we found that the ottawa.csv is not correct in the way that mode 148 and mode 149 (contains -noncompressedrefs) tags yes for compressed platforms. This doesn't cause failure because the previous parsing logic is happened to be wrong and caused the mode 148 and mode 149 to have no -noncompressedrefs in the options.  Correct ottawa.csv and the parsing logic to fix this issue.

**Comment by renfeiw** [comment]
Ignore the copyright check failure for ottawa.csv file.

**Comment by llxia** [comment]
jenkins test sanity all jdk8

**Comment by llxia** [comment]
jenkins test sanity all jdk8

**Comment by llxia** [comment]
jenkins test extended all jdk8

**Comment by llxia** [comment]
jenkins test sanity aix,plinux jdk8

**Pull request merged**
