### PR TITLE
Relocate DDR test code

### PR DESCRIPTION
**Pull request by keithc-ca**
Simplifies exclusion from main builds.

Related eclipse launch configurations are adjusted.

Issue: #378
Signed-off-by: Keith W. Campbell <keithc@ca.ibm.com>

### CODE REVIEW

**Comment by keithc-ca** [comment]
Copyright failures are for *.launch files which *could* have embedded notices, but those would disappear the next time eclipse made any changes.

**Comment by pshipton** [comment]
@llxia or @smlambert is this change ok with you?

**Comment by smlambert** [comment]
I am not clear on the purpose of this PR, are you intending these tests to be run with the other tests?  

But these are not in test dir (where they'd automatically be picked up as part of testing), rather in debugtools dir, what is the story for how and when these tests will be run?  

As part of our test migration, we have been converting JUnit tests to testng, using the testng logger for any System.out.println statements, renaming test packages that were previously called com.ibm.test.xxxx to org.openj9.test.xxxx, playlist.xml and testng.xml files created and so forth.

**Comment by keithc-ca** [comment]
I didn't change any of the test code, it has simply moved from the main source folder to the 'testsrc' folder of the DDR_VM project. I don't know the original intent of the tests so I don't know whether it makes sense to migrate them to the main 'test' folder.

**Comment by llxia** [comment]
I am not aware these tests. Do we run them at all?

**Comment by keithc-ca** [comment]
I don't think they are run automatically. Would people prefer that we simply remove these tests instead of just relocating them?

**Comment by smlambert** [comment]
Do you consider them valuable for testing the DDR feature you have been reworking?

If so, I think they should be migrated to the test dir (as done with other tests) into a new project for all of the DDR tests you wish to include to test the DDR feature.

**Comment by keithc-ca** [comment]
I haven't really spent any time trying to figure out what those tests are about. They depend upon org.junit and things like that don't belong in j9ddr.jar. I just needed to avoid trying to build them along with the classes that do belong in j9ddr.jar and avoid the need to have junit.jar on the classpath. I could have explicitly excluded them where they were, but relocating them seemed like the better solution.

**Comment by smlambert** [comment]
Here is the plan to move forward on this:  
1) approve and merge this change, to unblock the remaining DDR dev work
2) assess these DDR tests and determine if they should be retained (issue #1250)
3) if we should keep these tests, migrate them to the test dir (convert to testng, use logger, etc)

**Comment by smlambert** [comment]
As these tests will not be executed, will forego a PR build.

**Pull request merged**
