### PR TITLE
Update the values of JVM Cpu in the compilation msgs in server's verbose

### PR DESCRIPTION
**Pull request by EmanElsaban**
Moved the updateCpuUtil function outside the if statment that requires
the staticsFrequency option to be used. This will alow the Jvm Cpu
values to be updated even if the stats thread was not enabled under the condition
of having any verbose option set.
issue: #12031

Signed-off-by: Eman Elsabban <eman.elsaban1@gmail.com>

### CODE REVIEW

**Comment by EmanElsaban** [comment]
@mpirvu Can you please review it? Thanks!

**Review by mpirvu — CHANGES_REQUESTED** [review]
This implementation computes the CPU utilization if any verbose option is present.
However, we also want to print the CPU utilization from the statistics thread and this won't work anymore, unless we have some verbose option.

**Comment by mpirvu** [comment]
You need to update the copyright year as well.

**Review by mpirvu — COMMENTED** [review]
I would further optimize the code: currently, if we don't use the verbose option, but use the statistic thread to periodically (say every 10 sec) output CPU information, we calculate CPU utilization every 10ms leading to unnecessary overhead. 
Also, even for printing to vlog I thing that computing every 10ms is too frequent (in the non-jitserver implementation we do it every 0.5 sec).
I am suggesting the following implementation: 
- keep a static local variable that memorizes when the last update was done (like `lastStatsTime`)
- let the flow go through the logic that determines whether we want to print statistics and if we do update the time when we updated the CPU utilization.
- after this add a test for verbose log and a test whether at least 0.5 sec have passed since the last update. If true, then updateCPUUtilization.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
Actually, can you please change the title of the commit to be shorter and more explicit:
"Update JVM CPU utilization if vlog options are present"

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit jdk11

**Pull request merged**
