### PR TITLE
J9 PrivateLinkage refactoring

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Introduce an architecture-agnostic PrivateLinkage base class
* Migrate ARM64PrivateLinkage from TR namespace to J9
* Migrate PPCPrivateLinkage from TR namespace to J9
* Migrate S390PrivateLinkage from TR namespace to J9
* Migrate X86PrivateLinkage from TR namespace to J9
* Migrate ARMPrivateLinkage from TR namespace to J9

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
@ymanton @fjeremic : I'd appreciate a review on this from one of you please when you have some time.  Thanks.

The decision to move the J9 PrivateLinkage out of the TR namespace was because this linkage is only being used in OpenJ9 and not exposed to other projects.  Entities in the TR namespace can be referenced in any project.

**Comment by ymanton** [comment]
Shouldn't the JNI and helper linkages go there as well?

**Comment by 0xdaryl** [comment]
@ymanton : yes, they should (and will).  This PR was just about PrivateLinkage.  I didn't want to broaden the scope too much.

**Pull request merged**
