### PR TITLE
Fix syntax error in Test_String.java

### PR DESCRIPTION
**Pull request by Ailloviee**
Added a missing "}" in Test_String.java

Signed-off-by: Charles_Zheng <Juntian.Zheng@ibm.com>

### CODE REVIEW

**Comment by Ailloviee** [comment]
^^ @llxia

**Comment by llxia** [comment]
Jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
Jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
Jenkins test sanity xlinux jdk11

**Comment by llxia** [comment]
Build failed due to native test libraries are missing. Test compilation passed.

**Pull request merged**
