### PR TITLE
Deprecate HPR support

### PR DESCRIPTION
**Pull request by fjeremic**
This PR deprecates all HPR support in the compiler. eclipse/openj9#4609 does a pretty good job of summarizing the various HPR support and how each piece plays a role in the overall picture. It also explains the shortcomings of the feature and why it is no longer worth the investment to keep it on life support.

Opening up the PRs early to get some testing going and to self-review some of the TODOs that were left as a result of the cleanup. The cleanup itself was rather straightforward. I will also collect performance data on how much compile time improvement this cleanup has yielded as disabling of the feature is not equivalent to this cleanup (I expect more than double compile time improvement as a result of this PR vs. just disabling the feature).

Fixes: #4609

### CODE REVIEW

**Comment by fjeremic** [comment]
Depends on https://github.com/eclipse/omr/pull/3654. This is a breaking change. Due to the sheer size of the PRs I could not find a feasible way to untangle the support without a temporary build break. I'll work with the assigned committer to make sure we merge at the best possible time to avoid churn for everyone.

**Comment by fjeremic** [comment]
Jenkins test sanity all JDK8,JDK11

**Comment by fjeremic** [comment]
Jenkins test sanity all JDK8,JDK11 depends eclipse/omr#3654

**Comment by fjeremic** [comment]
Jenkins test sanity all JDK8,JDK11 depends eclipse/omr#3654

**Comment by fjeremic** [comment]
Jenkins test sanity all JDK8,JDK11 depends eclipse/omr#3654

**Comment by fjeremic** [comment]
Jenkins test sanity all JDK8,JDK11 depends eclipse/omr#3654

**Comment by 0xdaryl** [comment]
Jenkins test sanity all JDK8,JDK11 depends eclipse/omr#3654

**Comment by fjeremic** [comment]
I've included the latest performance numbers in #4609. We are green across the board in every metric we track. Performance wise this looks like a golden nugget.

**Comment by fjeremic** [comment]
Relaunching some builds because AIX machines were offline.

Jenkins test sanity aix,plinux JDK8,JDK11 depends eclipse/omr#3654

**Comment by 0xdaryl** [comment]
One more try:

Jenkins test sanity aix,plinux JDK8,JDK11 depends eclipse/omr#3654

**Comment by 0xdaryl** [comment]
I believe both parts of this change are ready to merge now.  Let me know when you're ready for me to push the button on both OpenJ9 and OMR PRs.

**Comment by fjeremic** [comment]
> I believe both parts of this change are ready to merge now. Let me know when you're ready for me to push the button on both OpenJ9 and OMR PRs.

Please go ahead, preferably in the evening. The OMR-Acceptance builds are passing as of 1:00 p.m. today. So hopefully the change sails through fine.

**Pull request merged**
