### PR TITLE
OpenJ9 Attach API Diagnostic extension #2543

### LINKED ISSUE #2543: OpenJ9 Attach API Diagnostic extension
I always ran jstack / jmap / jstat for OpenJDK in order get some diagnostic information. And I'd like to have similar useful utilities for OpenJ9.  I know I can configure -Xdump or use Diagnostic MBean to get a threaddump or heapdump, but it is not convenient for me.
jstack, jmap and other openjdk tools use Attach API to ask VM for a specific operation. So to make these  tools support OpenJ9 I want to extend Attach API implementation.
I want to add commands in jcl/src/java.base/share/classes/com/ibm/tools/attach/target/Command.java.
After that, I will implement these commands in 
jcl/src/java.base/share/classes/com/ibm/tools/attach/target/Attachment.java. 
To get java dump / heap dump I will call jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Dump.java. 
May be there will be more commands

### PR DESCRIPTION
**Pull request by d0k1**
To implement command line diagnostic utilities like jstack / jmap / etc I decided to use Attact API just as jstack does. Attach API extension contains 8 new commands. Among them, there are commands to get javadump/systemdump/heapdump/snapdump and to get Information about memory, about loaded/unloaded classes about JIT compilation time. There is one command to get a thread dump through com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl. The communication between JVM and Attach API client is going through IPC mechanism. Some commands have to send back some data to a client so they use java serialization to serialize a response and send it. Besides there are some new methods in com.ibm.tools.attach.attacher.OpenJ9VirtualMachine that uses the extension. #2543

Fixes #2543

Signed-off-by: Denis Kirpichenkov <denis.kirpichenkov@gmail.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Thanks for opening this PR, @d0k1!  

Have you signed the Eclipse Contributor Agreement?  As an Eclipse project, all contributors need to sign the ECA and have their commits pass the `ip-validation` check by using signed commits (ie: `git commit -s`)

Can you confirm you've signed the ECA and update the commit message to include the correct Signed-off by: tag?

Also, is there an existing issue that describes the approach taken to adding these extensions?  If there is, can you link to it from this item?  Any additional description of the design will help when reviewing the PR.

Thanks again!

**Comment by DanHeidinga** [comment]
@pdbain-ibm Can you take a look at the highlevel approach taken here and comment on how well it integrates into the existing attach api code?

**Comment by pdbain-ibm** [comment]
Dan

Will do.  

@d0k1 As you can appreciate, security is an issue with the JVM and particularly attachAPI.  Would you kindly indicate what steps you have taken to avoid compromising security.  Thank you.

**Comment by DanHeidinga** [comment]
> Please create a new class which extends OpenJ9VirtualMachine and move the new methods to same. 

@pdbain-ibm What benefit does this bring?

**Comment by pdbain-ibm** [comment]
a) it keeps the OpenJ9VirtualMachine API congruent with the com.sun implementation, which has been a design goal from the start of the attach API project. 
b) it separates the core attach API methods from the extensions thereto.

**Comment by d0k1** [comment]
@pdbain-ibm You asked about steps I may took to avoid compromising security. Honestly, I did nothing. This PR is just a prototype of extended Attach API. 
I would glad to hear advice about security check I need to implement.
May be I should do the same security check as Dump class (jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Dump.java) does in it's methods? May be I should check if current user that tries to make a dump is the same who started a JVM?

**Comment by AdamBrousseau** [comment]
Jenkins line endings check

**Comment by pshipton** [comment]
@d0k1 why close this pull request? Have you decided not to pursue this?

**Comment by d0k1** [comment]
@pshipton Unfortunately adaptation of OpenJ9 has been stopped in project I'm involved in.

**Comment by pshipton** [comment]
@d0k1 if you are able to share any details of why you decided to stop using OpenJ9, can you please let me know, either here or by direct email. I'm wondering if there are any specific areas we should be focusing on to improve OpenJ9.

**Comment by thjaeckle** [comment]
Very sad to not have that included in OpenJ9 - we would need to use the same (e.g. using jmap in order to get a heapdump from a running JVM).

**Comment by DanHeidinga** [comment]
@d0k1 Thanks for creating this pull request.  

If you have no objections, we'd like to reopen this PR with goal of getting it merged.  If you're interested in helping with that, great!  If not, we'll take on the work required to get this through reviews and into OpenJ9.

**Comment by SueChaplain** [comment]
@pdbain-ibm - does this require any user documentation please? If so, please add the doc:externals label and open an issue at the docs repo: https://github.com/eclipse/openj9-docs/issues/new?template=new-documentation-change.md

**Comment by d0k1** [comment]
@DanHeidinga Thanks for interest in this PR. Of course you can use it freely, I have no objections at all.  
I'm just curios what about some concerns @pdbain-ibm had written about?
I'd like to add that, this API extension is just an extension, and OpenJ9 at the moment is still missing utilities that would use it. Is there any plans to implements such utilities?

I'd say that it's great to continue working on this PR, but I don't know where to start at the moment.

**Comment by DanHeidinga** [comment]
Thanks @d0k1.  Re: @pdbain-ibm's concerns, they can be handled in review - validating that appropriate security concerns have been identified and mitigated.

**Comment by pshipton** [comment]
As this is being implemented by other PRs, closing this one.

**Pull request closed without merging**
