### PR TITLE
Change fastIdentityHashCode() to use unsigned int to long conversion

### PR DESCRIPTION
**Pull request by DanHeidinga**
J9VMInternals.fastIdentityHashCode(Object) incorrectly sign-extended the
32bit J9Class pointer when reading it from an object header in a
compressedrefs VM.

This can can cause crashes with i.e. InaccessibleReadAddress=FFFFFFFF999609D8
in Java_com_ibm_jit_JITHelpers_getBackfillOffsetFromJ9Class64.

The int value needs to be assigned to the long without sign-extension.
Code now uses Integer.toUnsignedLong(int) to work around the issue.

JShell example showing this is valid:
```
jshell> int ptr = 0x99960900
ptr ==> -1718220544

jshell> long lptr = Integer.toUnsignedLong(ptr)
lptr ==> 2576746752

jshell> Long.toHexString(lptr)
$3 ==> "99960900"

jshell> long castptr = ptr
castptr ==> -1718220544

jshell> Long.toHexString(castptr)
$5 ==> "ffffffff99960900"
```

Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
Before merging this we need to fast path the Integer.toUnsignedLong in the JIT for performance otherwise we are likely to have a lot of regressions since we don't seem to have acceleration for it right now.

**Comment by liqunl** [comment]
Can you change the call to `Integer.toUnsignedLong` to a bitwise operation? i.e. use
```
long ptr = (com.ibm.oti.vm.VM.FJ9OBJECT_SIZE == 4) ? ((long)h.getIntFromObject(anObject, 0L)) & 0xffffffffL : h.getLongFromObject(anObject, 0L);
```
Then we don't need any change in the JIT.

**Comment by fjeremic** [comment]
> Can you change the call to Integer.toUnsignedLong to a bitwise operation?

I disagree. We should take this opportunity and just accelerate `Integer.toUnsignedLong` so all future and existing code will benefit from this.

**Comment by andrewcraik** [comment]
I think it should be as simple as adding a transformer in ilgen somewhere to replace calls to Integer.toUnsignedLong with iu2l nodes

**Comment by fjeremic** [comment]
@DanHeidinga let us know if you need any help crafting the JIT commit. We'll be happy to assist.

**Comment by liqunl** [comment]
We can't transform it in ilgen since we need a HCR guard. I'm ok with keeping the call by force it to inline.

**Comment by andrewcraik** [comment]
I think we can white list replacing it for the JITHelper since that is an internal implementation detail would be my take.

**Comment by liqunl** [comment]
Personally I would prefer using bitwise operation over creating a JITHelper and fast pathing the JITHelper. I'm not sure if we should add Integer.toUnsignedLong to the alwaysWorthInlining list since it is a very small method, we should have always inlined it already. But I agree that adding it doesn't hurt.

**Comment by DanHeidinga** [comment]
@fjeremic Thanks for the pointers on how to mark toUnsignedLong as alwaysWorthInlining.  Is there a -Xjit:verbose option to print the inlines?  I'd like to confirm that the method is being inlined.

Minimal test case to force compilation of J9VMInternals.fastIdentityHashCode:
```
package java.lang;
public class Test {

public static void main(String[] args) throws Throwable {
        int i = 0;
        for (int j = 0; j < 100000; j++) {
                i += fastHash(new Object());
        }
        System.out.println(i);

}

public static int fastHash(Object o) {
        return J9VMInternals.fastIdentityHashCode(o);
}
}

```

Running as:
```
$ java -Xbootclasspath/a:dan -Xjit:verbose java.lang.Test
```

And I'm seeing `toUnsignedLong` being compiled which I wouldn't expect (maybe?) if it was always inlined:
```
+ (cold) java/lang/J9VMInternals.fastIdentityHashCode(Ljava/lang/Object;)I @ 00007F5273D80C20-00007F5273D80DAB OrdinaryMethod - Q_SZ=2 Q_SZI=2 QW=10 j9m=00000000006BD730 bcsz=135 GCR compThread=0 CpuLoad=1%(0%avg) JvmCpu=0%
+ (warm) java/lang/Integer.toUnsignedLong(I)J @ 00007F5273D80DF8-00007F5273D80E17 OrdinaryMethod - Q_SZ=1 Q_SZI=1 QW=4 j9m=00000000006E9BC8 bcsz=7 compThread=0 CpuLoad=1%(0%avg) JvmCpu=0%
+ (warm) java/lang/Test.fastHash(Ljava/lang/Object;)I @ 00007F5273D80E60-00007F5273D80F7A OrdinaryMethod - Q_SZ=0 Q_SZI=0 QW=2 j9m=000000000078F288 bcsz=5 GCR compThread=0 CpuLoad=1%(0%avg) JvmCpu=0%818586157
```

**Comment by fjeremic** [comment]
> Is there a -Xjit:verbose option to print the inlines?

Not at the moment. The easiest way to tell is to log `java/lang/Test.fastHash` and check the inlining table. You can achieve this via `-Xjit:{java/lang/Test.fastHash*}(tracefull,log=fastHash.log)`. In the generated `fastHash.log` search for "Post Optimization Trees". You should see an inlining table with caller callee relationship. In there hopefully you will see `fastIdentityHashCode`.

**Comment by fjeremic** [comment]
> Is there a -Xjit:verbose option to print the inlines?

Actually @DanHeidinga this is a cool idea. @mpirvu / @dsouzai do you guys think we could do something like this? i.e. in the verbose log print an indented tree of inlining done for each compiled method. This can be guarded via a `verbose={...}` option?

**Comment by fjeremic** [comment]
I'll wait for a confirmation that the inlining did happen, though I'm fairly confident it will have and given it's the weekend let's kick off preemptive builds.

Jenkins test all

**Comment by mpirvu** [comment]
@DanHeidinga For verbose inlining you could try something like
`-Xjit:verbose={compilePerformance},verbose={inlining},vlog=vlog.txt`

**Comment by DanHeidinga** [comment]
Attached the jit log as I'm not seeing the inlining table in the Post Optimization Trees section.  Likely an error on my end.

[fastHash.log.18460.45150.20180224.040550.18460.txt](https://github.com/eclipse/openj9/files/1754038/fastHash.log.18460.45150.20180224.040550.18460.txt)

**Comment by DanHeidinga** [comment]
> I think we can white list replacing it for the JITHelper since that is an internal implementation detail would be my take.

Anything further required to address this comment?

**Comment by mpirvu** [comment]
Inlining table from the jit log above
```
Post Optimization Trees: for java/lang/Test.fastHash(Ljava/lang/Object;)I

Call Stack Info
CalleeIndex CallerIndex ByteCodeIndex CalleeMethod
       0         -1           1       java/lang/J9VMInternals.fastIdentityHashCode(Ljava/lang/Object;)I
       1          0          78       java/lang/Integer.toUnsignedLong(I)J
```

**Comment by DanHeidinga** [comment]
Thanks @mpirvu.  I was looking for something called inlining table.

**Comment by JamesKingdon** [comment]
Just a footnote that this problem may also surface as an unexpected NPE when the memory access is in jitted code, and even as a crash in getJitRegisterMap as the faulting address is not associated with a stackmap.

**Pull request merged**
