### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by babsingh**
1) Removed unused references to j9sem_t.
2) Removed unused fields in struct J9JavaVM: sigQuitFlags, sigQuitThread and sigQuitMutex.
3) Removed obsolete flag from buildspecs: interp_sigQuitThreadUsesSemaphores.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Seems there is also an obsolete flag in the buildspecs - interp_sigQuitThreadUsesSemaphores

**Comment by babsingh** [comment]
Added changes to remove the following flags in buildspecs: interp_sigQuitThread and interp_sigQuitThreadUsesSemaphores.

**Comment by DanHeidinga** [comment]
> Added changes to remove the following flags in buildspecs: interp_sigQuitThread and interp_sigQuitThreadUsesSemaphores.

Can you look for all uses of those flags and remove them as well?

There are other files that can likely be deleted as part of this PR:
* https://github.com/eclipse/openj9/blob/26f8c7edb1fe37253d001243c0ce14473334d07f/runtime/oti/sigquit.h

* https://github.com/eclipse/openj9/blob/26f8c7edb1fe37253d001243c0ce14473334d07f/runtime/jcl/common/sigquit.c

**Comment by babsingh** [comment]
I made a typo during search. `interp_sigQuitThread` is still used. So, we can't remove `sigquit.h` and `sigquit.c`. Only `interp_sigQuitThreadUsesSemaphores` is unused.

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk8

**Pull request merged**
