### PR TITLE
VM marking exit started too early

### PR DESCRIPTION
**Pull request by gacholio**
Don't indicate exit until after calling Shutdown.shutDown() in
DestroyJavaVM.

See issue for details.

Fixes: #10255

[ci skip]

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity,extended zlinux jdk11

**Comment by pshipton** [comment]
We should add the hanging test case to the automated tests.

**Comment by DanHeidinga** [comment]
Change looks fine to me and I agree with Pete about adding the test case to the automated runs

**Comment by gacholio** [comment]
I have no idea how to add tests that aren't in the JVMTI framework (which isn't appropriate here), so I suggest merging this and opening a new issue to get the test added.

For the record, I modified the test to use wait/notify rather than the latch (which doesn't exist in java 8).

**Comment by gacholio** [comment]
FYI, I also plan to revert https://github.com/eclipse/openj9/pull/9867 and https://github.com/eclipse/openj9/pull/9885 once this is merged - they were a workaround which is no longer required with this more correct solution.

**Pull request merged**
