### PR TITLE
Eliminate J9AOTConfig data structure

### PR DESCRIPTION
**Pull request by mpirvu**
This data structure is no longer needed and can safely be deleted.

Fixes: #8514

Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
jenkins test sanity all jdk11

**Comment by pshipton** [comment]
Re-run plinuxxl as it was built on ub16-ppcle-2 which still doesn't have a proper protobuf install. #8257 

jenkins test sanity plinuxxl jdk11

**Comment by pshipton** [comment]
I think the switch to gcc 7.5 is causing protobuf problems on xlinux.

**Comment by pshipton** [comment]
Reverting from gcc 7.5 on xlinux here https://github.com/eclipse/openj9/pull/8533

**Comment by pshipton** [comment]
jenkins test sanity xlinux,linuxxl jdk11

**Comment by pshipton** [comment]
I guess the commit needs to be rebased to pick up the gcc change.

**Comment by mpirvu** [comment]
jenkins test sanity xlinux,linuxxl jdk11

**Comment by pshipton** [comment]
jenkins test sanity xlinuxxl jdk11

**Comment by mpirvu** [comment]
@ymanton, could you please review and merge this PR? Thanks

**Comment by mpirvu** [comment]
I think the other ones passed as well. Let me trigger some non-linux as well:
jenkins test sanity aix,win,osx jdk11

**Comment by pshipton** [comment]
The original PR test was https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/2653/
In end everything had passed. You can find the other PR builds at https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/

**Pull request merged**
