### PR TITLE
Update JITaaS Build Instructions

### PR DESCRIPTION
**Pull request by a7ehuo**
Update get_source.sh parameter in JITaas build document to point to the forked openj9 repository [skip ci]

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
Please keep in mind that this doc is also for people from outside of IBM, and some of them might not even have a fork yet. For people who just wants to build and try out JITaaS, they probably just want to use `bash get_source.sh -openj9-repo=https://github.com/eclipse/openj9.git -openj9-branch=jitaas -omr-repo=https://github.com/eclipse/openj9-omr.git -omr-branch=jitaas`. So in my opinion we should keep it as it is.

**Comment by a7ehuo** [comment]
@mpirvu I'll update it again to include Harry's suggestion: keep the original command but mention replace eclipse with forked repo.

**Comment by a7ehuo** [comment]
@mpirvu Yeah, I also noticed the typo after the 2nd update. Will update again in a min.

**Comment by a7ehuo** [comment]
@mpirvu Updated. Please check. Thx.

**Pull request merged**
