### PR TITLE
Cleanup of j9signalTest.c and j9signalExtendedTest.c

### PR DESCRIPTION
**Pull request by BrijeshNekkare**
j9signalTest.c and j9signalExtendedTest.c are duplicates of
corresponding tests in Eclipse OMR files omrsignalTest.cpp
and omrsignalExtendedTest.cpp, hence deleting the redundant
files along with cleanup of dependencies from other files

Fixes: #452

Signed-off-by: BrijeshNekkare <bnekkare@in.ibm.com>

### CODE REVIEW

**Comment by BrijeshNekkare** [comment]
@smlambert could you please review the PR.

**Comment by smlambert** [comment]
fyi @DanHeidinga @pshipton

**Comment by pshipton** [comment]
21:57:30 The following files were modified and have incorrect copyrights
21:57:30 runtime/tests/port/testHelpers.h

**Comment by BrijeshNekkare** [comment]
Interesting, Copyright check was triggered once i asked for PR review. Now that has been fixed.

**Comment by BrijeshNekkare** [comment]
@pshipton please review.

**Comment by pshipton** [comment]
@llxia any concerns?

**Comment by pshipton** [comment]
jenkins test sanity plinux

**Comment by pshipton** [comment]
@BrijeshNekkare To keep a cleaner history, please squash the commits so this is ready for merging. The copyright fix doesn't need to be separate. We could do it as part of the merge, but its preferred for the developer to do it, #254.

**Comment by BrijeshNekkare** [comment]
Thanks @pshipton, commit squashed as per your feedback.

**Comment by BrijeshNekkare** [comment]
@pshipton anything else pending for this PR?

**Comment by pshipton** [comment]
@llxia any concerns with the test changes?

**Comment by pshipton** [comment]
jenkins copyright check

**Comment by pshipton** [comment]
jenkins ip-validation

**Comment by pshipton** [comment]
@BrijeshNekkare there is no passed ip-validation check. Can you please update the commit in order to trigger this check.

**Comment by llxia** [comment]
LGTM :)

**Pull request merged**
