### PR TITLE
Changed the color of slack messages into grey for aborted jenkins jobs

### PR DESCRIPTION
**Pull request by JennyChenyj**
Switched the color from red to grey for aborted jenkins jobs

Signed-off-by: Jenny Chen <Jenny.Chen@ibm.com>

[skip ci]

### CODE REVIEW

**Comment by JennyChenyj** [comment]
Hi Adam! I finished modifying the script. Could you please review it? Thanks! :)

**Comment by AdamBrousseau** [comment]
Jenkins compile plinux jdk11

**Comment by pshipton** [comment]
The `def` can be moved, I'm not concerned about the others.

**Comment by genie-openj9** [comment]
Please ignore - testing comments

**Comment by AdamBrousseau** [comment]
Jenkins compile plinux jdk11

**Pull request merged**
