### PR TITLE
Branch to snippet unconditionally for array known to be discontiguous

### LINKED ISSUE #6498: Test_openjdk11_j9_extended.functional_x86-64_linux (+xl) threadMXBeanTestSuite1 SAXParseException
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_xl_Nightly/94
```
===============================================
Running test threadMXBeanTestSuite1_5 ...
===============================================
threadMXBeanTestSuite1_5 Start Time: Wed Jul 17 06:12:03 2019 Epoch Time (ms): 1563358323550
variation: Mode301 -Xjit:noJitUntilMain,count=0,optlevel=warm
JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:metronome -Xnocompressedrefs -Xjit:noJitUntilMain,count=0,optlevel=warm 
[TestNG] [ERROR] org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 8; The processing instruction must begin with the name of the target.
Exception in thread "main" java.lang.NullPointerException
	at org.testng.TestNG.getStatus(TestNG.java:211)
	at org.testng.TestNG.main(TestNG.java:1324)

threadMXBeanTestSuite1_5_FAILED
```

### LINKED ISSUE #6773: Test_openjdk8_j9_special.system_x86-64_linux MauveMultiThreadLoadTest_special_13
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_linux_Nightly/78
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_linux_Nightly/87
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_linux_Nightly/96

Mode351
JVM_OPTIONS: -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs

```
02:42:09  LT  02:41:13.223 - Test failed
02:42:09  LT    Failure num.  = 1
02:42:09  LT    Test number   = 3609
02:42:09  LT    Test details  = 'Mauve[gnu.testlet.javax.xml.xpath.XPath]'
02:42:09  LT    Suite number  = 0
02:42:09  LT    Thread number = 0
02:42:09  LT  >>> Captured test output >>>
02:42:09  LT  [Fatal Error] :1:2: The markup in the document preceding the root element must be well-formed.
02:42:09  LT  org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 2; The markup in the document preceding the root element must be well-formed.
02:42:09  LT  	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
02:42:09  LT  	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
02:42:09  LT  	at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:464)
02:42:09  LT  	at gnu.testlet.javax.xml.xpath.XPath.eval(XPath.java:63)
02:42:09  LT  	at gnu.testlet.javax.xml.xpath.XPath.nodeset(XPath.java:56)
02:42:09  LT  	at gnu.testlet.javax.xml.xpath.XPath.test(XPath.java:47)
02:42:09  LT  	at sun.reflect.GeneratedMethodAccessor1230.invoke(Unknown Source)
02:42:09  LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:42:09  LT  	at java.lang.reflect.Method.invoke(Method.java:498)
02:42:09  LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
02:42:09  LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
02:42:09  LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02:42:09  LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02:42:09  LT  	at java.lang.Thread.run(Thread.java:819)
02:42:09  LT  --------------- linked to ------------------
02:42:09  LT  javax.xml.xpath.XPathExpressionException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 2; The markup in the document preceding the root element must be well-formed.
02:42:09  LT  	at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:469)
02:42:09  LT  	at gnu.testlet.javax.xml.xpath.XPath.eval(XPath.java:63)
02:42:09  LT  	at gnu.testlet.javax.xml.xpath.XPath.nodeset(XPath.java:56)
02:42:09  LT  	at gnu.testlet.javax.xml.xpath.XPath.test(XPath.java:47)
02:42:09  LT  	at sun.reflect.GeneratedMethodAccessor1230.invoke(Unknown Source)
02:42:09  LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:42:09  LT  	at java.lang.reflect.Method.invoke(Method.java:498)
02:42:09  LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
02:42:09  LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
02:42:09  LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02:42:09  LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02:42:09  LT  	at java.lang.Thread.run(Thread.java:819)
02:42:09  LT  Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 2; The markup in the document preceding the root element must be well-formed.
02:42:09  LT  	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
02:42:09  LT  	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
02:42:09  LT  	at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:464)
02:42:09  LT  	... 11 more
02:42:09  LT  FAIL: gnu.testlet.javax.xml.xpath.XPath: jaxp-1.3-ch13s2.2.4 (number 0)
```

### PR DESCRIPTION
**Pull request by hzongaro**
If the array length in a `BNDCHKWithSpineCHK` is constant, generated code was comparing the constant length with the bound, bypassing the spine check, which is only OK if the array is not discontiguous.

Added a compile-time check of whether the array is discontiguous if the length is known.  If it is discontiguous, generate an unconditional branch to the spine check/bound check snippet.

Fixes #6498 and fixes #6773

Signed-off-by:  Henry Zongaro <zongaro@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
OK probably best to fix the functional problem and we can do the enhancement as a separate item. Sanity looks good and the change seems reasonable. @hzongaro are you happy for this to go in in light of your last comment?

**Comment by hzongaro** [comment]
> are you happy for this to go in in light of your last comment?

Yes, I'm happy with this going as it is.  I will open a separate issue (early next week) for the additional enhancement.  Thanks, Andrew!  @andrewcraik

**Comment by andrewcraik** [comment]
Great - I will merge this - @hzongaro could you open a PR for the same change against the 0.16 release branch?

**Comment by hzongaro** [comment]
Thanks, Andrew @andrewcraik.  I've created pull request #6934 to merge this to the 0.16 release branch.

**Pull request merged**
