### PR TITLE
Ensure Lookup::defineClass links the class

### PR DESCRIPTION
**Pull request by DanHeidinga**
From the VM spec:
Linking a class or interface involves verifying and preparing that class....

Calling prepare() on the class is sufficient to ensure it is
linked without calling the <clinit> method (which this method is not
supposed to do).

Fixes: #10297

Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Jenkins test sanity xlinux jdk15

**Comment by DanHeidinga** [comment]
@gacholio or @tajila can you review this?

**Comment by tajila** [comment]
@DanHeidinga CI failure:

```
﻿﻿﻿﻿﻿ERROR: Build failed for target 'images' in configuration 'linux-x86_64-normal-server-release' (exit code 2) 

=== Output from failing command(s) repeated here ===

* For target jdk_modules_java.base__the.java.base_batch:

/home/travis/build/eclipse/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/support/j9jcl_sources/java.base/share/classes/java/lang/invoke/MethodHandles.java:1689: error: cannot find symbol

			J9VMInternals.prepare(targetClass);

			^

  symbol:   variable J9VMInternals

  location: class Lookup

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: {0} uses or overrides a deprecated API that is marked for removal.

Note: Recompile with -Xlint:removal for details.

Note: Some input files use unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.

1 error
```

**Comment by tajila** [comment]
`java.lang.J9VMInternals::prepare()` is package private

**Comment by DanHeidinga** [comment]
Thanks.  Will fix today.

**Comment by DanHeidinga** [comment]
Jenkins test sanity xlinux jdk15

**Comment by DanHeidinga** [comment]
I have a fix for the copyrights once the testing is complete

**Comment by tajila** [comment]
Confirmed that JDK15 tests passed. CI failure is a linter issue:
```
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
apt-get.diagnostics

apt-get install failed

The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) i
```

**Review by gacholio — APPROVED** [review]

**Comment by DanHeidinga** [comment]
Jenkins test sanity zlinux jdk15

**Review by tajila — APPROVED** [review]

**Comment by DanHeidinga** [comment]
I've backported this to 0.22.0 as well - https://github.com/eclipse/openj9/pull/10546

Can you review + merge there as well?

**Pull request merged**
