### PR TITLE
Add jdk test natives to test-images.tar.gz archive

### PR DESCRIPTION
**Pull request by jdekonin**
* rename native-test-libs.tar.gz -> test-images.tar.gz to match
    what openjdk test framework is looking for
* eclipse/openj9#7521
* [skip ci]

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
fyi @pshipton

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk8,jdk11

**Comment by pshipton** [comment]
Need to wait for OMR promotion before re-trying PR testing.

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk8,jdk11

**Comment by pshipton** [comment]
Not sure why the Pull Request link is referring to the original failed PR build https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/1835/
The later PR build https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/1838/ passed.

**Pull request merged**
