### PR TITLE
Remove rconsole support

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
15:45:13  The following files were modified and have incorrect copyrights
[Pipeline] echo
15:45:13  runtime/bcutil/test/dyntest/romclass_testing.c
[Pipeline] echo
15:45:13  runtime/cassume/ctest.c
[Pipeline] echo
15:45:13  runtime/exelib/CMakeLists.txt
[Pipeline] echo
15:45:13  runtime/exelib/module.xml
[Pipeline] echo
15:45:13  runtime/include/exelib_api.h
[Pipeline] echo
15:45:13  runtime/tests/algorithm/algotest.c
[Pipeline] echo
15:45:13  runtime/tests/vm/vmtest.c

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/803/

**Comment by pdbain-ibm** [comment]
Copyrights updated.  Pull request build passed.

**Pull request merged**
