### PR TITLE
Fix datestamp to be ISO8601

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- YYYYMMDD-HHMMSS
- Affects the SDK filenames as well as the
  merge date on the OMR tags
- Move function to be reusable

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
cc @Maldivia
@keithc-ca for review

**Comment by keithc-ca** [comment]
Thanks, @AdamBrousseau for fixing that annoyance.

**Comment by keithc-ca** [comment]
Cancelled travis build.

**Comment by keithc-ca** [comment]
Jenkins sanity.functional zlinux jdk10

**Comment by AdamBrousseau** [comment]
Jenkins compile zlinux jdk10

**Comment by AdamBrousseau** [comment]
`Using SDK_FILENAME = OpenJ9-JDK10-linux_390-64_cmprssptrs-20181003-141417.tar.gz`

**Pull request merged**
