### PR TITLE
Fix String.indexOf corner case where start == Integer.MAX_VALUE - 1

### PR DESCRIPTION
**Pull request by fjeremic**
When calling the `java.lang.String.indexOf` API with a `String`
argument and passing the starting offset to be `Integer.MAX_VALUE - 1`
we encounter an overflow when we test for the following condition:

```
if (start + s2len > s1len) {
    return -1;
}
```

This if statement checks that the there are enough characters from the
starting position the user specified for the substring to occur. i.e.
if the source string is "abcdefg" and the substring is "fghijk" and
start offset is 2 then because the length of the source string is 7 and
the length of the substring is 6, 2 + 6 > 7 so it is impossible for the
substring to be contained within the source string. We can return -1
immediately.

The problem with the if statement is if we pass a starting offset to be
`Integer.MAX_VALUE - 1` which is a valid input the addition in the if
statement overflows and we never enter the if block, even though we
should have had there been no overflow. This causes us to call the
JITHelpers intrinsic which has implicit assumptions about the arguments
and we end up dereferencing memory outside of the heap.

This commit fixes the overflow by using subtraction. We also take this
opportunity to document the implicit assumptions on the JIT intrinsics
that we make use of.

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8

**Comment by andrewcraik** [comment]
x changes and common code changes look good - I'll leave it to someone else to verify the POWER and z changes since I'm not an expert on those areas.

**Comment by fjeremic** [comment]
@gita-omr @r30shah could we get a review for Power and Z please?

**Comment by gita-omr** [comment]
@aviansie-ben could you please review Power changes?

**Comment by gita-omr** [comment]
Looks fine to me. Just wanted @aviansie-ben to take a look at the  Power changes.

**Comment by pshipton** [comment]
I'll go ahead and merge since it seems everyone has approved now.

**Pull request merged**
