### PR TITLE
Remove JVM_IsDynamicDumpingEnabled

### PR DESCRIPTION
**Pull request by keithc-ca**
Fixes: #10935.

### CODE REVIEW

**Comment by pshipton** [comment]
We need an openjdk acceptance build promotion before this will be moved out of draft state.
https://ci.eclipse.org/openj9/job/Pipeline-OMR-Acceptance/

**Comment by keithc-ca** [comment]
> We need an openjdk acceptance build promotion before this will be moved out of draft state.
> https://ci.eclipse.org/openj9/job/Pipeline-OMR-Acceptance/

Agreed, but I think you meant to refer to https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK-Acceptance/.

**Comment by pshipton** [comment]
Any old acceptance build won't do? :) Thanks, I've fixed the link in my update. FYI my update wasn't intended for you, but for any others looking at this PR.

**Comment by keithc-ca** [comment]
I think we're ready for this. Last night's acceptance build would have passed if not for what appears to be a machine problem building AIX (https://ci.eclipse.org/openj9/job/Build_JDKnext_ppc64_aix_OpenJDK/238/):
```
[2020-10-21T02:35:57.337Z] Error: LinkageError occurred while loading main class build.tools.symbolgenerator.CreateSymbols
[2020-10-21T02:35:57.337Z] 	java.lang.ClassFormatError: JVMCFRE113 unexpected EOF; class=build/tools/symbolgenerator/CreateSymbols, offset=0
[2020-10-21T02:35:57.337Z] gmake[3]: *** [Gendata.gmk:72: /home/jenkins/workspace/Build_JDKnext_ppc64_aix_OpenJDK/build/aix-ppc64-server-release/support/javadoc-symbols/symbols] Error 1
[2020-10-21T02:35:57.337Z] gmake[2]: *** [make/Main.gmk:153: jdk.javadoc-gendata] Error 2
```

**Comment by pshipton** [comment]
Started a new build to test AIX and promote the level if successful.

https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK-Acceptance/362/

**Comment by pshipton** [comment]
jenkins compile zlinux jdk15

**Comment by pshipton** [comment]
jenkins compile zlinux jdknext

**Comment by pshipton** [comment]
lgtm, forgot to approve it.

**Pull request merged**
