### PR TITLE
Initial implementation of TR_ResolvedRelocatableJ9JITaaSServerMethod

### PR DESCRIPTION
**Pull request by satbir-ca**
TR_ResolvedRelocatableJ9JITaaSServerMethod is drived from TR_ResolvedJ9JITaaSServerMethod

Signed-off-by: Satbir Singh <satbir.singh1@ibm.com>

### CODE REVIEW

**Comment by satbir-ca** [comment]
@mpirvu please review the code

**Comment by mpirvu** [comment]
Also, "is drived" --> "is derived", but maybe a more descriptive commit message would be helpful here.

**Comment by satbir-ca** [comment]
updated

**Comment by satbir-ca** [comment]
rebased

**Pull request merged**
