### PR TITLE
Remove all out-of-process code

### PR DESCRIPTION
**Pull request by gacholio**
Debug extensions are obsolete.

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
I don't expect a detailed review of this PR - it's just deleting dead code and removing unnecessary macros, then deleting completely unused code.

**Comment by pshipton** [comment]
@keithc-ca

**Comment by pshipton** [comment]
jenkins test sanity win,aix,win32,zlinux,osx jdk8

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/791/

**Comment by pshipton** [comment]
jenkins compile xlinux+cmake jdk11

**Comment by gacholio** [comment]
> jenkins compile xlinux+cmake jdk11

Is that not the CI build?

**Comment by pshipton** [comment]
> Is that not the CI build?

Ya, I thought I saw a `[ci skip]` but I see the ci build did run already. I will stop the unnecessary build.

**Comment by gacholio** [comment]
> > Is that not the CI build?
> 
> Ya, I thought I saw a `[ci skip]` but I see the ci build did run already. I will stop the unnecessary build.

I default to skip, but I repushed it without since I was clearly changing the cmake files.

**Comment by pshipton** [comment]
I didn't run it correctly anyway.

**Comment by pshipton** [comment]
The mac failures is a known problem #6361

**Pull request merged**
