### PR TITLE
Update JDK8 windows compiles to use Visual Studio 2013

### PR DESCRIPTION
**Pull request by jdekonin**
* [skip ci]
* eclipse/openj9#10129

Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/449

Doc issue https://github.com/eclipse/openj9-docs/issues/662

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
jenkins test sanity win32,win jdk8

**Comment by jdekonin** [comment]
jenkins test sanity win32,win jdk8 depends ibmruntimes/openj9-openjdk-jdk8#449

**Comment by jdekonin** [comment]
jenkins test sanity win jdk8 depends ibmruntimes/openj9-openjdk-jdk8#449

**Comment by jdekonin** [comment]
jenkins test sanity win32,win jdk8 depends ibmruntimes/openj9-openjdk-jdk8#449

**Comment by jdekonin** [comment]
jenkins test sanity win32,win jdk8 depends ibmruntimes/openj9-openjdk-jdk8#449

**Comment by jdekonin** [comment]
jenkins test sanity win32,win jdk8 depends ibmruntimes/openj9-openjdk-jdk8#449

**Comment by pshipton** [comment]
@jdekonin conflicts now.

**Comment by jdekonin** [comment]
I'm not surprised, but easy enough to correct.

jenkins test sanity win32,win jdk8 depends ibmruntimes/openj9-openjdk-jdk8#449

**Comment by jdekonin** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/449 will need to be reviewed and merged at the same time as this PR.

**Comment by keithc-ca** [comment]
Jenkins test sanity win,win32 jdk8 depends ibmruntimes/openj9-openjdk-jdk8#449

**Comment by pshipton** [comment]
I've added the `depends:doc` label as we need to update the build environments in https://www.eclipse.org/openj9/docs/openj9_support/
I can take care of that.

**Comment by pshipton** [comment]
@jdekonin pls confirm the VS2013 version (update 5?) we have installed.

**Review by keithc-ca — APPROVED** [review]

**Comment by jdekonin** [comment]
Yes, 40629 is VS2013 update 5.  All windows systems at on the same level.

```
08:31:27  * Toolchain:      microsoft (Microsoft Visual Studio 2013)
08:31:27  * C Compiler:     Version 18.00.40629 (at /cygdrive/c/progra~2/micros~3.0/vc/bin/cl)
08:31:27  * C++ Compiler:   Version 18.00.40629 (at /cygdrive/c/progra~2/micros~3.0/vc/bin/cl)
```

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
Jumped the gun. There is a merge conflict in https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/449 that needs to be resolved first.

**Pull request merged**
