### PR TITLE
Modify the translated PII files in nls folder-20200430

### PR DESCRIPTION
**Pull request by XiaojuanChen**
Files update for 2020_PII_Ship1.

Signed-off-by: Xiao Juan Chen <bjchenxj@cn.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
There are 5 errors:
```
* Failure occured during the process *
Error: J9NLS_SHRC_SHRINIT_OPTION_INVALID_LAYER_NUMBER Message "A(z) "%s" esetén a(z) %d érvénytelen rétegszám érhető el. A rétegszámnak %d értéknél kisebbnek kell lennie." in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/shrc/j9shr_hu.nls is different from "Invalid layer number %d found for "%s". The layer number should be less than %d." in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/shrc/j9shr.nls

* Failure occured during the process *
Error: J9NLS_SHRC_SHRINIT_OPTION_INVALID_LAYER_NUMBER Message ""%s"에 대해 올바르지 않은 계층 번호 %d이(가) 발견되었습니다. 계층 번호는 %d 미만이어야 합니다." in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/shrc/j9shr_ko.nls is different from "Invalid layer number %d found for "%s". The layer number should be less than %d." in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/shrc/j9shr.nls

* Failure occured during the process *
Error: J9NLS_SHRC_SHRINIT_OPTION_INVALID_LAYER_NUMBER Message ""%s" için geçersiz katman numarası %d bulundu. Katman numarası %d değerinden küçük olmalıdır." in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/shrc/j9shr_tr.nls is different from "Invalid layer number %d found for "%s". The layer number should be less than %d." in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/shrc/j9shr.nls

* Failure occured during the process *
Error: J9NLS_SHRC_SHRINIT_OPTION_INVALID_LAYER_NUMBER Message "為 "%s" 找到的層號碼 %d 無效。層號碼應該小於 %d。" in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/shrc/j9shr_zh_TW.nls is different from "Invalid layer number %d found for "%s". The layer number should be less than %d." in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/shrc/j9shr.nls

* Failure occured during the process *
Error: J9NLS_VM_CLASS_RELATIONSHIP_INVALID Message "Relazione caricamento classe non valida per l'elemento child: %2$.*1$s, elemento parent: 4$.*3$s" in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/j9vm/j9vm_it.nls is different from "Invalid class loading relationship for child: %2$.*1$s, parent: %4$.*3$s" in /home/travis/build/eclipse/openj9-openjdk-jdk11/openj9/runtime/nls/j9vm/j9vm.nls
```

**Comment by XiaojuanChen** [comment]
@pshipton Thanks for providing 5 errors. But I am sure how  to fix in in translations. What is different with EN and languages? Could you give some suggestion? Thanks!

**Comment by pshipton** [comment]
The errors are related to the parameters. In the first 4 errors, the parameter order is %d %s %d. In the translated messages the order is %s %d %d. The order cannot change.

In the 5th error `4$.` should be `%4$.`, same as the English.

**Comment by XiaojuanChen** [comment]
Thanks Peter! I will close this PR.

**Comment by XiaojuanChen** [comment]
@pshipton If translation have to use that order %d %s %d because of language syntax, can Travis CI tool ignore this Failure?

**Comment by pshipton** [comment]
> If translation have to use that order %s %d %d because of language syntax, can Travis CI tool ignore this Failure?

I'm not sure what you are asking. The VM build fails with the updated .nls files, we can't accept them until the errors are fixed.

**Pull request closed without merging**
