### PR TITLE
More VMThread reclamation removal

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Eliminate detectEndOfVMThreadGlobalRegisterLiveRange CG phase
* Remove uses of getSupportsVMThreadGRA and fold code
* Remove more VMThread reclamation code from x86

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@0dvictor , I would appreciate a review please.

**Comment by 0xdaryl** [comment]
Jenkins test sanity

**Comment by 0dvictor** [comment]
LGTM

**Comment by 0xdaryl** [comment]
@andrewcraik / @ymanton : could I ask one of you to merge (and review as well if you like) once the CI has completed?  Thank you.

**Comment by andrewcraik** [comment]
Windows failures due to #2129 others are clean

**Pull request merged**
