### PR TITLE
Extend summary table to include all downstream builds

### PR DESCRIPTION
**Pull request by vsebe**
Add build and test pipelines status and runtime to the downstream jobs
summary.

[ci skip]

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
@jdekonin please review, thx

**Comment by vsebe** [comment]
[personal build](https://ci.eclipse.org/openj9/view/Sandbox/job/vs_Pipeline_Build_Test_All/13/)

**Comment by pshipton** [comment]
The labels don't seem to line up correctly. I see labels on the platform line, and nothing on the sanity.functional line.

**Comment by vsebe** [comment]
@pshipton please have a look at this build: https://ci.eclipse.org/openj9/view/Sandbox/job/vs_Pipeline_Build_Test_All/14/ - has finished downstream jobs.

https://ci.eclipse.org/openj9/view/Sandbox/job/vs_Pipeline_Build_Test_All/13/ looks as designed, not all of the downstream jobs run to completion.
On the platform line it shows the status of the `Pipeline-Build-Test-JDK<version>-<platform>`. The sanity.functional has not run that's why the cell is empty.

**Pull request merged**
