### PR TITLE
Process zip files up to 4 GB

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Change 32-bit signed variables to unsigned variables to allow zip/jar files up
to 4 GB. Use a common function to check if results are in the correct range.

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pdbain-ibm** [comment]
@gacholio would you kindly review?  Thank you

**Comment by pdbain-ibm** [comment]
@DanHeidinga or @gacholio would you kindly run pull request builds.
Thank you

**Comment by gacholio** [comment]
jenkins test sanity xlinux jdk8

**Comment by gacholio** [comment]
IP validation and signed off checks fail due to the merge commit from git.  copyright failure is some other foolishness unrelated to this PR.

**Pull request merged**
