### PR TITLE
Use getClass instead of getFixedClass

### PR DESCRIPTION
**Pull request by liqunl**
The function name is changed in OMR.

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
This PR depends on OMR PR https://github.com/eclipse/omr/pull/2396

**Comment by liqunl** [comment]
@andrewcraik Can you review this PR. The ci build failed/will fail due to the breaking dependency on the OMR PR.

**Comment by DanHeidinga** [comment]
Looks like OMR sync build is broken until this is merged

**Comment by liqunl** [comment]
@andrewcraik This PR depends on the OMR one, the jenkins test won't pass. My pbuild has passed. I think you can ignore the Jenkins test.

**Comment by andrewcraik** [comment]
ok the change is pretty simple and matches the OMR - I'm going to merge this to get the build going. @liqunl please help monitor the builds in case of any failures.

**Pull request merged**
