### PR TITLE
Enable gcc 7.5 on Linux x86 platform

### PR DESCRIPTION
**Pull request by KevinBonilla**
Upgrade gcc compiler from v7.3.0 to v7.5.0.

[ci skip]

This shouldn't be merged before #8443

fyi: @pshipton @vsebe 

Signed-off-by: kevin-bonilla <kevin.bonilla@ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
@KevinBonilla you need to add a Signed-off-by: footer to your commit. You can reword your commit and force push it to this PR.

**Comment by KevinBonilla** [comment]
> 
> 
> @KevinBonilla you need to add a Signed-off-by: footer to your commit. You can reword your commit and force push it to this PR.

Added Signed-off-by footer to commit and PR.

**Comment by pshipton** [comment]
@KevinBonilla the eca check is still failing. I don't think the Signed-off-by: is in the right form, here is mine as an example.
`Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>`

**Comment by pshipton** [comment]
The Signed-off-by: is typically added automatically. For example using -s or --signoff with the git commit command. You need to set user.name and user.email in your git config.

**Comment by KevinBonilla** [comment]
> 
> 
> @KevinBonilla the eca check is still failing. I don't think the Signed-off-by: is in the right form, here is mine as an example.
> `Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>`

Thanks @pshipton, I learn something new everyday! I just modified my commit messaged and added the `--signoff` flag. Check is passing now.

**Pull request merged**
