### PR TITLE
Added ubuntu18 x86 Dockerfile

### PR DESCRIPTION
**Pull request by cwesMills**
Added new dockerfile to create ubuntu18 docker containers
for testing purposes only.

Signed-off-by: Colton Mills <millscolt3@gmail.com>

### CODE REVIEW

**Comment by cwesMills** [comment]
@AdamBrousseau

**Comment by cwesMills** [comment]
The dockerfile is the same as ubuntu18 on z and p

**Comment by AdamBrousseau** [comment]
@llxia for merge please

**Comment by AdamBrousseau** [comment]
@pshipton for merge

**Pull request merged**
