### PR TITLE
(v0.22.0) Hidden class implementation 4

### LINKED ISSUE #9328: JEP 371 Hidden Classes
https://openjdk.java.net/jeps/371

This is delivered to OpenJDK now, affecting OpenJ9 builds of jdk15.

### PR DESCRIPTION
**Pull request by hangshao0**
1. Add checks for class bytes for hidden classes in MethodHanles.
2. Do bytecode verification for hidden classes.
3. Do not allow record and enum to be defined as hidden classes.
4. Fix APIs for hidden classes in Class.java.

Closes #9328

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
Copyright check failing, which means this was somehow ported incorrectly.

**Comment by gacholio** [comment]
If this was ported by any means other than cherry picking the commit, please abandon this and do it that way.

**Comment by hangshao0** [comment]
I was using cherry pick, not sure what went wrong there.

**Comment by hangshao0** [comment]
OK. I see what is going on. 
The copy right date of vrfyhelp.c in master is changed by https://github.com/eclipse/openj9/pull/10404. It was merged before my change. So it is already 2020 in master before my PR, so my change does not (need to) update the copy right.

https://github.com/eclipse/openj9/pull/10404 is not in v0.22.0 branch, so the copy right date is still 2019 in v0.22.0.

**Comment by gacholio** [comment]
OK, that makes sense. Go ahead and re-open and fix the copyright.

**Comment by gacholio** [comment]
In this case, I would not squash so that the real commit is unchanged.

**Comment by hangshao0** [comment]
New PR: https://github.com/eclipse/openj9/pull/10520

**Comment by hangshao0** [comment]
> In this case, I would not squash so that the real commit is unchanged.

Already squashed, I didn't see this comment when I open #10520. But I can split the copyright date change out in to a separate commit if you want.

**Comment by gacholio** [comment]
No it's fine as it is.

**Comment by gacholio** [comment]
Alternately, we could close the new PR, re-open this one, and apply the copyright fix unsquashed.

**Pull request closed without merging**
