### PR TITLE
Updated ppc64le ubuntu16 Dockerfile

### PR DESCRIPTION
**Pull request by cwesMills**
Added gdb to package list to allow generation of core files

Signed-off-by: Colton Mills <millscolt3@gmail.com>

### CODE REVIEW

**Comment by cwesMills** [comment]
@AdamBrousseau

**Comment by cwesMills** [comment]
@keithc-ca could you give a final review/merge

**Comment by AdamBrousseau** [comment]
@llxia for merge please

**Comment by AdamBrousseau** [comment]
@pshipton for merge

**Pull request merged**
