### PR TITLE
Refactor allowGuardMerging() to the common codegen

### PR DESCRIPTION
**Pull request by dchopra001**
Signed-off-by: Dhruv Chopra <Dhruv.C.Chopra@ibm.com>

### CODE REVIEW

**Comment by dchopra001** [comment]
See https://github.com/eclipse/omr/pull/4456 for related OMR PR.

@fjeremic Can I get a review please?

**Comment by dchopra001** [comment]
Note: I have verified these tests with internal builds w.r.t JITServer testing. Except for an existing issue, the builds are stable for: `_sanity.functional.regular, _sanity.functional.native,` and also for cold/warm runs of AcmeAir. (Mentioning this here since JITServer on Z is not stable in upstream yet, we won't be able to run testing for it.)

**Comment by mpirvu** [comment]
```
../../../../../openj9/runtime/compiler/codegen/CodeGenGPU.cpp:1300:1: error: static assertion failed: Number of elements in nvvmOpCodeNames does not match the value of TR::NumIlOps
```
Maybe you need a rebase?

**Comment by dchopra001** [comment]
Trying a rebase. I think 91f2a080436c70fe1fb7a3206fe6383677e3a75a should fix it.

**Comment by mpirvu** [comment]
jenkins test sanity all jdk11

**Pull request merged**
