### PR TITLE
Migrate innerConstrainAcall to OpenJ9

### PR DESCRIPTION
**Pull request by 0xdaryl**
Move the implementation from OMRValuePropagation, and add a virtual
function in OpenJ9.

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11,jdk8

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11,jdk8

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

Rebased and re-pushed.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by 0xdaryl** [comment]
Un-WIPing as OMR change has been merged.

**Comment by 0xdaryl** [comment]
@vijaysun-omr , this is the OpenJ9 piece of eclipse/omr#3763.  Would you mind reviewing/merging if you have time?

**Comment by vijaysun-omr** [comment]
Jenkins test sanity all jdk11

**Comment by vijaysun-omr** [comment]
Change looks safe to me and checks passed. Merging.

**Pull request merged**
