### PR TITLE
Add jitCloneValueType jit runtime helper

### PR DESCRIPTION
**Pull request by OussamaSaoudi**
Added following jit runtime helpers:
- old_slow_jitCloneValueType: Clones value using slow path, and
throws exceptions when needed.
- old_fast_jitCloneValueType: Clones value using fast path, if
unexpected bahaviour occurs, directs to slow path.

Both perform clone operation on ValueType

Signed-off-by: Oussama Saoudi <oussama.saoudi@ibm.com>

### CODE REVIEW

**Comment by OussamaSaoudi** [comment]
@tajila

**Review by tajila — APPROVED** [review]

**Comment by tajila** [comment]
Jenkins test sanity win jdk8

**Comment by tajila** [comment]
Jenkins test sanity xlinuxvalst jdknext

**Comment by tajila** [comment]
Jenkins test sanity zlinux jdk8

**Pull request merged**
