### PR TITLE
Prepended test jvm lib dir to the LIBPATH

### PR DESCRIPTION
**Pull request by llxia**
Issue: #7822
[ci skip]
Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
jenkins test sanity,extended all jdk8

**Comment by llxia** [comment]
Will relaunch for [AIX](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_ppc64_aix_Personal/68/console) as the error is `Remote call on aix71-p8-9 failed`

**Comment by llxia** [comment]
jenkins test extended aix,win32,xlinuxlargeheap,plinux jdk8

**Comment by llxia** [comment]
jenkins test sanity,extended all jdk11

**Comment by llxia** [comment]
- TestAttachErrorHandling failure on [AIX JDK11](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Personal/52) and [AIX JDK8](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_ppc64_aix_Personal/69/console) is related to https://github.com/eclipse/openj9/issues/3081
- TestManagementAgent_0 failure on [ppcle JDK11](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64le_linux_Personal/72/console), [ppcle JDK8](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_ppc64le_linux_Personal/112/console) and [xlinux](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Personal/49/console) in related to https://github.com/eclipse/openj9/issues/7820

**Comment by llxia** [comment]
jenkins test extended plinuxlargeheap jdk11

**Comment by llxia** [comment]
jenkins test extended xlinuxlargeheap jdk8

**Comment by llxia** [comment]
jenkins test extended plinuxlargeheap jdk11

**Comment by llxia** [comment]
It seems this change causes `testJCMMXBeanRemote` to hang on ppcle xl and xlinux xl.

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64le_linux_xl_Personal/5/console
```
11:01:06  ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
11:01:06  ...
11:01:06  
11:29:00  Cannot contact ub16p8j93: java.lang.InterruptedException
Cancelling nested steps due to timeout
20:16:10  Sending interrupt signal to process
20:16:24  
20:16:24  testJCMMXBeanRemote_0_FAILED
20:16:24  
```
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Personal/56/console
```
14:46:47  ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
14:46:47  ...
14:46:47  
Cancelling nested steps due to timeout
20:41:42  Sending interrupt signal to process
20:41:46  [JvmCpuMonitorMXBeanTest] [WARN] Failed connecting. Retry 1 after 1000 ms.
20:41:46  
20:41:46  testJCMMXBeanRemote_SE80_0_FAILED
```

**Comment by pshipton** [comment]
Can we have different behavior per platform, and only prepend on AIX?

**Comment by smlambert** [comment]
Would be better to avoid differing the behaviour between platforms and also to understand why prepending would cause the hang on those specific SPECs...  (since design decisions driven by avoidance usually comes back to bite us later).

**Comment by llxia** [comment]
Since openj9Settings.mk is moved to TKG now, we may have a glitch. I will create PR in TKG repo and retest. Close this PR.

**Comment by llxia** [comment]
PR in TKG repo: https://github.com/AdoptOpenJDK/TKG/pull/19

**Pull request closed without merging**
