### PR TITLE
Use maximum allowed scratch space memory limit for JitDump compilations

### PR DESCRIPTION
**Pull request by fjeremic**
Tracing higher optimization level compilations may put us past the
allocation limit and result in an std::bad_alloc exception being thrown.
To maximize our chances of getting a trace log we artificially inflate
the scratch space memory for JitDump compilations.

### CODE REVIEW

**Comment by fjeremic** [comment]
Suggesting @dsouzai for committer. @r30shah FYI this will help us gather a JitDump for #12557.

**Comment by fjeremic** [comment]
Launching a build so we can launch a grinder with this fix and hopefully get a log for the blocker.

Jenkins test sanity zlinux jdk16

**Review by dsouzai — APPROVED** [review]
Looks fine to me; just note though that the limit can still change even in a jitdump compile later on because of jsr292, or jitserver, or if `TR_EnableSelfTuningScratchMemoryUsageBeforeCompile` is set.

**Comment by dsouzai** [comment]
Jenkins test sanity zlinux jdk16

**Comment by dsouzai** [comment]
Several Jenkins failures :/

**Comment by dsouzai** [comment]
Jenkins test sanity zlinux jdk16

**Pull request merged**
