### PR TITLE
Enable CUDA in 64-bit Windows builds

### PR DESCRIPTION
**Pull request by keithc-ca**

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins compile win jdk11

**Comment by keithc-ca** [comment]
This depends upon a resolution to #7432.

**Comment by keithc-ca** [comment]
It may make more sense to move the use of `cygpath` into the configure scripts - I'll investigate.

**Comment by keithc-ca** [comment]
Simplified to assume these are merged so Windows paths are handled properly:
* https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/337
* https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/223
* https://github.com/ibmruntimes/openj9-openjdk-jdk13/pull/21
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/144

**Comment by pshipton** [comment]
jenkins compile win jdk8 depends ibmruntimes/openj9-openjdk-jdk8#337

**Comment by pshipton** [comment]
Machines might be fine now, but the build doesn't work yet.
```
10:46:38  /cygdrive/c/Users/jenkins/workspace/Build_JDK11_x86-64_windows_Personal/build/windows-x86_64-normal-server-release
10:46:38  using configure arguments '--with-freemarker-jar=/cygdrive/c/openjdk/freemarker.jar --with-boot-jdk=/cygdrive/c/openjdk/jdk11 --with-toolchain-version=2017 --disable-ccache --with-openssl=/cygdrive/c/openjdk/OpenSSL-1.1.1-x86_64 --enable-openssl-bundling --enable-cuda --with-cuda='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0''.
10:46:38  
10:46:38  Configuration summary:
10:46:38  * Debug level:    release
10:46:38  * HS debug level: product
10:46:38  * JVM variants:   server
10:46:38  * JVM features:   server: 'cds cmsgc compiler1 compiler2 epsilongc g1gc graal jfr jni-check jvmci jvmti management nmt parallelgc serialgc services vm-structs' 
10:46:38  * OpenJDK target: OS: windows, CPU architecture: x86, address length: 64
10:46:38  * Version string: 11.0.5-internal+0-adhoc.jenkins.BuildJDK11x86-64windowsPersonal (11.0.5-internal)
10:46:38  
10:46:38  Tools summary:
10:46:38  * Environment:    cygwin version 2.10.0(0.325/5/3) (root at /cygdrive/c/cygwin64)
10:46:38  * Boot JDK:       openjdk version "11.0.1" 2018-10-16  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)  Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Windows Server 2012 R2 amd64-64-Bit Compressed References 20181115_19 (JIT enabled, AOT enabled) OpenJ9   - 090ff9dcd OMR      - ea548a66 JCL      - d4455071ce based on jdk-11.0.1+13)   (at /cygdrive/c/openjdk/jdk11)
10:46:38  * Toolchain:      microsoft (Microsoft Visual Studio 2017)
10:46:38  * C Compiler:     Version 19.15.26726 (at /cygdrive/c/progra~2/mib055~1/2017/commun~1/vc/tools/msvc/1415~1.267/bin/hostx86/x64/cl)
10:46:38  * C++ Compiler:   Version 19.15.26726 (at /cygdrive/c/progra~2/mib055~1/2017/commun~1/vc/tools/msvc/1415~1.267/bin/hostx86/x64/cl)
10:46:38  
10:46:38  Build performance summary:
10:46:38  * Cores to use:   7
10:46:38  * Memory limit:   8187 MB
10:46:38  * ccache status:  Disabled
10:46:38  
10:46:39  + make all
10:46:39  /cygdrive/c/Users/jenkins/workspace/Build_JDK11_x86-64_windows_Personal/build/windows-x86_64-normal-server-release//custom-spec.gmk:50: *** invalid syntax in conditional.  Stop.
```

**Comment by pshipton** [comment]
custom-spec.gmk:50 is `ifneq (,@OPENJ9_CUDA_HOME@)`

**Comment by pshipton** [comment]
Jenkins compile win jdk11

**Comment by keithc-ca** [comment]
Rebased and resolved merge conflict.

**Comment by keithc-ca** [comment]
Rebased.

**Comment by keithc-ca** [comment]
Jenkins compile win jdk11

**Pull request merged**
