### PR TITLE
Restore the inline handling for 'StrictMath.sqrt()' and 'Math.sqrt()' on X86

### PR DESCRIPTION
**Pull request by simonameng**
Put back the `inlineMathSQRT` function and the related switch cases on X86. Because the transformation to `dsqrt` (changes in #6217) will not be triggered in X86 and Power, leading to slow performance on calling the `StrictMath.sqrt` and `Math.sqrt` to the VM which implements the function. 
We'll keep the `inlineMathSQRT` on X86 for now. And then we'll work on the proper solution (reduce the call to a proper `dsqrt` evaluator).

Fixes: #7525

Signed-off-by: simonameng <simonameng97@gmail.com>

### CODE REVIEW

**Comment by simonameng** [comment]
@andrewcraik @fjeremic

**Comment by andrewcraik** [comment]
If POWER is also broken and you need to do further work before you can re-enable please also restore the inline handling on POWER.

**Comment by fjeremic** [comment]
Just waiting for confirmation from @simonameng that the performance is restored following this change by measuring the bumblebench micro-benchmark from #7525 on x86 and Power machines.

**Comment by simonameng** [comment]
I ran the bumblebench performance on Power for the jvm which includes the power switch cases and the jvm which excludes the power switch cases. I found the performance scores are almost the same on Power. I also checked in the trace log for the jvm without switch cases. The trace log shows that it will end up generating a `dsqrt` IL, which will call `dsqrtEvaluator` on Power. Therefore, I remove the restoration of switch cases on Power. 

As for the comparison of bumblebench scores on X86, the JVM with `inlineMathSQRT` does have much higher scores than the one without it.

**Comment by andrewcraik** [comment]
where does the dsqrt come from on POWER?

**Comment by fjeremic** [comment]
> where does the dsqrt come from on POWER?

It's in the tree evaluator table here:
https://github.com/eclipse/omr/blob/75dd916218addfef73d8be04ffd270651526a198/compiler/z/codegen/OMRTreeEvaluatorTable.hpp#L766

And it's implemented here:
https://github.com/eclipse/omr/blob/1bc0b8512f7f192f377126b4cd56cf425901a5a0/compiler/p/codegen/FPTreeEvaluator.cpp#L2540-L2552

If you note the former Power function from #6217 had the exact same implementation as the `dsqrtEvaluator` above. You can see the deleted function from #6217 here:
https://github.com/eclipse/openj9/pull/6217/files#diff-efcdf3eda93e6ae70d4c46dd0bf9b5acL13430

**Comment by andrewcraik** [comment]
Jenkins test xlinux,xlinuxxl,win jdk8,jdk11

**Comment by andrewcraik** [comment]
Jenkins test xlinux,xlinuxxl,win jdk8,jdk11

**Comment by andrewcraik** [comment]
@fjeremic any idea what's going wrong with the sanity testing?

**Comment by fjeremic** [comment]
Jenkins test sanity xlinux,xlinuxxl,win jdk8,jdk11

**Comment by fjeremic** [comment]
> @fjeremic any idea what's going wrong with the sanity testing?

I think the "sanity" keyword was missed.

**Pull request merged**
