### PR TITLE
Avoid mishandling of immutable objects that escape in cold blocks

### PR DESCRIPTION
**Pull request by hzongaro**
In fixupNode, force non-contiguous, immutable objects that escape in
cold blocks to go through fixupFieldAccess processing to ensure the
temporary that will replace it will be properly initialized.

Then, in fixupFieldAccessForNonContiguousAllocation, ensure the store
to the original object is preserved along with the store to the temporary
that's being created to replace its field.  The former will be needed
if we escape, and the latter is needed if we don't escape.

Fixes:  #4281

Signed-off-by:  Henry Zongaro <zongaro@ca.ibm.com>

### CODE REVIEW

**Comment by hzongaro** [comment]
@vijaysun-omr Vijay, may I ask you to review this pull request?

**Comment by vijaysun-omr** [comment]
Looks good to me @hzongaro The logic makes sense to keep both auto and field store when we have the special case of an immutable discontiguous allocation that escapes in the given block.

**Comment by hzongaro** [comment]
Thanks, Vijay @vijaysun-omr , for all your guidance, help and advice in fixing this problem!

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux jdk11,jdk8

**Comment by DanHeidinga** [comment]
This is targeted for post-`0.12.0`.  I've assigned it to the `0.13.0` milestone so we can ensure it gets merged as soon as possible after we open up master again

**Comment by charliegracie** [comment]
Can this be merged now?

**Comment by andrewcraik** [comment]
I believe so - I'm happy with this given the clean sanity and review from @vijaysun-omr.

**Pull request merged**
