### PR TITLE
Updated job build description

### PR DESCRIPTION
**Pull request by cwesMills**
Previously when building a docker container build description
was overwritten by new data, but now new data will be appended
to the build description.

Signed-off-by: Colton Mills <millscolt3@gmail.com>

### CODE REVIEW

**Comment by cwesMills** [comment]
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
@llxia for final review/merge

**Comment by AdamBrousseau** [comment]
Jenkind build docker s390x ubuntu16

**Comment by AdamBrousseau** [comment]
Jenkins build docker s390x ubuntu16

**Comment by AdamBrousseau** [comment]
I killed the build once the changed code was executed
image

**Pull request merged**
