### PR TITLE
Migrate testSCCMLTests3 to openj9/test

### PR DESCRIPTION
**Pull request by sophia-guo**
Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by smlambert** [comment]
Can you please clean up/remove the author annotations from the test files?

**Comment by smlambert** [comment]
Jenkins test extended

**Comment by sophia-guo** [comment]
Updated. @smlambert

**Comment by smlambert** [comment]
@sophia-guo - https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-Extended-linux_390-64_cmprssptrs/9/console

**Comment by sophia-guo** [comment]
Jenkins test extended

**Comment by llxia** [comment]
Jenkins test extended

**Pull request merged**
