### PR TITLE
Fixed asmtools.jar download

### PR DESCRIPTION
**Pull request by LongyuZhang**
- changed url and SHA for asmtools.jar download source
[ci skip]

Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
reviewers: @llxia

**Comment by llxia** [comment]
jenkins test sanity,extended plinux,win jdk8,jdk11

**Comment by llxia** [comment]
jenkins test sanity,extended plinux,win jdk8

**Comment by llxia** [comment]
jenkins test sanity,extended plinux,win jdk8

**Comment by llxia** [comment]
Grinder:
sanity.functional: https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/468/
extended.functional: https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/469/

**Comment by smlambert** [comment]
Will merge now, as Grinders are good, and not waiting for PR builds to be fixed (unknown ETA).

**Pull request merged**
