### PR TITLE
Rework timeout handling for the cmdline tester

### PR DESCRIPTION
**Pull request by pshipton**
Fixes https://github.com/eclipse/openj9/issues/11397

Tested Java 8 Windows 32-bit sanity.functional via grinder https://ci.eclipse.org/openj9/view/Test/job/Grinder/1332/

### CODE REVIEW

**Comment by llxia** [comment]
jenkins test sanity aix,zlinux,win jdk8,jdk11

**Comment by pshipton** [comment]
The AIX test failure https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_Personal/471/ is due to stderr timing out, which wasn't expected or desirable. I had a 1 sec timeout, I've increased it, and the Process timeout as well, to 30 sec. All the other testing passed.

**Comment by pshipton** [comment]
jenkins test sanity aix jdk8

**Comment by pshipton** [comment]
jenkins test sanity aix jdk8,jdk11

**Comment by pshipton** [comment]
@llxia pls take another look.

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
