### PR TITLE
Backout AOT heuristic on PPC

### PR DESCRIPTION
**Pull request by mpirvu**
Some recently introduced AOT heuristic makes some test to fail on PPC.
This is likely due to an existing AOT bug on PPC. Until we figure the
reason, we should backout this change on PPC only.

Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
@mpirvu Can you add details of the failure on P?  It'll make it much easier to identify this issue for anyone else that may be affected and to find this if the failure comes back after reintroducing this change.

**Comment by mpirvu** [comment]
A few of the symptoms:
1) AIX64
```
j> 13:12:28 20181219 13:12:27 Thread Control Engine INFO: Starting JobSet DAA
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR: java.lang.reflect.InvocationTargetException
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR: 
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR:    at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR: 
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR: 
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR:    at java.lang.reflect.Method.invoke(Method.java:508)
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR: 
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR:    at com.ibm.test.Arithmetics.TestPerformance.getReferenceValues(TestPerformance.java:419)
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR: 
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR:    at com.ibm.test.Arithmetics.TestPerformance.testSub(TestPerformance.java:108)
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR: 
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR:    at com.ibm.test.Arithmetics.TestPerformance.testIntrinsicPerformance(TestPerformance.java:57)
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR: 
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR: 
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR: 
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR: 
j> 13:12:39 20181219 13:12:39 <DAA|SimpleDriver|com.ibm.test.Arithmetics.TestPerformance|239|Default Invocant>-STDERR ERROR:    at java.lang.reflect.Method.invoke(Method.java:508)
```
2) LinuxPPC
```
j> 13:15:48 Unhandled exception
j> 13:15:48 Type=Segmentation error vmState=0x00000000
j> 13:15:48 J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
j> 13:15:48 Handler1=00003FFF7E8AEE08 Handler2=00003FFF7E5F2C18
j> 13:15:48 R0=0000000000000000 R1=00003FFE6DD3B710 R2=00003FFF7E8C1608 R3=00003FFF78932800
j> 13:15:48 R4=00003FFF781A1C80 R5=00003FFE4F05CFD0 R6=0000000000000020 R7=0000000000000020
j> 13:15:48 R8=0000000000000000 R9=00003FFF78932908 R10=00003FFDE800AE10 R11=0000000000000000
j> 13:15:48 R12=0000000028444842 R13=00003FFE6DD46900 R14=00003FFDE800AC28 R15=00003FFF78932800
j> 13:15:48 R16=00003FFE6C420038 R17=FFFFFFFFFFFFFFFF R18=00003FFF78933270 R19=00003FFF7E5EC3A8
j> 13:15:48 R20=00003FFF78185500 R21=0000000000000000 R22=00003FFE8F05CFC8 R23=0000000000000000
j> 13:15:48 R24=0000000000000001 R25=0000000000000001 R26=00003FFF78932908 R27=000000003FFFFFF8
j> 13:15:48 R28=00003FFF781A1C80 R29=0000000028444842 R30=00003FFF78932800 R31=0000000000000020
j> 13:15:48 NIP=00003FFF7E7738BC MSR=800000000280F032 ORIG_GPR3=00003FFF7E773348 CTR=00003FFF7E773C00
j> 13:15:48 LINK=00003FFF7E773C34 XER=0000000020000000 CCR=0000000028244842 SOFTE=0000000000000001
j> 13:15:48 TRAP=0000000000000300 DAR=00003FFE8F05CFC8 dsisr=0000000040000000 RESULT=0000000000000000
.....
j> 13:15:48 Module=/bluebird/builds/bld_405311/sdk/xp6480/jre/lib/ppc64/default/libj9vm29.so
j> 13:15:48 Module_base_address=00003FFF7E650000
j> 13:15:48 Target=2_90_20181219_405311 (Linux 3.10.0-514.21.1.el7.ppc64)
j> 13:15:48 CPU=ppc64 (16 logical CPUs) (0x7bc6e0000 RAM)
j> 13:15:48 ----------- Stack Backtrace -----------
j> 13:15:48 (0x00003FFF7E5AB8B8 [libj9prt29.so+0x7b8b8])
j> 13:15:48 (0x00003FFF7E57C250 [libj9prt29.so+0x4c250])
j> 13:15:48 (0x00003FFF7E5AB978 [libj9prt29.so+0x7b978])
j> 13:15:48 (0x00003FFF7E5ABB4C [libj9prt29.so+0x7bb4c])
j> 13:15:48 (0x00003FFF7E5AB540 [libj9prt29.so+0x7b540])
j> 13:15:48 (0x00003FFF7E57C250 [libj9prt29.so+0x4c250])
j> 13:15:48 (0x00003FFF7E5AB608 [libj9prt29.so+0x7b608])
j> 13:15:48 (0x00003FFF7E733850 [libj9vm29.so+0xe3850])
j> 13:15:48 (0x00003FFF7E732EEC [libj9vm29.so+0xe2eec])
j> 13:15:48 (0x00003FFF7E57C250 [libj9prt29.so+0x4c250])
j> 13:15:48 (0x00003FFF7E732780 [libj9vm29.so+0xe2780])
j> 13:15:48 (0x00003FFF7E57FA54 [libj9prt29.so+0x4fa54])
j> 13:15:48 __kernel_sigtramp_rt64+0x0 (0x00003FFF7F5D0478)
j> 13:15:48 (0x000000000000000E [<unknown>+0x0])
j> 13:15:48 (0x00003FFF7E773C34 [libj9vm29.so+0x123c34])
j> 13:15:48 (0x00003FFF7DC32044 [libj9jit29.so+0x1582044])
j> 13:15:48 (0x00003FFF7DC4F53C [libj9jit29.so+0x159f53c])
j> 13:15:48 (0x00003FFF7E716530 [libj9vm29.so+0xc6530])
j> 13:15:48 (0x00003FFF7E78CEA0 [libj9vm29.so+0x13cea0])
j> 13:15:48 (0x00003FFF7E57C250 [libj9prt29.so+0x4c250])
j> 13:15:48 (0x00003FFF7E78CC54 [libj9vm29.so+0x13cc54])
j> 13:15:48 (0x00003FFF7E62CB4C [libj9thr29.so+0xcb4c])
j> 13:15:48 (0x00003FFF7F57C2BC [libpthread.so.0+0xc2bc])
j> 13:15:48 clone+0xfff4298c (0x00003FFF7F42B344 [libc.so.6+0x13b344])
........
p> 20181219-13:16:35 <gdb> backtrace:
p> 20181219-13:16:35 <gdb> #0  0x00003fff7f582f60 in .pthread_kill () from /lib64/libpthread.so.0
p> 20181219-13:16:35 <gdb> #1  0x00003fff7e5ac6d8 in .omrdump_create () from /bluebird/builds/bld_405311/sdk/xp6480/jre/lib/ppc64/default/libj9prt29.so
p> 20181219-13:16:35 <gdb> #2  0x00003fff7e311570 in .doSystemDump () from /bluebird/builds/bld_405311/sdk/xp6480/jre/lib/ppc64/default/libj9dmp29.so
p> 20181219-13:16:35 <gdb> #3  0x00003fff7e3185d8 in .protectedDumpFunction () from /bluebird/builds/bld_405311/sdk/xp6480/jre/lib/ppc64/default/libj9dmp29.so
p> 20181219-13:16:35 <gdb> #4  0x00003fff7e57c250 in .omrsig_protect () from /bluebird/builds/bld_405311/sdk/xp6480/jre/lib/ppc64/default/libj9prt29.so
p> 20181219-13:16:35 <gdb> #5  0x00003fff7e3182b0 in .runDumpAgent () from /bluebird/builds/bld_405311/sdk/xp6480/jre/lib/ppc64/default/libj9dmp29.so
p> 20181219-13:16:35 <gdb> #6  0x00003fff7e3424a8 in .triggerDumpAgents () from /bluebird/builds/bld_405311/sdk/xp6480/jre/lib/ppc64/default/libj9dmp29.so
p> 20181219-13:16:35 <gdb> #7  0x00003fff7e732f20 in .generateDiagnosticFiles () from /bluebird/builds/bld_405311/sdk/xp6480/jre/lib/ppc64/default/libj9vm29.so
p> 20181219-13:16:35 <gdb> #8  0x00003fff7e57c250 in .omrsig_protect () from /bluebird/builds/bld_405311/sdk/xp6480/jre/lib/ppc64/default/libj9prt29.so
p> 20181219-13:16:35 <gdb> #9  0x00003fff7e732780 in .structuredSignalHandler () from /bluebird/builds/bld_405311/sdk/xp6480/jre/lib/ppc64/default/libj9vm29.so
p> 20181219-13:16:35 <gdb> #10 0x00003fff7e57fa54 in .masterSynchSignalHandler$AF35_16 () from /bluebird/builds/bld_405311/sdk/xp6480/jre/lib/ppc64/default/libj9prt29.so
p> 20181219-13:16:35 <gdb> #11 <signal handler called>
p> 20181219-13:16:35 <gdb> #12 0x00003fff7e7738bc in .resolveStaticFieldRefInto () from /bluebird/builds/bld_405311/sdk/xp6480/jre/lib/ppc64/default/libj9vm29.so
p> 20181219-13:16:35 <gdb> #13 0x00003fff7e773c34 in .resolveStaticFieldRef () from /bluebird/builds/bld_405311/sdk/xp6480/jre/lib/ppc64/default/libj9vm29.so
```
3) LinuxPPC
```
j> 13:17:03 20181219 13:17:02 <Primary|SimpleDriver|com.ibm.test.Arithmetics.TestArithmetics|3253|Default Invocant> ERROR: Test randomTest(com.ibm.test.Arithmetics.TestArithmetics) reported an error
j> 13:17:03 Throwable trace:
j> 13:17:03 java.lang.NoClassDefFoundError: math.1C
j> 13:17:03 	at java.math.BigInteger.cutOffLeadingZeroes(BigInteger.java:1505)
j> 13:17:03 	at java.math.Elementary.add(Elementary.java:115)
j> 13:17:03 	at java.math.BigInteger.add(BigInteger.java:588)
j> 13:17:03 	at com.ibm.test.Arithmetics.TestArithmetics.testWithOffsetAndPrec(TestArithmetics.java:66)
j> 13:17:03 	at com.ibm.test.Arithmetics.TestArithmetics.randomTest(TestArithmetics.java:28)
j> 13:17:03 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
j> 13:17:03 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
j> 13:17:03 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
j> 13:17:03 	at java.lang.reflect.Method.invoke(Method.java:508)
j> 13:17:03 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
j> 13:17:03 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
j> 13:17:03 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
j> 13:17:03 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
j> 13:17:03 	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
j> 13:17:03 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
j> 13:17:03 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
j> 13:17:03 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
j> 13:17:03 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
j> 13:17:03 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
j> 13:17:03 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
j> 13:17:03 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
j> 13:17:03 	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
j> 13:17:03 	at org.junit.runners.Suite.runChild(Suite.java:128)
j> 13:17:03 	at org.junit.runners.Suite.runChild(Suite.java:24)
j> 13:17:03 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
j> 13:17:03 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
j> 13:17:03 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
j> 13:17:03 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
j> 13:17:03 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
j> 13:17:03 	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
j> 13:17:03 	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
j> 13:17:03 	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
j> 13:17:03 	at com.ibm.jtc.test.jltf.workunitadapters.JUnit4WorkUnit.runWork(JUnit4WorkUnit.java:300)
j> 13:17:03 	at com.ibm.jtc.test.jltf.threads.WorkUnitRunner.run(WorkUnitRunner.java:113)
j> 13:17:03 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.runWork(PooledRunnable.java:170)
j> 13:17:03 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.getAndRunWork(PooledRunnable.java:136)
j> 13:17:03 	at com.ibm.jtc.test.jltf.threads.pooling.PooledRunnable.run(PooledRunnable.java:93)
j> 13:17:03 	at com.ibm.jtc.test.jltf.threads.PooledLangThreadFactory$JavaLangPooledThread.run(PooledLangThreadFactory.java:152)
j> 13:17:03 20181219 13:17:03 <Primary|SimpleDriver|com.ibm.test.Arithmetics.TestArithmetics|3253|Default Invocant> ERROR: JUnit test finished with: FAIL
j> 13:17:03 20181219 13:17:03 <Primary|SimpleDriver|testcases.misc.JGbigd2(dumponfailure)|3155|Default Invocant> ERROR: JGrinder testcase failed.
```

**Comment by mpirvu** [comment]
@harryyu1994 verified that the errors go away with this change.

**Comment by mpirvu** [comment]
Jenkins test sanity all jdk8

**Comment by ymanton** [comment]
Jenkins test sanity all jdk8

**Comment by ymanton** [comment]
AIX failed due to `17:00:19 gmake[2]: *** virtual memory exhausted.  Stop.`, which is unrelated, everything else passed. Merging.

**Comment by JamesKingdon** [comment]
@mpirvu Do you know if the underlying AOT bug you mentioned was ever identified and fixed?

**Comment by mpirvu** [comment]
No, we didn't identify the bug. It may be worth trying the failing tests again in case some AOT bug responsible for this behavior was independently fixed.

**Comment by JamesKingdon** [comment]
I'm looking at a case at the moment which has similar symptoms from 8.0.7.15 on ppcle

**Comment by JBKingdon** [comment]
An additional case has arrived with these symptoms. In the previous case I got as far as identifying that the math.1x names are ordinary strings from the constant pool that are used as lookups for translatable messages. The failing code appears to be using incorrect CP indexes when accessing the CP. Unfortunately I wasn't able to reproduce the problem in a testcase. I'm hoping to get a compilation log for the problem method from the new case.

**Comment by JamesKingdon** [comment]
I currently have access to a test system which can reproduce the problem. It looks like hitting the problem requires the shared class cache to be populated with bad data, which occurs only intermittently. In my earlier investigation I was suspicious that the cpIndex was incorrect, but in the current log I can see three snippets that are generated with matching cpIndex and constant pool address values, and when the crash happens it is the constant pool address that is different in the failing snippet. Substituting the constant pool address from either of the other two snippets yields an entry that looks like it would have been reasonable in the context. So the current direction is to investigate the relocation of the constant pool address for the three snippets and try and find out why one of them diverges from the other two.

**Pull request merged**
