### PR TITLE
Mark CPU extensible and add new constructor

### PR DESCRIPTION
**Pull request by harryyu1994**
Issue: #4339

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
dependent on https://github.com/eclipse/omr/pull/4744

**Comment by harryyu1994** [comment]
@fjeremic Could you please help review this?

**Comment by fjeremic** [comment]
Jenkins test sanity all depends eclipse/omr#master

**Comment by harryyu1994** [comment]
```
ERROR: Incorrect syntax for requested JDK version:'depends'
Expected 'jdkX' where X is one of [8, 11, 14, next]
Finished: FAILURE
```

**Comment by pshipton** [comment]
Jenkins test sanity all jdk11 depends eclipse/omr#master

**Comment by gacholio** [comment]
Assuming the CI build error isn't real, enough has passed for this to be merged, I think, as it's a common code change.

**Comment by harryyu1994** [comment]
I have verified this change is fine with my personal build. I think the CI build failed because it doesn't use the omr master branch and thus doesn't have the dependent omr change.

**Comment by gacholio** [comment]
Sounds reasonable, I'll merge now so OMR can be accepted again.

**Pull request merged**
