### PR TITLE
Remove the obsolete APIs in known object table

### LINKED ISSUE #8952: Intermittent JITServer Assert in debug build: "_references[1]=0x3b56f0 is not the same as the client KOT[1]=0x3d5230. _references.size()=5"
Running into the following assert intermittently with the debug build while running sanity test `jit_tr_0`. Likely the assert should be removed since the reference could be updated at the client and there is a chance the cached one at the server is staled. 

```
Assertion failed at /root/home/ahuo/src/openj9-openjdk-jdk8/openj9/runtime/compiler/env/J9KnownObjectTable.cpp:248: (objectReferenceLocation == _references[index])
VMState: 0x000501ff
	_references[1]=0x3b56f0 is not the same as the client KOT[1]=0x3d5230. _references.size()=5
compiling org/testng/internal/XmlMethodSelector.includeMethodFromIncludeExclude(Lorg/testng/ITestNGMethod;Z)Z at level: warm
#0: function TR_LinuxCallStackIterator::printStackBacktrace(TR::Compilation*)+0x32 [0x7ffb280d4a0c]
#1: function TR_Debug::printStackBacktrace()+0x23 [0x7ffb280e733b]
#2: /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x102f2b1) [0x7ffb27d6a2b1]
#3: /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so(+0x102f3c9) [0x7ffb27d6a3c9]
#4: function TR::assertion(char const*, int, char const*, char const*, ...)+0x104 [0x7ffb27d6a4d2]
#5: function J9::KnownObjectTable::updateKnownObjectTableAtServer(int, unsigned long*)+0x178 [0x7ffb277e7d20]
#6: function J9::KnownObjectTable::getIndexAt(unsigned long*)+0x93 [0x7ffb277e77b7]
#7: function J9::SymbolReferenceTable::findOrCreateStringSymbol(TR::ResolvedMethodSymbol*, int)+0x132 [0x7ffb27772a9c]
#8: function TR_J9ByteCodeIlGenerator::loadFromCP(TR::DataType, int)+0x1352 [0x7ffb2789679c]
#9: function TR_J9ByteCodeIlGenerator::walker(TR::Block*)+0x790 [0x7ffb2787e0e6]
#10: function TR_J9ByteCodeIlGenerator::genILFromByteCodes()+0x595 [0x7ffb27869f77]
#11: function TR_J9ByteCodeIlGenerator::internalGenIL()+0x8d9 [0x7ffb278699b5]
#12: function TR_J9ByteCodeIlGenerator::genIL()+0x9c [0x7ffb27868e02]
#13: function OMR::ResolvedMethodSymbol::genIL(TR_FrontEnd*, TR::Compilation*, TR::SymbolReferenceTable*, TR::IlGenRequest&)+0x52e [0x7ffb27d60cce]
#14: function TR_J9InlinerPolicy::_tryToGenerateILForMethod(TR::ResolvedMethodSymbol*, TR::ResolvedMethodSymbol*, TR_CallTarget*)+0x32c [0x7ffb278b959a]
```

### PR DESCRIPTION
**Pull request by a7ehuo**
Remove `getIndex()` and `getIndexAt()` which have been replaced by `getOrCreateIndex()` and `getOrCreateIndexAt()`.

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Comment by a7ehuo** [comment]
This PR has dependency on eclipse/omr#5004. Should not be merged until eclipse/omr#5004 is promoted to `eclipse/openj9-omr` `openj9` branch.

**Comment by andrewcraik** [comment]
These two APIs have different meanings - getOrCreate can create an index which you may not always want to do which is why there is also a get. While the API isn't used widely I'm not sure why it needs to be expunged?

**Comment by a7ehuo** [comment]
The existing `getIndex()` could end up adding an entry to the known object table. `getIndex()` would be misleading. Same reason for replacing `getIndexAt()`.

https://github.com/eclipse/openj9/blob/ffece8e6c10a1b403c4bc8c93e32ca4fb7af9b98/runtime/compiler/env/J9KnownObjectTable.cpp#L105-L111

**Comment by mpirvu** [comment]
jenkins test sanity xlinuxjit jdk11

**Pull request merged**
