### PR TITLE
Stop using obsolete javac option -Xmodule: in tests

### LINKED ISSUE #10130: Tests compiling using javac with unsupported -Xmodule: option
On zOS, the functional tests are failing to compile, as they are using an unsupported option `-Xmodule:`. I'm not sure how all the other platforms are working.

I find 2 references to `-Xmodule:`.
https://github.com/eclipse/openj9/tree/master/test/functional/cmdLineTests/proxyFieldAccess/build.xml#L51
https://github.com/eclipse/openj9/tree/master/test/functional/Java8andUp/build.xml#L84

```
23:43:20  compile:
23:43:20       [echo] Ant version is Apache Ant(TM) version 1.9.9 compiled on February 2 2017
23:43:20       [echo] ============COMPILER SETTINGS============
23:43:20       [echo] ===fork:                         yes
23:43:20       [echo] ===executable:                   /home/jenkins/workspace/Test_openjdk11_ibm_sanity.functional_s390x_zos_Personal_testList_0/openjdkbinary/j2sdk-image/bin/javac
23:43:20       [echo] ===debug:                        on
23:43:20       [echo] ===destdir:                      /home/jenkins/workspace/Test_openjdk11_ibm_sanity.functional_s390x_zos_Personal_testList_0/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/proxyFieldAccess
23:43:20      [javac] Compiling 1 source file
23:43:21      [javac] JVMJ9VM082E Unable to switch to IFA processor - issue "extattr +a libj9ifa29.so"
23:43:21      [javac] error: invalid flag: -Xmodule:java.base
23:43:21      [javac] Usage: javac <options> <source files>
23:43:21      [javac] use --help for a list of possible options
```

### PR DESCRIPTION
**Pull request by pshipton**
Fixes #10130

### CODE REVIEW

**Comment by llxia** [comment]
jenkins test sanity plinux jdk8

**Comment by pshipton** [comment]
Seems it needs more work, just remove -Xmodule: doesn't work either.
```
11:41:48      [javac] /home/jenkins/workspace/Grinder/openjdk-tests/functional/cmdLineTests/proxyFieldAccess/src/java/util/$Proxy0.java:22: error: package exists in another module: java.base
11:41:48      [javac] package java.util;
11:41:48      [javac] ^
11:41:48      [javac] 1 error
```

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8,jdk11

**Comment by pshipton** [comment]
Confirmed the tests compile on zOS via view/Test_grinder/job/Grinder/8891.

**Comment by pshipton** [comment]
@smlambert if you are available to review/merge. This will get functionality tests running again on zOS.

**Comment by pshipton** [comment]
The test is running:
ok 61 - cmdLineTester_ProxyFieldAccess_SE80_0
ok 86 - cmdLineTester_ProxyFieldAccess_0

**Comment by pshipton** [comment]
Sigh, this broke Windows compiles. 
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_windows_Nightly_testList_0/45
```
02:28:23       [echo] Ant version is Apache Ant(TM) version 1.10.3 compiled on March 24 2018
02:28:23       [echo] ============COMPILER SETTINGS============
02:28:23       [echo] ===fork:                         yes
02:28:23       [echo] ===executable:                   C:/Users/****/workspace/Test_openjdk11_j9_sanity.functional_x86-64_windows_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/javac
02:28:23       [echo] ===debug:                        on
02:28:23       [echo] ===destdir:                      C:/Users/****/workspace/Test_openjdk11_j9_sanity.functional_x86-64_windows_Nightly_testList_0/openjdk-tests///..//jvmtest/functional/cmdLineTests/proxyFieldAccess
02:28:23      [javac] Compiling 4 source files
02:28:24      [javac] error: invalid flag: C:\Users\****\workspace\Test_openjdk11_j9_sanity.functional_x86-64_windows_Nightly_testList_0\openjdk-tests\functional\cmdLineTests\proxyFieldAccess\src
02:28:24      [javac] Usage: javac <options> <source files>
02:28:24      [javac] use --help for a list of possible options
```

**Pull request merged**
