### PR TITLE
Allow NODE param to be passed to container build

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Rename container build file with groovy extension. Allows for
  automatic syntax highlighting. Consistent with other Jenkins files.

[skip ci]
Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@jdekonin  for review.
Will need to update 
https://ci.eclipse.org/openj9/view/Build/job/Build-Jenkins-Agent-Container/
and
https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-Build-Jenkins-Agent-Container/
with the .groovy extension on the JenkinsFile.

**Comment by pshipton** [comment]
@AdamBrousseau are you ready for this to be merged?

**Comment by AdamBrousseau** [comment]
Yes, just need you to update the jobs as described once it's merged.

**Comment by pshipton** [comment]
@AdamBrousseau ok, I see. It is done.

**Pull request merged**
