### PR TITLE
Force VM exit if exception thrown while threads deadlocked

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Fixes https://github.com/eclipse/openj9/issues/3369

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
Not sure we should close #3369. Is there another issue to handle the native library problem?

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Comment by pdbain-ibm** [comment]
>  Is there another issue to handle the native library problem?

Yes: https://github.com/eclipse/openj9/issues/3292

**Comment by smlambert** [comment]
thanks!

**Pull request merged**
