### PR TITLE
Use getScalarField to set TEST_FLAG

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Was broken due to #8098

[skip ci]
Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins test sanity plinuxjit jdk8

**Comment by AdamBrousseau** [comment]
Jenkins test sanity plinuxjit jdk8

**Comment by AdamBrousseau** [comment]
Jenkins test sanity plinuxjit,plinux jdk8

**Comment by AdamBrousseau** [comment]
Jenkins test sanity plinuxjit,plinux jdk8

**Comment by AdamBrousseau** [comment]
@mpirvu I think this is working now.
https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK8_ppc64le_linux_jit/10/console
`00:42:28.405  TEST_FLAG:'JITAAS'`
https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK8_ppc64le_linux/1504/console
`00:40:26.453  TEST_FLAG:''`

**Comment by mpirvu** [comment]
I would appreciate a review from @vsebe on this one. My knowledge of groovy is nil. Thanks

**Comment by mpirvu** [comment]
Testing has passed, so this PR is good to be merged.

**Pull request merged**
