### PR TITLE
Enable optimizations with JProfiling

### PR DESCRIPTION
**Pull request by ncough**
This change enables various optimizations
that were disabled under JitProfiling due
to issues with the duplication it performed.

It also ensures JProfiling bodies are treated
as sampling bodies, that upgrade only through
the recompilation counter they insert.

### CODE REVIEW

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by andrewcraik** [comment]
So the only item here that needs conscious discussion is how we intend to handle/surface disable for profiling. There were the IfNotProfiling flags on the opt strategy (which make a lot of sense from seeing how a strategy could change) and there are disables in optimizations. This change nomralizes on the opt disable. This isn't wrong, it just makes it a bit harder to see which opts will disable when. In the new world where profiling is frequently on and opts don't have to limit themselves because of profiling I think this probably makes sense, but is something we should consciously decide. Opinions from @vijaysun-omr and @fjeremic would be good to hear on this particular point before this is merged.

**Comment by fjeremic** [comment]
> So the only item here that needs conscious discussion is how we intend to handle/surface disable for profiling. There were the IfNotProfiling flags on the opt strategy (which make a lot of sense from seeing how a strategy could change) and there are disables in optimizations. This change nomralizes on the opt disable. This isn't wrong, it just makes it a bit harder to see which opts will disable when. In the new world where profiling is frequently on and opts don't have to limit themselves because of profiling I think this probably makes sense, but is something we should consciously decide.

Thanks for the great summary @andrewcraik. I think losing the easy way to identify which optimizations may be disable under profiling is definitely a step backwards. We need some way to documenting this behavior. As a starter, could we as part of this PR at the very least add a comment in the optimization strategies if an optimization may be disabled due to profiling?

**Comment by ncough** [comment]
This change doesn't fully normalize control to either disables in optimizations or flags in the profiling strategy. It removes duplicate checks for certain optimizations as they aren't part of an optional strategy - they must be disabled under a profiling implementation due to how it functions. For example, `redundantAsyncCheckRemoval` can't run under JitProfiling as it will modify asyncchecks that the body duplication step relies on, where as it can under JProfiling.

There are still optimization passes that make use of the strategy flags to indicate the opt is undesirable under profiling, for example, due to the compile time overhead in `generalLoopUnroller `.

I'm happy to document which optimizations are disabled in certain implementations of profiling.

**Comment by ncough** [comment]
After consideration, an optimization flag for `IfNotJitProfiling` has been added, to express optimizations that are disabled due to JitProfiling's limitations. This flag is sufficient to express all optimizations enabled under JProfiling by this change.

**Comment by ncough** [comment]
Depends on OMR PR: https://github.com/eclipse/omr/pull/2149

**Comment by andrewcraik** [comment]
Jenkins test sanity depends eclipse/omr#2149

**Comment by andrewcraik** [comment]
Jenkins test sanity depends eclipse/omr#2149

**Comment by andrewcraik** [comment]
dependent change has merged - change LGTM and has passed testing. will merge now.

**Pull request merged**
