### PR TITLE
JITServer Compilation Fixes for Power

### PR DESCRIPTION
**Pull request by dchopra001**
Signed-off-by: Dhruv Chopra <Dhruv.C.Chopra@ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Jenkins test sanity plinux,aix jdk8

**Comment by fjeremic** [comment]
@dchopra001 please see compilation failures. Sounds like protobufs are missing on these machines.

**Comment by mpirvu** [comment]
#7099 is being worked on

**Comment by fjeremic** [comment]
@dchopra001 let us know when this is ready for review.

**Comment by dchopra001** [comment]
OOPS! Sorry I was using this branch as my dev branch. Didn't realize there was a PR open against it. I'll fix this.

**Comment by dchopra001** [comment]
@mpirvu @fjeremic This one is good for another round of reviews+merge.

**Comment by fjeremic** [comment]
Jenkins test compile all jdk8

**Comment by dchopra001** [comment]
@fjeremic protobufs is still not available on the power machines, so the builds will still fail.

**Comment by fjeremic** [comment]
> @fjeremic protobufs is still not available on the power machines, so the builds will still fail.

Ok, so this is going into the jitaas branch so it won't affect master then.

**Pull request merged**
