### PR TITLE
Check preferred size on J9::SystemSegmentProvider init

### PR DESCRIPTION
**Pull request by dsouzai**
Partially addresses https://github.com/eclipse/openj9/issues/434 .

### CODE REVIEW

**Comment by dsouzai** [comment]
@mpirvu @fjeremic for your review.

**Comment by fjeremic** [comment]
@dsouzai what else is left to fix #434?

**Comment by dsouzai** [comment]
Because it's still possible for `J9::SystemSegmentProvider`'s constructor to throw for a different reason (eg due to some problem while in STL code), we're probably going to have to wrap the call to `compile` in a try/catch. I have to go through the code and see what kind of clean up we may have to do in that case. There are two places where `compile` is called; one is related to Compilation Threads, the other is related to compiling on Application Threads. As such, it might not be trivial and might even require some code refactoring work.

As for this PR, I'm running some tests, once they all pass I'll remove the WIP.

**Comment by dsouzai** [comment]
@mpirvu I've finished with my tests, PR should be ok to merge.

**Pull request merged**
