### PR TITLE
Fix JITServer java_lang_invoke_PermuteHandle_permuteArgs

### PR DESCRIPTION
**Pull request by harryyu1994**
Reflect new changes from JIT in JITServer.
Original JIT change can be found here
https://github.com/eclipse/openj9/pull/6305

Issue: #7674

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@mpirvu could you help review this one?

**Comment by harryyu1994** [comment]
@mpirvu Hi Marius, could you help review this one?

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Java11 showed the known `cmdLineTester_gcsuballoctests_0` failure, while Java8 had infra issues.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
Only the known `cmdLineTester_gcsuballoctests_0` test has failed hence merging.

**Comment by mpirvu** [comment]
@harryyu1994 Please port this to master branch

**Pull request merged**
