### PR TITLE
Remove unused field ThreadGroup.memorySpace

### PR DESCRIPTION
**Pull request by keithc-ca**

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile zlinux jdk11

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
There is a merge conflict now.

**Comment by keithc-ca** [comment]
Merge conflict resolved (and rebased).

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
The change is the same as was previously tested, I'm not going to re-test.

**Pull request merged**
