### PR TITLE
Enable --enable-jitserver for all xlinux and plinux

### PR DESCRIPTION
**Pull request by pshipton**
Adds --enable-jitserver for jdk14+

### CODE REVIEW

**Comment by mpirvu** [comment]
jenkins test sanity,extended,sanity.system,extended.system xlinux jdk13,jdknext

**Comment by pshipton** [comment]
The jdknext system test failures are due to the tests not supporting jdk15 yet.

**Comment by pshipton** [comment]
Set as WIP as once the testing is completed I'm going to change the commit similarly to https://github.com/eclipse/openj9/pull/8196

**Comment by pshipton** [comment]
Rebased and updated to remove the `=yes`.

Previous PR testing was https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-OpenJ9/2348/, the only failures were the expected jdknext (jdk15) system test failures.

**Comment by pshipton** [comment]
The jdk11 large heap build is failing to compile due to enabling JITserver, marked this WIP for now.

**Comment by pshipton** [comment]
The jdk11 large heap build problem was a machine issue.
I'll keep this WIP for now, I'll fix up this PR after #8098 is merged.

**Comment by AdamBrousseau** [comment]
Now that all the xlinux specs have `--enable-jitserver` the only difference between regular specs and JITServer specs is the `TEST_FLAG=JITAAS`. I assume this is desired behaviour for now as to allow for both regular testing and JITServer testing to be run but I wanted to make sure I'm on the same page and there is awareness.

**Comment by mpirvu** [comment]
Yes, we want to allow for both regular and JITServer testing. For instance, regular testing should pass on all JDK levels, whereas with JITServer we only support JDK8/11 at the moment.

**Comment by pshipton** [comment]
Updated the commit and removed WIP.

**Comment by mpirvu** [comment]
This PR fell off my radar.
@pshipton Is the right testing incantation: "jenkins test sanity,extended,sanity.system,extended.system xlinux,plinux jdk14,jdknext" or will jdknext tests fail? Thanks

**Comment by pshipton** [comment]
jdknext is fine.

jenkins test sanity,extended,sanity.system,extended.system,sanity.openjdk xlinux,plinux jdk14,jdknext

**Comment by pshipton** [comment]
Not sure if you also want to check the XL builds since the change will affect them as well.

**Comment by mpirvu** [comment]
Sanity for jdknext on plinux and xlinux failed.
From the console output on plinux
```
12:20:28  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: Native library loaded. Expected: JNI_OnUnload not invoked
12:20:28  REASON: User specified action: run main/othervm/native -Xcheck:jni Main 
12:20:28  TIME:   0.805 seconds
12:20:28  messages:
12:20:28  command: main -Xcheck:jni Main
12:20:28  reason: User specified action: run main/othervm/native -Xcheck:jni Main 
12:20:28  Mode: othervm [/othervm specified, test or library overrides a system module]
12:20:28  Additional options from @modules: --add-modules java.base --add-exports java.base/jdk.internal.loader=ALL-UNNAMED
12:20:28  elapsed time (seconds): 0.805
12:20:28  configuration:
12:20:28  Boot Layer
12:20:28    add modules: java.base                     
12:20:28    add exports: java.base/jdk.internal.loader ALL-UNNAMED
12:20:28    patch:       java.base                     /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_ppc64le_linux_Personal/openjdk-tests/TKG/test_output_15863620309951/jdk_lang_j9_0/work/classes/1/jdk/internal/loader/NativeLibraries/Main.d/patches/java.base
12:20:28  
12:20:28  STDOUT:
12:20:28  STDERR:
12:20:28  JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
12:20:28  java.lang.AssertionError: Native library loaded.  Expected: JNI_OnUnload not invoked
12:20:28  	at java.base/jdk.internal.loader.NativeLibrariesTest.assertTrue(NativeLibrariesTest.java:132)
12:20:28  	at java.base/jdk.internal.loader.NativeLibrariesTest.runTest(NativeLibrariesTest.java:69)
12:20:28  	at Main.main(Main.java:46)
12:20:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:20:28  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:20:28  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:20:28  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
12:20:28  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
12:20:28  	at java.base/java.lang.Thread.run(Thread.java:835)
12:20:28  
12:20:28  JavaTest Message: Test threw exception: java.lang.AssertionError: Native library loaded.  Expected: JNI_OnUnload not invoked
12:20:28  JavaTest Message: shutting down test
12:20:28  
12:20:28  STATUS:Failed.`main' threw exception: java.lang.AssertionError: Native library loaded. Expected: JNI_OnUnload not invoked
..
```

On xlinux we have the same error as above , plus this one:
```
13:19:29  java.lang.RuntimeException: Cipher Cipher.ChaCha20-Poly1305, mode: decryption, algorithm from: SunJCE, in: 1024, expOut: 6128, actual: 1008
13:19:29  	at OutputSizeTest.testOutLen(OutputSizeTest.java:170)
13:19:29  	at OutputSizeTest.testCC20P1305GetOutSize(OutputSizeTest.java:118)
13:19:29  	at OutputSizeTest.main(OutputSizeTest.java:48)
13:19:29  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:19:29  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:19:29  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:19:29  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
13:19:29  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
13:19:29  	at java.base/java.lang.Thread.run(Thread.java:835)
13:19:29  
13:19:29  JavaTest Message: Test threw exception: java.lang.RuntimeException
13:19:29  JavaTest Message: shutting down test
13:19:29  
13:19:29  
13:19:29  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Cipher Cipher.ChaCha20-Poly1305, mode: decryption, algorithm from: SunJCE, in: 1024, expOut: 6128, actual: 1008
13:19:29  --------------------------------------------------
13:19:44  Test results: passed: 91; failed: 1
13:19:55  Report written to /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_x86-64_linux_Personal/jvmtest/openjdk/report/html/report.html
13:19:55  Results written to /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_x86-64_linux_Personal/openjdk-tests/TKG/test_output_1586362760561/jdk11_tier1_cipher_0/work
13:19:55  Error: Some tests failed or other problems occurred.
13:19:55  
13:19:55  jdk11_tier1_cipher_0_FAILED
```

**Comment by pshipton** [comment]
Those are expected failures, you can compare against the internal nightly build results.

**Pull request merged**
