### PR TITLE
Create known object for MethodHandle constant

### PR DESCRIPTION
**Pull request by liqunl**
Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@andrewcraik May I ask for your review?

**Review by andrewcraik — APPROVED** [review]

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk15

**Comment by liqunl** [comment]
The jdk15 ppc64_aix and jdk15 ppc64le_linux_xl builds failed with the following error, not related to the change
```
5:28:04  java.lang.VerifyError: JVMVRFY012 stack shape inconsistent; class=org/apache/tools/ant/helper/ProjectHelper2$ProjectHandler, method=onStartElement(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/xml/sax/Attributes;Lorg/apache/tools/ant/helper/AntXMLContext;)V, pc=550
```

**Comment by pshipton** [comment]
The VerifyError failures were caused by https://github.com/eclipse/openj9/pull/11089, which was subsequently reverted.

**Comment by andrewcraik** [comment]
Change looks good - only failures look to be known issues as previously linked

**Pull request merged**
