### PR TITLE
AArch64: Add files for building AArch64 JIT

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds files for building AArch64 JIT.

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
With this PR the toolchain and the compiler flags are set for aarch64 Linux JIT cross build, although you cannot build the JIT shared library yet.

**Comment by 0xdaryl** [comment]
Jenkins tests are needed though because the changes touch a common file.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Comment by knn-k** [comment]
Updated `runtime/compiler/build/files/host/aarch64.mk`, adding `CodeSync.cpp` to its `JIT_PRODUCT_BACKEND_SOURCES`.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Pull request merged**
