### PR TITLE
Propagate arg info from caller

### PR DESCRIPTION
**Pull request by liqunl**
Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
Depends on https://github.com/eclipse/omr/pull/4566

**Comment by andrewcraik** [comment]
Jenkins test sanity jdk8,jdk11 all depends eclipse/omr#4566

**Comment by andrewcraik** [comment]
Is there any performance of functional concern if the OMR change is merged and promoted before this is merged? ie does this require a coordinated delivery?

**Comment by andrewcraik** [comment]
Functionally the code looks good. I do note that there is no trace in any of these additions - it seems like there should be some given the impact this code can have on inlining?

**Comment by andrewcraik** [comment]
@liqunl was there any functional change in your last force push? Should I continue with testing and could you reply to the questions above?

**Comment by liqunl** [comment]
> Is there any performance of functional concern if the OMR change is merged and promoted before this is merged? ie does this require a coordinated delivery?

Yes, it requires a coordinated delivery. There will be performance regression if the OMR change is promoted without this change.

**Comment by liqunl** [comment]
> @liqunl was there any functional change in your last force push? Should I continue with testing and could you reply to the questions above?

There is no functional change in my last push. The change is comment only.

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8 depends eclipse/omr#4566

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8 depends eclipse/omr#4566

**Comment by andrewcraik** [comment]
Jenkins test sanity all jdk8 depends eclipse/omr#4566

**Comment by andrewcraik** [comment]
OMR change has merged - merging

**Pull request merged**
