### PR TITLE
Recognize a field by its declaring class

### PR DESCRIPTION
**Pull request by liqunl**
Currently we recognize a field by comparing its reference class' name to
the declaring class' name. The referenece class can be the declaring
class' subclass and the compare will fail. Fix it.

#4837 

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@andrewcraik Could you review?

**Comment by andrewcraik** [comment]
@liqunl Is there any risk of fields being recognized more widely and resulting in bugs by us doing things we should not have done, but weren't doing because of the limited scope?

**Comment by liqunl** [comment]
@andrewcraik I think no. If there is such bug, we may hit it even without this change. Due to the shadow aliasing, a field accessed from the subclass can use the symref created for field access in the base class. So curretnly, `subclass.field` can still be treated as a recognized field.

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Comment by andrewcraik** [comment]
@liqunl it isn't so much the aliasing - more structurally would we fold in more cases and some of those be wrong. I guess the argument is that the field is foldable and so if we do that naming the class directly or a derrived class it doesn't really matter it should still hold.

**Comment by liqunl** [comment]
> 
> 
> @liqunl it isn't so much the aliasing - more structurally would we fold in more cases and some of those be wrong. I guess the argument is that the field is foldable and so if we do that naming the class directly or a derrived class it doesn't really matter it should still hold.

Agree

**Pull request merged**
