### PR TITLE
Remove code that only applies to unsupported versions

### PR DESCRIPTION
**Pull request by keithc-ca**
* String.java - only for Java 12
* Thread.java - only for Java 13

### CODE REVIEW

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9/blob/74c3cc1c2ef1ee14c28487fadc2be0586d60a400/jcl/src/java.base/share/classes/java/lang/Thread.java#L557-#L564 and the closing brace should be removed as well.

**Review by DanHeidinga — APPROVED** [review]
lgtm

**Comment by keithc-ca** [comment]
Updated as [suggested](https://github.com/eclipse/openj9/pull/10804#issuecomment-704590483) by @pshipton.

**Comment by DanHeidinga** [comment]
@keithc-ca I assume you'll add Peter's suggested change to this as well.  Once that's done, I'll launch builds and we can get this merged

**Review by pshipton — APPROVED** [review]

**Comment by DanHeidinga** [comment]
Jenkins test sanity zlinux jdk11,jdk15

**Pull request merged**
