### PR TITLE
Array Translate Improvement on X86

### PR DESCRIPTION
**Pull request by 0dvictor**
Optimized assembly sequences of array translate helpers.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
Change looks good - any comment on performance implications? Will need for the CI build to complete before I can look at merging.

**Comment by 0dvictor** [comment]
This PR improves decoding ASCII and ISO8859-1 strings. On my measurement, performance of ASCII decoding improved 7% while ISO8859-1 decoding improved 2%.

**Comment by pshipton** [comment]
Note the travis-ci build doesn't run any testing yet, except -version.

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by andrewcraik** [comment]
@AdamBrousseau any ideas on the sanity failure above on Linux 390? seems infra or something?

**Comment by AdamBrousseau** [comment]
First time I've seen this error externally
```
00:00:52.923 + make all
00:00:53.297 Cannot contact  ub16-390-2: java.io.IOException: Remote call on  ub16-390-2 failed
00:01:17.127 make[1]: *** No rule to make target '/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-linux_390-64_cmprssptrs/build/linux-s390x-normal-server-release/spec.gmk'.  Stop.
00:01:17.127 make: *** No rule to make target 'all'.  Stop.
```
Jenkins test sanity zlinux

**Comment by AdamBrousseau** [comment]
To be clear...
`Cannot contact  ub16-390-2: java.io.IOException: Remote call on  ub16-390-2 failed`
is not new, and doesn't seem to be a problem. The make failure is the real failure

**Comment by andrewcraik** [comment]
Testing says this is clean so I will merge it now

**Pull request merged**
