### PR TITLE
Add --illegal-access=permit in JCL tests

### PR DESCRIPTION
**Pull request by LongyuZhang**
- add --illegal-access=permit in JCL_Test and JCL_Test_none_SCC
- Issue: https://github.com/eclipse/openj9/issues/11419

[skip ci]
Signed-off-by: Longyu Zhang <longyu.zhang@ibm.com>

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test links:
xlinux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5359/
aix:https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5330/
plinux:https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5331/
zlinux:https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5333/
mac:https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5334/

**Comment by fjeremic** [comment]
Could we fix the commit title to be consistent with the rest of the contributions?

https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md#commit-guidelines

> The first line describes the change made. It is written in the imperative mood, and should say what happens when the patch is applied. Keep it short and simple. The first line should be less than 70 characters, where reasonable, and **should be written in sentence case** preferably not ending in a period. Leave a blank line between the first line and the message body.

**Comment by LongyuZhang** [comment]
> Could we fix the commit title to be consistent with the rest of the contributions?
> 
> https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md#commit-guidelines
> 
> > The first line describes the change made. It is written in the imperative mood, and should say what happens when the patch is applied. Keep it short and simple. The first line should be less than 70 characters, where reasonable, and **should be written in sentence case** preferably not ending in a period. Leave a blank line between the first line and the message body.

The commit has been updated. Thanks.

**Comment by llxia** [comment]
jenkins test sanity zlinux jdknext

**Review by llxia — APPROVED** [review]
LGTM

**Pull request merged**
