### PR TITLE
Convert short SHAs in build description to hyperlinks

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- OpenJDK, OpenJ9, OMR and Vendor Tests

[skip ci]
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@vsebe for review
fyi @amicic 
Jenkins compile plinux jdk11

**Comment by AdamBrousseau** [comment]
I think the UNSTABLE is related to Github issues
https://www.githubstatus.com/incidents/xp2qc958g4wt

**Comment by AdamBrousseau** [comment]
@vsebe for review
Jenkins compile plinux jdk11

**Comment by jdekonin** [comment]
For PR builds this only shows the sha for the `Pipeline_Build_Test_<release>_<arch>_<os>` pipeline, I cannot tell if it was detailed in `PullRequest-OpenJ9/2822` as well.

Jenkins compile plinux jdk11

**Comment by jdekonin** [comment]
It is detailed in `PullRequest-OpenJ9`, the history on the pipeline for the previous build was already gone so I couldn't verify.

Was this PR created to fix a specific issue raised?

**Comment by AdamBrousseau** [comment]
>Was this PR created to fix a specific issue raised?

No.

**Comment by amicic** [comment]
I'm not competent to review this, so I'll leave it up to you. But, THANKS!

**Pull request merged**
