### PR TITLE
Javadoc updates for DTFJ & management extensions

### PR DESCRIPTION
**Pull request by keithc-ca**
Javadoc updates for DTFJ & management extensions

* add javadoc to module-info.java files
* add missing package-info.java files
* apply accessibility fix (better colour contrast)
* remove redundant tooling for Java 9 javadoc generation
* use unix line-ends for xml files

### CODE REVIEW

**Comment by genie-openj9** [comment]
Can one of the admins verify this patch?

**Comment by genie-openj9** [comment]
Can one of the admins verify this patch?

**Comment by genie-openj9** [comment]
Can one of the admins verify this patch?

**Comment by pshipton** [comment]
Caused: Exception in thread "main" java/lang/reflect/LayerInstantiationException: Package share.classes in both module com.ibm.dtfj and module com.ibm.management

**Pull request merged**
