### PR TITLE
Code cleanup related to instanceof/checkcast on X86

### PR DESCRIPTION
**Pull request by 0dvictor**
The old implementation of instanceof, checkcast, and j/l/Class.isAssignableFrom
have been deprecated, removing them.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by 0dvictor** [comment]
This is a follow-up of #2361, #2494, #2515, and #2551.

**Comment by andrewcraik** [comment]
Jenkins tests sanity xlinux,win

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win

**Comment by andrewcraik** [comment]
Jenkins test sanity win32

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux32

**Comment by andrewcraik** [comment]
@0dvictor seems there is a merge conflict that will need to be addressed.

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win32

**Pull request merged**
