### PR TITLE
update getDependencies.pl logic

### PR DESCRIPTION
**Pull request by llxia**
- add shaurl and shaalg options in hash
- if sha1 is not provided in the hash, the program will try to get sha
info from shaurl
- shaalg is optional and default value is sha1. sha is calculated based
on shaalg

[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
jenkins test sanity all jdk8

**Comment by llxia** [comment]
Output from Grinder:
```
00:04:15.407  /home/jenkins/workspace/Test-Grinder/openjdk-tests/TestConfig/../TestConfig/lib/jcommander.jar exists with correct hash, not downloading
00:04:15.407  --> sha1 is not provided for asmtools.jar. Download sha file content from https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/lastSuccessfulBuild/artifact/asmtools.jar.sha256sum.txt
00:04:15.407  -->sha for asmtools.jar: 1bce60c4cb101524599b2940b53413d894836c5e08466c0c9c4fb91138aa90a7
```
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/470/console

**Comment by llxia** [comment]
Change it to WIP. 
The current code only checks sha file content, which creates a dependency on https://ci.adoptopenjdk.net at the runtime. We need to store the sha file on disk, so the stage job stores the sha file as well.

**Comment by llxia** [comment]
Changeset is updated to store sha file on disk, so that the stage job can store all files (including sha file). As mentioned above, this is needed for not creating dependency on https://ci.adoptopenjdk.net at the runtime for auto builds.

The program will check for local sha file first. If it does not exist, download it from `shaurl` and store the file locally. The program will then parse the sha file to get the expected sha value.
If the depend jar is newly downloaded due to mismatching sha value, the sha file will also be downloaded from `shaurl`.

**Comment by llxia** [comment]
```
00:02:01.532  downloading https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/lastSuccessfulBuild/artifact/asmtools.jar.sha256sum.txt
00:02:02.141  --> file downloaded to /home/jenkins/jenkins-agent/workspace/Test-Grinder/openjdk-tests/TestConfig/../TestConfig/lib/asmtools.jar.sha256sum.txt
```
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/472/console

**Comment by llxia** [comment]
jenkins test sanity,extended all jdk8

**Comment by llxia** [comment]
`threadMXBeanTestSuite1_5 ` failure in https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Personal/24/tapResults/ is the same issue as https://github.com/eclipse/openj9/issues/6498

**Comment by llxia** [comment]
jenkins test sanity,extended all jdk11

**Comment by llxia** [comment]
Ready for review

**Comment by sophia-guo** [comment]
Could we do the same for other jars sha check? Looks like all other jars has the same name format and same sha name format. 

Say asm-7.0 https://repository.ow2.org/nexus/content/repositories/releases/org/ow2/asm/asm/7.0-beta/
asm-7.0-beta.jar
asm-7.0-beta.jar.sha1

or asm jar http://central.maven.org/maven2/org/ow2/asm/asm-all/6.0_BETA/
asm-all-6.0_BETA.jar
asm-all-6.0_BETA.jar.sha1 

So we don't need to hard code the sha1 for each jar?

**Comment by llxia** [comment]
> Could we do the same for other jars sha check?

yes, we can. We can deliver this PR first and make the enhancement for the rest of jars.

**Comment by smlambert** [comment]
PR testing already done on this one, just waiting for a couple of Grinders at other servers then will merge:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1852

**Pull request merged**
