### PR TITLE
Remove unnecessary debug print

### PR DESCRIPTION
**Pull request by sophia-guo**
[ci skip]

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/954/console

FYI @hangshao0 

@llxia please take a review, thanks.

**Comment by hangshao0** [comment]
These lines are incorrect:

https://github.com/eclipse/openj9/blob/master/test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java#L261
https://github.com/eclipse/openj9/blob/master/test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java#L312

Message is getOSsemid() but the value printed out is getLastDetach().

**Comment by hangshao0** [comment]
This line should be removed:
https://github.com/eclipse/openj9/blob/master/test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java#L468

Might be worth adding a line to print out cacheInfo.getLastDetach().getTime() around these lines:

https://github.com/eclipse/openj9/blob/master/test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java#L264
https://github.com/eclipse/openj9/blob/master/test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java#L315
https://github.com/eclipse/openj9/blob/master/test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java#L361
https://github.com/eclipse/openj9/blob/master/test/functional/CacheManagement/src/tests/sharedclasses/options/TestSharedCacheJavaAPI.java#L414

**Comment by pshipton** [comment]
jenkins test extended zlinux jdk8

**Pull request merged**
