### PR TITLE
Optimize Unsafe call in field getter/setter handle

### PR DESCRIPTION
**Pull request by liqunl**
Reduce Unsafe call in field getter/setter handle to a read/store.

#4837 

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@andrewcraik May I ask for your review?

**Comment by andrewcraik** [comment]
Jenkins test sanity xliunx,win,plinux jdk8,jdk11

**Comment by liqunl** [comment]
@andrewcraik There is a typo in platform `xliunx`, it should be `xlinux`, could you restart the test?

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Pull request merged**
