### PR TITLE
Update README.md file with getdependency target information

### PR DESCRIPTION
**Pull request by llxia**
Update README.md file with getdependency target information

Fixes: #196

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
Reviewer: @renfeiw

**Comment by DanHeidinga** [comment]
@llxia for changes to documentation, please add `[skip ci]` to the commit messages body to avoid triggering the travis.ci build.

I'm hesitating to mention this as it's a bit of a nitpick, but please use more descriptive commit messages in the future.  It makes it easier to figure out *why* something changed from looking at the short form git log (i.e.: git log --oneline).

**Comment by llxia** [comment]
@DanHeidinga I remembered [skip ci] after I created pull request. But it was too late. :(

**Comment by pshipton** [comment]
> I remembered [skip ci] after I created pull request. But it was too late. :(

It depends what you mean by too late. Once the Pull Request is created, a Travis build gets added to the queue. Typically there is a backlog and the build doesn't start right away. If you push a new commit, it removes the old Travis build and queues a new one, or in the case of adding [skip ci], doesn't add a new build into the queue.

**Pull request merged**
