### PR TITLE
Extract concurrent marking delegate from CLI

### PR DESCRIPTION
**Pull request by ktbriggs**
NOTE: This PR depends on OMR PR https://github.com/eclipse/omr/pull/1578. Please do not merge this PR until the OMR PR has been accepted and merged.

Extract concurrent collector marking delegate 
(MM_ConcurrentMarkingDelegate)
from deprecated collector language interface 
(MM_CollectorLanguageInterface*).

Structures and methods extracted:
(MM_CollectorLanguageInterface -> MM_ConcurrentGC)
```
_concurrentStats -> _stats
```
(MM_CollectorLanguageInterface -> MM_ConcurrentMarkingDelegate)
```
concurrentGC_processItem()
 -> processItem()
concurrentGC_createSafepointCallback()
 -> createSafepointCallback()
concurrentGC_getProtectedSignalHandler()
 -> getProtectedSignalHandler()
concurrentGC_concurrentInitializationComplete()
 -> concurrentInitializationComplete()
concurrentGC_forceConcurrentKickoff()
 -> *canForceConcurrentKickoff()*
concurrentGC_getNextTracingMode()
 -> getNextTracingMode()
concurrentGC_collectRoots()
 -> collectRoots()
concurrentGC_signalThreadsToTraceStacks()
 -> signalThreadsToTraceStacks()
concurrentGC_signalThreadsToDirtyCards()
 -> signalThreadsToDirtyCards()
concurrentGC_signalThreadsToStopDirtyingCards()
 -> signalThreadsToStopDirtyingCards()
concurrentGC_kickoffCardCleaning()
 -> *cardCleaningStarted()*
concurrentGC_flushRegionReferenceLists()
 -> *abortCollection()*
concurrentGC_flushThreadReferenceBuffer()
 -> *flushThreadRoots()*
concurrentGC_isThreadReferenceBufferEmpty()
 -> *removed* (usage replaced with !flushThreadRoots())
concurrentGC_startConcurrentScanning()
 -> startConcurrentScanning()
concurrentGC_concurrentScanningStarted()
 -> concurrentScanningStarted()
concurrentGC_isConcurrentScanningComplete()
 -> isConcurrentScanningComplete()
concurrentGC_reportConcurrentScanningMode()
 -> reportConcurrentScanningMode()
concurrentGC_scanThread()
 -> *scanThreadRoots()*
```

Other changes: normalize MM_EnvironmentBase use in concurrent collector
(MM_ConcurrentGC) to eliminate spurious casting to
MM_EnvironmentStandard (MM_EnvironmentStandard extensions to 
MM_EnvironmentBase are not used by concurrent collector in mark/sweep 
or generational configurations); eliminate MM_CollectorLanguageInterface
parameter from constructors in MM_Collector and subclasses.

Tested on rhel6x64vm10 256/384M 10x optavgpause, gencon SPECjbb2005. No
significant differences between base and head in verbose GC log ouputs. 

OMR Issue #1577
Signed-off-by: Kim Briggs <briggs@ca.ibm.com>

### CODE REVIEW

**Comment by ktbriggs** [comment]
@j9build openj9 freestyle depends ktbriggs/omr/concurrent-mark-delegate

**Comment by ktbriggs** [comment]
Thanks, @DanHeidinga. If I understand correctly, this PR must be built with

```
Jenkins test sanity depends eclipse/omr#1578
```

But requires an openj9 committer to kick off the build. @charliegracie | @DanHeidinga can you please start this build so I can remove WIP for submission.

**Comment by DanHeidinga** [comment]
The usual process here is that the committer will kick the build after they've reviewed the changes.  We're limiting the builds due to limited build resources.

@dmitripivkine can you take a look at this?

**Comment by dmitripivkine** [comment]
Jenkins test sanity depends eclipse/omr#1578

**Comment by ktbriggs** [comment]
@charliegracie The Travis build (for xLinux) failed because the freemarker tarball that it downloaded was corrupt or incomplete. I think all this needs is for the Travis build to be restarted. Are you able to do that (Dmitri, a committer, cannot)?

If not, let me know and I will rebase and push yet again and ask Dmitri to rerun the Jenkins test sanity... builds for p and z, and let Travis try x again. I'm trying to conserve build resources here.

**Comment by charliegracie** [comment]
I restarted it.  All committers can restart jobs.  

image

**Comment by ktbriggs** [comment]
@j9build openj9 freestyle depends briggs/omr/concurrent-mark-delegate

**Comment by ktbriggs** [comment]
Travis build is expected to fail owing to dependent omr pull request. Please see build result (where?) for `@j9build openj9 freestyle depends briggs/omr/concurrent-mark-delegate` for integrated build that includes dependent omr changes.

**Comment by ktbriggs** [comment]
@dmitripivkine you will need to launch dependent builds to pick up the requisite OMR changes: 
`Jenkins test sanity depends eclipse/omr#123`.

**Comment by dmitripivkine** [comment]
Jenkins test sanity depends eclipse/omr#123

**Comment by dmitripivkine** [comment]
Jenkins test sanity depends eclipse/omr#1578

**Comment by charliegracie** [comment]
Jenkins test sanity depends eclipse/omr#1578

**Pull request merged**
