### PR TITLE
Changed Cuda 7.5 to Cuda 9.0 for CentOS 6

### PR DESCRIPTION
**Pull request by JennyChenyj**
Signed-off-by: Jenny Chen <Jenny.Chen@ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
I'd like to see an explanation included for this change. `runtimes/infrastructure#2430` is not visible here.

**Comment by JennyChenyj** [comment]
> I'd like to see an explanation included for this change. `runtimes/infrastructure#2430` is not visible here.

Thanks for reminding me! I will take that issue number off. Sorry I am not quite sure about this. @AdamBrousseau

**Comment by AdamBrousseau** [comment]
jenkins build docker x86 centos6.9

**Comment by AdamBrousseau** [comment]
Adopt playbooks use Cuda 9.0. I believe this matches the plan for OpenJ9 support. I don't see an OpenJ9 issue. Maybe @keithc-ca can comment.

**Comment by pshipton** [comment]
I agree with the change, I just didn't like having a link to a non-accessible link as the explanation for it. I did open https://github.com/eclipse/openj9/issues/7242 yesterday.

**Comment by keithc-ca** [comment]
Apparently we need to adjust the URL for ant: http://www.us.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.tar.gz is not (currently?) available.

**Comment by AdamBrousseau** [comment]
`https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.zip`

**Comment by JennyChenyj** [comment]
> `https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.zip`

I fixed the url. Thanks!

**Comment by AdamBrousseau** [comment]
jenkins build docker x86 centos6.9

**Comment by AdamBrousseau** [comment]
The new link is a zip not a tar. You will have to change the followup commands.

**Comment by AdamBrousseau** [comment]
jenkins build docker x86 centos6.9

**Pull request merged**
