### PR TITLE
Add pre RA peephole phase to Z code generation

### PR DESCRIPTION
**Pull request by dhong44**
Add peephole phase before register allocation to Z codegen.

Signed-off-by: Daniel Hong <daniel.hong@live.com>

### CODE REVIEW

**Comment by dhong44** [comment]
@fjeremic

**Comment by dhong44** [comment]
Depends https://github.com/eclipse/omr/pull/2829

**Comment by fjeremic** [comment]
Jenkins test sanity zlinux JDK8 depends eclipse/omr#2829

**Comment by fjeremic** [comment]
Merging this as the OMR-Acceptance build will fail without it.

**Pull request merged**
