### PR TITLE
Move J9 specific changes to S390J9CallSnippet

### PR DESCRIPTION
**Pull request by r30shah**
This commit contains changes to move J9 specific part of code from S390CallSnippet to S390J9CallSnippet.
In addition to those changes, it also contains changes to refactor PICBuilder for Static and Special Direct calls.

Signed-off-by: Rahil Shah <rahil@ca.ibm.com>

### CODE REVIEW

**Comment by r30shah** [comment]
@fjeremic  Can I please get a review on this changes?  Apart from moving J9 specific changes from OMR I have refactored and cleaned up the PIC Builder for Static/Special direct call (taking a reference from X86 which only contains three glue code function related to such calls - https://github.com/eclipse/openj9/blob/56b263b768417119ed12dec405cc2e5803962b5f/runtime/compiler/x/codegen/CallSnippet.cpp#L782-L1015)

**Comment by r30shah** [comment]
Depends on https://github.com/eclipse/omr/pull/5723

**Comment by r30shah** [comment]
@fjeremic  With https://github.com/eclipse/omr/pull/5723 merged, this one should be merged soon as OMR change removes the J9 specific code which is implemented in this PR (I think omr acceptance will fail without this change). I think this one needs your review first before merging.

**Comment by pshipton** [comment]
@fjeremic what should be done in order to not break builds is a full OMR acceptance PR build like follows. Then manually push the tested OMR SHA to the openj9 branch and merge this PR in quick succession.

test sanity all jdk8, jdk11 depends eclipse/omr#master

The Thursday 5am build will test all platforms, so assuming it all passes except for zlinux, and if nothing new has been merged to OMR since that build, the following should be sufficient.

test sanity zlinux,zlinuxxl jdk8,jdk11 depends eclipse/omr#master

**Comment by fjeremic** [comment]
Jenkins test sanity all jdk8, jdk11 depends eclipse/omr#master

**Comment by fjeremic** [comment]
Right sorry, I was going through my assigned PRs and totally missed that I merged one without checking for OpenJ9 dependency. This should be good to go as long as tests pass.

**Review by fjeremic — APPROVED** [review]

**Pull request merged**
