### PR TITLE
Remove unused JITServer message types and associated dead code

### PR DESCRIPTION
**Pull request by AlexeyKhrabrov**
This PR removes JITServer message types that are currently not used, i.e. never sent from the server to the client, and removes the dead code that handles them on the client.

It also removes the comments with message type numbers in `MessageTypes.hpp`, and adds message type names to all the logging and diagnostic messages that used to only include message type numbers. The comments with numbers do not have much value anymore, and keeping them consistent and up to date has only been an unnecessary maintenance burden, especially in cases when multiple outstanding pull requests added or removed message types.

### CODE REVIEW

**Comment by AlexeyKhrabrov** [comment]
@mpirvu Can I please get a review for this cleanup PR? Thanks.

**Review by mpirvu — COMMENTED** [review]
LGTM. To prevent future errors from inserting a new message type without a name for it, I would like a static assert that verifies the number of entries in `messageNames` is the same as the number of message types. Thus we probably need change 
`static const char *messageNames[MessageType_ARRAYSIZE] =`
into
`static const char *messageNames[] =`
and add a 
`static_assert(sizeof(messageNames) == MessageType_MAXTYPE*sizeof(messageNames[0]), "Possibly missing a messageName");`

**Comment by AlexeyKhrabrov** [comment]
Added the static assert (actually moved an existing one from `CommunicationStream.hpp`). I also removed a duplicate constant `MessageType_ARRAYSIZE`, which I'm assuming is leftover from protobuf-generated code.

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit jdk11

**Pull request merged**
