### PR TITLE
Adapt the formatting to remove unnecessary indent level

### PR DESCRIPTION
**Pull request by DanHeidinga**
Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
@DanHeidinga please fix the copyright failure

**Comment by DanHeidinga** [comment]
I've fixed the copyrights now

**Comment by DanHeidinga** [comment]
Jenkins copyright check

**Comment by DanHeidinga** [comment]
Jenkins line endings check

**Pull request merged**
