### PR TITLE
Enable class sharing by default on all openj9 builds except OSX

### LINKED ISSUE #3854: Enable shared classes by default on jdk8
As enabling shared classes by default for jdk11 #1646 appears to be working now, we can look at enabling it by default on jdk8.

### LINKED ISSUE #3882: Set shared cache dir to user's home directory jdk8
Before #3858 is merged, the default shared cache directory should be changed to the user's home directory for jdk8, as was done for jdk11 via #2862

### PR DESCRIPTION
**Pull request by hangshao0**
Fixes #3854 
Fixes #3882

Doc issue https://github.com/eclipse/openj9-docs/issues/149

Signed-off-by: hangshao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
I stopped the osx build since I don't think it is needed.

**Comment by pshipton** [comment]
jenkins test sanity all jdk8

**Comment by pshipton** [comment]
jenkins test all all jdk8

**Comment by pshipton** [comment]
jenkins test extended win32 jdk8

**Comment by pshipton** [comment]
The extended failures are known issues.

**Comment by hangshao0** [comment]
I've made change to set the default cache directory to user's home on Java 8.

**Comment by pshipton** [comment]
jenkins test sanity all jdk8

**Comment by pshipton** [comment]
jenkins test all all jdk8

**Comment by pshipton** [comment]
The extended failures are known issues.

**Pull request merged**
