### PR TITLE
Anchor arguments of MethodHandle invoke before expansion

### PR DESCRIPTION
**Pull request by liqunl**
The expansion will insert calls before the original call. Anchor the
arguments such that the evaluation of arguments is before the execution
of the call.

Notice that missing the anchoring does not cause functional issues
because the inserted calls are internal to the JIT and have no side
effect on arguments. However, it prevents us from folding argument that
is a static final field because the inserted calls are unsupported
potential OSR points.

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@andrewcraik Can I have you review?

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Comment by andrewcraik** [comment]
error looks to be a repeat of existing javac issue and unrelated to change - merging

**Pull request merged**
