### PR TITLE
Enable gcc-7.5 on Linux platforms for pipeline builds

### PR DESCRIPTION
**Pull request by vsebe**
Upgrade gcc compiler to v7.5.0 for Linux x86, s390x and ppc64le
platforms.  Update PATH and LD_LIBRARY_PATH environment variables.

[ci skip]

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
jenkins compile xlinux,plinux,zlinux jdk8

**Comment by vsebe** [comment]
jenkins compile plinux,zlinux jdk8

**Comment by vsebe** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_linux_Personal/671/

**Comment by vsebe** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Personal/471/
https://ci.eclipse.org/openj9/job/Build_JDK8_ppc64le_linux_Personal/671/

**Comment by pshipton** [comment]
jenkins compile xlinux,plinux,zlinux jdk8,jdk11

**Comment by pshipton** [comment]
jenkins compile xlinux,plinux,zlinux jdk8,jdk11

**Pull request merged**
