### PR TITLE
Add nasm to path for windows pipelines

### PR DESCRIPTION
**Pull request by jdekonin**
* [skip ci]
* v2.13.03 installed as per #3461

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
jenkins compile jdk8

**Comment by jdekonin** [comment]
jenkins compile win,win32 jdk8

**Comment by jdekonin** [comment]
jenkins compile win jdk8

**Comment by jdekonin** [comment]
jenkins compile win jdk11

**Comment by jdekonin** [comment]
jenkins compile win jdk8

**Comment by jdekonin** [comment]
jenkins compile win32 jdk8

**Comment by jdekonin** [comment]
@nbhuiyan this is just testing the addition of nasm to the PATH doesn't break anything existing.  Is there a method for me validating that the install is complete and to expectations?

**Comment by nbhuiyan** [comment]
@jdekonin PR #3459 enables use of NASM on windows. To verify that NASM works as expected, one way I can think of is to rebase my branch once this PR is merged, and launch a build. Perhaps there are better ways?

**Comment by jdekonin** [comment]
jenkins compile win32 jdk8

**Comment by jdekonin** [comment]
jenkins compile win jdk8

**Comment by jdekonin** [comment]
jenkins compile win jdk11

**Comment by jdekonin** [comment]
This is ready for review/commit.

**Pull request merged**
