### PR TITLE
Remove deprecated Java preprocessor flags

### PR DESCRIPTION
**Pull request by keithc-ca**
* remove `Java10` and replace with `JAVA_SPEC_VERSION >= 10`
* remove `Java11` and replace with `JAVA_SPEC_VERSION >= 11`
* remove `Java12` and replace with `JAVA_SPEC_VERSION >= 12`
* remove `Java13` and replace with `JAVA_SPEC_VERSION >= 13`
* remove `Java14` and replace with `JAVA_SPEC_VERSION >= 14`
* remove `Java15` and replace with `JAVA_SPEC_VERSION >= 15`
* remove `Java16` and replace with `JAVA_SPEC_VERSION >= 16`
* remove unused flag `Open-Module-Support`

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins test sanity win32 jdk8

**Comment by keithc-ca** [comment]
Jenkins test sanity aix jdk11

**Comment by keithc-ca** [comment]
Jenkins test sanity osx jdk15

**Comment by keithc-ca** [comment]
Jenkins test sanity zlinux jdknext

**Review by pshipton — APPROVED** [review]

**Pull request merged**
