### PR TITLE
Allow Xcodecachetotal to decrease default total code cache size

### PR DESCRIPTION
**Pull request by mpirvu**
The supported Xcodecachetotal option is not allowed to decrease the default
value for the code cache repository. This commit eliminates that restriction,
but imposes a lower bound of 2MB.

Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
@joransiu Could you please review this PR about allowing a decrease in default code cache size? Thanks

**Comment by joransiu** [comment]
Jenkins test sanity all JDK8

**Comment by fjeremic** [comment]
Failures are due to jvm.cfg issues which are currently being fixed:
https://openj9.slack.com/archives/CDS7QE9HB/p1541085437012100

**Comment by joransiu** [comment]
Jenkins test sanity all JDK8

**Comment by joransiu** [comment]
The OSX build failure is a configuration issue unrelated to this change (looks like in general, it currently only works for JDK 11 atm).  Will go ahead and merge, based on the clean set of remaining Sanity tests.

**Pull request merged**
