### PR TITLE
CMake: require that BOOT_JDK be specified

### PR DESCRIPTION
**Pull request by keithc-ca**
* find java, javac and jar based on BOOT_JDK

### CODE REVIEW

**Comment by keithc-ca** [comment]
This requires ibmruntimes/openj9-openjdk-jdk11#186.

**Comment by keithc-ca** [comment]
The error in the travis build is expected
```
  BOOT_JDK must be defined
```
because the required change in jdk11 is not present.

**Comment by pshipton** [comment]
@dnakamura can you please review this and ibmruntimes/openj9-openjdk-jdk11#186

**Comment by dnakamura** [comment]
Is there a reason we want to force you to define a boot jdk? It is rather nice to have the fallback when hacking around on the build system etc and not wanting to hammer it in on the command line every time

**Comment by keithc-ca** [comment]
I think the one being used by openjdk should definitely take priority over anything that cmake might discover on its own.

If we want to consider allowing cmake to have a default, I think it needs more validation than it was getting before. I ran into that yesterday on a system that didn't have a system JDK install and it proceeded as if things would be alright, but of course they were not. It appeared to make use of an environment variable that was not set. In my opinion, it's not worth the effort to provide a default that might be incompatible with the rest of the build process.

**Comment by dnakamura** [comment]
agreed it probably needs better validation, however it could be set up (and IIRC was set up) so that `BOOT_JDK` has the the final say. Ie if it is specified (presumably the the openjdk makefiles) that is what gets used.

**Comment by keithc-ca** [comment]
`BOOT_JDK` was *not* in the environment and, IMO, it should not be. The environment is a fragile communication channel.

I could live with it using the environment only if `BOOT_JDK` is not specified as a command-line property (and fail if neither was set). @dnakamura Would that satisfy you?

**Comment by keithc-ca** [comment]
As I look at the invocation of cmake, there's already a rather long list of command-line options: those hacking on the build system and invoking cmake directly can easily write a little script if they haven't done so already - one more line there isn't too onerous, IMO.

**Comment by keithc-ca** [comment]
@dnakamura Any further thoughts?

**Comment by dnakamura** [comment]
I'm not crazy about it, but I can live with it

**Comment by pshipton** [comment]
The travis build for `RUN_BUILD=no RUN_LINT=yes` is failing, after I restarted the travis build, after merging ibmruntimes/openj9-openjdk-jdk11#186
```
+cmake -C /home/travis/build/eclipse/openj9/runtime/cmake/caches/linux_x86-64_cmprssptrs.cmake ..
loading initial cache file /home/travis/build/eclipse/openj9/runtime/cmake/caches/linux_x86-64_cmprssptrs.cmake
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-3.8
-- Check for working CXX compiler: /usr/bin/clang++-3.8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:28 (message):
  BOOT_JDK must be defined
```

**Comment by keithc-ca** [comment]
Updated to fix travis lint build.

**Pull request merged**
