### PR TITLE
Remove unused cs2/tableof.h includes

### PR DESCRIPTION
**Pull request by lmaisons**
Signed-off-by: Luc des Trois Maisons <lmaisons@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
LGTM

**Comment by lmaisons** [comment]
I'm not sure why Travis CI reports back as failed, the JVM appears to have compiled successfully and printed its version information without issue...

**Comment by andrewcraik** [comment]
Jenkins test sanity

**Comment by andrewcraik** [comment]
tested fine LGTM - merging

**Pull request merged**
