### PR TITLE
Use boolean conditions in while statements for mac osx

### PR DESCRIPTION
**Pull request by DanHeidinga**
issue: #36

Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
I'm assuming the ci failure is related to #2295

**Comment by pshipton** [comment]
jenkins compile win jdk8

**Comment by pshipton** [comment]
jenkins test sanity plinux jdk8

**Comment by pshipton** [comment]
hmm, I guess the windows compile will fail until #2300 is merged.

**Comment by pshipton** [comment]
jenkins compile win jdk8

**Comment by DanHeidinga** [comment]
The windows build has passed.  Can this be merged?

**Pull request merged**
