### PR TITLE
Collapse JCL shared libraries into a single version

### PR DESCRIPTION
**Pull request by keithc-ca**
This will dramatically simplify working with multiple Java versions from the single openj9 code base.

Instead of trying to manage multiple JCL shared libraries and the complexities of adding a new version every six months, additions and removals can be conditional in C/C++ code based on `JAVA_SPEC_VERSION` or included in the constant pool for specific versions via the `versions="..."` attribute in `vmconstantpool.xml`.

This PR:
* updates the constant pool generation tool to produce a single version
* updates the build process to generate a single JCL library
* collapses JCL versions

Must be merged together with:
* jdk8 - https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/272
* jdk11 - https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/137
* jdk12 - https://github.com/ibmruntimes/openj9-openjdk-jdk12/pull/16
* jdk13 - https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/78

See also: #4632.

### CODE REVIEW

**Comment by keithc-ca** [comment]
The travis failure is expected because it didn't build with https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/137.

**Comment by pshipton** [comment]
jenkins test sanity zlinux,win jdk8,jdk11

**Comment by pshipton** [comment]
jenkins test sanity zlinux,win jdk8 depends ibmruntimes/openj9-openjdk-jdk8#272

**Comment by pshipton** [comment]
jenkins test sanity zlinux,win jdk11 depends ibmruntimes/openj9-openjdk-jdk11#137

**Pull request merged**
