### PR TITLE
[Reapply] Pass Reference repo to get_source.sh

### PR DESCRIPTION
**Pull request by AdamBrousseau**
- Speed up get_source clones by using a local
  reference repository cache.

Issue #6744
[skip ci]

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@pshipton

**Comment by pshipton** [comment]
Note I could have reverted the revert.

**Comment by pshipton** [comment]
jenkins compile zlinux jdk14 depends ibmruntimes/openj9-openjdk-jdk14#58

**Comment by pshipton** [comment]
jenkins compile zlinux jdk8 depends ibmruntimes/openj9-openjdk-jdk8#420

**Comment by pshipton** [comment]
jenkins compile zlinux jdk11 depends ibmruntimes/openj9-openjdk-jdk11#316

**Comment by pshipton** [comment]
jenkins compile zlinux jdk14 depends ibmruntimes/openj9-openjdk-jdk14#58

**Comment by pshipton** [comment]
jenkins compile zlinux jdk15 depends ibmruntimes/openj9-openjdk-jdk15#3

**Comment by pshipton** [comment]
jenkins compile zlinux jdknext depends ibmruntimes/openj9-openjdk-jdk#214

**Pull request merged**
