### PR TITLE
Update JITServer heuristics

### PR DESCRIPTION
**Pull request by mpirvu**
Under -Xjit:enableJITServerHeuristics change the logic that
determines which compilations to keep local vs which ones to
send to the server based on the amount of memory and CPU
available.

Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,xlinuxjit jdk11

**Comment by mpirvu** [comment]
@ymanton, could you please review this PR? Thanks

**Comment by mpirvu** [comment]
jenkins test sanity xlinuxjit jdk11

**Comment by mpirvu** [comment]
jenkins test sanity plinuxjit,xlinuxjit jdk11

**Comment by mpirvu** [comment]
@ymanton Review comments are addressed.

**Comment by mpirvu** [comment]
Infra issues:
```
[Pipeline] artifactoryUpload
expected to call org.jfrog.hudson.pipeline.common.types.ArtifactoryServer.upload but wound up catching artifactoryUpload; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/
03:44:47  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_jit_Personal/104/OpenJ9-JDK11-x86-64_linux_jit-20200519-023853.tar.gz
03:44:56  [consumer_1] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_jit_Personal/104/test-images.tar.gz
03:45:11  Response received: 
03:45:11  
03:45:11  <!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>Apache Tomcat/8.5.32</h3></body></html>
03:45:11  
03:45:11  
03:45:11  Failed while reading the response from: PUT https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_jit_Personal/104/test-images.tar.gz;build.parentNumber=104;build.parentName=Pipeline_Build_Test_JDK11_x86-64_linux_jit;build.buildIdentifier=eclipse/openj9%239556;build.timestamp=1589855924814;build.name=Build_JDK11_x86-64_linux_jit_Personal;build.number=104 HTTP/1.1
03:45:11  [consumer_1] An exception occurred during execution:
03:45:11  java.lang.RuntimeException: java.io.IOException: Failed to deploy file. Status code: 403
03:45:11  	at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
03:45:11  	at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
03:45:11  	at java.lang.Thread.run(Thread.java:821)
```

**Comment by ymanton** [comment]
Jenkins test sanity plinuxjit,xlinuxjit jdk11

**Pull request merged**
