### PR TITLE
Enable atomic-free JNI

### PR DESCRIPTION
**Pull request by gacholio**
Enable the feature everywhere but ARM and OSX.

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Was it intentionally turned on for the ztpf spec?

**Comment by DanHeidinga** [comment]
Is there an issue that describes why this change is being made?  Preferably something that covers what "Atomic-free JNI" is.

**Comment by gacholio** [comment]
TPF was intentional (why not?).  There is no issue.

**Comment by DanHeidinga** [comment]
> TPF was intentional (why not?). There is no issue.

Glad to hear.  I wasn't sure this had been tested / validated on TPF

**Comment by gacholio** [comment]
I don't know what level of testing TPF gets, as another team performs it.  It can always be disabled if need be, though I can't imagine why it wouldn't work there.

**Comment by DanHeidinga** [comment]
Jenkins test sanity all jdk8

**Comment by gacholio** [comment]
Feature is described in issue #2576

**Pull request merged**
