### PR TITLE
Add shrc generation number change to release notes

### PR DESCRIPTION
**Pull request by SueChaplain**
Added to issues table.

[ci skip]

Signed-off-by: Sue Chaplain <sue_chaplain@uk.ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
I think the change should be in the "Notable changes in this release" table.

**Comment by SueChaplain** [comment]
@pshipton Moved to the notable changes table. 

Still one more item to go in the release notes and that's for the watched fields option. I've still had no input on this so far .... anyone you can prod please?

**Comment by pshipton** [comment]
Should `(see the  -Xshareclasses option)` provide a link to the docs?

**Comment by SueChaplain** [comment]
> Should (see the -Xshareclasses option) provide a link to the docs?

It could do Peter, although there is a link to the user guide just before the table. Am a bit stretched this week ..... there is still the other option to go in, so I could fix it then if I have time.

**Comment by pshipton** [comment]
> there is still the other option to go in, so I could fix it then

Sounds good.

**Pull request merged**
