### PR TITLE
Fix off-by-one issue in intrinsicIndexOfString* intrinsic on Z

### PR DESCRIPTION
**Pull request by fjeremic**
When compact strings are enabled and the input and search strings are
of length 1 the `loadLenReg` will contain a value of 0, signifying we
want to load and compare a single character, because the `VLGV`
instruction is zero-length based (0 means load 1 element). If there is
a match in the first character, the index reported by `VLGV` will also
be 0.

There is a fast-path exit which checks if the index matched is past the
last character we're allowed to read, but it doesn't take into account
that index 0 is valid. As such the following test will fail when
compact strings are enabled:

```
"a".indexOf("a", 0) == 0
```

as it will report -1 instead. We fix this by changing the branch
condition to allow for this corner case.

Fixes: #6671
Fixes: #6778

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Marking as WIP/draft PR until #6932 is merged as it fixes a critical bug in the JIT exposed by the tests added in this PR. None the less this PR is ready for peer review. Suggesting @llxia / @smlambert for test reviews and @r30shah / @joransiu for Z codegen fix review.

**Comment by fjeremic** [comment]
#6932 has now been merged. This one is ready as well.

**Comment by fjeremic** [comment]
@llxia could you be the committer for this one? The test portion of the PR needs to be reviewed.

**Comment by fjeremic** [comment]
Could we get a committer to pick this one up?

**Comment by llxia** [comment]
jenkins test sanity all jdk8

**Comment by llxia** [comment]
jenkins test sanity all jdk11

**Comment by llxia** [comment]
jenkins test sanity all jdk8

**Comment by fjeremic** [comment]
@llxia I think there are some problems on Eclipse side. This is why builds are not launching. Some discussion in [1]. Hope they fix it soon 🤞 

[1] https://openj9.slack.com/archives/C8PQL5N65/p1568726726000500

**Comment by AdamBrousseau** [comment]
jenkins test sanity all jdk8

**Comment by AdamBrousseau** [comment]
jenkins test sanity all jdk8

**Comment by AdamBrousseau** [comment]
jenkins test sanity all jdk8

**Comment by AdamBrousseau** [comment]
jenkins test sanity all jdk8

**Comment by AdamBrousseau** [comment]
Jenkins copyright check

**Comment by AdamBrousseau** [comment]
Jenkins test sanity all jdk8

**Comment by AdamBrousseau** [comment]
Jenkins copyright check

**Comment by AdamBrousseau** [comment]
Jenkins line endings check

**Comment by llxia** [comment]
jenkins test sanity all jdk8

**Comment by llxia** [comment]
jenkins test sanity all jdk11

**Comment by llxia** [comment]
`JCL_Test_JITHelpers_0 ` failed on JDK11 on aix:

```
01:11:18.224  FAILED: test_intrinsicIndexOfUTF16
01:11:18.224  java.lang.AssertionError: expected [-1] but found [760911]
01:11:18.224  	at org.testng.Assert.fail(Assert.java:96)
01:11:18.224  	at org.testng.Assert.failNotEquals(Assert.java:776)
01:11:18.224  	at org.testng.Assert.assertEqualsImpl(Assert.java:137)
01:11:18.224  	at org.testng.Assert.assertEquals(Assert.java:118)
01:11:18.224  	at org.testng.Assert.assertEquals(Assert.java:652)
01:11:18.224  	at org.testng.Assert.assertEquals(Assert.java:662)
01:11:18.224  	at org.openj9.test.com.ibm.jit.Test_JITHelpers.test_intrinsicIndexOfUTF16(Test_JITHelpers.java:577)
01:11:18.224  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:11:18.224  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:11:18.224  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:11:18.224  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:11:18.224  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
01:11:18.224  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
01:11:18.224  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
01:11:18.224  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
01:11:18.224  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
01:11:18.224  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
01:11:18.224  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
01:11:18.224  	at org.testng.TestRunner.run(TestRunner.java:505)
01:11:18.224  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
01:11:18.224  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
01:11:18.224  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
01:11:18.224  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
01:11:18.224  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
01:11:18.224  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
01:11:18.224  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
01:11:18.224  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
01:11:18.224  	at org.testng.TestNG.runSuites(TestNG.java:1049)
01:11:18.224  	at org.testng.TestNG.run(TestNG.java:1017)
01:11:18.224  	at org.testng.TestNG.privateMain(TestNG.java:1354)
01:11:18.224  	at org.testng.TestNG.main(TestNG.java:1323)
01:11:18.224  
01:11:18.224  
01:11:18.224  ===============================================
01:11:18.224      JCL_TEST_JITHelpers
01:11:18.224      Tests run: 13, Failures: 1, Skips: 0
01:11:18.224  ===============================================
```
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_ppc64_aix_Personal/114/consoleFull

**Comment by fjeremic** [comment]
Very interesting. Looking at the method we failed in it's actually not one of the tests we introudced in this PR. The test that fails seems to come from the tests we just merged a few hours ago in #7000. The particular failure is in Test_JITHelpers.java:577 which corresponds to the test in [1].

The reason this suddenly starts failing is because when #7000 got merged we were not running the tests with the variations we introduce as part of this PR. With the extra variations we have in this PR, i.e.

```
      <variation>-Xjit:count=0 -XX:-CompactStrings</variation>
      <variation>-Xjit:count=0 -XX:+CompactStrings</variation>
      <variation>-Xjit:count=1,disableAsyncCompilation -XX:-CompactStrings</variation>
      <variation>-Xjit:count=1,disableAsyncCompilation -XX:+CompactStrings</variation>
```

We are now able to 100% deterministically catch the bug (yay for unit testing!). I'm going to reproduce this locally momentarily and investigate. @gita-omr @aviansie-ben FYI we seem to have a corner case bug in the `intrinsicIndexOfUTF16` [2] evaluator on Power.

[1] https://github.com/eclipse/openj9/pull/7000/files#diff-fe67427200feb55170a5f1cce53462a1R577
[2] https://github.com/eclipse/openj9/blob/master/runtime/compiler/p/codegen/J9TreeEvaluator.cpp#L12206

**Comment by fjeremic** [comment]
I've added 7b4b511 which fixes the issue. As per the documentation in [1] the offset must be at most equal to the length, so we checked in a faulty test which the JIT ends up tripping on because of the additional JIT test variations added as part of this PR.

[1] https://github.com/eclipse/openj9/blob/12ef37b1db2bc58ace8f532dbd102464dbd1c689/jcl/src/java.base/share/classes/com/ibm/jit/JITHelpers.java#L665-L670

We should be good to go here. We can verify things are passing now.

jenkins test sanity all jdk11

**Comment by fjeremic** [comment]
@AdamBrousseau any idea why the trigger failed here? Triggers at the end of a comment used to work fine before. Is this a recent regression?

https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/1266/console:

```
ghprbCommentBody:'I've added 7b4b511 which fixes the issue. As per the documentation in [1] the offset must be at most equal to the length, so we checked in a faulty test which the JIT ends up tripping on because of the additional JIT test variations added as part of this PR.\r\n\r\n[1] https://github.com/eclipse/openj9/blob/12ef37b1db2bc58ace8f532dbd102464dbd1c689/jcl/src/java.base/share/classes/com/ibm/jit/JITHelpers.java#L665-L670\r\n\r\nWe should be good to go here. We can verify things are passing now.\r\n\r\njenkins test sanity all jdk11'
[Pipeline] echo
ghprbTargetBranch:'master'
[Pipeline] echo
ghprbActualCommit:'7b4b51113313db7349bfaec480179f5c10167593'
[Pipeline] timeout
Timeout set to expire in 12 hr
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] node
15:38:22  Running on worker-1 in /home/jenkins/jenkins-agent/workspace/PullRequest-OpenJ9@2
[Pipeline] {
[Pipeline] checkout
15:38:23  using credential b6987280-6402-458f-bdd6-7affc2e360d4
15:38:24  Cloning the remote Git repository
15:38:24  Cloning repository https://github.com/eclipse/openj9.git
15:38:24   > git init /home/jenkins/jenkins-agent/workspace/PullRequest-OpenJ9@2 # timeout=10
15:38:24  Using reference repository: /home/jenkins/openjdk_cache
15:38:24  Fetching upstream changes from https://github.com/eclipse/openj9.git
15:38:24   > git --version # timeout=10
15:38:24  using GIT_ASKPASS to set credentials Github bot
15:38:24   > git fetch --tags --progress https://github.com/eclipse/openj9.git +refs/heads/*:refs/remotes/origin/*
15:38:33   > git config remote.origin.url https://github.com/eclipse/openj9.git # timeout=10
15:38:33   > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
15:38:33   > git config remote.origin.url https://github.com/eclipse/openj9.git # timeout=10
15:38:33  Fetching upstream changes from https://github.com/eclipse/openj9.git
15:38:33  using GIT_ASKPASS to set credentials Github bot
15:38:33   > git fetch --tags --progress https://github.com/eclipse/openj9.git +refs/pull/6938/merge:refs/remotes/origin/pr/6938/merge
15:38:34  Checking out Revision 00a4f89401d45e2f52dfa3e10e48cdfc392c539b (refs/remotes/origin/pr/6938/merge)
15:38:34   > git rev-parse refs/remotes/origin/pr/6938/merge^{commit} # timeout=10
15:38:34   > git rev-parse refs/remotes/origin/origin/pr/6938/merge^{commit} # timeout=10
15:38:34   > git config core.sparsecheckout # timeout=10
15:38:34   > git checkout -f 00a4f89401d45e2f52dfa3e10e48cdfc392c539b
15:38:40  Commit message: "Merge 7b4b51113313db7349bfaec480179f5c10167593 into 12ef37b1db2bc58ace8f532dbd102464dbd1c689"
[Pipeline] load
[Pipeline] { (buildenv/jenkins/common/variables-functions.groovy)
[Pipeline] }
[Pipeline] // load
[Pipeline] load
[Pipeline] { (buildenv/jenkins/common/pipeline-functions.groovy)
[Pipeline] }
[Pipeline] // load
[Pipeline] error
[Pipeline] cleanWs
15:38:44  [WS-CLEANUP] Deleting project workspace...
15:38:44  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
15:38:59  [WS-CLEANUP] done
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
Time spent fetching downstream jobs for PullRequest-OpenJ9: 0.001 seconds
[Pipeline] End of Pipeline
Setting status of 7b4b51113313db7349bfaec480179f5c10167593 to FAILURE with url https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/1266/ and message: ' '
Using context: Pull Request - OpenJ9
ERROR: Unable to parse trigger comment. Unknown build option:'added'
Finished: FAILURE
```

**Comment by AdamBrousseau** [comment]
Not recent, since we changed over the build, months ago.
I opened an issue (internally) to address the comment parsing to make it more forgiving.

**Comment by fjeremic** [comment]
jenkins test sanity all jdk11

**Comment by pshipton** [comment]
@fjeremic is this going to get into the 0.17 release?

**Comment by pshipton** [comment]
Given the approvals we already have, I'm happy to merge this, although I'll wait until Monday just in case there are problems.

**Comment by fjeremic** [comment]
> @fjeremic is this going to get into the 0.17 release? i.e. is there enough of a benefit and a low enough risk?

Yes I think this needs to go in. The fix is very contained and unit tests have been written for extra coverage.

**Comment by pshipton** [comment]
@fjeremic I've merged this, pls create the PR for the 0.17 release.

**Pull request merged**
