### PR TITLE
Remove J9PPCArrayCmp.spp

### PR DESCRIPTION
**Pull request by aviansie-ben**
Previously, the Power codegen had a file called J9PPCArrayCmp.spp that
was supposed to have helpers related to array comparison. However, this
file has been surrounded by an `#if 0` guard for a significant period of
time, rendering it useless. In line with this, the file has been
entirely removed as it's not doing anything.

Signed-off-by: Ben Thomas <ben@benthomas.ca>

### CODE REVIEW

**Comment by gita-omr** [comment]
@zl-wang fyi. LGTM.

**Comment by zl-wang** [comment]
LGTM too.

**Comment by gita-omr** [comment]
Oops, forgot Jenkins test... let me do it anyway.

**Comment by gita-omr** [comment]
Jenkins test sanity aix,plinux jdk8,jdk11

**Comment by dsouzai** [comment]
@gita-omr no builds will run after a PR is merged; in the future please ensure Jenkins has run prior to merging.

**Comment by gita-omr** [comment]
Yes, as my comment above indicated, I merged accidentally. Sorry about that.

**Pull request merged**
