### PR TITLE
Relocate Compilation instruction pointers to CodeGenerator

### PR DESCRIPTION
**Pull request by 0xdaryl**
The "first" and "append" instruction pointers are being relocated to the
CodeGenerator object from the Compilation object.  Fix up all call sites
to call the CodeGenerator equivalents.

Functions affected:

* getFirstInstruction()
* setFirstInstruction()
* getAppendInstruction()
* setAppendInstruction()

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
This will stay WIP until https://github.com/eclipse/omr/pull/1841 is merged.

**Comment by 0xdaryl** [comment]
Jenkins test sanity

**Comment by fjeremic** [comment]
Looks like https://github.com/eclipse/omr/pull/1841 is merged. Will wait for WIP removal and a green light from the author before merging this.

**Comment by fjeremic** [comment]
@0xdaryl is this good to merge? Please see comment above.

**Comment by 0xdaryl** [comment]
Its been a while, so I rebased and am re-running some sanity tests.  If all goes well as expected I'll remove the WIP.

**Comment by 0xdaryl** [comment]
Personal testing passed.  No longer a WIP.

**Comment by fjeremic** [comment]
Jenkins test sanity

**Pull request merged**
