### PR TITLE
WIP: Support static value type fields

### PR DESCRIPTION
**Pull request by thomaslittletrainx**
1. Add the ACC_STATIC flag to any static fields in value type classes.
2. Create value type classes with static fields to test.
 
Signed-off-by: thomasli <Xinhai.Li@ibm.com>

### CODE REVIEW

**Comment by thomaslittletrainx** [comment]
@tajila  I set the ACC_STATIC flag for VT static fields and created a class with static fields. Is there a way to check if the fields in an instance is static or not? Please review.

**Comment by tajila** [comment]
>  I set the ACC_STATIC flag for VT static fields and created a class with static fields

If the ACC_STATIC flag is set than the field is a static field.

**Comment by thomaslittletrainx** [comment]
@tajila Changes made as suggested. Please have a look.

**Comment by DanHeidinga** [comment]
@tajila given the changes in Valhalla, is this still relevant or should it be closed?

**Comment by tajila** [comment]
Work was completed in another PR

**Pull request closed without merging**
