### PR TITLE
Use ByteArrayOutputStream instead of List<Byte>

### PR DESCRIPTION
**Pull request by keithc-ca**
ByteArrayOutputStream is much more space-efficient than any list of Byte object references.

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity,extended win,zlinux jdk8

**Comment by keithc-ca** [comment]
Jenkins test sanity,extended win jdk8

**Comment by pshipton** [comment]
Testing on windows is running twice. once from the original PR test and again in the second.
Not sure why the second was started, was the running build not reflected in this PR?
https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK8_x86-64_windows/2463/
https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK8_x86-64_windows/2466/

**Comment by pshipton** [comment]
Ok I see. The first one actually failed due to failing to delete the workspace and is waiting for a restart or abort selection.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
