### PR TITLE
Port cmdLineTester_fastClassHashTable into openj9

### PR DESCRIPTION
**Pull request by llxia**
Related: runtimes/backlog/issues/378

[ci skip]

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by llxia** [comment]
|JDK_VERSION|JDK_IMPL|PLATFORM|Ginder|
|--|--|--|--|
|8| opnej9 |all|Grinder/10740 |
|11| opnej9 |all|/Grinder/10750 |

**Comment by llxia** [comment]
jenkins test extended all jdk8,jdk11

**Comment by llxia** [comment]
[TestAttachErrorHandling_0](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Personal/78/) failure on aix is related to #3081

**Comment by llxia** [comment]
jenkins test extended win32,win jdk8

**Comment by llxia** [comment]
@pshipton could you please review this when you have time? Thanks

**Review by pshipton — APPROVED** [review]

**Pull request merged**
