### PR TITLE
AArch64: Add ARM64RelocationTarget

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds code for ARM64RelocationTarget.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
Functions of `TR_ARM64RelocationTarget` are to be implemented later in a separate PR.

**Comment by 0xdaryl** [comment]
Can you open an issue to track the work to complete the implementation in the future please?

**Comment by knn-k** [comment]
I opened Issue #6636 to track the work.

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11

**Pull request merged**
