### PR TITLE
Removing references to UT_DIRECT_TRACE_REGISTRATION in OpenJ9

### PR DESCRIPTION
**Pull request by adityas71094**
Closes: #6080
Signed-off-by: Aditya Subramanian <aditarun2008@gmail.com>

### CODE REVIEW

**Comment by adityas71094** [comment]
runtime/cuda/CudaCommon.cpp has failed the Copyright Check, should I just change the date? Or is there some process that I have to follow ?

**Comment by 0xdaryl** [comment]
Yes.  The contributor is responsible for making sure the leading copyright date is current on all files changed.  Please update it to 2019.

**Comment by adityas71094** [comment]
Can anyone review this PR ?

**Comment by charliegracie** [comment]
Can you squash the commits into a single commit?

**Comment by charliegracie** [comment]
jenkins test sanity plinux jdk11

**Comment by adityas71094** [comment]
@charliegracie squashed the commits.

**Comment by adityas71094** [comment]
@charliegracie does anything else need to be changed?

**Comment by DanHeidinga** [comment]
jenkins test sanity win32 jdk8

**Pull request merged**
