### PR TITLE
Enable native tests using executables in test image

### PR DESCRIPTION
**Pull request by sophia-guo**
Enable for 8,9,11
Disable problematic tests with issues opened

[ci skip]

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
FYI @llxia

**Comment by llxia** [comment]
Jenkins test sanity all jdk8

**Comment by llxia** [comment]
Jenkins test sanity xlinux jdk8

**Comment by llxia** [comment]
Jenkins test sanity plinux,aix,win jdk8

**Comment by llxia** [comment]
Jenkins test sanity plinux,aix jdk8

**Comment by llxia** [comment]
Jenkins test sanity win jdk8

**Comment by llxia** [comment]
Jenkins test sanity xlinux,plinux,aix jdk11

**Comment by llxia** [comment]
Wins jdk11 build failed at SDK compilation. The failure is not related to this PR. https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-win_x86-64_cmprssptrs-OpenJ9/83/

Since the rest of PR builds passed, I am going to merge this change.

**Pull request merged**
