### PR TITLE
Rename com.ibm.traceformat to openj9.traceformat

### PR DESCRIPTION
**Pull request by mikezhang1234567890**
Changed all text instances with old module name to openj9.traceformat

Depends on https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/84

Signed-off-by: Mike Zhang <mike.h.zhang@ibm.com>

### CODE REVIEW

**Comment by mikezhang1234567890** [comment]
Reviewers: @JasonFengJ9 @DanHeidinga

**Comment by pshipton** [comment]
There is a reference to com.ibm.traceformat in /openj9/debugtools/DDR_VM/compile_ddr.xml

**Comment by JasonFengJ9** [comment]
There is no usual deletion for previous module `com.ibm.traceformat`, it seems both modules are included.

**Comment by mikezhang1234567890** [comment]
For `/openj9/debugtools/DDR_VM/compile_ddr.xml`, we don't build DDR in OpenJ9, and internal builds use Java 8 jars as per the comments in that file. So we have to use old module names until then.

**Comment by pshipton** [comment]
I don't think the reference to module com.ibm.traceformat can refer to the traceformat.jar as there is nothing in place to modularize the jar with the name com.ibm.traceformat. You might find that when you address Jason's comment to remove the old com.ibm.traceformat then compile_ddr.xml will need to be fixed in order for the internal builds to continue to work.

**Comment by pshipton** [comment]
Mike explained the com.ibm.traceformat reference in compile_ddr.xml works because the internal build is using an older JVM which still contains this module.

**Pull request merged**
