### PR TITLE
Enable openssl on JDK11 for Windows,pLinux and xLinux

### PR DESCRIPTION
**Pull request by jdekonin**
* [skip ci]
* related #31

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
fyi @pshipton

**Comment by pshipton** [comment]
jenkins test sanity xlinux,plinux,zlinux,win jdk11

**Comment by pshipton** [comment]
jenkins compile xlinuxlargeheap jdk11

**Comment by pshipton** [comment]
@jdekonin did we miss something, is extra_getsource_options not enabled for jdk11?
```
11:18:37 checking for OPENSSL... no
11:18:37 configure: error: Unable to find openssl in specified location /home/jenkins/openssl-1.1.1
```

**Comment by pshipton** [comment]
I don't get it. zlinux uses a pre-built openssl in location `/home/jenkins/openssl-1.1.1`, which is working for jdk8 but not jdk11

**Comment by pshipton** [comment]
plinux using `--with-openssl=fetched` is also failing
`11:34:04 make[3]: *** No rule to make target '/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK11-linux_ppc-64_cmprssptrs_le-OpenJ9/openssl/libcrypto.so.1.1', needed by '/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK11-linux_ppc-64_cmprssptrs_le-OpenJ9/build/linux-ppc64le-normal-server-release/support/modules_libs/java.base/libcrypto.so.1.1'.  Stop.`
@enasser

**Comment by keithc-ca** [comment]
I suspect the

> No rule to make target .../openssl/libcrypto.so.1.1

is becaus OSX is the only platform where the build command line starts with a tab.

**Comment by pshipton** [comment]
jenkins test sanity xlinux,plinux,zlinux,win jdk11 depends ibmruntimes/openj9-openjdk-jdk11#78

**Comment by keithc-ca** [comment]
Jenkins test sanity xlinux,plinux,zlinux,win jdk11 depends ibmruntimes/openj9-openjdk-jdk11#78

**Comment by keithc-ca** [comment]
Jenkins test sanity xlinux,plinux,zlinux,win jdk11 depends ibmruntimes/openj9-openjdk-jdk11#78

**Comment by enasser** [comment]
@pshipton I saw @keithc-ca already fixed the build issues and merged the PR.. not sure why the tab becomes spaces when I raise the PR.. looks like my editor issue..

**Comment by keithc-ca** [comment]
zLinux failed:
> configure: error: Unable to find openssl in specified location /home/jenkins/openssl-1.1.1

@jdekonin can you check that the machine is set up as expected?

**Comment by pshipton** [comment]
@enasser the zlinux build issue is not fixed. zlinux uses a pre-built openssl in location /home/jenkins/openssl-1.1.1, which is working for jdk8 but not jdk11

**Comment by pshipton** [comment]
@enasser probably you can't see the PR build links. The zlinux failure can be seen at
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-linux_390-64_cmprssptrs-OpenJ9/104/

**Comment by pshipton** [comment]
@enasser jdk8 and jdk11 share the same machines. Here is a run on the same machine for jdk8.
https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-Sanity-JDK8-linux_390-64_cmprssptrs-OpenJ9/490
`12:16:31 + bash configure --with-freemarker-jar=/home/jenkins/freemarker.jar --with-boot-jdk=/usr/lib/jvm/adoptojdk-java-s390x-80 --with-openssl=/home/jenkins/openssl-1.1.1 --enable-openssl-bundling`
`12:17:08 checking for OPENSSL... yes`

**Comment by pshipton** [comment]
@jdekonin while we figure out the zlinux issue, can you please separate the zlinux change from this PR (and fix the commit title). I'll merge the other platforms which are working.

**Comment by enasser** [comment]
Thank you @pshipton @keithc-ca. Looks there is an issue with zLinux platform with pre-built openssl.. I am looking into it..

**Comment by enasser** [comment]
@pshipton @keithc-ca  The variables LIBRARY_PREFIX and SHARED_LIBRARY_SUFFIX are used in CONFIGURE_OPENSSL which is set only later in  toolchain.m4.  The root cause is CONFIGURE_OPENSSL is defined in CUSTOM_EARLY_HOOK. If we move it to CUSTOM_LATE_HOOK, the issue can be resolved. Currently am building it on zLinux. Will raise the pull request once the build process is completed.

**Comment by pshipton** [comment]
@jdekonin re the new commit title, this does not affect AIX (and should not).

**Comment by jdekonin** [comment]
Ah, for some reason I thought I saw a change for AIX, my bad.  Fixed both abstract and commit comment.

**Comment by enasser** [comment]
@pshipton Created the PR https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/79 for the configure failure with xz64.

**Pull request merged**
