### PR TITLE
Remove unused local variables

### PR DESCRIPTION
**Pull request by keithc-ca**
Fixes a fatal warning when building with cmake.

### CODE REVIEW

**Comment by keithc-ca** [comment]
What version of `nasm` is used by the travis build?
Does it understand the `-Wreturn-type` option added by #9679?

**Comment by keithc-ca** [comment]
I tried installing `nasm` in a ubuntu:16.04 docker container to test:
```
# nasm -Wreturn-type -v
nasm: error: invalid warning `return-type'
NASM version 2.11.08
```
In ubuntu:18.04:
```
nasm -Wreturn-type -v
NASM version 2.13.02
```
`.travis.yml` specifies 'xenial' which is 16.04: how did the travis build in #9679 pass?

**Comment by mpirvu** [comment]
jenkins compile xlinuxcm jdk11

**Comment by mpirvu** [comment]
The change looks good and build with cmake has passed on one platform, hence merging.

**Pull request merged**
