### PR TITLE
Merge JITServer update in env directory

### PR DESCRIPTION
**Pull request by a7ehuo**
Most of the changes are related to formatting.

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Comment by a7ehuo** [comment]
This one could be reviewed after #7487.

**Comment by a7ehuo** [comment]
Will revert the change in `CompilationThread.hpp`. It was updated in order to remove `JITSERVER_TODO` in `env/VMJ9.cpp`. 

https://github.com/eclipse/openj9/blob/b6c9177f46527c6730cd4be15b35e7d8ec1bea67/runtime/compiler/env/VMJ9.cpp#L598-L600

**Comment by a7ehuo** [comment]
@mpirvu  All comments addressed. Ready for another review. Thanks.

**Comment by mpirvu** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by mpirvu** [comment]
mac test failed due to infra. Will restart.

**Comment by mpirvu** [comment]
Jenkins test sanity osx jdk8

**Comment by mpirvu** [comment]
Tests have passed, hence merging

**Pull request merged**
