### PR TITLE
AArch64: Add rules for JIT assembler files

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds rules for JIT assembler files for aarch64.

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
C preprocessor converts `.spp` files to `.s` files.

**Comment by knn-k** [comment]
The Travis CI build failed with:
> Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:443... connected.
> Unable to establish SSL connection.

**Comment by knn-k** [comment]
Separated addition of `-fPIC` in `common.mk` to PR #5017, because that is not a part of rules for asm files.

**Comment by 0xdaryl** [comment]
Jenkins test sanity plinux,xlinux,zlinux,osx jdk11

**Comment by 0xdaryl** [comment]
Is the plan to follow the same build flow for AArch64 assembly files as it is for AArch32?  That is,

`.armasm` ----via armasm2gas----> `.spp` ----via C preprocessor----> `.s`

If so, can you explain why the first step is necessary?  Why not write in `.spp` directly?

**Comment by knn-k** [comment]
I am not planning to use `.armasm` in aarch64 build.
I added the initial version of `PicBuilder` (declaration only) as `.spp` instead of `.armasm` in #4816.

**Pull request merged**
