### PR TITLE
Use compressionFlag null test as a check to see if string is compressed

### PR DESCRIPTION
**Pull request by yanluo7**
Implemented compressionFlag null test for remaining String operations

Signed-off-by: Yan Luo <yan_luo@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Jenkins test sanity plinux

**Comment by yanluo7** [comment]
@DanHeidinga We've been using bumblebench to run microbenchmark testcases targeting individual methods to see the generated code where the `compressionFlag` check is being NOP'd. As a result, we've seen abround 2-3% throughput gain in StringHashcode, StringEquals, StringGetBytes,StringConcat,StringReplace,StringSubstring,StringIndexOf,StringCompareTo,StringSplit,and various forms of String Constructors.

**Comment by DanHeidinga** [comment]
Is there a separate PR with the bumblebench microbenchmarks?

**Comment by yanluo7** [comment]
@DanHeidinga Not yet, but we will be making one with the testcases, along with changes to the microbenchmark others in the team are working on.

**Pull request merged**
