### PR TITLE
Use a bitset for shouldNotBeNewlyExtended

### PR DESCRIPTION
**Pull request by lmaisons**
Move the definition of MAX_TOTAL_COMP_THREADS to its own header.

Change the definiton of the _shouldNotBeNewlyExtended field in
TR_PersistentClassInfo to use a std::bitset with a size of
MAX_TOTAL_COMP_THREADS, and update implemntation to work with the new
format.

Signed-off-by: Luc des Trois Maisons <lmaisons@ca.ibm.com>

### CODE REVIEW

**Comment by lmaisons** [comment]
It seems that, on some platforms, std::bitset<BITS> will use a 32 bit integer for all values of BITS <= 32 [1]. I'm not sure that matters, as I'm not sure how many of these structures we create, but it may be worth checking to see if this has a footprint impact.

[1] https://stackoverflow.com/questions/7511355/why-is-stdbitset8-4-bytes-big

**Comment by lmaisons** [comment]
@mpirvu @dsouzai FYI

**Comment by mpirvu** [comment]
Yes, this has some footprint impact. I remember that I made the filed 8-bit on purpose to avoid the footprint increase because we have such a field for every class that is loaded. This is why we cannot have more than 8 compilation threads (one bit per compilation thread)

**Comment by mpirvu** [comment]
I have to ask about the purpose of this change. To me flags8_t looks like a good type to use that ensures no memory wastage.

**Comment by andrewcraik** [comment]
So this is introducing a 4th bitset data structure into the codebase - TR_BitVector being one with the CS2 dense and sparse bit bectors being the others. What is the justification for the use of std::bitset in this context?

Going forward perhaps we should find a way to abstract tall of the different bit set data structures behind a common API (a template with explicit instantiation perhaps?) so that we can have a common API and data structures can be swapped in and out easily as performance requires and the codebase evolves? Not necessarily requiring this, but thought we should at least consider the longer term direction of the bit set data structures and how to avoid them proliferating in poorly controlled ways...

**Comment by lmaisons** [comment]
The purpose of this change was to enable building a JVM that allowed the use of more than 7+1 compilation threads should that be desired.

Re: std::bitset vs other bit vectors:
std::bitset was used in this context instead of an existing bit vector implementation because std::bitset fixes its size at compile time, and eschews dynamic allocation completely.  None of our existing facilities offer that property.  As for the use of a common API for bit vectors, I think that makes sense in principle.  I expect that smoothing the rough corners related to memory management will not be a trivial task, but given our historical hardships experienced surrounding bit vector implementations, quite possibly a worthwhile one.

**Comment by andrewcraik** [comment]
ok that makes sense to me from a data structures perspective - there is a benefit here you can't get with the existing implementations. Hopefully, we will be able to reduce the number being used going forward, but an aspirational goal for an API for all - or at least one for a static and one for a dynamic bit set would seem a good goal to have.

**Comment by dsouzai** [comment]
We probably need to measure the memory impact, but would `std::vector<bool>` be a good compromise for memory footprint vs comp thread scalability? It may not fix the size at compile time but it is supposed to be very efficient.

**Comment by mpirvu** [comment]
On the number of compilation threads, I don't see the need to move beyond 7 usable compilation threads. I haven't seen strong evidence that even 7 are needed. Compilations are not totally independent (they do acquire monitors from time to time) and they increase the footprint when going in parallel, so having too many of them is counter-productive.

**Comment by lmaisons** [comment]
Not needed at this time.

**Pull request closed without merging**
