### PR TITLE
Remove obsolete CommandLineOptions.html

### PR DESCRIPTION
**Pull request by dmitripivkine**
This collection of GC related options is obsolete (last time was updated
for 2.4). There is a different (better) way to provide description for
command lime options now.

Issue #319 

Signed-off-by: dmitripivkine <Dmitri_Pivkine@ca.ibm.com>

### CODE REVIEW

**Comment by dmitripivkine** [comment]
Jenkins test sanity

**Comment by AdamBrousseau** [comment]
Jenkins copyright check

**Comment by AdamBrousseau** [comment]
Jenkins line endings check

**Comment by AdamBrousseau** [comment]
Jenkins line endings check

**Comment by SueChaplain** [comment]
Hi @dmitripivkine. Can this be closed now - looks as if the file has been removed. Thanks

**Pull request merged**
