### PR TITLE
Use JITServer check to create a relocation record for interface calls on Power

### PR DESCRIPTION
**Pull request by dchopra001**
This is a double delivery of #7386

### CODE REVIEW

**Comment by dchopra001** [comment]
@mpirvu

**Comment by mpirvu** [comment]
Jenkins test sanity plinux,aix jdk8,jdk11

**Comment by mpirvu** [comment]
On aix Java8 there is one failure: `SharedCPEntryInvokerTests_1`

**Comment by mpirvu** [comment]
Jenkins test sanity aix jdk8

**Comment by dchopra001** [comment]
@mpirvu Tests passed, so this is good to merge as well.

**Pull request merged**
