### PR TITLE
WIP: Initial checkin of Jenkins files

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Issue #660

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins test sanity zlinux jdk9

**Comment by AdamBrousseau** [comment]
Jenkins test sanity plinux java9

**Comment by AdamBrousseau** [comment]
Jenkins test sanity all all

**Comment by AdamBrousseau** [comment]
Adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
Jenkins test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity plinux java9

**Comment by AdamBrousseau** [comment]
adam test sanity

**Comment by AdamBrousseau** [comment]
adam test sanity plinux java9

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity zlinux java9

**Comment by AdamBrousseau** [comment]
adam test sanity all java8

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all java9

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam test sanity all all

**Comment by AdamBrousseau** [comment]
adam compile all all

**Comment by AdamBrousseau** [comment]
adam compile all all

**Comment by AdamBrousseau** [comment]
adam compile plinux java8

**Comment by DanHeidinga** [comment]
@AdamBrousseau Is this a duplicate of PR#851?

**Pull request closed without merging**
