### PR TITLE
Remove deprecated code related to ArrayCopy

### PR DESCRIPTION
**Pull request by 0dvictor**
Old implementation of ArrayCopy has been deprecated, cleaning up.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by 0dvictor** [comment]
This Pull Request requires https://github.com/eclipse/omr/pull/2167

**Comment by fjeremic** [comment]
This is currently blocking the build as the OMR dependent change has been merged. @0dvictor could you please resolve the merge conflicts?

**Comment by 0dvictor** [comment]
Conflicts now have been resolved. It is ready to be merged now.

**Comment by vijaysun-omr** [comment]
@cathyzhyi please review.

**Comment by cathyzhyi** [comment]
LGTM

**Comment by fjeremic** [comment]
Jenkins test sanity depends eclipse/omr#2167

**Comment by fjeremic** [comment]
Jenkins test sanity

**Pull request merged**
