### PR TITLE
SUPERSEDED: Remove hand-written assembly for SSE check

### PR DESCRIPTION
**Pull request by 0dvictor**
Instead of hand-written assembly code, X86 now uses intrinsic
function _mm_getcsr() on Windows and inlined assembly on Linux
to check SSE support.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
@0dvictor Good find!  I think we can go further and remove all of this code from the JIT as the VM already ensures that SSE2 is supported on x86, refusing to start the JVM if SSE2 isn't available.

Checkout `jvminit.c`:
```
#ifdef J9VM_ENV_SSE2_SUPPORT_DETECTION
	if (FALSE == isSSE2SupportedOnX86()) {
		j9nls_printf(portLibrary, J9NLS_ERROR, J9NLS_VM_SSE2_NOT_SUPPORTED);
		return JNI_ERR;
	}
#endif /* J9VM_ENV_SSE2_SUPPORT_DETECTION */
```

Its very similar to what the JIT is doing.  Can this code be removed from the JIT and the same cleanup be applied to the VM's version?

**Comment by 0dvictor** [comment]
Good point. Checking for SSE/SSE2 availability in JIT is indeed redundant as VM requires and guarantees SSE2 support. I'm preparing another Pull Request to remove the related code from JIT.

**Comment by 0dvictor** [comment]
Having a quick look at `jvminit.c`, I believe we can easily apply this cleanup to VM's `isSSE2SupportedOnX86()` function.

**Comment by 0dvictor** [comment]
https://github.com/eclipse/omr/pull/1714 need go in before this redundant checks can be removed.

**Comment by 0dvictor** [comment]
This PR has become the combination of following three PRs:
1. https://github.com/eclipse/omr/pull/1714
2. https://github.com/eclipse/openj9/pull/224
3. https://github.com/eclipse/openj9/pull/300

Closing.

**Pull request closed without merging**
