### PR TITLE
Add missing JITServer StreamInterrupted handle

### PR DESCRIPTION
**Pull request by harryyu1994**
When JITServer is at the "early translation" stage and JITClient issues 
an interruption, an exception will be thrown in the next JITServer read. 
However, the catch statement did not include handling of `StreamInterrupted`
exceptions and as a result will treat the interruption as a `compilationFailure` . 
An client-issued interruption and an actual compilationFailure are handled differently. 
For the actual `compilationFailure`, JITserver has to inform JITclient about the 
compilation failure so it terminates the compilation on its end. But for an interruption, 
JITClient already took action and terminated the compilation so JITserver should not 
remind JITClient about it again.
[skip ci]

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@mpirvu Hi Marius, I have verified on my end that the mismatch failures went away with this change. Maybe you want to verify again on your end. And it's ready for review.

**Comment by harryyu1994** [comment]
I have verified that this code path does get entered and it was not properly handled before

JITServer log:
```
#JITServer: Server will process a list of 0 unloaded classes for clientUID 4765992136370800785
#JITServer: <EARLY TRANSLATION FAILURE: compilation interrupted by JITClient>
#JITServer: compThreadID=0 has failed to compile
#JITServer: compThreadID=0 found clientSessionData=00007F5646C94BC0 for clientUID=4765992136370800785 seqNo=242
```

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaa

**Comment by harryyu1994** [comment]
Yes we could see `compilationStreamFailure` at the same point. I added in a catch statement for compilationStreamFailure as well.

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk8,jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
In Java11 there is this J9vmTest_2 failure which we have seen before
```
+++ j9vm.test.jni.CriticalRegionTest: +++
command: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdkbinary/j2sdk-image/bin/java -XX:+UseJITServer -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump -Xms64m -Xmx64m    -classpath /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/../../jvmtest/functional/VM_Test/VM_Test.jar:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.jni.CriticalRegionTest 

03:01:15.178 0x1a60800    j9mm.141    *   ** ASSERTION FAILED ** at ../gc_glue_java/MetronomeDelegate.hpp:231: ((false))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2019/11/01 00:01:15 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15725733263748/J9vmTest_2/core.20191101.000115.28547.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.28578.

JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15725733263748/J9vmTest_2/core.20191101.000115.28547.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15725733263748/J9vmTest_2/javacore.20191101.000115.28547.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15725733263748/J9vmTest_2/javacore.20191101.000115.28547.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15725733263748/J9vmTest_2/Snap.20191101.000115.28547.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15725733263748/J9vmTest_2/Snap.20191101.000115.28547.0003.trc
JVMDUMP013I Processed dump event "traceassert", detail "".
no-zero exit value: 255
*** Test FAILED *** (j9vm.test.jni.CriticalRegionTest)
```

**Comment by mpirvu** [comment]
Jenkins test sanity.functional+jitaas xlinux jdk11 depends eclipse/openj9-omr#jitaas

**Comment by mpirvu** [comment]
BTW, I see no performance issues, so we should be good.

**Comment by mpirvu** [comment]
Only the known `cmdLineTester_gcsuballoctests_0` test is failing, hence merging.

**Pull request merged**
