### PR TITLE
Remove <PLATFORM>_mixed_cm and use <PLATFORM>_mixed for mixed refs

### PR DESCRIPTION
**Pull request by sharon-wang**
Since we intend to deprecate UMA, we are not pursuing mixed references builds for UMA. As such, we only need a single pipeline spec for mixed references builds on each platform.

The new PR build shortnames for mixed references:
- `aixmxd`
- `alinux64mxd`
- `osxmxd`
- `plinuxmxd`
- `winmxd`
- `xlinuxmxd`
- `zlinuxmxd`
- `zosmxd` -- currently unavailable since CMake for JDK 11 is pending

Discussion: https://openj9.slack.com/archives/C8312LCV9/p1607532450200200
Related: #8878 #11166

### CODE REVIEW

**Comment by sharon-wang** [comment]
FYI @pshipton @llxia

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
lgtm

**Comment by llxia** [comment]
Unless we update [the map](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/openjdk_tests#L12), this will fail. As mentioned in slack, `_cm` can be easily removed (without any other update in the test side), but `<PLATFORM>_mixed` cannot be changed without updating the map.

**Comment by sharon-wang** [comment]
Ok, it seems that it would work to change `<PLATFORM>_mixed_cm` --> `<PLATFORM>_mixed` (removing `_cm` no longer necessary)?

Or, I can update the map if there a preference for a shorter name (i.e. use `<PLATFORM>_mxd`).

**Comment by llxia** [comment]
Also, I forgot to mention there is another map in TKG: https://github.com/AdoptOpenJDK/TKG/pull/129/files
Yes, we have two maps and this yucks. Unfortunately, we are dealing with three names: SPEC, Platform from internal (historical reason), and Platform from Adopt. And it is in our plan to get rid of them and just to have one name. But until then, we have to support this.

Personally, I would prefer to remove `_cm` as it is the easiest (not map update is needed). Plus, we shortened the name in system tests and going to do the same in TKG. If all these do not work, then we can shorten the name and update the maps. Thoughts?

**Comment by pshipton** [comment]
Works for me. We'll try to keep short names in mind for future work.

**Comment by sharon-wang** [comment]
Sounds good -- I've updated the changes to just remove `_cm` from the specs.

**Comment by pshipton** [comment]
Start a build to ensure everything is still parse-able.

jenkins compile aix jdk8

**Comment by pshipton** [comment]
Looks good. I'll stop the build since it got far enough.

**Pull request merged**
