### PR TITLE
Replace CPU APIs on Z

### PR DESCRIPTION
**Pull request by harryyu1994**
depends on: https://github.com/eclipse/omr/pull/5153

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@mpirvu FYI processor detection work on Z (OpenJ9 side)

**Comment by fjeremic** [comment]
I think we'll need to wait for the OMR change to propagate.

**Comment by harryyu1994** [comment]
@fjeremic @mpirvu Could you guys help review this one? This one is the next on the list to be merged. I'm going to perform some tests and let you know the results.

**Comment by harryyu1994** [comment]
Found an zos failure, looking into it.
```
Assertion failed at /tmp/bld_447886/bld_zos_390/compiler/../omr/compiler/z/env/OMRCPU.cpp:99: self()->supports_feature_test(feature)
	feature test 133 failed, _supportedArch 8, _processorDescription.processor 8
```

**Comment by harryyu1994** [comment]
Have some non-gold ARM failures, looking into it. (http://vmfarm.ottawa.ibm.com/build_info.php?build_id=447914)

**Comment by fjeremic** [comment]
Jenkins test sanity zlinux jdk8,jdk11

**Comment by harryyu1994** [comment]
Yeah it looks like the ARM failure is caused by my change. I may need to have access to an ARM machine to debug this.

**Comment by harryyu1994** [comment]
Going to disable the new api initialization logic on ARM for now since I don't have a machine to investigate the issue.
```cpp
 J9::CompilerEnv::CompilerEnv(J9JavaVM *vm, TR::RawAllocator raw, const TR::PersistentAllocatorKit &persistentAllocatorKit) :
+#if defined(TR_HOST_ARM) || defined(TR_HOST_ARM64)
+   OMR::CompilerEnvConnector(raw, persistentAllocatorKit),
+#else
    OMR::CompilerEnvConnector(raw, persistentAllocatorKit, OMRPORT_FROM_J9PORT(vm->portLibrary)),
+#endif
```
We do not have get_processor_description api for ARM/AARCH64 yet, added them in this PR: https://github.com/eclipse/omr/pull/5262

**Comment by harryyu1994** [comment]
Now ARM/AARCH64 tests passed cleanly with the workaround in the above comment. We should be ready to merge this one.

**Comment by harryyu1994** [comment]
Just verified that this change works on all platforms

**Comment by fjeremic** [comment]
Jenkins test sanity zlinux jdk8,jdk11

**Pull request merged**
