### PR TITLE
Add new committer to admin_list.yml

### PR DESCRIPTION
**Pull request by 0xdaryl**
Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@AdamBrousseau : please review.

Presumably, adding @knn-k to this list will give him authority to launch Jenkins PR builds?

**Comment by pshipton** [comment]
Still doesn't seem to work, but we probably need the Jenkins admins to approve it or something.

**Comment by pshipton** [comment]
I found https://ci.eclipse.org/openj9/view/Infrastructure/job/Add-Committer-to-PR-list/ but I suspect it's obsolete.

**Comment by AdamBrousseau** [comment]
In a perfect world, this PR would be all you need. We're not quite there. The job Pete linked was the semi-automated way to do it. That was before we migrated to the new infra. It may still work. I can't see the job configs to know how it works but iirc it does a sed on the PR job configs on disk. There is also a global list in Jenkins config (at least on the previous instance) which only Eclipse admins would be able to see. This list should be updated as well as it would be used for any newly created jobs (provided they are not copied from existing jobs). I can sit with Pete today and get this sorted out.

**Comment by pshipton** [comment]
I've manually added knn-k to the Admin list of all PR jenkins jobs.

**Comment by 0xdaryl** [comment]
Thanks Peter.

**Comment by knn-k** [comment]
I successfully triggered a build in #7993.  Thank you.

**Pull request merged**
