### PR TITLE
Add missing vm access

### PR DESCRIPTION
**Pull request by liqunl**
VM access is required before dereferencing a java object during JIT
compilation. Also check that MethodHandle object is non-null before
folding CollectHandle.allocateArray.

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@andrewcraik May I ask for your review?

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Comment by keithc-ca** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Pull request merged**
