### PR TITLE
Disable JNI specialCasing of java_util_zip_CRC32_updateBytes

### PR DESCRIPTION
**Pull request by dchopra001**
This is a double delivery of #7391

### CODE REVIEW

**Comment by dchopra001** [comment]
@mpirvu

**Comment by mpirvu** [comment]
Jenkins test sanity plinux,aix jdk8,jdk11

**Comment by mpirvu** [comment]
On aix Java8 there is one failure: `jsigjnitest_0`, but it is not related to this PR
```
failed to open </opt/java8_64/jre/lib/ppc64//libjvm.so> - reason: <	0509-022 Cannot load module /opt/java8_64/jre/lib/ppc64//libjvm.so.
	0509-026 System error: A file or directory in the path name does not exist.>
Attempting to open /home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_Personal/openjdkbinary/j2sdk-image/jre/bin/../lib/ppc64/j9vm/libjvm.so
About to invoke JNI_CreateJavaVM with 2 option(s).
Starting test.
Primary handler set.
Secondary handler set.
Raising signal.
Test passed. Both signal handlers invoked.
Internal Error: Failed to initialize redirector - exiting
```

**Comment by mpirvu** [comment]
Since it's not clear at all why the aix test failed I am going to trigger it again.

**Comment by mpirvu** [comment]
Jenkins test sanity aix jdk8

**Comment by dchopra001** [comment]
@mpirvu Tests passed. So this is good to merge.

**Pull request merged**
