### PR TITLE
JIT support for re-sizable SCC

### PR DESCRIPTION
**Pull request by dsouzai**
This had to be reverted in https://github.com/eclipse/openj9/pull/10357 because of failures in JITServer tests. This PR is a cherry-pick of the commits in https://github.com/eclipse/openj9/pull/9772 + one more commit to add support for JITServer

### CODE REVIEW

**Comment by dsouzai** [comment]
@mpirvu could you please review, specifically https://github.com/eclipse/openj9/pull/10369/commits/9dee9eae08b9c44f07abe466faa1fbbfb73e211d. The rest of the commits are simply a cherry-pick from the https://github.com/eclipse/openj9/pull/9772, but feel free to review anyway if you'd like.

fyi @ymanton

**Comment by mpirvu** [comment]
Some sniff tests first
jenkins test sanity xlinuxjit jdk11

**Comment by mpirvu** [comment]
JITServer seems to be working.
Another remark: the name of `TR_J9SharedCache::isPointerInMetadataSectionSectionInCache` has "Section" twice. was that intentional?

**Comment by dsouzai** [comment]
> Another remark: the name of TR_J9SharedCache::isPointerInMetadataSectionSectionInCache has "Section" twice. was that intentional?

Heh no, that was a typo; good catch. I fixed it in https://github.com/eclipse/openj9/pull/10369/commits/7844bedbddc58d86cc41ae081d222aecb7311ff6

**Comment by mpirvu** [comment]
jenkins test sanity all jdk11

**Comment by dsouzai** [comment]
@mpirvu Should be ok to merge now.

**Comment by dsouzai** [comment]
I had a thought regarding JITServer; do we need to do anything to inform a JITServer instance that doesn't have this change that it shouldn't accept requests from a client that does have this change? Otherwise the offsets might be misinterpreted.

**Comment by mpirvu** [comment]
> I had a thought regarding JITServer; do we need to do anything to inform a JITServer instance that doesn't have this change that it shouldn't accept requests from a client that does have this change? Otherwise the offsets might be misinterpreted.

oops, yes in such cases we increment the minor version number:
https://github.com/eclipse/openj9/blob/master/runtime/compiler/net/CommunicationStream.hpp#L105

**Comment by mpirvu** [comment]
jenkins test sanity all jdk11

**Pull request merged**
