### PR TITLE
Double the size of Constant Pool shape description

### PR DESCRIPTION
**Pull request by fengxue-IS**
Expand cpShapeDescription entry to 8 bits
Update JCL constantpool stream constants to match VM size

Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Is there some background for why this change is required?

**Comment by fengxue-IS** [comment]
@fjeremic The vm currently used up all 4 bits to label different constant pool types, this change is to allow adding different types in the future for optimization/type checking

**Comment by andrewcraik** [comment]
@fengxue-IS I would imagine a use for the 5th bit is currently envisioned to motivate this change - what is the motivating use case since growing the structure just to keep a free bit could be counter productive (footprint gain for no benefit)?

**Comment by fengxue-IS** [comment]
@andrewcraik I am currently working on an issue regarding CP consistency checking that would require this change.

**Comment by DanHeidinga** [comment]
@andrewcraik @fjeremic OpenJ9 has historically tracked the CP type based on the invoke bytecode targeting the entry (ignoring splitting entries, etc).  Unfortunately, this is no longer sufficient to pass test cases and match the RI's behaviour.

In particular, we need to check that the CP type is consistent with the type of the method referenced.  

The current CP description doesn't have enough free bits to enable us to mark the entries correctly.  The extra wrinkle in this is the vm uses the cp type to set the initial values for the cp entries - basically to point them at special resolve targets.  Here's where splitting comes back into play - a Constant_MethodRef can be targeted by 3 kinds of bytecodes - invokespecial, invokestatic, and invokevirtual - but with two slot cp entries there is only enough space to store the resolved values for one of special or static.  Without the knowing the bytecode type targeting the cp entry, we can't properly initialize it.

That forces us to grow the description.  Couple that with some the new features coming in later java releases - such as Constant_Dynamic - we'll need to grow that description anyway.

@fengxue-IS's experiments have shown the grow is a very very small footprint hint.  @fengxue-IS Can you provide some of the details of the experiements?

**Comment by fengxue-IS** [comment]
Currently the cpShapeDescription is leaving a footprint on average of 20 - 50 bytes per ROM class, and should be expecting about double this amount after this change.

For an application using around of 500 classes this will be extra 20-40 kbytes of memory

On a larger scale, this should increase footprint by 50 kbytes for every GB of memory used by the VM (normal case)

**Comment by andrewcraik** [comment]
Ok great - thanks @DanHeidinga and @fengxue-IS for the extra information and clarification. It is great to understand the motivation of the change, I have no objections at this time. FYI @mpirvu since he tracks footprint numbers quite carefully in his work on this project.

**Comment by DanHeidinga** [comment]
Jenkins test sanity

**Comment by DanHeidinga** [comment]
@mpirvu FYI - this has been merged

**Pull request merged**
