### PR TITLE
Emit field load instead of call in expanding MethodHandle invoke

### PR DESCRIPTION
**Pull request by liqunl**
Inliner uses bytecode to find the call node to inline for a call target
not from top level. Having a bytecode shared by multiple calls will
cause the inliner to inline a method into a wrong callsite. This is not
a problem now because MethodHandle invoke is inlined at the top level by
targeted inlining that inlines one level each time. With the upcoming
change to inline the whole MethodHandle chain at once, this will become
a problem.

#4837 

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@andrewcraik @cathyzhyi May I have your review?

**Comment by andrewcraik** [comment]
I'm fine with this but would like @cathyzhyi review as well before we look to merge given her expertise in this area

**Comment by cathyzhyi** [comment]
LGTM

**Comment by andrewcraik** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Comment by pshipton** [comment]
Jenkins test sanity xlinux,win,plinux jdk8,jdk11

**Pull request merged**
