### PR TITLE
Preserve vector registers across helper calls on P

### PR DESCRIPTION
**Pull request by gacholio**
Optionally preserve the vector registers in the assembly helpers on
Power. This is controlled by the
J9_EXTENDED_RUNTIME_USE_VECTOR_REGISTERS bit in the J9JavaVM
extendedRuntimeFlags field.

This is #12239 with another commit to fix the problems with the flag test and concurrent scavenge.

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
jenkins test sanity plinux jdk8

**Comment by gacholio** [comment]
jenkins test sanity.system plinux jdk8

**Comment by gacholio** [comment]
jenkins test sanity,sanity.system plinux jdk8

**Comment by gacholio** [comment]
jenkins test sanity.system plinux jdk8

**Comment by gacholio** [comment]
jenkins test sanity,extended,sanity.system,extended.system plinux jdk8

**Comment by gacholio** [comment]
jenkins test sanity,extended,sanity.system,extended.system plinux jdk8

**Comment by gacholio** [comment]
@zl-wang @gita-omr Now passing all CS testing as well. Only the new commit needs to be reviewed.

**Comment by gita-omr** [comment]
Should we run on AIX as well?

**Comment by gacholio** [comment]
I don't think it's necessary but up to you.

**Comment by gacholio** [comment]
jenkins test sanity.system aix jdk8

**Comment by gacholio** [comment]
May as well run the CS tests I guess - I don't think we need al 4 suites.

**Comment by gacholio** [comment]
jenkins test sanity.system aix jdk8

**Comment by gacholio** [comment]
@gita-omr AIX testing has passed.

**Comment by gacholio** [comment]
Can we get this reviewed/merged?

**Review by zl-wang — APPROVED** [review]

**Comment by pshipton** [comment]
In internal testing we're seeing an Illegal Instruction on Power 6 which I tracked to this change. I'm going to revert the change until this can be resolved.

**Comment by pshipton** [comment]
Crash details.
cmdLineTest_J9test_common_0 (NoOptions)
```
Testing: verbose:stack
Test start time: 2021/03/28 13:18:06 Eastern Standard Time
Running command: "/bluebird/builds/bld_468465/sdk/ap6480/bin/java"   -Xdump -cp "/bluebird/builds/bld_468465/jvmtest/test/SE80/functional/cmdLineTests/utils/utils.jar" -verbose:stack VMBench.FibBench
Time spent starting: 18 milliseconds
Time spent executing: 9219 milliseconds
Test result: FAILED
Output from test:
 [ERR] Unhandled exception
 [ERR] Type=Illegal instruction vmState=0x00000000
 [ERR] J9Generic_Signal_Number=00000048 Signal_Number=00000004 Error_Value=00000000 Signal_Code=0000001e
 [ERR] Handler1=09001000A045E0E0 Handler2=09001000A0439E30
 [ERR] R0=0000010010117750 R1=0000010010117510 R2=09001000A0461D10 R3=0000010010117CD0
 [ERR] R4=0000010010177EB0 R5=000000003002BD68 R6=000000003002C000 R7=0000010010117C78
 [ERR] R8=0000010010117C80 R9=0000010010117C70 R10=09001000A043F8C8 R11=0000000000000000
 [ERR] R12=000000002200214B R13=0000010010121800 R14=09001000A043D7A0 R15=0000000030008200
 [ERR] R16=0000000030029700 R17=0000000000000000 R18=0000000030027A20 R19=0000000000000000
 [ERR] R20=0000000000000000 R21=0000000030008203 R22=0000000000020200 R23=000000000001F100
 [ERR] R24=0000000000000000 R25=0000000000000000 R26=0000000030027A20 R27=0000000000000001
 [ERR] R28=000000003002BD68 R29=09001000A043D7A0 R30=000000003002C000 R31=0000000030008200
 [ERR] IAR=0900000000B1005C LR=0900000000B01E7C MSR=A00000000000D032 CTR=0000000000000000
 [ERR] CR=4400214200000003 FPSCR=8202400000000000 XER=0000000382024000
 [ERR] FPR0 0000000082024000 (f: 2181185536.000000, d: 1.077649e-314)
 [ERR] FPR1 0000000082024000 (f: 2181185536.000000, d: 1.077649e-314)
 [ERR] FPR2 0000000082028000 (f: 2181201920.000000, d: 1.077657e-314)
 [ERR] FPR3 402a000000000000 (f: 0.000000, d: 1.300000e+01)
 [ERR] FPR4 4530000000000000 (f: 0.000000, d: 1.934281e+25)
 [ERR] FPR5 412e848000000000 (f: 0.000000, d: 1.000000e+06)
 [ERR] FPR6 43300000000f4240 (f: 1000000.000000, d: 4.503600e+15)
 [ERR] FPR7 4530000000000000 (f: 0.000000, d: 1.934281e+25)
 [ERR] FPR8 be4fe986c8707660 (f: 3362813440.000000, d: -1.486028e-08)
 [ERR] FPR9 bf2ff4c15fd99000 (f: 1608093696.000000, d: -2.438055e-04)
 [ERR] FPR10 402f34a63ff050cc (f: 1072713920.000000, d: 1.560283e+01)
 [ERR] FPR11 3fd55555555450ef (f: 1431589120.000000, d: 3.333333e-01)
 [ERR] FPR12 3c7abc9e3b39803f (f: 993624128.000000, d: 2.319047e-17)
 [ERR] FPR13 405b800000000000 (f: 0.000000, d: 1.100000e+02)
 [ERR] FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
 [ERR] Module=/bluebird/builds/bld_468465/sdk/ap6480/jre/lib/ppc64/compressedrefs/libj9vm29.so
 [ERR] Module_base_address=0900000000AA5000
 [ERR] Target=2_90_20210328_468465 (AIX 6.1)
 [ERR] CPU=ppc64 (8 logical CPUs) (0x3d4000000 RAM)
 [ERR] ----------- Stack Backtrace -----------
 [ERR] sendClinit+0x218 (0x0900000000B01E7C [libj9vm29.so+0x5ce7c])
 [ERR] IPRA.$initializeImpl+0x2b0 (0x0900000000AFE8B4 [libj9vm29.so+0x598b4])
 [ERR] IPRA.$classInitStateMachine__FP10J9VMThreadP7J9Class16J9ClassInitState+0xd64 (0x0900000000AFFA88 [libj9vm29.so+0x5aa88])
 [ERR] initializeClass+0x60 (0x0900000000B005A4 [libj9vm29.so+0x5b5a4])
 [ERR] initializeRequiredClasses+0x68c (0x09000000028E2F90 [libjclse29.so+0x3df90])
 [ERR] standardInit+0x19c (0x09000000028E3A80 [libjclse29.so+0x3ea80])
 [ERR] J9VMDllMain+0x2f4 (0x090000000292EEF8 [libjclse29.so+0x89ef8])
 [ERR] runJ9VMDllMain+0x138 (0x0900000000AB907C [libj9vm29.so+0x1407c])
 [ERR] (0x0900000000AC5C38 [libj9vm29.so+0x20c38])
 [ERR] runInitializationStage+0x210 (0x0900000000AB8D94 [libj9vm29.so+0x13d94])
 [ERR] protectedInitializeJavaVM+0xd80 (0x0900000000AAF604 [libj9vm29.so+0xa604])
 [ERR] (0x0900000000D688A8 [libj9prt29.so+0x528a8])
 [ERR] initializeJavaVM+0x1c8 (0x0900000000AAE24C [libj9vm29.so+0x924c])
 [ERR] J9_CreateJavaVM+0xa4 (0x0900000000ACD2A8 [libj9vm29.so+0x282a8])
 [ERR] JNI_CreateJavaVM_impl+0xa94 (0x0900000000A6B9F8 [libjvm.so+0x269f8])
 [ERR] JNI_CreateJavaVM+0x1e0 (0x0900000000A30BE4 [libjvm.so+0x1dbe4])
 [ERR] InitializeJVM+0xa8 (0x00000100000053AC [java+0x53ac])
 [ERR] JavaMain+0x9c (0x0000010000004360 [java+0x4360])
 [ERR] _pthread_body+0xf0 (0x0900000000515D34 [libpthreads.a+0x3d34])
 [ERR] ---------------------------------------
```

**Pull request merged**
