### PR TITLE
Use FE query to do instanceOfOrCheckcast check on Power

### PR DESCRIPTION
**Pull request by dchopra001**
Signed-off-by: Dhruv Chopra <Dhruv.C.Chopra@ibm.com>

### CODE REVIEW

**Comment by dchopra001** [comment]
The Z instances will be accounted for by: https://github.com/eclipse/openj9/pull/6909/files. The missing changes in power and X are addressed now: 78f732b.

**Comment by mpirvu** [comment]
Compilation errors:
```
../../../../../openj9/runtime/compiler/x/codegen/J9TreeEvaluator.cpp: In function ‘void generateInlinedCheckCastOrInstanceOfForInterface(TR::Node*, TR_OpaqueClassBlock*, TR::CodeGenerator*, bool)’:
../../../../../openj9/runtime/compiler/x/codegen/J9TreeEvaluator.cpp:3877:9: error: conflicting declaration ‘auto fej9’
    auto fej9 = (TR_J9VMBase *)(cg->comp()->fe());
         ^~~~
../../../../../openj9/runtime/compiler/x/codegen/J9TreeEvaluator.cpp:3838:9: note: previous declaration as ‘TR_J9VMBase* fej9’
    auto fej9 = (TR_J9VMBase*)(cg->fe());
         ^~~~
runtime/compiler/CMakeFiles/j9jit.dir/build.make:2421: recipe for target 'runtime/compiler/CMakeFiles/j9jit.dir/x/codegen/J9TreeEvaluator.cpp.o' failed
```

**Comment by dchopra001** [comment]
It looks like the X change was made a few days ago as part of the jitserver merge into master:
https://github.com/eclipse/openj9/commit/b1c11e9c1f3e188ac5ede77532e1fc356c2afd2d.

I'm going to back out the X change then.

**Comment by dchopra001** [comment]
@mpirvu This one is good to merge.

**Comment by mpirvu** [comment]
Jenkins test sanity aix,plinux jdk8,jdk11

**Comment by dchopra001** [comment]
It looks like all the `Build_JDK*` builds failed. I'm unable to open any of the pages though, so I'm not sure why they failed.

**Comment by mpirvu** [comment]
```
10:13:12  In file included from /home/jenkins/workspace/Build_JDK8_ppc64le_linux_Personal/build/linux-ppc64le-normal-server-release/vm/compiler/../compiler/optimizer/InlinerTempForJ9.cpp:46:0:
10:13:12  /home/jenkins/workspace/Build_JDK8_ppc64le_linux_Personal/build/linux-ppc64le-normal-server-release/vm/compiler/../compiler/optimizer/J9CallGraph.hpp:34:101: error: ISO C++ forbids declaration of ‘TR_CALLSITE_TR_ALLOC_AND_INHERIT_EMPTY_CONSTRUCTOR’ with no type [-fpermissive]
10:13:12         TR_CALLSITE_TR_ALLOC_AND_INHERIT_EMPTY_CONSTRUCTOR(TR_ProfileableCallSite, TR_IndirectCallSite)
10:13:12                                                                                                       ^
10:13:12  /home/jenkins/workspace/Build_JDK8_ppc64le_linux_Personal/build/linux-ppc64le-normal-server-release/vm/compiler/../compiler/optimizer/J9CallGraph.hpp:34:101: error: expected ‘;’ at end of member declaration
```

**Comment by dchopra001** [comment]
This is new code that was just merged this morning: https://github.com/eclipse/openj9/pull/7560. There is a dependent OMR PR as well.

We'll have to wait till the changes propagate through in order to launch another build.

**Comment by mpirvu** [comment]
@dchopra001 could you please keep an eye when conditions are right to test and tag me in this PR? Thanks

**Comment by dchopra001** [comment]
@mpirvu Can we try running the tests again?

**Comment by ymanton** [comment]
Jenkins test sanity aix,plinux jdk8,jdk11

**Comment by dchopra001** [comment]
All checks passed. This is good to merge.

**Pull request merged**
