### PR TITLE
Fix unsafeHelper.m4 to use correct mov instruction.

### PR DESCRIPTION
**Pull request by hangshao0**
Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Jenkins test sanity osx jdk8,jdk11

**Comment by DanHeidinga** [comment]
Jenkins test sanity xlinux jdk8,jdk11

**Comment by DanHeidinga** [comment]
Jenkins test sanity win jdk8,jdk11

**Comment by DanHeidinga** [comment]
@hangshao0 Can you port this to the `v0.17.0-release` branch as well?

**Comment by hangshao0** [comment]
> Can you port this to the v0.17.0-release branch as well?

https://github.com/eclipse/openj9/pull/7403

**Pull request merged**
