### PR TITLE
Add MSVS 2017 support for JDK11 and next to Windows platform

### PR DESCRIPTION
**Pull request by vsebe**
- enable VS2017 as toolchain for JDK11
- add MinGW to PATH

[ci skip]

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

### CODE REVIEW

**Comment by vsebe** [comment]
Blocked by https://github.com/eclipse/omr/issues/2885

**Comment by vsebe** [comment]
eclipse/omr#2885 has been closed.
@pshipton are we ready to switch to VS2017?

**Comment by pshipton** [comment]
> are we ready to switch to VS2017?
I believe so, its supposed to work now.

**Comment by vsebe** [comment]
[Windows build](wip_Build-Any_Platform) passed.

**Comment by vsebe** [comment]
Jenkins test sanity win jdk11

**Comment by vsebe** [comment]
Jenkins test sanity win jdk11

**Comment by vsebe** [comment]
@pshipton please review, thank you!

**Comment by pshipton** [comment]
jenkins test extended win jdk11

**Comment by pshipton** [comment]
The failures in the builds are expected and don't appear to be caused by the compiler change.

**Pull request merged**
