### PR TITLE
Consolidate all trace CG options

### PR DESCRIPTION
**Pull request by fjeremic**
See eclipse/omr#5165 for details.

Issue: #9428

### CODE REVIEW

**Comment by fjeremic** [comment]
Depends on eclipse/omr#5165.

**Comment by fjeremic** [comment]
@0xdaryl this is the OpenJ9 piece of the OMR PR. Fairly minimal changes here.

Jenkins test sanity xlinux jdk11

**Comment by PushkarBettadpur** [comment]
@0xdaryl - Based on my attempts, I believe that builds will break without this PR.

**Comment by pshipton** [comment]
What I'd like to see here is a "test sanity all jdk8,jdk11 depends eclipse/omr#master". Once that is passing, we can merge this PR and push the omr level at the same time.

For the time being, I'll disable the scheduled omr build since it doesn't compile.

**Comment by pshipton** [comment]
(even better would have been to test it before the omr change was merged).

**Comment by fjeremic** [comment]
> What I'd like to see here is a "test sanity all jdk8,jdk11 depends eclipse/omr#master". Once that is passing, we can merge this PR and push the omr level at the same time.

This isn't needed because the OMR dependency is a soft dependency. This PR could have gotten merged before the OMR one, however the change doesn't make sense unless we want to go ahead with the OMR piece - something I don't know until committers in OMR review first.

> (even better would have been to test it before the omr change was merged).

I used to do that however I stopped because typically PRs don't get merged without committers requesting some (even trivial) changes, at which point we are just wasting machine resources kicking off builds before all reviews are addressed. But yeah I get the pain. The build breakage is not at all what we want but it is a reality of having one project consuming another and changes getting merged independently.

**Comment by pshipton** [comment]
Even if not necessary, "test sanity all jdk8,jdk11 depends eclipse/omr#master" is essentially an omr promotion build, it allows the tested omr level to be promoted (manually). Otherwise, some level of testing will be done here (I assume), then omr acceptance needs to be re-enabled after this is merged, and then the next time there is an omr change the build will run again and hopefully promote.

**Comment by pshipton** [comment]
So this broke the zlinux builds.

**Comment by pshipton** [comment]
Reverted it. https://github.com/eclipse/openj9/pull/9527

**Pull request merged**
