### PR TITLE
Move dmp for test compilation in all platforms

### PR DESCRIPTION
**Pull request by JennyChenyj**
[skip ci]

Signed-off-by: Jenny Chen <Jenny.Chen@ibm.com>

### CODE REVIEW

**Comment by JennyChenyj** [comment]
Hey @llxia! Thanks for reviewing it!

**Comment by llxia** [comment]
Please create PR in https://github.com/AdoptOpenJDK/TKG

**Comment by JennyChenyj** [comment]
Hey @llxia! This is the link to the pull request in TKG:
https://github.com/AdoptOpenJDK/TKG/pull/11

**Comment by llxia** [comment]
jenkins test sanity xlinux,aix,win jdk8

**Comment by JennyChenyj** [comment]
The change was merged in https://github.com/AdoptOpenJDK/TKG

**Pull request closed without merging**
