### PR TITLE
Reference Linkage_inlines files as appropriate

### PR DESCRIPTION
**Pull request by 0xdaryl**
A few files were missed in the original commit.  Include Linkage_inlines.hpp
in them as appropriate.

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins test sanity all jdk11,jdk8

**Comment by 0xdaryl** [comment]
Jenkins test sanity win jdk8

**Comment by 0xdaryl** [comment]
Jenkins test sanity win jdk8

**Comment by AdamBrousseau** [comment]
Jenkins test sanity win jdk8

**Comment by AdamBrousseau** [comment]
Jenkins test sanity win jdk8

**Comment by 0xdaryl** [comment]
@ymanton , would you mind reviewing and merging this one too please?  I neglected to include a few Linkage implementation files.  Thank you.

**Pull request merged**
